### ISSUE TITLE
Content strategy for fac.gov

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#1000]
## Background
FAC.gov needs to be able 

## Acceptance criteria (We'll know we're done when...)

We have a draft sitemap for fac.gov and a prioritized list of the content to migrate/update.

```[tasklist]
## Tasks

- [ ] ROT analysis of existing content
- [ ] Talk to TTS outreach team to talk about approval workflow.
- [ ] Analyze content currently in PDFs
- [ ] Updated information architecture with notes on what content needs to be on which pages
- [ ] Establish a publishing workflow
- [ ] Prioritized list of content to create/update/migrate

```
## Definition of Done

We have a plan for the the website IA, publishing workflow, and a good idea of the content that is needed for the new site. Which we will likely break out into their own issues or otherwise tracked in another space since github isn't the best place to manage content workflows.

**Comment by jadudm** [comment]
We're effectively doing this. There is more we need to do (process, etc.), but we should ticket that more specifically, and work it into the timeline. Much of this is, in some ways, in flight in other tickets.
