### ISSUE TITLE
Update manifests to be standardized across the environments.

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#1017]
### Description:
Upon removing some of the code in #1005 that removed postgrest and swagger from the fac-prod manifest, there was a discussion about the usage of the multiple manifests across the environments.

### Fix
[deploy-apps.yml](https://github.com/GSA-TTS/FAC/blob/main/.github/workflows/deploy-apps.yml) would contain a new passthrough `--var` for each of the [deploys](https://github.com/GSA-TTS/FAC/blob/cb9d5983205fd5b45fe98048959dd9ec0d2269d3/.github/workflows/deploy-apps.yml#L64-L87) in the context of: 
`--var ENVIRONMENT=${{ env.space }}`

In turn, that would accomplish the following.
- Parameterized and Abstracted code
- Turn 9 (12 after new relic) into 3 (4 after new relic)
- Minimize drift across the 3 environments, having `deploy-apps.yml` calling 1 file, instead of 3 for a deployment in each environment.

This change would turn [manifests](https://github.com/GSA-TTS/FAC/tree/main/backend/manifests) into non-environment dependent manifests, creating the following tree:
```
backend/manifests/ -
| - manifest-fac.yml
| - manifest-postgrest.yml
| - manifest-swagger.yml
| - manifest-newrelic.yml
```
instead of:
```
backend/manifests/ -
| -/{{env}}
| | - manifest-fac-{{env}}.yml
| | - manifest-postgrest-{{env}}.yml
| | - manifest-swagger-{{env}}.yml
| | - manifest-newrelic-{{env}}.yml
```

The code changes would create blocks like this:
```
    env:
      ENV: DEVELOPMENT
      DJANGO_BASE_URL: https://fac-((ENVIRONMENT)).app.cloud.gov
      ALLOWED_HOSTS: fac-((ENVIRONMENT)).app.cloud.gov
      AV_SCAN_URL: https://fac-av-((ENVIRONMENT)).apps.internal:61443/scan
```
instead of:
```
    env:
      ENV: DEVELOPMENT
      DJANGO_BASE_URL: https://fac-dev.app.cloud.gov
      ALLOWED_HOSTS: fac-dev.app.cloud.gov
      AV_SCAN_URL: https://fac-av-dev.apps.internal:61443/scan
```

### Tasks:
```[tasklist]
- [x] Utilize the new manifest structure for swagger
- [x] Utilize the new manifest structure for postgrest
- [x] Utilize the new manifest structure for fac app
```

**Comment by asteel-gsa** [comment]
@jadudm I believe this can be closed out based on the PRs and merge into `main`
