### ISSUE TITLE
Offboarding checklist for Jordan

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1036]
# For everyone

- [x] Remove from [the FAC-team Google Group](https://groups.google.com/a/gsa.gov/g/fac-team/members)
- [x] Remove from [the FAC team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members)

**For designers, also...**

- [x] Remove from active Figma projects

**For engineers, also...**

- [x] Make a PR to [remove the departing team member from the list of developers and managers](https://github.com/GSA-TTS/FAC/tree/main/terraform/management/config.tf) with access to our spaces.

**For product leads/owners, also...**

- [ ] Make someone else the owner of [the various Google Groups in the project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/edit#heading=h.81zynabayrrg) (and remove them)
- [ ] Make someone else the Maintainer and remove the departing team member from [the FAC-admins team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-admins/members) and [the FAC-team team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members).

**Comment by jadudm** [comment]
Closed as done; no Figma access was granted, and no ownership of GGroups/GHub was granted.
