### ISSUE TITLE
Validate UEIs

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#104]
## Background
As a user I can enter an UEI and receive feedback on the validity of the value so that I can be sure I've entered the correct UEI.

**Note** 

- UEIs are [specifically structured](https://www.gsa.gov/about-us/organization/federal-acquisition-service/office-of-systems-management/integrated-award-environment-iae/iae-systems-information-kit/uei-technical-specifications-and-api-information) and maintained by SAM.gov.
- Sam.gov offers an Entity API which may be helpful here: https://open.gsa.gov/api/entity-api/
- We'll need to handle all validation on the backend but, where possible we want to also perform validations as close as possible to data entry.  
  - For example, we can check that an entry is 12 character before a user submits a POST via the frontend.

**Current mock of interface where UEIs are entered**
![Screen Shot 2022-04-05 at 3 23 07 PM](https://user-images.githubusercontent.com/3485564/161833591-1e816616-c3fa-4f90-b4cf-4cec5c376bf6.png)

## We'll know we're done when...
- [ ] When a user submits a UEI not meeting the standards, they receive a helpful error message 

## Tasks
- [ ] Examine spec and identify checks which may be feasible on the client side (Engineering)
- [ ] Propose and implement a layered approach to UEI validation (Engineering)
- [ ] Mock up error states for UEI validation errors (Design)
- [ ] Front end implementation to perform validation and render error message(s) (Engineering)

**Comment by NicholasKramer** [comment]
Sharing our proposed approach to validating UEIs: @Jkrzy and I contemplated a layered approach to UEI validation where we followed the UEI spec to validate locally before verifying with the SAM.gov API.  The following checks can be performed locally, and if they pass, finalize verification by reaching out to the SAM.gov API:

* The Unique Entity ID is a 12-character, alphanumeric value that adheres to the following rules:
* The letters “O” and “I” are not used to avoid confusion with zero and one.
* The first character is not zero to avoid cutting off digits that can occur during data imports, for example, when importing data into spreadsheet programs.
* Nine-digit sequences are not used in the identifier to avoid collision with the nine-digit DUNS Number or Taxpayer Identification Number (TIN).

Any thoughts?  Suggestions?  I'm happy to document this elsewhere if needed.

**Comment by jadudm** [comment]
Makes sense to me. Saves us from sending complete randomness to the API. And, the proposed local checks are light/straight-forward. I don't think this level of decision requires an ADR, if that's part of the question.

**Comment by NicholasKramer** [comment]
With #142, I think we've got a foundation to validate UEI's locally and being work validating with SAM.gov.

I'm going to write a new issue to validate UEI’s with [SAM.gov](http://sam.gov/)

**Comment by NicholasKramer** [comment]
New issue to validate UEI's with SAM.gov: #148
