### ISSUE TITLE
RESEARCH SPIKE: Discovery with agency users (audit resolution officials)

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#105]
**Background**
We dont know enough about the needs of folks who rely on FAC data to resolve audit findings. We need to do some discovery research to understand their needs and how we might meet them in the new FAC. This work will compliment the API user discovery #103. And we are recruiting users for this research via #64.  

**We'll know we're done when...**
- [x] We have conducted research with agency users 

**Tasks**
- [x] Document current IMS screenflow in Figma
- [x] Articulate research qs and design hypotheses
- [x] Write research plan
- [x] (recruitment is covered in #64) 
- [x] Conduct test sessions
