### ISSUE TITLE
Synthesize auditor research

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#106]
**Background**

**We'll know we're done when...**
- [x] We have documented any new user stories
- [x] We have documented auditor user roles, goals, pain points, and needs in the design wiki

**Tasks**
- [x] Set up air table
- [x] Pull quotes
- [x] Tag quotes
- [x] Write up summary
- [x] Write up new needs statements
- [x]  Mel shares with @brentryanjohnson and @sreuber for review. 
- [x] Write up user roles, goals, pain points, and add to the design wiki

**Comment by MelissaBraxton** [comment]
New user needs statements are here in [this sheet](https://docs.google.com/spreadsheets/d/1q6xhXy0NKzMublqtVoVHYUT0s--CTwa8LBmbRqhpFBg/edit#gid=0). I have not crosswalked this with Mural. @jadudm and @Jkrzy would love your thoughts on how you'd like to inventory stories. I love the Mural, but there's a lot of manual work there as the number of stories grows...

**Comment by MelissaBraxton** [comment]
Wiki updated [here](https://github.com/GSA-TTS/FAC/wiki/User-roles-and-key-epics)
