### ISSUE TITLE
Configure apps to use SMTP egress-proxy

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#1070]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** ensure the fac.gov application can deliver notifications from a restricted-egress space
**as a** system architect
**I want** the fac.gov application to use an SMTP relay in a public-egress space for sending mail

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetitive? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 

**Given** I have configured the gsa-fac app to use the smtp credentials provided in the smtp-creds UPSI
**when** the gsa-fac app sends a mail to fac@gsa.gov from test@fac.gov
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] the test mail arrives at in the fac@gsa.gov Google Group
- [ ] the mail appears to be from test@fac.gov
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: N/A
* Engineering shepherd: Bret

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

This helps us meet SC-7, in the same way that the cg-egress-proxy helps with outbound HTTPS connections.

# Sketch/tasklist

```[tasklist]
### Tasks
- [x] Configure GSA SMTP Relay to handle fac.gov domains
- [x] Configure FAC application to use proxy credentials
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by mogul** [comment]
> Configure GSA SMTP Relay to handle fac.gov domains

I've put in ServiceNow request REQ0780052/RITM1084956

**Comment by mogul** [comment]
I put in [a PR that will add the domain verification records to DNS that G Suite wants](https://github.com/18F/dns/pull/644).

**Comment by mogul** [comment]
Just added [a subsequent PR to turn on DKIM for the domain](https://github.com/18F/dns/pull/648).

**Comment by mogul** [comment]
GSA IT says: 

> You should be good to go.  You can have Groups and accounts setup for that domain as well.

I'll work on a test that demonstrates the ACs before we close this.

**Comment by mogul** [comment]
Here's a manual check that demonstrates the domain is configured correctly!
```
$ nc gsa-tts-oros-fac-staging-egress-smtp-proxy.apps.internal 8080
220 smtp-relay.gmail.com ESMTP i81-20020a819154000000b00561e914d467sm127294ywg.3 - gsmtp
HELO fac.gov
250 smtp-relay.gmail.com at your service
```

**Comment by mogul** [comment]
> I'll work on a test that demonstrates the ACs before we close this.

This has been sitting here long enough... The `nc` command above is sufficient and automated tests can be added later if needed.
