### ISSUE TITLE
Create and deploy an SMTP egress-proxy

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#1071]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** enable FAC apps to send mail from a restricted space
**as a** FAC system architect
**I want** an SMTP proxy configured for apps to use that will only allow mail to our upstream SMTP provider.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 

**Given** an `smtp-proxy` app is deployed in the `-egress` space
**And** a network policy enables traffic from `gsa-fac` to the `smtp-proxy` app on port 8080
**And** a USPI containing SMTP creds for the proxy is bound to the `gsa-fac` app
**And** I have `cf ssh`'d into the `gsa-fac` app
**And** I have extracted the SMTP creds from VCAP_SERVICES
**when** I send mail using the extracted credentials
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [x] I can see the mail is delivered to the target address
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: N/A
* Engineering shepherd: Bret

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

# Sketch 

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/cg-egress-proxy/pull/17
- [x] Add SMTP proxy to Terraform module
- [x] Add client test with mocked SMTP server
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by mogul** [comment]
We can [test both sending mail to the SMTP proxy and inspecting for mail delivery to the proxy's upstream using `mhsendmail` and `mailhog`](https://www.atatus.com/blog/a-guide-to-email-testing-using-mailhog/). ([Another post better shows how to use the API for headless testing.](https://jfelix.info/blog/test-your-email-flow-with-mailhog-a-fake-smtp-server#:~:text=and%20text%20content.-,Query%20Mailhog,-Querying%20Mailhog%20is)) Since `mailhog` and `mhsendmail` are simple Go binaries, they're well suited for use with the CF `binary_buildpack`.

**Comment by mogul** [comment]
I also had ChatGPT take a stab at what the SMTP Proxy `nginx.conf` file should look like, and it produced something that looks pretty convincing... Thanks ChatGPT!
![image](https://user-images.githubusercontent.com/47762/236523943-c239f65b-aeb7-4f37-afbd-30d63bd67dd7.png)

Here's that code for someone to start with:
```
events {
    worker_connections  1024;
}

http {
    server {
        listen 80;
        server_name smtp.example.com;

        location / {
            return 301 https://$server_name$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name smtp.example.com;

        ssl_certificate /path/to/certificate.pem;
        ssl_certificate_key /path/to/key.pem;

        location / {
            proxy_pass smtp://localhost:2525;
            proxy_smtp_auth on;
            proxy_smtp_user username;
            proxy_smtp_password password;
            proxy_smtp_capabilities "SIZE 10485760";
            proxy_smtp_starttls on;
            proxy_smtp_ssl_session_reuse on;
            proxy_smtp_timeout 10s;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

```

We should be able to use this with [the `nginx_buildpack`](https://docs.cloudfoundry.org/buildpacks/nginx/index.html). Note however the obstacles to be overcome to get the necessary module installed [noted in the PR](https://github.com/GSA-TTS/cg-egress-proxy/pull/17#issuecomment-1522196686).

**Comment by mogul** [comment]
For future archaeologists: ChatGPT's configuration attempt was laughably awful, but debugging it at least got me pointed in the right direction. Here's a draft I'm working with:

```
{{module "ngx_mail_module"}}

worker_processes 1;
daemon off;
error_log stderr;
events { 
  worker_connections 1024; 
}

# This doesn't check auth and just hardcodes the backend server to use
# This idea came from https://serverfault.com/a/610481
http {
  access_log stdout;
  server {
    listen 9000;
    location = /auth {
      add_header Auth-Status OK;
      add_header Auth-Server smtp-relay.gmail.com;  # backend ip
      add_header Auth-Port   587;                   # backend port
      return 204;
    }
  }
}

mail {
  server_name       mail.fac.gov;
  smtp_auth         none;
  proxy_smtp_auth   on;
  auth_http         localhost:9000/auth;

  server {
    listen {{port}};
    protocol smtp;
  }
}
```

**Comment by mogul** [comment]
Further update: [I couldn't get the example above working, and switched to using the `ngx_stream_module`, and had this working almost immediately.](https://github.com/GSA-TTS/cg-egress-proxy/pull/17#issuecomment-1549022712)

**Comment by mogul** [comment]
Since the module ended up being a generic stream proxy, rather than doing anything SMTP-specific, [I implemented the test using curl and a static app](https://github.com/GSA-TTS/FAC/pull/1156/files#diff-8359bd936ba721dc6e13bbc44344eb58dfdf6701e72f935260e22783ad18f5e6R20).

The referenced PR is ready for review.

**Comment by mogul** [comment]
The merged PR didn't deploy cleanly... Addressing that now.

**Comment by mogul** [comment]
[This PR](https://github.com/GSA-TTS/FAC/pull/1167) should resolve that.
