### ISSUE TITLE
Establish python code quality tooling, configuration, documentation, and implementation

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#108]
## Background
As a contributor to and reviewer of code within this repository I need code quality tooling to run automatically so that I can  focus on functional changes and implementations.

We can break these into separate tasks/issues. For implementation, we'll look to existing TTS documentation and patterns used on previous/current projects for guidance.

**We will implement tooling to cover these areas of python development**
* [x]   Linting with [Flake8](https://github.com/PyCQA/flake8) (#172)
* [x]   Formatting with [black](https://black.readthedocs.io/en/stable/) (#178)
* [x]   Static security scanning with [Bandit](https://github.com/PyCQA/bandit) (#182)
* [x]   Test coverage with [Coverage](https://github.com/nedbat/coveragepy) (#192)
* [x]   Type hinting support, probably using [mypy](https://mypy.readthedocs.io/en/stable/). (#184)

## We'll know we're done when...
- [x] When all of the tools above are implemented, documented
- [x] Tools are able  to be executed locally 
- [x] Tools are executed automatically within our CI pipeline

## Tasks
- [x] For each, add to requirements, propose an initial configuration, add to documentation, add to CI.

**Comment by Jkrzy** [comment]
@tadhg-ohiggins, I'm going to take the linting piece here

**Comment by Jkrzy** [comment]
In today's stand-up, there were no objections to the use of Black and it's default settings.

**Comment by Jkrzy** [comment]
Thanks @tadhg-ohiggins, appreciate you annotating the original issue w/ PRs!  This looks good!
