### ISSUE TITLE
Training and support materials for the GFAC

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1116]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

submitter = auditor/auditee

**In order to** learn how to submit the SF-SAC
**as a** submitter
**I want** support docs and materials.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

**All of these scenarios are in the context of MVP development**. The PO will work with UX, CX researchers and content developers to limit the scope of this work with an eye on an September release.

### Scenario: I am a product owner trying to understand what work needs to be done.

**Given**   I need to plan content development, application documentation, and possible app changes
**when**  I go to do this planning
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] as a PO, I need to know what first-time submitters (possibly under Covid relief programs) will need for support
- [ ] as a PO, I need to know what experienced auditors expect to find for support in the new system
- [ ] as a PO, I need to know *exactly* what information Federal staff *need* to extract, so we can support them in that work accordingly
- [ ] as a PO, I need the Figma designs to be a source of Truth, so we can begin documentation work ahead of implementation
- [ ] as a PO, I need SME engagement with our new design, highlighting where differences are likely to catch the community out
```

The following scenarios are projective, and need curation based on the above research/documentation.

### Scenario: I am submitting the SF-SAC for the first time, and may not do it again.

**Given**   I need to "just do the thing"
**when**  I go to submit
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] as a submitter, I would appreciate step-by-step documentation for this process.
```

### Scenario: I have prepared and submitted many SF-SACs.

**Given**   I have deep experience with the SF-SAC, but not the GFAC,
**when**  I go to submit
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] as a submitter, I need quick reference to specific aspects of the new sheets and forms.
- [ ] as a submitter, I may want to know what is *different* going in, so I can prepare accordingly.
```

### Scenario: I have prepared one or two SF-SACs, and the GFAC will feel very new.

**Given**   I have limited experience with the SF-SAC, but not the GFAC,
**when**  I go to submit
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] 
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] 
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
Closing. Missed the comment previously.
