### ISSUE TITLE
Initial frontend implementation of homepage 

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#114]
**Background**
In 11ty, implement our current mock-up of the FAC front page.

<Insert picture of mock>

**We'll know we're done when...**
- [x] Users can find where they would log in
- [x] Users can understand what the site is for

**Tasks**
- [x] Design refine mocks based on Sprint 1 user research.
- [ ] Design/Content collaborate on error message mocks, attach to issue.
- [ ] Design attach refined most recent mocks to this issue and tag FE/BE re: most recent design/learning for eligibility entry.
- [x] Implement front-end
- [ ] Customer Support documentation regarding this step in the process.

**Definition of done**
- [x] Meets acceptance criteria
- [x] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [x] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [x] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

**Comment by Jkrzy** [comment]
Closed by https://github.com/GSA-TTS/FAC-Frontend/pull/1

**Comment by austinhernandez** [comment]
Just wanted to check in with engineering on this. Is something like this feasible with search?

<img width="1253" alt="Screen Shot 2022-05-13 at 11 00 00 AM" src="https://user-images.githubusercontent.com/23194720/168311614-73c06a4e-f92a-42cf-b189-f829c1c2c63c.png">

**Comment by MelissaBraxton** [comment]
cc: @Jkrzy, @tadhg-ohiggins, and @heymatthenry to weigh in.

**Comment by austinhernandez** [comment]
@heymatthenry — let's just go with this homepage for v1 and what we will show the auditee user group for the next round of usability testing. 

uncertain things:
- the logo is a placeholder cuz idk what this thing is gonna be called
- the navigation is a best guess v2 from the first round shown to users and will be dependent with #147 
- content is really rudimentary, subject to change
- how much of the new search UI do we want to have there if it will take awhile for things to get migrated

the biggest things are:
- it tells users what is fac.gov
- it has the broad strokes CTAs and context
  -  it tells users if you wanna search older entries you have to go to the legacy system
  - release 1 we shouldn't have the search since there will be nothing to search. instead it will direct to the legacy FAC IMS. _but_ once FY21 is in, we can add it! (adding text that's basically like "if you wanna try the new search, its limited and it's below")
  - to submit, you need to login

new developments:
- search is somewhat de-prioritized as it will not have legacy yet.  things are that its important

![Frame 1](https://user-images.githubusercontent.com/23194720/170103429-db13d648-3f09-443f-acf8-a88714bd0836.png)

Here is the screen in figma:
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2721%3A12813

**Comment by heymatthenry** [comment]
@petermarks-gsa FYI for QA purposes, the V1 homepage won't have the search/filter functionality, hence what's implementened in GSA-TTS/FAC-Frontend#21 doesn't match the screen above in that one regard.

**Comment by petermarks-gsa** [comment]
@heymatthenry This is ready to close now that https://github.com/GSA-TTS/FAC-Frontend/pull/21 has been merged?

**Comment by heymatthenry** [comment]
@petermarks-gsa As far as I'm concerned! If/when we ever revisit the filters etc. We can start a new issue.
