### ISSUE TITLE
Refactor schemas in-tree and in-situ

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1140]
### Tasks

First set of related work:

```[tasklist]
- [x] Get all of our schema-related work into one place in the tree. #1150
- [x] Create base, atomic types (e.g. `string`, `integer`) to build off of. #1163/#1165
- [x] Create compound types (e.g. `string_or_null`) for use. See note number 2. #1163/#1165
- [x] Do not use union types that have `NULL` as a component as base types anywhere (e.g. do not build objects off of `string_or_null`). #1163/#1165
- [x] Integrate refined checks for complex data (e.g. use new/revised/refined UEI check). #1163/#1165
```

The following tasks are more appropriately tackled once we have a solid base from the first set:

```[tasklist]
- [ ] Look at fields that might have standards, and move to standards. Note number 3. #1180 
- [ ] Update random tests to include some targeted tests. For example, we have some random tests for phone numbers, etc., against our regexes. I think we should instead try and do a few targeted edge tests. The fuzz tests are fun (and can be kept), but they're not as useful as checking the boundaries (as best we can) on our regexes (for example). #1181 
- [ ] Walk every field and verify where `null` is, or is not, allowed/appropriate. See note  number 1. #1182 
- [ ] Make sure all lists are complete/correct (e.g. state abbreviations currently seem to exclude the territories?) #1180
```

Notes:

1. I would prefer to never allow null. I would prefer types that were of the shape `UEI_or_NA`. That is, I would like to move to a world where every field *always* has an input. There may be exceptions... for example, the second address line in a two-line address. However, at that point, we should probably assert that *at least one* of the two address fields **must** have a string value. Further, do address fields have a minimum length? What is the shortest valid entry in an address field? (*How many angels can dance on the head of a pin*, while we're at it.) Although pedantic, I think I would rather people submit helpdesk tickets where we discover, in practice, that our typing is *too robust*, and we have to relax it, than to have typing that is *too lax*, and we end up (quietly) with data that we validate, but wish we hadn't.
2. We can automate this in the library. I'm OK with creating a list of types that we want `_or_null`, writing a small function to map over that list, and it returns an object that creates the compound types for all of them. In fact, that would be a good idea. That said, I'd also like us to minimize use of `_or_null` types throughout the schemas.
3. Phone numbers are governed by the E164 standard. Census stores the phone numbers as 10-digit integers. We should store them as strings, and we should store them against the E164 standard. Why? Because if (big if) we ever have to handle international numbers, I want our validation to work. (It also opens the door to having *warnings* at some point... but, our schemas are not ready for that.) This (along with zip codes) is one of the only examples I have right now of this, but... we should look at each field, and ask "does this have a standard, and can we conform to it?"

**Comment by tadhg-ohiggins** [comment]
Related: we should put data that we use for tests/fixtures/mock data/etc. in one place—for example https://github.com/GSA-TTS/FAC/blob/main/backend/cypress/fixtures/sac-report.json is a good basis for a lot of non-Cypress uses (so should probably be somewhere else) and should probably be the basis for tests like https://github.com/GSA-TTS/FAC/blob/main/backend/api/test_views.py#L792

Otherwise the number of places we need to update whenever we make a schema change is awkward.

**Comment by tadhg-ohiggins** [comment]
Schema reorganization approach will be to use these for source files:

*   `backend/schemas/source/base` for Jsonnet shared files
*   `backend/schemas/source/sections` for all Jsonnet SF-SAC sections
*   `backend/schemas/source/excel` for Jsonnet templates specific to Excel
*   `backend/schemas/source/data_distro` for Jsonnet historical data schemas

And these for JSON output from Jsonnet:

*   `backend/schemas/output/sections` for JSON SF-SAC
*   `backend/schemas/output/excel` for JSON Excel templates
*   `backend/schemas/output/data_distro` for JSON historical data schemas (if needed)

Also, for all data for testing or mocking or development, etc., we’ll use:

`backend/data_fixtures/[purpose]`, e.g. `backend/data_fixtures/cypress`

**Comment by jadudm** [comment]
As a todo (noting it here) we want to revisit our list of states and make sure it is a complete set of states and territories. To be picked up in the future work/field-by-field.
