### ISSUE TITLE
the `vw_auditee` view incorporates 2023 data

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1146]
6/20/23: #1282 is likely a better/more refined ticket? This is based on what was learned at the end of the week ending 6/16.

The parent issue (#1170) covers the background for incorporation of 2023 data in the API views and, more broadly, search.

### Tasks

```[tasklist]
- [ ] ~~Develop a data dictionary (GSheet) mapping AY23 fields (JSON) to AY22 (view) fields.~~
- [ ] ~~Implement `select` statement that, alone, does the correct `select` against AY23 and constructs a result set that matches the set in the AY22 data.~~
- [ ] ~~Give the AY23 `select` [statement a name](https://stackoverflow.com/questions/56872965/how-to-give-select-query-a-name-in-postgres)~~
- [ ] ~~Present the AY23 statement as a view (e.g. `vw_auditee_2023`), and run the regression tests against it~~
- [ ] ~~Give the data distro `select` statements names~~
- [ ] ~~`UNION` the select statements for AY23 and AY22 as a single view `vw_auditee`~~
- [ ] ~~Run the regression tests against `vw_auditee` in its new, combined form~~
- [ ] ~~Make sure that the `is_public` flag is honored for all AY22 and AY23 queries.~~
```
- [ ] Define a dictionary mapping JCM to [BRM](https://github.com/GSA-TTS/FAC/blob/main/backend/data_distro/models.py) 
 > ```[tasklist]
> - [ ] Agency model is mapped
> - [ ] Auditee model is mapped
> - [ ] Auditor model is mapped
> - [ ] FindingText model is mapped
> - [ ] Finding model is mapped
> - [ ] FederalAward model is mapped
> - [ ] CapText model is mapped
> - [ ] Note model is mapped
> - [ ] Revision model is mapped
> - [ ] Passthrough model is mapped
> - [ ] General model is mapped
>  
- [ ] Define an ETL to process JCM into BRM using the aforementioned dictionary as a reference.

**Comment by pluribus-tony** [comment]
Here is the google sheet that I have started: https://docs.google.com/spreadsheets/d/1GoVm21SMOSgNaXTUVHC-qQVRk9gsX0Mt5BU7kgNw_no/edit#gid=472641333

**Comment by JeanMarie-TTS** [comment]
@jadudm , we have master tables in Census for entities like audtees, auditors, etc. But G-FAC only stores SF-SAC and associated info like general-info and federal-awards. If you query the consolidated vw-auditee view, we will return one row for all submissions up to AY22 and one row each for every submission from AU23 - which seems incorrect. 
Do we need to de-duplicate an auditee from multiple submissions? How does C-FAC do this today?

**Comment by jadudm** [comment]
1. Taking your last question first... I have no idea how CFAC does anything (internally). We only have the publicly exported data. In studying that data, it is clear that they replicate auditee information in every row of the `gen` table export. We can re-visit LY's ETL for import, but I think she is attempting to consolidate the auditees by de-duping those rows. 
2. Should we dedupe? I see... that this rapidly gets us into our own ETL space with the 23+ data. For example, an audit may include many auditees, but we're going to end up with that data embedded in a JSON object in a column representing a workbook. Therefore, there may be multiple elements of a JSON array that are (essentially) duplicate auditees, or multiple occurrences of an auditee across workbooks. We can either do that de-dupe at time of submission, or it is a post-processing step, which begs an ETL pipeline. 

I'm going to pause and *sigh* for a moment. 

I'll continue numbering things to make it easier to reference.

3. Every one of our auditees should have a UEI associated with them. (Is that true in workbooks as well... I have to look at the XLSX templates again...) This suggests that we should be able to determine uniqueness of auditees more easily than was done in 22- data. (22- meaning "data from 2022 and prior," whereas 23+ meaning "data from 2023 and beyond.") However, it does still suggest that we have... it is possible that, when we do a submission of a form, we could have another mapping that gets applied. Currently, we map into a JSON object. We could apply one more mapping, dependent on the form being submitted (e.g. keyed off of the workbook template name, so to speak) that then hits the JSON object that is inserted (because it would have been validated at that point), and we could rip data out to create *yet another table* (or object) that represents (say) an auditee. This would allow us to set some uniqueness constraints, and really, it should "just" be a bunch of UEIs. 
4. I'm beginning to believe we need to cache SAM.gov data. (See #1191 as a starting point. It's not a fully worked up ticket yet. We may not need/want to cache login.gov data, for many reasons.) This would mean we're caching the info about the auditee, and then would have a way to grab what we need given a UEI. 
5. Also, this will likely be important for crosswalks... we will, at some point, need to go from UEI23 (the UEI in 2023) to UEI22 to EIN22 to EIN21- (the EIN in 2021 and back).  Otherwise, we'll have no way of knowing that an auditee (for example) in 2023 was the same person in 2022 as they were in 2021, but once we go pack 2022, we lose UEI, and therefore can no longer connect the dots. This matters to the AROs and IGs.

I don't know if I answered anything... but, yes. Our data model is form-centric, and our nascent API has some agglomerations that suggest a bit of post-processing. Lets keep talking and decide if there's a path-of-least-work/least-resistance that moves us forward in the first instance.

(This is why I wanted to be doing this work sooner rather than later... I was afraid there would be some complexities along the way. Better now than September.)

**Comment by jadudm** [comment]
I know this is inefficient...

Can we do that aggregation, for the moment, as a `select` across our existing objects, and get a set of unique auditees that way?

**Comment by JeanMarie-TTS** [comment]
I created a new django app called dissemination to hold data model and views for postgrest. It seems easier to borrow from data-distro than to directly edit it as we move to a simplified model.

**Comment by jadudm** [comment]
Closing this ticket; it is mentioned/tracked from #1282, which is simpler and more to the point, now that we've seen the schema and (closer-to) raw data from Census.
