### ISSUE TITLE
Spike use of api.data.gov from frontend for search

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1149]
### Tasks

```[tasklist]
- [x] Get an API key, get it approved
- [ ] Demonstrate a basic API search against agency and program number (e.g. 42 and 123, being 42.123)
- [ ] Present a list of audits (record number, UEI, link to PDF, link to XLSX)
```

For the spike/pilot, it doesn't matter what you return from the `vw_general` view. PDFs are not yet in the DB, and XLSX docs don't exist for 2022 and back. (O_o) So, there's some thinking we need to do regarding consistency between 2023 and 2022 and back.

For now, mock against api.data.gov, but assume the query URLs that you use will ultimate be routed against our Django instance, and then be rewritten (in the backend) to use api.data.gov with a key.

**Comment by JeanMarie-TTS** [comment]
@jadudm Question:
If Search is going to be routed through the django app, can't the django app query postGREST directly? What ae the benefits of having the django app go through api.data.gov?

**Comment by jadudm** [comment]
Hm. Good question.

I'll leave this to @timoballard and @jperson1 to answer/make recommendations. 

On one hand, using api.data.gov means that we're using *the same* pathway as all of our users. In this way, our implementation of search takes no shortcuts, and we know that the API "works," as it will have to work for (say) HHS, Americorps, or any other groups consuming the data via API.

On the other hand, we would save some routing/network time.

I... like the idea of using the same path as our users. That said, I think hitting the container "next door" in our stack makes sense, and we aren't cheating *much* in terms of dogfooding. 

If @timoballard or @jperson1 have opinions, I'd love to hear them.

**Comment by jperson1** [comment]
The biggest benefit of going through api.data.gov rather than PostgREST is, in my opinion, keeping exactly the same results in a search on the frontend or a separate API call. On a previous project, we called them "super users," basically API-savvy individuals at other organizations, that may want `api.data.gov/.../query` to return exactly the same results as we would see on the front end at `fac.gov/search/query`. This can be beneficial if/when we're implementing "export search results to csv/xlsx/pdf," or something similar.

Feels like I am just saying "I agree with Jadud" in a long form and less nicely written format, but still.

**Comment by JeanMarie-TTS** [comment]
@timoballard should we create another django app, say search, that will route requests related to user search to postgREST?   I would like to have a place to create tests for our api views and have these tests go through postgrest to the database.

**Comment by jadudm** [comment]
I think we've captured some of this in an expanded version of the search ticket.

We'll have a view to receive the search object inputs, and a Django view will handle that work of talking to PostgREST. So, there should be a good surface to:

1. Write tests in the form of "search objects"
2. Pass it to the view
3. Compare the result to a known/expected result.

"Search objects" meaning "an object representing the state of the search form."

I'm going to close this ticket, and reference back to it from #1170.
