### ISSUE TITLE
Statically render the API docs

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1153]
The API is currently rendered via a Swagger container. We'd like to drop that container; it's a big moving piece for what it does.

The API docs will be locked behind an API key. (api.data.gov) So, we should probably have them stuffed into the static site.

For now, the issue isn't "how to automate," but just "how can we run a command to output a static rendering of the API docs from a locally downloaded API JSON spec and have it appear in our standard template."

### Tasks

```[tasklist]
- [x] Download the API JSON spec (`curl -OL https:/api.data.gov/.../?api_key=...`)
- [x] Pick a tool to render the API docs (Swagger, redocly-cli, etc.)
- [x] Wrap it in a site template
- [ ] Document it.
```

It is just fine for this to be a manual process for now. Whether we later make it part of a build, etc. is for later. This is a first-step, get the docs out of a living containerized process, and make the slow-moving/slow-changing docs static and part of the site.

**Comment by jadudm** [comment]
Considering this done, until we investigate new/better ways to acheive the same.
