### ISSUE TITLE
Restrict the api.data.gov -> postgrest pathway

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1155]
### Tasks

```[tasklist]
- [x] Add relevant SQL to migrations to configure PostgREST to use JWT tokens.
- [x] Generate a long-lived token (with potential future rotation)
- [x] Add JWT header and token to api.data.gov endpoint
- [x] Disable public access on the PostgREST instance.
```

OR

```[tasklist]
### Tasks
- [ ] Lock down (via TF/CF/ingress) the PostgREST instance so it only accepts connections from api.data.gov
```

**Comment by JeanMarie-TTS** [comment]
@jadudm  Some thoughts on implementation:

1. The token can be manually generated, updated in api.data.gov by a FAC admin, maintained as a secret in the FAC github repo.
2. We should use Terraform to set up postGREST with the token and the configuration to restrict access based on the use of the token.
3. Not sure why we need any SQL to set this up.

**Comment by jadudm** [comment]
1. Yep. Agreed.
2. Yep. Agreed.
3. Is JWT enabled out-of-the box on PostgREST? I may be confusing this with implementing **basic auth** in PostgREST, which requires setting up a table, and doing a bit of SQL wizardry.

That said, we do still need to create a user. For example, even the `anon` user in PostgREST does not exist out of the box; you have to `GRANT` privs and set escalation pathways from the authenticator to the anon user, as well as pass in (as an environment variable) what Postgres (note the lack of a `t`) user will be treated as the anonymous user. In other words, PostgREST only does for us what we grant it permission to do.

In this regard, checking the docs, and adding the relevant migrations to the PostgREST stand-up procedure (which will probably be in `data_distro`) feels necessary in order to get JWT tokens working. For example, we'll need an `api_gov_user` that `authenticator` can become as part of the PostgREST authentication process. But, as you say, once we do that, we can then put the token in the GH secrets, pass them to the container, and put them in `api.data.gov`. 

(The JWT token, I *think*, needs to be passed to Postgres as well, and PostgREST then picks it up from there. So, again, PostgREST is doing as little for us as possible, in the name of security, and forcing us to actively set configuration before it makes things happen.)

**Comment by mogul** [comment]
@jadudm what more needs to be done here?

**Comment by danswick** [comment]
I believe this was resolved with https://github.com/GSA-TTS/FAC/pull/1663
