### ISSUE TITLE
Ensure general web hygiene on static site & application

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#1160]
### Tasks

```[tasklist]
- [x] Ensure all pages have meta descriptions
- [x] Ensure all pages have meta titles
- [ ] Confirm buttons are labeled as buttons
- [ ] Validate alt text for buttons
```

**Comment by jadudm** [comment]
Buttons are not anywhere near the roadmap at this point. We'll pick it up when we actually have buttons.
