### ISSUE TITLE
Epic: Search

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1170]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** search for previously completed audits
**as a** user of the FAC 
**I want** to be able to search for audits.

# Acceptance Criteria

ARO = Audit Resolution Official (Federal employee at an agency)

### Scenario: An ARO is looking for  prior audits 

**Given**  that I have a UEI in hand 
**when** I search for that UEI
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] https://github.com/GSA-TTS/FAC/issues/1231
- [ ] https://github.com/GSA-TTS/FAC/issues/1233
```

Some of the design/UX work is detailed in #1148. We're closing that ticket for now, but also know we need to refine the above items; 1148 will be reflected in that work. 

### Scenario: A back-end engineer is supporting search implementation

The backend integration will work via communication with the Postgrest API—not using internal Django access to the database.

```[tasklist]
### then
- [ ] as a backend engineer, implement a proxy URL for the front-end to query.
- [ ] as a backend engineer, connect the proxy URL to the Postgrest server. (Essentially `djangoappurl.gov/api/query/postgreststuff` -> `postgrestserviceurl.whatever/postgreststuff`)
- [ ] as a backend engineer, work with the front-end engineer to implement new queries as needed to support the front-end implementation.
- [ ] as a backend engineer, work with the FE engineers/design to present the Search page
- [ ] as a backend engineer, work with the FE engineer to implement a view(s) for supporting the query process
```

### Scenario: backend/frontend engineers are trying to make search "just work"

```[tasklist]
### then...
- [ ] the frontend bundles up the search and filters as an object to send to the backend; this is a "plain Django form submission"
- [ ] the backend pulls this object apart, and does the query(s) that are necessary against PostgREST to build up a result set
- [ ] results are passed back to the FE for display. Pagination... exists within PostgREST, therefore should be implemented transparently to leverage that functionality. (Track pagination in the FE; it should be passed as part of the query object)
- [ ] fe/be and design must design a result set object that allows for population of result set cards in the UI
```

See also #1149 for some conversation that pertains to the above items (in particular, w.r.t. testing and how Django will interact with the FE and PostgREST.)

### Scenario: A data engineer is supporting search implementation

```[tasklist]
### then
- [ ] https://github.com/GSA-TTS/FAC/issues/1146
- [ ] the `vw_note` view incorporates 2023 data
- [ ] the `vw_federal_award` view incorporates 2023 data
- [ ] the `vw_passthrough` view incorporates 2023 data
- [ ] the `vw_revision` view incorporates 2023 data
- [ ] the `vw_cap_text` view incorporates 2023 data
- [ ] the `vw_findings_text` view incorporates 2023 data
- [ ] the `vw_auditor` view incorporates 2023 data
- [ ] the `vw_general` view incorporates 2023 data
- [ ] the `vw_findings` view incorporates 2023 data
```

Copy/paste #1146 as a template for each of the above as needed if a breakout is desired for work tracking.

### Scenario: A test/QA engineer is looking at all of this and sees a mountain of work. 

```[tasklist]
### then 
- [ ] as a QA engineer, meet with design, FE, BE engineers to understand what the "happy path" for testing search might look like
- [ ] as a QA engineer, draft a GDoc in the Engineering part of the project folder for what the testing plan will be, and discuss with the PO
- [ ] as a QA engineer, develop a testing ticket that documents the testing strategy for this work and steps to carry it out
- [ ] as a QA engineer, request any additional support for that testing work, or make sure the testing is integrated in the individual workstreams
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

## Frontend thoughts

The purpose of this increment is to have a minimally viable search interface. If it only has one filter (e.g. search by UEI), then that is great.

![search-interface-sketch](https://github.com/GSA-TTS/FAC/assets/38290/5fc37f68-b83d-4e78-9dbb-17e06faa25ed)

Unless an easier-to-implement interface is proposed, we'll go with a popular bookstore layout, and put filters on the LH side (A, above) and results in the main body of the page (B, above).

Search results should have enough information for an ARO to determine if the result is useful to them. A result should also link to the PDF of the report as well as a "summary page."  We will not link to the XLSX uploads at this time.

![search-result-sketch](https://github.com/GSA-TTS/FAC/assets/38290/21dcb044-2868-4e19-a28f-3fe47e327102)

The summary page is the contents of the SF-SAC. The CFAC would generate a workbook on the fly with this information; we will have a templated HTML page that provides the content of the SF-SAC, which people can then print to PDF. This "summary page" will need to be designed; it should be a complete dump, in so many words, of all of the contents of the SF-SAC. (In short, we are converting our XLSX workbooks into a document.)

This section should be updated as higher quality sketches become available.

## Backend support

To support the search, we'll do the following:

![backend-flow](https://github.com/GSA-TTS/FAC/assets/38290/161eb2db-58ac-4715-b460-2635307e50ee)

The frontend will query the app (e.g. `local/query`, **C** in the image above). Queries will be expressed as if the query was being run against `api.data.gov`. That is, the query will be written as if it were a PostgREST query against our existing views. 

The app endpoint is, in so many words, a proxy. It will rewrite the query, and in doing so, attach the `X-API-key` header that api.data.gov expects (**D**, in the image above). This way, the FE does not need to think about how to manage that protected access; the backend can do that work.

We are *not* implementing the queries in the backend; we are proxying the queries through to api.data.gov. In this regard, our frontend search is using the same API that our partners are using (**E** in the image above, kinda-mostly). If we need to extend the API to support the frontend, then we will do that.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no more security concerns here than anywhere else in our application. Because our query interface is routed through PostgREST, we gain a lot of protections (e.g. from possible SQL injection attacks, etc.), and therefore are in a robust space for search implementation from a security perspective.

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] a thing
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by danswick** [comment]
This is now tracked as the somewhat confusingly-named "data increment 1" epic 👉  https://github.com/GSA-TTS/FAC/issues/2236
