### ISSUE TITLE
Record PDR for whether to continue to require EIN  or replace it UEI before users can create a new audit record in the DB

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#119]
**Background**
To create a new audit, users need to specify which entity it is attached to it. Basically, they enter an ID, which pulls up a list of entities attached to the ID in a database, and then they choose/confirm that the ID matches the entity they intend before they can create a new audit record.  

Currently, they enter EIN and its validated against the FAC legacy DB. Users select from entity names associated with the EIN in the DB. 

We want to know whether it'd be preferable, from both a data and a UX perspective, to ask folks to enter UEI and have that validated against the sam.gov DB / have them select from entities listed in sam.gov instead. 

**We'll know we're done when...**
- [x] We have an PDR that clearly documents this decision

**Tasks**
- [x] Write up possible approaches and pros/cons of each 
- [x] Submit DRAFT PDR for discussion
- [x] Discuss! Decide!
-[ ] Finalize PDR in GitHub

**Comment by Jkrzy** [comment]
Closing this w/ merge of #120
