### ISSUE TITLE
MVP Debt Tracking

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1200]
# What is this?

As we proceed, we are engaging in new implementation as well as test development and bug fixes. That said, we are also, in places, accruing new "debt." That is, we're doing *minimal viable* implementations in some cases, which suggest that there is more to be done in order to move pas the *minimum* qualifier.

This is a living, working ticket for tracking where we see/think there is work still to be done. We will work some "paydown periods" into our dev cycle as we move to MVP. 

```[tasklist]
- [ ] #1191: I think we are going to need to cache some of the SAM.gov data. This is both because I'm worried about API limits, but also because I think we're going to need it for crosswalks. 
- [ ] #1190: We have initial validations in place for many of the SF-SAC elements. In doing this work, we discovered places where we can refine our validations. For example, we have a goal of having *no `null` values allowed in submissions*. We may not be able to achieve that goal, but we believe that requiring intentional, validated inputs will raise the quality of the data collected (e.g. explicit `N/A` in places rather than allowing `null`). 
- [ ] #983: We have a list of data integrity items that we need to visit individually, and make sure that we are addressing them, or if we are not, being clear why we are not/are unable to as part of MVP.
- [ ] #1175: We have some missing summations in one of the sheets. It is not a data collection item, but if we include the summation in the workbook, it will simplify some things about collection. Or, we can do the summations in the backend. Either way, we need to look at this.
- [ ] #1201: After implementing the automation to rapidly deploy from dev to staging, further enhancements may be beneficial to our deployment cadence.
- [ ] #1043: We need to refine the certification workflow from a UX/flow perspective, and bring it together with the new "audit progress" page. 
- [ ] #1213: We need to modify the pre-screener to offer a warning when someone attempts to submit another audit for a given (UEI + Audit Year) combo.
```

**Comment by danswick** [comment]
Everything here is done or consolidated under an epic.
