### ISSUE TITLE
Require UEI for submission

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1203]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** submit the SF-SAC
**as a** submitter
**I want** <strike>MY MTV</strike> to be <b>REQUIRED</b> to have a valid UEI in hand.

We have moved, with [PDR 0008](https://github.com/GSA-TTS/FAC/blob/main/docs/product/decisions/0008-P-uei-required.md), to a UEI-required stance. This ticket tracks the work of making sure our system implements this decision record.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: An auditor/auditee is creating a new audit.

**Given**   that the UEI is required
**when**  we ask for that UEI
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] the UEI is requested of SAM.gov, and appropriate success/error messages are passed to the frontend
- [ ] if the UEI is found to be in error (does not  match pattern validation), the user is asked to check their UEI and try again.
- [ ] if the UEI is found not to be present in SAM.gov, the user is asked to check their UEI and try again, with a limited (3?) number of retries
- [ ] if SAM.gov is not present/down, the user is alerted to the fact, and asked to try again later. 
```

Although the ticket is incomplete at the time of this initial authoring, see #1191 regarding caching of SAM.gov information. 

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

We know of no security implications to requiring the UEI. Access/use of SAM.gov is already documented within our SSPP.

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] 
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by heymatthenry** [comment]
@Leighdiddy @jadudm couple of questions about this part of the form: 

![Image](https://github.com/GSA-TTS/FAC/assets/6290/9d771ba0-8cc7-4740-9bf1-b19f7c4e147c)

1. At one point in the saga of this form, we assumed the auditee name would have to come from SAM.gov, and so we opted to make that form field just plain, un-editable text on the page. At the time we figured it would be unnecessarily confusing to have a disabled form field that wouldn't ever actually become editable. Since we're back in that situation (either we successfully communicate with SAM and get the auditee name or we tell the user they can't proceed), can I go back to just making this text rather than a form field?
2. I'm going to remove the red text since that's not a thing that can happen anymore. Ok this one wasn't a question.

**Comment by jadudm** [comment]
1. Just make it text. We want to use the authoritative source for that information.
2. Yep. Definitely not a question. :smile:
