### ISSUE TITLE
Epic: Cognizance and Oversight Assignments and Display

### ISSUE THREAD

**Issue by Carley-Sullivan** [GSA-TTS/FAC#1218]
This epic tracks how we'll handle the process of assigning cognizance to a given audit and, once established, how to communicate and display that information via the FAC app. 

### Tasks

```[tasklist]
- [ ] https://github.com/GSA-TTS/FAC/issues/1462
- [ ] https://github.com/GSA-TTS/FAC/issues/1463
- [ ] https://github.com/GSA-TTS/FAC/issues/1464
- [ ] https://github.com/GSA-TTS/FAC/issues/1534
- [ ] https://github.com/GSA-TTS/FAC/issues/1699
- [ ] https://github.com/GSA-TTS/FAC/issues/1738
- [ ] https://github.com/GSA-TTS/FAC/issues/1762
- [ ] https://github.com/GSA-TTS/FAC/issues/1811
- [ ] https://github.com/GSA-TTS/FAC/issues/1812
- [ ] https://github.com/GSA-TTS/FAC/issues/1813
- [ ] https://github.com/GSA-TTS/FAC/issues/1887
- [ ] https://github.com/GSA-TTS/FAC/issues/1986
- [ ] https://github.com/GSA-TTS/FAC/issues/2022
```

### Open questions

- Will we need to notify agencies when they've been assigned to an audit?

**Comment by Carley-Sullivan** [comment]
I'm just gonna leave this here:

https://docs.google.com/document/d/1_8xB7JG-Yk7HDx12NSHCpO_GmbZMs07IslRl6m9u-5A/edit

**Comment by JeanMarie-TTS** [comment]
@Carley-Sullivan , in the C-FAC are these assigned manually by someone? Or does the system do this automatically using the info in the doc you've included?

**Comment by Carley-Sullivan** [comment]
In general, the system automatically looks at the data provided on the form, and determines what agency will be the cognizant or oversight. However, if the assigned agency disagrees with the assignment and another agency agrees to take it over, then there must be a way to change it manually.

**Comment by jadudm** [comment]
I'm putting this in the ETL milestone, which isn't 100% correct. However, it is something we do "at the end" of the process, after the data is validated. We need it for MVP, and it is *kinda* related to ETL. So, it goes in the ETL milestone *for now*.

**Comment by gsa-suk** [comment]
<img width="1130" alt="Screenshot 2023-08-02 at 12 49 32 PM" src="https://github.com/GSA-TTS/FAC/assets/135276194/a97069a6-006a-4f2c-aa37-2f5fc26b5828">
Flow chart from Carley.

**Comment by gsa-suk** [comment]
Database analysis, cog / over algorithm test results with 2022 data and algorithm update details are in:
https://docs.google.com/document/d/1SaBRMdr7HsHqHuDZ98oxsJOvQGQPlYjEmk7Zhky8mXM/edit

**Comment by gsa-suk** [comment]
Carley's updated flowchart:
https://app.mural.co/t/gsa6/m/gsa6/1688072157586/bacad68ed1da8805af45e5b7d89a07451e930d69?sender=644512a6-7f18-466d-b508-8716835c88dd

**Comment by jadudm** [comment]
This work has landed in `main`. There will be follow-on tickets, as the administrative side will require both policy and technical work. The work to calculate, assign, and disseminate cog/over is done, and an initial tool to do reassignments exists. Calling this epic "closed," and future work will be in smaller epics/increments.
