### ISSUE TITLE
Confirm eligibility at start of new audit submission

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#122]
**Background**

Eligibility confirmation is currently mocked as a single page. It covers the following stories:

1. As an auditor or auditee creating a new audit, I need to check that audits are required for my entity type so that I can determine whether my entity is required to submit an audit.
2. As an auditor or auditee creating a new audit, I need to check that my entity spent at least $750K in funding during the audit period so that I can know whether I need to proceed.
3. As an auditor or auditee creating a new audit, I need to check that the audit is for a US based entity so that I know whether I need to proceed.

**We'll know we're done when...**
- [x] When a user can complete input valid criteria and move forward to create a new audit.
- [x] When the API can accommodate this data and store it to the backend.
- [x] When the schema/backend is ready for receipt of this data and can associate it with a new, unique single audit identifier.
- [x] A user who does not need to complete a single audit cannot proceed.
- [x] When a user enters criteria that are not valid, they get immediate feedback that helps them recover. (E.g. A user may be determined as not needing to complete an audit, and they should be informed *as well as* prevented from proceeding.)

**Tasks**
- [x] Design refine mocks based on Sprint 1 user research.
- [x] Design/Content collaborate on error message mocks, attach to issue.
- [x] Design attach refined most recent mocks to this issue and tag FE/BE re: most recent design/learning for eligibility entry.
- [x] Update Rosetta Stone (API design documentation) with best understanding of input data and schema mapping.
- [x] Update data model (as needed) to reflect data needs for this story.
- [x] Implement and document JS unit test suite for API
- [x] Implement front-end, attach to API.
- [ ] Customer Support documentation regarding this step in the process.

**Definition of Done**
- [x] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [x] FE test suite updated to test the form
- [x] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by MelissaBraxton** [comment]
@Jkrzy 

Conditions that should trigger an error:

Q1. IF entity type is **none of the above**
Q2. IF answer is **no**
Q3. IF answer is **no*

In the current system, and error is thrown the moment someone selects one of those radio buttons--it doesn't wait until they try and "continue."

**Comment by Jkrzy** [comment]
With #146 I believe the backend portion of this is complete

**Comment by heymatthenry** [comment]
@Jkrzy & @MelissaBraxton Are we aiming to match the functionality of the current system? As it stands, we're relying on the server for the validation & to provide the error messages (as implemented in #146. ty!). So if we want users to see those errors before submitting, we're going to have to call the API every time an onchange event fires.

Alternatives to this would be to either: 

* do the validation on the client-side; or 
* keep the validation on the server and only run it on submit, which would deviate from how the existing system works

What do y'all think?

**Comment by MelissaBraxton** [comment]
Thanks @heymatthenry  - What are the implications of running the validation on the client side? That's my preference from a UX perspective.

The thing that's nice about the existing functionality is that users find out as soon as the trigger an invalid criteria so they could potentially not waste any time answering the other Qs. It also helps us in error message design. If they are checking against all criteria at the same time, then we need logic around the error message telling them which of the 3 criteria they don't meet.

**Comment by Jkrzy** [comment]
We lose a bit of maintainability in that we'd need to update changes in error messaging/logic in both places, in this eligibility case I think that's OK. 

So long as we're intentional about where we're OK duplicating that work to provide a better user experience, I think this is a reasonable approach.

**Comment by jadudm** [comment]
One implication of having it on the client-side is that we will end up with duplication of logic: the API *must* validate the data, because it cannot trust its inputs (even if they come from our frontend). 

I was trying to estimate, with 40K submissions/year, what the load might look like if we fired off an API event for every... `onfocus` event (perhaps instead of `onchange`?). Either way, I don't know what our throughput might look like for this kind of round-trip, nor do I have a sense for how many milliseconds of delay we're looking at when someone departs a field, we fire an event, and come back with a response. I assume it's on the order of 100-250ms, which is noticeable in a UX context.

But, it doesn't *necessarily* have to be on page submit ("next").

Ah. Joe and I crossed paths. I was going to close with "I defer to the engineering team."

**Comment by Jkrzy** [comment]
With https://github.com/GSA-TTS/FAC-Frontend/pull/5 we're doing these checks on the client side as well as server side. 

I did a check w/ Accessibility Insights, looks good for an initial a11y scan.

I took a pass through the issue checklist, but need eyes from others outside of engineering. cc: @jadudm @MelissaBraxton

**Comment by jadudm** [comment]
For conversation:

Issue #153, from the community, references entity types. In the original FAC, users entered this information. However, from a consumer of the data's perspective, this field can often be misreported by the auditor/auditee.

This is in light of the fact that SAM.gov encodes the entity type. 

For discussion. From "path of least disruption" and "we can't casually change the SF-SAC" perspectives, it suggests that we may need to encode the user's choice, and also capture the reality/truth as known by SAM.gov. 

These are not considered opinions at this point. However, this is probably the right place to record the connection between #122 and #153.

**Comment by MelissaBraxton** [comment]
@austinhernandez  - How's this one going? Any updates to add?

**Comment by petermarks-gsa** [comment]
@heymatthenry and @austinhernandez to pair on this. We think this is very close to being done.

**Comment by MelissaBraxton** [comment]
@austinhernandez and @heymatthenry There is one refinement needed here from sprint 1 research:

- [ ] As an auditor or auditee submitting a new audit, I need to understand that  “US based” is  inclusive of the US territories (Puerto Rico, Guam, US Virgin Islands, Northern Mariana Islands).

May also be something @brentryanjohnson can help with, since it's primarily a content change)?

**Comment by MelissaBraxton** [comment]
I went ahead and made the content tweak [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=1862%3A15765).

@heymatthenry  - what else needs to happen before we call this done?

**Comment by heymatthenry** [comment]
@MelissaBraxton I made that change in GSA-TTS/FAC-Frontend#11 so if that's the last piece of this that's outstanding, then we can call it good when that lands.

**Comment by MelissaBraxton** [comment]
@heymatthenry and @petermarks-gsa you want to take one last look and then close out this issue once https://github.com/GSA-TTS/FAC-Frontend/pull/11 has been merged?

**Comment by heymatthenry** [comment]
Just merged ✅
