### ISSUE TITLE
API ADR/go-live

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1236]
### Tasks

```[tasklist]
- [ ] Revise/check [docs drafted](https://docs.google.com/document/d/1yljM1OSNrJwkPmsLa1_FW4zJkm1Yr84tuefbBk-flm0/edit)
- [ ] Write them up as an ADR
- [ ] JWT-ize api.data.gov -> api.fac.gov connection
```
