### ISSUE TITLE
Error chasing 20230613

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1251]
### Tasks

```[tasklist]
- [ ] https://github.com/GSA-TTS/FAC/issues/1252
- [ ] https://github.com/GSA-TTS/FAC/issues/1253
- [ ] https://github.com/GSA-TTS/FAC/issues/1255
- [ ] https://github.com/GSA-TTS/FAC/issues/1254
- [ ] https://github.com/GSA-TTS/FAC/issues/1256
- [ ] https://github.com/GSA-TTS/FAC/issues/1257
```

**Comment by jadudm** [comment]
On my local stack...

```
backend-web-1          | INFO "GET /static/compiled/loader-XRERFQEW.svg HTTP/1.1" 200 1713
backend-web-1          | INFO "GET /static/compiled/loader-XRERFQEW.svg HTTP/1.1" 200 1713
backend-web-1          | INFO Uploaded file federal-awards-expended-template.xlsx slugified filename: federal-awards-expended-template
backend-web-1          | INFO Uploaded file federal-awards-expended-template.xlsx extension: .xlsx
backend-web-1          | INFO Uploaded file federal-awards-expended-template.xlsx content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
backend-web-1          | INFO Uploaded file federal-awards-expended-template.xlsx size: 52369 (max allowed: 26214400)
backend-web-1          | INFO Attempting to scan file: federal-awards-expended-template.xlsx.
backend-web-1          | DEBUG Starting new HTTP connection (1): clamav-rest:9000
backend-web-1          | WARNING FederalAwardsExpended Excel upload failed validation: {'file': ['We were unable to complete a security inspection of the file, please try again or contact support for assistance.']}
backend-web-1          | INFO "GET /static/compiled/file-excel-OKJUW4HL.svg HTTP/1.1" 200 658
backend-web-1          | INFO "GET /static/compiled/file-excel-OKJUW4HL.svg HTTP/1.1" 200 658
backend-web-1          | WARNING {'file': ['We were unable to complete a security inspection of the file, please try again or contact support for assistance.']}: /audit/excel/FederalAwardsExpended/2023BYG0001000001
backend-web-1          | Traceback (most recent call last):
backend-web-1          |   File "/src/audit/views.py", line 104, in post
backend-web-1          |     excel_file.full_clean()
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 1502, in full_clean
backend-web-1          |     raise ValidationError(errors)
backend-web-1          | django.core.exceptions.ValidationError: {'file': ['We were unable to complete a security inspection of the file, please try again or contact support for assistance.']}
backend-web-1          | 
backend-web-1          | During handling of the above exception, another exception occurred:
backend-web-1          | 
backend-web-1          | Traceback (most recent call last):
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
backend-web-1          |     response = get_response(request)
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
backend-web-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
backend-web-1          |     return self.dispatch(request, *args, **kwargs)
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
backend-web-1          |     return bound_method(*args, **kwargs)
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
backend-web-1          |     return view_func(*args, **kwargs)
backend-web-1          |   File "/src/audit/views.py", line 88, in dispatch
backend-web-1          |     return super(ExcelFileHandlerView, self).dispatch(*args, **kwargs)
backend-web-1          |   File "/src/audit/mixins.py", line 44, in dispatch
backend-web-1          |     return super().dispatch(request, *args, **kwargs)
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 73, in dispatch
backend-web-1          |     return super().dispatch(request, *args, **kwargs)
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/newrelic/hooks/framework_django.py", line 909, in wrapper
backend-web-1          |     return wrapped(*args, **kwargs)
backend-web-1          |   File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
backend-web-1          |     return handler(request, *args, **kwargs)
backend-web-1          |   File "/src/audit/views.py", line 141, in post
backend-web-1          |     raise BadRequest(e)
backend-web-1          | django.core.exceptions.BadRequest: {'file': ['We were unable to complete a security inspection of the file, please try again or contact support for assistance.']}
backend-web-1          | WARNING {'file': ['We were unable to complete a security inspection of the file, please try again or contact support for assistance.']}: /audit/excel/FederalAwardsExpended/2023BYG0001000001
```

**Comment by jadudm** [comment]
Running a debugger against Django, and checking the `_scan_file` function/breaking on exception:

```
Exception has occurred: ConnectionError
HTTPConnectionPool(host='clamav-rest', port=9000): Max retries exceeded with url: /scan (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe94f502380>: Failed to establish a new connection: [Errno 111] Connection refused'))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe94f502380>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='clamav-rest', port=9000): Max retries exceeded with url: /scan (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe94f502380>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

  File "/src/audit/validators.py", line 252, in _scan_file
    return requests.post(
  File "/src/audit/validators.py", line 273, in validate_file_infection
    while (res := _scan_file(file)).status_code in AV_SCAN_CODES["ERROR"]:
  File "/src/audit/validators.py", line 304, in validate_excel_file
    validate_file_infection(file)
  File "/src/audit/views.py", line 104, in post
    excel_file.full_clean()
  File "/src/audit/mixins.py", line 44, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/src/audit/views.py", line 88, in dispatch
    return super(ExcelFileHandlerView, self).dispatch(*args, **kwargs)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='clamav-rest', port=9000): Max retries exceeded with url: /scan (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe94f502380>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by jadudm** [comment]
Fixed the above, I think. Minio was clobbering the ClamAV port. But, now I have something else.

```Exception has occurred: VariableDoesNotExist
Failed lookup for key [post] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f2699d7b130>>, 'request': <WSGIRequest: GET '/audit/'>, 'user': <SimpleLazyObject: <User: 7cd7f076-8189-4282-bd14-4cd15b97a996>>, 'perms': PermWrapper(<SimpleLazyObject: <User: 7cd7f076-8189-4282-bd14-4cd15b97a996>>), 'messages': <FallbackStorage: request=<WSGIRequest: GET '/audit/'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'data': <QuerySet [{'report_id': '2023REA0001000001', 'submission_status': 'in_progress', 'auditee_uei': 'EJLRWNCJTJF5', 'auditee_name': 'Berea College', 'fiscal_year_end_date': '2023-09-12'}]>, 'new_link': 'report_submission', 'edit_link': 'audit:EditSubmission'}, {'block': <Block Node: metatags. Contents: [<TextNode: '\n            <meta name="'>, <Variable Node: post.meta_description>, <TextNode: '" />\n            <meta pr'>, <Variable Node: post.title>, <TextNode: '" />\n            <meta pr'>, <Variable Node: post.meta_description>, <TextNode: '" />\n            <meta pr'>]>}]
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
KeyError: 'post'

During handling of the above exception, another exception occurred:

  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 886, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
AttributeError: type object 'RequestContext' has no attribute 'post'

During handling of the above exception, another exception occurred:

  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'post'

During handling of the above exception, another exception occurred:

  File "/src/templates/base.html", line 21, in Django Template
    <meta name="description" content="{{ post.meta_description }}" />
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/src/audit/views.py", line 56, in get
    return render(request, template_name, context)
django.template.base.VariableDoesNotExist: Failed lookup for key [post] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f2699d7b130>>, 'request': <WSGIRequest: GET '/audit/'>, 'user': <SimpleLazyObject: <User: 7cd7f076-8189-4282-bd14-4cd15b97a996>>, 'perms': PermWrapper(<SimpleLazyObject: <User: 7cd7f076-8189-4282-bd14-4cd15b97a996>>), 'messages': <FallbackStorage: request=<WSGIRequest: GET '/audit/'>>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'data': <QuerySet [{'report_id': '2023REA0001000001', 'submission_status': 'in_progress', 'auditee_uei': 'EJLRWNCJTJF5', 'auditee_name': 'Berea College', 'fiscal_year_end_date': '2023-09-12'}]>, 'new_link': 'report_submission', 'edit_link': 'audit:EditSubmission'}, {'block': <Block Node: metatags. Contents: [<TextNode: '\n            <meta name="'>, <Variable Node: post.meta_description>, <TextNode: '" />\n            <meta pr'>, <Variable Node: post.title>, <TextNode: '" />\n            <meta pr'>, <Variable Node: post.meta_description>, <TextNode: '" />\n            <meta pr'>]>}]
```

Admittedly, I am CTRL-C-ing the stack. Perhaps a down and up will help. 

But, re-entering at localhost:8000 seems to cause some kind of awfulness.

**Comment by jadudm** [comment]
We discovered a few things, which are being fixed elsewhere.

1. We were using the wrong container image for clamav in the local stack.
2. There may have been some minio port issues.
3. It is useful to have the debugger.

https://github.com/GSA-TTS/FAC/tree/jadudm/add-vscode-debugging-support

gets us rolling; that was collab effort along with colleagues. Closing this and related tickets.
