### ISSUE TITLE
Validate dates as part of creating a new audit submission record

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#127]
**Background**

We need to make sure people are not trying to submit audit reports for years prior to FY22. 

It covers the following stories:

1. As an auditee or auditor creating a new audit, I need the fiscal period dates to be validated so that subsequent data I enter is what's required for that year. 

**We'll know we're done when...**
- [x] When a user who enters dates outside of FY 22 is barred from moving forward
- [x] When a user who enters dates outside of FY 22 gets a helpful error message that allows them to recover
  
**Tasks**
- [x] Research what FY means in this context - Is it only federal fiscal year or can it be different for different types of entities? 
- [x] [DESIGN] Mock error message visual design and language/content @brentryanjohnson 
- [x] [DESIGN] Front end implementation of date picker and error message
- [x] https://github.com/GSA-TTS/FAC/issues/224
- [x] https://github.com/GSA-TTS/FAC/issues/223

**Definition of Done**
- [x] Meets acceptance criteria
- [x] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [x] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [x] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

**Comment by Jkrzy** [comment]
In #160 I looked across all the FY dates available from sam.gov. Ready to chat when you all are @MelissaBraxton, @austinhernandez!

**Comment by MelissaBraxton** [comment]
Great! Let's put this on the agenda for tomorrow's design/eng sync.

**Comment by tadhg-ohiggins** [comment]
We will need a table of dates for which specific versions of the SF-SAC are/were valid. (This is a future, not MVP, issue, but should be considered architecturally for the MVP.)

**Comment by Jkrzy** [comment]
Coming out of a bit of research in the weeds, here's what we've learned.

- For every Entity, [SAM.gov](http://sam.gov/) tracks a Fiscal Year End Date. This is a MONTH/DAY value. We should use this in the same way we’re using Legal Entity Name
- The earliest possible END of a FY is 01/01 and the last possible is 12/31
- Using FY21 as an example, This means a fiscal year may run from 01/02/2020 - 01/01/2021 at one extreme to 01/01/2021 - 12/31/2021 at the other.
- We’re accepting FY22 audits for the MVP
- A valid audit period ranges from 1 to 24 months
- Annual audits are by far the most common, the earliest we’d expect one to start for FY22 is 01/02/2021. This would be an entity which has a FY End date of 01/01 in [SAM.gov](http://sam.gov/).
- But, we also need to accept Biennial audits, which cover up to 2 years. So we need to accept audits covering a period which starts as early as 01/01/2020.

We've confirmed this behavior with an SME, my next steps are implementing this on the backend

**Comment by MelissaBraxton** [comment]
@brentryanjohnson your error message above looks good to me! I went ahead and checked off the design task.

**Comment by heymatthenry** [comment]
@MelissaBraxton This is what I'm doing for other validation errors on that same form (though we can do whatever you think works, and the error messages are obviously placeholders.): <img width="458" alt="image" src="https://user-images.githubusercontent.com/6290/168334681-00f0ecc1-e5ee-4025-9a8b-abb21232e3a4.png">

**Comment by MelissaBraxton** [comment]
Cool! Tagging in @austinhernandez to weigh in when there's time.

**Comment by MelissaBraxton** [comment]
@heymatthenry Ryan's error text re: dates is ready to go. See also #165  which lays out the error message content for the rest of this page.

**Comment by NicholasKramer** [comment]
> Coming out of a bit of research in the weeds, here's what we've learned. [Ref to 🧵 in slack.](https://gsa-tts.slack.com/archives/C1L58R804/p1652272560822449)
> 
> * For every Entity, [SAM.gov](http://sam.gov/) tracks a Fiscal Year End Date. This is a MONTH/DAY value. We should use this in the same way we’re using Legal Entity Name
> * The earliest possible END of a FY is 01/01 and the last possible is 12/31
> * Using FY21 as an example, This means a fiscal year may run from 01/02/2020 - 01/01/2021 at one extreme to 01/01/2021 - 12/31/2021 at the other.
> * We’re accepting FY22 audits for the MVP
> * A valid audit period ranges from 1 to 24 months
> * Annual audits are by far the most common, the earliest we’d expect one to start for FY22 is 01/02/2021. This would be an entity which has a FY End date of 01/01 in [SAM.gov](http://sam.gov/).
> * But, we also need to accept Biennial audits, which cover up to 2 years. So we need to accept audits covering a period which starts as early as 01/01/2020.
> 
> We've confirmed this behavior with an SME, my next steps are implementing this on the backend

Regarding fiscalYearEndCloseDate, do we need to do any backend validation of the MONTH/DAY value?  Or just pass it along?  Is it possible to validate this if we aren't given the year and need to accept Biennial audits?

**Comment by MelissaBraxton** [comment]
Flagging for @Jkrzy, I think?

**Comment by MelissaBraxton** [comment]
@Jkrzy  - We think you're the one who has the best picture of how we're doing this date validation to be able to unblock this. Can you answer these Qs, please? 

Do we want we want return the FY end date from SAM.gov?  I was thinking we may not since it's only a month/day value? Either way, what kind of validation do we need to implement here?

**Comment by MelissaBraxton** [comment]
@NicholasKramer  - It's my understanding that the remaining work here will be done when your PR#206 is merged. @heymatthenry can you take a look and see confirm whether the front end task can be checked off?

**Comment by petermarks-gsa** [comment]
@heymatthenry @NicholasKramer Checking in here to see if we can consider this done after https://github.com/GSA-TTS/FAC/pull/206 is merged.

**Comment by heymatthenry** [comment]
@petermarks-gsa Once #206 lands and the API gives back the info described in that PR (which AFAICT is just waiting on someone to merge it), I'll then need to implement the error message on the front-end for the case when the dates provided are outside of the correct FY.

**Comment by heymatthenry** [comment]
Actually let me clarify something. The behavior described in #230 is based on the _beginning_ of the user's FY, but right now the API returning the FY end date (per #206). Am I missing something?

**Comment by petermarks-gsa** [comment]
I'm going to re-open this per QA process for stories. 

@heymatthenry - Is the front end for this done? If so, is there a way to get a fancy federalist preview link to check it out?

**Comment by petermarks-gsa** [comment]
@heymatthenry Hmmm. When I choose a date in 2019, I'm not seeing the following mentioned in the acceptance criteria: 

>  When a user who enters dates outside of FY 22 is barred from moving forward
>  When a user who enters dates outside of FY 22 gets a helpful error message that allows them to recover

**Comment by MelissaBraxton** [comment]
@heymatthenry - One note from our design sync:

The error that pops up when they enter dates outside the current range should direct them to Census for older submissions. Something like:

> We are currently only accepting audits from FY22. To submit an audit for a different fiscal period, visit the [Census Bureau](https://facides.census.gov/Account/Login.aspx).

We also talked about how we want to use the FY end date that we can pull from SAM.gov, but I'm thinking we should address that in [this issue ](https://github.com/GSA-TTS/FAC/issues/241)where we explore modals for more complex paths users may want to take to resolve Qs that'll arise based on what they enter on the auditee info page.

**Comment by heymatthenry** [comment]
@petermarks-gsa Ok I think I finally got my arms around this. Because we don't know whether the entity is on an annual or biannual schedule, the most we can say is that we know the submission is invalid if the start date is before 1/1/2020. So we show an error directing them to legacy FAC in that case, otherwise we let them go forward. By similar reasoning, we also can't currently do anything with the FY end date we get from SAM.gov since it doesn't have a year associated with it.

So GSA-TTS/FAC-Frontend#20 just checks the start date. We can figure out other paths forward in #241. 

Does that all sound right?

**Comment by petermarks-gsa** [comment]
@heymatthenry Yep, that all sounds right!

**Comment by MelissaBraxton** [comment]
@heymatthenry - This all sounds right to me too! I think we can close this out then?

**Comment by petermarks-gsa** [comment]
@heymatthenry Checking in on this, it seems like this is not necessarily ready for review as you're actively work on a subtask (https://github.com/GSA-TTS/FAC/issues/224). Is that correct?

**Comment by heymatthenry** [comment]
@petermarks-gsa Good call. I think I meant to move #224 to `Ready to Review` rather than this one.

**Comment by petermarks-gsa** [comment]
@heymatthenry So this looks almost completely done. However, I used the new accessibility QA checklist being discussed in https://github.com/GSA-TTS/FAC/issues/234 and found that the year isn't legible when viewed at 400%, which is a standard Austin proposed. Do you think 400% scale is realistic to fully support?
