### ISSUE TITLE
Audit information form

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1278]
### Tasks

```[tasklist]
- [x] Convert audit information form to web form
- [x] Add unit tests for audit information form checking validation boundaries
- [x] Add migration to add audit information column in 2023 data model
- [x] Add Django mapping to store audit information form
- [x] Add Jsonnet validation for audit information form
```

Broken out for visibility from https://github.com/GSA-TTS/FAC/issues/1219

**Comment by jadudm** [comment]
@eazapata23 , I removed the E2E bullet from this ticket, because the testing work is going to pick it up as a matter of course.

**Comment by jadudm** [comment]
Starting a branch

https://github.com/GSA-TTS/FAC/tree/jadudm/audit-information-schema

for the Jsonnet/validation schema piece.

**Comment by JeanMarie-TTS** [comment]
@jperson1 Are the following fields included?
1.  sp_framework
2.  is_sp_framework_required
3.  sp_framework_auditor_opinion
