### ISSUE TITLE
Notes to SEFA workbook

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1279]
### Background info

The "Notes to SEFA" portion of as submission used to a webpage/form, but we may want to turn it into a workbook instead that looks something like the following, though it might be possible to do this all in one sheet:

Sheet 1, mandatory notes:
| Describe significant accounting... | Did you use de minimis cost rate? | If yes, explain |
| --- | --- | --- |
| Description | Yes | We had to |

Sheet 2, additional notes
| Note title | Note content |
| --- | --- |
| Note one | This is a great note...|

* [Figma designs](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=5551-32825&mode=design&t=rIzhDf73erHw2b6D-0).
* [Previous discussion](https://github.com/GSA-TTS/FAC/issues/570).

### Tasks

```[tasklist]
- [ ] Convert notes to SEFA to Jsonnet
- [ ] Add unit tests for SEFA notes that check validation boundaries
- [ ] Add migration to add SEFA notes column in 2023 data model
- [ ] Add Django mapping to store notes to SEFA
- [ ] Add end-to-end test for happy path on notes to SEFA
```

Broken out for visibility from https://github.com/GSA-TTS/FAC/issues/1219

### Open questions

1. Do we need to pre-fill any of the notes? If not, do we need to provide additional text guidance? See figma mocks.
