### ISSUE TITLE
Audit submission access page

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#128]
**Background**

In the future, non-federal users will have to log in via login.gov. 

It covers the following stories:

1. As an auditor or auditee, I need to be able to specify who will need to certify my new audit (who will "check the box" at the end)
2. As an auditor or auditee, I need to be able to specify who should have access to my new audit
3. As a user, I need information on what will happen when I enter email addresses here so that I feel confident moving to the next step. (this is a front end/content change for now--not anything having to do with the mechanics of notifications)
4. As an auditor or auditee creating a new audit submission, I need the submission access page to make it clear what a “contact” is and what kind of access to the submission they’ll have so that I can give the right access to the right people. 

**We'll know we're done when...**
- [x] A user can enter a valid email address for (validated means any email address for now, for this bit of work. Later we'll need to figure out how we handle whether a particular users can access a particular audit submission)
- [x] When a user enters an invalid email address, they get a helpful error message that helps them recover. 
  
**Tasks**
- [x] [DESIGN/CONTENT] Update mocks based on sprint 1 research (#180) 
- [x] [DESIGN] Attach refined mocks to the issue
- [x] https://github.com/GSA-TTS/FAC/issues/200
- [x] https://github.com/GSA-TTS/FAC/issues/246
- [ ] https://github.com/GSA-TTS/FAC/issues/317
- [x] https://github.com/GSA-TTS/FAC/issues/168

**Definition of Done**
- [ ] Meets acceptance criteria
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

**Comment by Jkrzy** [comment]
🤔 Thinking about assumptions here

* At this point in the flow, the Names/Emails being specified **are not** linked directly to User Accounts in the FAC.
* At **some time in the future** we expect a person associated with a given email would authenticate via Login.gov and then be automatically associated with an `SF-SAC` created here.

**Comment by MelissaBraxton** [comment]
Yes, that matches my thinking @Jkrzy.

**Comment by MelissaBraxton** [comment]
One new need statement from sprint 1 research to discuss:

As an auditor or auditee creating a new audit submission, I need the submission access page to make it clear whether I need to enter my own contact information to get access to the submission. 

My hunch is that folks creating a new submission should get access automatically without having to enter their info. Edge case - if they are _also_ the certifying official, then they may need to enter their contact info in that box.

**Comment by MelissaBraxton** [comment]
@Jkrzy and @austinhernandez  - Is the checklist here up to date? Wanting to get a clear sense of where this is at before we head into backlog grooming tomorrow.

**Comment by heymatthenry** [comment]
@MelissaBraxton Are there any required fields here? Seems like they all could be required, but as it is the mocks don't mark any as such. @SSPJ has been working on building this out so I just want to make sure he's got all the info he needs for that.

**Comment by MelissaBraxton** [comment]
Yes, they are all required. Good catch!

**Comment by MelissaBraxton** [comment]
Heads up, @heymatthenry  - @sreuber has some minor content refinements to suggest here. I think he's planning to work on it tomorrow 5/18.

**Comment by sreuber** [comment]
@heymatthenry @MelissaBraxton I placed a line of text over the Cancel & Create buttons. I asked in Slack what type of e-mail is sent to perhaps be a little more specific but perhaps this language is fine. Mockup I'm working from is [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=1906%3A8483). 

"The above contacts will receive an e-mail once this audit is created." Open to feedback on the verbiage.

**Comment by MelissaBraxton** [comment]
Sounds good to me! All we need now is some content that helps folks know they need to include their own contact info to get access.

**Comment by heymatthenry** [comment]
@petermarks-gsa Here's the PR that was merged so you can see the functionality.

**Comment by petermarks-gsa** [comment]
@heymatthenry Going to consider this in progress and not ready for review as the backend work linked here is not done quite yet.

**Comment by petermarks-gsa** [comment]
Per my QA in https://github.com/GSA-TTS/FAC-Frontend/pull/34, we can consider this done.

**Comment by geekygirlsarah** [comment]
The "dones" aren't checked on here and this got closed. Safe to assume someone reviewed them?

**Comment by SSPJ** [comment]
@geekygirlsarah The unchecked "dones" for accessibility were things I was checking while working on this. @heymatthenry and @jasnakai did some work after I was involved and could probably answer whether those are complete on the finished PR or need another pass.

**Comment by jasnakai** [comment]
I did not perform dedicated tests of those points. I can do a quick review.

**Comment by petermarks-gsa** [comment]
I did accessibility checks as part of https://github.com/GSA-TTS/FAC/issues/200. Sorry for not being more explicit at story level.
