### ISSUE TITLE
Secondary auditors workbook

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1280]
### Tasks

```[tasklist]
- [x] Convert secondary auditors form to Jsonnet
- [x] Add unit tests for secondary auditors form checking validation boundaries
- [x] Add migration to add secondary auditors column in 2023 data model
- [x] Add Django mapping to store secondary auditors form
- [x] Add end-to-end test for happy path on secondary auditors form
```

Broken out for visibility from #1219

**Comment by danswick** [comment]
We're done here!
