### ISSUE TITLE
XLSX workbooks that are corrupt

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1285]
We need some corrupt XLSX workbooks for failure testing.

### Tasks

```[tasklist]
- [ ] Take a known good XLSX workbook (Federal Awards), and corrupt the middle 50% of the data.
- [ ] Take a known good secondary auditors workbook, and fill it with illegal characters (e.g. emoji)
- [ ] Rename a JPEG or PNG of a cat as .xlsx
```

**Comment by jadudm** [comment]
See #493 for some prior context.

**Comment by jadudm** [comment]
We now have a new intake process, and workbooks designed to fail our validations. Closing.
