### ISSUE TITLE
Corrupt PDFs for testing

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1286]
We need some PDFs that will cause our system to fail.

### Tasks

```[tasklist]
- [ ] A PDF that is locked with a password
- [ ] A PDF that is entirely scanned images
- [ ] A PDF that has the middle 50% zeroed out
- [ ] A PDF that is too large for our system to handle (e.g. 50MB)
- [ ] A short README detailing what/how each file was corrupted, stored with the files
```

**Comment by jadudm** [comment]
We... have one that is designed to fail. Closing as "not planned" for now.
