### ISSUE TITLE
Generate 2023-style test data in JSON format

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1287]
We need some 2023-style (JSON-object-based) data for testing ETL processes with. 

It might be easiest to take some Census CSVs and reverse-map them into JSON objects, which can then be loaded into our tables. 

### Tasks

```[tasklist]
- [ ] Obtain 2022 CSVs from the Census website
- [ ] Use the 2023->historical mapping (in GDrive) to "reverse map" data into JSON objects
- [ ] Use the Jsonnet schemas (in the `schemas` directory) to test/validate the objects created
- [ ] Store objects into the 2023 table as GFAC-style data for ETL testing.
```

This has the side-effect of populating the dissemination tables with data that the API can test.

The CSVs are in the GDrive here

https://drive.google.com/drive/folders/1ETDwj4xDv_mUOHLt39e-3HmEi2Q-E5FF

as SQLite3 files. However, I have found that standard (Python) tools crash on trying to open them, because the CSV export has some invalid characters that I have not yet stripped. I believe a byte-wise process needs to comb the CSVs first, before running the Bash script that makes the DB files. 

Point being, `sqlitebrowser` will open those files, and that might be useful for extracting tables.

The [mappings](https://github.com/GSA-TTS/FAC/tree/main/backend/data_distro/mappings) directory in the repo is also a good source of info.

**Comment by mogul** [comment]
Just checking in: Is this still needed? If so, is it a `SHOULD` or a `MUST`? (If the former, I'd like to delete it from the project.)

**Comment by jadudm** [comment]
This was completed as the `workbooks_e2e` command, which is now merging in.
