### ISSUE TITLE
Email support channel investigation

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1289]
# At a glance

**In order to** ask for help
**as a** user
**I want** confidence I'm using the right email address.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: I am a PO with a short timeline, and need a support channel that can quickly be integrated into a static site and web-based application.

**Given** that there is neither team nor staff for a complex implementation, 
**when** we decide on a pathway to providing support to users

```[tasklist]
### then...
- [ ] we will understand what is involved in having an email-only pathway, and the time costs involved
- [ ] we will understand what is involved in having a web-based ticketing solution, and the time costs involved
- [ ] we will have discussed those as a team, and made a decision that supports delivery with minimal impact on the CX and dev team
``` 

We have one person on the CX team, and that person is also our SME; therefore, they play a critical role elsewhere on many tickets. We need the lightest/fastest path to CX for MVP, and then need to prioritize any additional CX work appropriately. Currently, it is not clear what the time costs are in the options available to us.

### Scenario: I encounter an error in my submission process.

**Given**   that I am on `app.fac.gov` 
**when**  I encounter that error
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] I should easily find my way to a help page.
- [ ] A copy-pastable email template should be available to me.
- [ ] An address consistent with future help offerings should be provided (e.g. `support@fac.gov`) 
- [ ] The email address should route to our ticketing system
```

For now, it is not in the roadmap to provide in-site mail features; we need to route them to their own email client for MVP. If we get further ahead, we'll replace the email path with web-based ticketing.

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: @Leighdiddy 
* Engineering shepherd: @Carley-Sullivan 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

The purpose for exploring email support first is that it has the lightest load on the development team, and uses tools we know will work for the user (their email client). It only requires a static page on our site.

If it is the case that a web-based ticketing solution is easier/faster, then we can/should consider that. However, if setting up a web-based embedding is more work, we need the fastest/smallest increment of work that provides user help integrated before we go to MVP. 

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no known security concerns, as this will be routing to a third-party application, and will not touch our software in any way.

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] 
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
#413 was arguably about this; this is a refinement, in that it asks us to make a decision about email vs. web ticketing.
