### ISSUE TITLE
Compensate Sprint 1 research participants

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#129]
**Background**
We Just got approval from TTS Ops to compensate research participants.  

**We'll know we're done when...**
- [ ] We've sent giftcards to all sprint 1 participants

**Tasks**
- [ ] Email participants to let them know about compensation and ask them their preference for email of snail mail compensation 
- [ ] Update participant tracking sheet to communicate to Djemila batches of participants that need to be reimbursed and whether they prefer email or snail mail (and associated addresses)
- [ ] Share sheet w/ Djemila
- [ ] Create purchase request and link to sheet in request
