### ISSUE TITLE
UAT ("A" round) documentation

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1291]
In order to run the tests, we're going to need a document and some files zipped up and ready to ship.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/1283
- [ ] Document test procedure
- [ ] Create PDF of docs, create zip file
```

**Comment by jadudm** [comment]
Done.
