### ISSUE TITLE
Document current team working practices in Wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#13]
**Background**

**We'll know we're done when...**
- [x] **We've decided how we'll use the Github Wiki** - Peter Proposal: Don't have a ton of context, but the homepage of the wiki suggests it was created for the purpose of exposing information we want available to outside parties. My suggestion is to keep doing that, but also put documentation important to the team that is subject to change (i.e. agile process) in docs / version control so that changes are more clear.  
- [x] We have initial content that addresses below topics 

**Tasks**

Document
- [x] **What's the lifecycle of a user story? (e.g., how do things move across the board? who moves them? when?)** - https://github.com/GSA-TTS/FAC/wiki/Agile-Process
- [x] **How do we approach sizing and estimation?** - Matt's comments [here](https://github.com/GSA-TTS/FAC/wiki/sizing-estimation) seem reasonable, although they're not being fully implemented. 
- [x] **Team ceremonies** (including facilitator and note taking rotation) - Defined [here](https://github.com/GSA-TTS/FAC/wiki/agile-process)
- [x] **Optional** - How do design and engineering work together? Collaborate? - Peter suggestion: Product facilitates this handoff. 
- [x] **Team availability** - Google calendar for OOO

**Comment by MelissaBraxton** [comment]
@jadudm  - do we want to hand this off to @petermarks-gsa based on our discussion earlier today?

**Comment by jadudm** [comment]
That sounds good to me. I've made some headway, but they're things he will
essentially be leading, so it makes sense to handoff.

**Comment by petermarks-gsa** [comment]
@jadudm This is ready for review. Also flagging Jenna, but don't know her github.
