### ISSUE TITLE
Replace repo-sync/pull-request action

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#1304]
The `repo-sync/pull-request@v2` action we currently use in our [PR autogeneration workflow](https://github.com/GSA-TTS/FAC/blob/main/.github/workflows/auto-create-pr.yml) is being archived and will need to be replaced soon. 

### Tasks

- [x] Investigate some of the [suggested replacements](https://github.com/repo-sync/pull-request/issues/143) using the GitHub CLI, though there doesn't appear to be a straightforward way to get outputs to pass on to other workflows.
- [x] Decide on a path forward.
- [x] Implement a new solution.

**Comment by asteel-gsa** [comment]
Managed to find a way to get the PR# which was the original reason for reverting back to this:
```yaml
run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT
```

Which will allow us to call `${{ steps.pr.outputs.pull_request_number }}` or `${{ needs.pull-request.outputs.pr_number }}` if we want to enhance the workflow. Ill open a PR now and get this back into main

**Comment by asteel-gsa** [comment]
![image](https://github.com/GSA-TTS/FAC/assets/130377221/606001f3-b07b-4f0f-bdfc-4be881c414cb)

**Comment by theletterf** [comment]
Came here from https://github.com/repo-sync/pull-request/issues/143. Is your current solution in https://github.com/GSA-TTS/FAC/pull/1306 replacing `pull-request` satisfactorily?
