### ISSUE TITLE
Add a Django command to load fixture data

### ISSUE THREAD

**Issue by neilmb** [GSA-TTS/FAC#1308]
As a development team member, I want to have a simple way to bootstrap audit information so that I can more easily test and explore the application.

### Tasks

```[tasklist]
- [ ] Create a Django command `load_fixtures` that will add made up data into the application
- [ ] Give team members a place to record their Login.gov sandbox UUID so that their user will get example data loaded
- [ ] Start with happy-path `SingleAuditChecklist` and its attendant `general_information` for each user
- [ ] Continue on with the various workbook objects under the `federal_awards` object
```

CC @jadudm

**Comment by danswick** [comment]
@neilmb should this issue be closed now that #1321 has merged or do we still want to track some of the tasks here?
