### ISSUE TITLE
Process documentation for how helpdesk tickets are triaged, handled, and archived

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1312]
### Tasks

```[tasklist]
- [ ] Refine mural process based on consultation with team members
- [ ] Draft as GDoc, signoff w/ PO, CX lead, OROS Design Lead
- [ ] Move PDR or web-facing document for archive as "process v1"
- [ ] Implement, iterate, reflect after 1-2 months (new ticket to be written for evaluation)
```

**Comment by jadudm** [comment]
@LeoFotovich , I'm going to close this ticket as "not planned" because of age (and we did most of it), but I actually think that when we epic out your documentation effort, it will do this work.
