### ISSUE TITLE
How do we message fixes, changes, versioning to workbooks

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1322]
### Tasks

```[tasklist]
- [ ] What do we do with errors that *must* be fixed? 
- [ ] Do we use semver for this, too?
- [ ] Do we allow changes?
```

Probably want to version the entire suite of workbooks. Always want to use the most current version across the board. 

We currently don't have a workbook version embedded in the workbook, the validation, or the objects. 

Example:

* Tues, July 1, they download 1.2. It's been up for four months.
* They spend six bazillion hours filling it with data.
* On Monday, July 8th, they upload a version 1.2. document. We moved to 1.3.
* Do we... ask them to update? All the workbooks?

**Comment by jadudm** [comment]
Picked up as epic #1477.
