### ISSUE TITLE
Assign Sequential Numbers to Rows in an XLSX Sheets when Converting to JSON Objects

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#1364]
### Tasks

```[tasklist]
- [ ] Add sequential numbers to rows in Federal Awards JSON object.
- [ ] Add sequential numbers to rows in Corrective Action Plan JSON object.
- [ ] Add sequential numbers to rows in Finding Text JSON object.
- [ ] Add sequential numbers to rows in Finding Uniform Guidance object.
```

**Comment by JeanMarie-TTS** [comment]
> It sounds like this ticket is no longer needed. I will wait for your thumbs-up to close @JeanMarie-TTS

@sambodeme  Yes, we can close this one as it's replaced by other tickets which are being worked on now.
