### ISSUE TITLE
Combine workbooks into one page in SF-SAC workflow

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1366]
This issue covers the presentation of workbooks in the SF-SAC workflow. 

### Background
They are currently broken into separate screens, and can be combined into one to simplify navigation for users. 

### Acceptance criteria (We'll know we're done when...)

- [ ] A new single screen showing all seven workbooks with clear implementation and copy is designed to replace this workflow: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=1%3A31587&mode=design&t=bp89uLYfV4jyNp4D-1
  
### Tasks

- [ ] Design
- [ ] Copy review
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by jadudm** [comment]
We did this thing.
