### ISSUE TITLE
Design data validation screen for certification checklist 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1367]
This issue covers the design of a single screen for data validation before submitting for certification. 

### Background
The full contents of the users SF-SAC will need to pass through a final validation before submission to maintain clean data in the clearinghouse. It will be the fourth from last step in this checklist: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=1%3A31587&mode=design&t=bp89uLYfV4jyNp4D-1

### Acceptance criteria (We'll know we're done when...)

- [ ] a new page has been designed that lets the user consent to validation of their full SF-SAC contents and displays an error table to address corrections before certification. 
  
### Tasks

- [ ] Design
- [ ] Copy review 
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)
