### ISSUE TITLE
Epic: Automated E2E regression testing

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1399]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Product owner, test lead
**What**: On every push to `staging`, we want to run at least one complete submission.
**Why**: This is an end-to-end regression test. It asserts that our automated, daily pushes to `staging` do not break the user's ability to submit the SF-SAC.

```[tasklist]
### Stories
- [x] Run any (one) cypress test against staging in GH Actions
- [ ] #1055
- [ ] https://github.com/GSA-TTS/FAC/issues/1552
- [ ] https://github.com/GSA-TTS/FAC/issues/1569
- [ ] https://github.com/GSA-TTS/FAC/issues/1582
- [ ] https://github.com/GSA-TTS/FAC/issues/1570
- [ ] https://github.com/GSA-TTS/FAC/issues/1572
- [ ] https://github.com/GSA-TTS/FAC/issues/1571
- [ ] https://github.com/GSA-TTS/FAC/issues/1573
- [ ] https://github.com/GSA-TTS/FAC/issues/1574
- [ ] https://github.com/GSA-TTS/FAC/issues/1575
- [ ] https://github.com/GSA-TTS/FAC/issues/1576
- [ ] https://github.com/GSA-TTS/FAC/issues/1577
- [ ] https://github.com/GSA-TTS/FAC/issues/1578
- [ ] https://github.com/GSA-TTS/FAC/issues/1579
- [x] https://github.com/GSA-TTS/FAC/issues/1784
- [ ] https://github.com/GSA-TTS/FAC/issues/1581
- [ ] https://github.com/GSA-TTS/FAC/issues/1580
- [ ] https://github.com/GSA-TTS/FAC/issues/1583
- [ ] https://github.com/GSA-TTS/FAC/issues/1584
- [ ] https://github.com/GSA-TTS/FAC/issues/1585
- [ ] https://github.com/GSA-TTS/FAC/issues/1586
- [ ] https://github.com/GSA-TTS/FAC/issues/2047
- [ ] https://github.com/GSA-TTS/FAC/issues/2048
- [ ] https://github.com/GSA-TTS/FAC/issues/2123
```

Then...

```[tasklist]
### Next...
- [ ] Refactor for running locally.
- [ ] Stretch goal: Refactor for running on `dev` PRs
```

**Comment by jadudm** [comment]
The multiple submissions is an improvement, not a completion factor. We will story other improvements to E2E as we go. 🥳
