### ISSUE TITLE
Set up prototyping in environment in Figma

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#14]
**Background**

**We'll know we're done when...**
- [x] We have a place in Figma where all designers can jam
- [x] Figma environment includes USWDS components and templates we think we may use

**Tasks**
- [X] Create Figma environment
- [x] Add/ upload USWDS components
