### ISSUE TITLE
Synthesize and write up sprint 2 research

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#140]
**Background**

**We'll know we're done when...**
- [x] We have documented research results in the wiki. 
- [x] We've documented any new user stories on the story map

**Tasks**
- [x] Synthesize research
- [x] Write up summary 
- [x] Write up new user needs statements add to Mural
- [x] Post roles goals and needs statements in wiki

**Comment by MelissaBraxton** [comment]
@sreuber  - is this in progress?

**Comment by sreuber** [comment]
Wanted to discuss further, we had some hiccups.

**Comment by sreuber** [comment]
@MelissaBraxton Updated research report. Where in the wiki is it posted? And are we good with the user stories to add to the Mural?
