### ISSUE TITLE
Epic: Dissemination tables

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1402]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Product owner
**What**: Models instantiated in the DB for dissemination of data.
**Why**: Because we need somewhere for completed audits to go, and for the API to pull from.

This epic is about *creating the tables*, and is not about how we move data between our collection tables and dissemination tables (Epic #1403) or how we provide views in the API for the dissemination tables (Epic #1405).

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1406
- [ ] https://github.com/GSA-TTS/FAC/issues/1414
- [ ] https://github.com/GSA-TTS/FAC/issues/1407
- [ ] https://github.com/GSA-TTS/FAC/issues/1408
- [ ] https://github.com/GSA-TTS/FAC/issues/1409
- [ ] https://github.com/GSA-TTS/FAC/issues/1410
- [ ] https://github.com/GSA-TTS/FAC/issues/1411
- [ ] https://github.com/GSA-TTS/FAC/issues/1412
- [ ] https://github.com/GSA-TTS/FAC/issues/1413
- [ ] https://github.com/GSA-TTS/FAC/issues/1460
- [ ] https://github.com/GSA-TTS/FAC/issues/1619
```

**Comment by jadudm** [comment]
Closed via #1384.

**Comment by jadudm** [comment]
Closed via #1384.

**Comment by JeanMarie-TTS** [comment]
@gsa-suk I added GenAuditor table to models.py. We have hist_columns that need to be removed from model if we don't need them to support recent history from census. If we need to keep them, we should rename them and not call them hist_. We decided to keep hist_ columns only in fac.md for documentation purposes as comments.

**Comment by jadudm** [comment]
Was tracking in #1282.
