### ISSUE TITLE
Epic: ETL for AY23

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1403]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Product owner
**What**: Move a completed audit from collection to dissemination.
**Why**: Because completed audits want to be free. :tada: 

This epic is about *moving data between collection and dissemination tables*, and is not about we model the data (Epic #1402 ) or how we provide views in the API for the dissemination tables (Epic #1405).

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1415
- [ ] https://github.com/GSA-TTS/FAC/issues/1416
- [ ] https://github.com/GSA-TTS/FAC/issues/1418
- [ ] https://github.com/GSA-TTS/FAC/issues/1419
- [ ] https://github.com/GSA-TTS/FAC/issues/1420
- [ ] https://github.com/GSA-TTS/FAC/issues/1421
- [ ] https://github.com/GSA-TTS/FAC/issues/1422
- [ ] https://github.com/GSA-TTS/FAC/issues/1423
- [ ] https://github.com/GSA-TTS/FAC/issues/1601
- [ ] https://github.com/GSA-TTS/FAC/issues/1600
- [ ] https://github.com/GSA-TTS/FAC/issues/1609
```
