### ISSUE TITLE
Initial take on data dissemination functionality

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#141]
**Background**

<<background>>

It covers the following stories:

1. As an ...

**We'll know we're done when...**
- [ ] When a user can ...
  
**Tasks**
- [ ] Design designs all the things
- [ ] Engineering engineers all the things

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by MelissaBraxton** [comment]
Based on this[ PDR](https://github.com/GSA-TTS/FAC/blob/main/docs/product/decisions/0004-P-migration-plan.md), this shifts down on our priority list.

**Comment by austinhernandez** [comment]
initial wireframes for search, sort and filter on figma:
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2443%3A10893
