### ISSUE TITLE
Epic: Bugs to be addressed before go-live

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1426]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Auditees and auditors.
**What**: Don't like bugs.
**Why**: They're annoying or showstoppers for doing their job.

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/937
- [ ] #889
- [ ] https://github.com/GSA-TTS/FAC/issues/1341
- [ ] https://github.com/GSA-TTS/FAC/issues/1483
- [ ] https://github.com/GSA-TTS/FAC/issues/1636
- [ ] https://github.com/GSA-TTS/FAC/issues/1435
- [ ] https://github.com/GSA-TTS/FAC/issues/1175
- [ ] https://github.com/GSA-TTS/FAC/issues/1227
- [ ] https://github.com/GSA-TTS/FAC/issues/1269
- [ ] https://github.com/GSA-TTS/FAC/issues/1431
- [ ] https://github.com/GSA-TTS/FAC/issues/1637
- [ ] https://github.com/GSA-TTS/FAC/issues/1639
- [ ] https://github.com/GSA-TTS/FAC/issues/1640
- [ ] https://github.com/GSA-TTS/FAC/issues/1050
- [ ] https://github.com/GSA-TTS/FAC/issues/1603
- [ ] https://github.com/GSA-TTS/FAC/issues/1741
- [ ] https://github.com/GSA-TTS/FAC/issues/1290
```

**Comment by jadudm** [comment]
Switching to the bug swimlane for tracking.

https://github.com/GSA-TTS/FAC/issues/1924

Archiving this ticket.
