### ISSUE TITLE
Add logic to cross-validation looking for consent regarding data sharing.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1433]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

If a submitter identifies as a tribal organization, they must complete the data sharing consent. It does not matter if data is requested to be kept private, or it is made public: the consent must be completed.

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [x] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [ ] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [x] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [x] This generates one error
- [ ] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"TBD"
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
TRIBALCONSENT_202307071713
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```

**Comment by jadudm** [comment]
#1453 articulates the same thing, but better. Closing this one.
