### ISSUE TITLE
Epic: API to support partner development

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1438]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Federal partners relying on the FAC API
**What**: Want to talk to our API
**Why**: Because they, too, are developing software under time pressure.

```[tasklist]
### Stories
- [ ] #1153
- [ ] https://github.com/GSA-TTS/FAC/issues/1405
- [ ] #1287
- [ ] https://github.com/GSA-TTS/FAC/issues/1224
- [ ] https://github.com/GSA-TTS/FAC/issues/1162
- [ ] https://github.com/GSA-TTS/FAC/issues/1320
- [ ] https://github.com/GSA-TTS/FAC/issues/1155
```
