### ISSUE TITLE
Cross-validation: Checking workbook version

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1442]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

This is not *technically* a cross-validation. It can be checked on a per-workbook basis as part of our schema. Labeling as a bug as well, because (technically) we could view it as a bug against our current JSON Schema validation process.

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [x] Federal Awards
- [x] Audit Findings
- [x] Audit findings text
- [x] CAP Text
- [x] Additional UEIs
- [x] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [x] This generates one error
- [ ] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"You uploaded version {old-version} of this workbook; please download the most recent version from fac.gov, transfer your data, and submit again."
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
VERSION_202307100727
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```
