### ISSUE TITLE
Cross-validation: Cluster totals

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1444]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [x] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [ ] This generates one error
- [x] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"The cluster total for {cluster-name} is reported {value}; it should be {correct-value}."
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
CLUSTER_202307070735
```

## Notes

[//]: # (Any additional notes for implementation.)

For a given award and cluster, there might be multiple rows in that cluster. The total spend for that cluster should be the same on every row where it appears. 

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```

**Comment by jadudm** [comment]
This is a locked column in our workbooks. It should not be possible to have a "wrong" cluster total. It is worth checking it in the backend *only* after we have run out of other validations, and have handled all MUST/SHOULD work for MVP.

**Comment by danswick** [comment]
https://github.com/GSA-TTS/FAC/blob/main/backend/audit/intakelib/checks/check_cluster_total.py
