### ISSUE TITLE
Epic: Manage users

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1446]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Auditors and auditees
**What**: Add and remove team members
**Why**: Team members come and go

The user management interface is designed, but we need to implement the page as well as any associated tooling to store the users. 

This is a draft epic; we will need to ticket this out further in order to bring it on to the board.

```[tasklist]
### Stories
- [ ] Verify design in Figma as being "source of truth."
- [ ] Write Jsonnet for JSON Schema to validate user management form
- [ ] Add tests for user management submission
- [ ] https://github.com/GSA-TTS/FAC/issues/1447
- [ ] https://github.com/GSA-TTS/FAC/issues/1636
```

**Comment by jadudm** [comment]
See #795 for historical information.

**Comment by jadudm** [comment]
We are going to do this, but this epic/ticket is very old. We're going to do new design work to reflect current realities/understandings/needs. Best to just close this one out.
