### ISSUE TITLE
Auditee information page - Content explaining UEI

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#145]
**Background**

We are working on the auditee info page in #126. This issue is focused on the content users see on that page. 

It covers the following stories:

1. As an auditee or auditor creating a new audit, I need in-context information on the auditee information page about what a UEI is and where I get it so that I know what number to put in.
2. As an auditee or auditor creating a new audit, I need in-context information on the auditee information page about how UEI will be validated and used to auto-populate entity information from sam.gov so that I know where that information comes from.

**We'll know we're done when...**
- [ ] Users are presented with clear content describing which number they're being asked to enter into the UEI field and where to get it and what data will be auto-populated from sam.gov. 
  
**Tasks**
- [x] Research what data we will populate from sam.gov
- [x] Review sprint 2 research report findings re: USE communication
- [ ] ~Determine where in users task flows they'll encounter UEI for the first time~
- [ ] ~Mock content to better explain UEI where it first appears in their process~
- [x] Mock refinements to the auditee information page to better communicate UEI and what "validate" will do
- [ ] [FRONT END] Implement refinements

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by MelissaBraxton** [comment]
@petermarks-gsa I think we need to prioritize this work and refine the issue so that it can be picked up, since I believe the auditee info page is in progress.

**Comment by MelissaBraxton** [comment]
Yep! I also refined it a bit so I think it's ready to pick up and could be moved into available if you agree.

**Comment by MelissaBraxton** [comment]
I crossed out the two tasks re: adding a UEI explanation. The first place UEI appears in the flow is in the "my submission access page, which is currently being mocked [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2443%3A11491). I added a comment to the mock to include a glossary link or other def of UEI on that page for consideration when we are ready to take on that work. 

With that change, this story is narrowly focused on adding the tool tip on the audit submission access page that explains what UEI is validated against for @heymatthenry to implement.

**Comment by heymatthenry** [comment]
@MelissaBraxton The tooltip is implemented in GSA-TTS/FAC-Frontend#16. Couple of notes:

There's no link to SAM.gov since: 1) the USWDS tooltip component doesn't support any formatting inside the tooltip; and 2) if you were to stop hovering over the button to go click the link the tooltip would disappear.

Also there's no line break. Again this is a function of using the stock USWDS tooltip.

If either of the above are dealbreakers let me know and we can implement our own tooltip from scratch.

**Comment by MelissaBraxton** [comment]
I'm thinking this is done? Or at least ready for review, based on https://github.com/GSA-TTS/FAC-Frontend/pull/16. What do you think, @petermarks-gsa and @heymatthenry ?
