### ISSUE TITLE
Cross-validation: Require data sharing consent if identifying as a tribal organization

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1453]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

As part of the Pre-SAC, an auditee might identify as a tribal organization. If this is the case, than we will (conditionally) be making a data sharing consent form available as part of submission. (This is not *actually* a new form; it was part of the certification process in the Census FAC.)

So, we need a validation that says:

```
IF the user identified as a tribal organization
THEN
they must have a data sharing/consent form in the database
AND 
it must be complete. 
FI
```

Complete, in this case, means that they answered "yes/no" and signed the form. ("Signed" means "filled in their name.") 

**Only the certifying auditee can complete this form.**

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [x] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [ ] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [x] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [x] This generates one error
- [ ] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"As a tribal organization, you must complete the data sharing consent statement before submitting your audit."
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
TRIBAL_202307101232
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```
