### ISSUE TITLE
Epic: Application event logging

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1454]
We need to walk the app and log a number of things. This is both for compliance purposes as well as making sure we can understand what our app is doing (especially if something goes wrong).

At the least:

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/1455
- [ ] https://github.com/GSA-TTS/FAC/issues/1456
- [ ] Log process tracking
- [ ] Log administrator** activities
- [ ] Log authentication checks
- [ ] Log authorization checks
- [ ] Log data deletions
- [ ] Log data access
- [ ] Log data changes
```

**Comment by jadudm** [comment]
This is not targeted enough to be actionable, and can be better ticketed as part of ongoing NR alerting work.
