### ISSUE TITLE
ETL tests for full data model

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1458]
We need test(s) for the ETL process. This suggests (at the least) data and a run of the process (that checks the transfer of the data).

We'll know we're done when...

```[tasklist]
### Tasks
- [ ] ETL: Add the ETL tests to CI/CD test runner
- [ ] https://github.com/GSA-TTS/FAC/issues/1459
- [ ] ETL: Check result of ETL process against source data for correctness
```

**Comment by JeanMarie-TTS** [comment]
@pluribus-tony , can you reuse what @sambodeme is developing, I think, to load test data from workbooks? It would be useful to have some end to end test from data entry to dissemination.

**Comment by pluribus-tony** [comment]
https://github.com/GSA-TTS/FAC/pull/1610

**Comment by jadudm** [comment]
We have... tests for the ETL. More testing can be ticketed separately, as it is covered in multiple ways currently (e.g. via regression, unit testing, etc.)
