### ISSUE TITLE
Verify dissemination model against piped headers in Census data

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1460]
Census sent us a set of tables that contain a single row/single column. That single row/column contains data that looks like:

SOMETHING|ALSOATHING|MORETHINGS

where each values in the pipe-delimited string is a column name. The database name (e.g. ELECGENERALPIPE) tells us that these are the columns from the ELECGENERAL table that will be exported. 

We should check to see if all of the columns that would be exported are present in our dissemination model. This is a manual process (most likely).

```[tasklist]
### Tasks
- [x] Check all pipe files/columns for presence in the data model.
- [x] Make sure the type and format are noted (e.g. `TEXT`, `NUMERIC`, or `DATE`).
- [x] Add missing fields to the data model.
```

**Comment by gsa-suk** [comment]
Comparison of columns in the pipe table with columns in GFAC: 
https://docs.google.com/spreadsheets/d/1sgWEHhOPT_7byQRYB9pWLXT76Y186Uae74kaUwMKqTs/edit#gid=1932906304
Please note the items highlighted in yellow.

Reference: https://docs.google.com/spreadsheets/d/1GoVm21SMOSgNaXTUVHC-qQVRk9gsX0Mt5BU7kgNw_no/edit?pli=1#gid=905306839
