### ISSUE TITLE
Map and test information architecture and navigation

### ISSUE THREAD

**Issue by brentryanjohnson** [GSA-TTS/FAC#147]
**Background**
The presentation of information on the current FAC is inconsistent, as the top-level navigation changes depending on which part of the system the user is interacting with. The functions of submitting and accessing audit information have specific naming conventions ("Internet Data Entry System" and "Image Management System," respectively), although the homepage navigation refers to these functions as "Submit an Audit" and "Find Audit Information."

**Questions to answer**
- What tasks and information need to be available at which stage in the process?
- Which tasks or information need to be available at _all_ stages of the process?
- Which tasks do users need to log in to complete? Which tasks or information should be available without logging in?
- Does the presence of the Login button imply that a user must log in in order to complete specific tasks or access certain information?
- Which instruction content should be presented in context versus on separate pages?

**We'll know we're done when...**
- [x] We know what content exists now and what content needs to be created
- [x] Content is grouped, labeled, and organized
- [x] We've developed and tested draft UI/navigation

**Tasks**
- [x] Inventory existing content 
- [x] Categorize existing content
- [x] Prototype user interface navigation

**Comment by brentryanjohnson** [comment]
Here's a draft high-level nav:

## Main nav (persistent)

- Submit an audit
- Find an audit
- Resources 
  - _I'd like to make this more specific...Data sheets? Templates?_
- FAQs
- Contact us

## Utility nav (persistent)
- Language
- Login

**Comment by MelissaBraxton** [comment]
Refined this to focus on initial IA draft. Created https://github.com/GSA-TTS/FAC/issues/248 as a breakout issue to cover testing.
