### ISSUE TITLE
Epic: workbook refinement 

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#1471]
## Description

Once workbooks are completed, add more data validation, formatting, etc.

**Who**: Submitters
**What**: Submitting valid data
**Why**: Because we want confidence that forms will be submitted correctly

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1431
- [ ] https://github.com/GSA-TTS/FAC/issues/1175
- [ ] https://github.com/GSA-TTS/FAC/issues/1227
- [ ] https://github.com/GSA-TTS/FAC/issues/1269
- [ ] https://github.com/GSA-TTS/FAC/issues/1435
- [ ] https://github.com/GSA-TTS/FAC/issues/1513
- [x] Add `OTHER_CLUSTER` (in `Base`) to the list of cluster names allowed (per HDMS) in the Jsonnet validation
- [x] https://github.com/GSA-TTS/FAC/issues/1617
- [ ] https://github.com/GSA-TTS/FAC/issues/1660
- [ ] https://github.com/GSA-TTS/FAC/issues/1473
- [ ] https://github.com/GSA-TTS/FAC/issues/1472
- [ ] https://github.com/GSA-TTS/FAC/issues/1519
- [ ] https://github.com/GSA-TTS/FAC/issues/1470
```

#1341 will close via this epic.
