### ISSUE TITLE
Cross-validation: All workbooks are the same version

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1474]
## Validation Description

We are now versioning workbooks. All workbooks submitted should have the same version.

**WARNING**: #1314 will answer whether this validation is needed. This is a pre-emptive ticket. See the resolution of #1314 before beginning work on this validation.

[//]: # (A description of the validalidation in plain language.)

## Section(s):
- [x] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [ ] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [ ] This generates one error
- [ ] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"You are attempting to upload workbook version 1.2; we are using workbook version 2.2. Please download a new workbook and copy your data in, and resubmit."
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
VERSION_2023071357
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```

**Comment by jadudm** [comment]
Done.
