### ISSUE TITLE
Epic: Workbook change management

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1477]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: The auditor/auditee community
**What**: Will be impacted by changes made to submission workbooks
**Why**: Because a change could interrupt or confuse work in-progress.

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1478
- [ ] https://github.com/GSA-TTS/FAC/issues/1479
- [ ] https://github.com/GSA-TTS/FAC/issues/1480
```
