### ISSUE TITLE
Validate UEI's and return entity data from SAM.gov

### ISSUE THREAD

**Issue by NicholasKramer** [GSA-TTS/FAC#148]
**Background**

We need to validate UEI's that pass local validation with [SAM.gov](http://sam.gov/).

We have a piece on the backend for local validation, which confirms that the UEI meets the standards we can reasonably validate locally, but now we need a component that can validate the UEI against SAM.gov.

It covers the following stories:

1. As a user I can enter a UEI and receive feedback on the validity so that I can be sure I've entered the correct UEI.

**We'll know we're done when...**
- [x] When a user submits a UEI that meets local validation but does not validate against the SAM.gov API, they receive a helpful error message
  
**Tasks**
- [x] Create a SAM.gov API account (Engineering)
- [x] Propose and implement UEI validation using SAM.gov (Engineering)
- ~~[ ] Front end implementation to perform validation and render error message(s) (Engineering)~~

**Definition of Done**

- [x] Meets technical definition of done
- ~~[ ] Usability tested~~
- ~~[ ] FE test suite updated to test the form~~
- [x] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by NicholasKramer** [comment]
Proposed UEI validation and processing flow:

- We'll reach out to the SAM.gov API upon UEI entry only as part of the serializer validation.
- We'll be using V3 of the SAM.gov API:  https://api.sam.gov/entity-information/v3/entities? gathering data in the JSON format.
- We'll be using the SAM.gov API data to validate the UEI.  There is quite a bit of information we may also use.  TBD.

**Comment by geekygirlsarah** [comment]
Given ticket #170 exists to do the front end implementation of this, I think the task "Front end implementation to perform validation and render error message(s)" can be removed, and since it's the backend only for this ticket, the "usability testing" and "FE test suite updated to test the form " criteria can be removed.

**Comment by Jkrzy** [comment]
Thanks @geekygirlsarah, coming out of our conversation earlier this afternoon.

I'm going to self-assign this one and take it through a round of testing to confirm the validation and API calls here are working as expected before moving it to done.

**Comment by Jkrzy** [comment]
Functionality works as expected testing locally and on the deployed cloud.gov dev instance! Thanks @tadhg-ohiggins, @NicholasKramer, @geekygirlsarah!

I think there's some opportunities to refine this in terms of the shape of the response to the client and logging would be particularly helpful, but let's tackle those in new issues.
