### ISSUE TITLE
Epic: Helpdesk process

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1484]
As a team, we need a way to process, triage, assign, and respond to help desk inquiries. We can revise this process at a later date, but we should have *something* documented, in place, and communicated publicly when we open our doors.

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1485
- [ ] https://github.com/GSA-TTS/FAC/issues/1486
- [ ] Document process in a PDR (Product Decision Record) in GH.
- [ ] Revisit in 3 months (or sooner)
```

**Comment by danswick** [comment]
@jadudm should we add this back to the epic board?

**Comment by Carley-Sullivan** [comment]
I vote for effectively done, too.

**Comment by jadudm** [comment]
Effectively done!
