### ISSUE TITLE
Research spike: Discovery + usability testing planning with Auditees

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#150]
**Background**
We don't know enough about the needs of auditees and have yet to talk with any directly. 

My hope is that we can schedule 1 hour test sessions with auditees and spend half the session observing/understanding how they work and then the other half actually testing the data submission side of things (creating a new audit, entering SF-SAC "general info" form data). 

Aiming to schedule these interviews for 5/4/22-5/6/22.

**We'll know we're done when...**
- [ ] We have conducted research sessions with auditees.

**Tasks**
- [x] Articulate research qs and design hypotheses
- [x] Write research plan
- [x] Create any artifacts for testing
- [x] Recruit participants (#151) 
- [x] Conduct test sessions (#460, https://github.com/GSA-TTS/FAC/issues/473)

**Comment by MelissaBraxton** [comment]
@austinhernandez, @sreuber, and @brentryanjohnson - Shell of a research plan is [here](https://docs.google.com/document/d/1J8TlQXs05g6NTWnT9uBPG4dw9NsZZpca6z3ItLEaSrQ/edit#). Feel free to pile on the research Qs we can go back and prioritize and organize these around scenarios/script the actual protocol later on.

**Comment by MelissaBraxton** [comment]
We are going to hold off on this for a few weeks. Moving back to the backlog.

**Comment by austinhernandez** [comment]
With a recent turn over in teammates, and three designers developing new screens and content, we need to be able to get consistent on design and track which questions we want to ask of our next round of usability testing. 

I added to the research plan Melissa added above and created a figma prototype file that we can use to upload "finalized screens.

1. [Research plan for auditees ](https://docs.google.com/document/d/1J8TlQXs05g6NTWnT9uBPG4dw9NsZZpca6z3ItLEaSrQ/edit#heading=h.4zb6gfafw38g)
2. [Figma prototype file that we will use for testing](https://www.figma.com/file/8REinLFKSMj7pwQ7JIEHGW/FAC-Sprint-11-prototype?node-id=0%3A1)
