### ISSUE TITLE
Recruit auditees for user research

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#151]
**Background**
This is recruiting users for research covered in #150. 

**We'll know we're done when...**
- [x] We have interviews with 8 agency auditees on the books
- [ ] At least 3 of the participants work with tribal auditees and/or organizations that serve historically underrepresented groups. 

**Tasks**
- [x] Email auditor contacts for connections to their auditees
- [x] Refine recruitment criteria
- [x] Draft recruitment email
- [x] Email participants
- [x] Add interview times to the FAC-team calendar

**Comment by MelissaBraxton** [comment]
Drafting instructions/process for Melissa Avalos [here](https://docs.google.com/document/d/16UpgQbFOh5F9RLkTGHEsgHyTBC_O65y6nZSiFOvxHjg/edit#heading=h.5pa9w461cm0n). Will assign her to this issue once she has TTS GH access.

**Comment by MelissaBraxton** [comment]
Moving this back to the backlog until we're ready to push this round of research forward.

**Comment by melchoyce** [comment]
Update: we weren't able to speak to any tribal auditees, but we're having Census keep an ear out for us.
