### ISSUE TITLE
Limit intake length on all text fields in workbook specs, schema

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1510]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** control data taken into the system
**as a** system owner
**I want** limits and validations on the intake.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: Someone decides to put 32K characters in every text field in a spreadsheet, up to a max of 3000 rows.

**Given**   that this has no basis in legitimate submission
**when**  we encounter something outside of reasonable limits
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] The federal awards workbook limits text fields to 3000 chars
- [ ] The audit findings workbook limits text fields to 3000 chars
- [ ] The audit findings text workbook limits text fields to 30000 chars
- [ ] The notes to SEFA workbook limits text fields to 30000 chars
- [ ] The CAP text workbook limits text fields to 30000 chars
```

UPDATE:

We could catch this all in the validation schema.

Everywhere we use `Types.string`, we could instead use a function. `string_min_max(0, 256)` would return an object that looked like

```
{
   type: string,
   minLength: 0, 
   maxLength: 256
 }
```

It might also need an error field that can be pulled by the frontend. That error would also be produced by a function. `string_min_max_error(0, 256)`. That way, the error could explictly say what the limits were that were being adhered to. 

This would save us from trying to hit the workbooks, but instead would move the validation to the schema, where it belongs. 

We should set reasonable limits. For example, an address field might want 300 characters, but the notes fields for things like findings text something close to the Excel limit (30,000). 

Base.const should have a few max values set.

```
Base.const.small_string = 64
Base.const.medium_string = 256
Base.const.large_string = 4096
Base.const.extra_large_string = 30,000
```

Then, the functions might be simplified. `Func.small_string()` and `Func.small_string_error()` would "just do the right thing." They could use the constants, and all call one `string_min_max` underneath.

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Engineering shepherd: @sambodeme 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

I don't know what the appropriate limits are for intake. Perhaps it should not be 3K/30K. Lets make some judgement calls and note them in the conversation below before implementing (or update the ticket).

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

Limiting user input in text fields matters for potential denial-of-service attacks on storage space/processor time.

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] [something we'll definitely have to do]
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
@sambodeme , @danswick , for consideration when we get to this ticket.

https://github.com/GSA-TTS/FAC/tree/jadudm/string-limits-in-schema

**Comment by jadudm** [comment]
I'm less concerned with the "what if they fill a workbook," and more that we make sure we have limits on every string field. Most are regexes with `^` and `$`. But, a few need limits.

We limit the overall size of the workbook on intake, so in the end... that protects us from large files/large fields/etc. (For now.) Adding `Func.string_small()` or `Func.string_extra_large()` would tighten up the schemas.

I don't know if we need to add error text to the object(s) yet, but see the above note. We probably want it, so the front-end gets a nice error of someone exceeds the limits.

**Comment by danswick** [comment]
Is this still a concern, @jadudm?
