### ISSUE TITLE
Make dissemination fields permissive in their typing

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1511]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** move data to dissemination (ours or historical)
**as a** data engineer / product owner
**I want** to know the data will always make it over without truncation.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: We are transferring data, and misjudged field limits on a text field.

**Given**   that this will truncate data silently
**when**  this is possible, we should eliminate the possibility.
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### Therefore
- [ ] General: Transform all columns to TEXT, NUMERIC, DATE
- [ ] Auditor: Transform all columns to TEXT, NUMERIC, DATE
- [ ] FederalAward: Transform all columns to TEXT, NUMERIC, DATE
- [ ] Passthrough: Transform all columns to TEXT, NUMERIC, DATE
- [ ] Note: Transform all columns to TEXT, NUMERIC, DATE
- [ ] FindingText: Transform all columns to TEXT, NUMERIC, DATE
- [ ] Finding: Transform all columns to TEXT, NUMERIC, DATE
- [ ] CAPText: Transform all columns to TEXT, NUMERIC, DATE
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Engineering shepherd: @gsa-suk 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

1. We want to make sure the dissemination tables will never silently throw away data. Make them permissive.
2. We can always optimize this later based on analysis of the data.

We're relying on [this Stack Overflow](https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying) post and [article from 2010](https://www.depesz.com/index.php/2010/03/02/charx-vs-varcharx-vs-varchar-vs-text/) to make this call. 

This led to modifications to the manual (perhaps around the v9 series of PostgreSQL). 

[Link](https://www.postgresql.org/docs/9.1/datatype-character.html), text:

> Tip: There is no performance difference among these three types, apart from increased storage space when using the blank-padded type, and a few extra CPU cycles to check the length when storing into a length-constrained column. While character(n) has performance advantages in some other database systems, there is no such advantage in PostgreSQL; in fact character(n) is usually the slowest of the three because of its additional storage costs. In most situations text or character varying should be used instead.

There is no reason for us to try and limit the size of text/numeric fields in our DB, given the scope and scale of our data collection/historic archive. We can optimize later if this ceases to be true. For now, it is more important to never lose data silently due to a truncation.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There should be no security considerations to modifying the shape of our dissemination tables. They are only interacted with (for write) from our system, not by outside systems. It does not impact users querying the data via the API.

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] [something we'll definitely have to do]
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by danswick** [comment]
Is this complete after the `intake_to_dissemination` work, @jadudm?

**Comment by jadudm** [comment]
Yes.
