### ISSUE TITLE
Cross-validation: Check award references in Federal Awards and Audit Findings

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1514]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

~~This is just a "shape" check. We want to confirm that the award numbers are all of the form~~
~~`AWARD-####`~~
This is to verify the existence of the award_reference field, ensuring that it is neither null nor empty.

The shape check is done through the schema; however, marking this field as required in the schema breaks our unit testing. Therefore, we decided to address this issue in cross-validation.

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [x] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [ ] This generates one error
- [x] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

~~f"Award reference {award_ref} does not match the pattern `AWARD-####`."~~

```python
f"The award listed in row {row_num} of your Federal Award workbook is missing a reference code. This should not be possible. Please contact customer support."
```
### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
AWARDREF-202307171104
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```
