### ISSUE TITLE
Document configuration management plan

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1522]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** meet ATO requirements
**as a** FAC system owner
**I want** a documented Configuration Management plan.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 

**Given** I am looking at the FAC GitHub repository
**when** I click into the `docs` subdirectory 
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [ ] there is a document named "configuration-management.md"
- [ ] the document describes the CM processes we have in place
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: N/A
* Engineering shepherd: @mogul 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"
We have a tentative assessment finding: Our Configuration Management plan isn't documented. If we document it before Aug 10th, it can be incorporated into our assessment and not be an actual finding.

For reference (though this is way more complex since it's for the full cloud.gov PaaS)...
https://cloud.gov/docs/ops/continuous-monitoring/

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

None, this will be a public document that documents public information.

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [x] Start from an existing CM from another GSA team hosting on cloud.gov
- [ ] Modify accordingly
```

---

<details>
  <summary>Process checklist</summary>

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [x] Has a clear story statement
- [x] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [-] Has clearly stated/testable acceptance criteria
- [-] Meets the design Definition of Ready [citation needed]
- [-] A design shepherd has been identified

## Design In Progress

- [-] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [-] Necessary outside review/sign-off was provided

## Design Done

- [-] Presented in a sprint review
- [-] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [x] Has clearly stated/testable acceptance criteria
- [x] Has a sketch or list of tasks
- [x] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by mogul** [comment]
I asked in #g-security-compliance for examples from other cloud.gov-hosted systems which we can use as a starting point. (The cloud.gov team one is very large, which fits their system, whereas other cloud.gov-hosted systems will operate much more similarly to ours.)

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 Is there a first draft that can be added to the repo or linked in this ticket?

**Comment by mogul** [comment]
The [SAR did not find the lack of an explicit "CM" a finding, they just asked that we remove that language from the SSP](https://docs.google.com/document/d/1vzO_KCxv3hLiJ675vMWNDV4ikJ9YbMgp5ZN7_gktjRM/edit). I reworded [the reference in CM-2(2)](https://docs.google.com/document/d/1s9kban5PaQpW9BDABcVQvV1wxWEDfVcY1QZp0trnSFY/edit#heading=h.1tuee74) in Suggest mode.

**Comment by jadudm** [comment]
This was previously marked as done, and was done. Closing.
