### ISSUE TITLE
Epic: Pre-signoff review of submission

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1527]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** certify an audit
**as a** certifying official
**I want** to see the full submission in one place.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: I'm an auditor certifying official who only enters the FAC when I need to "sign off."

**Given** that I don't know what was entered into the *web form* portions of the SF-SAC  
**when**  I go to certify
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] A link should be available to me on the submission checklist page to "review the full single audit submission"
```

The single audit submission overview should be a web page that meets the following criteria:

```[tasklist]
### Tasks
- [ ] Pre-SAC contents are rendered to the submission overview page
- [ ] General information contents are rendered to the submission overview page
- [ ] Audit information contents are rendered to the submission overview page
- [ ] Federal awards contents are rendered to the submission overview page (as HTML tables)
- [ ]  Audit findings contents are rendered to the submission overview page (tables)
- [ ] Audit findings text contents are rendered to the submission overview page (tables)
- [ ] CAP text contents are rendered to the submission overview page (tables)
- [ ] Notes to SEFA contents are rendered to the submission overview page (tables)
- [ ] Additional UEIs contents are rendered to the submission overview page  (tables)
- [ ] Secondary auditor contents are rendered to the submission overview page  (tables)
``` 

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

The concern is that a certifying official often comes into the process *at the end*. And, while the team could share with them the audit workbooks (for example), there is no way for the submitting team to share the contents of the web forms. If we don't render out the forms, it is possible for our users to be concerned about "signing off" on an audit that they cannot view the full contents of.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no particular security concerns to rendering public data out to a user, within the app, who has permission to see the data.

# Sketch

This is  a View in liquid tags.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
I ticketed this a second time. Closing this as "not planned" to use the newer epic.
