### ISSUE TITLE
Epic: API v1 iteration

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1539]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Developers using the API
**What**: have questions and possible changes
**Why**: because v1.0.0-beta is not *quite* there yet.

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1540
- [ ] https://github.com/GSA-TTS/FAC/issues/1541
- [ ] https://github.com/GSA-TTS/FAC/issues/1542
- [ ] https://github.com/GSA-TTS/FAC/issues/1543
- [ ] https://github.com/GSA-TTS/FAC/issues/1544
- [ ] https://github.com/GSA-TTS/FAC/issues/1545
- [ ] https://github.com/GSA-TTS/FAC/issues/1546
- [ ] https://github.com/GSA-TTS/FAC/issues/1547
- [ ] https://github.com/GSA-TTS/FAC/issues/1548
- [ ] https://github.com/GSA-TTS/FAC/issues/1549
- [x] Itemize all fields in the API (no table.*)
- [x] Remove type limitations in dissemination model (e.g. TextField, not CharField(2))
```

**Comment by jadudm** [comment]
The source for these questions is in our drive: https://docs.google.com/document/d/1EV3cppSY40jzT0-1oerzwFbtRdDCN8VS/edit

I have done my best not to change our colleague's questions. They've been reformatted/broken out as tickets as part of this epic.
