### ISSUE TITLE
Question: Duplication of data across tables?

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1542]
From our colleagues:

> Each table now has the following six  fields: “report_id”, “auditee_uei”, “auditee_ein”, “fy_start_date”, “fy_end_date”, and “audit_year”. 

1. Is “report_id” alone sufficient to link data across tables, or are one or more of the other fields required as well?
2. When resubmissions are implemented, will a “version” field also be added to every table?
3. Can the v0-style foreign keys (i.e. “federal_award_id”, “finding_id”, etc) be added back in to the General table?

```[tasklist]
### Tasks
- [ ] Address the questions through discussion in the comments of this ticket.
- [ ] Address this question in the `design.md` document that is added to the static site at `/docs/api`.
- [ ] Update views and/or models as appropriate, given the discussion on this ticket.
```

**Comment by jadudm** [comment]
## Regarding Q1

@JeanMarie-TTS , @pluribus-tony , @gsa-suk : do we have duplication of data across the API endpoints as described? Is this because of how the views are constructed, or the underlying table design?

Should we have this duplication? My suspicion is "no," but we should discuss it here, so we can document the design decision, and communicate it back.

## Re: Q2

We have prior discussion on this in #1067, and ultimately came to a simpler model. That simpler model chose not to store a tree so much as track the "source" audit for all revisions.

Each resubmission will be complete, new audit, but we will track (likely in the `general` view) the version number, as well as the parent/originating audit. Given that `report_id` is a PK/FK, it does not seem to be necessary to put a version number in every table. 

Note: we have outstanding questions about exposing old versions, at least to the public. I would like to understand prior behavior in terms of data dissemination to Federal partners. We can discuss/co-design what we do here.

## Re: Q3

We explicitly rolled this back, because the linking was part of where we got ourselves into trouble. Given that we still do not have reliable, historical data in hand, we are not going to attempt to do any FK/back-linking relationships. We know this is less convenient, but it is easier for us to guarantee correctness this way.

We can discuss/consider this v1.1 (if it is a non-breaking change to add this), or v2 (if this is a breaking change).

**Comment by jadudm** [comment]
The reason for the duplication *in the views* of those fields was to reduce API traffic and facilitate search. For example, if you know the UEI you're looking for, you can go straight to `/findings` and search for that UEI. Note that this is **not** a duplication of data in the underlying database, but instead an exposure of those fields in the *view*. 

We think it would be simpler to not duplicate these, and instead encourage this workflow:

1. You query general (perhaps) to search for `auditee_uei`, and from there, get the `record_id`. 
2. Using that `record_id`, grab data from the other endpoints.

We can, if it is deemed critical/performant as we go to production, introduce fields to the view in a non-breaking way. *Removing* fields from the view *will be a breaking change*. Therefore, we think we should minimize now, and expand as needed. Thoughts?

**Comment by jadudm** [comment]
Because some revisions may include material errors (e.g. inclusion of private information/PII), we need to think about what is exposed, where.

We still have design conversation underway regarding how we will be handling revisions, and how we bring revisions over from the historic data. So, we'll develop an epic around this, and have a space for further conversation and documentation.

**Comment by jadudm** [comment]
We're pretty sure (re: Q3) that in any given row, the `report_id` can be used to go from (say) `/findings` back to `/general` with no loss of fidelity.
