### ISSUE TITLE
Missing: Passthrough

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1544]
From our Federal partners:

> Passthrough, which had the fields PASSTHROUGHNAME (Name of Pass-through Entity) and PASSTHROUGHID (Identifying Number Assigned by the Pass-through Entity). This table was present in v0. I don’t see a field to name passthrough entities anywhere in the v1 specs.

```[tasklist]
### Tasks
- [x] Address the questions through discussion in the comments of this ticket.
- [ ] Address this question in the `design.md` document that is added to the static site at `/docs/api`.
- [ ] Update views/models as appropriate based on this discussion
```

It is possible/likely additional ticketing will be necessary if further work/revision is warranted.

**Comment by jadudm** [comment]
Flagging @pluribus-tony to follow up; we're confident this was added after we locked the system down for ATO review.

**Comment by jadudm** [comment]
These have been added to `/federal_awards`. If this is not appropriate, or otherwise does not address the question, we should revisit it. Closing.
