### ISSUE TITLE
Epic: Taming ALNs

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1555]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Everyone who deals with Federal grants.
**What**: Has to deal with the Assistance Listing Number.
**Why**: Because we can't have nice things.

The ALN is a very poorly designed number. It has two parts: the agency prefix, and a program... suffix? They have the general shape:

`##.###`

These numbers are supposed to uniquely represent agencies and their programs. This is, of course, **horrible**. 

There are more than 100 grant-making agencies, so some agencies have to share the first two digits. And, some programs have more than 1000 granting programs. Or, they have to recycle program numbers over time, meaning `.123` was one program a decade ago, but is something else now. Because of these limitations, some agencies have developed their own extensions... effectively changing the identifier, but also breaking the system in inconsistent ways.

If these were changed to hexidecimal values, we might buy some headroom: we would have (16^2-1) agencies available (255) and and 4095 program lines. This *might* fit in existing database systems, but ultimately, it's just a horrible identifier. 

Better would be to consider a reverse domain system:

`gov.gsa.2023.art-for-public-buildings`

which would suggest that it was a program by the GSA, in 2023, and it was about funding public art in buildings. (This is something made up for this example.) *Anything* would be better than what we have now. 

All of that said, we have to work with it *for now*. 

## For investigation and possible implementation

This epic is for us to investigate, discuss, and consider implementing a solution to tracking ALNs over time as part of the FAC. 

### Cache the data

First, we could grab the list of current ALNs from sam.gov every day.

https://sam.gov/data-services/Assistance%20Listings?privacy=Public

Then, we could store that in a table.

| fac_funding_id  | agency_number | program_number |  department | published_date | first_seen | last_seen | agency | samgov_link | hash | 
|---|---|---|---|---|---|---|---|---|---|
| gov.usda.forest-service.2022.opal-creek-wilderness-economic-grant-program | Opal Creek Wilderness Economic Grant Program | 10 | 726 | FOREST SERVICE, AGRICULTURE, DEPARTMENT OF | 2022-08-10 | 2023-07-03 | 2023-07-23 | USDA | https://sam.gov/fal/1676ff50744642b98a2a58f005ccf0d9/view  | f78130... |
| gov.usda.forest-service.2023.inflation-reduction-act-urban-community-forestry-program | Inflation Reduction Act Urban & Community Forestry Program | 10 | 727 | FOREST SERVICE, AGRICULTURE, DEPARTMENT OF | 	2023-02-03 | 2023-07-03 | 2023-07-23 |  USDA | https://sam.gov/fal/37ef4e1b5d4a4592854a971f40c885e1/view  |  01f67... |
| gov.usda.forest-service.inflation-reduction-act-hazardous-fuels-transportation-assistance | Inflation Reduction Act Hazardous Fuels Transportation Assistance | 10 | 728 | FOREST SERVICE, AGRICULTURE, DEPARTMENT OF | 2023-02-03 | 2023-07-03 | 2023-07-23 | USDA | https://sam.gov/fal/ae1cd60037f74334ac2651e87d41e92d/view  | 329d42... |
| gov.usa.forest-service.inflation-reduction-act | Inflation Reduction Act - National Forest System | 10 | 729 | FOREST SERVICE, AGRICULTURE, DEPARTMENT OF | 2023-02-27 | 2023-07-03 | 2023-07-23 | USDA | https://sam.gov/fal/a64ab147f19a4eb39c5366ec73225282/view  | 196a22... |

Our algorithm might look like:

1. Grab the data daily.
2. For each row...
    1.   Hash the `program_name`, `agency_number`, `program_number`, `department`, `published_date`, and  `agency`. As long as the hashed value is the same, we'll assume it is the same program. 
    2. If we have never seen the program before, insert into the table. Set `first_seen` and `last_seen` to today.
    3. If we have seen the program before (hashes are equal), then just update `last_seen`.

### Begin fixing the system

At this point, we can also assign a `fac_funding_id`. This would be a human-readable, reverse-domain-style ID. (Or, we design some other identifier.) Because this is our table, we can do what we want. By creating a new, improved ID (with an infinite name space), we can now use this in the SF-SAC collection (say, hypothetically speaking).

So, we could ask auditors and auditees to look their program up in our table. We can drive AROs to our table to verify/validate. Because we are keeping track of all of the data published by Grants.gov, but doing so in a way that adds critical information (when was a given program available, as opposed to just publishing what is available *today*?), we are adding value that we desperately need to inject integrity into the grant funding tracking ecosystem.

# In summary

We can, and should, improve the situation regarding ALNs. We don't have to wait for OMB, or an all-government coalition to spend 3 years arguing about the design, and another 5 years to run a task force to fail to implement things. We can (in community with our partners) pilot this, and by *doing*, provide a clear roadmap for where government should go. Even if we have to change our design, if we inspire change and improvement, we will have succeeded.

We will, ultimately, break the `cron` investigations out into separate epics. We simply don't have an architecture for it at the time of this ticket's writing.

```[tasklist]
### Stories
- [ ] Investigate architectures and tools for managing `cron` jobs in a system. (E.g. [Cronicle](http://cronicle.net/))
- [ ] Design, implement, prototype `cron` automation for fetching data.
- [ ] Design, define, and in PDR, describe the `fac_funding_id`. 
- [ ] Pilot integration of `fac_funding_id` in API, intake.
```
