### ISSUE TITLE
Epic: Figma is the source of truth

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1556]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

We are approaching preview and launch. Is everything in Figma accurate and true?

**Who**: Developers on the team.
**What**: Are working on finishing the application.
**Why**: Due dates.

Unlike some permissive profs we know (*cough*) there are no extensions to this due date...

For each page listed, the associated ticket has checkboxes for design, content, SME signoff, and product signoff. Where possible, links to the Figma are provided.

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1557
- [ ] https://github.com/GSA-TTS/FAC/issues/1558
- [ ] https://github.com/GSA-TTS/FAC/issues/1559
- [ ] https://github.com/GSA-TTS/FAC/issues/1560
- [ ] https://github.com/GSA-TTS/FAC/issues/1561
- [ ] https://github.com/GSA-TTS/FAC/issues/1562
- [ ] https://github.com/GSA-TTS/FAC/issues/1563
- [ ] https://github.com/GSA-TTS/FAC/issues/1564
- [ ] https://github.com/GSA-TTS/FAC/issues/1565
- [ ] https://github.com/GSA-TTS/FAC/issues/1566
- [ ] https://github.com/GSA-TTS/FAC/issues/1567
- [ ] https://github.com/GSA-TTS/FAC/issues/1568
- [ ] https://github.com/GSA-TTS/FAC/issues/1808
```
