### ISSUE TITLE
Apply final front-end edits to audits homepage

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1557]
```[tasklist]
### Tasks
- [ ] Front-end visits Django view and confirms content matches Figma.
- [ ] Front-end visits Django and makes spacing, layout look reasonable. 
``` 

These mocks are not pixel-perfect. We assume at this moment that front-end devs are using their judgement to reasonably space things on the page.

Page is here: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=241-3300&mode=design&t=9KUnCaxLNfGrbSC3-4

-----

```[tasklist]
### Tasks
- [x] Design complete
- [x] Content complete
- [x] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [x] SME signoff
- [x] Design lead signoff
- [x] Product signoff
- [x] Content signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy I made some proposed design changes to [the Figma mock](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=221-3144&mode=design&t=S2WsY76ymUneqU4t-4). From a content/copy perspective, I think this is good to go.

**Comment by lauraherring** [comment]
@jadudm, @thebestsophist , @Carley-Sullivan This page is done from content and design perspective and ready for reviews. See previous comment for direct link.

**Comment by jadudm** [comment]
The audit page is covered in red. What does that mean? @Leighdiddy ?

**Comment by lauraherring** [comment]
@jadudm Leigh is out sick today. I think you're looking at the FAC homepage (I just clarified in our section titles in Figma). This ticket is for the "audit submissions home". Try [this link](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=241-3300&mode=design&t=fNyYLftTVJ5aDxxD-4) and see if that takes you to the specific page.

**Comment by Carley-Sullivan** [comment]
Looks good to go.

**Comment by jadudm** [comment]
Should this say "from 2022 and earlier?"

**Comment by lauraherring** [comment]
@jadudm I think I've asked this about a dozen times as well and always manage to confuse myself. @Carley-Sullivan, are the dates on this page correct?

**Comment by Carley-Sullivan** [comment]
@lauraherring left a comment on figma screen for consideration.

**Comment by lauraherring** [comment]
Thanks, @Carley-Sullivan. I've updated the copy based on your feedback.

**Comment by James-Paul-Mason** [comment]
@lauraherring I left two comments for consideration (minor string revision suggestions).

**Comment by lauraherring** [comment]
Good flags, @James-Paul-Mason. The first one I made your change. The trick with the second one is that there isn't currently a way to search audits in progress. Users can only see those audits that are assigned to their email address. That said, I chatted through this with @thebestsophist and came up with something like this, suggesting to users that they ask around with their team as well. Thoughts from both of you?

Before beginning a new audit submission, make sure one isn't already in progress. Audit submissions assigned to your email address will show above. We also recommend confirming with your team as well.
