### ISSUE TITLE
The pre-screener is a source of truth.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1559]
```[tasklist]
### Tasks
- [x] Figma update to fix whitespace/vertical alignment
- [ ] Front-end visits Django view and confirms content matches Figma.
- [ ] Front-end visits Django and makes spacing, layout look reasonable.
```

These mocks are not pixel-perfect. We assume at this moment that front-end devs are using their judgement to reasonably space things on the page.

Page is here: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=241-3300&mode=design&t=9KUnCaxLNfGrbSC3-4

----

```[tasklist]
### Tasks
- [x] Design complete
- [x] Content complete
- [x] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [x] SME signoff
- [x] Design lead signoff
- [x] Product signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy I think we should co-work on these screens for a bit.

**Comment by lauraherring** [comment]
@Leighdiddy and I are both set for the design and content on the pre-screening screens and they're ready for review. There are 3 screens under "[Begin new audit submission](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=1-19394&mode=design&t=S2WsY76ymUneqU4t-4)" in Figma

**Comment by thebestsophist** [comment]
I think this is good enough as is but potential low-effort question:

On step 3, the submission access screen in the `Key information` section:

During the last round of UAT, I think folks were surprised that they were only entering email addresses and not people's names as well, would it be helpful to had some clarity to the "List anyone who will need access to the audit submissions to enter or edit information" bullet? like "List email addresses for anyone…you will be able to provide the names for the certifying officials at a later step" or something along those lines?

(Signing off since i don't think this is necessary, just helpful."

**Comment by jadudm** [comment]
I'm closing out the "source of truth" workstream. We have come well within 97%, and should now step back and decide what our process will be going forward. And, any remaining edits are that: refinements and edits to what is.
