### ISSUE TITLE
The workbook upload page is a source of truth.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1563]
```[tasklist]
### Tasks
- [ ] Add a link to the workbook as part of the template for these pages.
- [ ] Add a link to the instructions as well.
``` 
Page title: Workbook upload
Body copy: Download the workbooks below to complete and re-upload for the single audit submission. For every submission, the auditee entity must upload workbooks 1-4. Workbooks 5-7 are optional, depending on the scope of the single audit.
- Workbook 1: Federal Awards
- Workbook 2: Federal Awards Audit Findings
- Workbook 3: Federal Awards Audit Findings Text
- Workbook 4: Corrective Action Plan
- Workbook 5: Additional UEIs (optional)
- Workbook 6: Secondary Auditors (optional)
- Workbook 7: Additional EINs (optional)

[Submission instructions/interface]

---

@Leighdiddy , if you want to either 1) describe in words where it goes, or 2) put it in Figma (whichever is faster), that should be enough for the FE devs to be getting on with.  Move to Eng Avail when you're done.

```[tasklist]
### Tasks
- [ ] Design complete
- [x] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [ ] Design lead signoff
- [ ] Product signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy Let's cowork on this one, weren't we going to combine all the pages into one so that it's just the same page for each upload?

**Comment by lauraherring** [comment]
@jadudm and @jperson1 Can the four of us (plus @Leighdiddy) sync on this page and what's already built vs needed? Design is a little confused on where this stands at the moment.

**Comment by jadudm** [comment]
We're not going to block on the Figma updates for this.

Updating the checklist and moving to Eng Avail.

**Comment by lauraherring** [comment]
@Leighdiddy I've written the copy for this in the description above as @jadudm requested. Let me know if you have any questions/if there's anything else you need me to do to move this forward.

**Comment by jadudm** [comment]
https://github.com/GSA-TTS/FAC/issues/1899 is going to close this.

**Comment by jadudm** [comment]
I'm closing out the "source of truth" workstream. We have come well within 97%, and should now step back and decide what our process will be going forward. And, any remaining edits are that: refinements and edits to what is.
