### ISSUE TITLE
Request a SAM.gov System Account

### ISSUE THREAD

**Issue by NicholasKramer** [GSA-TTS/FAC#158]
**Background**

Break-off from issue #126 

We need a component that can validate the UEI against SAM.gov.  In order to do that, we need a SAM.gov system account.

Documentation on how to request a SAM.gov system account:  https://www.fsd.gov/gsafsd_sp?id=gsafsd_kb_articles&sys_id=f8426db91b594d9006b09796bc4bcb52

**Tasks**
- [x] Create a SAM.gov account
- [x] Follow the steps in the [knowledgebase](https://www.fsd.gov/gsafsd_sp?id=gsafsd_kb_articles&sys_id=f8426db91b594d9006b09796bc4bcb52) to request a SAM.gov system account

**Definition of Done**

- [ ] Tested SAM.gov system account
- [ ] Works against the API

**Comment by NicholasKramer** [comment]
Initial work:  I've created a SAM.gov account under my login.gov identity and requested an Entity Display Viewer Role.  After getting the role, I can request the System Account.

**Comment by NicholasKramer** [comment]
Current progress: waiting for account approval.  Once my account is approved, I can request a System Account.  I'm using my personal API key in the repository for testing - this will change once a System Account is approved.

**Comment by petermarks-gsa** [comment]
Per my conversation with @NicholasKramer, I got his confirmation email and escalated this to Memi.

**Comment by NicholasKramer** [comment]
I now have access to the System Accounts workspace through a system manager role, and have drafted a request for a new FAC system account.  

The draft request can be found [here](https://sam.gov/workspace/system/new/3996) (requires a System Manager role to access).  Currently waiting for Joe and Matt J to receive the System Manager role to add them to the System Account request.

There are additional requirements to complete the System Account request, including having an assigned ISSO.

**Comment by NicholasKramer** [comment]
To follow-up, I requested a System Account with Joe and Matt J as System Managers, with Matt J also listed as the security POC.  The request is now in process with no estimate of how long it will take - I will keep this issue updated with progress.

**Comment by petermarks-gsa** [comment]
@NicholasKramer @tadhg-ohiggins Per communication with [james.tsujimoto@gsa.gov](mailto:james.tsujimoto@gsa.gov)), we will not be able to get a system account set up until we have a completed ATO, which could be months from now. In the meantime, let's focus on transitioning the SAM.gov credentials away from Nick's creds and to Tadhg's (tracking in https://github.com/GSA-TTS/FAC/issues/245)


Moving this ticket to the backlog until we're ready and leaving a few notes
* An upload of that ATO document will be required to pass the Security Review process.
* In order to assign System Manager roles to those individuals, we need first need them to register for SAM.gov accounts.
* send james.tsujimoto@gsa.gov an email about the request
* When you resubmit the account, could you please see if there is a way to list James above Lydia in the application
