### ISSUE TITLE
Clean up remaining TODO items in ETL

### ISSUE THREAD

**Issue by pluribus-tony** [GSA-TTS/FAC#1600]
```[tasklist]
### Tasks
- [ ] Add audit_info fuelds:  general.sp_framework, general.is_sp_framework_required,           general.sp_framework_auditor_opinion
- [ ] Add number_of_months from General Info
- [ ] Add certification details - name, title, signature dates
- [ ] Add foreign address columns
- [ ] Add cognizant/oversight agency fields
- [ ] Resolve the following in General: total_fed_expenditures=None,  # TODO: Where does this come from?             type_report_major_program=None,  # TODO: Where does this come from?
- [ ] Resolve in FederalAward:                 type_requirement=None,  # TODO: What is this?
```

**Comment by JeanMarie-TTS** [comment]
@timoballard , @Leighdiddy  
Do we capture the following?
1. certifying_auditee_name
2. certifying_auditee_title
3. auditor_certificate_signed_date
These are present on the Census certifications page. If they are being captured, where are they being saved in our data model?

**Comment by JeanMarie-TTS** [comment]
@pluribus-tony The following fields should be removed from load_general:
material_weakness - present in audit_info
material_weakness_major_program - not used since 2013
condition_or_deficiency_major_program - obsolets
type_audit_code - always 'UG' for G-FAC, has been 'UG' in CFAC for a few years. Used to be 'A133' before
prior_year_schedule - 
questioned_costs - moved to Finding
type_report_financial_statements - sane as gaap_results in audit_info
current_or_former_findings - boolean field that says whether afencues in audit_info should be populated

**Comment by pluribus-tony** [comment]
https://github.com/GSA-TTS/FAC/pull/1602

**Comment by pluribus-tony** [comment]
https://github.com/GSA-TTS/FAC/pull/1608

**Comment by JeanMarie-TTS** [comment]
@pluribus-tony 
Let's include the following fields in the dissemination model. They will be included in a JSON field or in SAC directly when the certification page is implemented:

1. certifying_auditee_name
2. certifying_auditee_title
3. auditee_certification_date
4. auditor_signature_date

**Comment by JeanMarie-TTS** [comment]
> @pluribus-tony Let's include the following fields in the dissemination model. They will be included in a JSON field or in SAC directly when the certification page is implemented:
> 
> 1. certifying_auditee_name
> 2. certifying_auditee_title
> 3. auditee_certification_date
> 4. auditor_signature_date

The third column should be auditee_signature_date, not auditee_certification_date.

**Comment by JeanMarie-TTS** [comment]
[Census_Certification_Mapping.pdf](https://github.com/GSA-TTS/FAC/files/12177576/Census_Certification_Mapping.pdf)

**Comment by pluribus-tony** [comment]
https://github.com/GSA-TTS/FAC/pull/1616

**Comment by JeanMarie-TTS** [comment]
It was decided at a dev huddle that we would implement a method in audit/models.py to determine the value of is_public.
For now, we should return True if entity_type is not "tribal"

**Comment by JeanMarie-TTS** [comment]
Data type issues:

1. Boolean fields do not need max_length
2. auditee_addl_uei_list should allow nulls
3. auditor_ein (all ein fields) should be of type Charfield rather than Integer. Same datatype as IEI.
4. cognizant_agency, oversight_agency, agency_prefix should all be of the same datatype. Charfield of length 4?
5. total_fed_expenditures, dollar_threshold and any other amount field should have the same datatype. Decimal that can store up to $1_000_000_000.00

**Comment by JeanMarie-TTS** [comment]
@jadudm , we need to link the open tasks listed above to the associated tasks in the pre-ETL process.

**Comment by JeanMarie-TTS** [comment]
Moved remaining open items to #1609
