### ISSUE TITLE
Epic: Establish field parity between dissemination model and intake

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#1609]
As part of the ETL / dissemination development work, we have uncovered some inconsistencies between the ETL/dissemination model and the fields in our intake forms/workbooks. This might mean fields are missing, or there's a mismatch between field names, or that we haven't yet designed a process for handling conditional fields.

This issue is a place to collect those findings so we can batch them up and do one big design / eng update on the intake side. Unless there's a reason to capture disparities in greater detail, a comment below should be enough to keep track.

```[tasklist]
### Tasks
- [ ] #1729
- [ ] https://github.com/GSA-TTS/FAC/issues/1733
- [ ] https://github.com/GSA-TTS/FAC/issues/1734
- [ ] https://github.com/GSA-TTS/FAC/issues/1735
```

**Comment by danswick** [comment]
General form > primary auditor > international address: https://github.com/GSA-TTS/FAC/issues/1603

**Comment by danswick** [comment]
## Missing field: 

General form > `audit_period_months`

This is a conditional field that should appear when `audit_period_type` is `other`

cc @JeanMarie-TTS @tadhg-ohiggins

**Comment by JeanMarie-TTS** [comment]
Completed
