### ISSUE TITLE
Spike for automatic workbook generation - Continuation of Matt Jadud's spike

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#1615]
### Tasks

```[tasklist]
- [ ] Create generator function for additional-ueis
- [ ] Create generator function for notes-to-sefa
- [ ] Create generator function for secondary-auditors
- [ ] Create generator function for corrective-action-plan
- [ ] Test additional-ueis function
- [ ] Test notes-to-sefa function
- [ ] Test secondary-auditors function
- [ ] Test corrective-action-plan function
```

**Comment by jadudm** [comment]
@sambodeme , when I get back in, it would be good to touch base. I know you had some thoughts/questions/concerns around the spike/approach. I'll catch up with you on it next week.

**Comment by gsa-suk** [comment]
The TEXT fields in captext, notes, findingstext, cfda tables contain special characters.  I have pre processed the pipe delimited txt files from Public Census site with https://github.com/GSA-TTS/FAC/blob/sk/load_census_data/backend/load_census_data/Pre_Process_Census_Public_Raw_Data.ipynb.  
Automatic workbook generation for additional-ueis, notes-to-sefa, secondary-auditors, corrective-action-plan is working fine.

**Comment by gsa-suk** [comment]
Added a few checks in generate_findings.

**Comment by gsa-suk** [comment]
The following are the issues noticed with raw public data from Census website:
1.  There are special characters (diacritics) in TEXT columns.
2. There are mixed data types is some TEXT columns.

**Comment by jadudm** [comment]
Added a tool to handle cleaning the data before sqlite conversion.

Closing this; the spike is done. Now, we'll see when/what we do with it.
