### ISSUE TITLE
Add preview environment

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#1631]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** demonstrate upcoming functionality or potential options for feedback from stakeholders without interfering with the staging or production environments
**as a** UX researcher
**I want** a dedicated `preview` environment where specific branches can be deployed.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 

**Given** I am logged into cloud.gov
**when** I look at the set of spaces in the `gsa-tts-oros-fac` organization
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [x] `preview` and `preview-egress` spaces exist
- [x] the spaces are configured as expected (ASGs, access, etc)
- [x] the expected apps are in each space
```

**Given** I am logged into github.com as a FAC repository administrator
**when** I look at the `Actions` tab
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [x] I see a `Deploy Branch to Preview` workflow
- [x] I can invoke the workflow in the context of a particular branch
- [ ] (could) the FAC team receives a notification that a particular branch was deployed to Preview
```

**when** I visit fac-preview.app.cloud.gov
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [x] I see the FAC application branch that was most recently deployed
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: N/A
* Engineering shepherd: @mogul 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

We want a preview environment where we can have non-prod data and/or code live for purposes of demo or UX research. For example, we might have a non-functional or partially functional mock-up of search functionality that we want to watch people attempt to use. The code for that shouldn't ever be in production and may not ever merge to `main`, but we should be able to deploy it from a branch that someone is working on.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

We will be adding this environment using our usual IaC, which will apply all security settings consistent with our other environments. Anyone in the FAC team will be able to kick the workflow that deploys a branch to the preview environment; we don't consider this a risk since it will be on a completely separate domain.

# Sketch

Generally straightforward with the exception of the SMTP credentials

```[tasklist]
# Tasks
- [ ] Bring previously hand-propped things (like deployer accounts) under control of the bootstrap/meta Terraform module
- [x] Add an environment for `preview` and let the meta module create the spaces, ACLs, ASGs, etc. when it's merged to `main`
- [x] Add the `preview` GitHub environment with deployer account secrets
- [x] Add a GHA workflow that deploys the current branch to the `preview` spaces
- [ ] Add a step to the workflow to notify the team.
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [-] Design designs all the things
- [-] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [x] Has a clear story statement
- [x] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [-] Has clearly stated/testable acceptance criteria
- [-] Meets the design Definition of Ready [citation needed]
- [-] A design shepherd has been identified

## Design In Progress

- [-] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [-] Necessary outside review/sign-off was provided

## Design Done

- [-] Presented in a sprint review
- [-] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [x] Has clearly stated/testable acceptance criteria
- [x] Has a sketch or list of tasks
- [x] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by mogul** [comment]
We are deep in it.
https://github.com/GSA-TTS/FAC/tree/bret/refactor-terraform-bootstrap

**Comment by mogul** [comment]
[This DNS PR will need to go through as well.](https://github.com/18F/dns/pull/659#issue-1835653832)

**Comment by mogul** [comment]
The [preview environment went live yesterday](https://fac-preview.app.cloud.gov), and [the additional PR with fixes to enable that](#1754) was merged today.
