### ISSUE TITLE
Implement and document api key management for sam.gov

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#164]
High level: Need to document how we authenticate with SAM.gov API. Need patterns around API key storage and patterns. 

May be blocked by https://github.com/GSA-TTS/FAC/issues/158

**A story for this could be described as...**

As a developer, I need to know how to get a SAM.gov API key and add it to the project so that I can run or deploy the code to be able to access the SAM.gov API.

**We'll know we're done when...**
- [x] When a developer can locally run or deploy this code base and correctly attach a sam.gov API key so the software can use the APIs.
  
**Tasks**
- [x] Create a file in `/docs/` regarding API key management (Engineering)
- [x] Write out the process for acquiring a key from sam.gov (Engineering)
- [x] Write out the process to add the key to environment variables both locally and in production (Engineering)

**Definition of Done**

- [x] Rough draft of support documentation ("exists" not "perfect")
- [x] Usability tested (Someone can perform the steps to correctly go from fresh cloned repo to running instance)
