### ISSUE TITLE
Onboarding checklist for @James-Paul-Mason

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#1656]
# Welcome to the team @James-Paul-Mason!

@jperson1 will be your onboarding buddy and can help you if you get stuck on any of the steps in the checklist below. There's also a separate checklist that your onboarding buddy will tackle!

## For you

Here's a checklist to get you started and to make sure you've got access to :all-the-things:!

- [ ] Review [the project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/) in Google Drive
- [ ] Join the Slack channels in [the project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/)
- [ ] Review our [process documentation](https://github.com/GSA-TTS/FAC#fac-documentation)
- [x] Get access to our GitHub repositories
  - [x] If you're not already a member of BOTH the [GSA](https://github.com/orgs/GSA/people) and [GSA-TTS](https://github.com/orgs/GSA-TTS/people) GitHub organizations, [follow the process outlined here](https://github.com/GSA/GitHub-Administration#joining-the-gsa-enterprise-organization), requesting access to the appropriate org(s). When it's time to send the mail, look up the Product Lead (see [the staffing list](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/edit#heading=h.us8xylqg455c)) then start with this template, mailing from your GSA email address:

    ```text
    To: gsa-github.support@gsa.gov
    Cc: [the product lead]
    Subject: GSA and GSA-TTS GitHub organization membership
    Body:
    [Edit the following text to put in your GitHub username and your GSA email address, then remove this instruction text.]
    Please add my GitHub account (https://github.com/myusername) to the following GitHub organizations:
    - https://github.com/GSA
    - https://github.com/GSA-TTS
    
    I will be working on the FAC project:
    - https://github.com/GSA-TTS/FAC
    
    I have cc'd the FAC Product Lead for awareness.
        
    Thank you!
    ```        
    - (Note this step could take a few days; humans handle these requests.)
  - [x] Once you are added to the GSA-TTS org, ask [the person(s) with the "Maintainer" role to add you to the `FAC-team` team](https://github.com/orgs/GSA-TTS/teams/fac-team/members). This will grant you read/write access to our repositories.

**For designers, also...**
- [ ] Review the [design onboarding document](https://docs.google.com/document/d/1EILl0nZr59T4PFJJMtFbmnQDJPksgzIFPuoFDN0bk0g/edit#heading=h.bhu3dgydlbvr)
- [ ] Visit https://touchpoints.digital.gov/ and set up a touchpoints account
- [ ] If you don't already have a Figma license, request one from your supervisor. 
- [ ] If you don't already have a Mural account, follow the instructions to get one [here](https://handbook.tts.gsa.gov/tools/mural/).

## For your onboarding buddy

Note: If you're not able to do any of these yourself, you're still responsible for making sure that the right person makes them happen!

- [x] Add to the [FAC-team@GSA.gov](https://groups.google.com/a/gsa.gov/g/fac-team) Google Group
- [x] Add to standing meeting invites (should happen automatically via addition to the Google Group membership)

**For designers, also...**
- [x] Add as an editor on active Figma projects
- [ ] [Add as a form manager to the touchpoints recruitment intercept](https://touchpoints.app.cloud.gov/admin/forms/9412c559/permissions)
