### ISSUE TITLE
Cross-validation: validate CAP correctly

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1657]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

TODO: If a submitter has zero findings, is it possible they might still need to submit a CAP text from a prior year?

We will need a cross-validation appropriate to the answer to that question. 

* If yes, then... CAP text is optional. It is independent of how many findings there were.
* If no, then... we need to validate existence and CAP text rows against the number of findings.

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [x] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [x] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [ ] This generates one error
- [ ] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"FIXME"
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
FIXME 20230731
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```

**Comment by jadudm** [comment]
This is handled the same as audit findings and findings text; so, this ticket can be made redundant, and rolled into another validation.
