### ISSUE TITLE
Epic: Preview rollout

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1687]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

Lets finish some updates to the static site, and push it live to support the preview rollout/testing.

**Who**: Our users
**What**: want to give things a go
**Why**: because a dress rehearsal is always a good idea.

Currently, this work is happening in the branch `lh/ia-updates` in this static site repo.

https://github.com/GSA-TTS/FAC-transition-site/tree/lh/ia-updates

```[tasklist]
### Page-by-page
- [ ] https://github.com/GSA-TTS/FAC/issues/1688
- [ ] https://github.com/GSA-TTS/FAC/issues/1690
- [ ] https://github.com/GSA-TTS/FAC/issues/1691
- [ ] https://github.com/GSA-TTS/FAC/issues/1692
- [ ] https://github.com/GSA-TTS/FAC/issues/1693
- [ ] https://github.com/GSA-TTS/FAC/issues/1694
- [ ] https://github.com/GSA-TTS/FAC/issues/1695
- [ ] https://github.com/GSA-TTS/FAC/issues/1697
- [ ] https://github.com/GSA-TTS/FAC/issues/1696
- [ ] https://github.com/GSA-TTS/FAC/issues/1698
- [ ] https://github.com/GSA-TTS/FAC/issues/1702
- [ ] https://github.com/GSA-TTS/FAC/issues/1703
- [ ] https://github.com/GSA-TTS/FAC/issues/1704
- [ ] https://github.com/GSA-TTS/FAC/issues/1705
- [ ] Form Instructions: Pre-Screener
- [ ] Form Instructions: General Info
- [ ] Form Instructions: Audit Info
- [ ] https://github.com/GSA-TTS/FAC/issues/1706
- [ ] https://github.com/GSA-TTS/FAC/issues/1707
- [ ] https://github.com/GSA-TTS/FAC/issues/1325
```

**Comment by mogul** [comment]
@jadudm did you want to track #1631 here...?

**Comment by James-Paul-Mason** [comment]
@lauraherring Here is the Figma file for the static site: https://www.figma.com/file/x8dKJ8gDgd7PIPMnM80rlX/James-Mason%3A-Static-Site-Content-Review-File?type=design&t=UF2xr92VGLiGVAuI-6

**Comment by jadudm** [comment]
Closed. We're live. Further work will be picked up in future epics.
