### ISSUE TITLE
Homepage / landing page

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1688]
```[tasklist]
### Tasks
- [ ] Remove search of older audit reports from the homepage
- [ ] Add some info on the tasks for testing for the preview site
```
A draft of[ the homepage](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/ia-updates/) has been built on a branch. It still shows having audit search on it.

```[tasklist]
### Initial review
- [ ] Design complete
- [ ] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [ ] Design lead signoff
- [ ] Product signoff
- [ ] Content signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy we should co-work on this one to come up with a new design that doesn't include audit search since that isn't going to be ready when we launch.

**Comment by James-Paul-Mason** [comment]
Quick note: I have created a new Figma file (**completely separate from any existing "source of truth" files**) where I am documenting my content review for the static site. More to follow!
