### ISSUE TITLE
API endpoint for UEI to entity name lookup

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#169]
### Background
User's enter a UEI as part of the intake process to create an SF-SAC. We validate that UEI on both the client and server side.

Once validated the browser should display the associated LegalName, as provided by SAM.gov, to the user for confirmation.

### Tasks (not necessarily definitive list)
* [ ]   The backend validates UEIs against the validation rules (see [Validate UEIs and return entity data from SAM.gov](https://github.com/GSA-TTS/FAC/issues/148) ).
* [ ]   The backend takes UEIs and returns data about them, including their valid/invalid status and, if valid, the value of their `LegalName` property (also AFAICT covered by  [Validate UEIs and return entity data from SAM.gov](https://github.com/GSA-TTS/FAC/issues/148) ).

### We'll know we're done when
- [ ] We have a single endpoint which receives a user-provided UEI and returns either the associated LegalName or a list of errors describing why a LegalName is unavailable.

### Implementation Notes

In https://github.com/GSA-TTS/FAC/issues/148 provides the functionality to validate a UEI with sam.gov and return data. We should limit the returned data to only whats needed by the client.

**Comment by petermarks-gsa** [comment]
@geekygirlsarah  to take a look at this. @Jkrzy's suspicion is that we already have this in place and will draft up a "when this is done"

Main question: What is specific the expectation around this being done?

**Comment by geekygirlsarah** [comment]
@Jkrzy If you're looking at this, feel free to compare "done" to #148 .

**Comment by tadhg-ohiggins** [comment]
These are what occur to me as engineering sub-tasks (which may or may not constitute sub-issues):

* [ ]   The frontend validates UEIs against the validation rules[^1].
* [ ]   The backend validates UEIs against the validation rules (see [Validate UEIs and return entity data from SAM.gov](https://github.com/GSA-TTS/FAC/issues/148) ).
* [ ]   The backend takes UEIs and returns data about them, including their valid/invalid status and, if valid, the value of their `LegalName` property.
* [ ]   The frontend can submit UEIs to the backend and present the results—either invalid plus explanatory error messages or a `LegalName` value—to the user.

[^1]: To my knowledge these are: that the UEI contains only alphanumeric characters; that the UEI doesn't doesn't contain “O” or “I”; that the first character of the UEI is not “0”; that the UEI doesn't contain a nine-digit subsequence; and that SAM.gov returns information when the UEI is submitted for verification (the frontend cannot test this one).

**Comment by petermarks-gsa** [comment]
I think this looks sufficiently defined and have removed the "needs refinement" label. 

@tadhg-ohiggins I think that looks like a good task list. I think the backend ones are appropriate for this issue and the front end tasks are better for https://github.com/GSA-TTS/FAC/issues/126. I've updated descriptions of both issues.

**Comment by geekygirlsarah** [comment]
Looks good to me (@Jkrzy and @tadhg-ohiggins lists)

**Comment by geekygirlsarah** [comment]
I believe this ticket can be closed because:
* "The backend validates UEIs against the validation rules" This appears done in #148.
* "The backend takes UEIs and returns data about them, including their valid/invalid status and, if valid, the value of their LegalName property" There is no `LegalName` property but there's `legalBusinessName` and `dbaName`, which the former would be the main legal name. There are also `firstName`, `middleName`, and `lastName` responses for various contacts that can be returned but those aren't tied to the UEI directly and not retrieved with this call. The API response already returns `auditee_name` which returns the `legalBusinessName`, so this appears done from #148 as well.
Per Tadhg's suggestions:
* "The frontend validates UEIs against the validation rules" This will be done in #170.
* "The frontend can submit UEIs to the backend and present the results—either invalid plus explanatory error messages or a LegalName value—to the user." This will be done in #170.

Since the call works presently to do all of the tasks, I think this can be closed. @Jkrzy had some thoughts on possible renaming things and minor refactors, but that can be put into its own issue (or he can leave a comment here to maybe reopen this).
