### ISSUE TITLE
FAC updates

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1691]
```[tasklist]
### Tasks
- [x] Copy has not been updated in a long time; needs a closer walk and updates
```

Copy on [the page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/ia-updates/info/updates/) hasn't been updated since early July.

----

```[tasklist]
### Initial review
- [ ] Design complete
- [ ] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [ ] Design lead signoff
- [ ] Product signoff
- [ ] Content signoff
```
