### ISSUE TITLE
Instructions (previously "walkthrough")

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1694]
```[tasklist]
### Tasks
- [x] Screenshots are from May; probably need to update.
```

The page can be viewed [here](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/ia-updates/resources/instructions/).

There is a fancy way to link in all the screenshots, if they're named correctly. @jadudm set it up, ask if there are questions (it should be obvious, but... :shrug: )

----

```[tasklist]
### Initial review
- [ ] Design complete
- [ ] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [ ] Design lead signoff
- [ ] Product signoff
- [ ] Content signoff
```

**Comment by lauraherring** [comment]
Screenshots have been updated, moving this one to done.
