### ISSUE TITLE
Workbooks

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1695]
```[tasklist]
### Tasks
- [x] Light overview of each workbook
- [x] Links to instruction pages (for more depth)
- [x] Add workbooks
- [x] Talk about versioning
- [x] Update workbooks to include links to their instructions
```

[A shell page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/ia-updates/resources/workbooks/) has been created and initial copy written.

-----

```[tasklist]
### Initial review
- [ ] Design complete
- [ ] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [ ] Design lead signoff
- [ ] Product signoff
- [ ] Content signoff
```

**Comment by jadudm** [comment]
See https://github.com/GSA-TTS/FAC/issues/1899. This is ticketed/underway elsewhere. Close this when #1899  closes.

**Comment by lauraherring** [comment]
All content changes to the static site have been made.
