### ISSUE TITLE
Submission form: Articulate design hypothesis and research questions

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#17]
**Background**
Our assumption is that we can begin by prototyping the existing FAC interface and form in USWDS. That said, there are still many Qs about the best and most usable way to go about doing that. The purpose of this issue is to make sure that initial prototyping is oriented around out assumptions, most pressing research questions, and hypotheses that we can validate them in our first round of testing and refinements in the next iteration. 

**We'll know we're done when...**
- [x] We have a clearly articulated design hypotheses and research questions re: the submission form. 

**Tasks**
- [x] Create FAC user account
- [x] Represent current screen flow 
- [x] identify research Qs
- [x] Determine testing scenario
- [x] Prioritize what needs to be mocked for testing  / to get answers to QS
