### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#1706]
```[tasklist]
### Tasks
- [ ] Render field-by-field instructions from data file
- [ ] Review the FAQs.
- [ ] Nav link should point to ZD when it is ready.
```

```[tasklist]
### Initial review
- [ ] Design complete
- [ ] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```
[The FAQs](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/ia-updates/faq/) were written and published in May and haven't been touched since then.

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [ ] Design lead signoff
- [ ] Product signoff
- [ ] Content signoff
```

**Comment by lauraherring** [comment]
@jadudm I just met with @James-Paul-Mason and this ticket is done/completed and can be closed.
