### ISSUE TITLE
Epic: Workbook generation tech debt

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1712]
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/1831
- [ ] https://github.com/GSA-TTS/FAC/issues/1832
- [ ] https://github.com/GSA-TTS/FAC/issues/1833
- [ ] https://github.com/GSA-TTS/FAC/issues/1834
- [ ] https://github.com/GSA-TTS/FAC/issues/1835
- [ ] https://github.com/GSA-TTS/FAC/issues/1836
- [ ] https://github.com/GSA-TTS/FAC/issues/1837
- [ ] https://github.com/GSA-TTS/FAC/issues/1838
- [ ] https://github.com/GSA-TTS/FAC/issues/1839
- [ ] https://github.com/GSA-TTS/FAC/issues/1840
- [ ] https://github.com/GSA-TTS/FAC/issues/1841
- [ ] https://github.com/GSA-TTS/FAC/issues/1842
- [ ] https://github.com/GSA-TTS/FAC/issues/1843
- [ ] https://github.com/GSA-TTS/FAC/issues/1844
- [ ] https://github.com/GSA-TTS/FAC/issues/1845
- [ ] https://github.com/GSA-TTS/FAC/issues/1846
- [ ] https://github.com/GSA-TTS/FAC/issues/1847
```
