### ISSUE TITLE
Update general info page ordering

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1728]
```[tasklist]
### META TASKS
- [ ] Check off each of the below; close them as they're "done," where done might mean "I did it" or "Not doing."
- [ ] Move to "Design Review," and assign @jadudm and ping Matt in Slack
- [ ] Matt will take a look, and move to Engineering Available, and breakout any work that results.
``` 

```[tasklist]
### Tasks
- [ ] Check capitalization on sections; some are title case, some are not. Only cap the first word.
- [ ] “Fiscal Period” should be put before “Type of Audit”
- [ ] “Type of Audit” should be renamed to “Type of Uniform Guidance Audit”
- [ ] “Audit Period” should be renamed to “Audit Period Covered”
- [ ] Under “Auditee information”, the order of the headed sections should be arranged from top to bottom to be “Auditee Employer Identification Number (EIN)”, “Are multiple EINs covered in this report?”, “Auditee Unique Entity Identifier (UEI)”, “Are multiple UEIs covered in this report?” , “Auditee Details” and “Auditee Contact Information”
- [ ]  “Auditee details” as a header should be removed.
- [ ] "Auditee contact information" becomes "Auditee contact details"
- [ ] Under “Primary Auditor Information” the order from top to bottom should be “Audit Firm/Organization Name”, “Audit Firm/Organization EIN”, Audit Firm/Organization Address” and “Auditor Contact Information”.
- [ ] “Auditor Contact Information” should be renamed to “Primary Auditor Contact” 
```
