### ISSUE TITLE
Certification details - name, title, signature dates

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1733]
When certifying, we have a checklist. There is also a signature at the bottom, which is a name, title, and date.

We want to record those three fields in addition to our own timestamp from when the button is pressed.

```[tasklist]
### Tasks
- [ ] Update Figma to reflect truth.
- [ ] Update certification pages to make sure they have the name, title, (user-supplied) date, and our system timestamp from when they hit the button.
- [ ] Update the model to include these fields
- [ ] Update back through dissemination where appropriate
```
