### ISSUE TITLE
Additional EINs workbook

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1759]
`additional-eins.xlsx` workbook.

```[tasklist]
### Tasks
- [ ] Jsonnet spec for the workbook
- [ ] Jsonnet spec for the validation
- [ ] *Light* unit testing
- [ ] Commit resulting outputs to the tree
- [ ] Entry in the submission progress page
- [ ] Cross-validation integration
- [ ] Mapping in the model
- [ ] Migration
- [ ] Add to data-E2E tests (`generate_additional_eins`)
```
