### ISSUE TITLE
RESEARCH SPIKE: Naming the FAC url

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#176]
**Background**

<<background>>

It covers the following stories:

1. As an ...

**We'll know we're done when...**
- [ ] When a user can ...
  
**Tasks**
- [ ] Design designs all the things
- [ ] Engineering engineers all the things

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by jadudm** [comment]
OMB is providing guidance.
