### ISSUE TITLE
Additional auditors question in General Information

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1760]
```[tasklist]
### Tasks
- [x] Add question to JSON form spec
- [x] Add to ETL
- [ ] Cross-validation
- [x] Submission progress conditional visibility
```

**Comment by danswick** [comment]
This should be a question/checkbox that triggers the whole `secondary auditors` workbook/workflow. It probably shouldn't go on the Audit Submission Access page because secondary auditors shouldn't have access. Instead, it should go on the general info page.
