### ISSUE TITLE
Epic: SF-SAC overview

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1767]
# At a glance

**In order to** know what is about to be certified
**as a** certifying official
**I want** to see the whole SF-SAC in one go.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: I am about to certify an audit. I want to see what is in the audit.

**Given**   That I have a lot of information to take in at once
**when**  I am about to approve an audit
...

This comes _after_ cross-validation, but before _certification_. It is not possible  to go back and edit things at this point (for this version of the app). 

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] Run `ETL` on what they have
- [ ] General
- [ ] FederalAward
- [ ] Finding
- [ ] FindingText
- [ ] CapText
- [ ] Note
- [ ] Revision
- [ ] Passthrough
- [ ] SecondaryAuditor
```
# Background

We think the right way to do this is to ETL the data, and then use the dissemination models for displaying what they've submitted.

However, we do not want to actually ETL the code. Therefore, we want to suggest standing up an [in-memory SQLite database](https://stackoverflow.com/questions/33920368/django-in-memory-sqlite-in-production). We will invoke ETL and pass it an optional parameter, where we set the DB (that the ETL _saves to_) to the in-memory DB as opposed to the Postgres DB.

We then walk the in-memory DB to render out the tables. We can use [tricks like this](https://stackoverflow.com/questions/3106295/django-get-list-of-model-fields) to get all the model fields, and [verbose field names](https://docs.djangoproject.com/en/dev/topics/db/models/#verbose-field-names) to render pretty versions of the columns. Some question of how we sort that information is bound to come up, but we will figure it out.

We wrap this in a `try`/`finally`, and remove everything from the in-memory DB when we're done. It would be nice if we could instantiate a new SQLite in-memory DB for each user, which would mean we just drop and garbage collect it. 

We wonder if there's a memory leak hiding anywhere in this idea. :shrug: 

### WHY?

1. ETL does the work we need to do: it takes the JSON objects in the collection DB and organizes it nicely for people to consume.
2. We think this is the fastest way to get it done.
3. It eliminates places where we have to make changes if things change/fields are added/etc.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no security concerns to rendering the public SF-SAC data to the certifying official.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
This was all picked up slightly differently, and is done via the `etl-refactor` branch.
