### ISSUE TITLE
Epic: MVP helpdesk

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1768]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Our users
**What**: Might need help
**Why**: Because the SF-SAC is  complex

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1773
- [ ] https://github.com/GSA-TTS/FAC/issues/1772
- [ ] https://github.com/GSA-TTS/FAC/issues/1769
- [ ] https://github.com/GSA-TTS/FAC/issues/1770
- [ ] https://github.com/GSA-TTS/FAC/issues/1771
- [ ] PDR on ticket management process
```

**Comment by jadudm** [comment]
Done
