### ISSUE TITLE
Cross-validation: short summary

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1791]
## Validation Description

For a given `AWARD` in findings, there should be uniqueness across the `REFERENCE` numbers.

| award | ... | reference | 
| --- | --- | --- |
| AWARD-0001 | ... | 2023-001 |
| AWARD-0001 | ... | 2023-003 |
| AWARD-0001 | ... | 2023-004 |
| AWARD-0002 | ... | 2023-003 |
| AWARD-0002 | ... | 2023-005 |

So, award 1 has a unique set of references, {1, 3, 4}. Award 2 has a unique set of {3, 5}. It is possible for a reference to appear in multiple sets. However, it is *not* allowed to have a reference appear multiple times for a single award; eg. award 1 cannot be {1, 3, 3}. 

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [ ] Federal Awards
- [x] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [ ] This generates one error
- [x] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"Award {award-ref} repeats reference {ref}. The reference {ref} should only appear once for award {award-ref}."
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
AWARDREFS_202308111031
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```
