### ISSUE TITLE
Cross-validation: REF appearance across workbooks

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1792]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

In findings, there are award reference numbers. They may appear multiple times in the findings workbook. E.g. `2023-004` may appear multiple times. This is expected.

In findings text, `2023-004` must appear *at least once*. 

To validate this, we want to do a *set equality* check. The *set* of award references in the findings workbook should be equal to the *set* of reference numbers in the findings text workbook. Or, in findings, the list of reference numbers

`{2023-001, 2023-001, 2023-002, 2023-004}`

is the *set*

`{2023-001, 2023-002, 2023-004}`

and the same set of reference numbers should appear in findings text.

The same is true for CAP text. It is a set equality check.
 

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [ ] Federal Awards
- [x] Audit Findings
- [x] Audit findings text
- [x] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [x] This generates one error
- [ ] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"In findings text, you were missing the references {set-of-missing-refs}."
```

Or:

```python
f"In findings text, you had extra references: {set-of-extra-refs}."
```

Or:

```python
f"In findings text, you were missing {set-of-missing-refs}, and also had some extra references: {set-of-extra-refs}."
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```
