### ISSUE TITLE
Update mockups to reflect the findings in Auditors research report

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#180]
**Background**

In reviewing the tickets / sprint tasks from [the research report for on the Auditors user group (in Sprint Adirondack)](https://docs.google.com/document/d/1iuulBIkgRPeQKIinTN23B2pIOx17zvhzKe_2KwbxBCA/edit#heading=h.g1j9nc6gmfe) it became evident that many of the findings were dependencies that required more information and a holistic design approach. Also, in synthesizing preliminary findings from [the Agency Audit Resolution Officials user group)](https://app.mural.co/t/gsa6/m/gsa6/1650995940416/09d253ad5a85012d459e7931de14eb5f8894cc97?sender=austinhernandez5199) it appears that we are attempting to integrate several different tasks from a multiple user groups. We are creating a brand new website and design system and it was challenging to approach these findings in discrete tasks. 

As an example, ticket number [#147](https://github.com/GSA-TTS/FAC/issues/147)) states: "As an auditor or auditee, I need to be able to find the login w/ Login.gov button so that I can log in. (Dependent on figuring out the IA here)" This issue requires more understanding around which parts of the site require a log in, and where to disrupt user flow. There is also the Auditee user group which we have not spoken to yet.

In working with the design team and @heymatthenry, we have decided to create a larger ticket of mockup updates based on findings and work off of the research reports. As questions get answered and more is uncovered, these mockups will get updated.

The two main documents being edited are:
1. [Austin's DRAFT mockups on Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=1801%3A9179)
2. [Austin's design notes and questions](https://docs.google.com/document/d/1IAH8JF06A0Lr9-uxYBbCiTHGmYvv9_MX_yO7slrq5wQ/edit#)

It covers the following stories:
@MelissaBraxton to fill in old and related stories

Refinements to mocks for the following issues:
- [x] Home page #114
- [x] Filter and search audits associated with me page #238 
- [x] Submission criteria check page #122 
- [x]  Auditee information page - #127
- [x] UEI content #145
- [x] #165
- [x] Audit submission access page #128

**Comment by jadudm** [comment]
Related to the complexity of flows, etc. (and looking for @Jkrzy to chime in here)...

It may not be true that federal users access the system via login.gov? They may be using MAX/SecureAuth, because that brokers a number of federal identity services that can leverage a PIV/CAC. I can't remember where that conversation landed, however.

**Comment by MelissaBraxton** [comment]
The Login.gov user story is specific to auditors and auditees, so not federal users.

**Comment by MelissaBraxton** [comment]
Added checklist/links to relevant stories already on the board. @petermarks-gsa - thinking we can co-work on writing the new issues for remaining sprint 1 insights when we meet on 5/5.
