### ISSUE TITLE
Cross-validation: Checking for Award Refs Across Federal Awards and Federal Awards Audit Findings Workbooks

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#1805]
## Validation Description

[//]: # (A description of the validalidation in plain language.)
This ticket is to ensure consistency in award references between the `Federal Awards` and `Federal Awards Audit Findings` workbooks.
Any award reference mentioned in the Federal Awards Audit Findings workbook must match an existing entry in the Federal Awards workbook. In other words, the collection of award references in the Federal Awards Audit Findings workbook should be a subset of the award references in the Federal Awards workbook.

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [ ] Federal Awards
- [x] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [x] This generates one error
- [ ] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"Award {award-ref} is reported in the Federal Awards Audit Findings workbook, but was not declared in the Federal Awards workbook."
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
AWARDSREFS_202308141135
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```
