### ISSUE TITLE
Open user testing (Beta) 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1818]
### Open user testing on the gFAC preview site. 

In August 2023 we will be conducting open user testing with a group of 40 volunteers recruited via NASACT. Testing will consist of selected users being invited via email to access the preview site, given written instructions with task scenarios to complete, then asked to provide their feedback via written form and screen shots where applicable. We will supply completed materials for testers to work with. 
  
### Tasks

- [x] confirm potential test workflow with @jadudm 
- [x] draft user instructions with task scenarios
- [x] create pre-populated workbooks for task scenarios 
- [x] draft user feedback questions
- [x] build feedback form
- [x] test the test!
- [x] draft email correspondence 
- [x] send email invitations
- [x] sort incoming feedback into mural board for synthesis

### Definition of Done

- [x] Open user testing has completed and feedback is collected for synthesis
