### ISSUE TITLE
Epic: Front-end edits/sync

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1824]
```[tasklist]
### Tasks
- [x] Remove search for old audits from login page.
- [x] Address-from-SAM as source of truth: is this possible / can anyone with an out-of-date UEI even get here / what to do in the meantime
- [x] Remove all the breadcrumbs, but keep the blue line that's behind them
- [x] Link to regulations where possible (eCRF snapshots might combat linkrot concerns)
```
