### ISSUE TITLE
Cross-validation: Make sure all award references in federal awards are unique

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1848]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

It should be impossible for one award ref to show up twice. E.g. `AWARD-0023` should not be able to appear twice.

We might update another validation (that checks format), or write a new validation to just do this check.

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [x] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [x] This generates one error
- [ ] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"The award reference {award-ref} shows up more than once. This should not be possible. Please contact customer support."
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```
