### ISSUE TITLE
Cross-validation: page references in PDF submission

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1850]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

As part of the PDF upload, we have a set of page references that the user must enter. 

The last two fields are *optional*.

These fields come through into the JSON as a keyed dictionary.

### Summary schedule of prior audit findings

IF the submitter indicated that they had prior audit findings, THEN this field should have an integer. OTHERWISE, this field should be "N/A".

### CAP

IF the user indicated that there are *any* findings, THEN they should indicate which page their CAP starts.

(OTHERWISE) IF the user has zero findings, THEN this field should be "N/A".

## Section(s):
- [ ] This validation touches ALL sections

[//]: # (Spacing)

&nbsp;

[//]: # (Spacing)

- [ ] Pre-SAC
- [ ] General Information
- [ ] Audit Information
- [x] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [x] Audit package (PDF)
- [ ] Tribal data consent
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [ ] This generates one error
- [x] This possibly generates multiple errors

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"You have findings, but did not indicate where in your audit report your Corrective Action Plan appears."
```

```python
f"You have prior findings, but did not indicate where in your audit report the summary schedule of prior findings appears."
```

## Notes

[//]: # (Any additional notes for implementation.)

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```

**Comment by jadudm** [comment]
We need a corresponding front-end ticket to change the integer fields into text fields, so that we can enter EITHER a number OR N/A.
