### ISSUE TITLE
Audit Report PDF Updates

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#1851]
We want to ensure the Audit Report PDF upload page is up-to-date with [the Figma doc](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?node-id=1%3A22279&mode=dev). 

### Tasks

```
- [ ] Change the title of the page
- [ ] PII copy update
- [ ] Remove the process list (numbers) along the left side of the page
- [ ] Submit button copy
- [ ] "Upload PDF" -> "Re-Upload PDF" when there is already a submitted doc
- [ ] Confirmation modal after upload
```
