### ISSUE TITLE
Cross-validation: Audit report PDF optional page numbers

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#1852]
## Validation Description

[//]: # (A description of the validalidation in plain language.)

The last two page numbers a user can enter are optional. They are optional because they need only exist if the user has findings. If the user has _no_ findings, these fields should be N/A. If the user _does_ have findings, these fields should exists and be positive integers.

## Section(s):

- [ ] Audit package (PDF)

## Error(s)

- [ ] This generates (probably) one error. Two, if we differentiate the opposite situations.

### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"The audit report package indicates you have no findings. But, workbook uploads indicate you have {findings_count} findings."

f"The audit report package indicates you have {findings_count} findings. But, workbook uploads indicate you have no findings."
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
PAGENUMS_202307071352
```

## Notes

[//]: # (Any additional notes for implementation.)

We want to make sure these fields can accept both integers and N/A, and that they are now required fields, rather than optional.

```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```

**Comment by jperson1** [comment]
Whoops, duplicate.
