### ISSUE TITLE
Offboarding checklist for @neilmb

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1870]
# For everyone

- [x] Remove from [the FAC-team Google Group](https://groups.google.com/a/gsa.gov/g/fac-team/members)
- [x] Remove from [the FAC team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members)
- [x] Remove from the private channel #oros-fac-private in Slack (“/remove @[person]”)

**For engineers, also...**

- [x] Make a PR to [remove the departing team member from the list of developers and managers](https://github.com/GSA-TTS/FAC/tree/main/terraform/meta/config.tf) with access to our spaces.
- [x] [Remove the departing team member as a member of the FAC group in New Relic.](https://one.newrelic.com/admin-portal/organizations/users-list) (@GSA-TTS/fac-admins can do this)
    - [ ] If they're leaving TTS altogether, also delete their account.

**Comment by jadudm** [comment]
@neilmb was never added to the developers/managers list, as it was not required for the short duration he was on the team. In checking off the removal, I have confirmed that he is not in the list.

**Comment by jadudm** [comment]
@neilmb was never added to NR.
