### ISSUE TITLE
Changes from front-end walk

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1899]
```[tasklist]
### Tasks
- [x] Add links to workbooks on the workbook upload page.
- [x] Add "you have to upload this" to the optional workbooks (findings, findings text, CAP text). See notes below.
- [ ] Basically, check all the workbook pages. Yo.
- [ ] Checklist still says you don't have to upload some things. Remove those incorrect instructions (3--5).
- [ ] Get rid of `a.`, `b.` on the Audit Info page.
- [ ] Create a triage ticket for the cross-validation errors: they come through with user unfriendly text.
- [ ] Make sure  the "lock for cert" page has the correct text from source of truth.
- [ ] Make sure the final submission page has the correct text from source of truth.
- [ ] If you submit an incomplete and uncertified audit, you get a 500 error.
- [ ] Fix line wrap on cross-validation back button.
- [ ] Remove mention of email on access page.
- [ ] Remove this sentence: "If the financial statements of the auditee were prepared in accordance with GAAP, proceed to question b." from the audit information form.
- [ ] Question `i` on audit info seems to be helper text vs. black/actual text.
```

## Notes for "you have to upload this"

Text for workbook upload pages for optional pages can be found on the `ia-updates` branch of the static site.

We can replace the download link with these two bullets:

* Review the [instructions for this workbook]().
* [Download]() the Corrective Action Plan workbook template.

**Comment by jadudm** [comment]
Close https://github.com/GSA-TTS/FAC/issues/1695 when the appropriate work closes here.

**Comment by jadudm** [comment]
Also can close https://github.com/GSA-TTS/FAC/issues/1563 when we're done here.

**Comment by jadudm** [comment]
https://github.com/GSA-TTS/FAC/issues/1560 can close when this is done.
