### ISSUE TITLE
Implement logging framework

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#190]
**Background**
As a developer, we need to be able to log events such as unexpected errors, authentications, data modifications, etc. 

We'll configure Django's logging framework to play nicely with Cloud.gov's log ingestion and include documentation so developers know how and where to include logging statements.

**We'll know we're done when...**
- [ ] We can see log entries created by our application code in both local instances as well as on cloud.gov
- [ ] We've defined and documented our usage of logging levels.
- [ ] We've updated the documentation to cover our logging practices 

**Tasks**
- [ ] Log at the INFO level, all `user_logged_in` events from Django's authentication signals.
