### ISSUE TITLE
Onboarding checklist for isabella.s

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1901]
# Welcome to the team @{GitHub Username}!

@sambodeme will be your onboarding buddy and can help you if you get stuck on any of the steps in the checklist below. There's also a separate checklist that your onboarding buddy will tackle!

## For you

Here's a checklist to get you started and to make sure you've got access to :all-the-things:!

- [ ] Review [the project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/) in Google Drive
- [x] Join the Slack channels in [the project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/)
- [ ] Review our [process documentation](https://github.com/GSA-TTS/FAC#fac-documentation)

## For your onboarding buddy

Note: If you're not able to do any of these yourself, you're still responsible for making sure that the right person makes them happen!

- [x] Add to the [FAC-team@GSA.gov](https://groups.google.com/a/gsa.gov/g/fac-team) Google Group
- [x] Add to standing meeting invites (should happen automatically via addition to the Google Group membership)

**Comment by sambodeme** [comment]
isabella.s joined FAC as PMO support is now onboard.
