### ISSUE TITLE
Change state in general info to drop down

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1904]
```[tasklist]
### Tasks
- [ ] ~~Move states to States.libsonnet~~
- [x] Render states to their own JSON doc.
- [x] Pull JSON doc into FE for drop-down.
- [x] Change text field in frontend to drop-down w/ states.
```
