### ISSUE TITLE
Interview Census processors

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#191]
**Background**
This issue is to fill in knowledge gaps we have re: the human-in-the-loop part of processing and publicizing FAC submissions. We're have time scheduled with Census processors on 5/11, and this issue covers planning and facilitating that conversation and documenting what we learn.  

**We'll know we're done when...**
- [x] Our workflow model includes an accurate representation of what manual processing entails
- [x] We've documented any implications for our work as appropriate (new issues, etc.)

**Tasks**
- [X] Schedule time with Census processors
- [x] Draft agenda and questions
- [x] facilitate discussion
- [x] document learnings/write new issues as needed

**Comment by MelissaBraxton** [comment]
Drafting Qs [here](https://docs.google.com/document/d/1ApHaC5_daADSJzrUnWk4P6Oe-OYmJd6570ZmBiJWCk4/edit#).

**Comment by MelissaBraxton** [comment]
Started documenting insights by revising the processing section of the user story map[ here](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1649157562604)

**Comment by MelissaBraxton** [comment]
Documented takeaways and recommendations in #219.
