### ISSUE TITLE
Display of conditional sections on Submission progress page

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#1910]
These are the sections and my understanding of what makes them required:

| Section                            | Workbook number | Required                                                                         |
| ---------------------------------- | --------------- | -------------------------------------------------------------------------------- |
| General information                | N/A             | Always.                                                                          |
| Audit information                  | N/A             | Always.                                                                          |
| Audit report PDF                   | N/A             | Always.                                                                          |
| Federal awards                     | 1               | Always.                                                                          |
| Notes to SEFA                      | 2               | Always.                                                                          |
| Federal awards audit findings      | 3               | When there are audit findings listed in **Federal awards**.                      |
| Federal awards audit findings text | 4               | When there are audit findings listed in **Federal awards**.                      |
| Corrective action plan             | 5               | When there are audit findings listed in **Federal awards**.                      |
| Additional UEIs                    | 6               | When the **General information** multiple UEIs question has a “Yes” answer.      |
| Secondary auditors                 | 7               | When the **General information** secondary auditors question has a “Yes” answer. |
| Additional EINs                    | 8               | When the **General information** multiple EINs question has a “Yes” answer.      |

These are the three states that the blocks for each section can be in on the **Submission progress** page:

| State      | Interactive | Appearance |
| ---------- | ----------- | ---------- |
| Incomplete | Yes         | Standard   |
| Complete   | Yes         | Green      |
| Inactive   | No          | Grey       |

The blocks whose sections are always required will display either as **Incomplete** or **Complete**. The others will display as **Inactive** when the condition that makes them required is not met.

After both **General information** and **Federal awards** are submitted, every other section becomes either required or forbidden.

We decided that prior to those two sections being submitted, the sections with conditions will display as **Inactive** and switch to **Incomplete** only when their condition is met.

```[tasklist]
### Tasks
- [x] Get confirmation from design that above summary is correct.
- [x] Rewrite [submission_progress_check](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/cross_validation/submission_progress_check.py) to return `inactive` instead of `hidden`.
- [x] Update [tests for submission_progress_check](https://github.com/GSA-TTS/FAC/blob/d3ae27087523cdf618c2a7270abd85304bbd237e/backend/audit/test_views.py#L1179).
- [x] Rewrite [submission-checklist.html](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/templates/audit/submission_checklist/submission-checklist.html) to use `inactive` instead of `hidden`, plus the appropriate CSS changes.
- [x] Add logic to [submission_progress_check](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/cross_validation/submission_progress_check.py) to support the conditions for the as-yet-unsupported sections.
- [x] Update [tests for submission_progress_check](https://github.com/GSA-TTS/FAC/blob/d3ae27087523cdf618c2a7270abd85304bbd237e/backend/audit/test_views.py#L1179).
- [x] Make sure [submission-checklist.html](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/templates/audit/submission_checklist/submission-checklist.html) correctly displays the blocks.
- [ ] Update Cypress checks?
```

**Comment by jadudm** [comment]
This work merged; Cypress work is ticketed, underway.
