### ISSUE TITLE
Swimlane: Testing

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1923]
```[tasklist]
### Tasks
- [ ] Improve regression suite to allow running of individual files
- [ ] Incldue failing tests as part of the regression (workbooks that *should not* work)
- [ ] Revisit *old* api/test_views and api view after ETL lands.
```
