### ISSUE TITLE
Swimlane: Bug fixes

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1924]
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/1939
- [ ] https://github.com/GSA-TTS/FAC/issues/1951
- [ ] https://github.com/GSA-TTS/FAC/issues/1942
- [ ] #1944
- [ ] https://github.com/GSA-TTS/FAC/issues/1936
- [ ] https://github.com/GSA-TTS/FAC/issues/1777
- [ ] https://github.com/GSA-TTS/FAC/issues/1904
- [ ] https://github.com/GSA-TTS/FAC/issues/1957
- [ ] https://github.com/GSA-TTS/FAC/issues/1933
- [ ] https://github.com/GSA-TTS/FAC/issues/1927
- [ ] https://github.com/GSA-TTS/FAC/issues/1603
- [ ] #889
- [ ] https://github.com/GSA-TTS/FAC/issues/1865
- [ ] #1323
- [ ] #756
- [ ] #883
- [ ] #1635
- [ ] #1641
- [ ] #1642
- [ ] #1467
- [ ] #1481
- [ ] https://github.com/GSA-TTS/FAC/issues/1903
- [ ] https://github.com/GSA-TTS/FAC/issues/1868
- [ ] https://github.com/GSA-TTS/FAC/issues/1873
- [ ] https://github.com/GSA-TTS/FAC/issues/1932
```
