### ISSUE TITLE
FAC - Bug: Notes to SEFA workbook does not allow tables 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1940]
In `cap_text` and `audit_findings_text`, we have a column that says `Did Text Contain a Chart or Table?`

The workbook `notes_to_sefa` is missing this column. Users need that column. 

```[tasklist]
### Tasks
- [x] Add this column to the workbook sonnet spec for `notes_to_sefa`
- [x] Regenerate the workbook XLSX doc for visual testing
- [x] Add the column to the mapping (which converts the workbook to JSON)
- [x] Add the column to the validation for the workbook
- [x] Run tests. The tests should fail at this point.
- [x] Update the `notes_to_sefa` test object in the test harness to include this field. (Tests should fail until you do, if you update the validation first)
- [x] Run tests; they should now pass.
- [x] Update the dissemination model for `notes`
- [x] Update the dissemination code in `IntakeToDissemination` to include this field
- [x] Update the API view for `v1_0_0` to disseminate this field as part of `notes`
- [ ] Update the workbooks on the static site so that this new template is distributed to users
- [x] Generate/update workbooks for Cypress testing
```

To generate new workbooks, we will need... to fix the workbook generator.

Original bug below.

-----

### Describe the bug

Open test user feedback, Notes to SEFA workbook does not allow tables to be inserted, see screen grab for explanation: 
<img width="719" alt="Screenshot 2023-08-24 at 5 11 27 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/0bbc3acb-c8ed-4030-af68-e8b7771056f4">

### Steps to reproduce the bug

see above

### Expected Behavior

see above 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
I thought that the Notes to SEFA had a column that asked if a table was included. And, my understanding was that if they said "yes," then the table would be in the PDF document, not in the workbook. That is, I thought:

1. The user indicates there is a table,
2. The table is expected to be found in the PDF.

There is no way for us to accept tables of data in those workbooks. I didn't think Census did, either.

@Leighdiddy , this is another one that either we follow up with the user to learn more, or there's nothing we can do. Ticketing to you as "design available" for followup.

**Comment by jadudm** [comment]
I'm moving this to "available" for Design, @lauraherring , @James-Paul-Mason . We need to make sure the docs for this workbook make clear they can't add tables into the spreadsheet, and how they should do it.

**Comment by lauraherring** [comment]
@jadudm So the way they should do it is:

- note in the workbook that the note includes a chart and list the page # of the pdf on which the chart appears?

CC @James-Paul-Mason

**Comment by lauraherring** [comment]
@jadudm @James-Paul-Mason and I just looked at the Notes to SEFA workbook and there isn't a column for saying Y/N re. tables, charts, footnotes, etc., therefore no column for us to say "select Y/N."

The worksheet as we see it only has 2 columns: Note Title and Note Content.

We can update the instructions for Note Content to tell users that if the Note has a chart, table, or footnote, state that in the text and include the PDF page number but do not copy/paste in the chart/table/footnote itself.

Should this be what we do? Or will the engineers be adding a column that's Y/N for having charts/tables/footnotes and then an additional column for entering the PDF page number of said chart/table/footnote?

**Comment by jadudm** [comment]
Oh.

**Comment by danswick** [comment]
From the IDES manual: 

>If the Notes to the SEFA has already been created, enter the text as it appears in your Notes to the SEFA, excluding charts or tables. If there are any charts or tables within the text, enter “See the Notes to the SEFA for chart/table” in place of the chart or table within the text.

Given the above, I don't think we need to capture a page number.

**Comment by jadudm** [comment]
Ooh. Good find, Dan. Yes. 100%.

**Comment by lauraherring** [comment]
@James-Paul-Mason How does this text look to you:

> Enter the full text of the note. **Do not include charts, tables, or footnotes.** If there are any charts or tables within the text, enter “See the Notes to the SEFA for chart/table” instead.

**Comment by James-Paul-Mason** [comment]
@lauraherring Looks great!

**Comment by lauraherring** [comment]
Text updated in the app code, ready for @jadudm and @jperson1 to do their merging magic.
