### ISSUE TITLE
Epic: Naming and correctness

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1948]
```[tasklist]
### Tasks
- [x] Align names from named range through to dissemination name
- [ ] https://github.com/GSA-TTS/FAC/issues/1949
- [ ] https://github.com/GSA-TTS/FAC/issues/1950
```
