### ISSUE TITLE
To-be task flow model for audit submission and search/download

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#195]
**Background**
Now that we've completed initial research with primary users who submit data and access audit submissions, we would benefit from an abstract representation of the sequence/screens we're building and how they'll enable users to complete those high level tasks. 

**We'll know we're done when...**
- [ ] We have documented to-be task flows for data submission and data search/download

**Tasks**
- [x] Review sprint 1 and sprint 2 research reports 
- [x] sketch out to-be task flows In Mural
- [ ] Review at weekly design sync on 5/17
- [ ] Review at weekly design/eng sync on 5/19

**Comment by MelissaBraxton** [comment]
Draft is [here](https://app.mural.co/t/gsa6/m/gsa6/1652305949991/446f978a7539634e7cf9288ca1f9c0bf35e0a38f?sender=melissabraxton2796)

heads up @austinhernandez and @sreuber if you want to take a look in advance of next week's design sync.

**Comment by sreuber** [comment]
@MelissaBraxton Just have a few comments in the Mural re: the pages listed.

**Comment by MelissaBraxton** [comment]
Thanks! I addressed Scott's comments, so now the remaining task is to review at our design sync on 5/17.
