### ISSUE TITLE
FAC - Bug: Cannot collect audits from 2016 onward

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1987]
## Collecting late audits

We are starting the 2023 collection.

However, we also collect *late* submissions from 2016-2023.

```[tasklist]
### Tasks
- [ ] Test a submission with an audit period of 2016-01-01 to 2016-09-01
- [ ] Determine how/where it fails (if it does)
- [ ] Determine the data disseminates correctly (if the submission can be completed)
``` 

To test this, there may be workbook changes that are needed. For example, award reference numbers have the form `YYYY-###`, which means we would expect to have award references of the form `2016-###`. Take a set of test workbooks, go through, and adjust them to reflect a "past" submission.

To start, track problems in the comments on this ticket. We will then story out what needs to be done to address any issues.

Original bug report moved to the comments.

**Comment by jadudm** [comment]
### Describe the bug

We need to be able to collect late audits.

That means we need to be able to collect previous audit years (2016-present) according to our PRA.

Currently, the first page of the submission that asks for the AY range restricts us to 2022 audits.

Therefore, we need to fix this.

### Steps to reproduce the bug

1. Go here: https://fac-staging.app.cloud.gov/report_submission/auditeeinfo/
2. Try and enter old dates.
3. They won't work.

### Expected Behavior

They should work.

### Screenshots

_No response_

### System setup

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by LeoFotovich** [comment]
Just running through this, I was able to get all the way to certifying using dates from 2016.
<img width="329" alt="EV 1" src="https://github.com/GSA-TTS/FAC/assets/139488747/2baa96b4-a740-4485-9cfe-3aea2be41699">
Although you can't put old dates in the pre screener, you can manually change them in the general info.
<img width="310" alt="EV 2" src="https://github.com/GSA-TTS/FAC/assets/139488747/4eedae4d-23ae-4455-aabf-9ef1974d16b4">
Workbooks allow for dates to include 2016 without any validation issues.
<img width="416" alt="EV 3" src="https://github.com/GSA-TTS/FAC/assets/139488747/fe2789ee-45b6-4da9-ad3d-cb0aee9e34cd">
With all workbooks updated with the new date, I am able to certify.

This is where I ran into another issue.
<img width="592" alt="EV 4" src="https://github.com/GSA-TTS/FAC/assets/139488747/71e49b6a-8482-4ebc-a28e-447bc043aab5">
Got this error trying to do auditor certification. Full disclosure, I am using an audit that I've used to bug test other things in the past, though I doubt it would have any bearing on this error in particular. I also set up a different email as the auditor contact than my own, so that might also be the problem. It could also be that the dates are from 2016. Any dev insight here would be much appreciated. From my understanding, the only things keeping auditees from submitting forms from 2016 is the pre screener and potentially the certification steps.

**Comment by jadudm** [comment]
We're looking at this, but are pretty sure that if an audit with 2016 data passed cross-validation, then it will submit. I think the issue here is definitely the email address. 

The 403 error is correct, in that you are User A, and you set up User B to be the auditor certifying official. However, it would be nice if we handled the 403 more nicely in this specific context.

**Comment by jadudm** [comment]
Added #2138 to Triage to percolate over. Closing this ticket as I think the test was successful.
