### ISSUE TITLE
Investigate using Django reversion module

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#199]
**Version control at the database level**

We may need to track all changes to SAC forms in progress, and reversion may be the right library to use. Audibility and logging are major considerations here.

We might want to support user-level reversion (we would not remove any data from the actual versioning we store).

**We'll know we're done when...**
- [ ] We've decided whether or not to use reversions.

**Tasks**
- [ ]   If we decide to use it, add it to the backend.
- [ ]   If we decide not to use it, add whatever we choose instead to the backend.
- [ ]   If necessary (see [315](https://github.com/GSA-TTS/FAC/issues/315)) expose version info to frontend.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins Do we for sure need this for milestone 2? If so, can we estimate it?

**Comment by tadhg-ohiggins** [comment]
I'll move it to Milestone 3.
