### ISSUE TITLE
Add character limits to fields

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#1999]
## Background

We should have limits on our intake fields. This means both the spreadsheets and the webforms. 

```[tasklist]
### Tasks
- [x] Use API and historic data to get min, max, median lengths for every field
- [ ] Discuss how to do this for the web forms and spreadsheets
- [ ] Document decision
- [ ] Design consistent (table-driven, so to speak) approach for all inputs.
- [ ] ...
- [ ] Document limits for users in submission guide/howto.
```

We now have historic data; we can do some quick API work to evaluate various fields, and set sensible limits across the board. We might end up with four size buckets.

Once we know what we're facing, and have an idea how to do the implementation, we can revise this ticket to better support/track the implementation work.

### Describe the bug

There is no current character limit on "Auditee Name" under General Info. This does not cause a crash, however, creates some pretty funny results when going back to the landing page and the "in progress" audits page.

### Steps to reproduce the bug

Go to "Auditee Name" under General info and input a bunch of characters

### Expected Behavior

For there to be some limit on characters, or for the inputted name to not show up on other parts of the website

### Screenshots

<img width="386" alt="Funny bug 1" src="https://github.com/GSA-TTS/FAC/assets/139488747/ea27ef85-7afb-44b0-a258-115316d2ece4">
<img width="208" alt="Funny bug 2" src="https://github.com/GSA-TTS/FAC/assets/139488747/82d344c9-30c6-4b91-9987-fd86712628b9">

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by danswick** [comment]
Most form fields should have a character limit and those limits should be based on real data. These should be done as a single project rather than field-by-field.

**Comment by danswick** [comment]
This looks pretty stale, so I'm moving it back to "backlog." If you're working on it right now, could you link to a PR or branch, @phildominguez-gsa?

**Comment by jperson1** [comment]
1. Character limits have a set place to exist in the `schemas` directory. 
2. Character limits were determined based on existing data, adjusted up/down to avoid invalidating any production data
3. Character limits have been applied to the web form fields (general information, audit accesses)
    * At the `forms.py` level
    * In the relevant schema

Next steps are to determine and apply character limits to the workbooks. Existing data exists in the `schema` directory and can be used to determine the limits.

**Comment by danswick** [comment]
Per discussion during dev huddle, I think we're good to call this one done for now. We'll revisit workbook character limits later if needed.
