### ISSUE TITLE
Determine possible statuses for SAC submission

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#202]
**Background**
Discussion of #168 brought up the need to figure out what the possible statuses for a SAC submission are.

**We'll know we're done when...**
- [x] We have a list of the possible statuses.
- [x] We know what needs to be true in order to trigger a status change.
- [ ]  ~~We know how to determine the status of an existing SAC record with legacy date-based fields.~~ Moved to #209.

**Tasks**
- [x] Draft high-level to-be swimlane diagram.
- [x] Schedule design/eng time to review .
- [x] Map possible statuses to workflow.
-  [x] Create PDR/ADR to capture findings from discussion on this issue. #211

## Some definitions

<dl>
<dt>Intake form data</dt>
<dd>Preliminary data about the audit submission, including UEI, email addresses of users, year of submission.</dd>
<dt>SAC full validation</dt>
<dd>The SAC model in our system must allow incomplete/invalid submissions so that in-progress forms can be saved in our backend. This means we need another step, using application code that is not part of Django model validation, to verify that a form is valid and complete.</dd>
</dl>

## Possible SAC statuses (initial suggestions only!)

Below are the statuses in sequential order.

<dl>
<dt>Created/Submitted</dt>
<dd>The intake form data was sufficient to allow the user to begin the SAC process.</dd>
<dt>In Progress</dt>
<dd>The user(s) have entered some data post-creation.</dd>
<dt>Certifiable</dt>
<dd>The form is valid (complete and with valid entries) according to our SAC full validation step.</dd>
<dt>Auditee Certified</dt>
<dd>The form is valid (complete and with valid entries) according to our SAC full validation step and the auditee has marked it as certified.</dd>
<dt>Certified</dt>
<dd>The form is valid (complete and with valid entries) according to our SAC full validation step and the auditee and auditor have both marked it as certified.</dd>
<dt>Awaiting Manual Verification</dt>
<dd>A human examines the overall submission and checks to see that for example the submitted PDF is what it should be. Final quality control check before the FAC formally accepts the submission.</dd>
<dt>Accepted</dt>
<dd>FAC has accepted the submission and the entity's regulatory obligation to submit audit data has been fulfilled.</dd>
</dl>

## Related notes

We need to track the time of any status change (as well as who made the last change before that).

We think we shouldn't make attestation controls available if the form is incomplete/invalid.

Consider using Django reversion module (see #199).

**Comment by tadhg-ohiggins** [comment]
The current FAC workflow is included in [this diagram](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?sender=melissabraxton2796) 

We have some [relevant user research](https://docs.google.com/document/d/1iuulBIkgRPeQKIinTN23B2pIOx17zvhzKe_2KwbxBCA/edit#) [internal team only].

**Comment by tadhg-ohiggins** [comment]
A relevant comment from [user research](https://docs.google.com/document/d/1iuulBIkgRPeQKIinTN23B2pIOx17zvhzKe_2KwbxBCA/edit#) [internal team only]:

>>> Status column - Consider removing “certifiable” as a separate status. It wasn’t clear whether the distinction between “in progress” and “certifiable” was meaningful for auditors. The current FAC does not distinguish these two states to users--they’re lumped into one “continue/certify” category. The meaning of “certifiable” as a status was not clear to everyone.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins Thanks for taking the initiative and breaking this off! After our meeting today, I have a better understanding for how status is being communicated to the user and your intentions behind changing the data model. I understand the goal is to move away from a bunch of individual date fields, but to still have the date data recorded with each status change. I added the following to-do to the acceptance criteria "We know how to determine the status of an existing SAC record with legacy date-based fields" to make sure we don't have to rethink the data model when it's time to migrate legacy data.

**Comment by tadhg-ohiggins** [comment]
## 2022-05-13 statuses conversation

*   Melissa Braxton
*   Tadhg O'Higgins


Should we remove the distinction between CREATED and IN PROGRESS? We don't see a useful difference between them, we should probably just make it IN PROGRESS as soon as it's been created.

We think that “ready to be certified” should be a thing but we're not sure we want to show it to users.

How do we reflect to the user the difference between “errors” and/or missing fields and the fact that the typical user process includes filling things out partially?

How useful is the “certifiable” state (which means, essentially, that only the attestations haven't been filled in by the auditor and auditee) to the user? How useful is it to us internally?

Change “auditor/auditee certified” to “partially certified”? Or “auditor certified” and “auditee certified”? Last person to certify has the option to submit.

Research question: is it useful to have a status where both have certified and the form is NOT submitted?
    It's a separate step to submit. (“Submit to FAC for processing” in current system)

Once it's submitted, there's a bunch of manual processing. Following current-FAC states are:

*   Accepted, which means manual processing found no revisions. There's an accepted date.
*   Received, which presumably means there are revisions required.

We (current FAC team) want to remove manual processing from this workflow and return responsibility for catching these errors to the auditors. This means that we probably want to just have the “submitted”, “rejected”, and “accepted” statuses be collapsed into one.

If we remove manual processing, should we replace it with content saying, “many people make the following mistakes; please don't make any of these mistakes”?

Could we catch duplicate submissions of an audit (a common mistake caught manually in the current system) automatically? There should only be one audit per UEI per fiscal period, so maybe we could catch that.

**Comment by MelissaBraxton** [comment]
Draft WF model that starts to map statuses to work is[ here](https://app.mural.co/t/gsa6/m/gsa6/1652460935988/b240919b310e05f897c6452815fe5a07cad3eaea?sender=melissabraxton2796).

**Comment by MelissaBraxton** [comment]
One change:
We need to let users proceed to **in progress** even if the UEI they enter cannot be validated in SAM.gov. They should be able to enter data, but they won't be able to move from **in progress** to **submitted** until they've entered a valid UEI.

**Comment by tadhg-ohiggins** [comment]
@MelissaBraxton thanks! I updated the above comment to reflect that info.
