### ISSUE TITLE
Epic: Design/Content Go-Live

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2030]
```[tasklist]
### Design/UX Go-Live
- [ ] yay
``` 

```[tasklist]
### Content Go-Live
- [x] Homepage / testing alert banner needs to go away (at go-live)
- [ ] https://github.com/GSA-TTS/FAC/issues/2031
- [x] Dev tools / API docs: DS working on it, need a close walk too.
- [x] Make sure Zendesk is linked in appropriately
- [x] Prune FAC updates (keep/change/throw away)
- [ ] https://github.com/GSA-TTS/FAC/issues/2032
```
