### ISSUE TITLE
Revise  screenshots and develop process/documentation

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2032]
We need new screenshots for [this page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/ia-updates/resources/instructions/).

@LeoFotovich , @alyssamwong , if you would be so kind as to coordinate with @lauraherring and develop those, we can then show you how to bring those into the static site. (Or, we can do the git-fu later. But, we definitely need new screenshots, without draft watermarks, that reflect the current state of the system.)

```[tasklist]
### Tasks
- [x] Screenshot each of those pages
- [x] Do a full page screenshot (e.g. use Firefox and print to PNG)
- [x] Work with Leigh/Laura to figure out how to edit
```

If you are on a Mac issued by GSA, Quicktime should let you screengrab to a fixed size. If not... we can figure it out.

**Comment by Leighdiddy** [comment]
See #1694 for context!

**Comment by jadudm** [comment]
These are from the Figma mocks, and are not always reflective of the live site.

I'm moving this to "For Review." However, I think we need to ticket something where we develop a process for generating the screenshots from our live site. That process should make clear:

1. How to do it.
2. How to name the files.
3. What dimension(s) the files should have.
4. Any cropping/etc. that needs to be done.
5. Where to put the files in the site.
6. How to associate the files with the static content.

That's kinda the process right there. But, I would like to see a README, doc, or something that makes it possible for any number of people to do it. And, we want to update the screenshots so they reflect the living app, not the Figma mocks.

**Comment by jadudm** [comment]
Yep. However, I want to ticket this out either as 1) a template or 2) some kind of document/checklist, so that the next time we do it, anyone can do it. That's more what the note was about. 

It's... a reminder that I need to create another ticket...

**Comment by lauraherring** [comment]
@jadudm I'm treating this as that ticket, I was just putting my notes on what to include in the documentation in the ticket. I'm going to write up actual documentation instructions.

**Comment by lauraherring** [comment]
I've got [a draft of the instructions for updating the screenshots](https://docs.google.com/document/d/19pcFCujtbKLYIhDEA9X0RYSPkHR6H7NfB7MnA4YxRSI/edit?usp=sharing) written. It'd be great if I could get another set if eyes on this to make sure they're actually useful. @James-Paul-Mason @Leighdiddy @alyssamwong, would you all mind taking a look as people completely unfamiliar with the process from start-to-finish?

**Comment by James-Paul-Mason** [comment]
@lauraherring Looks great! I added one suggestion regarding the instructions for creating a test Login.gov account.

**Comment by alyssamwong** [comment]
@lauraherring The instructions are clear and make sense. All good on my end!

**Comment by lauraherring** [comment]
@Leighdiddy would you mind taking a look at these instructions and letting me know what you think? Particularly of the image sizing section?

**Comment by Leighdiddy** [comment]
@lauraherring updating with instructions for pulling images from Figma, hold please :)

**Comment by Leighdiddy** [comment]
@lauraherring gdoc is updated with figma instructions.

**Comment by lauraherring** [comment]
Thanks, @Leighdiddy. I think this ticket is all set then, @jadudm. I'll move it to done.
