### ISSUE TITLE
Epic: Go-Live (Eng)

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2033]
```[tasklist]
### Tasks
- [x] wipe dbs
- [x] reset migrations
- [x] redeploy
- [x] Cog assignment - ticket what will go live
- [x] we need a try/catch on both the load and the save in dissem
- [x] wrap dissemination save w/ some protection, user error
- [ ] https://github.com/GSA-TTS/FAC/issues/2035
- [ ] https://github.com/GSA-TTS/FAC/issues/2034
- [x] update schemas to move validations closer to the source of error (see 2036)
- [x] additional eins is missing from dissem
- [ ] https://github.com/GSA-TTS/FAC/issues/2187
- [x] Figure out how to backup / snapshot our S3 envs / PDFs and Excels.
- [x] status on load_... in dissem
- [x] Revisit the `if` on line 444 of audit/models.py. Is it *really* needed?
- [ ] https://github.com/GSA-TTS/FAC/issues/2188
- [x] remove legacy api and associated tests
```
