### ISSUE TITLE
Provision staff users

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#2038]
# At a glance

In order to perform privileged functions, such as manually overriding the assignment of a cognizant agency , users with `staff` permissions need to be provisioned in the FAC app

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 
When OROS Leadership decides to make someone a FAC Staff user, a member of FAC Admin should be able to add this users's government email address to a secret list. The FAC application deployment process should ensure that users with email addresses in the list are granted is_staff permissions in the FAC Django app. Note that auditors, auditees abd users from agencies besides GSA will not normally be authorized by the OROS leadership team to play this privileged role.

When a user whose email address is included in the list logs in to the FAC applocation via login.gov using thiis email address, they should be able to perform restricted functions that only users with is_staff can perform.  Note that the user may have already logged in to the FAC app for the first time before they were set up as a staff user.

### Shepherd

* Design shepherd:  @timoballard , @mogul 
* Engineering shepherd: @JeanMarie-TTS 

# Background

A privileged function that is required for the MVP is the overriding of the cognizant agency for a submission. When an audit is completed and submitted for dissemination, the FAC application determined the cognizant or oversight agency and assigns this to the submission using an algorithm documented elsewhere. However, there are times when the assigned cognizant agency will not agree with the assignment and will work with the GSA Staff team to manually have the cognizant agency re-assigned to another agency. The GSA staff works with the concerned agencies offline to obtain a consensus before overriding the currentl assignment.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

# Sketch

```[tasklist]
# Tasks
- [x] Identify where to store the list of email addresses with special privileges.  *In the database*
- [x] Will there be separate lists for different spaces?  *Yes, since we have different databases in each space*
- [x] Decide on and implement a process to add/remove users from this list *A user with special provileges will be able to do this in django admin. This specia; privilege could be FAC Admins having superuser privilege or FAC admins being set up as belonging to a special group.*
- [x] Modify our deployment scripts to create or modify users with is_staff permissions. *Make use of an existing management command `make_staff` included in the FAC repo.  Not required since this will happen whenever someone is added to the list on the django admin screen.*
- [x] Modiify the login process to use accounts created by the deployment process
- [x] Verify that a staff user is able to access the admin page of the FAC app without being prompted for additional credentials.
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
Noting this here: I'm wondering if we can do this as a list of users in the GH repo, and make a part of `.profile` that we do the work to raise (or lower) privs for those users? I'm thinking of something parallel to how we provide privileged access for cloud.gov spaces.

However, if it is a hard constraint that the users with these privileges are somehow secret/not known publicly, then the above idea does not work.

**Comment by JeanMarie-TTS** [comment]
@jadudm , do we want all our staff users be GH repo users as well? Why impose this constraint?

**Comment by jadudm** [comment]
Hm. Well, I don't know if they *have* to be GH users, but we could maintain
the list under version control, and it would meet some user access ATO
controls in much the same way as other accesses. (And, we could add it to
the onboarding checklist. " [ ] Be added as staff in admin app if you are
responsible for managing the application" or similar.)

I think I meant "we could maintain the list of email addresses in the
repo." Whether or not we require the user in question to add themselves is,
I think, secondary to the control. The fact  that it would go through
review is the important part.

It was just a thought. May not make sense.

**Comment by mogul** [comment]
Whether the list needs to be secret or not will be an important piece of info to have in hand before we determine our approach. I'm ambivalent about the actual technical approach, but I agree that keeping the list in version control is very desirable.

My main concern with this issue is that we also incorporate updating the roles described in our SSPP as part of the work.

**Comment by mogul** [comment]
Summarizing a discussion we just had: 

- The role is already anticipated and documented in the SSPP. 
- We determined that the best place to store the list is in [the vars files](https://github.com/GSA-TTS/FAC/tree/main/backend/manifests/vars) so that we have an audit trail of changes and can potentially vary the list per environment.
- The list will just be a set of email addresses, which allows us to match with the attribute from login.gov.
- The list will be independent of our normal team onboarding process... PRs will be made to those files in the normal way.
- We will enforce oversight of changes to those files by making an entry in [the CODEOWNERS file](https://github.com/GSA-TTS/FAC/blob/main/.github/CODEOWNERS).
- The state management code already has precedent only allowing certain roles to make particular state transitions. The code just needs to know where to read the list of users from.
-

**Comment by JeanMarie-TTS** [comment]
See #2430

**Comment by JeanMarie-TTS** [comment]
Implemented
