### ISSUE TITLE
Static site go-live

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2049]
```[tasklist]
### Tasks
- [x] Make sure we do not have a link to point to data subimssion
- [x] Merge all relevant branches/changes
- [x] Publish to fac.gov
```

**Comment by lauraherring** [comment]
@jadudm I just realized the link I have for sign-in is still `https://fac-staging.app.cloud.gov/`. Can I get what the actual live app link is going to be?

**Comment by jadudm** [comment]
app.fac.gov

**Comment by lauraherring** [comment]
This one is complete, moving to done.
