### ISSUE TITLE
Epic: Cog/Over

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2051]
```[tasklist]
### Tasks
- [ ] Code cleanup/renaming/refactor
- [ ] Remove CogBaseline table and calc from 2019
- [ ] Bring 21-25 table for data load
- [ ] Duplicates with EIN/UEI but different DBKEYs... :|
```

**Comment by jadudm** [comment]
This work was picked up in other stories/epics. Closing this particular epic as that work completes.
