### ISSUE TITLE
Re-enable pa11y tests

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2056]
Following https://github.com/GSA-TTS/FAC/pull/2039, we'll need to re-enable pa11y tests again. After some troubleshooting with @sambodeme, I believe the issue stems from a mismatch in Node environments in the workflow. We were specifying Node 16 and npm <9 in the workflow YAML, but `pa11y-ci` was being run with Node 18 and npm 9.x. We probably want to switch to `./backend` as a working directory and run the existing `npm run test:a11y:pa11y` command to make sure everything is running through a single Node environment.

### Tasks

```[tasklist]
- [ ] Create a test case that runs `npm run test:a11y:pa11y` from `./backend`
- [ ] Revert the changes I made in https://github.com/GSA-TTS/FAC/pull/2037
- [ ] Re-enable all of the old `pa11y` tests.
```
