### ISSUE TITLE
Document how to derive status from legacy SAC records 

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#209]
### Background
At some future date we may have to support displaying information about legacy records in our interface. This may include displaying the status of one of these legacy records, and thus we need to know how to translate legacy SAC information into one of the status values we have in our models.

### We'll know we're done when:
* [ ]   We have a list of all of the relevant fields in the legacy data model.
* [ ]   We have a matrix or algorithm or flowchart describing how various values of those fields translate to one of our status values.

### Tasks
* [ ]   Do spelunking required to figure out what all the relevant fields in the legacy data model are.
* [ ]   Do research required to understand those fields well enough to relate them to our status values.
* [ ]   Create matrix/algorithm/flowchart described above.

This issue was broken out from #202.
