### ISSUE TITLE
Provide extra API fields to support legacy expectations

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#210]
### Background
Our API may have to provide derived values corresponding some of the fields in the legacy model in order to allow consumers of our API to recreate all of the values they currently expect. We anticipate that this will not require adding any fields to our database models, but that it will require custom code to figure out what these derived values should be.

### We'll know we're done when:
* [ ]   We have a list of all of the relevant fields in the legacy data model.
* [ ]   We have a matrix or algorithm or flowchart describing how we can extract the corresponding information from our data structures.
* [ ]   We have an API endpoint that makes these fields available.
* [ ]   We have confirmation from the API consumers in question that the derived values match what they expect.

### Tasks
* [ ]   Do spelunking required to figure out what all the relevant fields in the legacy data model are.
* [ ]   Do research required to understand those fields well enough to relate them to what we need to provide.
* [ ]   Write tests to make requests from our API that exercise this expectation.
* [ ]   Write the API code required to pass those tests and meet these API consumer expectations.
