### ISSUE TITLE
Update cross-val logic to handle the new form

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2103]
The cross-validation logic happens after the tribal data access statement.

A few things should be incorporated into the cross-validation:

```[tasklist]
### Tasks
- [x] Make sure this information is passed as part of the "everything" object that cross-val functions used.
- [x] Check that if the audit indicates that this submission has tribal status, that the data access statement is 1) present and 2) complete. (The validation schema should do this, but we will check again.)
- [x] Check that if the submission status is **NOT** a tribal organization, then the field for this JSON object in our report submission row should be `null`
- [x] Add associated tests to verify that the above logic works as expected
```

**Comment by danswick** [comment]
Adding the cross-val checklist: 

---

## Validation Description

[//]: # (A description of the validation in plain language.)

## Section(s):


- [ ] Pre-SAC
- [x] General Information: self-reported organization type
- [ ] Audit Information
- [ ] Federal Awards
- [ ] Audit Findings
- [ ] Audit findings text
- [ ] CAP Text
- [ ] Additional UEIs
- [ ] Additional Auditors
- [ ] Audit package (PDF)
- [x] Tribal data consent: tribal data access statement section
- [ ] Auditee certification
- [ ] Auditor certification

## Error(s)

- [ ] This generates one error
- [ ] This possibly generates multiple errors


### Error text

[//]: # (Use Python format string syntax. E.g. f"The section {general-information} is missing everything.")

```python
f"Sad Mac"
```

### Error number

[//]: # (Short identifier followed by timestamp. E.g. UEI_202307050927)

```
SADMAC_202307071352
```

## Notes

[//]: # (Any additional notes for implementation.)


```[tasklist]
### Tasks
- [ ] Error text is edited and approved by @lauraherring 
- [ ] Validation is implemented
- [ ] When data is correct, validation produces no errors
- [ ] When data is incorrect, validation produces expected errors.
```

**Comment by danswick** [comment]
@jadudm will we ever disseminate the consent form data (name/title, for example) or will it only ever be used to determine whether an audit should be public?

**Comment by jadudm** [comment]
We will not be disseminating it at this time. If we ever determine that we need to in the future, we will add it as a separate increment of work.
