### ISSUE TITLE
Implement audit start page

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#212]
**Background**
This story is to design and develop the audit start page. This is the page that's specific to each audit submission from which users navigate to different things they want/need to do with that audit submission. You can find this in the story map [here.](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1649159658815).This covers the navigation to various other pages (help, changing submission access, etc.), but not the design and development of those pages themselves. 

**Stories:** 

1. As an auditor or an auditee, I want key information about the audit I'm working on to be persistent at the top of the page so that I can be sure the info I'm entering is for the correct audit
2. As an auditor or an auditee, I need to know what parts of my audit have been completed so that I know where to dive in. 

**Designs:** 
[Start Page (standard)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3407%3A15718)
[Start Page (invalid UEI)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3458%3A16797) 
[Start Page modal (edit entity type)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3457%3A16114)
[Start Page modal (edit UEI initial)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3457%3A16257) 
[Start Page modal (edit UEI, new unconfirmed)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3458%3A16405)
[Start Page modal (edit UEI, new confirmed)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3458%3A16573)
[Start Page modal (unlock)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3457%3A16400)

**Acceptance criteria**
When a user has a homepage specific to an audit submission they're working on from which they can navigate to take the actions they want and need to take on that audit submission. This includes the need to navigate to:
 - [ ] Help documentation
 - [ ] Change who has access to the submission
 - [ ] Unlock finalized SF-SAC
 - [ ] View/print SF-SAC form
 - [ ] Enter and finalize SF-SAC data
 - [ ] Upload and finalize audit report
 - [ ] Auditor and auditee certification
 - [ ] Submit to FAC for processing
  
**Tasks**
- [ ] [FRONT END] Implement mocks
- [ ] [BACK END] work with front end to figure out what to add to the data model and expose via the API

**Break into separate tasks**
- COVER STORY: 3. As an auditor or auditee, I need to know who may have worked on a particular part of my audit so that I know where to go with questions.  **NOTE: We may want to break this out into it's own story - covers how we'll surface auto logging to users**
- [ ] [BACK END] Logging model - show on the front end who touched an issue last (Partially covered by #199)
- [ ] [BACK END] permissions model - this person has a role associated with this permissions aspect. Assumption a submitter can view their own single audit checklist (potentially separate issue)
- [ ] [BACK END] Permissive validation model 
- [ ] [BACK END] final validation model (including PDF uploading)
- [ ] [BACK END] Determine different sections of SAC model

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] Automated accessibility tests pass
- [ ] Manual accessibility tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by petermarks-gsa** [comment]
@MelissaBraxton We could use more detailed design specifications, especially as it relates to dynamic data? 

Decision: We think the design elements of this could start.
