### ISSUE TITLE
Epic: Zendesk ticketing

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2127]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: A member of the FAC team
**What**: Bring the helpdesk to full readiness for go-live.
**Why**: Because we value our users and their input.

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/2129
- [ ] https://github.com/GSA-TTS/FAC/issues/2130
- [x] Remove any existing/draft forms
- [ ] https://github.com/GSA-TTS/FAC/issues/2140
- [ ] https://github.com/GSA-TTS/FAC/issues/2128
```
