### ISSUE TITLE
Design and implement Notes to SEFA page

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#213]
**Background**

This story covers the design and implementation of the **notes to SEFA** page. We mocked and tested this page in sprint 1 and did not recommend any refinements for the MVP. You can find this in the story map [here](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1649156963527). Current mocks are [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2464%3A11229).

This is dependent on #185. 

It covers the following stories:

1. As an auditee, I can enter or edit the notes to SEFA and have it populate my SEFA form so that I can complete my audit 

**We'll know we're done when...**
- [ ] When a user can enter or edit the notes to SEFA and have it populate the SEFA part of the SAC in the data model.
  
**Tasks**
- [x] Dependent on https://github.com/GSA-TTS/FAC/issues/185
- [x] [DESIGN] @sreuber Mock up / communicate expected behavior for drop down and additional notes
- [ ] [FRONT END] Implement sprint 1 mocks
- [ ] [BACK END] extend SAC model and API to include form fields (at time of writing too early to refine)
- [ ] Implement model enhancements to capture audit enhancements info
- [ ] [DESIGN/PRODUCT] Better notes functionality and storage expectations

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] Automated accessibility tests pass
- [ ] Manual accessibility tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by sreuber** [comment]
Mocks for Notes to SEFA, including the interaction for the add notes, are complete. Annotations/instructions included in the comments on the Figma file.

[Notes to SEFA default
](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2464%3A11229)
[Notes to SEFA add note
](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2555%3A11913)
[Notes to SEFA current note](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2555%3A11456)

**Comment by petermarks-gsa** [comment]
Flagging that this story is in progress, but no one is assigned to it, so I'm moving this back to "available"

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Okay to remove "needs refinement" here? Seems like this is fairly spec'ed out.

**Comment by MelissaBraxton** [comment]
This is one of the SF-SAC pages. Since sprint 5 is focused on the pre-SF-SAC part of the journey, we may want to move this back to the backlog.

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Good flag, moving to backlog.
