### ISSUE TITLE
Add column to Notes to SEFA, validations, ETL...

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2132]
In `cap_text` and `audit_findings_text`, we have a column that says `Did Text Contain a Chart or Table?`

The workbook `notes_to_sefa` is missing this column. Users need that column. 

```[tasklist]
### Tasks
- [ ] Add this column to the workbook sonnet spec for `notes_to_sefa`
- [ ] Regenerate the workbook XLSX doc for visual testing
- [ ] Add the column to the mapping (which converts the workbook to JSON)
- [ ] Add the column to the validation for the workbook
- [ ] Run tests. The tests should fail at this point.
- [ ] Update the `notes_to_sefa` test object in the test harness to include this field. (Tests should fail until you do, if you update the validation first)
- [ ] Run tests; they should now pass.
- [ ] Update the dissemination model for `notes`
- [ ] Update the dissemination code in `IntakeToDissemination` to include this field
- [ ] Update the API view for `v1_0_0` to disseminate this field as part of `notes`
- [ ] Update the workbooks on the static site so that this new template is distributed to users
- [ ] Generate/update workbooks for Cypress testing
```

To generate new workbooks, we will need... to fix the workbook generator.

**Comment by jadudm** [comment]
This was inspired by bug #1940.

**Comment by jadudm** [comment]
Moved all the info to the original bug ticket.
