### ISSUE TITLE
Implement Audit Information screen

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#214]
## Background

This story covers the design and implementation of the **Audit info** page. We mocked and tested this page in sprint 1 and did recommended this very small refinement, which doesn't need to be mocked and can be handled as part of front end implementation: Remove the second tier bullets (a., b., c., etc.). People said that these letters are not useful.

You can find this in the story map [here](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1649157602768).

It covers the following stories:

1. As an auditor, I can enter or edit audit info data and have it populate my SF-SAC so that I can complete my audit.

**We'll know we're done when...**
- [ ] When a user can enter or edit audit info data and have it populate the **audit info** part of the SAC in the data model.
  
**Tasks**
- [ ] [FRONT END] Implement refined mocks.
- [ ] [BACK END] Update SAC data model and API for new fields
- [ ] [DESIGN/PRODUCT] Define logic and flesh out edge cases in acceptance criteria
- [x] Dependent on https://github.com/GSA-TTS/FAC/issues/185

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] Automated accessibility tests pass
- [ ] Manual accessibility tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

## Design

https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3534%3A16365
* Note: The header section is outdated, but will be updated in https://github.com/GSA-TTS/FAC/issues/375

![image](https://user-images.githubusercontent.com/2846578/182708320-4522618d-26e5-42ee-858d-47c78c1d3377.png)

## Implementation Notes

Agencies list:
- This version of the mockup replaces checkboxes with a multiselect html list of all the agencies.
- The agencies are listed in numerical order instead of alphabetical order. During interviews, auditors noted that they know the number code for the agency the audit is under. Displaying in numerical order makes it easier to browse by that number, or find it by typing the number into the list and having it jump down to that number.
- As far as I can tell, this is not an existing USWDS component; their multiselect option is a combobox. 
- See #305 for our reasoning in choosing this pattern.

Please note: the top-level navigation and the page header (organization name, report id, entity type, etc.) layout will be changing in the future.
