### ISSUE TITLE
Develop SOP for CX

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2146]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** support our users
**as a** product owner
**I want** a documented process for support work.

# Acceptance Criteria

We need a document---at the least, an outline or flowchart, perhaps---that describes how a helpdesk ticket becomes actionable work by the team.  

The document should guide any member of the team who is familiar with Zendesk in doing the work of processing help tickets that have come into the system.

Our goal is to run the process for a week, see how it works, and revisit at the end of that week to reflect, revise, and document our process.

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### Tasks
- [x] Revise the [helpdesk ticketing process](https://docs.google.com/document/d/1gN55UQa8ofsAUylBWR9-TU_ztARzTpSvlwZCqW0-wLk/edit#heading=h.q9eufeg2m9ji) draft as needed
- [x] Revise Zendesk intake ticket as needed to support the workflow
- [x] Revise Github helpdesk issue template as needed
- [x] Run the process for a week to see how it works; update process as needed
- [x] Check in on effectiveness
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* CX shepherd: @LeoFotovich  

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

We have drafted a process. Now it is time to see if it works. 

The important thing to remember is that the process can be changed. The reason for trying it is to see if our *process* is as lightweight as possible. We do not want to spend time doing *triage* on tickets; we want to spend our energy *answering* tickets and *helping our users*. Those are two very different things.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

None.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
We've revised our process. We now have a regular sync for helpdesk work, and improvements to process and the SOP are ongoing.
