### ISSUE TITLE
Implement Award Findings page

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#215]
## Background

This story covers the design and implementation of the **award findings page**. This is currently scoped as a pace where auditors download and upload an Excel template. TBD how we want to split off Excel template design and implementation from this issue. 

This is dependent on #185. 

It covers the following stories (likely will need to break this up into more than one issue):

1. As an auditor I can upload a file containing award findings data from my local machine in a format that will be accepted.
2. As an auditor I can upload a file containing award findings data from my local machine iand have it populate the SF-SAC.
4. As an auditor, I can get a template for how I need to format my award findings data so that it will be accepted.

**Acceptance Criteria**
- [ ] The page renders as designed
- [ ] A user can download [this worksheet](FACWorkbooks\EmbeddedResources\FederalAwardsFindingsTemplateUG2016.xlsx) with their EIN number inside
- [ ] A user can upload a completed worksheet via drag and drop or file selection
- [ ] Display worksheet validation errors
  - What is list of errors? 
- [ ] Display file name in place of "upload worksheet" button when it validates successfully. 
- [ ] Display option to delete uploaded file with warning message
- [ ] When "Save and continue" button is clicked, data is uploaded to the server and saved in the DB
  
**Tasks**
- [ ] Design designs all the things
- [ ] Engineering engineers all the things

**Definition of Done**

- [ ] Meets acceptance criteria
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate. 

## Design
* https://www.figma.com/file/8REinLFKSMj7pwQ7JIEHGW/FAC-Sprint-11-prototype?node-id=3%3A3568
* See these designs for [error state](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3061%3A14588) and upload

**Comment by austinhernandez** [comment]
here is fed award uploaded page:

https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3061%3A14588
