### ISSUE TITLE
Reset migrations prior to launch

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2152]
### Tasks

The existing migrations don't represent any states we'd actually want to track or go back to. Now that the models reflect a more realistic state, we should reset migrations to make future changes clearer and easier to track.

```[tasklist]
- [ ] PR for resetting all migrations: https://github.com/GSA-TTS/FAC/pull/2178
- [x] Reset database in `dev` before the dev deploy
- [x] Reset database in `staging` before staging deploy
- [ ] Reset database in `prod` before prod deploy
```

**Comment by timoballard** [comment]
for each environment:

```
cf delete-service-key fac-db postgrest
cf unbind-service gsa-fac fac-db
cf delete-service fac-db
```

**Comment by asteel-gsa** [comment]
This is complete as of 9/20
