### ISSUE TITLE
Update Figma mock of tribal consent page to include authentic text, layout

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2157]
```[tasklist]
### Tasks
- [x] Turn three screens into one. ("Modal text," followed by Y/N, followed by signature)
- [x] Make sure text is a copy from Census
```

## We'll know we're done when

```[tasklist]
### Tasks
- [x] We have a single-screen form ready for implementation by engineering
- [x] We have signoff from content for (plain) language
- [x] We have signoff from product
```

**Comment by Leighdiddy** [comment]
@lauraherring @jadudm designs are updated and awaiting Laura's plain language treatment: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-Source-of-Truth?type=design&node-id=1%3A31587&mode=design&t=aSsuCZi6cLL3XXif-1

**Comment by jadudm** [comment]
As part of this work, it would be good to know for certain: is the *auditor certifying official* completing this statement, or the *auditee certifying official*?

@Carley-Sullivan , thoughts?

**Comment by Carley-Sullivan** [comment]
@Leighdiddy Auditee Certifying official should be signing the tribal release page. Its their data & their audit - it is up to them to suppress it.

**Comment by lauraherring** [comment]
@Leighdiddy I added copy to the page. It's very short so there's going to need to be a lot of spacing adjusted. I also put an additional comment on the actual certification boxes themselves. Passing this one back to you.

**Comment by jadudm** [comment]
We can pick up spacing in the implementation if need be. @jperson1 has generally "done the right thing" there, so I wouldn't worry *too much* about whitespace in the mock.

**Comment by lauraherring** [comment]
@jadudm Then from my perspective, this can move to done and/or engineering available.

**Comment by Leighdiddy** [comment]
@jadudm I did adjust the UI a bit to better highlight the action items, all done on the design front: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-Source-of-Truth?type=design&node-id=1%3A31587&mode=design&t=aLSFj6I0RhvATjzG-1

**Comment by jadudm** [comment]
Two questions:

First question: What style guide are we using for consistency around tribe/tribal, and (I'm only asking because I want to make sure), did we apply that editorial style to the language on this page? E.g. [BIA's guide](https://www.bia.gov/guide/editorial-guide#:~:text=List%20of%20Abbreviations-,Cultural%20Terms,-American%20Indian%20and).

Second question: Carley said (unless this changed and I missed it) that it is the **Auditee Certifying Official** who should complete this form ([above](https://github.com/GSA-TTS/FAC/issues/2157#issuecomment-1737269683)). The form is genericized in some ways, but this is phrased from the perspective of an auditor who is making a claim on behalf of the auditee. Is this what we want? It feels like it isn't. 

Happy to huddle on this tomorrow if we need to in order to sync.

**Comment by lauraherring** [comment]
@jadudm I was following the same style used in the Uniform Guidance. I like the idea of following BIA better, though I'll need to talk with @Carley-Sullivan to see what exactly we can change and what we can't, similar to the auditee and auditor cert pages.

**Comment by lauraherring** [comment]
OK, chatted with Carley and made some more updates to the page to clarify that it's the auditee ceritfying official doing the work on this page. I also talked through the UG vs BIA style with her and we decided to stick with the UG style, even though it's in conflict with BIA.

**Comment by jadudm** [comment]
Good to go, then.
