### ISSUE TITLE
Update Figma for checklist

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2158]
```[tasklist]
### Tasks
- [x] Update the checklist mock to include the tribal consent page
- [x] Develop content for that checklist entry
```

## We'll know we're done when

```[tasklist]
### Tasks
- [x] We have a revised checklist ready for implementation by engineering
- [x] We have signoff from content for (plain) language
- [x] We have signoff from product
```

**Comment by Leighdiddy** [comment]
@lauraherring Design updated in Figma, let me know if you'll need spacing adjustments after inserting the new text! https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-Source-of-Truth?type=design&node-id=1%3A31587&mode=design&t=aSsuCZi6cLL3XXif-1

**Comment by Carley-Sullivan** [comment]
@lauraherring  LGTM

**Comment by James-Paul-Mason** [comment]
@lauraherring Clear and concise--good to go.

**Comment by lauraherring** [comment]
Great.

@jadudm This one is ready to go to the dev team for implementation.

**Comment by jadudm** [comment]
LGTM.
