### ISSUE TITLE
Front End - SF-SAC General Information

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#217]
Breakout task for https://github.com/GSA-TTS/FAC/issues/185

**Tasks:**
- [ ] develop the entire form (potentially break up if this is too much)
- [ ] Navigate form through left menu anchor links

**Acceptance Criteria:**
from [implementation notes](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2464%3A10748)

Done, aside from auto populated aspects: 
- [x] Fiscal period start and end dates should be autopopulated from the auditee info page. These fields should not be editable here. 
- [x] Auditee UEI should be autopopulated from the auditee info page. This field should not be editable here. 
- [x] Auditee name - should be autopopulated from the auditee info page. This field should not be editable here. 
- [x] Auditee address should be autopopulated from SAM.gov. This field should not be editable here. 
- [x] Auditee email - Should allow folks to select from emails they entered on the submission access page.
- [x] Primary auditor email - Should allow folks to select from emails they entered on the submission access page.
- [x] All required fields show validation messages

**Comment by petermarks-gsa** [comment]
@MelissaBraxton  Yes, this issue just covers the general information form.

**Comment by heymatthenry** [comment]
@MelissaBraxton & @petermarks-gsa: Couple of questions here: several of the fields on this form (FY start/end, EIN, contact info, etc.) are repeated from the pre-SAC screens. Are we imagining they're going to be populated when the user gets to this page? If so, are they going to be editable? There's a bunch of validation happening in the pre-SAC flow, particularly around FY & EIN and I'm wondering if we're going to have to do all of those checks again.

**Comment by petermarks-gsa** [comment]
@MelissaBraxton I imagine it's not our intention to ask for the same information twice? Following up on the specific fields @heymatthenry mentioned:

- **FY start/end** - @MelissaBraxton Are "Fiscal period Start/End Date" and "Auditee fiscal period start/end date for this submission" truly the same thing? 
- **EIN** - @heymatthenry I'm not seeing a EIN form in the pre-SAC screen [mocks](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=1862%3A15765)
- **Contact info** - @MelissaBraxton Seems like "Auditee contacts" on the audit submission access page and "Auditee contact" on general information are the same thing, only you can only enter one contact on the latter? Would it make sense to scrap the contact on the second form or just display the multiple contacts already entered?  

-

**Comment by heymatthenry** [comment]
@petermarks-gsa Sorry, I mean UEI—not EIN

**Comment by MelissaBraxton** [comment]
@heymatthenry and @petermarks-gsa  - There are implementation notes to the left of the current Figma mocks that I believe address these Qs: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2464%3A10748

**Comment by heymatthenry** [comment]
Thanks, @MelissaBraxton. Those are super helpful and I think(?) address everything I was wondering. I must've overlooked those while hopping around different iterations of the form in the Figma file.

**Comment by heymatthenry** [comment]
@petermarks-gsa I have a WIP PR for this (GSA-TTS/FAC-Frontend#23 — Federalist link in the PR) and I just want to check in on a few pieces of it before wrapping it up:

* Currently the only client-side validation we're doing is whether the fields are not null, so we're not checking stuff like format of EIN, phone numbers, etc. Are we expecting to validate those things on the client side? If so is that part of this ticket?
* Is the behavior of everything we've implemented up to now working as expected? Just want to confirm before I start memorializing that behavior in tests.

**Comment by petermarks-gsa** [comment]
@heymatthenry Minor bug: I can select multiple "audit period covered" ratios (should only be able to select one @MelissaBraxton?), but I cannot deselect the radios: 

![Screen Shot 2022-06-16 at 1 53 37 PM](https://user-images.githubusercontent.com/100610443/174135400-718ff2a2-0f36-4bdc-8477-ff6025c6b705.png)

**Comment by heymatthenry** [comment]
Thanks, @petermarks-gsa. I fixed the bug on the audit period radio buttons and will wrap the rest of it up.

**Comment by petermarks-gsa** [comment]
@heymatthenry Would you mind sending me an updated federalist link to review the fixes?

**Comment by petermarks-gsa** [comment]
Awesome, thanks Matt! calling this done. 

Also, good to know there is a static [Federalist preview of main](https://federalist-9a617ff8-042d-4076-9581-bb999f9c6639.app.cloud.gov/site/gsa-tts/fac-frontend/audit/submission/) link :)
