### ISSUE TITLE
New JSON Schema for tribal access form

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2185]
Migrating field names from https://github.com/GSA-TTS/FAC/issues/2107: 

This form collects three pieces of information:

* A radio button that we will call `is_tribal_information_authorized_to_be_public`
  * `Boolean`
* A text field `tribal_authorization_certifying_official_name`
  * `String`
* A text field `tribal_authorization_certifying_official_title`: 
  * `String`

These fields are all required. We will use the first field in our dissemination logic; the other two fields (the name/date) are not disseminated at this time.

## We'll know we're done when

```[tasklist]
### Tasks
- [ ] The schema is implemented
- [ ] Validations are updated
- [ ] Rudimentary tests are included in the schema test file
- [ ] All tests pass locally
- [ ] All tests pass in GH Actions
```
