### ISSUE TITLE
Run `seed_cog_data` in `run.sh` and `.profile`

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2191]
### Tasks
```[tasklist]
- [ ] `seed_cog_data` must be updated to run as described below
- [ ] `seed_cog_data` should be run as part of run.sh and .profile
``` 

This script seeds the cog/over table with the living table from Census. However, that should only happen *once*. 

Therefore, `seed_cog_data` must be modified so it behaves as follows:

```
IF the seed table already exists
THEN do nothing
ELSE
  load the seed data
```

`seed_cog_data` is a Django command. This means that

```
python manage.py seed_cog_data
```

is essentially all that needs to be added to the appropriate locations in the boot scripts.

**Comment by JeanMarie-TTS** [comment]
@jadudm Please note that this should only be run once in `prod`. Subsequent cog assignments update this table, and these updates should not be lost when the next deployment happems.

**Comment by jadudm** [comment]
@JeanMarie-TTS , I've updated the story to the best of my understanding and assigned it over to you. If you can pick it up, it would be much appreciated.

**Comment by JeanMarie-TTS** [comment]
Here's how I think this requirement should be addressed:

- [ ] Add a `source` column to CognizantBaseline table so we can distinguish rows seeded from census from rows populated by GSA FAC
- [ ] Modify seed_cog_data such that it deletes all Census rows before loading them from the csv file in the fixtures folder. The current version deletes all rows first.
- [ ] Set up a signal in the support app to do a post_migrate task. Invoke seed_cod_data as part of this post_migrate action.  

@jadudm ,  please indicate if you agree with this, or if you would like someone to review this before finalizing.

**Comment by JeanMarie-TTS** [comment]
@gsa-suk  Regarding Matt's concern about EIN, this should be stored in a CharFiled (or equivalent) whenever we persist it, This will allow leading zeros to be stored. Not sure where it is defined as an IntegerField, but this should be corrected.

**Comment by JeanMarie-TTS** [comment]
django signals do not run asynchronously. I'm not convinced that the issue about cog/over was due to the use of signals - probably a bug that could have been fixed without a redesign.
If the preference is to use shell scripts and make sure they are called from the right places, I'm okay though I personally find these things harder to understand and debig.

BTW @jadudm , we should create a ticket to fix run_2022 to make sure it does not leave behind SingleAuditChecklist records in the database corresponding to the census 2022 data. Alternatively, we can just remove this module from our codebase so it won't accidentally be run.

**Comment by gsa-suk** [comment]
run_2022 is meant for local testing only.

**Comment by gsa-suk** [comment]
Created bug ticket to not disseminate test data in run_2022.py.  https://github.com/GSA-TTS/FAC/issues/2224

**Comment by gsa-suk** [comment]
Based on comments above and discussions, the plan is as follows:
1. In support/models.py, add 'source' column to CognizantBaseline table.  
2.In support/management/commands/seed_cog_baseline.py, if CognizantBaseline table does not exist, load data from support/fixtures/census_baeline.csv to CognizantBaseline table with 'source' set to 'Census'.
3. In support/management/commands/seed_cog_baseline.py, if CognizantBaseline table exists, delete rows with 'source' = 'Census'.  Then load data from support/fixtures/census_baeline.csv to CognizantBaseline table with 'source' set to 'Census'.
4. In support/signals.py, add 'source' = 'GSA_FAC' when saving data to CognizantBaseline table.
5. In run.sh, add 'python manage.py seed_cog_baseline'.
6. In .profile, add 'python manage.py seed_cog_baseline'.

**Comment by jadudm** [comment]
For consistency w/ other places in the app, a source of `GSA` is probably enough.

**Comment by JeanMarie-TTS** [comment]
I assume "table does not exist" to mean that there are no rows in the table. The table should exist since it is is in models,py
We should only delete Census rows that are `active`.

**Comment by JeanMarie-TTS** [comment]
@gsa-suk 
I think you can use dbkey to determine if a row was sourced from Census. So, we may not have to add another column to the table.
To deal with active and inactive records, we should delete all the active census records from the table. Then each inactive Census record in the table should be deleted from the pd dataframe.

**Comment by jadudm** [comment]
I don't mind the column re: source, to be honest. Explicit is fine. It
mirrors the dissemination side, FWIW. Up to y'all.
