### ISSUE TITLE
[HD]: UEI validates, but cannot get past the UEI validation page.

### ISSUE THREAD

**Issue by Carley-Sullivan** [GSA-TTS/FAC#2196]
# Suggested fix

From conversation on the team, it appears that there can be interaction issues if the "validate" button is not pressed before continuing. (Meaning, we didn't fetch/validate the UEI.)

So, we're going to:

```[tasklist]
### Tasks
- [ ] Grey out the continue button
- [ ] Enable it after the validation completes successfully. 
``` 

This, we think, will fix things.

### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/35

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

Attempting to submit audit for 06/30/2023 year end. I am able to start the submission and reach step two where I am able to successfully validate my UEI and then enter the fiscal period dates for my audit. When I hit continue, the page refreshes and is still on step 2. It does not move forward, it generates no errors or popups or otherwise.

**Comment by jadudm** [comment]
Went to app.fac.gov, and cannot get past the UEI validation page. The user's experience seems correct.

Could a dev please try this on staging, and then prod, and see what is up?

**Comment by jadudm** [comment]
I think it will be good for us to take another look at this, just to make sure we've landed a good fix/experience for the user. 

The PR

https://github.com/GSA-TTS/FAC/pull/2206

addressed it, but let's take another look to either 1) decide we have a good fix, or 2) ticket further work to make sure that the UX is good.

**Comment by jadudm** [comment]
Closed via #2222, unless we see more tickets on this.
