### ISSUE TITLE
Design form page save/discard data prompt

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#220]
**Background**

This issue covers the front end design and implementation of functionality that helps users save forms in progress. 

Desired behavior: 

Record (but don't save) changes as they're made, but then prompt users to save or discard any unsaved changes if they try to navigate away from the page.

It covers the following stories:

1. As an auditor or auditee inputting submission data, I need to know how my progress on a form page will be saved so that I don’t worry about my information being lost.

**We'll know we're done when...**
- [ ] When a user can ...
  
**Tasks**
- [ ] Design prompt for users (modal?) that tells them they have unsaved data and asks them to either save or discard unsaved data
- [ ] Engineering engineers all the things

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] Automated accessibility tests pass
- [ ] Manual accessibility tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").

**Comment by austinhernandez** [comment]
Question for @heymatthenry: If the browser is closed by quitting the application will the modal be triggered? Also, since we talked about using browser controls as default for accessibility, is this a case where we would want to do that as well? Like a standard browser popup?

<img width="931" alt="Screen Shot 2022-06-10 at 11 16 42 AM" src="https://user-images.githubusercontent.com/23194720/173097169-b252f0ea-19ff-4207-b76e-e2a74e54a5f9.png">


If this is a modal here is the design:
![image](https://user-images.githubusercontent.com/23194720/173097141-0af1988c-3ba7-4cd6-b155-8d9a878cbc55.png)

**Comment by heymatthenry** [comment]
@austinhernandez I think we should stick with the browser-based alert unless there's a compelling UX reason to do otherwise. We'd have to replicate a lot of effort in terms of bulletproofing the accessibility and functionality that we'd get for free just leveraging the browser.

**Comment by MelissaBraxton** [comment]
Agree with @heymatthenry and @austinhernandez 's recs to just use the browser based alert. With that said, what else needs to happen before we call this issue done?

**Comment by petermarks-gsa** [comment]
Next step: Peter to create an implementation issue for this.

**Comment by MelissaBraxton** [comment]
Hey there, @petermarks-gsa Is there an implementation issue for this. Can we call this done?

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Thanks for the nudge on this. I created https://github.com/GSA-TTS/FAC/issues/311

Is the design really just the browser / operating system alert (below) and does this have final copy? 

![173097141-0af1988c-3ba7-4cd6-b155-8d9a878cbc55](https://user-images.githubusercontent.com/100610443/177372477-a07c657f-55c7-4642-87cf-6ea322b52f87.png)

**Comment by MelissaBraxton** [comment]
Yes, to the first Q. Re: the copy, can we call it done for now with the idea that our content person will do a full copy editing pass (including this copy) when they arrive?
