### ISSUE TITLE
Mock SEFA page of the SF-SAC

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#221]
**Background**

This issue covers design mocks for the SEFA part of the SF-SAC and is the first task as part of the larger story to implement the SEFA page (#187). Current mocks are [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2464%3A11167)

**We'll know we're done when...**
When the page design has:
- [ ] ~A way for users to enter SEFA data into a web form on the page~
- [ ] ~A way for users to add as many rows of SEFA data they'd like to enter via the web form~
- [x] A way for users to get a template for SEFA data that they can fill out offline 
- [x] A way for users to upload a completed template
  
  
**Tasks**
- [X] Mock up SEFA page
- [X] Link to current mocks in this issue

**Definition of Done**
- [ ] Meets acceptance criteria
- [ ] PO approved

**Comment by MelissaBraxton** [comment]
I think this is halfway done. Current mocks don't have web form fields for SEFA data. Those need to be added.

**Comment by MelissaBraxton** [comment]
Based on recent discussion w/ @petermarks-gsa re: testing a hypothesis around not including web form data entry as part of the MVP, this is ready for review[ here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2837%3A12888).

**Comment by MelissaBraxton** [comment]
@petermarks-gsa - With the creation of #255, is this done?

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Yes, we can consider this done.
