### ISSUE TITLE
Epic: Implement backup and restore workflows

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#2211]
## Updated 20240117

We want to bring the work on media backups in, and get it working. We then want to revisit this ticket, curate it/close it, and create some smaller epics to do targeted work that moves backups forward in sync with the rest of the platform. This ticket is too large/complex at this point. 

In short: lets get S3 backups running reliably, and then revisit/refine/curate/close/etc.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2212
- [ ] https://github.com/GSA-TTS/FAC/issues/2213
- [ ] https://github.com/GSA-TTS/FAC/issues/2215
- [ ] https://github.com/GSA-TTS/FAC/issues/2214
- [ ] https://github.com/GSA-TTS/FAC/issues/2216
- [ ] https://github.com/GSA-TTS/FAC/issues/2217
- [ ] https://github.com/GSA-TTS/FAC/issues/2218
- [ ] https://github.com/GSA-TTS/FAC/issues/2219
- [ ] https://github.com/GSA-TTS/FAC/issues/2221
- [ ] https://github.com/GSA-TTS/FAC/issues/2279
- [ ] https://github.com/GSA-TTS/FAC/issues/2280
- [ ] https://github.com/GSA-TTS/FAC/issues/2281
```

**Comment by asteel-gsa** [comment]
This already occurs every prod deployment

**Comment by jadudm** [comment]
This epic has a lot of pieces to it. I'd like us to scope it back and/or think about how this work is part of ongoing engineering effort. The parts of the epic are right, but I'm not sure it makes sense as its own thing for where we're at and how we want to be working. Leaving  this as-is/here for now, but I do want to get to a place where epics have timelines, and this would be hard to both say "how we'll know we're done" and "when will it be done as stated."

(We've done a lot of good work on it/in this space, but I think it wants to be restructured at this point.)

**Comment by jadudm** [comment]
I know @asteel-gsa and @timoballard have had some conversation around this, and I think the right thing to do is to close the current epic. It needs to be restructured and carried out in a way that more people can get involved. However, we're now positioned to do so. The individual tickets are still open, and over the next week or two, we can clean them up and get them organized into something we can tackle. Closing this top-level epic, which has been around since *September*.
