### ISSUE TITLE
Implement on-demand backup (db and media) tooling in the codebase

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2213]
This work has already been spiked out/done?

To consider it done:

```[tasklist]
### Tasks
- [x] It is possible to trigger the backup from a GH action
- [x] Documentation regarding the process exists
- [x] The action is triggered automatically on deploys to `prod`
```

**Comment by asteel-gsa** [comment]
this will be complete with #2220 merge
