### ISSUE TITLE
[HD]: Need FAQ on 30 day waiver

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#2237]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/37

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

We are trying to submit audits for the year ended June 30, 2023 on the new FAC website. Of 6 different entities that we are trying to submit, only one was “found” when we entered it's  UEI in the new website. We have checked the SAMs website and confirmed that the UEI we are entering is 100% correct. The audits need to be submitted within 30 days of their audit report date in order to remain compliant so we will need this resolved soon. I've attached a screen shot of the error message we are receiving. Please advise or provide me with a phone number with someone I can speak to about this issue. 

```[tasklist]
### Tasks
```

**Comment by Carley-Sullivan** [comment]
I think we have a FAQ on this, it just isn't published in ZD.  Already OMB approved language
