### ISSUE TITLE
API bugfixes

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2249]
```[tasklist]
### Tasks
- [x] Add `fac_accepted_date` to dissemination
- [x] Add migration to rewrite `submitted` to `accepted` for any existing submissions
- [x] Fix multiple return values in `general` view for a single audit
```

```[tasklist]
### Tasks for MJ/DS
- [x] Explain fields / data dictionary? (might be its own ticket)
- [ ] Explain date fields
- [x] Make sure all dates are present
- [x] `is_duplicate_reports` no longer exists? (I don't see it anywhere in the intake)
- [x] Lookup for name of cog/oversight agency? (How could we do this?) Name of agency from two-digit identifier?
- [x] Confirm report_id will never be a number.
- [x] Fix docs: trailing slash on API_GOV_URL
```

For the migration, we have an interesting question. 

It is not enough to assign a default value to the field when the migration runs. Instead, we need every empty `fac_accepted_date` to take on the value of `submitted` from that row. That is, we can't say "any previously existing rows have the default value of *X* for the accepted date`, but instead we need to say `the accepted date for all rows that exist as this migration is applied should be the value contained in the `accepted` field in the same row."

There's a way to do this with migration functions ...

https://docs.djangoproject.com/en/4.2/topics/migrations/#data-migrations

might be a starting point in the docs.

**Comment by jadudm** [comment]
Some questions from HHS came from here: https://docs.google.com/document/d/19tbaKVkFFTIUOE2nJ23vZmU16mTXJGld/edit

Those are reflected in the ticket above.

**Comment by jadudm** [comment]
Regarding `is_duplicate_reports`, this does not seem to be part of our collection anywhere. Without more information, we're going to leave it absent from the API. It seems to be historic. (Historic data will reflect it, but it really does not seem to be part of the 2023 collection.)

**Comment by jadudm** [comment]
We are adding back in the certification timestamps for `auditor` and `auditee`.

**Comment by jadudm** [comment]
I do not have a timeline (yet) for when we will have an agency number lookup. This is for two reasons:

1. I do not know what the authoritative list is for these numbers/names
2. I do not know if the FAC should be the authoritative source

We have a list that we use in our various interface elements:

https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/data/cfda-agencies-20230626.csv

And, we could discuss how we might make that available. However, this is part of our transition that is unclear to me: why did Census maintain this list? Why did they provide it? How should we maintain it? How should we provide it? What process/policy do we have around maintaining/changing it?

Happy to discuss further, but for now, I'm uncertain what would be a best practice/best solution in response to this question.

**Comment by jadudm** [comment]
For tracking: because of how the state for `DISSEMINATED` is set internally, we're going to go ahead and set `fac_accepted_date` to `submitted` for now in the `IntakeToDisseminated` code. 

This may change in the future, but for now, it is semantically accurate, and won't do us wrong.

**Comment by jadudm** [comment]
`is_duplicate_reports` is 

> Does the auditor's report include a statement that the auditee's financial statements include departments, agencies, or other organizational units expending Federal awards which are not included in this audit? (AICPA Audit Guide) *

from Audit Info. Needs to be added to the API.
