### ISSUE TITLE
[HD]: Ability to print/view SF-SAC Form 

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2257]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/47

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [X] other

### What browser did the user report as using?

None

### What happened?

Note: Creating ticket to add a future enchancement to the new system, regarding to user ability to print/view forms for review. 

```[tasklist]
### Tasks
```

**Comment by Carley-Sullivan** [comment]
reviewed this with @James-Paul-Mason FAQ draft is ready.
