### ISSUE TITLE
Revise Figma UI to reflect live site

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#2293]
```[tasklist]
### Tasks
- [ ] Review and resolve all open comments re: UI in Figma source of truth
- [ ] Review Figma SOT against current live site
- [ ] ticket UI corrections for front end as needed
```

**Comment by Leighdiddy** [comment]
This has become a rolling process, does not need ticketed!
