### ISSUE TITLE
Epic: API download of protected data

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2298]
```[tasklist]
### Timeline
- [x] Mid-Jan: Have code complete, tested locally
- [ ] Late Jan: Have confirmational and failing tests in Cypress, running in `staging`
- [ ] Early Feb: Have code in production
- [ ] Early Feb: Issue keys to first agency
```

## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Federal users
**What**: Performing oversight over all data
**Why**: It's required.

The tribal data requires some additional handling via the API. Given that the API is really it's own application, it makes sense to epic/story it out separately. 

## Background

 https://github.com/GSA-TTS/FAC/issues/2184 has background on this. This epic is updated to break out the work in a bit more granularity. This was further developed by @purvinptl in notes [here](https://docs.google.com/document/d/142ebz8pmn7fdz_1RZgbx6MvzdrWlGGZ7ephR2B8UnEc/edit#heading=h.ntpof6c4oef). What follows is from these two documents.

## Part 1: Adding access to SF-SAC data

The first part of this work sets up tribal access for the SF-SAC. This is a necessary first step, because it also involves creating the infrastructure for recognizing what API keys should have tribal data access.

```[tasklist]
### Tasks
- [x] Add Django model (`TribalApiAccessKeyIds`) for tribal access in `dissemination`
- [x] Update `has_tribal_data_access` in `dissemination` to use  `TribalApiAccessKeyIds`
- [ ] Add tests (that should execute locally and in the TESTING environment) to verify that access is appropriately moderated
- [ ] Extend Cypress tests to verify that Tribal data *can* be accessed with a key that has appropriate privs
- [x] Add two endpoints to administrative API: `add_tribal_api_key_access` and `remove_tribal_api_key_access`
- [ ] https://github.com/GSA-TTS/FAC/issues/3281
- [ ] https://github.com/GSA-TTS/FAC/issues/3369
```

First, we will want a table that can track who has access. We think it should have

* email address of keyholder
* api.data.gov API key Id
* the date (YYYY-MM-DD) the key was added to the table

We then have a function attached to the dissemination API called `has_tribal_data_access`. This function should now:

1. Get the api.data.gov API key Id (not the key itself) from the HTTPS headers
2. If the key exists in `TribalApiAccessKeyIds` and the date is not passed, return 1 (cast to the boolean `TRUE`). Otherwise, 0 (`FALSE`)

This will look similar to the code in the admin API for determining access. Unit tests (in Python) should be added to the dissemination API tests to determine this functions correctly. For a variety of reasons, we can expect that these tests will *only* ever run in LOCAL or TESTING environments, not PREVIEW, DEV, STAGING, or PRODUCTION. If need be, data can be inserted directly into the DB to test against (eg. some data in the DB that is flagged with `is_public` == `false`).

There is currently a test in Cypress that inserts (fake) tribal data, and determines whether a key that does *not* have privs correctly *fails* to access tribal data. Another key should be added to the Cypress test suite. That key should be *granted* tribal access. Then, the Cypress suite should be extended to determine whether the key with privs can *successfully* access tribal data, where a key without privs fails.

Finally, to close  out part 1, we want to add two endpoints to the administrative API: one for adding keys to the table, and one for removing them. This will be in the `support` app, and look very similar to the code for adding and removing individual email addresses from the user_userprivs table (whatever it is called). We do not need the ability to bulk add API keys (e.g. we do not need something that lets us add multiple, the way we needed it for email addresses.)

## Part 2a: Implementing `GET` for tribal PDFs

The second part involves granting access to keys so that programmatic download of PDFs is possible.

```[tasklist]
### Tasks
- [ ] Implement `request_tribal_audit_report_access`
- [ ] Implement tests for `request_tribal_audit_report_access`
```

This call needs to be in pl/PgSQL. 

1. The user will call the function (using a library like `requests` in Python)
2. The function will use `has_tribal_data_access` (calling across schemas; don't replicate the code) to determine if the API key should have access;
3. If access is verified, then
    1. Generate a UUID4
    2. Write that into the `one_time_tribal_audit_report_access` table, including the UUID, api key ID, report id, and timestamp
    3. Return the UUID to the user

The naming is verbose, but the reason is that we do not know how/if this will be abstracted in the future. Better to be explicit now, and we will revise/refactor later if we think this can be generalized.

The tests for this would involve adding unit tests (to run in LOCAL or TESTING) that

1. Call the function
2. Verify (via DB call) that the correct row was inserted into the table

### Part 2b: Implementing `GET` for tribal PDFs

Once we know we can control access, we need to implement the actual `GET` of the file.

1. Add a view for `pdf/uuid/<uuid>`
2. When the view is hit (in the browser, with `curl`, `requests`, etc.)
    1. Delete all rows in the `one_time_tribal...` table where the timestamp is more than 1m old
    2. Check if the UUID exists in the table.
    3. If found
        1. Delete the row
        2. create a pre-signed AWS S3 URL with a 1m lifetime for the report id that is in the table
        3. Redirect the client to the generated S3 URL
    4. If not found, return an appropriate... er. Return a 403? (Access denied?)

To test this, it should be possible to add unit tests that call the API function, get a UUID, and then do a `GET` against the view. No PDF has to be returned (it can be mocked), but we do need to verify that the row is deleted, and the appropriate redirect (302?) happens. (I can't remember my HTTP status codes.)

We do not (yet) have automated loading of test data. [That is for a future ticket, sadly](https://github.com/GSA-TTS/fac-data-test-search). However, this should be able to be unit tested well enough to have confidence. It should be tested manually as well.

**Comment by danswick** [comment]
Docs are only remaining items. Once those are merged, this epic will be complete.

**Comment by danswick** [comment]
Docs are published. This is done!
