### ISSUE TITLE
Epic: Instructions incorporated into workbooks

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2299]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Auditors and auditees
**What**: They're completing the workbooks
**Why**: We want instructions close to where they're working

The old Census workbooks had instructions embedded in a tab. We can do the same thing. The workbook instructions are already implemented in a sonnet data structure, so we can pull them in and render them on a tab without too much trouble.

Note the instructions also drive the rendering of the static site.

```[tasklist]
### Stories
- [ ] Bring the sonnets into `main`
- [ ] Decide how they best interact with the static site
- [ ] Add instructions to each of the workbooks
```
