### ISSUE TITLE
Epic: Historic data migration

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2302]
Our goal is to do some planning for the coming migration of historic Census data, so we can move with confidence once we have access.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2394
- [ ] https://github.com/GSA-TTS/FAC/issues/2395
- [ ] https://github.com/GSA-TTS/FAC/issues/2396
- [ ] https://github.com/GSA-TTS/FAC/issues/2528
- [ ] https://github.com/GSA-TTS/FAC/issues/2576
- [ ] https://github.com/GSA-TTS/FAC/issues/2577
- [ ] https://github.com/GSA-TTS/FAC/issues/2578
- [ ] https://github.com/GSA-TTS/FAC/issues/2579
- [ ] https://github.com/GSA-TTS/FAC/issues/2815
- [ ] https://github.com/GSA-TTS/FAC/issues/2816
- [ ] https://github.com/GSA-TTS/FAC/issues/2886
- [ ] https://github.com/GSA-TTS/FAC/issues/2889
```

**Comment by JeanMarie-TTS** [comment]
https://docs.google.com/document/d/1VV2jox-M1uUHZJR3b4et9SvYiyn90niPdKT5ElH7iNY/edit

**Comment by sambodeme** [comment]
We moved tickets to #2837 to keep tracking more consistent
