### ISSUE TITLE
Document "where things stand" for research and design

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#231]
**Background**
With the Design Lead rolling off the project, we want to make sure knowledge is not lost, the team is resilient and can easily onboard additional designers as needed. We are aiming for a document like [this](https://docs.google.com/document/d/1VcitXr5MZ1J6_EcMk4WSJYtz6VchxtigxsSliaCE49k/edit): 

**Acceptance Criteria (We'll know we're done when...)**
- [x] We have a document that lays out where all design work currently stands and what to consider in picking it up. 
- [x] A peer designer confirms that they have a picture of the landscape and how and where they might carry work forward on any front. 
- [x] Relevant content is copied or linked to from the wiki

**Tasks**
- [x] Create document
- [x] Invite peer review
- [x] Update wiki as needed

**Comment by MelissaBraxton** [comment]
Drafting [here.](https://docs.google.com/document/d/1EILl0nZr59T4PFJJMtFbmnQDJPksgzIFPuoFDN0bk0g/edit#). My thought is that this work should cover #236 , but let me know if there's something else you want to see in terms of scope, @petermarks-gsa!

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Thanks, just took and look and think this draft fleshed out should cover it.

**Comment by MelissaBraxton** [comment]
Wiki updates are [here](https://github.com/GSA-TTS/FAC/wiki/Design-documentation)
