### ISSUE TITLE
UX flow diagram for to-be FAC

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#232]
This is a sub part of #231 

**Background**
We need a UX flow diagram that depicts the high level IA, and the flow of  interactions and screens that enable people to accomplish their tasks. This work will bridge and build on what we already have documented in our [task flow model ](https://app.mural.co/t/gsa6/m/gsa6/1652460935988/b240919b310e05f897c6452815fe5a07cad3eaea?sender=melissabraxton2796)and [mockups](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=1801%3A9179).

**Acceptance Criteria (We'll know we're done when...)**
- [ ] UX flow diagram captures current knowledge of screens and interactions we are building
- [ ] It's understandable to product folks
- [ ] It's understandable to engineers

**Tasks**
- [x] Create UX flow diagram
- [ ] @petermarks-gsa or @jhansen-flexion reviews
- [ ] @tadhg-ohiggins and/or @heymatthenry reviews 
- [ ] Reine based on feedback
- [ ] Add link to completed diagram from the wiki

**Comment by MelissaBraxton** [comment]
Draft is [here.](https://app.mural.co/invitation/mural/gsa6/1652991266114?sender=melissabraxton2796&key=7c1e42e0-c5aa-49aa-b1fe-9c243971d54f)

**Comment by MelissaBraxton** [comment]
The diagram is not ready for prime time, BUT! Yes, we need to let people manually enter their name and dates if they choose to proceed to enter data with a UEI that is not found in SAM.gov. However, they will not be able to submit their audit report until they have entered a valid UEI.

**Comment by MelissaBraxton** [comment]
@jhansen-flexion or @petermarks-gsa ready for your review! Whichever of you gets to it first, feel free to assign yourself! :)

**Comment by petermarks-gsa** [comment]
@MelissaBraxton I'm finding this diagram really helpful to compare to the designs to flesh out a story. I just did that for the SEFA page and left a clarifying question in mural. I think realistically we'll keep coming back to this as we define stories, so I don't think makes sense for me to review the entire diagram thoroughly right this moment. I'm going to suggest calling this done!

**Comment by MelissaBraxton** [comment]
Sounds good to me!
