### ISSUE TITLE
Epic: Workbook validations

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2333]
There are multiple validation questions lurking around the Federal Awards workbook.

We have some examples in the GDrive that we can use to figure out what needs to be updated.

This ticket is done when we are confident we have tracked down the workbook errors and validations.

```[tasklist]
### Workbooks
- [ ] https://github.com/GSA-TTS/FAC/issues/2334
- [ ] https://github.com/GSA-TTS/FAC/issues/2335
- [ ] https://github.com/GSA-TTS/FAC/issues/2336
- [ ] https://github.com/GSA-TTS/FAC/issues/2282
- [ ] https://github.com/GSA-TTS/FAC/issues/2331
- [ ] https://github.com/GSA-TTS/FAC/issues/2338
- [ ] https://github.com/GSA-TTS/FAC/issues/2339
- [ ] https://github.com/GSA-TTS/FAC/issues/2036
```

**Comment by jadudm** [comment]
These are handled by #2441.
