### ISSUE TITLE
New Relic spike

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2365]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."
[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** chart the course for systems monitoring 
**as a** product owner
**I want** to have a NR skeleton/dev plan

This lays out a spike for NR capabilities exploration and planning.

```[tasklist]
### Tasks
- [x] Shift keys to provide AS (full) access to NR
- [ ] Identify what we are capturing as-is
- [ ] Itemize what we *want* to be capturing
- [ ] Delineate security vs. application metrics
- [ ] Logging for critical actions (e.g. enabling users, admin access via Django)
- [ ] Lay groundwork for evaluating CF log shipper (e.g. does it ship, what does it ship, etc.)
- [ ] How/can we track API and service monitoring?
- [ ] Monitoring DB outside of Django?
- [ ] Runtimes for testing SQL, CRUD operations, etc., and tracking their
- [ ] Report out/discuss current capabilities, desired state
- [ ] Draft epic and tickets for NR enhancements based on exploration
```

### Item: Identify what we are capturing as-is
**In order to** know everything that new relic captures
**as a** audit submission tester
**I want** to have a dashboard of all interactions a user will do on the application

```[tasklist]
### Build a Dashboard
- [x] Walk through the application and monitor the logs at any new stage
- [ ] Turn the log message into a usable piece of information (i.e request.uri, request.method, WebTransactionName, etc)
- [ ] Build a query targeting Transactions based off the Log message
- [ ] Add the query to the testing dashboard
- [ ] Repeat until entire audit submission process is cataloged
```

### Item: Itemize what we *want* to be capturing
**In order to** determine what we want to capture
**as a** audit submission tester
**I want** look through the dashboard for items that need to be added

```[tasklist]
### Catalog events to capture
- [ ] Determine if there are items in the submission process that are not present in the logs
- [ ] Build queries around submission process events that were missing
```

### Item: Delineate security vs. application metrics
**In order to** differentiate security events from application events
**as a** tester
**I want** have a clear log for security related events

```[tasklist]
### Security Events
- [ ] Sketch what would constitute a security event
- [ ] Determine if we can have more information about failed password events
- [ ] Determine where in our application we should have security events
- [ ] Determine if CF logs show security events
- [ ] Determine if our application is capable of logging security events
- [ ] Build queries around security events
```

### Item: Logging for critical actions (e.g. enabling users, admin access via Django)
**In order to** capture critical events
**as a** tester
**I want** capture all events that are not generic application events

```[tasklist]
### Critical Actions
- [ ] Walkthrough the admin interface with a developer
- [ ] Determine if admin panel events are sent to application logs
- [ ] Determine what information is sent as part of admin events
- [ ] Ensure admin level events are generic without extracting too much sensitive information
- [ ] Catalog logins to admin panel
- [ ] Catalog all admin panel operations
- [ ] Build queries around specific admin interactions
- [ ] Determine which events should become alerts
```

### Item: Runtimes for testing SQL, CRUD operations, etc., and tracking their operations
**In order to** determine run times for sql operations
**as a** New Relic Operator
**I want** capture all SQL operations with their runtimes

```[tasklist]
### SQL
- [ ] Reference existing "long running database transactions" query and expand it
- [ ] Itemize existing long running operations
- [ ] Build a dashboard around all operations that occur (Timeseries)
- [ ] Ensure the query shows the operation along with the performance
```

**Comment by danswick** [comment]
Capturing from conversation with @asteel-gsa, @jadudm, and @asteel-gsa. I recommend we break this down into a few broad goals and identify achievable goals for each.

* Compliance requirements, especially around alerts, that we haven't started to address yet.
  * A good first step might be to build out basic alerting for a small subset of conditions, including documentation
* Performance monitoring:
  * What kind of performance characteristics matter?
  * How could we capture those characteristics/metrics? 
* Troubleshooting/investigation:
  * Is the application configured to send usable stacktraces?
  * Do we have appropriate dashboards/tools for developers to view and query? These need to be available to lower-level license holders due to the limited number of NR seats.

**Comment by eazapata23** [comment]
In regards to our alerts & incidents, I added an Alert Quality Management(AQM) dashboard: 

![Image](https://github.com/GSA-TTS/FAC/assets/99770283/28ff0eac-99a0-4b61-b9bc-65f9cf857309)



![Image](https://github.com/GSA-TTS/FAC/assets/99770283/756e8732-4d22-46bb-9e05-abdb5a4c1473)

Benefits:

- Decreased alert volume - some alerts aren't relevant 
- Reduced mean time to resolution (MTTR) 
- Identify alerts that are valuable
-Help identify issues earlier
-Improve the quality of our alerts

The goal being that by having this it will help reduce the noise of less valuable alerts and focus on identifying when more valuable business impactful incidents occur.

**Comment by jadudm** [comment]
Calling this spike done. We have more work to do, but we should ticket it out more incrementally. Nice work!
