### ISSUE TITLE
Design "My audit submissions" page

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#238]
**Background**

Design screens and empty state for creating a new audit or editing one that already exists
It covers the following stories:

1. [As an auditor or auditee I need to choose existing or create new audit.](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1647625748037&sender=austinhernandez5199)

**We'll know we're done when...**
- [x] Create an audit
- [x] Select an existing audit
  
**Tasks**
- [x] Design designs all the things

**Definition of Done**
- [x] Design reviewed!

**Comment by austinhernandez** [comment]
@sreuber will talk to legal dept!

**Comment by austinhernandez** [comment]
@petermarks-gsa can you create an engineering task for this?! it's done being designed

**Comment by petermarks-gsa** [comment]
@austinhernandez Tracking implementation in https://github.com/GSA-TTS/FAC/issues/244
