### ISSUE TITLE
As an auditor or auditee, I need to be able to create a new audit submission even if I don't have a valid UEI.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#241]
**Background**
On the auditee info page (preview it on Federalist [here](https://federalist-9a617ff8-042d-4076-9581-bb999f9c6639.app.cloud.gov/preview/gsa-tts/fac-frontend/mh-validate-fy-date-127/audit/new/step-2/)), We need to iterate on some of the error handling.  

This issue covers the business process and front end design aspects of this work. 

Users should be given an option to proceed with a UEI not found in SAM.gov and/or if a UEI is not found because the SAM.gov API is unavailable. 

If they do decide to proceed, we need to let them manually enter the name and FY period dates and also communicate that they’ll need to enter a valid UEI before their submission can be certified. 

Current thinking is that the following types of errors will appear in a modal (rather than as inline validation errors) and give users the option of proceeding or otherwise backing out/canceling:

 - Invalid UEI
 - SAM.gov API unavailable
 - For records validated in SAM.gov, we need to decide how we want to handle folks entering an FY end date that doesn't match what's in SAM.gov

It covers the following stories:

1. As an auditor or auditee, I needto be able to create a new audit submission even if I don't have a valid UEI.

**We'll know we're done when...**
- [x] When we've designed a way for users to proceed to creating a new audit submission if their UEI is not valid
- [ ] ~When we've designed a way for users to proceed to creating a new audit submission if the FY end date they enter does not match what's in SAM.gov~

**Tasks**
- [x] Sketch out business logic for how users will proceed with invalid UEI and FY end dates.
- [x] Mock the experience of proceeding through from the auditee info page to create a new submission even if UEI ~and/or FY end dates~ cannot validated. 
- [x] ~[FRONT END] implement mocks~
- [x] Peer review at a design sync or co-working sesh
- [ ] Create new front end and back end engineering tickets as needed. 

**Definition of Done**

**Acceptance Criteria (We'll know we're done when...)**
- [x] Screen is ready to be used in a Figma usability testing
- [ ]  All text has a contrast ratio of 4.5:1 with the background
- [ ]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment]
@petermarks-gsa or @heymatthenry  - New issue based on today's design sync. Thoughts on prioritizing and further refining this welcome!

**Comment by MelissaBraxton** [comment]
Starting point for error messaging to show in the modal for 2 types of errors. Note that error messages for these types of errors are currently handled **on the server side.**

**If API is working, but UEI isn’t recognized:**
We don’t recognize this UEI. You can continue for now, but you’ll need to come back to this. [Find out how to get a UEI](https://github.com/GSA-TTS/FAC/issues/126#).

**If API isn’t working:**
We can’t connect to SAM.gov to confirm your UEI. We're sorry for the delay. You can continue, but we'll need to confirm your UEI before your audit can be certified.

**Comment by MelissaBraxton** [comment]
Edited to reflect that we won't really be using FY end date validation from SAM.gov right now.

**Comment by MelissaBraxton** [comment]
Screen shot of draft revised flow:
<img width="720" alt="Screen Shot 2022-06-09 at 4 13 42 PM" src="https://user-images.githubusercontent.com/20651166/172960332-f57435b8-bcc8-47fa-a331-60c7c37130c7.png">

1st iteration mocks are [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2552%3A11276)

Would love feedback from @austinhernandez and @heymatthenry.

More initial thoughts: 

   - Audit remains "in progress"  until a valid UEI has been added. (until there's a valid UEI, the submission isn't "complete" and it can't be certified.)
 - We need to figure out where in the workflow we prompt folks to add a valid UEI to an in progress submission. Some thoughts: 
     - SF-SAC page: there's a UEI field that will be auto-populated with a validated UEI. **If no valid UEI**, Should folks be able to enter data in in this field? It could get added to the SF-SAC data object, but then isn't validated against SAM.gov until the ["finalize/"](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2464%3A10748)check for errors step? 

 - Possible future features: alerts that let folks know an in-progress submission needs a valid UEI. Two places that come to mind:
   - **"my submissions"page:** via a tag on submissions listed 
   - **"Audit start page"** banner alert at the top of the page > a link to a UEI search page or modal?

**Comment by MelissaBraxton** [comment]
Updated acceptance criteria.

**Comment by austinhernandez** [comment]
Looks good to me! I would suggest making sure a user knows it's an "error" throughout. 

I added a mockup of an error field and an idea of where to edit the UEI again on the audit start page:
![Audit Start Page - invalid UEI](https://user-images.githubusercontent.com/23194720/173442863-8e339a7a-5c56-4c1a-84e5-4be5e705c4d3.png)

The questions are just around the sample data:
- I changed the mockup to reflect the Unique Entity ID: J92ENHDF5733 and Auditee name: D.C. CENTRAL KITCHEN, INC. (THE), but are we changing the name to: George Strudgeon?
- The navigation different
- The invalid and valid UEIs are the same on your mocks, so I changed my invalid one to AAABBBCCCDDD

**Comment by MelissaBraxton** [comment]
@petermarks-gsa - One remaining task is to create new front and back end tickets for this. I'm wondering if the team can cover that at next week's backlog grooming? It's something I'd thought we could cover at the weekly design/eng sync, but it looks like most folks can't make it tomorrow.

**Comment by petermarks-gsa** [comment]
@MelissaBraxton I'd like to take a stab at creating tickets and then review at design / engineering sync. Can you or @austinhernandez please link me the designs in figma + any implementation notes?

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Great, I created an implementation task: https://github.com/GSA-TTS/FAC/issues/278

Closing this as done.
