### ISSUE TITLE
Epic: Add missing fields to API responses

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2414]
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2468
- [ ] https://github.com/GSA-TTS/FAC/issues/2467
- [ ] https://github.com/GSA-TTS/FAC/issues/2466
- [ ] https://github.com/GSA-TTS/FAC/issues/2492
```
Data dictionary updated for v1.0.2: https://docs.google.com/spreadsheets/d/1sLU7sWWXOj-1wZ4rKVoSWQipdYABptgP/edit#gid=727005974

**Comment by phildominguez-gsa** [comment]
Research doc: https://docs.google.com/document/d/1JF113c52Ywx0BK4vZQN9xKmW22hpuqJQ4PqdCunBLac/edit
