### ISSUE TITLE
Instructions should be consistent with 2022/2023 UG

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2454]
The instructions on fac.gov are plain language. This is good.

We need to revisit the 2022 UG (and the 2023 UG we submitted) to make sure that our instructions online are consistent with UG that we published.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/3640
- [ ] https://github.com/GSA-TTS/FAC/issues/3641
- [ ] https://github.com/GSA-TTS/FAC/issues/3642
- [ ] https://github.com/GSA-TTS/FAC/issues/3643
- [ ] https://github.com/GSA-TTS/FAC/issues/3644
- [ ] https://github.com/GSA-TTS/FAC/issues/3645
- [ ] https://github.com/GSA-TTS/FAC/issues/3646
- [ ] https://github.com/GSA-TTS/FAC/issues/3647
- [ ] https://github.com/GSA-TTS/FAC/issues/3648
- [ ] https://github.com/GSA-TTS/FAC/issues/3649
- [ ] https://github.com/GSA-TTS/FAC/issues/3650
```

Not everything is simple; in some cases, we may need more words to explain complex things. The instructions need to be complete, even if that means they become more complex. The side-effect of incomplete or oversimplified instructions are incomplete or incorrect submissions, and that leads to user frustration.

**Comment by jadudm** [comment]
@lauraherring , we'll track the work of the day here. When we complete the UG additions, we'll call this one closed.

**Comment by jadudm** [comment]
Leaving this in backlog, as we should include references to UG, as it is the authoritative source for all instructions. It will be a bit of a slog, but we can find a way to do it that leverages our publishing framework.

**Comment by lauraherring** [comment]
@Leighdiddy and @danswick: I think this one can be closed out in favor of the individual issues I opened for each section of the app and set of workbook instructions. It makes more sense to me to break this work down so it can be picked up by multiple people as they have time/can be chipped away at instead of one massive ticket for everything.

**Comment by danswick** [comment]
A few questions before we start divvying up the work:
1. This ticket's original description is about aligning the _instructions_ with uniform guidance, but the broken out tickets are about adding links. Don't we want to do both of those things?
2. If each form/workbook is its own discrete task, does that mean we'll get to a state where some forms/workbooks have UG citations and others do not? Does that matter?
3. Have we landed on some kind of template for citing and displaying language from the UG? Would this be different for the app vs the static site?
4. Do we need to make any considerations for updating when new guidance comes out? Like a reusable component for citing policy, variables for linking to the correct version of guidance, etc?
5. If someone wanted to pick up one of the breakout tickets, how would they start?

I'm wondering if we might want to front-load both the design/templating work and the pulling-language-from-UG work _before_ divvying up by form. Once we have both a template and set of language/links to work from, it should (theoretically) be more straightforward to split up the work of dropping everything into the app and static site.

**Comment by lauraherring** [comment]
> A few questions before we start divvying up the work:
> 
>     1. This ticket's original description is about aligning the _instructions_ with uniform guidance, but the broken out tickets are about adding links. Don't we want to do both of those things?

A: I think the focus is on adding the links/citations. The original ticket is pretty old, I don't think the misalignment with the UG as far as the wording of the instructions is a concern anymore, we'd know by now if we were telling people to do the wrong thing.
> 
>     2. If each form/workbook is its own discrete task, does that mean we'll get to a state where some forms/workbooks have UG citations and others do not? Does that matter?

A: Yes, if we do it this way, some might be updated before others but I think that's OK. We'll probably want to group the app updates together if we can, just for the sake of app PRs taking so much longer to publish, but if they're a little out of sync, I think that's fine.
> 
>     3. Have we landed on some kind of template for citing and displaying language from the UG? Would this be different for the app vs the static site?

A: We can keep it simple and the same for both. "See [citation] for more information."
> 
>     4. Do we need to make any considerations for updating when new guidance comes out? Like a reusable component for citing policy, variables for linking to the correct version of guidance, etc?

A: When new guidance comes out, we'll need to review the entire submission process anyway, to make sure we're in accordance with it. We can update necessary citations at that time, though I think the links will stay the same.
> 
>     5. If someone wanted to pick up one of the breakout tickets, how would they start?

A: The best starting point is to go through the 2022 submission instructions from the Census and note the UG citations, confirm the citation is still the same number, and then copy the link from the UG site and insert it into our site using the language on #3.
> 
> 
> I'm wondering if we might want to front-load both the design/templating work and the pulling-language-from-UG work _before_ divvying up by form. Once we have both a template and set of language/links to work from, it should (theoretically) be more straightforward to split up the work of dropping everything into the app and static site.

**Comment by danswick** [comment]
We can track using the sub-tasks from here on out.
