### ISSUE TITLE
Create a service blueprint depicting customer support touchpoints and needs

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#247]
**Background**
GSA will be providing customer support for the FAC. We need to better understand current customer support processes and design the future state of customer support services that GSA will provide. 

**Acceptance Criteria (We'll know we're done when...)**
- [x] We have a service blueprint that depicts the current state of customer support
- [x] The service blueprint is stored in a place the whole team can access

**Tasks**
- [x] Interview Census CX staff
- [x] Review Census CX customer support scripts
- [x] Create a service blueprint that maps out the  CX service.
- [ ] Review the service blueprint with the team at a co-working meeting
- [ ] Create a follow on Github issue to cover the work of further designing the future state of CX support

**Comment by MelissaBraxton** [comment]
Drafting [here.](https://app.mural.co/t/gsa6/m/gsa6/1654206591049/9273bb1523718b513273882f38c0b50bc3d54c24?sender=melissabraxton2796)

**Comment by MelissaBraxton** [comment]
@petermarks-gsa  - It looks like we wont have a chance to review this at co-working this week. Thoughts on keeping that as acceptance criteria? We could leave it in "in review" until the team can convene, or you could review and then let me know what you think is the next best time/place to review with other folks and whether we want to wait to call this "done" until we've done that broader review?

**Comment by petermarks-gsa** [comment]
@MelissaBraxton I took a quick look at this. I'm not sure I understand how the "support process" swimlane on the mural board relates to "customer support touchpoints". Maybe leave this in review and we can discuss?

**Comment by petermarks-gsa** [comment]
I reviewed this with @MelissaBraxton and understand it better. Next steps:

* https://github.com/GSA-TTS/FAC/issues/275
*https://github.com/GSA-TTS/FAC/issues/276
