### ISSUE TITLE
Test information architecture

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#248]
Breakout issue of #147 to cover testing the draft IA created in #147.  

**Background**

**Acceptance Criteria (We'll know we're done when...)**
- [x] We have documented the results of testing the IA with users
- [ ] ~We have documented any refinements to the IA needed~

**Tasks**
- [x] Create a tree test in Optimal workshop to test the draft IA
- [x] Get PRA clearance: Fill out this PRA clearance [template](https://docs.google.com/document/d/11XJv6WxgzfRj_wJ2zvcWO-y3sJ9ldVrQ/edit?usp=drive_web&ouid=118175247657582651514&rtpof=true), and send it to OMB PRA contact
- [x] Draft invitation email
- [x] Pull together list of emails to send the test to
- [x] Send the survey to at least 150 users (aiming for a min. of 30 responses w/ an estimated 20% response rate)
- [ ] ~Analyze results~
- [ ] ~Write up 1 pg. summary~ 
- [ ] ~Create new issue to refine IA as needed~

**Comment by MelissaBraxton** [comment]
@sreuber  - I think we will want PRA clearance for this. Updated tasks to reflect filling out approval form and sending it to the OMB PRA contact. I'm thinking we could either split out the PRA application task for this sprint or just punt on this entirely until sprint 7.

**Comment by sreuber** [comment]
@MelissaBraxton I think punting to 7 is totally fine, we're already halfway through and I haven't really even begun to think about it further. If I have some time early next week I might get started on it.

**Comment by petermarks-gsa** [comment]
Just chatted with @MelissaBraxton about this. Sounds like we might be able to get a PRA clearance in 2-3 days? We talked about trying to get this done next sprint.

**Comment by MelissaBraxton** [comment]
Drafting PRA clearance template [here.](https://docs.google.com/document/d/1ELud_MR_TbtgXrDGLTTgitqHNJ5WuqM6/edit)

**Comment by MelissaBraxton** [comment]
Link to preview the tree test is [here](https://10x.optimalworkshop.com/treejack/3z680324). 
Sent PRA approval request to OMB on 6/24, awaiting approval.

**Comment by MelissaBraxton** [comment]
Sent a revised PRA clearance request base on OMB feedback on 6/29. Blocked again while we await their approval on the revised draft. Revised version is [here.](https://docs.google.com/document/d/1ELud_MR_TbtgXrDGLTTgitqHNJ5WuqM6/edit#)

**Comment by MelissaBraxton** [comment]
We got PRA approval!  Now all we need to do is email the link to participants when we have the list together.

**Comment by MelissaBraxton** [comment]
@sreuber  - Anything else here we can check off?

**Comment by MelissaBraxton** [comment]
Update: We've split off analysis/recommending refinements as a separate issue in #357. With that, this issue is done.

**Comment by MelissaBraxton** [comment]
Results of testing are available in Optimal Workshop.
