### ISSUE TITLE
Activate Wrap Text in Workbook

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2499]
### Tasks

```[tasklist]
- [ ] Activate Wrap Text in all workbooks
- [ ] Increase column height in all workbooks
- [ ] Update workbook versions
```
