### ISSUE TITLE
[HD]: Compliance Requirements Instructions are not on site

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#2502]
```[tasklist]
### Tasks
- [ ] See Lauras comment :)
``` 

### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/420

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

User cannot locate the Type Compliance Requirements for the Findings workbook.  They should be listed in our instructions, but after 15 minutes of searching I couldn't locate them. 

In previous iterations of the FAC, instructions for each workbook were located within the workbook - not in the app or static site. I think it may be something we want to go back to.  From a CX perspective it makes sense to include the instructions within the tool.

**Comment by jadudm** [comment]
@lauraherring , relevant to today's work.

**Comment by jadudm** [comment]
I think we'd need to create a ticket describing all the updates we'd want to make to workbooks. If you have a list of notes (or, it might just be "add instructions into every workbook") we could use that as a starting point.

However, we'd have to decide when/where that was a priority to add (over-and-above instructions on the website).

**Comment by Leighdiddy** [comment]
This could end up in workbooks and possible submission guide -MJ

**Comment by lauraherring** [comment]
Need to add to the [static site instructions for workbook 3](https://www.fac.gov/resources/workbooks/federal-awards-audit-findings/), add alpha definitions to column C

**Comment by lauraherring** [comment]
Published these changes on 1/3/24

**Comment by jadudm** [comment]
See above. Closing.
