### ISSUE TITLE
[INTAKE]: Add a Validation Check for the sum calculations in Federal Awards Workbook.

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2509]
As part of intake data validation we must validate the sum calculations in Federal Awards Workbook.

### Tasks

```[tasklist]
- [x] Validate Federal Program Total
- [x] Validate Cluster Total
- [x] Validate Total Amount Expended
```
