### ISSUE TITLE
Epic: Validation improvements 1

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2511]
From walking the instructions and help desk tickets, we've identified additional improvements to the validations. These are easier/possible now that we have a new intake validation framework in front of the schemas.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2509
- [ ] https://github.com/GSA-TTS/FAC/issues/2514
- [ ] https://github.com/GSA-TTS/FAC/issues/2506
- [ ] https://github.com/GSA-TTS/FAC/issues/2504
- [ ] https://github.com/GSA-TTS/FAC/issues/2503
- [ ] https://github.com/GSA-TTS/FAC/issues/2501
- [ ] https://github.com/GSA-TTS/FAC/issues/2505
- [ ] https://github.com/GSA-TTS/FAC/issues/2507
- [ ] https://github.com/GSA-TTS/FAC/issues/2523
- [ ] https://github.com/GSA-TTS/FAC/pull/2518
- [ ] https://github.com/GSA-TTS/FAC/issues/2553
- [ ] https://github.com/GSA-TTS/FAC/issues/2552
- [ ] https://github.com/GSA-TTS/FAC/issues/2562
- [ ] https://github.com/GSA-TTS/FAC/issues/2460
- [ ] https://github.com/GSA-TTS/FAC/issues/2625
- [ ] https://github.com/GSA-TTS/FAC/issues/2567
- [ ] https://github.com/GSA-TTS/FAC/issues/2717
- [ ] https://github.com/GSA-TTS/FAC/issues/2819
- [ ] https://github.com/GSA-TTS/FAC/issues/2877
- [ ] https://github.com/GSA-TTS/FAC/issues/3077
- [ ] https://github.com/GSA-TTS/FAC/issues/3095
- [ ] https://github.com/GSA-TTS/FAC/issues/2792
```
