### ISSUE TITLE
Recruit auditors to test SF-SAC form mocks

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#253]
**Background**

**Acceptance Criteria (We'll know we're done when...)**
- [x] We have interviews with 7-9 auditors on the books
- [x] Auditors represent a range of experience including work with small entities and non-profits

**Tasks**
- [x] Set up appointment slots following [these instructions](https://docs.google.com/document/d/16UpgQbFOh5F9RLkTGHEsgHyTBC_O65y6nZSiFOvxHjg/edit#)
- [ ] ~Articulate screening criteria~ 
- [X] Draft email recruitment text
- [x] Email potential participants
- [ ] ~Draft screening call/email script~
- [ ] ~Screen and~ schedule interested folks

**Comment by MelissaBraxton** [comment]
Removed tasks re: screening, as we have a pre-vetted list from our partners at AICPA.
