### ISSUE TITLE
Mock modals and alt states for SF-SAC form pages that involve worksheets

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#255]
**Background**
We've mocked SF-SAC form pages involving the use of Excel worksheets in their empty state, but we have yet to design error states and modals that users will encounter on these pages. A lot of these will be the same, since they all follow the same pattern. We'll want to mock these and include them in testing with auditors in sprint 6. 

Note, this does not cover the work of designing save/discard data prompt that will apply to all SF-SAC form pages. That's covered under #220. 

**Acceptance Criteria (We'll know we're done when...)**
We have mocked the error states and modals that users may encounter on each of the SF-SAC data entry form sections that involve uploading worksheete. We need to design:
 - [ ]  A way for users to either drag/drop a file to upload or "browse" for a file on their machine (on clicking "upload worksheet" button)
 - [ ] A way to display worksheet validation errors
 - [ ] A way to  display file name in place of "upload worksheet" button when it validates successfully.
 - [ ] A way to display the option to delete an uploaded file with a warning message

**Tasks**
- [ ] Review UX flow diagram to identify modals/alt states that need to be designed
Mock modals and alt states for the following form sections: 
 - [ ] Federal awards (SEFA)
 - [ ] Award findings
 - [ ] Findings text
 - [ ] CAP text
 - [ ] Additional EINs
 - [ ] Additional UEIs
 - [ ] Secondary auditors
 - [ ] Invite peer review

**Definition of done**
- [ ] Meets acceptance criteria
- [ ] PO approved

**Comment by austinhernandez** [comment]
@sreuber / @MelissaBraxton keeping with the layout of the [Audit Report Start page](https://github.com/GSA-TTS/FAC/issues/264), is there any reason this wont work?

![DSF - Federal Awards](https://user-images.githubusercontent.com/23194720/173647870-07729df3-7ad7-498c-a80a-0e27be333f7b.png)

On Figma
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3112%3A17184

**Comment by austinhernandez** [comment]
- For the prototype only the Federal awards page has the modal states, but it's going to be the same throughout
- It will use the USWDS [file input component](https://designsystem.digital.gov/components/file-input/ )
- It will restrict uploadable file types to XLS

Pages on figma:
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3159%3A20568

Screens
No files uploaded
![DSF - Federal Awards](https://user-images.githubusercontent.com/23194720/173709269-b356a596-9bf0-4a95-8465-a100c34be108.png)

1 file uploaded
![DSF - Federal Awards uploaded](https://user-images.githubusercontent.com/23194720/173709228-cc30fa2f-b61c-4b4d-96fd-d5c92cdd9061.png)

overlay
![DSF - Federal Awards - file download](https://user-images.githubusercontent.com/23194720/173709236-6258728b-c0e5-4eb2-a7f2-c883e4dfec4d.png)

**Comment by MelissaBraxton** [comment]
Sounds good! Thank you @austinhernandez!

**Comment by MelissaBraxton** [comment]
Looking at this again, I see it's blocked by us not having clarity on exactly what file types we are going to accept. I don't know the answer. Currently, only .xlsx. is allowed. My thoughts - for the MVP, .xlsx is sufficient. I don't think we need to enable .csv. Down the road .xlsm would probably be desirable, but that'd be an enhancement.  @tadhg-ohiggins, do you have an opinion?

**Comment by geekygirlsarah** [comment]
With the [xlsx](https://www.np mjs.com/package/xlsx) library that was discussed before, it can open xls, xlsx, ods (OpenOffice), csv, and a bunch of other formats. I don't think there'd be too much in terms of code changes to allow other formats since the library just reads them all.
