### ISSUE TITLE
Plan and conduct sprint 6 research with auditors

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#256]
**Background**
We need to put our first iteration mocks of the SF-SAC form in front of auditors. 

**Acceptance Criteria (We'll know we're done when...)**
- [x] We have conducted research with auditors

**Tasks**
- [x]  Articulate research qs and design hypotheses
- [x]  Write research plan
- [x] Prepare artifacts for testing (wire up clickable prototype)
- [x] Create schedule of who will facilitate/note take during each interview
- [x]  (recruitment is covered in #253)
- [x]  Conduct test sessions

**Comment by MelissaBraxton** [comment]
Draft shaping up [here](https://docs.google.com/document/d/1xdaiEGTyslc0vOQ2eBy-51j3KQq_ewtouevrpJtfELQ/edit#).
