### ISSUE TITLE
Allow unlocking of READY_FOR_CERTIFICATION submissions

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2574]
Being able to move submissions back to an editable state after someone marks a submission as ready for certification seems to be the biggest current user request.

### Tasks

```[tasklist]
- [x] A basic way to do this.
- [x] Tests for the basic way to do this.
- [x] An issue covering addition of a way to do this with reasonable copy and design.
```

**Comment by tadhg-ohiggins** [comment]
First two tasks addressed in https://github.com/GSA-TTS/FAC/pull/2572.

**Comment by jadudm** [comment]
Subsequent merge with fixes addressed third.
