### ISSUE TITLE
Onboarding checklist for @timoballard

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#258]
### Welcome to the team @timoballard!

Here's a few pointers to get you started as well as a checklist to make sure you've got access to :all-the-things:!

**For you**
- [ ] [Join](https://github.com/GSA/GitHub-Administration#joining-the-gsa-enterprise-organization) GSA’s Enterprise Github org
- [ ] Review the [project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/) in drive
- [ ] Join Slack channels in the project README

{ONBOARDING BUDDY'S GH USERNAME} will be your onboarding buddy and will tackle the list below!

**For your onboarding buddy**
- [ ] Add to the FAC team folder in drive
- [ ] Add to [FAC@GSA.gov](https://groups.google.com/a/gsa.gov/g/fac) google group
- [ ] <Engineering> Added to `gsa-10x-prototyping` Organization in cloud.gov
- [ ] Add to the [FAC team](https://github.com/orgs/GSA-TTS/teams/fac-team) in github
- [ ] Add to standing meeting invites

**Comment by geekygirlsarah** [comment]
I think @jadudm said he'd add you to the FAC group.
