### ISSUE TITLE
Design the Login.gov / you are now leaving FAC page screens

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#259]
Breakout issue of #135 

**Background**

- [x] As a user, I need to know that I need to login to the system to access secure information
- [x] As a user, I need to consent to the redirect and understand the implications of falsifying information on a government site
- [x] As a system, authentication is done through login.gov which requires a redirect to a login.gov sign-in/sign-up page.

**Acceptance Criteria (We'll know we're done when...)**
- [x] There is a mockup of "you are now leaving FAC to go to login.gov" modal
- [x] There is an example of login.gov screen

**Tasks**
- [x] Design screens
- [x] Add recommendations for implementation

**Comment by austinhernandez** [comment]
We'll be using a similar flow to the [Trusted Traveler Programs page](https://ttp.dhs.gov/), except without step 2 confirming Global Entry vs TSA Pre✅ 

Example of user flow on [DHS Trusted Traveler Programs](https://ttp.dhs.gov/):
1. click on "Get Started" under Global Entry column
<img width="1186" alt="Screen Shot 2022-06-07 at 5 58 13 PM" src="https://user-images.githubusercontent.com/23194720/172491610-5d1d0c10-819d-4af2-a0d1-7edeb582cb9d.png">

2.  modal confirming selection 
<img width="1183" alt="Screen Shot 2022-06-07 at 5 58 19 PM" src="https://user-images.githubusercontent.com/23194720/172491842-20d3f1b9-e079-4092-a2ce-a5f1ef3893a6.png">

3. Disclaimer and redirect notice
<img width="1186" alt="Screen Shot 2022-06-07 at 5 58 29 PM" src="https://user-images.githubusercontent.com/23194720/172491891-ecffa61a-b9f8-48fc-af4b-74bc6a79168f.png">

4. Login.gov page with CBP logo and ability to "Sign in with your government employee ID"
<img width="863" alt="Screen Shot 2022-06-07 at 6 00 10 PM" src="https://user-images.githubusercontent.com/23194720/172492110-5313e8fb-9201-4a05-8cfd-eb722161cf89.png">

**Comment by austinhernandez** [comment]
1. Click on "submit an audit" in the header
<img width="933" alt="Screen Shot 2022-06-07 at 6 23 34 PM" src="https://user-images.githubusercontent.com/23194720/172493272-529fcb14-777c-4393-b90e-c93a25d12d1e.png">

2. Modal with redirect and usage warning/information
<img width="621" alt="Screen Shot 2022-06-07 at 6 19 15 PM" src="https://user-images.githubusercontent.com/23194720/172492905-44dcb662-cf6e-4584-828d-a8d29fb95518.png">

3. Login screen 🎉 
![Login gov](https://user-images.githubusercontent.com/23194720/172492814-47ed84e3-a4f6-49ff-b5c5-b42a7ddaadaf.png)

Outstanding questions:
- What will the leaving FAC text be / what needs to be there?
- How does someone sign in with their government employee ID?
- How much design control do we have with this page? (I would like to make the government employee ID more prominent)

**Comment by petermarks-gsa** [comment]
@austinhernandez Following up on outstanding questions:

> How does someone sign in with their government employee ID?

Got a live demo of this: 
    - Insert your id card via usb reader
    - Click PIV link
    - Chrome auth menus
    - Then they’re in! 

> How much design control do we have with this page? (I would like to make the government employee ID more prominent)

Sounds like we change the logo and the top and "help text" (circled below). It sounds like we can change the destination of the "forgot password" link to go to our help text, but it doesn't sound like other links like the government id one are editable. 

![Screen Shot 2022-06-09 at 3 26 34 PM](https://user-images.githubusercontent.com/100610443/172930394-56c7a47f-b975-47d9-b8f8-599d85e0167b.png)

**Comment by austinhernandez** [comment]
Thanks Peter! My responses

1. The initial mocks had a "Sign in with login.gov" button that everyone missed, so we are trying another CTA. 
2. The leaving FAC text is the same "Modal with redirect and usage warning/information" text. That text was lifted directly from the current FAC, I just don't know all of it needs to be there. It's long.
3. From user research and since there's a user group of Federal employees, I think it's a safe assumption we should support gov ID sign-in and test it. I don't think theres much we can do if there's no ability to change how it looks, but I believe it should be there. Here's a  direct quote from a user in the last round of usability testing: _"Is it gonna be password protected or need login.gov? ... It feels like a headache sometimes. We have so many systems we work in. some use login.gov. If i can just use my PIV, thats easiest."_
5. Thanks for giving feedback from the demo about how to sign in with a gov ID. I think the design is good to go then.

**Comment by austinhernandez** [comment]
On Figma*:
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3136%3A18590
note, the old homepage is in the background of the modal but disregard

**Comment by petermarks-gsa** [comment]
@austinhernandez Looks good, tracking implementation in these engineering issues: 

- https://github.com/GSA-TTS/FAC/issues/267
- https://github.com/GSA-TTS/FAC/issues/268

Closing as done.
