### ISSUE TITLE
Design audit report start page CTAs

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#260]
Breakout issue of #212 and #264 

**Background**
- In addition to designing #264, this ticket will contain information for the additional states for all the pages from the [in the Primary CTAs section (overview here on Mural)](https://app.mural.co/invitation/mural/gsa6/1654109929324?sender=austinhernandez5199&key=93f016dc-f3d6-41c9-a2b9-0b8f72b0926a)

Original screen
![Screen Shot 2022-02-02 at 10 50 2](https://user-images.githubusercontent.com/23194720/173101042-b8230626-8c29-4bf4-bed2-0bab2de7d39f.png)

**Acceptance Criteria (We'll know we're done when...)**
- [x] Dev and Design teams understand functionality
- [X] There is a mockup

**Tasks**
- [x] Set up meeting between Dev + Design 
- [x] Walkthru current FAC functionality to decide next steps on design and implementation
- [x] Break this ticket into smaller tickets to explore functionality for the following pages:
  - [x] Upload and Finalize Audit Report - #338 
  - [x] Auditee Certification - #321 
  - [x] Auditor Certification - #321
  - [X] Submit to FAC for Processing - #339
- [X] Create mockups based on team consensus

**Comment by austinhernandez** [comment]
Meeting notes
- Auditee and auditor certification don't need to be in sequential order
 
Completion status is not particularly explicit on the Report Home page
- If there are any Xs on report home page, it is marked as "incomplete" on the my audits page
- Current status
 - in progress (break these into 2 sub-statuses which are essentially: in progress: audit report uploaded and in progress: audit report not uploaded)
 - submitted
 - received
 - available
 
- [ ] Question for Census: who can click submit button (anyone with access or a particular role) who asks this??

- [ ] @tadhg-ohiggins this may need to be captured in another ticket— We need a unique ID for customer support (currently Report ID) and we don't have it 
- It needs to be captured to data model
- We want to try something with a submission year prefix
- It is manually assigned right now

**Comment by austinhernandez** [comment]
Question added to the [Census call agenda here](https://github.com/GSA-TTS/FAC/issues/260)

**Comment by MelissaBraxton** [comment]
Per @austinhernandez Q above - We learned that anyone who has been given access to the submission can "submit" once all other steps are complete. 

@petermarks-gsa  - This is blocked until we confirm whether we're removing the in-app certification steps in favor of a signed pdf audit report. If we go that direction, we'll need this page to reflect that change.

**Comment by MelissaBraxton** [comment]
Created #321 to breakout the certify steps.

**Comment by MelissaBraxton** [comment]
With the creation of #321, #339 , and #338 to cover additional UI design, and with the bulk of start page design happening under #303, I think we can call this done. Can I get a 👍 from someone? @sreuber, @melchoyce, @petermarks-gsa

**Comment by petermarks-gsa** [comment]
👍 @MelissaBraxton Let's call this done :)
