### ISSUE TITLE
Epic: Search improvements

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2600]
```[tasklist]
### Tasks
- [ ] Provide `PublicQuery` and `ProtectedQuery` builders for search
- [ ] Revisit semantics of audit_year multiselect
- [ ] https://github.com/GSA-TTS/FAC/issues/2637
- [x] Fix cog/over search query
- [ ] https://github.com/GSA-TTS/FAC/issues/2821
- [ ] https://github.com/GSA-TTS/FAC/issues/2629
```

**Comment by jperson1** [comment]
Just about complete. Relevant tasks moved over to https://github.com/GSA-TTS/FAC/issues/2652, which succeeds it.
