### ISSUE TITLE
Add report ID to SAC data model

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#262]
## Background
The current version of the FAC provides “report IDs” for submissions. These are primarily for users to communicate with customer support.

## Acceptance Criteria (We'll know we're done when...)
* [ ]   We have a format for unique identifiers for this use case.
* [ ]   We have a way to generate them.
* [ ]   We have a field in the SAC data model for them.
* [ ]   We autogenerate then on SAC creation.

## Tasks
* [ ]   Decide on format.
* [ ]   Write code to generate them.
* [ ]   Add field to SAC model.
* [ ]   Autogenerate value on SAC creation.
* [ ]   Add tests.

**Comment by tadhg-ohiggins** [comment]
The current version uses a six-digit number:
![image](https://user-images.githubusercontent.com/2626258/172925191-d12ca012-2eaf-4c71-956d-5eb46e0056b7.png)

**Comment by tadhg-ohiggins** [comment]
First-pass thoughts:

*   Name it `report_id` for continuity.
*   In future, if we bring over data from the existing FAC systems, we will put the existing report ID value into this field, so this field could contain either the old report IDs (six-digit values) or the new one.
*   New format considerations:
    *   It should be relatively easy to communicate, so 10 characters is probably about the limit.
    *   It should be difficult for users to mix up their current report ID with any prior years’ report IDs.
    *   It shouldn't be completely predictable, that is, users should not be able to trivially guess what the next report ID in the system is given their own report ID.
*   New format proposal is for it to be 10 characters long:
    *   Four-digit year (the year when the report is created in the system).
    *   Three-digit day (the day when the report is created in the system, 1–366).
    *   Three-character randomly-generated alphanumeric case-insensitive value (but no “O” or “I” characters). (39,304 possibilities.)

**Comment by jadudm** [comment]
If we are going to mix new and old, I would consider finding a way to make sure they're... not "different kinds of data in the same field." 

This could lead to a situation where we begin writing conditional logic to determine if something is "new" or "old" by inspecting the "shape" of data within an id field. This feels... icky.

Some questions.

1. The four digit year is the year it is created in the system, which could be out of sync with the financial year to which the audit applies. Is that desirable? That is, a FY22 audit coming in during 2023 will have 2023 vs. 2022. Should this be the year the audit is being submitted for (which we know)?
2. I like the three-digit day. 
3. Could we have a 10-digit sequence identifier? That would allow us to mix new and old? 
4. Does it matter if you can "guess" the next audit?
5. If we're going to have an alphanumeric, should we instead just pick from a set of word lists? (E.g. two selections from a 7000-word common word list is 7000*6999 options, yielding "yellow-woodchuck" or "arguable-broccoli")
6. Should the ID instead be a true UUID (or is that hiding elsewhere in the model?), in which case this is... what is this?

Those questions are not all compatible with each-other; the first few are in the spirit of trying to merge an "old and new" situation without having a "different things in one field" situation. Or: if we're going to import old data into a new model, I'd personally rather see old IDs "lifted" into the new system, and having an easy way for users (e.g. agencies, auditors) to map their old report id back to the new id (because they can do a `*id*` search on our ID field with the right submission year, and therefore pull out the right report, even though the old id is now part of a longer/new/improved id.)

**Comment by tadhg-ohiggins** [comment]
An additional issue: if we are planning to send the data from the new FAC to the old FAC during the transition process, we might have to generate old-style six-digit numeric IDs as part of that process, and it's unclear how that might fit in with current Census system expectations.

**Comment by tadhg-ohiggins** [comment]
Note that this identifier is not the database id, which is the default, a monotonically increasing number starting at 1 (unless we decide otherwise, which I don't think we need to do).

I don't have a great reason for not using our database id as our customer support identifier, other than just having a vague feeling that letting any user give an easily-guessed value to customer support is questionable.

Our “new” versus “old” question should probably be resolved some other way, but I'm not completely convinced we need that because I'm not sure it'll be meaningful once data is moved over, but if it is meaningful we should have a boolean `legacy` field or similar to represent that.

In addition, I don't know whether or not it would make sense, for legacy imported data, to have both a legacy report ID and a new report ID. If we have both, then customer support would potentially have to look at both fields, which seems bad. But otherwise have to support having two kinds of report ID in the same field, which is ugly (although I don't know that it's that bad practically.)

Comments on @jadudm’s [numbered questions above](https://github.com/GSA-TTS/FAC/issues/262#issuecomment-1152604626):

1.  I initially thought the year should be the year of the start of the audit period, or the year of the end of the audit period, but thought that it would be harder for someone to remember which of those it was, and easier to remember when the submission was initiated. I'm definitely not attached to this and would be fine with whatever year makes most sense.
1.  That's not a question!
1.  We could definitely have a 10-digit identifier.
    Assuming we're never going to have more than 9,999,999,999 entries in the system, that is.
    Would that be randomly assigned? Monotonically increasing? Still starting with the whatever year we decide on? Would we start at 1,000,000,000 to make sure we don't clash with the existing six-digit numbers? (Or at 2,022,000,000 if we're still starting with year?)
    (Also, doing year + six digits does make it very easy to turn the older report IDs into new ones, but I don't know if that's something that actually matters.)
1.  I don't know for sure if guessability matters, but it feels like we might be missing some scenario where it might and that makes me uneasy, which makes me want to make it at least not easily guessable.
1.  That's an interesting idea, I think we should consider it. Will we get sued if we use the <cite>Wordle</cite> words as our list? Having them all be five letters seems useful. I feel like I'd still like to have a year reference in there, but user research might suggest otherwise.
1.  I didn't think we needed a true UUID since my sense of the requirements for this were:
    *   Easy for the user to communicate.
    *   Difficult for the user to confuse with other audits of their own (like the one they submitted the previous year)
    *   Easy for customer service to look up.
    *   Not too easy to guess since that apparently makes me anxious.

**Comment by jadudm** [comment]
The mapping back to Census is a thing, yo. Good point.

So, the `report_id` is basically for users and support, not for unique mapping. *Except*, possibly, that it plays a greater role in prior audit years/legacy data.

YEAR-DAY-3LETTERRANDOM-VERSION5-6DIG

The day and three letters, in a typical submission scenario, becomes enough of a reference for users and customer support.

To make mapping easier (and going back on something I said earlier), we could have an id version field. (This... please push back on this.)

`C2016`, `C2019`, let us say "this was the ID for Census in 2016." We could then start with `G2022` for `GSA 2022`. In truth, this should be a different field, perhaps. (The report changes shape from time to time, so do we have a way of tracking the SF-SAC version? If not...)

OK. I really don't like having an ID version dropped in the middle of the ID. It suggests a new field in the model, which perhaps we already have. If we don't have a version field... perhaps we need one. If we do, perhaps we use that to differentiate IDs when mapping back-and-forth between the systems.

Either way, I like the idea that we can generate these as we "lift" legacy data into our tables, and "map it back" as we go back to legacy tables for export. That feels like an important property of the `report_id` field.

Some thinking out loud here. I've come around from my `yellow-woodchuck` days (we would use an open wordlist, FYI... apologies to the NYT for my brash colleague... :D). 

Thoughts?

**Comment by tadhg-ohiggins** [comment]
As a related note, it turns out that audits should be done using the version of the form corresponding to their audit year. So if a users in 2023 submits an audit for FY 2017, they should submit the 2017 version of the form, not the 2023 version.

This strongly suggests we should have a version field in the model.

**Comment by tadhg-ohiggins** [comment]
I ended up using a 17-character report id:

*   Four-digit year of start of audit period.
*   Three-digit char (but without I or O) random.
*   10-digit numeric (monotonically increasing, but starting from 0001000001 because the Census numbers are six-digit values. The formula for creating this is basically "how many non-legacy entries there are in the system plus 1,000,000".
