### ISSUE TITLE
Design audit report start page

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#264]
**Background**
Breakout issue of #212 
Related page / follow up work in #260 

Original screen on FAC
![Screen Shot 2022-02-02 at 10 50 2](https://user-images.githubusercontent.com/23194720/173101042-b8230626-8c29-4bf4-bed2-0bab2de7d39f.png)

**Tasks**
- [x] Set up meeting between Dev + Design 
- [x] Walkthru current FAC functionality to decide next steps on design and implementation
- [x] Design the start page / "report home" page

**Acceptance Criteria (We'll know we're done when...)**
- [x] Screen is ready to be used in a Figma usability testing
- [x]  All text has a contrast ratio of 4.5:1 with the background
- [x]  Interaction are documented if they deviate from USWDS components
- [x]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] There is an option for multilingual support
- [x] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by austinhernandez** [comment]
**Considerations:**
- Changed auditee name to The DC Central Kitchen
- Moved secondary nav up to match with USWDS pattern 
- Reorganized audit report information 
- Put CTAs in a more simplistic table
- Changed date/time into an easier to read format

Questions
- Are there any other user actions that a user can take associated with their account? (sign out, ... but what else?)
- What is the reason for being able to edit type of entity but nothing else on the document?
- I don't want to over complicate things, but if 2 or more people are editing a thing, it seems like it would be helpful if there was a timestamp/last edited by, instead of just completion date and time? 

![Audit Start Page](https://user-images.githubusercontent.com/23194720/173147214-be9350d2-9e28-45c5-aae0-ee2b21ac5b87.png)

**Comment by MelissaBraxton** [comment]
1. Are there any other user actions that a user can take associated with their account? (sign out, ... but what else?)
_With their global account (MVP), no. Not at this time._ 

3. What is the reason for being able to edit type of entity but nothing else on the document?
_Everything else but entity type and UEI one this page are system generated. I don't think we want to invite folks to edit/change UEI at this stage unless they've chosen to initially proceed with an invalid UEI and later need to be reminded to update/validate it._ 

5. I don't want to over complicate things, but if 2 or more people are editing a thing, it seems like it would be helpful if there was a timestamp/last edited by, instead of just completion date and time?
_I think you're hunch that "edited by + timestamp" is more valuable to users than "completed by + timestamp" is probably right. But I'm not sure if the value outweighs the back end engineering effort in logging. I think we can ask about the usefulness of logging info in this table it in sprint 6 research. If there's a strong signal that "edited by" is a need, then we can document it and prioritize the work accordingly._ 


7. I feel like I now need to revisit the "submit an audit" header. 1) because it will not link to the expected page and 2) it at least needs to change states once logged in
_++_

**Comment by austinhernandez** [comment]
on figma at:
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3136%3A18949

**Comment by petermarks-gsa** [comment]
@austinhernandez Thanks! Are there any corresponding implementation notes for this aside from what's discussed in this issue?

**Comment by austinhernandez** [comment]
@petermarks-gsa for the purpose of the prototype, there is no more implementation notes. I think we will know more about implementation after this round of usability testing

**Comment by MelissaBraxton** [comment]
I'd like to propose that further refining this issue/adding implementation notes be an explicit goal of the first few days of sprint 7. cc @austinhernandez and @petermarks-gsa

**Comment by petermarks-gsa** [comment]
@MelissaBraxton, @austinhernandez Sounds good. Happy to close this issue out if we want to open another design issue, or put this one back "in progress". Whatever is easiest on your end to track.

**Comment by petermarks-gsa** [comment]
Per discussion, next steps are captured in https://github.com/GSA-TTS/FAC/issues/271

Following that we'll create mocks and implementation notes in a new ticket: https://github.com/GSA-TTS/FAC/issues/279
