### ISSUE TITLE
Epic: User experience with search increment 1

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2652]
# User Experience with Search

Succeeds https://github.com/GSA-TTS/FAC/issues/2600

## At a glance:

**In order to** improve my search experience
**as a** user
**I want** access to more search resources and report data

After implementing search, this is a space to write out and track sub-tasks related to improving the user search experience. 
Buttons, links, restructuring, etc. 

```[tasklist]
### Data
- [ ] https://github.com/GSA-TTS/FAC/issues/2918
- [ ] https://github.com/GSA-TTS/FAC/issues/2967
- [x] Search by state
- [x] Tribal data access (provide `PublicQuery` and `ProtectedQuery` builders for search) - Allow authorized users to access private tribal audits in search results and summary pages.
```

```[tasklist]
### Resources
- [x] Link to the advanced search instructions (https://www.fac.gov/data/resources/) from the app search page.
- [ ] Make it more clear whether a user is on the submission side or the search side by making use of **_colors_**. Potentially, blue for submission pages and green for search pages.
```

**Comment by jperson1** [comment]
Placeholder buttons for export? [jp/search-bulk-download](https://github.com/GSA-TTS/FAC/tree/jp/search-bulk-download)

![image](https://github.com/GSA-TTS/FAC/assets/91098850/23c8e7f2-18b6-46b8-8dfe-5ffd4c724bec)
![image](https://github.com/GSA-TTS/FAC/assets/91098850/7b624e5a-ecf5-4d54-bb65-9ba43f1075f1)

**Comment by jadudm** [comment]
Calling this:

Make it more clear whether a user is on the submission side or the search side by making use of **_colors_**. Potentially, blue for submission pages and green for search pages.

a *result* of search increment one. Closing the work as done.
