### ISSUE TITLE
Epic: Card sort regarding top-nav terminology

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2653]
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2702
- [ ] https://github.com/GSA-TTS/FAC/issues/2704
- [ ] https://github.com/GSA-TTS/FAC/issues/2706
- [ ] https://github.com/GSA-TTS/FAC/issues/2707
- [ ] https://github.com/GSA-TTS/FAC/issues/2708
- [ ] https://github.com/GSA-TTS/FAC/issues/2716
- [ ] https://github.com/GSA-TTS/FAC/issues/2709
- [ ] https://github.com/GSA-TTS/FAC/issues/2710
- [ ] https://github.com/GSA-TTS/FAC/issues/2769
- [ ] https://github.com/GSA-TTS/FAC/issues/2711
- [ ] https://github.com/GSA-TTS/FAC/issues/2712
- [ ] https://github.com/GSA-TTS/FAC/issues/2713
- [ ] https://github.com/GSA-TTS/FAC/issues/2714
- [ ] Retro this ticket and template it
- [x] Get Leigh access to FAC@GSA.GOV
```

```[tasklist]
### Tasks
```
