### ISSUE TITLE
Epic: Summary report generation

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2655]
# Bulk Data Download

## At a glance:

**In order to** disseminate all the data in a report
**as a** developer
**I want** a way to grab a spreadsheet of the current search results.

After implementing search, this is a space to write out and track sub-tasks related to providing bulk data downloads. 
Single or multi-report excel downloads. Spike proof-of-concept completed by @jadudm. 

```[tasklist]
### Single report
- [ ] https://github.com/GSA-TTS/FAC/issues/2923
- [ ] https://github.com/GSA-TTS/FAC/issues/2963
- [ ] https://github.com/GSA-TTS/FAC/issues/2510
```

```[tasklist]
### Multiple reports
- [ ] https://github.com/GSA-TTS/FAC/issues/2924
- [x] Design multiple downloads
- [ ] https://github.com/GSA-TTS/FAC/issues/3035
```
```[tasklist]
### Backend
- [ ] https://github.com/GSA-TTS/FAC/issues/2925
- [ ] https://github.com/GSA-TTS/FAC/issues/2927
- [ ] https://github.com/GSA-TTS/FAC/issues/2962
- [ ] https://github.com/GSA-TTS/FAC/issues/2964
```
