### ISSUE TITLE
Stitching together prototype

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#266]
**Background**
Add all designed pages to a clean Figma page that will be used for usability testing:
https://www.figma.com/file/kftEBMYHgDvP3IPZCQaW14/FAC-Sprint-6-prototype?node-id=0%3A1

**Acceptance Criteria (We'll know we're done when...)**
- [x] ensure that the sample data is the same
- [x] making sure the links work to complete tasks
- [x] make sure it aligns with research protocol

**Tasks**
- [x] Add all designed pages to this [clean Figma page that will be used as a prototype for usability testing](https://www.figma.com/file/H4hZuxApc9akq3b4UtMv6M/FAC-Sprint-6-Prototype?node-id=0%3A1
):

**Comment by austinhernandez** [comment]
Clickable prototype for the sprint 6 usability tests: https://www.figma.com/proto/kftEBMYHgDvP3IPZCQaW14/FAC-Sprint-6-prototype?page-id=0%3A1&node-id=13%3A2081&viewport=622%2C317%2C0.25&scaling=min-zoom&starting-point-node-id=13%3A2081&show-proto-sidebar=1

note: It is a very linear prototype, so the the navigation is not clickable
