### ISSUE TITLE
Epic: Migrate `additional-ueis`

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2669]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."
[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** migrate historical data
**as a** developer
**I want** a map in front of me and a breadcrumb trail behind

Note: *cells* are just *degenerate ranges* that have the same cell for the beginning and end of a named range.

## Mapping functions

Each range will either 1) have a new mapping function in `census_data_migration` or 2) re-use an existing mapping. All mappings will end up in `/census_data_migration/insertions`, `/census_data_migration/common`, or `census_data_migration/additional-ueis`.

For any fields that require discussion, break them out as an issue. At the least, document all decisions on how the field will be mapped in that issue. Preferably, conduct all discussion of how those fields will be mapped in the issue.

For simple mappings, or mappings previously discussed, simply check the item off; no issue breakout nessary.

```[tasklist]
### Cells
- [ ] `additional-ueis` : mapping `auditee_uei`
- [ ] `additional-ueis` : mapping `section_name`
- [ ] `additional-ueis` : mapping `version`
```

```[tasklist]
### Ranges
- [ ] `additional-ueis` : mapping `additional_uei`
``` 

## Document transformations

IGs, resolution officials, and members of the public make use of this data for their day-to-day work conducting oversight of federal awards. We must document everything.

Every mapping should documented in the *mapping dictionary*

| Workbook | Historic table | Historic column | Named range | Mapping function | HREF |
| -- | -- | -- | -- | -- | -- |
| additional-ueis | N/A | N/A | version | insert_version_number | https://github.com/... |
| additional-ueis | ELECUEIS | UEI | additional_uei | uei_to_uei | https://... |

## Exceptions

Some records will fail during the workbook generation, intake, or validation steps. For this workbook, document, review, and update (as needed) exception handling.
