### ISSUE TITLE
Epic: Initial end-to-end workbook code refactor 

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2670]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."
[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** migrate historical data 
**as a** product owner
**I want** to know the process held the data to the same (or higher) standard as our intake.

## The code: a brief and likely inaccurate history

Months ago, I developed a workbook generator. It began life in order to exercise our early JSON Schema validations. It helped find many logical errors, and drove a great deal of improvement in our intake. 

It grew and evolved, serving in a one-off capacity for generating workbooks. As the API came online, I extended it to run end-to-end. Or, I discovered I could generate workbooks *in memory*, and feed them to the Django application. This rapidly became an end-to-end test: a set of workbooks could be generated, fed to the app, run through all of our validations (including cross-val), and then the data at time of input is compared with what is available via the API.

It is this code that we are basing our historical data migration on.

## Approach

The initial refactoring will clone the existing code to another part of the tree, and then walk it forward.

1. The code will always generate workbooks that validate end-to-end.
2. Unit tests for critical/core functions will be developed as needed along the way.
3. Cleanup/refactoring can and should happen as needed.
4. No massive/architectural rewrites are part of this work.

At all points in the refactoring the code should continue to generate workbooks that validate.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2723
- [ ] https://github.com/GSA-TTS/FAC/issues/2727
- [x] E2E refactor: Update `import` statements for new E2E code
- [ ] https://github.com/GSA-TTS/FAC/issues/2671
- [ ] E2E refactor: document execution of code locally, in GH Actions
- [x] Add a README for running the end-to-end code
- [x] Add a README for running the historical migration code
```

https://github.com/GSA-TTS/FAC/issues/2672 is broken out as its own epic for refactoring/improving this code.

When these steps are complete, the team should have a tool that can generate workbooks using the "messy" historical data loaded into our environments via Docker container. It does not yet work with new/"authoritative" Census data.
