### ISSUE TITLE
Epic: improve testing around core/critical E2E functions

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2672]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."
[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** have confidence in the workbook migration code 
**as a** product owner
**I want** more testing around what was previously exploratory/nice-to-have app code.

## `workbook_creation.py`

https://github.com/GSA-TTS/FAC/blob/main/backend/dissemination/workbooklib/workbook_creation.py

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2673
- [ ] https://github.com/GSA-TTS/FAC/issues/2674
- [ ] https://github.com/GSA-TTS/FAC/issues/2675
- [ ] https://github.com/GSA-TTS/FAC/issues/2833
- [ ] https://github.com/GSA-TTS/FAC/issues/2890
```

## `excel_creation.py`

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2676
- [x] E2E improve: Remove `test_pfix()`
- [ ] https://github.com/GSA-TTS/FAC/issues/2677
- [ ] https://github.com/GSA-TTS/FAC/issues/2678
- [ ] https://github.com/GSA-TTS/FAC/issues/2679
- [ ] https://github.com/GSA-TTS/FAC/issues/2680
```

The code around test tables is problematic, and [I speak about it in the E2E documentation](https://docs.google.com/document/d/12jcupPwqTc1muIaCsMxKgC33cOPOQQ6V4EoH9OmZGo0/edit?disco=AAAA_SMW678). There are ways to improve this dramatically, but it may not be worth it. In which case, despite how this code looks... *not touching it* might be the right thing to do.

## `sac_creation.py`

Probably all of it. At the least, we need a way to map

historic field -> named range -> api_field

as well as provide a migration function. In essence, it would be good to have a dictionary of `FieldMap` structures (just like the workbooks) that do the work of creating the general info object. However, we would then take the FieldMap structures and, instead of filling a workbook, use them to create a JSON object that represents the `general_info` and `audit_info` objects in the SAC.

That would be the best way to clean this whole thing up. And, it would then be easy to integrate the general info form into the API end-to-end testing.
