### ISSUE TITLE
FAC-D-2023-009 - Scanning at rest

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2693]
```[tasklist]
### Tasks
- [x] ClamAV needs to scan files at rest
- [x] Schedule to run on a periodic basis
- [x] Capture events of failed scans in NR and remediate
```

**Comment by jadudm** [comment]
https://github.com/GSA-TTS/FAC/tree/jadudm/scan-files-at-rest-for-viruses

**Comment by danswick** [comment]
@asteel-gsa will test in preview, monitor performance, check results with a collection of historical test data.

**Comment by jadudm** [comment]
@danswick , @asteel-gsa lets put in a GH Action/cron that runs this every six months, scheduling it to run in April and... whatever six months from April is. 

We're going to have to discuss the strategy as a whole w/ GSA, but for now, we need to complete the ticket.

**Comment by jadudm** [comment]
Hm. We may also want to think about how it reports things, how it keeps track of what it has run, etc... :/

**Comment by asteel-gsa** [comment]
I am fine merging it as is, just to say it is running. However, I am not keen on the idea of watching it for x months 😆 

it would probably be nice to have a `logger.info(f"SCAN PASS: {object}")` statement as well, though that may clutter the logs, so... 

the `excel` bucket is fine however, I see a lot of `Read timed out. (read timeout=15)"}` errors, and not a true failed scan. I don't see anything in the code to `exit 1` either, so, I am rerunning `singleauditreport` scan in `preview` atm, but, considering it will run for 2 days, we probably shouldn't deploy anything else to preview, so I can check the logs as to why it failed the task. (at this point, my only guess is the task runner crashed)

**Comment by asteel-gsa** [comment]
@jadudm I think we need to look at this a bit further. Even in `preview` this operation is so long running that when I realize the task has failed and check the logs, they are gone.

It has a lot of trouble combing through `${bucket}/singleauditreport/` with an incredible amount of failed scans, so we might want to adjust the read timeout to 30s or more

**Comment by jadudm** [comment]
It is probably worse than it appears.

It may be the smart thing is to just have the convo about scanning inbound *and* outbound, as opposed to trying to solve this problem. Otherwise, we're going to need a whole database/logging framework for tracking how often we've scanned all 700K+ files.

:/ 

More TBD.

**Comment by danswick** [comment]
MVP work is being tracked here: https://github.com/GSA-TTS/FAC/issues/3758. I'm going to move this issue to "Blocked" until the MVP is done, mostly so it's clear which of these issues is active.

**Comment by asteel-gsa** [comment]
This should be satisfied with the completion on #3758 
@timoballard will be configuring New Relic alerts and I can support if needed to wrap this up.

**Comment by asteel-gsa** [comment]
As of the 2024-05-16 release, `production` files are now being scanned with the logs being sent to new relic.

```
$ cf logs fac-file-scanner
Retrieving logs for app fac-file-scanner in org gsa-tts-oros-fac / space production as alexander.steel@gsa.gov...

   2024-05-16T14:15:35.80-0400 [APP/PROC/WEB/0] OUT [2024-05-16 18:15:35,806] INFO in app: singleauditreport/2016-01-CENSUS-0000003259.pdf scan result: ScanResult.CLEAN
   2024-05-16T14:15:37.09-0400 [APP/PROC/WEB/0] OUT [2024-05-16 18:15:37,089] INFO in app: singleauditreport/2016-01-CENSUS-0000019833.pdf scan result: ScanResult.CLEAN
   2024-05-16T14:15:38.42-0400 [APP/PROC/WEB/0] OUT [2024-05-16 18:15:38,426] INFO in app: singleauditreport/2016-01-CENSUS-0000019890.pdf scan result: ScanResult.CLEAN
   2024-05-16T14:15:39.66-0400 [APP/PROC/WEB/0] OUT [2024-05-16 18:15:39,663] INFO in app: singleauditreport/2016-01-CENSUS-0000020971.pdf scan result: ScanResult.CLEAN
```
