### ISSUE TITLE
Analyze sprint 6 research data

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#271]
Breakout issue of <story>

**Background**

**Acceptance Criteria (We'll know we're done when...)**
- [x] We've done some affinity mapping across relevant data and have identified themes from sprint 6 research

**Tasks**
- [x] Create analysis template in Mural or Excel
- [x] Review interview notes and (if needed) videos
- [x] Pull relevant excerpts into analysis template
- [x] Look across excerpts and name themes.

**Comment by MelissaBraxton** [comment]
I really like the idea of continuing to use [this airtable ](https://airtable.com/app8jhoGYFecY0qe3/tbledY67Jaw017MMO/viwESEDUp7MYRapE4?blocks=hide)for analysis, but I'll leave it to whoever picks up this issue to choose the analysis framework that works best for them.
