### ISSUE TITLE
Epic: Historic data loading

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2718]
```[tasklist]
### Tasks
- [x] Remove data from the tree
- [x] Cleanup, comment the historic data loading scripts
- [x] Document how to use them so any dev on the team can load some historic data
- [x] **Pair**/present to the team how to do this, and support everyone getting setup
```
