### ISSUE TITLE
Write up sprint 6 research report

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#272]
Breakout issue of <story>

**Background**

**Acceptance Criteria (We'll know we're done when...)**
- [ ] We have an easily scanable document that lists research insights
- [ ] New needs statements are reflected on the story map
- [ ] New stories/refinements are documented in new/existing issues as needed

**Tasks**

- [x]  Synthesize research (dependent on #271)
- [x] Write up summary 
- [ ] Write up new user needs statements add to Mural
- [ ] Post roles goals and needs statements in wiki

**Comment by sreuber** [comment]
Report is saved to the newly created Research Report-outs folder. 
https://docs.google.com/presentation/d/18atRRgAp-BKzJQ4d3QGSLyIqr1BRL59nD4YQ75p6Uzc/edit?usp=sharing
