### ISSUE TITLE
Compensate sprint 6 research participants

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#273]
Breakout issue of <story>

**Background**

**Acceptance Criteria (We'll know we're done when...)**
- [ ] We have confirmation that compentation was sent to all sprint 6 participants 

**Tasks**
- [x] Complete [compensation tracking sheet](https://docs.google.com/spreadsheets/d/1OfCKLx8iPpunUdfnLVzVtKz_IhHQTYjDOpkiK3LiJZw/edit#gid=0)
- [x] Ping TTS ops when it's ready
- [ ] Follow up w/ TTS ops to ensure compensation was sent.

**Comment by melchoyce** [comment]
@MelissaBraxton Do you know if this was completed?
