### ISSUE TITLE
Refine all SF-SAC forms based on sprint 6 research insights

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#274]
Breakout issue of <story>

**Background**
This issue is intended to cover refining mocks of the SF-SAC form pages we identified in sprint 6 research. Further refining the issue depends a bit on issue #271, since we won't have a clear sense of needed refinements until we've started our analysis. 

**Sub-tasks**
- [x] https://github.com/GSA-TTS/FAC/issues/288
- [x] https://github.com/GSA-TTS/FAC/issues/289
- [x] https://github.com/GSA-TTS/FAC/issues/290
- [x] https://github.com/GSA-TTS/FAC/issues/295
- [x] https://github.com/GSA-TTS/FAC/issues/278 (invalid UEI)
- [x] https://github.com/GSA-TTS/FAC/issues/301
- [ ] https://github.com/GSA-TTS/FAC/issues/313
- [x] https://github.com/GSA-TTS/FAC/issues/302
- [x] https://github.com/GSA-TTS/FAC/issues/303

Work on last 
- [ ] notes for SEFA
- [ ] secondary auditors

**Acceptance Criteria (We'll know we're done when...)**
- [ ] We have mocks of all SF-SAC form pages that reflect our most recent knowledge of the best way to meet users needs. 

**Tasks**
- [ ] Review sprint 6 research analysis
- [ ] Create checklists for refinement needed to each page
- [ ] Update this issue with the checklist of refinements needed
- [ ] Make refinements
- [ ] Peer review

**Definition of done**
**Acceptance Criteria (We'll know we're done when...)**
- [ ] Screens in Figma are ready to be handed off to front end
- [ ]  All text has a contrast ratio of 4.5:1 with the background
- [ ]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment]
Leaving the "needs refinement" label on here until we've started #271

**Comment by MelissaBraxton** [comment]
@petermarks-gsa  - Once #https://github.com/GSA-TTS/FAC/issues/302 and https://github.com/GSA-TTS/FAC/issues/295 clear review, we can close this out. #313 will stay in blocked.

**Comment by MelissaBraxton** [comment]
Closing with the understanding that #313 will be worked separately once it is unblocked.
