### ISSUE TITLE
Document New Relic "Steps Taken" for POA&M Notes

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#2748]
Based on discussion with Jadud and Mogul, since we have open POA&Ms in regard to new relic, we want to document all steps taken thus far, so if we need to ask for an extension on the deadline, we have evidence to support our efforts in attempting to get new relic to work.

### Tasks

```[tasklist]
- [ ] Compile a gdoc of steps taken
- [ ] Export NR Support logs and attach to file
- [ ] PR links that illustrate changes to rectify in relation to NR support discussions
- [ ] Review
```

**Comment by asteel-gsa** [comment]
This is done. https://docs.google.com/document/d/1SOtwAjMwnO0b7BcDnUDFFIwhjlkgCVe0ukiyy5M0kQk/edit#heading=h.xl5s0hbcax46
