### ISSUE TITLE
Create how-do-i-resubmit article for static site

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#2756]
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2758
- [ ] https://github.com/GSA-TTS/FAC/issues/2759
- [x] CX/Helpdesk team publishes article in ZD
- [ ] Update the static site FAC.gov
```

**Comment by Carley-Jackson** [comment]
CJ & JM synced on this following message:

Improved resubmission capabilities for FAC records will be available in the future.  If you need to resubmit your GSA record, please submit a new record at FAC.gov.  Please know, this will affect your FAC Acceptance date and potentially change your risk profile.

**Comment by James-Paul-Mason** [comment]
This looks very good from a content perspective. Here is a suggestion for greater clarity: 

"We are actively working on improved resubmission features for FAC records, and they will be available in the future. For now, if you need to resubmit your GSA record, please submit a new record at FAC.gov. Please note that this will affect your FAC Acceptance date and may potentially change your risk profile" 

If there are any issues in terms of the accuracy of my revision, your original message is sufficiently plain-language enough especially given our audience.

**Comment by James-Paul-Mason** [comment]
@lauraherring Can you do a quick review of the content above when convenient? Thanks in advance!

**Comment by lauraherring** [comment]
Hey @James-Paul-Mason, this looks really good. The only thing I would change would be removing the second clause of the first sentence, "...and they will be available in the future."

**Comment by James-Paul-Mason** [comment]
@jadudm @Carley-Jackson So in terms of **the question** for this FAQ, are we going for something simple like this: 
"How do I resubmit my record at the GSA FAC?" 
Or something more comprehensive like this:
"How do I resubmit my record at the GSA FAC? Do I need to delete my previous submission"?
The question of deleting previous submissions comes up so often, I thought it was worth checking before I publish the FAQ.

**Comment by Carley-Jackson** [comment]
I prefer the first one.

**Comment by James-Paul-Mason** [comment]
Published FAQ and created macro for HD. @lauraherring looks like this is ready for static site.
Here is the FAQ link if needed: https://support.fac.gov/hc/en-us/articles/21368035577357-How-do-I-resubmit-my-record-at-the-GSA-FAC-

**Comment by danswick** [comment]
This is done.
