### ISSUE TITLE
Document first increment of search as support center article

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2763]
Search is live, but we have no documentation to support it.

```[tasklist]
### Decision
- [ ] Decide if we should, or should not, have a help center article to support the initial launch of search.
``` 

If content/CX leads think we should have an interim/starting-point help center article for search, then

```[tasklist]
### Tasks
- [ ] Revise/author content. The document below is offered as a starting point.
- [x] Review for plain language
- [x] Post to help center
- [ ] Author announcement for site, link to help center article.
```

Possible starting point: https://docs.google.com/document/d/15FJb9YqtaGN7kTRScv0Yu6SGoy1dgVvPooIADbNV7OU/edit

**Comment by lauraherring** [comment]
@James-Paul-Mason Do we have anything in the knowledge base about search? We have [a guide on the static site ](https://www.fac.gov/data/resources/)but has that been translated over to ZD?

**Comment by James-Paul-Mason** [comment]
@lauraherring Here is a draft of a FAQ on this topic--as we discussed, it's mainly a re-direct to the static site guide. https://docs.google.com/document/d/1PnOXE4ZmRSzMeztPR8oEZEBZ9N4vXHsRDJQl4czTS_k/edit

**Comment by lauraherring** [comment]
@James-Paul-Mason Looks good to me, I made a slight tweak now that Tribal audits are available but otherwise this was great.

**Comment by James-Paul-Mason** [comment]
@lauraherring Thanks! I have published the updated version to ZD.
