### ISSUE TITLE
Address Chromium crashes during Cypress tests

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2778]
We are now occasionally seeing Cypress tests crash, both locally and during deployments. This is probably because we are now doing multiple full submissions:
![image](https://github.com/GSA-TTS/FAC/assets/142051477/df164e53-cca0-40cc-a789-fbecf255842e)

Docs for this error are [here](https://docs.cypress.io/guides/references/error-messages#The-browser-process-running-your-tests-just-exited-unexpectedly). The fix to limit `numTestsKeptInMemory` would only help with local crashes, since deployments don't use open mode. It would seem trying out `experimentalMemoryManagement` set to true is our only option. This would be set in `FAC/backend/cypress.config.js`.

### Tasks

```[tasklist]
- [x] Set `experimentalMemoryManagement` to true in `FAC/backend/cypress.config.js`
- [ ] Confirm crashes stop occurring locally in open mode. This may take many runs.
- [ ] Monitor deployments and confirm crashes stop occurring there
```

**Comment by danswick** [comment]
We haven't seen this issue in a while.
