### ISSUE TITLE
Mapping / Transformation functions

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#2798]
When Census historical data is migrated to GSAFAC, mapping / transformations may be required. This ticket will track these functions.

**Please note that all Census tables have many rows that contain header information as data.  All these rows need to be ignored for migration.**

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/2799
- [ ] https://github.com/GSA-TTS/FAC/issues/2800
- [ ] https://github.com/GSA-TTS/FAC/issues/2801
```
