### ISSUE TITLE
Epic: user role management

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2812]
Epic: user role management

Implementation of [Expanded user role management ADR](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0031-user-access-management.md).

This is the outline, but most of these will become full issues of their own. 

```[tasklist]
- [x] Shepherd https://github.com/GSA-TTS/FAC/issues/2739 through the acceptance process.
- [ ] https://github.com/GSA-TTS/FAC/issues/2831
- [x] https://github.com/GSA-TTS/FAC/pull/2849 Django functions for creating a `DeletedAccess` object and deleting the corresponding `Access` object; probably we’ll override `Access.delete`.
- [x] https://github.com/GSA-TTS/FAC/issues/2830 (Because we need to do this, and doing it before adding another view makes sense.)
- [ ] https://github.com/GSA-TTS/FAC/issues/2855
- [x] Content and visual design for `/audit/manage-submission/<report_id>`.
- [x] Add Django admin support for this feature, primarily around making `DeletedAccess` entries viewable/searchable by admin staff users. (https://github.com/GSA-TTS/FAC/pull/2973)
- [x] Add links to `/audit/manage-submission/<report_id>` to `/audit/submission-progress/<report_id>` so that this entire feature is available to users
```

*   These are repeated sets, one each for each of the roles. Do the auditor certifying official support first and see if it works, then either do the others or rewrite them.

```[tasklist]
- [x] Content and visual design for auditor certifying official role change.
- [x] Add a link to `/audit/manage-submission/auditor-certifying-official/<report_id>` to the manage access page. Django views for the GET side, plus attendant HTML.
- [x] Django POST skeleton (not necessarily wired up to backend functions) for `/audit/manage-submission/auditor-certifying-official/<report_id>`, plus attendant HTML form. https://github.com/GSA-TTS/FAC/pull/2891
- [x] Wiring up the POST function so that it actually does the change, deletion, etc. https://github.com/GSA-TTS/FAC/pull/2891
- [x] Content and visual design for auditee certifying official role change.
- [x] Add a link to `/audit/manage-submission/auditee-certifying-official/<report_id>` to the manage access page. Django views for the GET side, plus attendant HTML.
- [x] Django POST skeleton (not necessarily wired up to backend functions) for `/audit/manage-submission/auditee-certifying-official/<report_id>`, plus attendant HTML form. https://github.com/GSA-TTS/FAC/pull/2891
- [x] Wiring up the POST function so that it actually does the change, deletion, etc. https://github.com/GSA-TTS/FAC/pull/2891
- [ ] https://github.com/GSA-TTS/FAC/issues/3006
- [x] Add a link to `/audit/manage-submission/editors/<report_id>` to the manage access page. Django views for the GET side, plus attendant HTML. https://github.com/GSA-TTS/FAC/pull/3042
- [x] Django POST skeleton (not necessarily wired up to backend functions) for `/audit/manage-submission/editors/<report_id>`, plus attendant HTML form. https://github.com/GSA-TTS/FAC/pull/2994
- [x] Wiring up the POST function so that it actually adds the new access. https://github.com/GSA-TTS/FAC/pull/2994
```

```[tasklist]
### Tasks from <https://github.com/GSA-TTS/FAC/issues/2654>
- [ ] https://github.com/GSA-TTS/FAC/issues/2740
- [ ] https://github.com/GSA-TTS/FAC/issues/2741
- [ ] https://github.com/GSA-TTS/FAC/issues/2742
- [ ] https://github.com/GSA-TTS/FAC/issues/2743
- [ ] https://github.com/GSA-TTS/FAC/issues/2745
- [ ] https://github.com/GSA-TTS/FAC/issues/2966
```

**Comment by danswick** [comment]
FYI @Carley-Jackson and @Leighdiddy, I combined the previous user access epic with this one and pasted the tasklist at the top.

**Comment by jadudm** [comment]
Closing this epic based on the ADR. However, we do need (at some point) for user compliance reasons the ability to remove editors *and* certifying officials.

Example: If an editor or certifying official leaves an organization/state, they may need to be removed (for legals reasons) in a prompt manner from the audits they are associated with. 

But. That's a new epic/story. Closing  this story as done.
