### ISSUE TITLE
Implement Digital Analytics Program (DAP) for the FAC application and static site

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#2813]
### Tasks

```[tasklist]
- [x] ~~Per the [DAP docs](https://digital.gov/guides/dap/add-your-site-dap/), contact the DAP program to define a point of contact.~~ This is handled at the GSA level.
- [x] Decide if we should use the hosted bundle or self-host. Self-hosting should avoid CSP/proxy configuration issues at the expense of additional maintenance burden.
- [x] Once the above is decided, implement for both the FAC application and static site.
```

Previously:
- https://github.com/GSA-TTS/FAC/issues/1014#issuecomment-1520660294
- https://github.com/GSA-TTS/FAC/issues/741

**Comment by lauraherring** [comment]
It looks like there is some code in our source for tracking analytics but we're not being picked up by the TTS Google Analytics dashboard. It's possible this is related to the GA4 transition?

**Comment by danswick** [comment]
A couple of additional considerations:

* Is it appropriate to enable DAP on pages that require authentication? (ref: https://github.com/digital-analytics-program/gov-wide-code?tab=readme-ov-file#appropriate-placement) 
* It looks like the DAP script is broken by our fairly strict CSP. We may need to update the egress proxy (and probably some other related things) for it to work.

**Comment by Leighdiddy** [comment]
@jadudm Hi! is there any chance of this getting addressed before March? I'm not sure where we left off here. Design would love to have access to analytics before heavy traffic hits :)

**Comment by jadudm** [comment]
Seems reasonable; we're queueing in a few things for the January POA&M deadline, but this should be (famous last words) doable. @danswick comments from when he looked at it yesterday need investigation, and I would look to him to determine when it is good to queue in over the next 2-4 weeks.

**Comment by Leighdiddy** [comment]
@danswick is it alright if I check in with you on this next week? Or should I raise it at the next backlog?

**Comment by jadudm** [comment]
This will likely not be touched before we close https://github.com/GSA-TTS/FAC/issues/2649.

**Comment by danswick** [comment]
We should be set up now! The following folks have confirmed access to the DAP GA page:

* @Leighdiddy 
* @lauraherring 
* @danswick 

Our configuration specifies `agency=GSA` `subagency=TTS{,OROS}` (the static site omits `,OROS`), which appears to be correct, but our analytics do not appear under GSA or TTS in the DAP system. Instead, our data is under the primary "GOV-wide" umbrella. I put together a [basic pageviews "exploration" here](https://analytics.google.com/analytics/web/?utm_source=marketingplatform.google.com&utm_medium=et&utm_campaign=marketingplatform.google.com%2Fabout%2Fanalytics%2F#/analysis/p393249053/edit/4gPR9S2KRbySbhWYVYiWXw) (authentication required). 

Looks like we're done here!
