### ISSUE TITLE
🅛 Back end - Create/modify API endpoint for SF-SAC

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#284]
Breakout of https://github.com/GSA-TTS/FAC/issues/185

### Background
* Create/modify API endpoint to present and accept SF-SAC data for this page

###  Tasks

* [x]  Creation of SAC.
* [x]  Handling of UEI stuff during creation.
* [x]  Viewing SAC post-creation.
* [x] Editing SAC post-creation.
* [ ] ~~Handling the special case of manually-entered data that would normally be provided by SAM.gov via UEI lookup.~~
  * Will verify this at story level

### Related tasks, but out of scope for this issue:

- Ⓛ Backend work for viewing and editing the SAC: [#398](https://github.com/GSA-TTS/FAC/issues/398)
- Frontend work for viewing and editing the SAC: [#399](https://github.com/GSA-TTS/FAC/issues/399)
- https://github.com/GSA-TTS/FAC/issues/402

**Comment by petermarks-gsa** [comment]
Adding "needs refinement" to look into editing UEI use case.

**Comment by tadhg-ohiggins** [comment]
284 consists of at least the following features:

*   Creation of SAC.
*   Handling of UEI stuff during creation.
*   Viewing SAC post-creation.
*   Editing SAC post-creation.
*   Handling the special case of manually-entered data that would normally be provided by SAM.gov via UEI lookup.

@heymatthenry  and I suggest that we split these out.

- [x]   Creation of SAC (already done, as a SAC instance is created when the pre-SAC flow is completed).
- [x]   Most of the UEI-related complexity during creation flow is also already done.
- [ ]   Backend work for viewing and editing the SAC: [#398](https://github.com/GSA-TTS/FAC/issues/398)
- [ ]   Frontend work for viewing and editing the SAC: [#399](https://github.com/GSA-TTS/FAC/issues/399)
- [ ]   Editing the UEI or UEI-derived field (regardless of whether or not they were originally provided by SAM.gov or manually). (This should be its own specific flow addressed in other issues at some future point.)

@petermarks-gsa thoughts on this approach?

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins That sounds good to me. Do you want to take at refining this issue given that or would you like me to?

**Comment by tadhg-ohiggins** [comment]
@petermarks-gsa my refinement would essentially be replacing the current description with the contents of my comment, creating a new issue for changing UEI-related fields, and moving a lot of the current description into the description of that new issue. I'm not sure on how that relates to what #185 expects from this issue, however; do you think you need to change #185 if we do take this approach?

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins I've minimized the scope of this issue to the tasks you laid out and created a separate story for the UEI-related fields that needs scoping: https://github.com/GSA-TTS/FAC/issues/402

I'm going to remove the needs refinement label for this issue.
