### ISSUE TITLE
design homepage for implementation based on sprint 6 research insights

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#288]
Breakout issue of #274 

**Background**
[Sprint 6 research -  observations/refinements by page](https://docs.google.com/document/d/1Y8g7HEd6eysBQjg3x_-K3nzk9M9xBCp5w8eZXql_8xQ/edit#heading=h.ycduc4d91ltn)

**Observation(s)**
- Most people understood that they could access historical data via the legacy Census system; one person felt that this was unclear and would prefer to be able to search from the new FAC homepage. 
- One  person expected to find links back to the legacy FAC under “resources.”
- The 2 different CTAs for logging in confused folks. People wondered whether they would lead to the same or different places. While several participants commented on this, the severity was very low--every participant successfully proceeded from the homepage to the next step in submitting an audit. 

**MVP recommendation(s)**
- Consider making the copy of the two CTAs that take folks to sign in a bit more consistent. 

**Tasks**
- [x] Review sprint 6 research analysis
- [x] Create checklists for refinement needed to each page
- [x] Update #274 with the checklist of refinements needed
- [x] Make refinements
- [x] Peer review

**Definition of done**
**Acceptance Criteria (We'll know we're done when...)**
- [x] Screens in Figma are ready to be handed off to front end
- [x]  All text has a contrast ratio of 4.5:1 with the background
- [x]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by austinhernandez** [comment]
![Audit home Page](https://user-images.githubusercontent.com/23194720/176722350-25449d02-7e75-4895-8dbb-1df28403c1e3.png)

Questions for peer reviewers (@MelissaBraxton @melchoyce @sreuber) :

- This page had minimal updates, just looking for thoughts on the CTAs "Sign in to access (my) audit submissions" ?? 
- Happy to wait for a content designer on *final* text, but is this good?
 

Implementation note (@heymatthenry): 
- Secondary navigation is still underworks
- Both "sign in to access..." links will take you to the login.gov/modal flow on #290 
- There's not a content designer so the text is subject to change, but the functionality should be good once I get design feedback.

**Comment by austinhernandez** [comment]
@sreuber i'm using login.gov's recommendation of "sign in" as the call to action. [https://github.com/GSA-TTS/FAC/issues/259](https://www.figma.com/exit?url=https%3A%2F%2Fgithub.com%2FGSA-TTS%2FFAC%2Fissues%2F259)

**Comment by melchoyce** [comment]
> This page had minimal updates, just looking for thoughts on the CTAs "Sign in to access (my) audit submissions" ??

Is this section called "My audit submissions" once you're logged in?

I'd probably avoid adding a pronoun here like you've done in the button, based on some recommendations here that originally came from Microsoft: https://ux.stackexchange.com/questions/4348/your-vs-my-in-user-interfaces. There doesn't feel like a strong need to use pronouns in this interface at all, IMO.

**Comment by MelissaBraxton** [comment]
@melchoyce and I chatted about Mel carrying this forward while @austinhernandez is out.

**Comment by melchoyce** [comment]
![image](https://user-images.githubusercontent.com/2846578/177416067-31edfa14-69a1-4727-802b-d0a15857598b.png)

@MelissaBraxton @sreuber Does this page need anything else?

**Comment by MelissaBraxton** [comment]
@melchoyce I don't think so!

**Comment by sreuber** [comment]
@melchoyce @MelissaBraxton Looks good to me. I don't mean to throw a wrench in the works but did we want to add something about UEI here, even if it's just a line of copy somewhere?

**Comment by petermarks-gsa** [comment]
@melchoyce @austinhernandez could you please point me to where this lives in Figma + any implementation notes and I'll make an implementation task for this?

**Comment by melchoyce** [comment]
Hey @petermarks-gsa! This lives here: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=2443%3A10612

I have one question regarding implementation I've asked the other designs. When I hear back, I'll update the Figma page to include that information.

**Comment by melchoyce** [comment]
Implementation notes added!

**Comment by petermarks-gsa** [comment]
@melchoyce @austinhernandez Seems like navigation / header changes are in scope for this issue? Possible to get designs + design notes on the logged in state of the navigation? I've seen some designs floating around that show the logged in username + "Logout" link.

**Comment by melchoyce** [comment]
I'll take a look!

**Comment by petermarks-gsa** [comment]
@melchoyce Understood that the navigation as a whole needs to be tested. I'll create an implementation issue for just homepage copy updates? 

We're taking on permissions related engineering tickets in the next milestone and it would be really handy to have a "logged in as" and "logout" link for testing, so we may just implement those without a final design.

**Comment by melchoyce** [comment]
> I'll create an implementation issue for just homepage copy updates?

Sounds good 👍 

> We're taking on permissions related engineering tickets in the next milestone and it would be really handy to have a "logged in as" and "logout" link for testing, so we may just implement those without a final design.

Also makes sense to me. @MelissaBraxton any issues with this?

**Comment by MelissaBraxton** [comment]
Sounds good!

**Comment by petermarks-gsa** [comment]
@melchoyce Here is the implementation issue for homepage updates: https://github.com/GSA-TTS/FAC/issues/358

And here is the issue for logout: https://github.com/GSA-TTS/FAC/issues/359

**Comment by melchoyce** [comment]
Re-opening this with some design suggestions based on the copy updates in #380:

![image](https://user-images.githubusercontent.com/2846578/182418094-68733fb2-2ca4-43e9-9fd8-58484920b6ea.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4148%3A19746)

Ready for peer review @austinhernandez @sreuber

**Comment by austinhernandez** [comment]
looks great! as long as there is a disclaimer that this is the copy we will be testing :D

**Comment by melchoyce** [comment]
Great point, added a note. @petermarks-gsa this is ready to pass on.

**Comment by petermarks-gsa** [comment]
@melchoyce Great, I've updated https://github.com/GSA-TTS/FAC/issues/358 with latest figma link and implementation notes.
