### ISSUE TITLE
🅢 design of disclaimer text for implementation based on sprint 6 research insights

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#289]
Breakout issue of #274 

**Background**
[Sprint 6 research -  observations/refinements by page](https://docs.google.com/document/d/1Y8g7HEd6eysBQjg3x_-K3nzk9M9xBCp5w8eZXql_8xQ/edit#heading=h.ycduc4d91ltn)

**Observation(s)**
- People were thrown off by seeing two disclaimers prior to creating a new submission. 

**MVP recommendation(s)**
-  Show the disclaimer only one time prior to users creating a new submission. . 
- The disclaimer should appear prior to logging in. That way folks who may work on multiple submissions during a session will not see this more than once. 

**Tasks**
- [x] Review sprint 6 research analysis
- [X] Create checklists for refinement needed to each page
- [X] ~Update #274 with the checklist of refinements needed~ (N/A)
- [x] @erinzstrenio & @melchoyce to touch base with other GSA services to find out what disclaimer text they use
- [ ] @erinzstrenio to draft updated disclaimer text
- [ ] Peer review of disclaimer text
- [ ] Set up conversation with GSA OGC to review disclaimer text

**Definition of done**
**Acceptance Criteria (We'll know we're done when...)**
- [ ] Screens in Figma are ready to be handed off to front end
- [ ]  All text has a contrast ratio of 4.5:1 with the background
- [ ]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment]
I'm assigning myself to this while @austinhernandez is out. no changes to mocks needed, but I need to add some implementation notes.

**Comment by MelissaBraxton** [comment]
@heymatthenry - There's one small front end change needed here -  We'll want to wire up the primary "log in to submit an audit"  CTA on the homepage to show this disclaimer (in addition to it being triggered by the "login" button on the top nav).

**Comment by austinhernandez** [comment]
I wanted to clarify for @heymatthenry and flag this for @erinzstrenio cuz this was closed when I was out sick. 

During the usability tests, there was confusion for users around why there were 2 places where there was disclaimer text. The first one appears before you hit the login.gov screen to submit an audit. The second appears before you start a new audit. However, they are 2 different disclaimers that might _need_ to be there. (This is where I am not sure and we would have to confirm with someone - Census?)

**"Warning" text:** Firstly, there's also a lot of ... words ... lol at the top of the login screen about how this is being used? What it is? IDK if this needs to be on the screen before you are redirected to login.gov
> 0MB Control Number: 0607-0518 
> Approval Expires: February 28, 2025
> The Internet Data Entry System (IDES) is the place to submit the single audit reporting package, including form SF-SAC, to the Federal Audit Clearinghouse (FAC). Single audit submission is required under the Single Audit Act of 1984 (amended in 1996), and the Office of Management and Budget (0MB) Title 2 U.S. Code of Federal Regulations (CFR) Part 200, Uniform Administrative Requirements for Federal Awards (Uniform Guidance). 
> YOUR RESPONSE IS REQUIRED BY LAW. Title 31 United States Code (U.S.C.), Section 7501 et. seq., and 2 C.F.R. Part 200 authorize this collection. 31 U.S.C. 7502(h) and 2 C.F.R.200.512(d) require your response. The provisions set forth in 31 U.S.C. 7502(h) and 2 C.F.R. 200.512(9) require the information provided be made publicly available, and therefore not given confidential treatment, with the following exception: 2 C.F.R. 200.512(b)(2) states that Indian Tribes and Tribal Organizations are exempt from having their reporting package made publicly available. 
> This collection has been approved by the Office of Management and Budget (0MB). The eight-digit 0MB approval number is 0607-0518 and appears at the upper right of this screen. Without this approval, we could not conduct this survey. 
<img width="895" alt="Screen Shot 2022-07-20 at 1 29 21 PM" src="https://user-images.githubusercontent.com/23194720/180048034-4fdebeed-8e0c-4a2d-9380-d85b2cb4aa69.png">


**Disclaimer text 1 / U.S. Census Bureau Notice and Consent Warning:** Then there's the "disclaimer text" you have click to acknowledge reading before you login into the system:
> U.S. Census Bureau Notice and Consent Warning 
> You are accessing a United States government computer system. This United States government computer system is provided for the collection of the single audit reporting package and form SF-SAC as required under the Single Audit Act of 1984 (amended in 1996) and the Office of Management and Budget (0MB) Title 2 U.S. Code of Federal Regulations (CFR) Part 200, Uniform Administrative Requirements for Federal Awards (Uniform Guidance). 
> Use of this system indicates your consent to collection, monitoring, recording, and use of the information you provide for any lawful government purpose. So that our network remains safe and available for its intended use, network traffic is monitored to identify unauthorized attempts to access, upload, change information, or otherwise cause damage to the web service. Use of a government computer network for unauthorized purposes is a violation of federal law and punishable by fines or imprisonment (Public Law 99-474). 
> Collecting data on behalf of 0MB. Version: 1.4.14.0 Last Modified: February 09, 2022 
> If you need assistance, please contact us. 
> If you are experiencing technical issues, please ensure that you are using the latest version of your web browser, or try visiting our website using a different browser (Internet Explorer, Mozilla Firefox, Google Chrome, etc.). 
<img width="880" alt="Screen Shot 2022-07-20 at 1 29 09 PM" src="https://user-images.githubusercontent.com/23194720/180046799-f70cd588-842f-4bc0-9259-78e7c6b2f1c4.png">


**Disclaimer text 2 / Compliance Supplement:** Lastly, there's the text when you click "submit a new audit" (you dont need to do this every time you open an existing audit
> On September 20, 2019, the 0MB issued a corrected edition of the 2019 Compliance Supplement (Supplement) which is dated August 2019 and replaces the previously released edition dated June 2019. For Single Audits subject to the 2019 Supplement (i.e., audits of fiscal years beginning after June 30, 2018), auditors are permitted to perform the audit using either the June 2019 or August 2019 edition of the Supplement for reports dated on or before October 31, 2019. Please document the version of the Supplement that is used for the audit. Auditors are required to perform the audit using the August 2019 edition for reports that are dated after October 31, 2019. The August edition of the 2019 Supplement can be accessed on the 0MB Website. An "Errata Page" inserted after the Table of Contents describes the changes made. 
> If you have questions about this notice or the corrected edition of the 2019 Supplement, you may contact the relevant agency National Single Audit Coordinator using the contact information found in Appendix Ill of the Supplement. 

<img width="936" alt="Screen Shot 2022-07-20 at 1 28 42 PM" src="https://user-images.githubusercontent.com/23194720/180045673-a3795ebb-8db8-461b-9ae0-eee4d2e9f4ca.png">

**Comment by austinhernandez** [comment]
Yes, let's def raise on the census sync call for a definitive answer (ive been punting on this one) waiting for someone like yoouuuuuuu 🎵

**Comment by erinzstrenio** [comment]
We reached out to Scott at Census to ask if the disclaimer text is required he said the following: 

"I don't believe any of the disclaimer text is mandatory from a Uniform Guidance requirements perspective.  I believe all disclaimer text is present to satisfy Census Policy and Census IT security requirements/controls.  I would think all disclaimers on the Census FAC websites could be added/removed/edited on the GSA FAC to meet whatever GSA Policy standards are relevant."

@melchoyce and I are going to connect with other teams within GSA (see list below) that collect data and disseminate it and find out if they have any disclaimers in place. Once we do more research there, we can put together recommended disclaimer text for the FAC and then meet with GSA OGC to get approval. “This is how we saw it done in these other 2-3 places, and we think we might want to do XYZ for the FAC." cc @jadudm  

USA.gov - Erin
vote.gov - Erin
FedRAMP - Erin
cloud.gov - Mel
cloud.gov Pages - Mel
search.gov - Mel

**Comment by erinzstrenio** [comment]
Updated the tasks above cc @melchoyce

**Comment by melchoyce** [comment]
## cloud.gov

Small text warning with a "more details link," which opens a modal with the full text. Only option in the modal is "hide details." Accepting leads to cloud.gov's government login.

| Warning | T&S | Login |
| ------------- | ------------- | ------------- |
| ![Screen Shot 2022-07-26 at 4 59 34 PM](https://user-images.githubusercontent.com/2846578/181111558-74ab7e3f-f0e7-4fe1-98a8-dec8acc641fb.png) | ![Screen Shot 2022-07-26 at 4 59 54 PM](https://user-images.githubusercontent.com/2846578/181111561-bf1a2c2a-b550-4e03-aba6-52ef79baaf7e.png) | ![Screen Shot 2022-07-26 at 5 00 05 PM](https://user-images.githubusercontent.com/2846578/181111564-7fe3e5bb-cd2d-4040-ab20-83ebd995d98b.png) |

## federalist/cloud.gov pages

A small warning with a "more details" link that leads to a T&S page in the same window. (No link back.) Accepting leads to Github.

| Warning | T&S Page |
| ------------- | ------------- |
| ![Screen Shot 2022-07-26 at 5 00 48 PM](https://user-images.githubusercontent.com/2846578/181111932-c7699020-a174-49e0-8c6f-3236dc820e69.png) | ![Screen Shot 2022-07-26 at 5 01 05 PM](https://user-images.githubusercontent.com/2846578/181111937-c9c03ea1-671c-491a-857a-ce22de67afc5.png) |

## search.gov

Full (small) warning page. No additional details. Accepting leads to login.gov.

| Warning | Login |
| ------------- | ------------- |
| ![Screen Shot 2022-07-26 at 5 01 24 PM](https://user-images.githubusercontent.com/2846578/181112155-d9a83db6-fe89-40f1-8b3e-e76ec3ca1913.png) | ![Screen Shot 2022-07-26 at 5 01 43 PM](https://user-images.githubusercontent.com/2846578/181112153-29304f65-1cce-4d8f-9330-d03368576f80.png) |

**Comment by erinzstrenio** [comment]
## usa.gov and vote.gov 

Neither of these two sites collects information from people beyond emails for email subscription, so this is the only disclaimer text they provide (as far as I could tell). 

<img width="1042" alt="Screen Shot 2022-07-26 at 4 23 02 PM" src="https://user-images.githubusercontent.com/46569779/181115088-9489b70b-6268-4c33-9e4a-722fd3a9120c.png">
<img width="762" alt="Screen Shot 2022-07-26 at 4 23 30 PM" src="https://user-images.githubusercontent.com/46569779/181115091-d8ec686a-4afe-420f-922e-02e51262a8c4.png">

**Comment by melchoyce** [comment]
Based on our research, I think [Austin's approach here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3341%3A15650) works. It's pretty much exactly how cloud.gov handles their terms, and improves on the pattern by allowing someone to accept and proceed straight from the modal as well.

**Comment by erinzstrenio** [comment]
I agree that Austin's approach looks good, and I updated the text to more closely mimic the disclaimer text found on cloud.gov and other GSA services — [here's the updated disclaimer text.](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#heading=h.x0twed3s3rwi) There seemed to be a lot of unnecessary jargon on the Census disclaimer text (but we shall see what OGC says).

**Comment by melchoyce** [comment]
The updated text seems nice and succinct. 

@austinhernandez anything else we need to do before moving this on to dev? I figure we can get it moving while working on getting the disclaimer text approved.

**Comment by petermarks-gsa** [comment]
@melchoyce Just to make sure I understand, the disclaimer text we're talking about here is the "Federal Audit Clearinghouse terms and conditions" copy in the [modal](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3341%3A15489) that is viewable when you click "submit an audit" in nav or "start a new submission" on the "my audit submissions" page?

**Comment by melchoyce** [comment]
> @melchoyce Just to make sure I understand, the disclaimer text we're talking about here is the "Federal Audit Clearinghouse terms and conditions" copy in the [modal](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3341%3A15489) 

Correct.

> ...that is viewable when you click "submit an audit" in nav or "start a new submission" on the "my audit submissions" page?

It's been updated now to _only_ show when you click the link in "I agree to the above terms and conditions" on the My Audit Submissions page:

![image](https://user-images.githubusercontent.com/2846578/182695541-7bc13f92-5694-4cea-ae14-1679b8223f1c.png)

**Comment by petermarks-gsa** [comment]
@melchoyce Gotcha. I've created an implementation ticket [here](https://github.com/GSA-TTS/FAC/issues/424). Is it fair to assume people should see that modal regardless of whether they click the "I agree to the above" checkbox, or should they see some sort of error?

**Comment by melchoyce** [comment]
Good catch—the "start a new submission" button should be disabled until you check "I agree."

**Comment by petermarks-gsa** [comment]
@melchoyce Thanks for the clarification, I've updated the acceptance criteria. 

@tadhg-ohiggins For transparency, I've created a front end implementation issue for this that seems limited in scope: 

https://github.com/GSA-TTS/FAC/issues/424

I've listed it as a related task for this issue: 

https://github.com/GSA-TTS/FAC/issues/391

**Comment by melchoyce** [comment]
Head's up, this has been updated with [new copy](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#heading=h.x0twed3s3rwi) from @erinzstrenio:

![image](https://user-images.githubusercontent.com/2846578/186259256-ed0b4b1f-5ff4-4642-b6af-f3cfc7684ed9.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3341%3A15489)
