### ISSUE TITLE
design login.gov flow for implementation based on sprint 6 research insights

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#290]
Breakout issue of #274 

**Background**
[Sprint 6 research -  observations/refinements by page](https://docs.google.com/document/d/1Y8g7HEd6eysBQjg3x_-K3nzk9M9xBCp5w8eZXql_8xQ/edit#heading=h.ycduc4d91ltn)

**Observation(s)**
- While most people were not familiar with Login.gov, it sparked few concerns. 
- A few people wondered whether their login info for the legacy FAC could be used to log in to the new FAC. 
- One person was confused by the Q re: whether they were a federal employee, but this is part of Login.gov’s flow and is outside the scope of our work (in addition to it not being a prevalent issue among participants).

**MVP recommendation(s)**
- Consider adding content that makes it clear to users that their Census FAC credentials are not what they’ll use to access the new system. Possible placement for this content  - on the Login.gov login page itself or via a modal triggered on clicking “sign in” before they’re taken to Login.gov. 

**Tasks**
- [x] Review sprint 6 research analysis
- [x] Create checklists for refinement needed to each page
- [x] Update #274 with the checklist of refinements needed
- [x] Make refinements
- [x] Peer review

**Definition of done**
**Acceptance Criteria (We'll know we're done when...)**
- [x] Screens in Figma are ready to be handed off to front end
- [x]  All text has a contrast ratio of 4.5:1 with the background
- [x]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by heymatthenry** [comment]
@austinhernandez I wouldn't count on language settings from the FAC carrying over to Login but we can look into that further.

**Comment by melchoyce** [comment]
> The forgot password page seems like a good, relevant place to put this info but is it too heavy handed?

It doesn't feel heavy-handed to me — I think it's a good "just in case" for someone who may not have read the message the first time and is like "but why isn't my password working." I might even bold it there, too.

> Let's check in after implementation so I can see what the latest version of the login screen looks like! Maybe there are text formatting options that I'm unaware of that would make the help text less bulky

If this is an option, I think it would help!

**Comment by melchoyce** [comment]
Made the two minor adjustments based on the above conversations:
- Put "You cannot use Census FAC credentials to access the new system" on its own line.
- Bolded the sentence.

Additionally, I checked on the latest Login.gov styles and updated the mockups to reflect the current layout:

## Login.gov screen with logo and information

![image](https://user-images.githubusercontent.com/2846578/177597265-10e738a6-b911-4890-9026-617068e4f018.png)

## Forgot password screen

![image](https://user-images.githubusercontent.com/2846578/177596883-a71394fc-0a18-444f-a5a1-ee3948bd23df.png)

**Comment by MelissaBraxton** [comment]
@melchoyce  - LGTM! I think we can move this to "in review." 
@petermarks-gsa do we need to create new issues for implementation?

**Comment by petermarks-gsa** [comment]
@MelissaBraxton @melchoyce  Let's create an implementation issue for this. Can you please link to designs and any implementation notes in figma?

**Comment by melchoyce** [comment]
This lives here: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3136%3A18520

I'll update the page with implementation notes tomorrow 👍

**Comment by melchoyce** [comment]
Added implementation notes to that page. Please let me know if you have any questions!
