### ISSUE TITLE
Allow users to enter lowercase UEIs

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2928]
### Background

Our JSON Schema requires uppercase UEIs; we don’t uppercase them when the user initiall submits on the frontend, and we don’t validate initially to check for uppercase, but the auditee info form will fail silently at JSON Schema validation and not give the user any feedback.

We should change this to be better.

### Acceptance Criteria (We'll know we're done when...)

- [ ] Users can submit valid UEIs that have lowercase letters.

### Tasks

- [ ] Change the backend; this may be as simple as changing the trailing `,`at the end of https://github.com/GSA-TTS/FAC/blob/main/backend/report_submission/views.py#L68 to instead be `.upper(),`.
- [ ] Change the frontend to uppercase the UEI when the user enters it or validates it, so that the user sees the change.
