### ISSUE TITLE
Write up trade-offs re: replacing in-app certification with signatures on pdf audit reports 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#293]
**Background**
We are considering whether we can replace in-app cert with signed pdfs. 

**Acceptance Criteria (We'll know we're done when...)**
- [ ] We have a document that lays out the tradeoffs (including user impacts) of removing the in-app certify steps and requiring signed pdfs instead. 

**Tasks**
- [ ] Mock up (this work is covered under #321 
- [ ] Consult #319 
- [ ] Write up 1 page doc. that facilitates a product decision on whether to replace in-app cert with signed pdfs.

**Comment by MelissaBraxton** [comment]
@petermarks-gsa - Is this still needed?
