### ISSUE TITLE
Record transformations in MigrationChangeRecord table

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#2950]
When a migration completes successfully,
update MigrationChangeRecord table with information about the transformations performed.

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/3040
- [ ] https://github.com/GSA-TTS/FAC/issues/3046
- [x] https://github.com/GSA-TTS/FAC/issues/3047
- [ ] https://github.com/GSA-TTS/FAC/issues/3048
- [ ] https://github.com/GSA-TTS/FAC/issues/3056
```
