### ISSUE TITLE
PRA Approval 

### ISSUE THREAD

**Issue by jhansen-flexion** [GSA-TTS/FAC#296]
[**Background**

<<background>>
](https://pra.digital.gov/)
It covers the following stories:

1. As an ...

**Acceptance criteria (We'll know we're done when...)**
- [ ] When a user can ...
  
**Tasks**
- [ ] Design designs all the things
- [ ] Engineering engineers all the things

**Definition of Done**

- [ ] Meets acceptance criteria
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.
