### ISSUE TITLE
RESEARCH SPIKE: find out the impact of replacing in-app certification with signed pdfs

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#298]
**Background**
We are considering whether we can replace in-app cert with signed pdfs. This issue is blocking #212 and #260. 

**Acceptance Criteria (We'll know we're done when...)**
- [ ] We have a document that lays out the tradeoffs (including user impacts) of removing the in-app certify steps and requiring signed pdfs instead. 

**Tasks**
- [ ] Write research Qs
- [ ] Write research plan
- [ ] Carry out research
- [ ] Write up 1 page doc. that facilitates a product decision on whether to replace in-app cert with signed pdfs.

**Comment by melchoyce** [comment]
Is this still relevant?
