### ISSUE TITLE
RESEARCH SPIKE: find out the impact of delaying notes to SEFA and secondary auditor data collection

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#299]
Breakout issue of #274 

**Background**
We are considering whether we can delay launching data collection for a few of the existing SF-SAC form section - **notes to SEFA** and **secondary auditors** pages. Issue #274 is somewhat dependent on us deciding on this, as the current SF-SAC form includes these sections, and the navigation also includes these options. 

**Acceptance Criteria (We'll know we're done when...)**
- [ ] We have a document that lays out the tradeoffs (including user impacts) of including/excluding these sections in the MVP

**Tasks**
- [ ] Write research Qs
- [ ] Write research plan
- [ ] Carry out research
- [ ] Write up 1 page doc. that facilitates a product decision on whether to include these pages in MVP

**Comment by MelissaBraxton** [comment]
Hey there, @petermarks-gsa - Per our discussion on 7/6, We are de-prioritizing this, so I moved it down in the backlog. I created new issue https://github.com/GSA-TTS/FAC/issues/326 to track that we'll need to make some design decisions about what's currently in the side nav and how we'll message this deviation from the expected data collection to folks. Also flagging that this may impact our PRA application.
