### ISSUE TITLE
design "Create New Audit: 1. Criteria Check" page for implementation based on sprint 6 research insights

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#301]
Breakout issue of #274 

**Background**
[Sprint 6 research -  observations/refinements by page](https://docs.google.com/document/d/1Y8g7HEd6eysBQjg3x_-K3nzk9M9xBCp5w8eZXql_8xQ/edit#heading=h.ycduc4d91ltn)

**Observation(s)**
- While the questions themselves were easy for folks to answer, the purpose of these Qs wasn’t always clear to folks, but this didn’t bar them from continuing. 
- A few users asked whether the $500K threshold regarding the OMB circular A-133 is still relevant, and this tripped them up. 
- A few users wondered what would happen if you selected “No” for either of the second and third questions.
- Several users indicated confusion over the “unknown” field in the first question. 

**MVP recommendation(s)**
- We should remove the “$500,000 or more during its audit period in accordance with OMB circular A-133” portion of the second question if possible (do we need clarification if there are reasons why this is here?). 

**Future improvements**
- Consider adding content that better explains the purpose of these questions as checking that they need to submit a single audit and barring them from doing so if their entity doesn’t need to submit a single audit. 
- Determine if or why the Yes/No questions are necessary.

**Tasks**
- [x] Review sprint 6 research analysis
- [x] Create checklists for refinement needed to each page
- [x] Update #274 with the checklist of refinements needed
- [x] Make refinements
- [x] Peer review

**Definition of done**
**Acceptance Criteria (We'll know we're done when...)**
- [x] Screens in Figma are ready to be handed off to front end
- [x]  All text has a contrast ratio of 4.5:1 with the background
- [x]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Captured in this task: https://github.com/GSA-TTS/FAC/projects/1#card-84116842
