### ISSUE TITLE
Record sac_general_lib transformations

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3046]
Record transformations in the following files by updating the transformations list in result.  Store transformations in MigrationChangeRecord table.
```[tasklist]
### Tasks
- [x] audit_information.py
- [x] general_information.py
- [x] sac_creator.py
- [x] utils.py
```
