### ISSUE TITLE
Updating top nav "Sign in" button and copy

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3051]
### Background

The current "Sign in" button on the top navigation is too large/dark so it scales poorly. It states "Sign in - Submit and review your audits." This copy is confusing for users who need to sign in to view tribal search results. 

![Screenshot 2023-12-20 at 10 21 33 AM](https://github.com/GSA-TTS/FAC/assets/119363060/b47cd85f-ea4f-48a6-a55a-3f7fa1ad5df2)

We want to replace the current "Sign in" and "Sign out" button with this simplified design, and remove the "submit and review your audits" copy from the button: 

![Screenshot 2023-12-20 at 10 27 56 AM](https://github.com/GSA-TTS/FAC/assets/119363060/ee1c2804-48d3-4fe7-9486-28b493998ace)
![Screenshot 2023-12-20 at 10 30 00 AM](https://github.com/GSA-TTS/FAC/assets/119363060/e692a91e-814b-453f-961e-b0cd2844a648)

### Acceptance criteria (We'll know we're done when...)

- [ ] Frontend has implemented the revised design as shown in the mockup to the static site and app top navigation 
  
### Tasks

- [x] Design mocks up the revised "Sign in" button
- [ ] Frontend implements the revised design and copy as shown in the mockup to the static site and app top navigation

**Comment by Leighdiddy** [comment]
@jperson1 Changes are documented in Figma, let me know if you need additional mocks!

**Comment by Leighdiddy** [comment]
@jperson1 This revision is no longer needed with the upcoming top nav full redesign
