### ISSUE TITLE
How-to page for accessing tribal audits in search results

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3052]
### Background

We have implemented protected tribal audits in our search results database, and users have shared that it's unclear how to access them through our current site navigation. We will build and share a brief "how-to" page to walk the user step by step through signing in and accessing tribal search results. The page will not be directly linked from our current top navigation. It will be linked from our [site updates](https://www.fac.gov/info/updates/) page, available to share from the help desk, and used for future stakeholder communications. 

### Tasks

- [x] Content prepares general explainer text around tribal audits
- [x] Content prepares step-by-step instructions to access tribal audits in search results starting from the home page
- [x] Design creates step-by-step images to illustrate instructions using screen grabs from the current site
- [x] The page is pushed live by content
- [x] The new page is shared with the help desk and linked from the Updates page

### Acceptance criteria (We'll know we're done when...)

- [x] We have built the new "How-to" tribal page and pushed it live
- [x] The new page is linked it from the updates page (12/11/23 update announcing tribal access) and shared with the help desk

**Comment by lauraherring** [comment]
Page is built and [PR](https://github.com/GSA-TTS/FAC-transition-site/pull/71) submitted
