### ISSUE TITLE
Offboarding checklist for @leo_fotovich

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3092]
# For everyone

- [x] Remove from [the FAC-team Google Group](https://groups.google.com/a/gsa.gov/g/fac-team/members)
- [x] Remove from [the FAC team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members)
- [x] Remove from the private channel #oros-fac-private in Slack (“/remove @[person]”)
- [x] Transfer Zendesk license to another FAC user
- [x] Remove from Slack?
- [x] Remove from other Google Groups (test-user, etc.)
- [x] Check that drive sharing is disabled by removal from GGroups
    - [x] Remove from fac@gsa.gov (which might be by Google Group)
- [x]  Set up recurring checkin/coffee (so we have something to cancel/bump around)
- [ ]  Do a brief coffee followup on keep/change/add/throw away from experience
