### ISSUE TITLE
Walkthrough min. viable roadmap and align on sprint 1/2 priorities. 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#31]
**Background**

**We'll know we're done when...**
- [x] We have at least placeholders for sprint 1 and maybe 2 epics on the board. 

**Tasks**
- [x] Walk through [roadmap](https://app.mural.co/t/gsa6/m/gsa6/1646336450605/6a77a27a287989f91e1c0dfbcf9be4dec6e49393?sender=melissabraxton2796) as a team. 
- [x] Schedule time for Matt and Melissa to co-work
- [ ] Create new issue template for design/dev work
- [x] Add sprint 1 issues
