### ISSUE TITLE
[Epic] Site status notification system (SSNS)

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3107]
How do we easily notify users about site issues on both the static site and the app?

* Notify users of issues that are "in the moment"
* Issues that are ongoing

We should be able to: 
* Turn notifications on/off without having to deploy the app.
* Add more detailed information about the incident.
  * Follow a link to find more information
  * Information might be on the static site or might be somewhere else
* Find and follow internal docs/procedure to:
  * Decide if it is an incident (what is the threshold). This could follow service alerts, help desk traffic, or some combination of all.
  * Turn alert on/add more info
  * Decide when an incident is resolved (how do we define resolution)

```[tasklist]
### Tasks
- [ ] Investigate ways to use Django to conditionally display a banner and maybe fetch data
- [ ] Investigate ways to use the static site to conditionally display a banner and maybe fetch data
- [ ] Draft internal docs, including some basic definitions for starter thresholds 
```
