### ISSUE TITLE
Submission guide

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3108]
```[tasklist]
### Timeline
- [ ] Late January: Outline the work to be done
- [ ] Mid-February: Stand up initial refinements to documentation
- [ ] Late Feb/Early March: Complete submission guide revisions
```

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/3140
``` 

## Background

The FAC has MVP-style support for submissions. In bringing forward Census documentation, we simplified; in some cases, so much so that auditors are asking about missing examples/guidance becuase *it was guidance*. It shaped what they did, why they did it, and (in some cases) helped guarantee data quality.

Or: our submission documentation is part of how we both help users understand what to do and when, as well as make clear what they must do in order to adhere to policy and data quality expectations. 

Our goal is to shift knowledge hard-earned through HD support into persistent documentation on fac.gov that can guide users through submissions, resolve their own issues/challenges without asking for support, and improve the quality of the data they submit.

## Story: Bopping along

I'm an auditor familiar with the previous process, but not so much so that it is what I "expect." I find the checklist to be clear, the workbooks align closely enough with my expectations that I'm OK, but when I go to submit, I find the error messages a bit unclear. I go straight to the helpdesk.

*Should we have links from errors to documentation in the site so that an auditor can click on the error and get support with resolving the issue themselves? Should our error messages be revisited to be more action-oriented, guiding users more clearly to solutions in all cases?*

## Story: Stuck in a rut

I have been submitting SAs for the past 15 years, and as an auditor, I want my MTV. I don't know why I can't print a DCF (and I don't like it), I don't know why I don't get my SEFA auto-generated, I don't know why GSA can't send emails, and all of this frustrates me to no end. In my frustration, I see every difference as an annoyance, and the fact that the documentation has so little to say is icing on the cake. I may have asked some questions in ALL CAPS in the help desk.

At this point, while I just want the things I want, I would appreciate some guidance and best practices. If you're not going to email everyone, could you at least say that up front, so I know I need to shift my practices? And, could you provide me with a guide so I know what to do each step of the way to work around your incomplete system so I can get all of this work done on time? Like... what else do I need to watch out for?

**Comment by jadudm** [comment]
@danswick , @lauraherring , as I pivot out of the room, this is an epic that perhaps wants to be reworked/rewritten. It isn't tracking anything well, I don't think.

**Comment by jadudm** [comment]
Done. Published.
