### ISSUE TITLE
Top-nav card sort round 2

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3109]
### Tasks

```[tasklist]
- [x] https://github.com/GSA-TTS/FAC/issues/3149
- [x] https://github.com/GSA-TTS/FAC/issues/3150
- [ ] https://github.com/GSA-TTS/FAC/issues/3151
- [ ] https://github.com/GSA-TTS/FAC/issues/3152
- [ ] https://github.com/GSA-TTS/FAC/issues/3153
- [ ] https://github.com/GSA-TTS/FAC/issues/3154
- [ ] https://github.com/GSA-TTS/FAC/issues/3155
- [ ] https://github.com/GSA-TTS/FAC/issues/3156
- [ ] https://github.com/GSA-TTS/FAC/issues/3157
- [ ] https://github.com/GSA-TTS/FAC/issues/3158
- [ ] https://github.com/GSA-TTS/FAC/issues/3159
```
