### ISSUE TITLE
Improved 500 errors at certification

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3118]
### Mini story

An auditee is in the system, clicks "lock for certification," and  then goes on to the auditor certification page. We could, at that point, say "You are an auditee, and this is the auditor certification. You should reach out to <email address> and inform them that <report-id> is ready for auditor certification."

Same for auditor hitting auditee.

There's also a strange case we might try and catch on auditor/auditee certification.

1. The user was listed as a certifying official *and* editor.
2. They log in.
3. Someone removed them as a certifying official.
4. They were still logged in. (Or, logged out and back in. We don't know.) But, they can log in and see the audit, because they are an edito.
5. They try to certify, and cannot. Why? Because they are an editor.
6. They realize they are no longer a certifyer, so they add themselves back.
7. They are logged in, but this change would not be detected. So, after adding themselves back as a certifying official, they still cannot certify their audit, and therefore get 500 errors.

The fix would be to log out and log back in again. Ideally, we would provide a message of some sort that suggests this if we're able to query some status in DeletedAccesses, or Accesses... that might imply that something akin to this case happened. Or, perhaps, we just always suggest logging out and back in as a way to make sure changes to certifying officials have taken effect.

We might want to also do that on the manage access page (include text that says "if you make changes, the users involved will need to log out and log back in again.)

2023-06-GSAFAC-0000005261 may be an example of an audit where the edge case came to be.

(These may be 403s, not 500s.)

### Tasks
```[tasklist]
- [ ] Catch auditors trying to go to the auditee cert page, and provide a better error (vs. a generic 500).
- [ ] Catch auditees trying to go to the auditor cert page, " "
- [ ] Catch the edge case described above.
- [ ] Update copy on the manage access page to advise logout/login for all users whose roles/status were changed.
```

**Comment by jperson1** [comment]
The generic error page (`/backend/templates/{err_code}.html`) will show an error message, if we provide it. As of now, accessing a certification page as the wrong/opposite role will display a "bad role" error message on the 403 page. 

An easy step is to update that message to be more helpful when we boot a user for having the wrong role. See: https://github.com/GSA-TTS/FAC/blob/265a1d2f99aec32372a4fbeea361a87487458f97/backend/audit/mixins.py#L68
We can instead say something like "You are not the Certifying Auditee Contact".

**Comment by jadudm** [comment]
Done. Closing.
