### ISSUE TITLE
Stand up public cloud.gov demo site

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#314]
### Background

We need a site for showing backend progress. This is part of the walking skeleton process of getting a public site out there. 

### Acceptance Criteria (We'll know we're done when...)

- [x] We have a cloud.gov space with appropriate memberships/permissions.
- [x] We have a publicly-accessible instance of the backend running in cloud.gov.

### Tasks
- [x] Figure out space creation/permissions.
- [x] Add automated deployment to GitHub workflow so that `main` branch gets automatically pushed to cloud.gov.
- [ ]   Bonus: stable URL?
- [ ]   Document process.

**Comment by heymatthenry** [comment]
[Stable link to `main` deployed to Federalist](https://federalist-9a617ff8-042d-4076-9581-bb999f9c6639.app.cloud.gov/site/gsa-tts/fac-frontend/).

There's also a note about this in the README for FAC-Frontend. GSA-TTS/FAC-Frontend@2dbf04b

**Comment by tadhg-ohiggins** [comment]
Thanks @heymatthenry!
