### ISSUE TITLE
🅢 Figure out what “version” means

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#315]
### Background

As far as I can tell there are three different `version` properties that are currently being discussed:

*   The “raw” tracking of changes by [django-reversion](https://github.com/GSA-TTS/FAC/issues/199), which may or may not need to be visible to users.
*   The current FAC system has revisions, which refers to changes made to submissions *after they have previously been accepted*. These may also need to be visible to users.
*   The version of the form itself; the form has changed in some years. This should probably be the year, as I don't think it can change within a given submission year. (The form we will be accepting will have changed in at least one way, the EIN to UEI change.) This version will probably have `G` or `GSA` at the start of the identifier to make it easier to see immediately whether or not a form is Census- or GSA-originated. For example, the forms users will fill out in October 2023 will presumably have a version of `GSA2023`.

### Acceptance Criteria (We'll know we're done when...)

- [x]   ~~We have an understanding of which of these users need to see.~~ Per Melissa and Scott in comments below, the users don't need to see any of them for MVP.
- [x]   ~~We know whether or not we need to track the current meaning of “revisions” at all or whether it's effectively covered by `django-reversion`.~~ Per Melissa and Scott, MVP doesn't need to expose version to users and doesn't need to deal with the Census FAC concept of “revisions”.
- [ ]   ~~We've added the needed fields to the backend model(s).~~ While we do need to add [django-reversion](https://github.com/GSA-TTS/FAC/issues/199), that's covered in its own story. 
- [ ]   ~~We've added the fields that need to be displayed to the frontend.~~ Looks like there aren't any!

### Tasks

- [X]   Do user research or make design decision on what, if any, version tracking of the submitted audit users need to see. ANSWER: none for MVP.
- [X]   Design decision on whether or not users need to see version of the form itself (my assumption here is no and that it would be confusing). ANSWER: Nope.
- [ ]   Implement [django-reversion](https://github.com/GSA-TTS/FAC/issues/199) on the backend.
- [ ]   ~~Add revision field (if necessary) and form version field to backend model(s).~~ Not necessary.
- [ ]   ~~Add desired fields to frontend.~~ None needed.

**Comment by MelissaBraxton** [comment]
Thanks for capturing this, @tadhg-ohiggins!  For the first task, I think we heard in our last round of user research, that "version" is more confusing than helpful to users, and we can decide not to surface it to folks at least for the MVP. One thing to clarify though, we were looking at surfacing "version" for audit submissions in progress--not already submitted ones. 

For the second task, I concur that the answer is **no.** What do you think, @sreuber? (cc @melchoyce, just fYI)

**Comment by sreuber** [comment]
@MelissaBraxton Agree. It's a **no** from me.

**Comment by tadhg-ohiggins** [comment]
Thanks @MelissaBraxton and @sreuber, I've updated the description and will close this issue and comment on #295.
