### ISSUE TITLE
Update design documentation

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#316]
### Background
W/ turnover in the design team, want to make sure all design docs are up to date as we onboard and offboard folks. 

### Acceptance Criteria (We'll know we're done when...)
- [x] All design documentation reflects the current state of knowledge

### Tasks

- [x] Review and update design onboarding doc
- [x] Review and update user research compensation process documentation
- [x] Review and update design debt doc
- [x] Add links to research reports from the design part of the wiki
- [x] Review and update UX flow diagram
