### ISSUE TITLE
Test in Preview

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3166]
Test migrations in Preview with Final Census Data.
```[tasklist]
### Tasks
- [x] Setup to use Preview
- [x] Access Preview DB
- [x] Query Preview Census tables
- [ ] https://github.com/GSA-TTS/FAC/issues/3207
- [x] Analyze errors
```

**Comment by gsa-suk** [comment]
Error details during migration testing: https://drive.google.com/drive/folders/1bv6vVCpbQbCl27zi9rqOk22vcp0uLxkG
