### ISSUE TITLE
Update copy + instructions re: email notifications

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3182]
## User story

**As the Certifying Official on a specific single audit package, I need to know if other assigned participants receive a notification when I complete a step of our submission package, so that I can update them myself if they aren't.**

Currently: Users are accustomed to email notifications from the previous cFAC. Our system does not yet support email notifications, and we do not explicitly state that in the current workflow. We're updating our content in strategic places to highlight this information. Images and further detail here: https://docs.google.com/document/d/14x2sjulPLSvMm0vBuWX-cV8FL7eo884yvpiE7a90kDY/edit?usp=sharing

### Tasks

```[tasklist]
- [ ] Update copy on following screens: Submission criteria, Lock for certification, collapsed Submission checklist, Auditor certification signature, Auditee certification signature (see notes doc above for images + detail)
- [x] Update relevant images/copy on submission guide
- [ ] Review FAQs for revisions
```

**Comment by lauraherring** [comment]
@Leighdiddy @jperson1 The new copy is in the Google doc. Let me know if you have any questions on it.

**Comment by lauraherring** [comment]
The static site instructions have been updated and published.
