### ISSUE TITLE
Auditee/Auditor audit certification

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#319]
## Background
Audits must be certified via a "signature" by an auditor certifying official as well as an auditee certifying official.

## Design
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3559%3A16444

### Path: non-certifying auditor/auditee
* [ ] When I am signed in as a non-certifying auditor/auditee and all criteria to validate the audit have been met.
* [ ] The buttons to certify as auditor and as auditee should be disabled.

#### Technical considerations
*   Frontend needs to know what the user's role is, in order to know user is not a certifier.
*   As part of this, the frontend needs some way to get information about the user, for example an endpoint the frontend can hit to ask about the role a user has on a given submission. This should be its own issue.
*   Backend will validate user role on any submission to prevent certification actions by non-certifier users.
*   Other restrictions aside, we do want to ensure that no user can be both certifying auditee and certifying auditor.
*   Note: we aren't fully clear on whether or not users can have multiple roles on a single submission, or whether, for example, a certifying auditor should not also be able to edit a submission. For now we are going forward assuming multiple roles are possible and that any edit restrictions will be added as future enhancements.
*   Note: we think that the existing `Access` database model covers the use cases here, so no database work should be necessary, with the exception that we need to add the “can't be both certifying auditor and auditee” restriction.

**Path: Invited auditor certifying official**
* [ ] The FAC creator specifies an auditor certifying official on the submission access page
* [ ] Notification aspects covered in [#386](https://github.com/GSA-TTS/FAC/issues/386)
* [ ] Their audits dashboard should now include this audit in the list with an appropriate status.
* [ ] Assuming other criteria are met, the button to sign their part of the audit should be enabled and they should see a text button to perform that action.
* [ ] When they click the button, they are taken to the certification screen. See [#387](https://github.com/GSA-TTS/FAC/issues/387) for details.
* [ ] When both auditee/auditor have signed, the main "next/submit" button on the audit start page is is enabled

**Path: Invited auditee certifying official**
* [ ] The FAC creator specifies an auditee certifying official on the submission access page
* [ ] The auditee certifying receives an email
* [ ] The auditee certifying receives an email notifying them that they've been added and to create an account or login
* [ ] Once their account has been created, they should be on the audit certification checklist screen
* [ ] assuming other criteria is met, the button to sign their part of the audit should not be disabled and they will see a text button to sign their part
* [ ] When they click the button, they are taken to the certification screen. When they complete each question, the next section reveals. When they enter their name and title, they will be taken back to the audit start page
* [ ] When both auditee/auditor have signed, the main "next/submit" button on the audit start page is is enabled

**Tasks**
* [design] https://github.com/GSA-TTS/FAC/issues/321
* https://github.com/GSA-TTS/FAC/issues/335
* Front end - auditee/auditor signing  
* Back end - auditee/auditor signing
* https://github.com/GSA-TTS/FAC/issues/341  
* Send auditee/auditor invite notification email

**alternate approaches to invite (out of scope)**
* [ ] Sharable invite link
* [ ] self-clicking mailto link
  * Less than ideal, UX but more simple: 
  * Enter "bob@bob.com" into the email field
  * Their email client will pop up like a mailto-link
  * You click this and it does a mailto to with pre-populating the subject line+body
  * It also sends something to the backend saying "add bob@bob.com"

**Related, but separate stories:**
* https://github.com/GSA-TTS/FAC/issues/319
* https://github.com/GSA-TTS/FAC/issues/212
* https://github.com/GSA-TTS/FAC/issues/342
* https://github.com/GSA-TTS/FAC/issues/332
* https://github.com/GSA-TTS/FAC/issues/343

**Comment by MelissaBraxton** [comment]
This looks good, @petermarks-gsa ! 

A few minor tweaks:  
Remove "When they click the button to sign their part of the audit, they should see the signature form"
The current thinking is that there will be a text box _on the checklist screen_ where they type in their name and title to "sign," and agree to the auditee/auditor statement. 

 ![Screen Shot 2022-07-06 at 11 32 37 AM](https://user-images.githubusercontent.com/20651166/177619091-f3562604-d71c-4666-8fe7-0cd686d63306.png)
 
Here's what it currently looks like ^ 

Would it be helpful for design to spend some time making either a detailed flow or prototype to depict this, or are we all clear on how this should work? (cc @melchoyce and @sreuber)

**Comment by petermarks-gsa** [comment]
@MelissaBraxton @melchoyce I just discussed this with @heymatthenry and @tadhg-ohiggins. We have a few follow up questions: 

* **Invite process** - What do we know about the process of inviting people to edit an audit on the current FAC? Do they receive an invite email? 
* **Invite permissions** - Should auditee and auditor users be able to edit any parts of the SF-SAC? Should they also be able to invite people? We're wondering how granular to make permissions. 
* **Post log-in experience** - What is the expected destination for new users associated with an audit who didn't necessarily come from an email link? Send them to a list of audits they have access to?

**Comment by MelissaBraxton** [comment]
- **Invite process** - The current FAC doesn't really have a concept of "invite." Instead, there are notifications about when something significant happens with a submission. So, when a new submission is created, anyone who has been given access gets an email to let them know. The emails are slightly customized based on whether the user already has a FAC Login, but I don't think we need to emulate that. 

Here's an example:
 <img width="1043" alt="Screen Shot 2022-07-08 at 2 27 13 PM" src="https://user-images.githubusercontent.com/20651166/178072911-1da26ece-ccb9-456e-8d74-4a30b75c3ff4.png"> 

- **Invite permissions** - Right now, anyone can edit any part of the SAC, and I think we should keep it that way. (We've talked to some auditors who wish there were more granular permissions, but given that we also heard that many auditee/auditor relationships rely on auditors being able to do **all** but the certification step, I don't think we should consider changing this right now). I'm not sure who has the current authority to change permissions. 

- **Post log in experience** - People currently can't access a specific audit via a URL. Right now, they are directed to log in to the FAC to access a newly created audit, and presumably find it on their own with the reference number in the email. We could consider something similar here, so...

_For a new user coming to the FAC for the first time who wants to view/edit a draft audit they've been given access to:_ 

 1. They arrive at FAC website
 2. Click "Login"
 3. They're directed to Login.gov
 4. They create a new account
 5. They login with Login.gov
 6. They arrive at "My submissions" page. If there are submissions associated with them, they'll be listed there. If there aren't any, the list will be blank. 

_If we are planning to include a URL in the email that would direct a **new user** to a specific draft submission, I'd imagine it would look like this:_ 

 1. They click on the URL in the email
 2. They're directed to Login.gov
 3. They create a new account
 4. They login with Login.gov
 5. They arrive at "My submissions" page. If there are submissions associated with them, they'll be listed there. If there aren't any, the list will be blank.

**Comment by MelissaBraxton** [comment]
Breakout issue for initial design work is here: #321

**Comment by danswick** [comment]
consolidating to https://github.com/GSA-TTS/FAC/issues/1401
