### ISSUE TITLE
🅜 Change login.gov flow to look for users with matching email addresses

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#320]
Breakout issue of #246

### Background

When users log in with login.gov and do not already have associated `User` objects, we need to check against the list of users that have been created without any non-email data. (These are the users that have been added to their SAC submissions by other users.)

The current login.gov flow only looks at primary email addresses supplied by login.gov, and we need to change that to look at all email addresses associated with the user. (Both primary and a set of other email addresses are provided in the user info passed along by login.gov.)

### Acceptance Criteria (We'll know we're done when...)

- [ ] We can add a user to a SAC when that user doesn't exist in the system and then log in using the login.gov flow and verify that that user has been added to the system.
- [ ] And that that user can edit that SAC.

### Tasks

- [ ] Check assumption that email address can only exist in one login.gov account at a time.
- [ ]

**Comment by petermarks-gsa** [comment]
@timoballard I just added this to the board. Can you please advise on t-shirt size of this?

**Comment by timoballard** [comment]
@petermarks-gsa M

**Comment by tadhg-ohiggins** [comment]
## 2022-07-08 discussion on some edge cases around login.gov users and `Access` objects.
Participants: @geekygirlsarah @tadhg-ohiggins @timoballard 

1.  `SingleAuditChecklist` object is created with `Access` objects that have null `user_id` fields but they have the email addresses the user submitted for auditee, etc.
1.  We do not check the email addresses in the newly-created `Access` objects to see if there are `User` objects with matching email addresses—we only check for that during the login.gov login flow.
1.  When a user logs in with login.gov, we:
    1.  See if there is already a `User` for that login.gov identifier. If not, we create that `User` with their login.gov primary email address as their email address property on `User`.
    1.  Look at all their login.gov email addresses and at all `Access` objects with `null` `user_id` fields to see if any of the email addresses match.
    1.  If any match, we associate those `Access` objects with their `user_id`.

## Scenario 1

*   Alice adds bob@agency1.gov to SAC 1. `Access` object is created with bob@agency1.gov as email address.
*   Chris adds fac-liason@agency2.gov to SAC 2. `Access` object is created with fac-liaison@agency2.gov as email address.
*   Bob logs into FAC for the first time, `all_emails` contains `[bob@agency1.gov, fac-liaison@agency2.gov]`
*   We create `User` for Bob with `bobprimaryemail@agency.gov` as the canonical email address.
*   We pull up all `Access` objects with null `user_id` fields and find two that match some of Bob's entries in the login.gov `all_emails` property: SAC 1 with bob@agency1.gov and SAC 2 with fac-liaison@agency2.gov.
*   We associate the Bob `User` with both of those `Access` objects.
*   We leave the email addresses as they are in both `Access` objects even though it doesn't match the email address in the Bob `User` object.

## Scenario 2: how do we remove users from `Access` objects given the potential mismatch between email address and `User` object and login.gov emails?

*   We need to look for changes to the contact fields in the `SingleAuditChecklist` object that contain `Access` references and delete potential dangling `Access` objects that are no longer referred to by any `SingleAuditChecklist` object.
*   We look up the `Access` object by email address and delete it; we also set the corresponding property on the `SingleAuditChecklist` object to `null`.

## Scenario 3

Bob quits Agency 2. Agency 2 promotes Jane to be the new FAC Liaison. Jane adds fac-liaison@agency2.gov to her login.gov account. Bob removes fac-liaison@agency2.gov from his login.gov account (hopefully in reverse order…).

Jane logs in to FAC:

*   We create `User` for Jane with `janeprimary@agency.gov` as the email address.
*   We don't find any `Access` objects with null `user_id` fields that match any of Jane's `all_email` entries.
*   ??? profit

Tadhg proposal: the FAC users at Agency 2 need to remove fac-liaison@agency.gov from the set of allowed users and then re-add it.

New issues:
*   We need to look for changes to the contact fields in the `SingleAuditChecklist` object that contain `Access` references and delete potential dangling `Access` objects that are no longer referred to by any `SingleAuditChecklist` object.
*   We look up the `Access` object by email address and delete it; we also set the corresponding property on the `SingleAuditChecklist` object to `null`.
*   Check assumption that email address can only exist in one login.gov account at a time.
*   Find out how (if it's possible at all) email addresses may be able to migrate from one login.gov account to another.

**Comment by mogul** [comment]
Doing some cleanup... Is this issue actually still active (it was in Milestone 1) or can it be closed?

**Comment by tadhg-ohiggins** [comment]
@timoballard my recollection is that you changed the login flow to look at all email addresses supplied by login.gov, not just primary. Can you confirm?

**Comment by tadhg-ohiggins** [comment]
@mogul While I think we covered the basic case, I'm not sure we fully covered all the edge cases. That being said, it's possible that we can icebox those edge cases.

**Comment by timoballard** [comment]
Yes @tadhg-ohiggins, that's correct. Also not sure that we covered every edge case. I'm writing the ticket right now that covers the updates we'll need to make to our LoginGov integration as part of the move to a unified Django app. Since I'll be in diving back into this code as part of that work, I can add it as a task to revisit this ticket and document exactly what is still outstanding. Does that work? cc @mogul

**Comment by mogul** [comment]
That sounds good. I'll close this issue and the related milestone containing it.
