### ISSUE TITLE
As an auditor/auditee certifying official, I need to be able to certify an audit submission

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#321]
### Background
[Breakout issue of 264](https://github.com/GSA-TTS/FAC/issues/264). 
This issue covers the design of the auditee/auditor "certify" pages as well as error messages/alt states and screen that confirms a user has certified after they've clicked "certify" on the certify page. 

Additional user needs statements that are in the scope of this issue: 
 - As an non-tribal certifying official, I need to agree that my audit and audit report will be made public
 - As certifying official for a tribal nation or organization, I need to be able to choose not to have my audit made public. 

We have a start on certification flow steps in https://github.com/GSA-TTS/FAC/issues/319.

### Acceptance Criteria (We'll know we're done when...)
- [ ] We have mocked auditor and auditee certify pages
- [ ] Mocks are annotated with implementation notes

### Tasks
- [x] Visit current FAC and grab screen shots of current certify pages in all states and drop in Figma @MelissaBraxton 
- [x] Mock up certify pages
- [ ] Add implementation notes in Figma
- [x] Tag someone to peer review

**We'll know we're done when...)**
- [ ] Screen is ready to be used in a Figma usability testing
- [ ]  All text has a contrast ratio of 4.5:1 with the background
- [ ]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment]
Hey there, @sreuber - I added the screen shots to a new page [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3420%3A15760).

**Comment by sreuber** [comment]
@MelissaBraxton @melchoyce @austinhernandez Could use some eyes on this one. As I mentioned in stand, I have a couple of options I'm floating here. One a pretty close representation of what happens currently, the other very streamlined. I don't have complete annotations off to the sides, so feel free to ask for clarification on anything and I'll try to address as soon as I can tomorrow morning.

Links to starting mocks, just follow the artboards right…
[Traditional path](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3602%3A18671)
[Streamlined path](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3559%3A16444)

**Comment by MelissaBraxton** [comment]
@sreuber  - This looks good to me! I agree that the "streamlined path" requiring fewer clicks may be preferable for folks.

**Comment by MelissaBraxton** [comment]
@sreuber  - What's the latest here? Looks like the mocks still need implementation notes.

**Comment by sreuber** [comment]
Implementation notes updated. Ready for review.

**Comment by petermarks-gsa** [comment]
I've reviewed the designs / implementation notes and have updated the implementation issue: https://github.com/GSA-TTS/FAC/issues/319
