### ISSUE TITLE
Feb 1A: User interviews with ARO + IG's re: resubmission

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3218]
**How does resubmission of revised single audits affect Audit Resolution Officials and/or IG's work with data from the FAC?** Our goal is to interview 6-8 agency users by mid-February. We're conducting this research to: 
1. Identify problem areas for further investigation 
3. Explore initial light-lift solutions for implementation 
4. Help inform our FY24 budget proposal

```[tasklist]
### Tasks
- [x] Frame research questions
- [x] Compose comms (invite, confirmation)
- [x] Create interview notes docs + schedule
- [x] Create new gcal appointment schedule
- [x] Identify recruits
- [x] Send email invitations
- [x] Confirm appointments, create zoom links, update invites + add CJ as optional
- [ ] Summarize (notes or whiteboard) + share results w team
```

**Comment by Leighdiddy** [comment]
Comms, notes docs and schedule can all be found [here](https://drive.google.com/drive/folders/1BCAfdboCPi854o5KgqWF-3tmuIqu9z51)!

**Comment by jadudm** [comment]
Conversations had/underway. Closing this ticket. We do need to summarize, which I'll put a placeholder ticket in for.
