### ISSUE TITLE
Build Audit Submission Resources hub page

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3227]
Will be closed by https://github.com/GSA-TTS/FAC-transition-site/pull/91

```[tasklist]
### Tasks
- [x] mock up page in Figma
- [ ] write copy for page
- [ ] build page in GIt
```

Initial draft of page will need 3 cards:

- Submission checklist
- Workbook instructions
- Manage user access instructions

**Comment by lauraherring** [comment]
Google doc of copy: https://docs.google.com/document/d/1aRHu5rlpuqJrKAte4YCTatIh9CKcq2taPuOEzau1W3s/edit
