### ISSUE TITLE
Build Audit Search Resources hub page

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3228]
Will be closed by https://github.com/GSA-TTS/FAC-transition-site/pull/91

```[tasklist]
### Tasks
- [x] design page in Figma
- [ ] write copy for page
- [ ] build page in Git
```
Initial draft will need 2 cards:

- search parameter definitions
- how to access Tribal audits

Future search resources:

- how to read the results audit table
- definition of cognizant vs oversight

**Comment by Leighdiddy** [comment]
Figma mocs shown in lower right hand corner: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-Source-of-Truth?type=design&node-id=0-1&mode=design&t=MgKrnjwVjYQdzFeZ-0

**Comment by danswick** [comment]
This is done.
