### ISSUE TITLE
Bug: is_direct and passthrough handling

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3236]
Working in: https://github.com/GSA-TTS/FAC/tree/jadudm/fix-passthrough-checks

## Story

In Federal Awards, when `is_direct` is `N`, then both columns `O` and `P` are required. We were only checking `O`.

```[tasklist]
### Tasks
- [x] Extend `check_` for this case.
- [ ] Update Jsonnet schema to reflect logic.
- [x] Add failing workbooks to the test suite for this situation, and confirm they fail appropriately
- [ ] Add a cross-validation for this check (if cross-validation re-runs this `check_`, no action required)
- [ ] Reply to https://fac-gov.zendesk.com/agent/tickets/1826 as appropriate
```

**Comment by jadudm** [comment]
See

https://github.com/GSA-TTS/FAC/issues/3240

before we go further on this ticket.

**Comment by danswick** [comment]
Next: discuss how we might start tracking these curation-related issues in one place.

**Comment by jadudm** [comment]
This will require further investigation before implementation. Closing as not planned at this time. Adding to a documentation ticket for doc/tracking.
