### ISSUE TITLE
Epic: Database performance

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3252]
## Background

We have approximately 12K audits in the dissemination table. This appears to be enough data to slow down:

1. The application
2. API queries
3. Web queries

We have suspicions that the DB is a bottleneck; that is, when the API is under load, it appears that other parts of the system slow down. This is commesurate with our `medium` database instance being heavily loaded. (We saw this in the DB migration work: the `medium` instance is 8GB of RAM on 1 VPU.) The performance DB is also a `medium` instance, and therefore we have no reason to believe it performs better than the `preview` instance doing migration work.

In `preview`, we did two things:

1. Upgrade to an `xlarge-redundant` instance. This provides 16GB of RAM and 2 VPUs to the DB.
2. Index critical columns or sets of columns in the dissemination tables. 

```[tasklist]
### Recommended actions
- [x] If possible, determine where the bottlenecks are.
- [ ] Identify and apply indicies to relevant columns
- [ ] Upgrade DB instance (during a low period) from `medium-redundant` to `xlarge-redundant`
- [x] Fix search so it does not crash on most/all queries.
```

The research needs to be timeboxed; we may, because of the cloud.gov architecture, have poor visibility into the DB server's performance bottlenecks.

Upgrading should be straight-forward, and involves a short downtime while the migration happens at the AWS end.

Relevant columns are at least:

1. Columns used in the WWW search interface
2. Columns that seem to be used heavily in the API queries

#1 is easy to determine by inspection of our search code.

#2 might be determinable from logs. If not, `report_id` is obvious in all tables.  

## We'll know we're done when: API test

Currently, it is not possible to reliably request 100 elements from the `passthrough` table via API. E.g.

```
/passthrough?select=report_id&limit=100&offset=100000
```

will either succeed (after a 120s+ delay) or, sometimes, fail with a 502. 

It is possible, but unlikely, that the issue is the PostgREST container not having enough RAM, but given the performance issues seen across the application, it is probably the DB.

## We'll know we're done when: WWW test

With 120K audits in the system (migrated data in `preview`), we see that a search for ALNs crashes the app.

```
93
45
```

as two agency numbers is enough to bring down the app after a timeout. This should be performant, and always succeed.

**Comment by jperson1** [comment]
Some quick notes for findings on Search:

We have a lot of records. This slows down queries on "standard" (non-ALN) searches, since we do a full query and order the results before display. Django queries are lazy by nature and do not hit the database until the results are accessed, which means we can order the results at the query level before accessing the results for a moderate performance increase. Standard searches are not generally problematic in our system, so this can come later. 

We handle ALNs differently, and they have the most bottlenecks.
1. The ALN match query involves finding all the relevant FederalAward objects. This is necessary, as that's where the ALN data is stored. We make an enormous set of report_ids, so that we can search the General table with them. We then make a giant list of `OR` clauses to add to the later search on General. This is not at all performant. 
2. The `_attach_finding_my_aln_and_finding_all_aln_fields` (AFMAFAAF), or "Aff Mah Faaf". It takes a while to find the relevant awards and then attach the relevant Y/N columns. This will be partially mitigated by limiting the above. But, since we get those FederalAward objects earlier anyways, we can make use of them in the AFMAFAAF. 

Immediate (or soon) steps:
1. The ALN match query:
    * Limit the FederalAward query. Even if the final results are limited, this isn't, and can get up to tens of thousands of report_ids. As the final results will be limited, getting all those id's is not necessary. _As long as it stays consistent_. We only need enough to get to `SUMMARY_REPORT_DOWNLOAD_LIMIT` total objects, so maybe like *2. 
    * Do not use `n` OR clauses, use a `report_id__in`. Even if it's a big list to do an "in" operation on, it's better than OR'ing everything. 
2. The AFMAFAAF
    * Don't make a list of report_ids. We can do `reporet_id__in=results`, and it's a little quicker.
    * Utilize the previously aquired award objects. 

Some testing changes can be spotted at https://github.com/GSA-TTS/FAC/compare/main...opt/speed-up-queries

Future steps:
- Break standard and ALN searches into different processes. They are different enough that breaking them up will make for more readable and understandable code. This will also make it easier to iterate on them separately, without breaking the other.

**Comment by danswick** [comment]
There may be some follow-up work, but this epic is done for now.
