### ISSUE TITLE
Design how we communicate to users that the notes to SEFA and secondary auditors form sections are not included in the MVP.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#326]
### Background
We've been talking about delaying the release of data collection instruments for two sections of the current SF-SAC form: **notes to SEFA** and **secondary auditors**. 
Our current mocks include these form sections in the side nav of the SF-SAC. This issue covers how we handle communicating to users that they can't submit data for these form sections using the MVP, and that they are not required for a "complete" submission. 

We need to decide whether we (a) continue to include these items in the nav, but then design some way to communicate to users that these features are slated for later release or (b) remove them from the form entirely. The risk of **b** is that folks who are very familiar with the current data collection will wonder what happen / be worried that they're missing something, so we'll need to communicate this change to them in either case. Then we need to mock up whatever we decide. 

### Acceptance Criteria (We'll know we're done when...)

- [ ] We've designed a way to communicate to users that the notes to SEFA and secondary auditors form sections are not included in the MVP

### Tasks

- [ ] Design an approach for Notes to SEFA
- [ ] Design an approach for Secondary Auditors
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
Note to self. The link in this sidebar:

![image](https://user-images.githubusercontent.com/2846578/179998679-2f50f9fe-b732-4a85-88fe-f412a33a6bfb.png)

Downloads an Excel form: [SEFAReport_932649_1 (1).xlsx](https://github.com/GSA-TTS/FAC/files/9150368/SEFAReport_932649_1.1.xlsx)

@MelissaBraxton What is this form used for?

**Comment by melchoyce** [comment]
Form screenshots:

![Screen Shot 2022-07-20 at 9 58 24 AM](https://user-images.githubusercontent.com/2846578/180023735-d0fb5094-208a-455e-a1ea-d355d3f84d13.png)
![Screen Shot 2022-07-20 at 9 58 38 AM](https://user-images.githubusercontent.com/2846578/180023742-8559c37a-05fc-4600-ade8-adad14c78db7.png)

**Comment by MelissaBraxton** [comment]
The data entry screens for this info are in the current mocks here and are a part of the side nav for the SF-SAC:
<img width="450" alt="Screen Shot 2022-07-20 at 8 41 04 AM" src="https://user-images.githubusercontent.com/20651166/180025311-fc2277dd-f4e6-470d-a7fd-a72bc2d6722b.png">
<img width="513" alt="Screen Shot 2022-07-20 at 8 44 40 AM" src="https://user-images.githubusercontent.com/20651166/180025844-7997a023-c4c8-4e10-be99-c20ba1271378.png">

**Comment by melchoyce** [comment]
Thanks for the details, @MelissaBraxton! I think I'm starting to understand better.

**Comment by melchoyce** [comment]
I'm thinking for the "Notes to SEFA" section, we can add a message to the previous screen that explains the section won't be used in 2023:

![image](https://user-images.githubusercontent.com/2846578/180304770-c87ee0ff-7b58-43ba-a48e-1b3778258195.png)
[Figma Link](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3982%3A21309)

@MelissaBraxton @sreuber @austinhernandez does this make sense to y'all?

@erinzstrenio Can I have you do a copy check when you have a moment? The new copy is:

> **Please note:** For fiscal year 2023, the “Notes to SEFA” is not required for your submission, so we are not currently collecting this information.

Thanks!

**Comment by erinzstrenio** [comment]
Quick question: Does "Notes to SEFA" refer to a section in the worksheet? Or a section of the FAC? Just trying to better understand the reference so I can try and give helpful feedback on the copy!

**Comment by melchoyce** [comment]
> Quick question: Does "Notes to SEFA" refer to a section in the worksheet? Or a section of the FAC? Just trying to better understand the reference so I can try and give helpful feedback on the copy!

The first image here: https://github.com/GSA-TTS/FAC/issues/326#:~:text=commented-,yesterday,-The%20data%20entry Thanks for clarifying!

**Comment by erinzstrenio** [comment]
Ah, I should have more thoroughly read the previous comments before commenting! 

If you decide to remove the page from the side nav as proposed here, then I might add just a little more context on the removed section:

> **Please note:** For fiscal year 2023, the “Notes to SEFA” section, which typically follows this section, is not required, so we are not currently collecting this information. 

If you decide to keep the page in the side nav because the plan is to add it back in future years, then you could include some simple text on the page without including the questions: 

> This section is not required in fiscal year 2023, so we are not currently collecting this information.

**Comment by melchoyce** [comment]
Updated with the new copy and correct version of this page:

![image](https://user-images.githubusercontent.com/2846578/180462922-712fbf96-a0da-4a01-b8ec-1704075c3930.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4018%3A19329)

**Comment by melchoyce** [comment]
Scrap the above; after chatting with @austinhernandez and @erinzstrenio, we do think it's better the keep the pages for the MVP, and put the "we're not collecting this" notice in those pages:

![image](https://user-images.githubusercontent.com/2846578/180878922-dd48a1d1-51ba-4483-a21d-3709b88425f1.png)
![image](https://user-images.githubusercontent.com/2846578/180878943-a53961f9-2df5-4ace-ac3b-5790841da7a5.png)

[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3910%3A18459)

Austin reminded me that the form is filled out non-linearly, so we can't rely on someone seeing the notice in the "Federal awards" section before moving on to "Notes to SEFA." Additionally, the person filling that page out might not even be the same person who filled out the "Federal awards" page.

Austin/Erin could I get one more design sign-off before this is ready for dev?

**Comment by erinzstrenio** [comment]
@melchoyce Looks great, thanks for updating these! 

Small edit: you can remove the second "The" on the "Notes to SEFA page" 
--> "Notes to the Schedule of Expenditures of Federal Awards (SEFA)"

**Comment by melchoyce** [comment]
@petermarks-gsa This is good to push forward! Implementation notes are in [Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3910%3A18459).

**Comment by petermarks-gsa** [comment]
Next steps captured here: https://github.com/GSA-TTS/FAC/issues/406. Closing.
