### ISSUE TITLE
🅛 PDR/ADR - Excel file generation

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#328]
## Background
The process for submitting entries to the FAC relies on uploading audit data via Excel templates. Design has been clear that this is so critical to workflows that it's a priority over web forms and could actually be done in place of them for MVP. There is already an accepted PDR for ["how to handle bulk data uploads"](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0008-bulk-data-uploads.md) which uncovered an Excel File validator as well as a corresponding [spike](https://github.com/GSA-TTS/FAC-xlsx-validator) in that effort. The part that we don't have clarity around, which is the subject of this ticket, is creating Excel file templates.

## Understanding of generated templates
Excel template forms downloaded from the Census FAC are custom generated by the server to validate against previous data entered, including:

* **Validating EIN** - Currently, EIN's are baked into the template and validated when they are uploaded. Per Census, this is helpful for auditors doing a bunch of audits at once to ensure they don't upload a sheet for another organization they're uploading an audit for. 
* **Previously entered data options** - We understand there are cases where data entered on previous steps is surfaced as options in the template on subsequent steps. 

## Maintainability

The Excel process under discussion would have at least three levels of validation:

1.  The backend validation rules: any `SAC` submitted, regardless of how it is submitted, must pass backend validation.
2.  The frontend validation rules: the frontend libraries being used to translate Excel into JSON for submission need to validate that JSON and flag errors before anything is submitted to the backend.
3.  The Excel validation rules: the Excel files need to contain validation rules so that users know within Excel that their entries are valid or have errors.

These constitute the base level of “dynamic generation”—not generation based on user data, but generation based on whatever the validation rules are, as these validation rules themselves are likely to change (for example, the rules include lists of valid answers to specific questions, and those lists change).

Any system we come up with for this must have a single source of truth for all three levels. While it's possible we could use the Python backend code itself as this source, it's more likely that we would use some well-documented, well-understood system for defining rulesets and then use its tooling as part of translation into the various domains.

One possible approach to this is [JSON Schema](https://json-schema.org/), but many other options doubtless exist.

The base questions for maintainability would then be:
*   What rule-definition tool(s) would we use?
*   How difficult would it be to translate the expected rules (such as those contained in the existing Census systems and the existing Excel templates) into that system?
*   How difficult would it be to translate the rules from that system into our three levels?
*   How difficult would it be to add that translation approach to our build pipeline?

In addition, each of those three levels of validation requires automated testing. We have good understanding for how to approach that for the frontend and backend, but no idea how this would be accomplished for Excel.

## Potential solutions (Non-exhaustive list)
  * Option 1: Find a way to generate Excel file templates (current Census FAC approach, Design team recommendation)
    * It's unclear this is an option on our stack
  * Option 2: Static Excel file templates
    * Risk: Potentially more confusing for the user to re-enter information
    * Risk: CPAs working on multiple audits might upload the wrong sheet
  * Option 3: Single Excel file templates
    * Risk: Limited / no client side validation, which could lead to more audit churn
    * Opportunity: More simple experience for users
  * Other options: any way to do this on CSV? 

## Acceptance Criteria:
- [ ] We have identified a solution or set of solutions that meets the maintainability criteria laid out above.
- [ ] Compared a few libraries for excel file generation and considered security/compliance considerations. 
- [ ] Consider the complexity of current excel templates / validation when making a recommendation
- [ ] Estimate effort various approaches
- [ ] (as a team) Compare estimates with user needs and make a technology decision for MVP

## Tasks
- Research Census's current implementation of template generation
- Look into libraries for template generation and compare them

**Comment by petermarks-gsa** [comment]
@geekygirlsarah @jasnakai @tadhg-ohiggins I've added more context to this ticket and clarified that this is about excel file generation as we already did a ADR and associated spike for ["How to Handle Bulk Data Uploads"](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0008-bulk-data-uploads.md). Please let me know if this is good to scope/estimate or if there are further refinements needed.

**Comment by tadhg-ohiggins** [comment]
This seems like a research spike rather than an ADR/PDR, any objections to changing the name of the ticket to reflect that? If I'm incorrect and @jasnakai and @geekygirlsarah are going to be making a product decision via this issue, I'm not clear on exactly what the decision in question would be.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins I'm flexible on whether we do a formal ADR/PDR as part of this work. 

My thinking is that @jasnakai and @geekygirlsarah would do this part of the AC: 

- [ ] Compared a few libraries for excel file generation and considered security/compliance considerations. 
- [ ] Consider the complexity of current excel templates / validation when making a recommendation
- [ ] Estimate effort various approaches

And I'm thinking we'd discuss this as a team:

- [ ] Compare estimates with user needs and make a technology decision for MVP

**Comment by tadhg-ohiggins** [comment]
@petermarks-gsa That seems like a reasonable approach to me. @geekygirlsarah and @jasnakai, does that work for you?

**Comment by jasnakai** [comment]
Works for me!

**Comment by geekygirlsarah** [comment]
Seems fine with me

**Comment by melchoyce** [comment]
Hey! Double-checking, will this research spike be a part of our next sprint?

**Comment by petermarks-gsa** [comment]
@melchoyce Good question. At our weekly design sync on 7/28 ([notes](https://docs.google.com/document/d/1Aq5Y6RyWSXXQD0CExanNekWn7GK3YpEmo0FznenRRf4/edit#)), we discussed whether we discussed whether we want to implement web forms before Excel upload. From notes, it looks like we decided to have the engineering team discuss if that approach will lead us to Excel upload in a shorter amount of time with less risk. I don't think we made a specific decision about whether to descope this, at least to my knowledge. cc @tadhg-ohiggins

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins @geekygirlsarah @jasnakai It sounds like we're aligned on acceptance criteria per [this comment](https://github.com/GSA-TTS/FAC/issues/328#issuecomment-1197307005). Are we good to remove either the needs refinement or needs scoping label?

**Comment by jasnakai** [comment]
I'm good with removing them but I did not add them.

**Comment by petermarks-gsa** [comment]
@jasnakai @geekygirlsarah Per discussion at engineering estimation, let's leave needs scoping on this until we have an estimate. I'll take needs refinement off, but let me know if you have any further questions on requirements.

**Comment by geekygirlsarah** [comment]
We are estimating this as an L because @jasnakai and I feel that the data points we need to make a determination aren't large, but the time needed to produce those data points will take a couple of days, at least. It feels like the work is a M, but due to the time will be an L.

**Comment by tadhg-ohiggins** [comment]
I added a section on maintainability, as that is critically important for our approach to this area; I also added that as part of the acceptance criteria.
