### ISSUE TITLE
Historic data go-live

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3287]
```[tasklist]
### Tasks
- [x] Load 2022 PDFs in to `preview`
- [x] Load PDFs into `production`
- [x] Spot-check against Census 2022 in `preview`
- [ ] https://github.com/GSA-TTS/FAC/issues/3318
- [ ] https://github.com/GSA-TTS/FAC/issues/3317
- [x] Load new data dump into `staging` for testing search
- [ ] Test SF-SAC creation in `preview` and `staging` on 2022/2019
- [ ] Develop recovery plan if everything goes sideways
- [x] Trigger action to backup `production` tables
- [x] Wipe `staging` (`TRUNCATE` dissemination tables in `staging`)
- [ ] https://github.com/GSA-TTS/FAC/issues/3330
- [ ] https://github.com/GSA-TTS/FAC/issues/3336
- [ ] https://github.com/GSA-TTS/FAC/issues/3354
- [x] Test search, links for 2022-2016 in `staging`
- [ ] Break `staging` in some way as if things had gone wrong, practice recovery plan in `staging`
- [ ] Veryify what we restore is what we backed up in `staging`
- [x] Increase disk size (and possibly memory size) in `production`
- [x] Backup `production`
- [ ] https://github.com/GSA-TTS/FAC/issues/3365
- [x] Test search, links, etc. in `production`
- [ ] Eat a peanut butter and jelly sandwich.
- [x] Ticket adding 2018, 2017, 2016 to search options
- [x] Ticket adding code to display EIN if UEI is `GSA_MIGRATION`
- [ ] Ticket GSA_PDF_NOT_FOUND/default PDFs for missing PDFs.
- [ ] Ticket repeatable? loading test historical data into `staging`
- [ ] Ticket updating `cog/over` to use new `dissemination` data, and load it repeatably into the app.
```
```[tasklist]
### Tasks
```

**Comment by jadudm** [comment]
Calling this ticket "done." We completed the migration. There is more work to do, but that will be true for months to come. The data is in production and live. Its now time to start the next sprint. Congrats to the data team!
