### ISSUE TITLE
Validation: Loan Guarantee / Balance error improvement

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3302]
## Background

ZD: https://fac-gov.zendesk.com/agent/tickets/2095

When `Loan/Loan Guarantee` is `N`, we expect `Loan Balance` to be blank.

People sometimes put `0`s there.

This falls all the way through to the Jsonnet validations, and ends up saying "Loan/Loan Balance must be Y or N." Which... it is Y or N, and therefore this is confusing to the user.

We should instead say, when someone says `N` and `0`:

```
When loan or loan guarantee is `N`, the loan balance should be left blank.
```

```[tasklist]
### Tasks
- [x] Add a `check` at the frontend to handle this.
- [x] Get content approval re: suggested error message, edit this ticket or comment as needed to fix it.
- [x] Double-check our documentation (and update if necessary) to properly call out what should be done when `N` is chosen.
```

**Comment by jadudm** [comment]
@sambodeme , just checking:

https://github.com/GSA-TTS/FAC/pull/3335

Is this ticket friends with your PR? If the PR covered this, go ahead and close the ticket.

Many thanks!

**Comment by sambodeme** [comment]
Closed by #3335

**Comment by sambodeme** [comment]
> @sambodeme , just checking:
> 
> #3335
> 
> Is this ticket friends with your PR? If the PR covered this, go ahead and close the ticket.
> 
> Many thanks!

yes
