### ISSUE TITLE
Removing in-progress audits

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3346]
# At a glance
<strike>In the early days of the FAC</strike> Users often create a new submission, and then have to start again before it was complete. This has led to a large number of incomplete audits cluttering up their dashboard view, and they have no way to remove those audits. It makes work confusing for editors who are on many audits, and it further is confusing for certifying officials.

We could "just let people delete audits." However, that could lead to "good" or "in-progress" audits being deleted accidentally. Therefore, a workflow that looks something like the following may be desirable:

```mermaid
flowchart LR
    X[Dashboard] -->|Delete audit| B{more than 30 days?}
    B -->|Yes| C[Delete audit]
    C --> X
    B ---->|No| E{Auditee & </br> Auditor OK?}
    E -->|Yes| C[Delete audit]
    E -->|No| F[No action]
```

On one hand, we could allow anyone attached to an audit to "simply delete an in-progress audit." However, that could lead to mistakes, and requests to undelete, and a host of user support activities that we are not prepared or well positioned to handle. We might instead want to have a workflow that allows us to ask if an audit has been untouched for more than a month, and then go ahead with the delete. Or, if it is newer, to require that the certifying auditor and auditee each "approve" the deletion before it takes place.

This is more about developing an SOP, and supporting it in a documented way that is *right* for us and our users. Therefore, a first step is to figure out what the flowchart should *actually* look like. 

This work may be part of motivation to bring a workflow engine into the FAC.

-------

**In order to** better keep track of all the *actual* work in front of me
**as a** submitter
**I want** to remove partial/incomplete audits.

# Acceptance Criteria

### Scenario: As a busy auditor working as part of a team

**Given**   a dashboard view with many incomplete audits
**when**  I know I made a mistake and have to start a new audit
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] I can easily indicate that the audit should be removed/"deleted"
- [ ] The audit is "deleted"
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

Note this could become a nightmare for the helpdesk. Granted... the inability to delete audits is already a real problem for our users, and therefore our helpdesk.

We should probably not *actually* delete these audits. That said, leaving them in the `singleauditchecklist` table as incomplete submissions (with files attached, etc.) is also not good. Keeping data in our system that is not actually data of record is... probably a problem.

So. While our inclination might be to "keep" the audit in a shadow form, we should actually delete the data.

If we develop, as part of this, a way to run a regular workflow (daily, weekly, etc.) that allows us to 

1. Mark an audit for removal.
2. Remove it some number of days/weeks later.

then that would be fine. But, keeping data that a user marks for deletion is not something we should do.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no security considerations to this.

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] [something we'll definitely have to do]
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by Leighdiddy** [comment]
Closing due to repetition with #4434
