### ISSUE TITLE
Search updates (year, cog/over)

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3362]
```[tasklist]
### Tasks
- [ ] We should have an `ALL` button in the year selection.
- [ ] On page load, pre-select 2023.
- [ ] We should add `Cog or Over` in addition to `Cognizant` or `Oversight` to the existing dropdown
- [ ] Fix "Other ALN" behavior
``` 

* Clicking "ALL" clears other years.
* Clicking another year clears "ALL"
* Clicking a year does not change other years.

The new Cog/Over option does a search where we are *either* cognizant *or* oversight.

We currently say "Other ALNs" is any other *agency*. However, there are users who are looking at ALNs within their *operating division*, and other ALNs in their agency "are not theirs." We should make "Findings Other ALNs" "do the right thing."

**Comment by jadudm** [comment]
For discussion: given that we often rely on the ALN in search, do we need an ALN column, computed or otherwise, on the Federal Awards table. It's a significant change, but perhaps it is necessary? Don't know.

**Comment by jadudm** [comment]
This is now out-of-date given other high-priority work on search. Closing as not planned.
