### ISSUE TITLE
📍 Next steps in data migration

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3364]
```[tasklist]
### Tasks
- [ ] Documentation around migration
- [ ] https://github.com/GSA-TTS/FAC/issues/3391
- [ ] https://github.com/GSA-TTS/FAC/issues/3408
- [ ] Discuss bringing in historic SAC objects, how/when. (Also, PdfReportFile)
- [x] Finish the ADR
- [ ] https://github.com/GSA-TTS/FAC/issues/3390
- [ ] https://github.com/GSA-TTS/FAC/issues/3406
- [ ] https://github.com/GSA-TTS/FAC/issues/3831
- [ ] Bringing migration status/inspection records into the live app and add to API
- [ ] Discuss/research how to surface this to users in the WWW?
- [ ] https://github.com/GSA-TTS/FAC/issues/3402
- [ ] https://github.com/GSA-TTS/FAC/issues/3413
- [ ] https://github.com/GSA-TTS/FAC/issues/3506
- [ ] https://github.com/GSA-TTS/FAC/issues/3515
- [ ] https://github.com/GSA-TTS/FAC/issues/3524
- [ ] https://github.com/GSA-TTS/FAC/issues/3528
- [ ] https://github.com/GSA-TTS/FAC/issues/3539
- [ ] https://github.com/GSA-TTS/FAC/issues/3544
- [ ] https://github.com/GSA-TTS/FAC/issues/3545
- [ ] https://github.com/GSA-TTS/FAC/issues/3546
- [ ] https://github.com/GSA-TTS/FAC/issues/3558
- [ ] https://github.com/GSA-TTS/FAC/issues/3682
- [ ] https://github.com/GSA-TTS/FAC/issues/3681
- [ ] https://github.com/GSA-TTS/FAC/issues/3201
- [ ] https://github.com/GSA-TTS/FAC/issues/3696
- [ ] https://github.com/GSA-TTS/FAC/issues/3686
- [ ] https://github.com/GSA-TTS/FAC/issues/3700
- [ ] https://github.com/GSA-TTS/FAC/issues/3687
- [ ] https://github.com/GSA-TTS/FAC/issues/3701
- [ ] https://github.com/GSA-TTS/FAC/issues/3688
- [ ] https://github.com/GSA-TTS/FAC/issues/3704
- [ ] https://github.com/GSA-TTS/FAC/issues/3689
- [ ] https://github.com/GSA-TTS/FAC/issues/3707
- [ ] https://github.com/GSA-TTS/FAC/issues/3691
- [ ] https://github.com/GSA-TTS/FAC/issues/3709
- [ ] https://github.com/GSA-TTS/FAC/issues/3694
- [ ] https://github.com/GSA-TTS/FAC/issues/3710
- [ ] https://github.com/GSA-TTS/FAC/issues/3692
- [ ] https://github.com/GSA-TTS/FAC/issues/3722
- [ ] https://github.com/GSA-TTS/FAC/issues/3693
- [ ] https://github.com/GSA-TTS/FAC/issues/3724
- [ ] https://github.com/GSA-TTS/FAC/issues/3695
- [ ] https://github.com/GSA-TTS/FAC/issues/3723
- [ ] https://github.com/GSA-TTS/FAC/issues/3697
- [ ] https://github.com/GSA-TTS/FAC/issues/3720
- [ ] https://github.com/GSA-TTS/FAC/issues/3698
- [ ] https://github.com/GSA-TTS/FAC/issues/3718
- [ ] https://github.com/GSA-TTS/FAC/issues/3699
- [ ] https://github.com/GSA-TTS/FAC/issues/3717
- [ ] https://github.com/GSA-TTS/FAC/issues/3702
- [ ] https://github.com/GSA-TTS/FAC/issues/3716
- [ ] https://github.com/GSA-TTS/FAC/issues/3703
- [ ] https://github.com/GSA-TTS/FAC/issues/3715
- [ ] https://github.com/GSA-TTS/FAC/issues/3705
- [ ] https://github.com/GSA-TTS/FAC/issues/3713
- [ ] https://github.com/GSA-TTS/FAC/issues/3706
- [ ] https://github.com/GSA-TTS/FAC/issues/3712
- [ ] https://github.com/GSA-TTS/FAC/issues/3708
- [ ] https://github.com/GSA-TTS/FAC/issues/3711
- [ ] https://github.com/GSA-TTS/FAC/issues/3732
- [ ] https://github.com/GSA-TTS/FAC/issues/3733
- [ ] https://github.com/GSA-TTS/FAC/issues/3763
- [ ] https://github.com/GSA-TTS/FAC/issues/3772
- [ ] https://github.com/GSA-TTS/FAC/issues/3804
- [ ] https://github.com/GSA-TTS/FAC/issues/3817
- [ ] https://github.com/GSA-TTS/FAC/issues/3856
- [ ] https://github.com/GSA-TTS/FAC/issues/3865
- [ ] https://github.com/GSA-TTS/FAC/issues/3866
- [ ] https://github.com/GSA-TTS/FAC/issues/3884
- [ ] https://github.com/GSA-TTS/FAC/issues/3885
- [ ] https://github.com/GSA-TTS/FAC/issues/3896
- [ ] https://github.com/GSA-TTS/FAC/issues/3917
- [ ] https://github.com/GSA-TTS/FAC/issues/3927
- [ ] https://github.com/GSA-TTS/FAC/issues/3928
- [ ] https://github.com/GSA-TTS/FAC/issues/3945
- [ ] https://github.com/GSA-TTS/FAC/issues/3951
- [ ] https://github.com/GSA-TTS/FAC/issues/3954
- [ ] https://github.com/GSA-TTS/FAC/issues/3955
- [ ] https://github.com/GSA-TTS/FAC/issues/3960
- [ ] https://github.com/GSA-TTS/FAC/issues/3980
- [ ] https://github.com/GSA-TTS/FAC/issues/4008
- [ ] https://github.com/GSA-TTS/FAC/issues/4114
```

**Comment by sambodeme** [comment]
Link to original epic https://github.com/GSA-TTS/FAC/issues/2837
