### ISSUE TITLE
Documentation regarding historical migration

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3368]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** understand the history of an auditee
**as a** resolution official
**I want** to know what the FAC's data means

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

### Scenario: I've downloaded an SF-SAC that includes mention of `GSA_MIGRATION`

**Given**   that I know `GSA_MIGRATION` looks *wrong*
**when**  I am in search results or on fac.gov
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] I can find a section of the site related to the historical data migration.
- [ ] The website helps me understand what `GSA_MIGRATION` means if I find it in an SF-SAC download
- [ ] The documentation tells me how/why this came to be
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: @James-Paul-Mason 
* Engineering shepherd: @phildominguez-gsa 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

We have no documentation online about the migration at this time. 

Given that it *looks like* we've changed data (because there are fields that now say `GSA_MIGRATION`), we need to provide documentation to users.

This documentation will not be complete on the first pass. It needs to have *enough* to make clear what is going on, and we need to then iterate on the documentation to expand it. For example, this documentation should focus on the web-based user's experience. 

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

None

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] [something we'll definitely have to do]
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by danswick** [comment]
Between https://www.fac.gov/api/differences/ and https://www.fac.gov/api/dictionary/, I think the spirit of this ticket's "first pass" requirement is complete. There is more work to do at some point, but that will need to be scoped.
