### ISSUE TITLE
As an auditor, I want to check for errors in the SF-SAC data before I submit my audit so that I can be sure my audit is correct and will be accepted.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#337]
### Background

This story covers the initial design of the UI for how auditors/auditees will check their SF-SAC data for errors. You can find it in the story map [here](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1649157107497)

This issue covers only the happy path where there are no errors in the form data. It **does not** cover the design of error messages/path to how folks will resolve errors. 

Finalizing this work is dependent on finalizing our decision how we'll have people input the data, but we can mock up how it might look under each option. 

### Acceptance criteria (We'll know we're done when...)

- [ ] When we've designed how a user specifies that they are done with entering the SF-SAC data. 
  
### Tasks

- [ ] Refine mocks based on sprint 6 research insights. 
- [ ] Further define what needs to happen at this step wrt "locking" or signaling to others who have access that this part is "done"
- [ ] Write implementation notes 
- [ ] Engineering engineers all the things

### Definition of Done

- [ ] Meets acceptance criteria
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

**Comment by MelissaBraxton** [comment]
This is what the UI looks like in the current FAC:
<img width="534" alt="Screen Shot 2022-07-11 at 3 13 01 PM" src="https://user-images.githubusercontent.com/20651166/178367573-301247a2-ea77-4d40-9d47-cb1184425f44.png">

**Comment by sreuber** [comment]
@melchoyce @austinhernandez @MelissaBraxton Could use eyes on this one to check. https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3723%3A17342

Going back to our discussion earlier in the week, I agree that handling error checks at each page level would be ideal if we stick with static Excel documents…much easier for the user. Can we float this to the backend folks to see how difficult this is?

**Comment by austinhernandez** [comment]
Yeah, I guess I'm seeing since this is a non-linear form, with several potential editors, there is no good way to do a validation per-page. The only thing I can think of is the ! icon if there is an error or missing field even before you  run the check for errors function.

I like the change of `re-run error check` because on the current system, it's not clear.

Adding this error content screen in here as well.

![Screen Shot 2022-07-15 at 12 16 59 PM](https://user-images.githubusercontent.com/23194720/179290964-5c21acc1-9dff-4815-8086-b0d2b03b0d4e.png)

**Comment by sreuber** [comment]
Per-page check before a first error check is a no-go. With that, my intention for the icons is to only show after the error check has been run , with errors also appearing on the pages as reminders so users don't have to repeatedly bounce back to the Finalize page

What does "Download errors" do? Is that the printable sheet?

**Comment by austinhernandez** [comment]
Sorry I missed this on Friday. Yes, it is a TXT file (and the thing they reference and/or print off if the errors list is long enough). Here's an example:
[Errors_939014.txt](https://github.com/GSA-TTS/FAC/files/9132950/Errors_939014.txt)
 
I'm not sure if it needs to be a TXT file. a print dialog box would make sense if you just need to reference for later

**Comment by sreuber** [comment]
The question is the error messages on the other pages, not on the Finalize page itself. I figured that would be simpler.

**Comment by erinzstrenio** [comment]
I made some suggested edits to the error messages (from the TXT file) in [this Google doc](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#heading=h.qxh1fnjvsw9m) — ready for peer review and if all looks good, these can replace the messages in the TXT file.

**Comment by melchoyce** [comment]
With the error copy editing, anything else we need to do here before passing off to devs?

**Comment by melchoyce** [comment]
@petermarks-gsa Let's move this to dev and create any follow-up design issues as needed.

**Comment by petermarks-gsa** [comment]
@melchoyce This appears to be covered in https://github.com/GSA-TTS/FAC/issues/412. Suggesting we close. cc @tadhg-ohiggins
