### ISSUE TITLE
Improve search to find results in `GSA_MIGRATION` fields

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3372]
# Story 

We flagged values as `GSA_MIGRATION`. For example, there are cluster names (which... we can't search on, so that's a bad example)... there may be entity names that are `GSA_MIGRATION`? 

OK. 

```[tasklist]
### Tasks
- [x] Determine if any searchable fields might contain `GSA_MIGRATION`
- [x] Estimate how many values in those fields are `GSA_MIGRATION`
- [ ] Propose how we do/do not make those records searchable, given that `GSA_MIGRATION` has supplanted a value.
```

This may be a non-issue.

Note that the API can now be used to do this kind of work.

For example, if you're asking "How many `cluster_name` fields have GSA_MIGRATION in them," the you could write a short script using the API:

```
res = response.get("https://api.fac.gov/federal_award?cluster_name=...&year=2022&report_id=...")
```

### Additional context from #3307 

Here are a few related ideas from another issue that we should fold in to the above:

1. Search results should use our accepted/standard language for "accepted date," whatever that is. (See Slack convo.)
2. Cog/over needs to link to a page on our static site that explains what it is, and provides a list of agency numbers and NSAC email addresses. Or, the PDF with this information should be on that page. Either way, this is useless/unusable as-is. 
3. UEI or EIN needs to actually be either.
    1. If the UEI exists, and is not `GSA_MIGRATION`, show that.
    2. If the UEI is `GSA_MIGRATION`, show the EIN.
    3. If both are `GSA_MIGRATION`, show `GSA_MIGRATION`
4. Add the time the search took to the top of the search results. "Results: 10314, 7.2 seconds"
5. Add 18, 17, 16 back to the year selection. The data is coming.

**Comment by jperson1** [comment]
Here are some changes we might make, depending on what might be useful to users and what might be "too much". These are all implemented in branch [jp/search-gsa-migration-fields](https://github.com/GSA-TTS/FAC/tree/jp/search-gsa-migration-fields), so one could mess around with them if they wanted. 

1. `auditee_uei` - We can include a flag ("Include missing UEIs?") This appends "GSA_MIGRATION" to the UEI search. 
    * This means that JUST selecting the flag and including some UEIs will bring back any and all audits with UEI "GSA_MIGRATION", which might be a lot more than expected if a user doesn't further narrow their search
    * Combining this with other fields can be useful. But, I'd wager that if the user is including other fields, they can already narrow their search down far enough without including the UEI fields. 
2. `passthrough_name` - We can include a similar flag ("Include missing names?") This also just appends "GSA_MIGRATION" to the name search.
    * In this case, there are few enough passthroughs with missing names that it may be helpful to include. I think it's also more likely that a user makes use of another search field alongside this one, so it doesn't get as many spam results.
3. `federal_award_extension` - When searching on a full ALN, we can always include the "GSA_MIGRATION" extensions, since we don't know for sure what they are. 
    * For example, searching on ALN `12.600` gives 219 resulting reports. By including the placeholder extension "GSA_MIGRATION", we see 389 resulting reports. 
    * This is especially helpful because a user can't intuitively search on `12.'GSA_MIGRATION'` or something. Currently there's no way to get these audits when searching on a full ALN. One has to search for ALN `12` and then filter out everything they don't want.

**Comment by danswick** [comment]
When the final ~3000 records make it to dissemination, there will likely be more `GSA_MIGRATION` fields. We probably also want to tie this work into a larger story around migration in general.

**Comment by jperson1** [comment]
I re-ran the script from [here](https://github.com/GSA-TTS/FAC/issues/3372#issuecomment-2115379296) with some minor tweaks. 

With the final records in the dissemination tables, nothing big has changed. The fields that had `GSA_MIGRATION` present show more hits, which is expected, and no new fields were hit by the change. None that we search on, at least. Perhaps more fields contain them, but they don't affect search for the end user. 

The one thing worth noting is that the number of `federal_award_extension`'s that contain `GSA_MIGRATION` has just about doubled to 7083. Because we can search on either the prefix _or_ the prefix with the extension, I still don't think this warrants a dedicated button. 

Overall, I think my recommendations from [above](https://github.com/GSA-TTS/FAC/issues/3372#issuecomment-2145491644) still hold. Dedicated buttons for the UEI and passthrough name fields to include the migrated data, and a slight change to how ALN searches work.

**Comment by jperson1** [comment]
Closing this as it's stale!
