### ISSUE TITLE
Create a documented subset of public data for devs to use locally

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3373]
#Story 

This may already exist.

We have found that there is a difference between three audits in a local database and 200K. 

We need a dump of our dissemination tables that contains _only public data_. We want the dissemination (and migration record, and singleauditchecklist) tables so that devs can be doing work that is demonstrated to work well with ~2.5M federal awards (as opposed to a few hundred). Search, Excel generation, etc. all are performance-bound on our database size.

```[tasklist]
### Tasks
- [ ] Export into Pgres SQL format (INSERT only) data of the above shape
- [ ] Document how to load into a local instance, preferably with a short `bash` script
- [ ] Put the docs and script(s) in `tools` at the top level of the repo, and the files in GDrive
``` 

For example, it is OK if the solution is, with a live local stack:

1. `cd` into `tools/load-public-dissemination-data`
2. Put SQL files into `tools/load-public../sql`
3. Run `load-all.bash`

You may need to put a placeholder file in the `sql` directory so that `git` will commit the directory.

This way, it is easy for us to, after standing up a clean instance, to run a single command (which may be a sequence of `psql` statements) that load millions of rows of data into our local, dockerized development stack.

**Comment by jadudm** [comment]
This is _mostly_ done, thanks to work done by SK before heading out.

We don't have a way to easily load in all environments, but it is possible to download the data from GDrive and load all the data locally.

**Comment by danswick** [comment]
This is basically done and the follow-up tasks are tracked in other issues now.
