### ISSUE TITLE
As an auditor, I need to be able to upload my audit report as a pdf so that I can complete my audit.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#338]
### Background
This issue covers the initial design of the interface for where auditors will upload a pdf audit report. You can find it in the story map [here](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1647627056111). 

We'll have to create additional issues to cover the front and back end implementation of this. This issue **does not** cover:

-  the back end pdf validation work that will be needed to implement this (needs issue)
- Error messages in the event there's an issue with uploading their pdf (needs issue)

Additional stories covered in this:

1. As an auditor I need to check that all audit report components are included in my audit report so that I can submit a complete audit that will be accepted.
3. As an auditor, I need to upload a CAP as a separate document so that my submission meets uniform guidance.
3. As an auditor, i need to ensure that my audit report contains no PII before I submit.  
4. As an auditor, I need to be sure the audit report I upload is for the entity UEI for which I created the audit submission.  

^ These user needs are not being met by the current UI. These are currently being caught by Census processors as part of their manual check. In this issue, we want to design how we might better support auditors in checking these things prior to upload. This is related to our recommendations re: processing in #219 

### Acceptance Criteria (We'll know we're done when...)

- [x] We've designed a way for auditors to upload a pdf of their audit report.

### Tasks
- [x] Explore whether this should be its own page or not?
- [ ]Mock screens
- [x] Add implementation notes
- [x] Tag a peer in to review

**Comment by MelissaBraxton** [comment]
Here's what it looks like in the current FAC:


<img width="534" alt="Screen Shot 2022-07-11 at 3 13 01 PM" src="https://user-images.githubusercontent.com/20651166/178367573-301247a2-ea77-4d40-9d47-cb1184425f44.png">

**Comment by melchoyce** [comment]
@MelissaBraxton Do you have access to this page? Wondering if we can see what's in "Compliant PDF Instructions" and get a copy of the content in text form.

**Comment by MelissaBraxton** [comment]
Here they are! [create_pdf.pdf](https://github.com/GSA-TTS/FAC/files/9106112/create_pdf.pdf)

**Comment by MelissaBraxton** [comment]
Also, it appears as though the current system handles the Uniform Guidance requirement to upload CAP text as a separate doc by asking people to call out the page it starts on as part of the combined pdf (so it's kinda not "separate." It's part of the combined pdf--appended to the audit report). 

The current system has a step that asks folks to specify which page each of their audit components start on. Two needs this helps meet: 

1. Need for auditors to make sure they've included all components (which we've also listed as part of the scope of this issue--TBD how we go about meeting this need tho--I imagine we can come up with something a bit different!) 
2. Need for processors to double check that each component is actually there (we will not have manual processing in the same way, so we don't need to worry about this)  

Here's what it looks like now:
<img width="668" alt="Screen Shot 2022-07-13 at 2 21 08 PM" src="https://user-images.githubusercontent.com/20651166/178841195-75c11d2a-e87f-4690-b802-3118da9e7baa.png">

**Comment by MelissaBraxton** [comment]
For reference, here is the language re: the legal requirement for CAP text to be "separate." 
<img width="697" alt="Screen Shot 2022-07-13 at 2 39 50 PM" src="https://user-images.githubusercontent.com/20651166/178841510-9e293e9e-375a-4baa-b93b-f678c933357c.png">

**Comment by melchoyce** [comment]
One quick thing I just noticed, should this "check..." be a link? 

![Screen Shot 2022-07-14 at 2 23 07 PM](https://user-images.githubusercontent.com/2846578/179055046-eb4cb800-3bbb-45a5-8b32-bb228e7e28b7.png)

**Comment by austinhernandez** [comment]
Oh ya. I just removed that text entirely bc the PDF upload will validate (no need for a checker)

![Upload PDF](https://user-images.githubusercontent.com/23194720/179065809-cab89c6d-9a77-4b19-8e23-5fab1c047a8b.png)

**Comment by petermarks-gsa** [comment]
@austinhernandez I've gone ahead and created an implementation ticket for this: https://github.com/GSA-TTS/FAC/issues/360

Are there any implementation notes for this? Curious about required text / file upload fields. I understand exact error copy might be out of scope here, could possibly use some guidance on other parts of acceptance criteria.

**Comment by austinhernandez** [comment]
The implementation notes are: 
- Erin is working on content so final navigation is pending IA/tree testing and error text will come after
- The requirement for the required fields are in the helper text: "Enter the starting PDF page number for each of the components listed below. Each required component on the checklist must have a numeric page number, unless otherwise noted below." 
- A PDF has to pass a validator check, what that entails is TBD

**Comment by melchoyce** [comment]
@MelissaBraxton Do you think the new copywriting issues cover your note about error messaging:

> Error messages in the event there's an issue with uploading their pdf (needs issue)

...Or do we still need to follow up with a new issue?

**Comment by melchoyce** [comment]
Let's assume error messages will be covered by #381, and move this forward.

**Comment by petermarks-gsa** [comment]
Next steps captured in https://github.com/GSA-TTS/FAC/issues/404. Closing this.
