### ISSUE TITLE
As a someone who has access to a draft audit submission, I need a way to submit my certified audit package to the FAC. 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#339]
### Background
This issue covers the design of the UI that enables users to submit their certified audit submission to the FAC (or otherwise move into "accepted" status in the DB in the case of tribal entities who choose to suppress their data). The scope of this issue also includes the design of a confirmation message users will see when their submission has been accepted. You find this on the story map [here](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1657579345801).

This is a breakout of issue #260. This issue covers the design of the UI users will see on clicking submit to FAC for processing from [the audit start page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3136%3A18722). 

**accepted status** = FAC has accepted the submission and the entity's regulatory obligation to submit audit data has been fulfilled. The submission is made public

### Acceptance Criteria (We'll know we're done when...)

- [ ] We have mocks, including implementation notes, ready to hand off to engineering. 

### Tasks

- [ ] Design
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by austinhernandez** [comment]
@MelissaBraxton i made you the certifying auditor on my test project so that i can look at what the current certification process is like. when you get a chance can you go through the auditor process to certify?

**Comment by austinhernandez** [comment]
ready for peer review @sreuber @MelissaBraxton @melchoyce!

on figma: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3736%3A17737

![image](https://user-images.githubusercontent.com/23194720/180056336-8f72241e-9fac-4db8-b37c-69d4a2f49f5b.png)

- I changed the submission process to a modal instead of a page
- I wanted feedback around the CTAs after submission
- I wanted to make sure that the status changes to "submitted" on the my audit submission home page (final page)
- I have a coworking session today to talk about firstname lastname display because im not sure that field would be here and if we need to capture that information manually for people if their info isnt coming from login.gov

**Comment by sreuber** [comment]
The first/last names should be automatically pulled from login.gov is my understanding. We just don't want manual entry for those fields, so they don't conflict with what login.gov already has.

**Comment by melchoyce** [comment]
Looks good to me 👍 

Spitballing: would it work to cut the second, "Submission Complete" modal and display the confirmation as a notice on the "My audit submissions" page instead?

**Comment by austinhernandez** [comment]
@melchoyce — Thats a great idea! Way better options for what to do next. 

@erinzstrenio — tadhg confirmed that we wont have a way to `uncertify` (https://github.com/GSA-TTS/FAC/issues/394) so i think we need some language around that like "you dont see it in this list and its in the ether rn. 🙈  nothing u can do about it 🤷🏽 maybe find it on the legacy fac in the near future?  🤷🏽 🙃 " i think the emojis really add something, don't you?

on figma: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3736%3A17737

![image](https://user-images.githubusercontent.com/23194720/181546570-1d153ba8-c77a-4d68-be92-bf9cdd4434c8.png)

**Comment by erinzstrenio** [comment]
@austinhernandez updated content [here](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#heading=h.44u63rrv7phf) based on our design + dev sync chat yesterday

**Comment by jhansen-flexion** [comment]
see the slack thread about this issue here: https://gsa-tts.slack.com/archives/C1L58R804/p1659357013381369

**Comment by melchoyce** [comment]
So, sounds like this won't need any changes? In that case, anything left to do before moving this one forward to dev?

**Comment by austinhernandez** [comment]
- I did have to change having `submitted` as one of the statuses under my audit submissions. This has implications both for dev AND for other design screens
- I incorporated Erin's feedback and made some [suggestions for alternative copy](url). 
- I am still not clear what actions a user can take when clicking the submitted audit. I think it should be clear that it's no longer editable from that action and the text before it, but what does viewing it look like. It seemed like [the action item from Matt Jaded on Slack](https://gsa-tts.slack.com/archives/C1L58R804/p1659357013381369) was for design and/or PM to read 2CFR200 and the Single Audits Act of 1996 that can help guide questions we ask

![image](https://user-images.githubusercontent.com/23194720/182656741-72de17f3-3869-43a2-8558-2b94320e51e9.png)

on figma: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3736%3A17737

**Comment by melchoyce** [comment]
> * I am still not clear what actions a user can take when clicking the submitted audit. I think it should be clear that it's no longer editable from that action and the text before it, but what does viewing it look like. It seemed like [the action item from Matt Jaded on Slack](https://gsa-tts.slack.com/archives/C1L58R804/p1659357013381369) was for design and/or PM to read 2CFR200 and the Single Audits Act of 1996 that can help guide questions we ask

I'll make a follow-up issue to explore this 👍

**Comment by petermarks-gsa** [comment]
@melchoyce and @petermarks-gsa to discuss whether we can close this out and what next steps are.

**Comment by mogul** [comment]
@petermarks-gsa to review for closure

**Comment by petermarks-gsa** [comment]
@melchoyce @mogul @mogul I've reviewed this and have created an implementation issue slated for Milestone 6: https://github.com/GSA-TTS/FAC/issues/503
