### ISSUE TITLE
Cog/Over: Move this to our own dissemination tables

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3390]
To use GSAFAC dissemination tables that contain Census historic data for cog/over calculations instead of the old Census tables, a few files in the support directory need to be modified.
1. cog_over.py
2. test_cog_over.py
3. run_2022.py
4. Remove dissemination/hist_models.
5. Remove hist_models in dissemination/models.py.

**References:** 

- Carley's flowchart - https://app.mural.co/t/gsa6/m/gsa6/1688072157586/bacad68ed1da8805af45e5b7d89a07451e930d69?sender=5824f83a-c5b1-4b97-a227-7aab91a2040e

- FAC Pre release Cog/Over epic - https://github.com/GSA-TTS/FAC/issues/1218

```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/3398
- [ ] https://github.com/GSA-TTS/FAC/issues/3399
- [ ] https://github.com/GSA-TTS/FAC/issues/3400
- [x] Remove dissemination/hist_models
- [ ] https://github.com/GSA-TTS/FAC/issues/3401
```
