### ISSUE TITLE
As a user, I need to be able to change who has/modify users' access to a draft audit submission.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#340]
### Background
This story covers the design of the UI and flow for how folks who have access to a draft submission can modify the roles and access of other users.

This includes: 
 - Adding a user
 - Deleting a user
 - Changing the role of an existing user (like whether they are a certifier or whether they represent the auditor or the auditee)

Current thinking is that this is one of the administrative actions that folks will get to from the audit start page. #361

### Acceptance Criteria (We'll know we're done when...)
- [ ] We've designed a way for users who have access to a submission to add a user, delete a user, and change the role of a user who has access. 
- [ ] We've documented technical considerations / implications for user roles and permissions 

### Tasks

- [ ] Design
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by austinhernandez** [comment]
Looking for peer review / co-work help on this @MelissaBraxton @melchoyce @sreuber. I changed the mocks [based on a Slack convo about name handling](https://gsa-tts.slack.com/archives/C1L58R804/p1658167390607859) and the re-work done in #228. 

Report/Submission Access v1: basically copies the [Audit submission access page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3830%3A18127). Is there a reason the names should be uneditable at this point?
![Report Access v1](https://user-images.githubusercontent.com/23194720/179804057-20aaf56e-ea03-44f1-a1e2-c2514e1c777a.png)


Report Access v2: is more like the current FACs UI where the names are uneditable, only the roles are changeable. I think there's some logic confusion with needing to have certifying officials and being able to change roles. (eg deleting a certifying official and trying to save OR changing the role to something that's already selected.)
![Submission Access v2](https://user-images.githubusercontent.com/23194720/179804201-2d03d483-c674-4d53-9cfa-f86c19901784.png)

Add new user modal: Adding a new user / selecting permissions modal
![Add new user](https://user-images.githubusercontent.com/23194720/179804055-48007ddb-50a8-4973-9504-f7d7cc155d06.png)

**Comment by sreuber** [comment]
> Is there a reason the names should be uneditable at this point?

Per [here](https://gsa-tts.slack.com/archives/C1L58R804/p1658167390607859), the names are set in Login.gov already, and we do not want to overwrite those. Names can still display, but we don't want to have users entering them. Step 3 in the audit creation flow may have already been updated.

**Comment by austinhernandez** [comment]
Yes, thanks for the update @melchoyce —now it only asks for email and role, thats what I have here and doesn't display a name. That's what I used as a model for this page and what I have here.

[As per that thread](https://gsa-tts.slack.com/archives/C1L58R804/p1658167390607859) "we're NOT keeping names for people invited in to audit/view it." So, in order to collect/display names for everyone, we would have to add back a field for manual entry for people invited to view it, and make it uneditable for the names that got set in Login.gov. That's where it gets a little confusing for me, especially if you want to change roles.


ALSO — 
On the original FAC, Adding a user, deleting a user, changing the role of an existing user (like whether they are a certifier or whether they represent the auditor or the auditee) are different pages on the audit start page side nav. [In the detailed user flow MURAL](https://app.mural.co/t/gsa6/m/gsa6/1654109929324/5da173ea5f7ba75104e4e624451e58496a7164c8?invited=true&sender=austinhernandez5199), all of these actions happen on 1 screen.

**Comment by sreuber** [comment]
There's several other statements in that thread that contradict that though, so we should definitely get that clarification. My questions would be: Don't users coming to the audit home page to audit/view still need a login regardless? Do all login users have a first/last name associated with them? If both of those are the case, I don't see why they can't pull those names from login to display.

**Comment by austinhernandez** [comment]
Yup just talked to him! I have a better sense of what's feasible and I'm currently working on this

TO DO:
Need to figure out rules for email address / roles (eg same email address cant be both certifier auditee and certifier auditor, etc.)

Questions:
- Can they cant be left blank?
- Is this picked up on the "check errors / finalize" page or which validation is at a page level?
- They can be left blank on the [Audit submission access page]( https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3830%3A18127) and here but would probably be picked up in check errors /finalize section

**Comment by austinhernandez** [comment]
Also linked in #361 

on figma here: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4034%3A19388

![image](https://user-images.githubusercontent.com/23194720/180519203-6c2f121d-63f2-4fa3-ae6d-cb3a23e8ee45.png)

notes:
- Email address fields are not editable on the submission access page, you must click the add or change button below each row to open the "Add / change..." modal
- Each role (Auditee certifying official, Auditor certifying official, Auditee, or Auditor) has its own add/change button is unique to the section, so no role selection is needed. 
- Since you can have only one "certifying official," the CTA is “Change contact," since you can have multiple auditees and auditors, the CTA is "Add another contact"
- `Add another contact` and `change contact` links open a modal which will ask for email address and confirm/re-enter email field
- You can shift the roles around on the page without adding a new user
- clicking on the `role` dropdown and changing the role moves the row to another section
- In the Auditee certifying official and Auditor certifying official sections, `Delete user` button clears the email address field
- In the Auditee and Auditor sections, `Delete user` button in the first row deletes the email address field, in the subsequent rows (in the case of multiple auditees/ors) `Delete user` button deletes the entire row  and `add another contact` link moves under the row above


Question:
- what is the role of the person who created the submission in the first place? does this need another field? 
- What  will all the potential error states will be? I am pretty sure some fields can be left blank, but they will show up if a user tries to check for errors and finalize. 
- Does there need to be formatting validation? There has to be some validation logic (eg can't have the same contact for both certifying officials).

**Comment by melchoyce** [comment]
This is great. I think it might be complicated enough to warrant a little clickable prototype, just to demonstrate the behavior described in the implementation notes. Does that seem overkill?

> what is the role of the person who created the submission in the first place? does this need another field?

Do we know if the audit creator has a role in the Census FAC? @tadhg-ohiggins I think you brought up this question, and I'm wondering if there's any way of figuring that out on the dev side.

If not, my feeling is whoever made the audit should be the "owner" and have full administrative rights. If they enter their own email into the certifying/auditor/auditee fields, we should probably just let them, and since they're already the highest permission level, probably not make any change. Does that make sense?

> What will all the potential error states will be? I am pretty sure some fields can be left blank, but they will show up if a user tries to check for errors and finalize.
> Does there need to be formatting validation? There has to be some validation logic (eg can't have the same contact for both certifying officials).

If you can leave fields blank and come back to them later, then we should probably _only_ validate that when an address is entered, it matches some form of email address.

Questions:
- Do you think it's worth adding an "are you sure?" alert when deleting a user?
- Maybe "remove user" might be a better label? Since you wouldn't be deleting their account, just removing their access to that role. @erinzstrenio what do you think?

**Comment by erinzstrenio** [comment]
@melchoyce Agreed that "remove user" is more clear for that label

**Comment by austinhernandez** [comment]
i changed the label to `remove user` AND added some prototype logic (which helped me think thru some edge cases). id love an extra set of 👀 on what to do when you remove a certifying official (which is mandatory for submission but will not prevent you from leaving this page)

on figma here: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4034%3A19388

**Comment by melchoyce** [comment]
The flow looks good to me. I definitely think we'll want to test this once it's built, since it requires a lot of email/position wrangling, but for now I think we're good to move forward with what you have.

**Comment by petermarks-gsa** [comment]
Next step: @petermarks-gsa to create implementation issue

**Comment by petermarks-gsa** [comment]
@austinhernandez @melchoyce Upon reviewing this, I think there are a couple things worth clarifying before we create an implementation issue: 

* This open question in the implementation notes seems important: "What is the role of the person who created the submission in the first place? does this need another field?"
* Regarding the open questions around error states, this question seems important: Can people be in more than one section at a time, I.e. is it legit to have the same person listed as an Auditee contact and an Auditee certifying official?

**Comment by petermarks-gsa** [comment]
@melchoyce @austinhernandez Here is a recap of clarity we got [from Census on 8/18](https://docs.google.com/document/d/1DxuyVOusBIIRrXCaOmmzQp-Q54bthuSirmwR4j4jTbc/edit#) and some next steps I'm proposing: 

> This open question in the implementation notes seems important: "What is the role of the person who created the submission in the first place? does this need another field?"

We learned that the current Census system does not designate a special role to the person who created the submission and does not allow you to change your own role. 

**My for next steps is to decide on and design one of the following options:** 

1. Create a separate "submission creator" role with the same permissions as "auditee" and "auditor" roles. This could be worthwhile if we think we'll need to continuously differentiate between auditee and auditor users. 
2. Consolidate equivalent "submission creator", "auditee" and "auditor" into a general "has access" sort of role. This could be a worthwhile simplification if we don't think we'll need to continuously differentiate between auditee and auditor users and if we think users could be confused by multiple roles that don't have a functional difference between them. 

> Regarding the open questions around error states, this question seems important: Can people be in more than one section at a time, I.e. is it legit to have the same person listed as an Auditee contact and an Auditee certifying official?

In the current application, it sounds like it's essentially not legit to have someone in multiple roles:

**Recommended next step**: Articulate what happens if you try to save this screen with someone in two roles. Is there error message on submission or selection? 

> What happens when you deactivate someone? Does it delete them from the database? 

We learned that in the current application, deactivating a user removes their access to the submission, but not the user’s record. They might have access to other submissions.  There’s no screen for deactivated users. Not common to reactivate people. 

**Recommended next step**: Change the copy of the delete button in the design from "delete user" to "deactivate" or "remove access". Advise on whether there should be warning copy.

**Comment by petermarks-gsa** [comment]
Notes from discussion at design sync today:

* We're unsure if we want to move forward with either of the options I proposed to clarify role of submitter. Given that it's vague in the current FAC, we believe it may be okay to not display the submission users. We could still show the name of the submission creator user in other places of the app, just not in the access page. Per @austinhernandez, we'll continue exploration in this area so moving this to "in progress"
* Per @melchoyce, sounds like we'll update the designs to clarify where error messages go here. 
* button copy is updated in [newest mockups](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4034%3A19388)

**Comment by austinhernandez** [comment]
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4738%3A22029

Ok. We made a number of changes to this ticket because we _just_ figured out that the certifying officials are a required field on the submission access page during the new audit creation process. 
![image](https://user-images.githubusercontent.com/23194720/189924991-6a1106f7-79b7-460c-9805-6e13584d9403.png)

Sooooo, we had to change some interactions and error messages. 
### New interaction notes
- Since you can have only one "certifying official" and they are a required field, the CTA is “Change user," and you have to add a valid email address (error message below)
- We also added the account creator as it's own role. 
  - The current FAC, does not show the audit submission creator user on the list of roles/users and [according to census](https://docs.google.com/document/d/1DxuyVOusBIIRrXCaOmmzQp-Q54bthuSirmwR4j4jTbc/edit#bookmark=id.8owbjdpuo8jv), the system does not allow you to change yourself and they do not have a special role they have because they start the form.
- Clicking on the role dropdown and changing the role moves the row to another section, but moving a certifying official [generates an inline error](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4755%3A22617) (more on errors below)
- I also made a new page for what will happen if the certifying officials are added during the submission creation process but the auditee/auditor contacts are blank


### Old notes that are still applicable
- Email address fields are not editable on the submission access page, you must click the add or change button below each row to open the "Add / change..." modal
- Each role (Auditee certifying official, Auditor certifying official, Auditee, or Auditor) has its own add/change button is unique to the section, so no role selection is needed.
- Since you can have multiple auditee contacts and auditor contacts, the button is "Add another contact"
- Add another contact and change contact links open a modal which will ask for email address and confirm/re-enter email field
- You can shift the roles around on the page without adding a new user
- Clicking on the role dropdown and changing the role moves the row to another section
- In the Auditee and Auditor sections, `remove user` button in the first row deletes the email address field, in the subsequent rows (in the case of multiple auditees/ors) remove user button deletes the entire row and add another contact link moves under the row above


### Error messages:
- On the [Manage user access - moved certifying auditee page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4755%3A22617) "You must enter an email address..." error message only occurs when you move someone from a certifying role (either auditee or auditor) into another role.
- On [Modal - duplicate error](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4706%3A21287) Error message only occurs when you try duplicating contacts
- On [Modal - invalid email address](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4762%3A21741) Error message only occurs when you try putting in an incorrect email address format (no @ or .domain, etc.)
- On [Modal - email address required](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4764%3A21782) Error message only occurs when you try submitting a blank form


- Question: 
Even tho Census doesn't designate a special role or allow you to change the account creator, **do account creators have access to the submission even if they don't add themselves to the submission access page**? 
  - I thought no contacts were required when you create a submission, which means that it's essentially unassigned to anyone _except_ the account creator by default. BUT, since certifying officials _are_ required when you create a submission that means that it is assigned to people before a submission gets created. 
  - I don't think we should default the account creator to a role, that can get confusing because it's more of an opt-out vs opt in action, but from what I understood, an account creator has access even if they don't designate themselves
  - Is this correct? I think we need to ask a clarifying question on the Census call when we do a design demo. 
<img width="838" alt="Screen Shot 2022-09-13 at 11 11 25 AM" src="https://user-images.githubusercontent.com/23194720/189939063-a7855eda-0b8e-4d0d-a2a3-818c143ce71e.png">

**Comment by melchoyce** [comment]
Following up on this after our Census call:

> Even tho Census doesn't designate a special role or allow you to change the account creator, **do account creators have access to the submission even if they don't add themselves to the submission access page**?

We heard that yes, account creators have the same permissions as non-certifying auditees and auditors.

> * I thought no contacts were required when you create a submission, which means that it's essentially unassigned to anyone _except_ the account creator by default. BUT, since certifying officials _are_ required when you create a submission that means that it is assigned to people before a submission gets created.

Pretty sure this is also yes? But let me know if I'm getting that wrong.

> * I don't think we should default the account creator to a role, that can get confusing because it's more of an opt-out vs opt in action, but from what I understood, an account creator has access even if they don't designate themselves 

This was correct, and Mark mentioned we can't assume whether the account creator is an auditee or auditor, and therefore cannot assign them to a role automatically. He mentioned that account creators will often assign themselves to the appropriate role.

**Comment by petermarks-gsa** [comment]
@melchoyce @austinhernandez I've captured this into an implementation ticket: https://github.com/GSA-TTS/FAC/issues/499. Closing as done. cc @tadhg-ohiggins @mogul
