### ISSUE TITLE
Page Object Model for Cypress Test suite

### ISSUE THREAD

**Issue by eazapata23** [GSA-TTS/FAC#3485]
# Overview:
Based off of issue #3458 The idea was brought up to look into implementing Page Object Model(POM) starting with Search Page as a starting point.

# Objective:
Implement the Page Object Model(POM) for the Search Page to enhance code maintainability and reusability.

# Scope: 
Create page objects for web elements and actions related to the Search Page. After that is done, do the same for the rest of cypress test suite. 

# Acceptance Criteria:

1. Page Objects are successfully created for all relevant elements on the Search Page.
2. Implement POM for rest of Cypress test suite.
3. Methods for common actions are implemented and tested.
4. Code is reviewed and approved by a team member.

### Tasks

```[tasklist]
- [ ] https://github.com/GSA-TTS/FAC/pull/3574
- [x] Create Page Object class for the Search Page.
- [x] Implement methods for interacting with the search input field.
- [x] Implement methods for clicking the search button.
- [x] Implement methods for verifying search results
- [x] add summary report page + tests for downloading SF-SAC and Single Audit report
- [ ] https://github.com/GSA-TTS/FAC/issues/3590
- [ ] https://github.com/GSA-TTS/FAC/issues/3589
- [ ] https://github.com/GSA-TTS/FAC/issues/3591
- [ ] https://github.com/GSA-TTS/FAC/issues/3592
- [ ] https://github.com/GSA-TTS/FAC/issues/3593
- [ ] https://github.com/GSA-TTS/FAC/issues/3628
- [ ] https://github.com/GSA-TTS/FAC/issues/3629
- [ ] https://github.com/GSA-TTS/FAC/issues/3630
- [ ] https://github.com/GSA-TTS/FAC/issues/3631
- [ ] https://github.com/GSA-TTS/FAC/issues/3632
- [ ] https://github.com/GSA-TTS/FAC/issues/3633
- [ ] https://github.com/GSA-TTS/FAC/issues/3634
- [ ] https://github.com/GSA-TTS/FAC/issues/3636
- [ ] https://github.com/GSA-TTS/FAC/issues/3637
```

**Comment by eazapata23** [comment]
As part of the full submission regression tests, I integrated a separate test dedicated to the search functionality. This test solely utilizes the UEI within our full submission tests to initiate a search. Upon execution, the test successfully demonstrated the appearance of results associated with the UEI without actually verifying/asserting. I’m aware that there’s significant room for improvement and refinement. I’m just seeking thoughts and feedback on potential avenues for further development to enhance this current test.



https://github.com/GSA-TTS/FAC/assets/99770283/7fc2819b-a405-485d-a99a-b07ecf4fd4f3

**Comment by eazapata23** [comment]
closing linked to #3574

**Comment by eazapata23** [comment]
Reopening to better track progress.

**Comment by danswick** [comment]
We've taken this into the MVP stage and aren't going to pursue any further in the near future.
