### ISSUE TITLE
As a user, I need to know when a draft submission I want to work on is in use by someone else

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#351]
### Background

When you log in to work on a draft, but another user is already working on it, you see an error message:

![image](https://user-images.githubusercontent.com/2846578/178846644-14a45c95-01c7-487f-bb96-7a023e6ed00b.png)

We need to provide a way for you to know that the draft is locked while someone else is editing it.

We'll also have to create additional issues to cover the front and back end implementation of this.

### Acceptance criteria (We'll know we're done when...)

- [ ] A logged-in user is notified that another user is currently working on the draft they want to work on, so the draft is locked to further editing.
  
### Tasks

- [ ] Design a way to let the user know someone else is editing the draft, so they cannot edit it.
- [ ] Write up implementation notes including expected behavior re: roles and access controls
- [ ] Tag a peer to review

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ]  All text has a contrast ratio of 4.5:1 with the background
- [ ]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ]  There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by jadudm** [comment]
We have a race hazard, and there's no plan to lock things at this time. Moving this to post MVP for further consideration later.

**Comment by jadudm** [comment]
Not planned.
