### ISSUE TITLE
Document FAC team charter

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#352]
### Background
Now that we have a full team, we want to KO with a team charter that 

**Background**
AS a team, we want to make sure we have consensus on how we want to work together. 

**Acceptance criteria** 
- [ ] We have team charter that describes our desired working and communication practices
- [ ] We have a team charter that clearly delineates each of our roles on the project

**Tasks**
 - [x] @MelissaBraxton creates shell of team charter that folks can react to
- [x] Each team member reviews draft team charter on their own or in small groups
- [x] Schedule charter co-working activity
- [x] Prep Mural template or other facilitation guides for team chartering mtg (@MelissaBraxton) 
- [x] Team co-working to refine the charter until everyone is happy with it 

**Definition of done**
- [ ]  Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Chartering activity template is [here](https://app.mural.co/invitation/mural/gsa6/1657921027860?sender=melissabraxton2796&key=ff3725ea-66b6-49d9-a18c-bbb556bc9aee)

**Comment by MelissaBraxton** [comment]
@petermarks-gsa moving this into review while the team takes a look. Can I pass on the task of making any refinements to you?

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Yes, sounds great.

**Comment by petermarks-gsa** [comment]
@heymatthenry @austinhernandez We took a stab at refining the draft of our team charter today at co-work. In the next week, could you please review it [here](https://app.mural.co/t/gsa6/m/gsa6/1657921027860/f6d15b9a5882fb0615078010bacc5dd4826c0130?invited=true&sender=ua4d37dfba3f1e69e09078790) and let us know if you have any questions or suggestions?

**Comment by heymatthenry** [comment]
@petermarks-gsa LGTM! 👍🏻

**Comment by austinhernandez** [comment]
sorry @petermarks-gsa , i already took action on this so i assumed it was done.

**Comment by petermarks-gsa** [comment]
@austinhernandez No problem, we updated the "core values" and "group norms" sections as a team last week.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins @melchoyce Per our discussion at last week's co-work, I solicited feedback from Matt and Austin who were unable to attend. With [this change](https://github.com/GSA-TTS/FAC/pull/433), I've linked to the charter in the agile process doc with context. I think we can merge that change and call this done?
