### ISSUE TITLE
Search performance: implement temporary filter limits and communicate to users

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3526]
### Tasks

```[tasklist]
- [x] Draft status update language for static site
- [x] Create system status page for static site
- [x] Draft concise language for status banners
- [x] Draft FAC APP PR reducing search filter options to UEI, adds a warning text box linking to status page, disables multi-download button, disables SF-SAC summary download button.
- [x] Review static-site and FAC PRs
- [x] Deploy static site and FAC application during off-peak hours
```

**Comment by lauraherring** [comment]
@danswick Here's the alert banner copy, the link will be `fac.gov/status`

> Audit search is currently limited to UEI-only. For more information, visit the FAC status page.

**Comment by lauraherring** [comment]
@danswick And here's the new copy for the Search page:

> Audit search is currently limited to UEI-only. You can search your UEI to confirm your audit submission is complete. The PDF report will still be available for download but summary report workbooks won't.

> For more information, visit (the FAC system status page)(link: fac.gov/status).

**Comment by lauraherring** [comment]
And here's my suggested copy for an email to the listserv:

> Hello,
>We're reaching out to let you know that audit search is currently limited to UEI-only. You can search your UEI to confirm your audit submission is complete. The PDF report will still be available for download but summary report workbooks won't.

>We understand this is a painful inconvenience and we apologize for that. We're working as quickly and efficiently as possible to return full search functionality as soon as we can. 

>For more information on this issue and to find regular updates, please visit (our new FAC system status page)(link: fac.gov/status).

>Thank you for your patience.

>-The FAC team

**Comment by lauraherring** [comment]
And finally,[ a PR](https://github.com/GSA-TTS/FAC-transition-site/pull/94) for the branch with the new alert banner and status page.

**Comment by jperson1** [comment]
To confirm, we're looking for a site-wide alert and a search-specific alert?

Something akin to:
![image](https://github.com/GSA-TTS/FAC/assets/91098850/fa769b00-1c37-4e8f-b1e4-e0d53f60b087)

**Comment by danswick** [comment]
This is done. We'll keep an eye on things and hopefully revert most of these changes in a day or two.

**Comment by lauraherring** [comment]
@danswick @Leighdiddy @jperson1 Do we want to remove the blue box from the page as well? I think it's a little confusing to have that info right after we say all the other filters are turned off.

**Comment by jperson1** [comment]
@lauraherring, that makes sense to me! Here's a [quick PR](https://github.com/GSA-TTS/FAC/pull/3532) that does just that, and can go in soon or after some conversation.
