### ISSUE TITLE
Create federal awards workbook with >10k awards rows

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3529]
_As a state entity submitting my annual single audit reporting package, I need to be able to upload a workbook with more than 10,000 awards rows and have it pass validation, so that my certifying officials can approve and submit my completed single audit report._ 

A recent help desk ticket exposed a case where a large entity needs 16,000+ rows for their awards workbook, and we are currently capped at 10k. We need to create a new workbook with a larger capacity for awards, and determine the best way to share it with our users. 

### Tasks

```[tasklist]
- [x] Generate new version of Workbook 1 Federal Awards that allows for >10k awards rows
- [x] Update validations to allow for new workbook
- [x] Test new workbook
- [ ] Update static site to include copy + link for new XL workbook and instructions on submission guide (audit submission> submission resources> submission guide)
- [ ] Update static site to include copy + link for new XL workbook and instructions on SF-SAC + instructions page (audit submission> submission resources> SF-SAC)
- [ ] Update app to include copy + link for new XL workbook and instructions on workbook 1 Federal Awards upload page (accesed from submission checklist)
```

**Comment by Leighdiddy** [comment]
@lauraherring The copy will need updated to include the new XL workbook on three screens: [The submission guide](https://www.fac.gov/audit-resources/how-to/) , [the workbook page](https://www.fac.gov/audit-resources/sf-sac/) , and workbook 1 Federal Awards upload page within the app.

**Comment by Leighdiddy** [comment]
@lauraherring task list is revised to include copy updates as discussed
