### ISSUE TITLE
Add note about 10K awards to static site/Federal Awards submission instructions

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3557]
We now know that some audits have more than 10K federal awards.

Our existing templates cap out at 10K rows. 

We can create new templates that have more than 10K rows, and can be distributed as needed. However, auditors and auditees need to know that if they have more than 10K award rows, that they must reach out to us and use a template. Failure to do so could result in their audit not validating.

```[tasklist]
### Tasks
- [ ] Audit + Identify locations within the static site and the app where we should have guidance on this.
- [ ] Develop language for guiding users to the helpdesk when they need a larger template.
- [ ] Update static site in appropriate locations
- [ ] Update app in appropriate locations.
- [ ] Tag a teammate to review your work
```

**Comment by lauraherring** [comment]
@danswick Is the larger workbook still something that needs to be requested via the helpdesk? Or did we just make the larger workbook the standard?

**Comment by danswick** [comment]
@lauraherring the default is still 10k. [Here's where that happens in code](https://github.com/GSA-TTS/FAC/blob/bc5b8957821c08bae470c613b656e80c972de5f0/backend/schemas/scripts/render.py#L30-L38).

**Comment by danswick** [comment]
This is done.
