### ISSUE TITLE
As a user, I want to be able to quickly and easily navigate the FAC website

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#357]
Breakout issue of #288 and #248.

Relies on #371.

This issue covers finalizing the FAC navigation and IA based on the results of our recent Tree Test.

#### Observation(s)

- 

#### MVP Recommendations

- 

### Acceptance criteria (We'll know we're done when...)

- [ ] We have designed a way for an auditee or auditor to log in.
- [ ] We have designed a way for an auditee or auditor to log out.
- [ ] **TBD**
  
### Tasks

- [ ] Update navigation design
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
Let's tackle this in the next sprint.

**Comment by melchoyce** [comment]
Actually, looks like #371 is a duplicate and already has comments. Going to close this issue in favor of that one.
