### ISSUE TITLE
As someone who has access to an audit submission, I need a way to navigate to administrative actions I may want to take from the audit start page.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#361]
This issue covers the design of the side navigation on the Audit Start Page. #264.  Included in this issue is some need to product and design to prioritize which features users might expect here are in scope for the MVP. 

Needs that are in scope: 
#340 
 
Needs that require a decision:
- As a user, I need to be able to unlock a SF-SAC form that has been finalized so that I can make edits
- As a user, I want to be able to print a draft of the SF-SAC form so that I can review it locally
- - As a user, I want to be able to print an audit report that has been uploaded to a draft submission so that I can review it locally

Needs that are recommended be addressed in later releases: 
- As a user, I want to be able to print just the draft SEFA form and notes to SEFA so that I can review them locally
- As a user, I want to be able to access FAQs and resources from the audit start page so that I can get the help I need in context

### Acceptance Criteria (We'll know we're done when...)

- [ ] We have mocks that reflect the side nav for the audit start page
- [ ] We've recorded any PDRs needed to document decisions we made about the scope of features that we'll make accessible from here as part of the MVP

### Tasks

- [ ] Schedule time to discuss with PM/Engineering lead which administrative features are in/out of scope for MVP. 
- [ ] Create mocks
- [ ] Write implementation notes
- [ ] Tag peer to review

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by austinhernandez** [comment]
Ready for peer review @MelissaBraxton @melchoyce @sreuber 

Notes:
1. `Unlock finalized form SF-SAC` and view print secondary navigation link only appears when `1. enter and finalize form SF-SAC` is complete 
![Submit audit package](https://user-images.githubusercontent.com/23194720/179281138-041d5b32-a714-4782-bbed-96bc9485b0e0.png)

2. Confirmation modal
![Confirmation modal](https://user-images.githubusercontent.com/23194720/179281412-8284f2e3-b411-44c5-bed2-226d29a4e285.png)
 
3. Returns to incomplete
![Unlocked](https://user-images.githubusercontent.com/23194720/179281527-957ba097-6cdb-40fe-b1d8-1379012ed0a5.png)

4. View/Print Form SF-SAC downloads XLS file with `DRAFT` watermark (screenshot of XLSX) / [view compete downloaded file here: IDESReport_934785_1.xlsx](https://github.com/GSA-TTS/FAC/files/9123009/IDESReport_934785_1.xlsx)
![Screen Shot 2022-07-15 at 1 50 01 PM](https://user-images.githubusercontent.com/23194720/179282401-8c1b7270-c1c3-4b6f-90e7-0152e5aac6a4.png)


**Questions**: 
- On screen 3: Should the status be changed to `unlocked` or something else to indicate its been unlocked/redone?
- Should the `View/Print Form SF-SAC` link ONLY be available once an audit report has been uploaded to a draft submission or is it while its in progress as well?

**Comment by MelissaBraxton** [comment]
**Questions:** 
On screen 3: Should the status be changed to unlocked or something else to indicate its been unlocked/redone? 
> Let's not worry about this right now. 

Should the View/Print Form SF-SAC link ONLY be available once an audit report has been uploaded to a draft submission or is it while its in progress as well?
>No. People want to take a look at parts of the form in progress.


I meant to include this screen shot in this issue when I drafted it, but also in scope is the design of the rest of the side nav (including sub-nav) depicted here, including decisions on which of these nav items lead to features that are out of scope for the MVP (and thus should not be included. )

<img width="303" alt="Screen Shot 2022-07-14 at 2 20 09 PM" src="https://user-images.githubusercontent.com/20651166/179284112-80f0f6d7-10a8-4252-af34-251a8bc0ebcb.png">

Below the image of the audit start page, I grabbed images of the current side nav expanded to show sub nav items.

**Comment by austinhernandez** [comment]
thanks @MelissaBraxton i missunderstood the scope! 

double checking on the help dropdown - [its not in the MURAL](https://app.mural.co/invitation/mural/gsa6/1654109929324?sender=austinhernandez5199&key=93f016dc-f3d6-41c9-a2b9-0b8f72b0926a), is it out of scope or should i just assume all the content is outdated and it should be removed?

![Screen Shot 2022-07-14 at 2 11 1](https://user-images.githubusercontent.com/23194720/179289378-362f2c44-8f5d-4dc9-9d6e-df987e6288ca.png)

**Comment by sreuber** [comment]
I had updated a few [mocks on the start page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3407%3A15718) per a [conversation in Slack](https://gsa-tts.slack.com/archives/C1L58R804/p1657749434195649?thread_ts=1657749160.495119&cid=C1L58R804) that changed the Status column to "Done", having completed by, and simply having a checkmark there. Also removed the CTA numbers, as well as kkept only the "Completed by" column…Not sure if those changes need to be reflected on the mocks here.

**Comment by MelissaBraxton** [comment]
@austinhernandez - It's a bit TBD, We have a separate story on the Story map (although not in GH yet) re: as a user I need to know where to go for help.  We do also already have most this content linked to from the FAC homepage. 

I was thinking we'd tackle it later, and meant to communicate that in the issue via the text below, but I see how it could be confusing!

> Needs that are recommended be addressed in later releases:
> 
> As a user, I want to be able to access FAQs and resources from the audit start page so that I can get the help I need in context

**Comment by MelissaBraxton** [comment]
@sreuber   - The screen shot above is from the old FAC, so it's understandably very out of date with our current mocks.

**Comment by austinhernandez** [comment]
alright this was a bigger ticket with a lot of dependencies, but getting there. ready for peer review @MelissaBraxton @sreuber @melchoyce: 

on figma here: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4034%3A19388

Audit Start Page - audit form secondary nav / unlock the SF-SAC
![image](https://user-images.githubusercontent.com/23194720/180514636-77f45b7d-aeac-4199-bd28-f99994cbf8c0.png)
notes
- content TBD, but this is the "final" start page design (with done column)
- `Unlock Finalized Form SF-SAC` link is active when SF-SAC is `done`
- Clicking `Unlock Finalized Form SF-SAC` opens confirmation modal letting a user know that it will delete the audit report and invalidate any auditor of auditee certifications
- If they click yes, the `Unlock Finalized Form SF-SAC` link is inactive, the `done` column gets cleared, the `completed by` column clears 

Audit Start Page - audit reform (PDF)
![image](https://user-images.githubusercontent.com/23194720/180516682-8a43b535-ccb4-4c3c-bdf6-ceb05eedd472.png)
![image](https://user-images.githubusercontent.com/23194720/180518991-91a0b3db-d497-402e-8f2d-c88d484d0e37.png)

notes
- `Re-upload audit report` and `View/Print audit report` link become active when `Enter and Finalize Form SF-SAC` and `Upload and Finalize Audit Report` is marked as `done`
- Clicking `Unlock Finalized Form SF-SAC` opens confirmation modal letting a user know that it will delete the audit report and invalidate any auditor of auditee certifications 
- Clicking `View/Print audit report` downloads the PDF


Last, we have the "[report access in ticket #340](https://github.com/GSA-TTS/FAC/issues/340)" process which has some navigation overlap (but its also on the 361 page). on figma here: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4034%3A19388

![image](https://user-images.githubusercontent.com/23194720/180519203-6c2f121d-63f2-4fa3-ae6d-cb3a23e8ee45.png)
notes:
- Email address fields are not editable on the submission access page, you must click the add or change button below each row to open the "Add / change..." modal
- Each role (Auditee certifying official, Auditor certifying official, Auditee, or Auditor) has its own add/change button is unique to the section, so no role selection is needed. 
- Since you can have only one "certifying official," the CTA is “Change contact," since you can have multiple auditees and auditors, the CTA is "Add another contact"
- `Add another contact` and `change contact` links open a modal which will ask for email address and confirm/re-enter email field
- You can shift the roles around on the page without adding a new user
- clicking on the `role` dropdown and changing the role moves the row to another section
- In the Auditee certifying official and Auditor certifying official sections, `Delete user` button clears the email address field
- In the Auditee and Auditor sections, `Delete user` button in the first row deletes the email address field, in the subsequent rows (in the case of multiple auditees/ors) `Delete user` button deletes the entire row  and `add another contact` link moves under the row above


Question:
- what is the role of the person who created the submission in the first place? does this need another field? 
- What  will all the potential error states will be? I am pretty sure some fields can be left blank, but they will show up if a user tries to check for errors and finalize. 
- Does there need to be formatting validation? There has to be some validation logic (eg can't have the same contact for both certifying officials). 


Excludes the `help` section which is TBD

**Comment by melchoyce** [comment]
> Audit Start Page - audit form secondary nav / unlock the SF-SAC

I know this is how it works now, but man is this rough. I'm wondering if copy changes would go a long way to making this interaction more clear. Not anything you need to change here, just wanted to note.

> Re-upload audit report and View/Print audit report link become active when Enter and Finalize Form SF-SAC and Upload and Finalize Audit Report is marked as done

Do we have any sort of popover that shows up on hover/click on mobile that explains why something is locked? That could be helpful in mitigating some of the confusion around "this only unlocks once I do task x."

Questions aside, these all seem good to me.

**Comment by austinhernandez** [comment]
Re-upload audit report and View/Print audit report link become active when Enter and Finalize Form SF-SAC and Upload and Finalize Audit Report is marked as done

> I went back and forth on this. I felt like it should be visible and locked so that a user knows that they can undo something once its been done. therefore, it seemed _more_ intuitive that its locked bc you havent done that thing yet. down with a copy change and or usability testing

**Comment by petermarks-gsa** [comment]
@melchoyce @austinhernandez From my reading of this, this issue is already covered by the following implementation issues: 

https://github.com/GSA-TTS/FAC/issues/499
https://github.com/GSA-TTS/FAC/issues/212

Is that correct?

**Comment by melchoyce** [comment]
I believe so!
