### ISSUE TITLE
User testing of static site instructions

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3626]
As the UX designer, I need to conduct user testing to get feedback from users on where their pain points in the submission guide and workbook instructions are so that the content team can update the content accordingly.

### Tasks

```[tasklist]
- [ ] Create research plan
- [ ] Build/compose test
- [ ] Compose all comms (invites, confirmation emails, etc)
- [ ] Create Gcal appointment schedule
- [ ] Pull recruiting list
- [ ] Send invitation emails
- [ ] Schedule backups, note takers, observers
- [ ] Create notes docs for individual participants
- [ ] Update calendar invites with zoom links, send out confirmation emails, schedule debriefs
- [ ] Synthesize results with Content team
```
