### ISSUE TITLE
Implement Instruction Updates

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3627]
As the content strategist, I need specific feedback from users on where their pain points in the submission guide and workbook instructions are so that I can update the content accordingly.

Work can't be completed until #3626 is finished.

### Tasks

```[tasklist]
- [ ] Update Submission Guide with recommended changes
- [ ] Update Workbook 1 instructions with recommended changes
- [ ] Update Workbook 2 instructions with recommended changes
- [ ] Update Workbook 3 instructions with recommended changes
- [ ] Update Workbook 4 instructions with recommended changes
- [ ] Update Workbook 5 instructions with recommended changes
- [ ] Update Workbook 6 instructions with recommended changes
- [ ] Update Workbook 7 instructions with recommended changes
- [ ] Update Workbook 8 instructions with recommended changes
```

**Comment by Leighdiddy** [comment]
Blocked until https://github.com/GSA-TTS/FAC/issues/3626 is finished.
