### ISSUE TITLE
Add links to Uniform Guidance to Submission Guide

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3642]
As a user, I need links to the relevant sections of the Uniform Guidance linked to from the Submission so that I can confirm I'm following policy correctly as I'm completing my single audit submission.

```[tasklist]
### Tasks
- [x] Identify citations in the UG for the submission guide
- [x] Add links to the site
- [x] Publish the changes
```

**Comment by lauraherring** [comment]
This work has been submitted in [PR #124](https://github.com/GSA-TTS/FAC-transition-site/pull/124) and is ready for review.
