### ISSUE TITLE
Add links to Uniform Guidance to Workbook 1 instructions

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3643]
As a user, I need links to the relevant sections of the Uniform Guidance linked to within the instructions for Workbook 1 so that I can confirm I'm following policy correctly as I'm completing my single audit submission.

```[tasklist]
### Tasks
- [ ] Identify citations in the UG for the workbook instructions
- [ ] Add links to the site
- [ ] Publish the changes
```

**Comment by lauraherring** [comment]
This work is covered under [PR #128](https://github.com/GSA-TTS/FAC-transition-site/pull/128).

**Comment by Leighdiddy** [comment]
PR approved! Feedback noted on the PR, moving this to done.
