### ISSUE TITLE
Add links to Uniform Guidance to Workbook 4 instructions

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3646]
As a user, I need links to the relevant sections of the Uniform Guidance linked to within the instructions for Workbook 4 so that I can confirm I'm following policy correctly as I'm completing my single audit submission.

```[tasklist]
### Tasks
- [x] Identify citations in the UG for the workbook instructions
- [x] Add links to the site
- [x] Publish the changes
```

**Comment by lauraherring** [comment]
Closing this as done, covered by [this PR](https://github.com/GSA-TTS/FAC-transition-site/pull/136).
