### ISSUE TITLE
Onboarding checklist for Erin

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#365]
### Welcome to the team Erin!

Here's a few pointers to get you started as well as a checklist to make sure you've got access to :all-the-things:!

**For you**
- [x] [Join](https://github.com/GSA/GitHub-Administration#joining-the-gsa-enterprise-organization) GSA’s Enterprise Github org
- [x] Review the [project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/) in drive
- [x] Read [design onboarding documentation](https://docs.google.com/document/d/1EILl0nZr59T4PFJJMtFbmnQDJPksgzIFPuoFDN0bk0g/edit#)
- [x] Read [known design debt](https://docs.google.com/document/d/14C5neV7rClnoGX2ds7ZBEOXYB6qwzrW-QrOeBxewGp8/edit#) doc
- [x] Join Slack channels in the project README

@MelissaBraxton  will be your onboarding buddy and will tackle the list below!

**For your onboarding buddy**
- [x] Add to the FAC team folder in drive
- [x] <Design> Added to [FAC playground Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3550%3A16794) 
- [x] Add to the [FAC team](https://github.com/orgs/GSA-TTS/teams/fac-team) in github
- [x] Add to standing meeting invites
