### ISSUE TITLE
Define content refinement workflow

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#366]
### Background
Now that we have a content strategist on board, we wanto lay out the easiest way to track and implement recommended refinements to all of our copy to date.

### Acceptance Criteria (We'll know we're done when...)

- [x] We have documented decisions on how we'll track and communicate content refinements
- [x] We've created whatever tools/templates/docs we'll use to support the process we've decided on

### Tasks

- [x] Discuss proposed process
- [x] Draft short summary of how it'll work
- [x] Added the workflow to the [design onboarding doc](https://docs.google.com/document/d/1EILl0nZr59T4PFJJMtFbmnQDJPksgzIFPuoFDN0bk0g/edit#heading=h.bo2bm1vpux0g)

**Comment by erinzstrenio** [comment]
## Content workflow

Here's how it's been going so far: 

- Content strategist reviews design mocks in Figma
- Content strategist leaves comments in Figma with suggested edits and tags designer
- Content strategist also tracks content updates in GitHub in #367 
- Content strategist works in [this Google doc](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit) scratchpad to draft edits
- Team gives a peer review of content edits
- Designer updates Figma mock with edited content
