### ISSUE TITLE
Draft site documentation for new advanced search filters 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3671]
**As a user of the search database of historical records on FAC.gov, I need to understand the difference between Basic Search and Advanced Search and how all of their filters work, so I can use the best possible search type and combination of filters for my query.** 

### Tasks

```[tasklist]
- [x] Review new [Advanced search](https://app.fac.gov/dissemination/search/advanced/) filters with dev team
- [x] Update existing _Search filters_ title card on [main resource page](https://www.fac.gov/search-resources/) to _Basic search filters_
- [x] Update [existing](https://www.fac.gov/search-resources/filters/) _Search filters_ headline to _Basic search filters_
- [x] Draft brief explanation of difference between _Basic_ and _Advanced_ search (can be pulled from infobox at top of search page home) and add to copy on [Basic search filters](https://www.fac.gov/search-resources/filters/) screen
- [x] Draft copy for new Advanced Search filter guide based upon [existing documentation](https://www.fac.gov/search-resources/filters/), including explanation of difference between Basic and Advanced.
- [x] Create new _Advanced search filters_ title card for [Search resources screen](https://www.fac.gov/search-resources/)
- [x] Create new _Advanced search filters_ screen that can be reached via Audit search> Search resources> _Advanced search_ title card
```

**Comment by lauraherring** [comment]
@jperson1 This ticket is also going to require making the following changes to the basic and advanced search pages in the app:

- basic search page
Update the copy in the blue box to match the screenshot below. The URL also needs to be updated to https://www.fac.gov/search-resources/filters/ so it doesn't rely on the redirect


![Image](https://github.com/GSA-TTS/FAC/assets/123114420/d1fc10e8-d854-477a-8413-4b036f572aeb)

- advanced search page
Update the copy in the blue box to match this screenshot. The URL will be https://www.fac.gov/search-resources/advanced/


![Image](https://github.com/GSA-TTS/FAC/assets/123114420/ea260184-3bb9-4c51-91a7-d9ce44b8878d)

**Comment by lauraherring** [comment]
@jperson1 The static site changes went live this morning so the updates to the app pages can happen at any time.

**Comment by jperson1** [comment]
@lauraherring Fantastic! The app-side PR is above.
