### ISSUE TITLE
Offboarding checklist for @Carley-Jackson 

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3673]
## For everyone

- [x] Remove from Google groups as applicable:
  - [x] [FAC-team](https://groups.google.com/a/gsa.gov/g/fac-team/members) 
  - [x] [fac-gov-test-users](https://groups.google.com/a/gsa.gov/g/fac-gov-test-users/members)
  - [x] [fac-gov-api-dev](https://groups.google.com/a/gsa.gov/g/fac-gov-api-dev)
- [x] Remove from [the FAC team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members)
- [x] Remove from the private channels #oros-fac-private and #fac-helpdesk in Slack (“/remove @[person]”)
- [x] Remove from active Figma projects
- [x] Remove from Mural
- [x] Remove from Zendesk 
- [x] Check for and remove admin access in the FAC application: this may include designated permissions and/or checked-in API  access ([for example](https://github.com/GSA-TTS/FAC/blob/fb0e7bdf1cb1807291e6b6eef068e97b4574078c/backend/support/api/admin_api_v1_1_0/create_access_tables.sql#L21))

## For GitHub contributors
- [x] Make a PR to [remove the departing team member from the list of developers and managers](https://github.com/GSA-TTS/FAC/tree/main/terraform/meta/config.tf) with access to our spaces.
- [x] [Remove the departing team member as a member of the FAC group in New Relic.](https://one.newrelic.com/admin-portal/organizations/users-list) (@GSA-TTS/fac-admins can do this)
    - [ ] If they're leaving TTS altogether, also delete their account. 

## For admins
- [x] If the departing team member is a Google Group manager, designate a new manager for any groups they manage.
- [x] If they are the on Make someone else the Maintainer and remove the departing team member from [the FAC-admins team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-admins/members) and [the FAC-team team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members).
- [x] Remove any deployment tokens associated with the PL/PO from the repository.

**Comment by jadudm** [comment]
Not applicable (for reference):

*  If the departing team member is a Google Group manager, designate a new manager for any groups they manage.
* If they are the on Make someone else the Maintainer and remove the departing team member from [the FAC-admins team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-admins/members) and [the FAC-team team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members).
*  Remove any deployment tokens associated with the PL/PO from the repository.
* [Remove the departing team member as a member of the FAC group in New Relic.](https://one.newrelic.com/admin-portal/organizations/users-list) (@GSA-TTS/fac-admins can do this)
*

**Comment by jadudm** [comment]
@Leighdiddy , could you please check the Mural, figma access?

@tadhg-ohiggins , @timoballard , could one of you please check the app access?

**Comment by danswick** [comment]
Looks like we're all done here.
