### ISSUE TITLE
Create research roadmap

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#368]
### Background

This story is to plan for any upcoming design research for the near & far term. We'll want to account for what each research spike will cover at a high level, how certain we are we will be able to run that research at the planned time, and any dependencies to run those research spikes to mitigate any surprises.

### Acceptance Criteria (We'll know we're done when...)

- [ ] We have research spikes planned up to the MVP as needed that answer outstanding organizational questions and help support & prepare project milestones.

### Tasks

- [x] Map out a provisional research roadmap up to the October MVP (in a tool such as Mural or Google Sheets).
- [x] Identify any dependencies needed to run each spike (eg. recruitment, gift card incentives, PRA approval, etc).
- [x] List any hypotheses we may already have for each, if any.

**Comment by sreuber** [comment]
Using agency Mural for now, will move over to GSA once I have access and will link to here.
