### ISSUE TITLE
🅢 Collect users' first name, last name from Login.gov

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#369]
### Background 
We currently only collect the `email` and `all_emails` user attributes from Login.gov. In order to populate the `first_name` and `last_name` fields for the Django user model, we will need to expand the scope of our Login.gov authorization request to include the `given_name` and `family_name` attributes (`profile` scope).

### Acceptance Criteria (We'll know we're done when...)

- [ ] On first login, users are prompted by Login.gov for their permission to provide the FAC with their `email`, `all_emails`, `given_name` and `family_name`
- [ ] On first login, the newly-created Django user has its `first_name` and `last_name` fields populated with the values received from Login.gov
- [ ] When a user logs in after changing their given and/or family name at Login.gov, the `first_name` and/or `last_name` fields for their Django user should be updated accordingly

### Tasks

- [ ] Update frontend authentication request to include `profile` scope
- [ ] Update backend authentication flow to populate the `first_name` and `last_name` fields when creating Django users
- [ ] Update backend authentication flow to update the `first_name` and `last_name` fields when retrieving existing Django users

**Comment by danswick** [comment]
We're not currently planning to do this.
