### ISSUE TITLE
Refine IA based on tree test results

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#371]
This issue covers tree test analysis and the refinement of the IA based on the results of our tree test in #248 

### Acceptance criteria (We'll know we're done when...)

- [x] We have mocks of our homepage showing the new refined IA
  
### Tasks

- [x] Analyze tree test results in Optimal workshop
- [x] Clarify questions with Mark Dixon at Census
- [x] Draft recommended IA changes ([doc](https://docs.google.com/document/d/1WKIO45rufy81cgVKiCoR4g0KMBATd4rwCr3XgVgvr1s/edit))
- [x] Review nav recommendations with design team
- [x] Revise mocks to reflect new IA based on tree test results

**Comment by erinzstrenio** [comment]
Taking notes on our analysis [here](https://docs.google.com/document/d/1WKIO45rufy81cgVKiCoR4g0KMBATd4rwCr3XgVgvr1s/edit)

**Comment by erinzstrenio** [comment]
@sreuber and I started making recommendations in the doc, but it requires a bigger conversation on the nav with the rest of the design team

**Comment by melchoyce** [comment]
Per our sprint review today, we're going to try re-testing the updated IA in a tree test, likely in one or two sprints from now (11 or 12).

**Comment by erinzstrenio** [comment]
We spoke to Mark Dixon at Census on 8/25 to clarify some of the terms used in the navigation and clarify which pages should stay on the Resources page and which are outdated ([notes here](https://docs.google.com/document/d/1DxuyVOusBIIRrXCaOmmzQp-Q54bthuSirmwR4j4jTbc/edit#heading=h.wxwlew1tfuhc))

We are adding some questions to the usability interviews to get more user perspective on the nav ([interview guide](https://docs.google.com/document/d/1BEt0p0aTPBZTjcE1KIybSn4-wKOYw5Peqx7STlrN6I4/edit#heading=h.5ibyluji038r))

**Comment by erinzstrenio** [comment]
Closing out this ticket since we've made some changes to the IA [see this doc](https://docs.google.com/document/d/1WKIO45rufy81cgVKiCoR4g0KMBATd4rwCr3XgVgvr1s/edit) which have been updated in the mockups. We created new tickets for follow-up research on the nav with auditees in upcoming usability testing (#473) as well as redesigning the FAQs page (#457) and Resources pages (#458).

**Comment by petermarks-gsa** [comment]
Tracking implementation in https://github.com/GSA-TTS/FAC/issues/280. Closing. cc @melchoyce @tadhg-ohiggins @mogul .
