### ISSUE TITLE
Write up FAC team design QB "playbook" 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#372]
With design team roles changing, we want to redistribute the work of writing and organizing design oriented issues. The scope of this issue is to document tips and considerations that will help set up for success anyone on the team who is involved in scoping and prioritizing design focused issues. 

### Acceptance criteria (We'll know we're done when...)

- [ ] We have a brief document that provides guidance on writing and prioritizing design issues and keeping the backlog of design issues organized and focused.
  
### Tasks

- [x] Create design QB playbook doc
- [x] Peer review
- [x] Link to from the wiki

### Definition of Done

- [x] Meets acceptance criteria

**Comment by MelissaBraxton** [comment]
Draft playbook is [here.](https://docs.google.com/document/d/10mRV4RSHruwLQm2BrDXqky0juB5ytqAWIZzAVCB217M/edit#)

Would love some extra eyes before I refine it further!

**Comment by melchoyce** [comment]
This is looking great! Super thorough :) 

I added one clarifying question to the doc, but that's all I have.

**Comment by MelissaBraxton** [comment]
Sweet! @melchoyce Double check that I addressed your comment, but I'm thinking this is done.

**Comment by austinhernandez** [comment]
looks good to me!
