### ISSUE TITLE
Consolidate stories that are post MVP into the story map

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#373]
Our story map mostly reflects work that is in scope for the MVP. We've identified user needs that we dont want to lose sight of for later releases, but they're scattered throughout research reports and other notes. This issue covers consolidating these into the story map so that we have one place keep track of and look for them.

### Acceptance Criteria (We'll know we're done when...)

- [x] All user stories are reflected in the story map

### Tasks

- [x] Review docs and decks where we've noted post MVP stories
- [x] Copy stories as stickies in the story map
