### ISSUE TITLE
Prep for AICPA call on 7/27

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#374]
On 7/27, we have a call scheduled to start talking about collaborating with some stakeholders in the auditor community on how to message changes that auditors may want to start anticipating. 

Context on the initial impetus for this call: 

> We had a member reach out and ask if GSA is requiring that UEI numbers be included for audit report submissions to the clearinghouse this year. That is not a requirement we are aware of, and so if that’s the case we want to make sure the state controllers responsible for certifying the submission and their auditors are aware of this requirement. With the DUNS numbers there could be dozens for a single state and if UEIs are similar this is something for which advance warning would be very helpful. 

We'll want to anticipate Qs re: what auditors can expect, but also I think this could be a great time to start teeing up a collaboration on a broader GSA comms strategy. 

### Acceptance Criteria (We'll know we're done when...)

- [x] We have an agenda for the call

### Tasks

- [x] Identify who will lead the mtg
- [x] Craft agenda
- [x] Circulate for review

**Comment by sreuber** [comment]
@MelissaBraxton @jadudm @petermarks-gsa I have a draft of the AICPA agenda linked here, looking for feedback. 

I'm assuming I am leading the meeting as discussed, but open to anyone else wanting to do this. https://docs.google.com/document/d/1CORabUQkigEwsL0iM80qWvRSf2Cg6BmCXWXGY0tXhb4/edit?usp=sharing

**Comment by sreuber** [comment]
Tagging @erinzstrenio as well; open to your input on any of this and particularly around engaging & communicating with the auditor community. I have a few questions for now but open to elaboration.

**Comment by erinzstrenio** [comment]
@sreuber added some suggestions in the agenda doc!
