### ISSUE TITLE
[Spike] SpiffArena Implementation within the FAC

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#3745]
Description: Now that https://github.com/GSA-TTS/spiff-arena/pull/1 has reached a point of being able to reliably create a SpiffWorkflow instance in a GSA Sandbox, we should look forward to finding a way to implement it within the FAC as a tool. 

Objective: Determine the LOE to create and utilize SpiffWorkflow tooling, to perform actions within the FAC. There should be a clear understanding of how we at the FAC can utilize this as is, without the necessity of replication in a pre-production system. The tool, as is, as defined in that PR, can hook into the process model repo, and directly commit into it, for use of saving diagrams and promoting them to other branches (environments).

Pre-Requisites: 

**In order to**: Work on the SpiffArena Models
**as a**: Engineer
**I want**: to get the SpiffArena system working in my sandbox.

### Setup

```[tasklist]
- [ ] Deploy SpiffArena to Sandbox with a custom [var setup](https://github.com/GSA-TTS/spiff-arena/blob/601722e84804e417e651c284637b760e5da517cb/vars.yml-template)
- [ ]  View and configure the Sandbox as necessary by using [the readme](https://github.com/GSA-TTS/spiff-arena/blob/601722e84804e417e651c284637b760e5da517cb/README-cloudgov.mdl)
```

### Tasks

```[tasklist]
- [ ] Create and utilize a bpmn workflow using SpiffArena
- [ ] Utilize the API to update workflows
- [ ] Implement a basic workflow designed for the FAC
- [ ] Integrate a basic workflow with the FAC
- [ ] .... TBD
```

**Comment by danswick** [comment]
Since the underlying work here is not moving forward, I'm going to close this as not planned. We can always reopen if it comes back up.
