### ISSUE TITLE
Periodic virus scanner MVP

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3758]
### Background
For compliance reasons, we need to stand up a tool that allows us to periodically scan the files resting in our S3 bucket.

During the 4/25/24 dev huddle, we decided to implement the virus scanner as a separate, standalone Python application that lives in the same cloud.gov space, as this will provide us with the most flexibility with respect to performance & scaling, while also firewalling the scan-at-rest process from the main FAC application.

### MVP
For this first iteration, we will build the simplest application we can that satisfies the compliance requirement. The application should consume a simple configuration at startup that provides the necessary information about the S3 bucket and ClamAV service. From there, the application will continuously traverse the targeted S3 bucket, performing a ClamAV scan on each file it finds.

Future iterations will include writing last scan timestamps for each file to the FAC database, which will allow the scanner to pick up where it left off in the event of an application crash or restart, but this feature is not strictly necessary and should therefore not be part of the MVP.

### Tasks

```[tasklist]
- [ ] https://github.com/GSA-TTS/FAC/issues/3759
- [ ] https://github.com/GSA-TTS/FAC/issues/3760
- [ ] https://github.com/GSA-TTS/FAC/issues/3761
```
