### ISSUE TITLE
As a user, I want to find informational content and support about the FAC

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#377]
This issue covers the design of the informational static pages on the FAC.

### Background

The existing FAC website has a number of sections outside of the audit submissions, such as FAQs and Resources:

![Screen Shot 2022-07-19 at 1 15 37 PM](https://user-images.githubusercontent.com/2846578/179810345-b2c136a0-e4b1-4304-9e26-b857c8181ddf.png)
[Screens in Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3854%3A18868)

After we finalize https://github.com/GSA-TTS/FAC/issues/458 and https://github.com/GSA-TTS/FAC/issues/457, we can take a look at how those pages relate to the new FAC website, and design the layout of those pages.

### Acceptance criteria (We'll know we're done when...)

- [ ] Users can locate information about the FAC, such as common questions, resources, and how to get in touch to ask questions.
  
### Tasks

- [ ] Design template(s) for static content pages that can be reused across these different pages
- [ ] #466 
- [x] #766 
- [x] #767 
- [ ] Mock up any additional pages
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by Leighdiddy** [comment]
Reviewed w Mel: not relevant until post milestone 7.

**Comment by jadudm** [comment]
We're picking this up elsewhere.
