### ISSUE TITLE
Create Data Resources Hub page

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3786]
As a user, I need a central location to see all the resources/guides available so that I can make the most out of using data from the FAC search.

Page should be modeled after other resource hub pages, such as [Search Resources.](https://www.fac.gov/search-resources/) URL for the page should be `fac.gov/data-resources`. 

### Tasks

```[tasklist]
- [ ] write content, including page intro and headline
- [ ] build the page in Git
- [ ] add page to static site navigation
- [ ] add page to app site navigation
```

This ticket won't be marked as complete until it meets the following acceptance criteria:
```[tasklist] 
- [ ] design review
- [ ] content review
- [ ] engineering review
```
