### ISSUE TITLE
Create submission field validation documentation resource page

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3787]
As a user, I need a documentation resource that explains how single audit submissions are validated by the FAC so that I can better troubleshoot my own issues without assistance from the helpdesk.

This page will live under the data resources section and the URL will be fac.gov/data-resources/validation

### Tasks

```[tasklist]
- [ ] gather the validation criteria for each field
- [ ] draft page copy
- [ ] build the page in Git
- [ ] add card for the page to the Data resources hub page
- [ ] add card for the page to the Submission resources hub page
- [ ] write helpdesk FAQ that points to the page
```

This ticket won't be marked as complete until it meets the following acceptance criteria:
```[tasklist] 
- [ ] design review
- [ ] content review
- [ ] engineering review
```

**Comment by danswick** [comment]
Rolled into https://github.com/GSA-TTS/FAC/issues/4465
