### ISSUE TITLE
[SOT2] Document known data issues

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3788]
The original intent behind this ticket should be rolled into a larger scope of work around refreshing all of out Data/API documentation. Until we're able to do some more planning, let's use this ticket to track known issues or other anomalies so they don't get lost.

---

As a user, I need a resource page that outlines the known issues in the FAC data and how to work around those limitations so that I can make the most use of the data in my daily work.

This page will live under the data resources section and the URL will be fac.gov/data-resources/data-status

### Tasks

```[tasklist]
- [x] gather the known data issues
- [ ] draft a workaround for each known issue
- [x] draft page copy
- [x] build the page in Git
- [x] add card for the page to the Data resources hub page
```

This ticket won't be marked as complete until it meets the following acceptance criteria:
```[tasklist] 
- [ ] design review
- [ ] content review
- [ ] engineering review
```

**Comment by lauraherring** [comment]
A [draft of this page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/data-curation/data-resources/data-interpretation/) is built.

**Comment by danswick** [comment]
Need some clarity re: start/end date off-by-one errors.

**Comment by lauraherring** [comment]
@danswick @Leighdiddy I've updated [the page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/data-curation/data-resources/data-interpretation/) with some additional examples and screenshots of what these issues will look like to users and would love feedback.

**Comment by gsa-suk** [comment]
2016 through 2022 historic audits from Census were migrated to GSAFAC.  Out of the 275+K audits, two audits could not be migrated due to severe data quality issues.  The audit year and dbkey information of these audits are:

2019	243753
2022	247680

**Epic references:**
https://github.com/GSA-TTS/FAC/issues/3364
https://github.com/GSA-TTS/FAC/issues/3994

**Comment by gsa-suk** [comment]
During investigation of census raw historic data for a helpdesk ticket for audit years 2016 through 2022, the following 3 audits were found to contain unusual data with respect to dates spanning multiple years.

<img width="1341" alt="Screenshot 2024-10-24 at 11 41 27 AM" src="https://github.com/user-attachments/assets/f70245df-42b4-4a02-8f29-03e153de3bcf">

**Comment by danswick** [comment]
I'm going to move this back into the backlog for now. It's something we still want to do and isn't technically _blocked_, but isn't a top priority at the moment. Let's continue documenting issues here in the meantime.

**Comment by danswick** [comment]
Based on some HD convos with @gsa-suk and @James-Paul-Mason, we think there are quite a few PDFs missing from the bulk PDF transfer we got from Census. I think we should create an updated list of these instances by looking for `null` entries in the `renaming.sqlite` table in [this folder on Drive](https://drive.google.com/drive/folders/1T5cwzB72uspSN2bhr_2ZWFulpl8uJPqR?usp=drive_link) (access limited) or possibly some other more definitive record. @gsa-suk, would you be able to create a quick export of those records? It would be great to see:

* Original filename
* Audit Year
* DBKEY
* Destination `REPORT_ID` (I'm pretty sure this is included in the table we looked at the other day)

**Comment by gsa-suk** [comment]
@danswick Pulling the null entries in renaming.sqlite, this is the list of historical audits that are missing pdf reports.  https://docs.google.com/spreadsheets/d/1i2oaDPvgdJKHwdL10M1BgHBrUKR6aqV0vW9S4aBVzag/edit?gid=14296428#gid=14296428

**Comment by gsa-suk** [comment]
Some historical audits only have pdf reports and no SF_SAC data.  The list is here - https://docs.google.com/spreadsheets/d/1L1F-kY60vA4zxzaeM1ACD1LyLOQFd3iyGCFpzqWc2cs/edit?gid=2106877303#gid=2106877303

**Comment by jadudm** [comment]
Some audits might have `secondary_auditors` (or other optional sections) included, but the submitters went back and said `No` to having that information. The record is logically inconsistent. Do we... do anything with this?

We have a cross-validation that now prevents this from happening, but there are both `CENSUS` and `GSAFAC` records with this contradiction.

**Comment by jadudm** [comment]
Documented.
