### ISSUE TITLE
Create data field mapping page

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3789]
As a user, I need a documentation resource that outlines each field in the single audit submission, including:

- the field name as I enter data
- the field name in the data output via search
- the validation for each field
- the field name in the Census FAC
- the field output name from the Census

This page will live under the data resources section and the URL will be fac.gov/data-resources/fields

### Tasks

```[tasklist]
- [ ] gather the field-by-field information
- [ ] draft page copy
- [ ] build the page in Git
- [ ] add card for the page to the Data resources hub page
```

This ticket won't be marked as complete until it meets the following acceptance criteria:
```[tasklist] 
- [ ] design review
- [ ] content review
- [ ] engineering review
```

**Comment by lauraherring** [comment]
Hey @danswick, can you please add the link to your Google Doc with the running notes on this page from the meeting we had on 4/30?

**Comment by danswick** [comment]
Whoops! Here's the doc: https://docs.google.com/document/d/1EOz6ULTu42AP_M5rxLj-PKnuxv7u7i_Ln6yF2cjAwo4/edit#heading=h.svopg3bux2i7

**Comment by danswick** [comment]
Rolled into https://github.com/GSA-TTS/FAC/issues/4465
