### ISSUE TITLE
Homepage content refinements

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#380]
Breakout issue of #367 

This issue covers the content for the FAC homepage content.

### Background

Original Figma mock [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3148%3A20146)
Updated Figma mock ([here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4142%3A19651))
Updated content in Google doc [here](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#heading=h.5y4yh9iy4gk6)

### Acceptance criteria (We'll know we're done when...)

- [x] Updated content is drafted and ready to be saved in Figma
  
### Tasks

- [x] Draft updated content for FAC homepage
- [x] Peer review with design team
- [x] Update Figma mocks

**Comment by MelissaBraxton** [comment]
Looks good! One minor suggestion - Consider keeping the scope narrow to just the homepage? (So remove the audit homepage from the task list).

**Comment by erinzstrenio** [comment]
@MelissaBraxton good call, just updated!

**Comment by erinzstrenio** [comment]
@melchoyce created some new Figma mocks with updated copy [here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4148%3A19746)!
