### ISSUE TITLE
Support 2024 audits

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3840]
Right now, users creating a new report can only select years up to 2023. This made sense in the lead-up to the 2023 audit year deadlines, but it is now 2024 and users would like to get started on their 2024 audit year reports. 

As an initial workaround, we should only reject end dates _in the future_, rather than hard-coding a particular year. We may eventually want to support end dates in the near future, but for now it should be sufficient to create a boundary at the present. 

### Tasks

```[tasklist]
- [ ] Update audit date picker logic to allow dates up to the present
- [ ] Change search filter defaults from 2023 to 2023 **and 2024** 
- [ ] Test a full submission locally or on preview to make sure 2024 audit years don't get caught in cross validation or dissemination 
```

**Comment by tadhg-ohiggins** [comment]
We don't actually prevent this in any way; we may at some point attempt to [prevent missives from the future via the app](https://github.com/GSA-TTS/FAC/issues/3659) but we don't at the moment. It turns out that the user in this case hadn't validated their UEI.

Closing.
