### ISSUE TITLE
Migrating fac.gov CX survey from Touchpoints to Qualtrics

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3841]
The fac website wants to move our site CX survey from touchpoints to qualtrix, so that we have accurate, trackable user feedback through fed approved software that we can use to inform decisions about our site and product. 

We currently have our CX survey hosted through touchpoints. We need to move to Qualtrix for compliance and continuity with other offices reporting metrics across OROS. 

### Tasks

```[tasklist]
- [x] @Leighdiddy shares [existing materials](https://docs.google.com/document/d/1IZj-mjqsgmv51rbHPPL5ULu_7wx6M6V-hIedjscOtVA/edit?usp=drive_link) with @James-Paul-Mason
- [x] Contact GSA Qualtrics POC (Liz Dodd) to begin process
- [x] Draft new survey
- [x] Collaborate with Qualtrics POC to revise
- [x] Route survey through Office of Customer Experience (OCE) for approval
- [x] Once approved by OCE,  fill out the FAST Track Request Template and send to GSARegSec@gsa.gov.
- [x] Proceed with PRA process
- [x] Get approval from GSA Legal
- [x] Email Ian and find out what pages eRegs uses for survey. Also ask if they embedded the survey following these instructions: https://it-humsci.stanford.edu/news/how-embed-qualtrics-forms-your-website AND <iframe width='100%' height='500px' src='https://feedback.gsa.gov/jfe/form/SV_8pqpHYK239kLfEi' style='border:0'></iframe>
- [x] Identify what screens we want to use survey for at fac.gov...Also should it be on the app itself?
- [x] Hand off survey for integration by engineer. Create GH ticket for the work.
- [x] Confirm that survey is live on static site #4129
- [x] Determine/document a schedule for who's checking data, how often, and how to check it. (create an SOP of sorts perhaps, that would live on G Drive?
```

```[tasklist]
### Tasks
```

**Comment by James-Paul-Mason** [comment]
Survey draft: https://feedback.gsa.gov/survey-builder/SV_8pqpHYK239kLfEi/edit

**Comment by James-Paul-Mason** [comment]
Received confirmation from Liz Brodd at OCE that I'll have the first review in hand by the end of the week

**Comment by James-Paul-Mason** [comment]
Updated task list as per OCE guidance.

**Comment by James-Paul-Mason** [comment]
Moving to blocked until the dev work is complete (launching survey on static site and app).

**Comment by James-Paul-Mason** [comment]
@Leighdiddy can you give [this SOP draft](https://docs.google.com/document/d/1xE7EpIyGCU8YSf7Y7z0c--26LWW_9Xdbr3qhIJIjIDA/edit) a quick review at your convenience?

**Comment by James-Paul-Mason** [comment]
Also, I am blocked from Qualtrics for some reason. ![Image](https://github.com/user-attachments/assets/fc71503b-41cb-49a1-a9c9-67ca818ccdeb)

**Comment by Leighdiddy** [comment]
@James-Paul-Mason the SOP looks good! I would add a short description of what to do with the collected feedback. ie "collected data should be summarized and shared with current CX and UX leads."
