### ISSUE TITLE
Publishing HD hours of operation to fac.gov and helpdesk site

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3849]
**As a user who has submitted a ticket to the fac.gov helpdesk, I want to know the helpdesk hours of operation so that I can anticipate how this may effect my ticket response time.** 

Currently we do not list hours of operation for the fac.gov helpdesk. Our hours of operation are 8a-6p EST, and we want to share that information both on our site and within the helpdesk.

### Tasks

```[tasklist]
- [x] Audit [static site](https://www.fac.gov/) for all mentions of the helpdesk.
- [x] Audit [helpdesk FAQ articles](https://support.fac.gov/hc/en-us) for any mentions of response time, update to include hours of operation
- [x] Add new article to helpdesk FAQ sharing hours of operation
- [x] If possible, add mention of hours of operation to [ticket template](https://support.fac.gov/hc/en-us/requests/new)
- [x] Add hours of operation to all mentions of the helpdesk on the static site
- [x] Tag colleague to review your work before closing ticket
```

**Comment by RanyeM** [comment]
https://support.fac.gov/hc/en-us/articles/29400580640397-Helpdesk-Hours-of-Operation

**Comment by RanyeM** [comment]
https://fac-gov.zendesk.com/admin/workspaces/agent-workspace/agent-interface
If you take a look at my [ticket](https://fac-gov.zendesk.com/agent/tickets/4441), you can see it at the bottom.

**Comment by RanyeM** [comment]
https://support.fac.gov/hc/en-us/requests/new 
added to the request ticket form
