### ISSUE TITLE
Tracking issue for notification system

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#386]
### Background
The approach we use for notifying users of any events contains a number of parts currently in existing stories; for the moment we're going to drop them here and will clean up this story in future.

#### Previously in https://github.com/GSA-TTS/FAC/issues/319
* [ ] The FAC creator specifies an auditor certifying official on the submission access page
* [ ] The auditor certifying receives an email notifying them that they've been added and to create an account or login

* [ ] The FAC creator specifies an auditee certifying official on the submission access page
* [ ] The auditee certifying receives an email notifying them that they've been added and to create an account or login

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] 
- [ ]

**Comment by danswick** [comment]
consolidating to https://github.com/GSA-TTS/FAC/issues/1401
