### ISSUE TITLE
Support change in audit threshold

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3872]
**Squad**: TBD
**Timeframe**: Must apply to submissions whose audit year begins October 1, 2024 and after.

The threshold for Single Audit submissions is changing from $750K to $1M.

## What problems are we trying to solve?

**This is the policy in the new UG.**

An entity with a Fiscal Year starting **on or after** October 1, 2024 must submit at a $1M threshold.

An entity with a Fiscal Year starting **before** October 1, 2024 must submit at the $750K threshold.

## What we can do today

We will need to address several things.

### Audit creation 

We need to rethink how the introduction to audit creation takes place. This will provide an opportunity to address several known weaknesses in the opening sequence:

1. Users cannot currently revisit any of these questions. This has been a pain point for users. It should be possible to revisit all of these questions from the checklist.
2. We can turn this multi-step form into a single form (if we want), simplifying implementation.
3. We can ask different questions about the threshold.

### Validations

We will need to improve our validations around this space. We recently added Federal Award checks that will need to be updated; we will want to check the reported FY start date and total amount expended, and make sure that they are reporting correctly. (E.g. a date before Oct 1, 2024 must clear $750K in expenditures, etc.).

## Context and further reading

Any number of [auditing houses have provided summaries](https://www.forvis.com/forsights/2024/04/omb-issues-updated-uniform-guidance), and there is the [UG itself](https://www.whitehouse.gov/omb/briefing-room/2024/04/04/the-biden-harris-administration-finalizes-guidance-to-make-grants-more-accessible-and-transparent-for-families-communities-and-small-businesses/).

```[tasklist]
### Tasks
- [x] Update documentation (fac.gov) to align with guidance, making clear timelines and thresholds
- [ ] Update submission templates where appropriate
- [ ] Update app.fac.gov copy
- [ ] Update app.fac.gov audit creation sequence
- [ ] Update app.fac.gov validations to correctly apply thresholds
- [x] Update all help desk materials (FAQ + macros) where thresholds are mentioned
```

**Comment by James-Paul-Mason** [comment]
Just documenting here that some FAQs and macros will need attention in addition to the static site.

**Comment by James-Paul-Mason** [comment]
Content work has already been ticketed separately in #4198. I'll be working from that ticket, but I will also come back to this ticket to check off the relevant content tasks from the list when complete.

**Comment by danswick** [comment]
I'm just going to close this one in favor of https://github.com/GSA-TTS/FAC/issues/4198. No judgement on this ticket, but the other one is newer and is tracking some other tickets in its tasklist :man_shrugging:
