### ISSUE TITLE
Program specific audit workflow is unclear for some users

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3875]
As a user submitting a program specific audit, I need to know how to answer required questions within the workflow that do not pertain to PSAs, so that I can submit my audit. 

We've received feedback via the helpdesk that certain required questions in the current workflow do not apply to program specific audits, so users aren't sure how to answer them. 

### Tasks

```[tasklist]
- [x] Write up a short summary of the issue: Please reference specific examples from the helpdesk, you can also include user supplied screen grabs
- [x] Share summary with @jadudm and determine who will send the question to AICPA and monitor for follow-up
- [x] Once response is received, respond to outstanding helpdesk tickets re: single program audits
- [x] Meeting with AICPA to determine how Program specific audit users should reply to existing questions.
- [x] Review meeting notes and begin content draft
- [x] Create macro and FAQ
- [x] Send to Mary and AICPA team to review for accuracy.
- [ ] Design/Dev handoff/co-work and implementation in FAC app.
```

**Comment by Leighdiddy** [comment]
@James-Paul-Mason has assigned himself to outstanding hd tickets mentioned above

**Comment by jadudm** [comment]
Excellent. @Leighdiddy , we can decide tomorrow live/in Slack who will ship the mail.

**Comment by James-Paul-Mason** [comment]
Just checked off task #3. In my opinion, the answer to the question of copy changes is YES. I am happy to be a part of that process.

**Comment by James-Paul-Mason** [comment]
We may want to collect the GH ticket links for users who were experiencing/describing their issues with Program Specific Audits here. Note to self...

**Comment by Leighdiddy** [comment]
Blocked pending clarification - @lauraherring , would you see this as a case to address with microcopy/helper text on the current site, or wait until the PRA revisions for larger overhaul?

**Comment by jadudm** [comment]
1. Are we 100% certain these questions are unnecessary when `program-specific` is selected? 
2. Who can we talk to in order to determine whether a documentation or logic choice is better?
3. Who is responsible for doing that work?

We can discuss this internally and come up with a good course of action.

**Comment by danswick** [comment]
@James-Paul-Mason to follow up with @jadudm to schedule stakeholder call / get clarity on the above questions.

**Comment by James-Paul-Mason** [comment]
There is also the PDF page number requirement that is a pain point for users. We even have a macro for it. I suppose it would be appropriate to address that issue in this ticket as well. Here's an example: https://fac-gov.zendesk.com/agent/tickets/4459

**Comment by James-Paul-Mason** [comment]
Notes/Review
https://fac-gov.zendesk.com/agent/tickets/2071
https://fac-gov.zendesk.com/agent/tickets/3554
https://www.ecfr.gov/current/title-2/subtitle-A/chapter-II/part-200/subpart-F/subject-group-ECFRfd0932e473d10ba/section-200.507

**Comment by James-Paul-Mason** [comment]
Meeting set for Monday, September 9⋅11:00am – 12:00pm

**Comment by James-Paul-Mason** [comment]
Completed meeting with AICPA. Decided that we would create a help desk article to instruct users which selections to make on the screen in question. Also decided to place a link to this article near "Program Specific Audit" option in the user flow. Need to follow up with Mary/Brianna to determine which selections users should make and why.

**Comment by James-Paul-Mason** [comment]
Great meeting on September 30th with Tasha, Mary, Brianna, Matt, and Analyn. They provided excellent suggestions in terms of how we can provide better instruction to Program specific audit users both short term (helper text, instructions, question-by-question) as well as things to consider longer term. I have detailed notes documenting all of their suggestions/conclusions. Mary and team agreed to review our help documentation before we publish it to ensure accuracy. Also, as per @jadudm, we are going to take a closer look at the following questions before developing the helper content: 

![Image](https://github.com/user-attachments/assets/f83fe81d-22d9-4e79-ae58-d0806b35d228)
![Image](https://github.com/user-attachments/assets/812473ae-d50d-41b7-b824-6e891b731ba4)

**Comment by danswick** [comment]
@James-Paul-Mason to update this ticket with info about where we're stuck (field-by-field would be best) and what we need to do to get unstuck.

**Comment by James-Paul-Mason** [comment]
We are no longer stuck in terms of the content necessary to move forward. After my meeting with Matt, we decided there needs to be a page on the static site with guidance for program specific audit folks. I will bring this up at the next design sync. We may need to ticket out the static site update separately (within this ticket).

**Comment by James-Paul-Mason** [comment]
Documenting[ my notes](https://docs.google.com/document/d/103hnw7vRlh3cUZzVA5vB978b_2rAmQjWqExrtlu9kY0/edit) for implementation of static site content.

**Comment by James-Paul-Mason** [comment]
@Leighdiddy I was planning to bring this up at design sync today. At this stage, I am looking for some final feedback on the best way to present the explanatory text to users.

**Comment by James-Paul-Mason** [comment]
FAQ language finalized, and [article published](https://support.fac.gov/hc/en-us/articles/32670960276365-Program-specific-audits-how-to-complete-the-Audit-Information-form)
[Macro created and currently live](https://fac-gov.zendesk.com/admin/workspaces/agent-workspace/macros/32699644304397)
FAQ created for [Audit report (PDF) upload issue](https://support.fac.gov/hc/en-us/articles/32700168226445-Program-specific-audits-how-to-upload-the-Audit-report-PDF) for program-specific audits. There was already a macro for this.

**For documentation purposes: for the final step in the task list,** we need to include a link to the Audit information FAQ in the Audit information section of the app (at the top, directly under Audit information: "For those completing program-specific audits, please refer to [this guide.](https://support.fac.gov/hc/en-us/articles/32670960276365-Program-specific-audits-how-to-complete-the-Audit-Information-form)" 

We also need to include the following text in the Audit Report PDF section: "All components of the audit report package must be merged into a single PDF file and meet the uniform guidelines below. For more information on PDF formatting, please review our PDF guidelines. For those completing program-specific audits, please refer to [this guide](https://support.fac.gov/hc/en-us/articles/32700168226445-Program-specific-audits-how-to-upload-the-Audit-report-PDF)."

**Comment by James-Paul-Mason** [comment]
@jperson1 Thanks for being willing to help with this! It's totally fine if this is a after-the-new-year project for us.

**Comment by jperson1** [comment]
For clarity on placement, we want things here?

Audit information:
![image](https://github.com/user-attachments/assets/8d7e0880-e211-41f2-8d61-fb1c171bb4e3)

PDF upload:
![image](https://github.com/user-attachments/assets/f04bb9e0-cfec-4161-a3f0-e5860a617154)

**Comment by James-Paul-Mason** [comment]
@jperson1 That is perfect! Amazing. Thank you!

**Comment by jperson1** [comment]
^ Here's the relevant PR with screenshots, and I've also updated the Figma Source of Truth doc to match the changes.

**Comment by James-Paul-Mason** [comment]
@jperson1 Thank you for the heads-up on needing to sign in...that was an error on my part, but I just fixed it. I think it was just a permissions thing, but just to be safe here are the correct links:
[Program-Specific Audit Information Guide](https://support.fac.gov/hc/en-us/articles/32670960276365-Program-specific-audits-how-to-complete-the-Audit-Information-form)
[Program-Specific PDF Guide](https://support.fac.gov/hc/en-us/articles/32700168226445-Program-specific-audits-how-to-upload-the-Audit-report-PDF)

**Comment by jperson1** [comment]
Awesome, all fixed!
