### ISSUE TITLE
Tribal opt-out statement contradicts certification statement

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3878]
As a tribal user who has chosen to opt out of making my information public, I want to understand why my certification statement says "The full reporting package and auditor's report may be shared publicly by the Federal Audit Clearinghouse or the report auditee, as required by the Uniform Guidance.", so that I know whether or not my information may be shared publicly. 

See thread for context: https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1714420977522319

### Tasks

```[tasklist]
- [x] Revise copy for [Audit certification process](https://www.fac.gov/audit-resources/how-to/#audit-certification-process-2) to include acknowledgement of discrepancy for tribes who have opted out of public dissemination.
- [x] Share copy with teammate to proofread
- [ ] Publish to static site submission guide
```

**Comment by Leighdiddy** [comment]
Paused to discuss alternate solution (having an "if/then" rule on the tribal opt out question, so if they select "opt out" then the last copy that contradicts the opt out is not included in the cert statement) w @danswick

**Comment by James-Paul-Mason** [comment]
@Leighdiddy @danswick As I begin the work for this ticket, I just want to confirm that we are proceeding with updating the submission guide instructions, rather than pursuing the two options mentioned in your respective comments above.

**Comment by James-Paul-Mason** [comment]
@Leighdiddy Could you please [review and approve this content](https://docs.google.com/document/d/15UxYk1H1NxBeibWCLMrxmjAxVY1KJ4XXR6o-K_b564Q/edit?tab=t.0)? After approval, I will update the static site, launch the HD article, and create a PR.

**Comment by lauraherring** [comment]
@James-Paul-Mason @Leighdiddy The GDoc looks good to me. I made one small copy edit but otherwise I think this is good to go.
