### ISSUE TITLE
User login routing

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#388]
### Background
An ideal login flow for users is somewhat complicated and involves checking on data about what submissions a user is associated with, as well as presumably having them return to the URL they attempted to navigate to prior to getting redirected to login.

Related to [#332](https://github.com/GSA-TTS/FAC/issues/332).

Rather than taking on that complexity now, we'll divide it in three:

*   Upon login a user will be redirected to the “My submissions” page, without any checks on how many audits they have. This is covered by [#401](https://github.com/GSA-TTS/FAC/issues/401), assuming that “home” and “My submissions” mean the same thing (and if they don't, we should pick one to be the default).
*   Enhancement: if a user tries to load the page for their submission `x` and are not logged in, upon logging in they will end up on the page for submission `x` [#408](https://github.com/GSA-TTS/FAC/issues/408).
*   Enhancement: upon login a user will be redirected to a destination based on how many submissions they're associated with [#407](https://github.com/GSA-TTS/FAC/issues/407).

### Acceptance Criteria (We'll know we're done when...)

- [ ]   When a user logs in, they are redirected to the “My submissions” page.

### Tasks

- [x] Break up issue.
- [ ]   [#401 Front end access control](https://github.com/GSA-TTS/FAC/issues/401)

### Not in scope
- [ ] Deal with the “create” copy on the logged-out home page in certain states.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins I'm going to put this in the backlog until we refine, scope and assign a milestone to it.

**Comment by tadhg-ohiggins** [comment]
Removing `needs scoping` on the basis that I think it can't be scoped until some refinement is done.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins Fair flag that we might want to consider more routing options. My hope is that we can make a quick decision here. 

Here is my proposal for user login routing for design to review (cc @melchoyce, @sreuber): 

* When a user logs in and has no submissions, they are redirected to step 1 of the pre-SAC flow
* When a user logs in and has exactly 1 submission, they are redirected to the audit start page
* When a user logs in and has two or more submissions, they are redirected to the "My submissions" page

**Comment by sreuber** [comment]
@petermarks-gsa @tadhg-ohiggins These make sense to me, though if users can land on the "My Submissions" page with zero, the page state for that will need to be updated ([this](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=2709%3A12631) was the only mock I could find for that page, not sure if an alternative exists? cc @austinhernandez)

**Comment by petermarks-gsa** [comment]
@sreuber I think what you have designed for zero submissions states generally works fine as it communicates a next step. I could see some minor copy tweaks being done, like clearly acknowledging you have no submissions, but I don't think that will change scoping.

**Comment by sreuber** [comment]
Yeah, just changes in copy was all the more I would expect there. @erinzstrenio will have some insight in that case.

**Comment by erinzstrenio** [comment]
Maybe we can add this to the design + dev agenda tomorrow so I have a better sense of the copy you're looking for on this page?

**Comment by petermarks-gsa** [comment]
@erinzstrenio Happy to chat about copy then. @sreuber @melchoyce @austinhernandez unless I hear otherwise EOD, I'm going to assume you all concur Scott's 👍 on the below proposal and move forward with that as the acceptance criteria: 

https://github.com/GSA-TTS/FAC/issues/388#issuecomment-1196948624

**Comment by melchoyce** [comment]
Agreed!

**Comment by petermarks-gsa** [comment]
Great, let's move forward with my proposal, then. @tadhg-ohiggins, I've updated the issue description removed the needs refinement label and added the needs scoping label.

**Comment by tadhg-ohiggins** [comment]
I removed the rules based on user number of submissions and moved that to #408 as a future enhancement, and moved the “they should end up where they were trying to go before logging in” feature to #407 as a future enhancement, and changed the description accordingly.

**Comment by tadhg-ohiggins** [comment]
This issue will now effectively be done when #401 is done.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins Should we close this as "not planned" as the breakout issues are their own stories to break up?
