### ISSUE TITLE
Bug: Auditee name no longer required on Pre-SAC step 3

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#389]
### Background

After talking with @jasnakai about #317, he found that, on step 3, after removing the auditee/auditor contact name fields (as discussed in the ticket), the API still requires it. These need to be removed. His error:

```
{"next":"/sac/eligibility","errors":"We're missing required fields, please try again.","missing_fields":["auditee_name"]}
```

### Acceptance Criteria (We'll know we're done when...)

- [ ] The `/sac/accessandsubmission` (or other) API endpoint(s) accepts a data object without the name as valid
- [ ] All other conditions of missing data (start/end date, UEI) still function the same

### Tasks

- [ ] Remove the field from the `AccessAndSubmissionSerializer`
- [ ] Modify or remove associated tests
