### ISSUE TITLE
🅛 Front End - My audit submissions Table

### ISSUE THREAD

**Issue by rachelschneiderman** [GSA-TTS/FAC#391]
Breakout of https://github.com/GSA-TTS/FAC/issues/343

As an authenticated FAC user, so that I may easily manage all my submissions, I need to be able to see a summary of all the Single Audit Checklists I have created.

## Pre-Conditions:
* User with at least one submitted (and no more than 5) SACs for the fiscal year is logged into FAC

## Acceptance Criteria:
* User can view all the Single Audit Checklists they have submitted
* All columns are sortable, default sort is report ID
* Pagination works
* UEI modal/tooltip works

## Design: 
![image](https://user-images.githubusercontent.com/20249233/180496724-da969e60-0632-4072-9bce-2cc0d0768107.png)
* NOTE: Links for Report ID and Auditee UEI column are not included as part of this story 

#### 1) FAC user with no submissions views 'My audit submissions'
* Login to FAC as user with no submissions
* Route to '/submissions'

    Expected results: 
    - [ ] Submissions table is not displayed
    
#### 3) FAC user with at least one submission views  'My audit submissions'
* Login to FAC as user with 1-5 submissions
* Route to '/submissions'

     Expected results:
    - [x] Submissions table is displayed 
    - [x] Table column are: Report ID, Status, Auditee UEI, Fiscal Year End Date,Auditee Name
    - [x] Table is sorted by Report ID ascending
    - [x] Table can be sorted by every column, ascending and descending   
  
## Tasks:
- [x] Add 'My audit submissions' page - Rachel (https://github.com/GSA-TTS/FAC-Frontend/pull/33)
- [x] Endpoint to retrieve submissions by user - Rachel & Sarah (https://github.com/GSA-TTS/FAC/pull/397)
- [x] Create My audit submissions table - Rachel
  - [x] Default sorted by `Report ID` ascending
  - [x] All columns should be sortable

## Definition of Done:
- [ ] Acceptance criteria for the story has been met
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.
- [ ] Automated test scripts have been written
- [ ] New screens are covered with automated accessibility testing
- [ ] Field level and page level validation integrated and functioning
- [ ] Code refactored for clarity and to remove any known technical debt
- [ ] READMEs and any other appropriate documentation has been updated

## Related tasks
https://github.com/GSA-TTS/FAC/issues/424

**Comment by petermarks-gsa** [comment]
@rachelschneiderman One minor thing that appeared to get lost in translation is the post-login redirect behavior. We don't want to always redirect people to the audit submissions page. We're closing in on an exact AC in https://github.com/GSA-TTS/FAC/issues/388, but it's out of scope in this issue. Can you please change "Login to FAC" in your test cases to "View my submissions table"? 

This came up as I was testing Milestone 1 end to end. I suggest we revert the routing change you did for now so we test that end to end, which I did here: https://github.com/GSA-TTS/FAC-Frontend/pull/35

**Comment by petermarks-gsa** [comment]
@heymatthenry @jasnakai Following up on estimation meeting today, flagging that the goal is to estimate this before sprint planning tomorrow.

**Comment by tadhg-ohiggins** [comment]
Note that this ticket addresses its AC as written: “User can view all the Single Audit Checklists they have submitted” but not the AC from #343: “The user will see a table containing the audits they're associated with.”

In the spirit of moving forward with the minimal approach, I think we leave this ticket as is in terms of that aspect, and I'll add a new ticket with the rather more significant backend work involved for user-associated SACs (as previously outlined [here](https://github.com/GSA-TTS/FAC/issues/343#issuecomment-1188426739) ) to #343.

**Comment by heymatthenry** [comment]
We're handling pagination for this all on the client side, right @tadhg-ohiggins & @geekygirlsarah? I feel like that's where we landed on this when we talked about it the other day. This feels 🅛 to me if so. 🅜 otherwise.

cc: @jasnakai

**Comment by tadhg-ohiggins** [comment]
Yes, pagination is client-side.

**Comment by petermarks-gsa** [comment]
Discussed at standup: Version column is not in json payload, @jasnakai moving forward on other things but need to clarify that.

**Comment by mogul** [comment]
This issue got archived from the board, but is still included in M2 and open. Should it be closed?

**Comment by mogul** [comment]
_ping_ @jasnakai should this be closed? Asking because I think it's done, and also because it was listed as blocking https://github.com/GSA-TTS/FAC/issues/185#issuecomment-1252661058

**Comment by jasnakai** [comment]
Yes, this is completed.
