### ISSUE TITLE
Revise microcopy/design for ZD CSAT auto-generated email and satisfaction survey

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#3914]
After a ticket is solved in ZD, users receive an email inviting them to rate the help they received from the FAC Helpdesk. There are three components in this user flow that are customizable: the subject line of the auto-generated email, the content of the email itself, and the survey content/design.  

I hypothesize that if I revise these components with an emphasis on proper UX Writing & Design principles, the percentage of survey respondents will rise. This will give us a clearer picture of FAC user experience as it relates to the Helpdesk. In addition, this feedback/data may assist in CX/UX revisions and general decision-making. 
### Tasks

```[tasklist]
- [x] Subject line
- [x] Email content
- [x] Survey content/design
- [x] Document launch date for changes
- [x] Compare percentage of respondents over a certain period (TBD)
```

**Comment by James-Paul-Mason** [comment]
Completed. I documented that the new microcopy for the survey will be active as of July 1st.
