### ISSUE TITLE
Configure and Run ESLint on All JS Files

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#3933]
# Configure and Run ESLint on All JS Files

### Context:

During dependency update PR https://github.com/GSA-TTS/FAC/pull/3932, ESLint was migrated to its v9.0.0 configuration system. Here, it is noticed that ESLint:
1. Is run via `npx run check:eslint`, which in turn only covers the static/js library
2. Does not inherently ignore any files (which is possibly why we specify just the one directory)

This means ESLint does not cover any Cypress files, despite being configured to do so. It also doesn't cover standalone/separate JS files, such as the ESBuild dedicated file, `build-assets.js`. 

### Tasks

```[tasklist]
- [x] Have `npx run check:eslint` cover all* JS files (Cypress, `build-assets.js`)
- [x] Remove the `--ignore-pattern` argument from `check:eslint` to rely on the config file instead
- [x] Configure `eslint.config.mjs` to ignore the proper directories (compiled directories such as `staticfiles`, `node_modules`, and `static/compiled`)
- [x] Choose appropriate rules for the Cypress ESLint plugin (defined [here](https://github.com/cypress-io/eslint-plugin-cypress/tree/master/docs/rules)) - maybe, the default are fine
- [x] _Resolve any issues discovered by ESLint, now that it covers everything_
```

A casual enabling of ESLint for the Cypress directory reveals about 100 errors:

```
jperson@FM-C02DX829ML7J backend % npx eslint cypress/

/Users/jperson/Documents/GSA/FAC/backend/cypress/e2e/audit-info-form.cy.js
  20:5   error  It is unsafe to chain further commands that rely on the subject after this command. It is best to split the chain, chaining again from `cy.` in a next command line  cypress/unsafe-to-chain-command

...

/Users/jperson/Documents/GSA/FAC/backend/cypress/support/workbook-uploads.js
  16:38  error  'request' is defined but never used  no-unused-vars

✖ 100 problems (100 errors, 0 warnings)
```
