### ISSUE TITLE
figure out what to do with the "My Audit Submissions" page

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#394]
This issue covers the design and functionality of the "My Audit Submissions" page

### Background

[Figma page](https://www.figma.com/file/8REinLFKSMj7pwQ7JIEHGW/FAC-Sprint-11-prototype?node-id=407%3A3588)

### Open questions 

- Can you still revise an audit after it's been submitted? (No)
- Will the submitted audit "disappear" after it's been submitted? (No)
  
### Tasks

- [x] Review open questions in 7/28 design + dev sync
- [x] Update content ([doc](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#heading=h.3i0lmix9p3bo))
- [x] Peer review
- [x] Update Figma mocks [(link)](https://www.figma.com/file/8REinLFKSMj7pwQ7JIEHGW/FAC-Sprint-11-prototype?node-id=407%3A3588)

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end

**Comment by austinhernandez** [comment]
June 28 design dev sync: 

Design question for devs: What happens to your submitted audit history once you submit an audit? How can you uncertify an audit? How edge-case is that?

Tadhg: We do not support uncertifying at the moment; not sure how common that requirement would be.
Census system allows for submissions going from a status of submitted back to in progress after Census staff do a manual review of them—but we don’t intend to support that at all. The long-term need (I think) here would be for the reviewing agencies to be able to get messages to the submitters to let them know they need to make changes.

**Comment by erinzstrenio** [comment]
[Updated text](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#heading=h.44u63rrv7phf) based on sync conversation yesterday - ready for peer review cc @austinhernandez

**Comment by erinzstrenio** [comment]
Here's the updated page on Figma

<img width="606" alt="Screen Shot 2022-08-30 at 12 11 26 PM" src="https://user-images.githubusercontent.com/46569779/187499113-12cf461a-f954-44c0-ba0f-f689128fc930.png">

**Comment by melchoyce** [comment]
@petermarks-gsa In case you need to track this ^
