### ISSUE TITLE
Validation: Improve finding reference controls in `findings` workbook

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3948]
Consider the following:

| award_reference	| reference_number | 	type_requirement	| is_modified_opinion	| is_other_findings |	is_material_weakness | 	is_significant_deficiency |	is_other_matters	| is_questioned_costs |	is_repeat_finding |	prior_finding_ref_numbers |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
AWARD-0003	| 2023-001	| L	| N | 	N | 	Y	| N| 	N | 	N	| Y	|2022-001 |
AWARD-0003	| 2023-002	| L | 	N |	N |	Y |	N | 	N|	N |	Y|	2022-001 |
AWARD-0004	| 2023-001	| L |	N |	N |	N |	Y |	N|	N |	N|	N/A |

Award 3 has findings reference 1 and 2. This is good.

Award 4 has finding reference 1. This is appropriate; a single finding can apply to multiple awards.

What does not make sense is that the auditor findings are _different_ for row 1 and row 3. That is, finding reference `2023-001` is being described in *two different ways*. In the case of finding 001, `is_material_weakness` is both `Y` *and* `N`. 

This can be seen in report [2023-05-GSAFAC-0000027356](https://app.fac.gov/dissemination/summary/2023-05-GSAFAC-0000027356).

## Validation improvement

Our data validation on this sheet should ensure that a given finding reference (e.g. `2023-001`) has the same values in every instance. 

For error reporting, we should report the first instance we find (in this case, row 1), and report each deviance as a separate error. So, we would expect one error to be reported back in this case, for row three. Something akin to:

```
On row 1, you reported 2023-001 as ..., and on row 3, you reported it as .... The FAC cannot accept one finding reference with different <insert word...>
```

```[tasklist]
### Tasks
- [ ] Determine correct language for the properties associated with a finding reference.
- [x] Implement validation
- [x] Add a findings sheet to `should pass` and `should fail` in the test suite
- [ ] Document this change as part of the next monthly update
```

**Comment by James-Paul-Mason** [comment]
Documented this ticket/topic for inclusion on the monthly update.
