### ISSUE TITLE
Design review of Milestone 1

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#395]
Background: We haven't been doing ticket-level design review. 

Acceptance Criteria: 
- [ ] Reviewed the features delivered in Milestone 1 (login + first three pre-FAC forms)
- [ ] File tickets for any needed fixes
- [ ] Advise on process for this going forward: Should we do it after each milestone or after each story?

**Comment by melchoyce** [comment]
Appreciate these testing steps, thanks @petermarks-gsa!

**Comment by melchoyce** [comment]
Follow-up: we'll create new issues for any bugs we find.

**Comment by melchoyce** [comment]
Completed a pass-through of the audit creation flow. Recording some notes here for storage, then I'll work on turning each into its own issue with screenshots and clarification:
- Can we add non-breaking spaces between required form labels and the * so the * doesn't get bumped to a new line?
- Continue/cancel buttons — reference #396
- Cancel button doesn't work
- Decrease space between form fields (1.5rem instead of 3)
- UEI search field too small, button too compact
- UEI lookup: can we cut the auditee name field before the lookup is complete? It's hard to tell the field is disabled and nothing will happen until you hit the search button to confirm your UEI. Might be worth rethinking this interaction and replacing the lookup here with a button that opens a modal for the lookup flow entirely, like in #304 
- In the latest mockups, the UEI lookup error message is displayed to the right of the field, outside of the form markup. Should that still be the case, and can it appear outside of the form? To check with Austin.
- Summary box: remove right margin on the list items
- Can we add links to the progress bar to navigate forward/back between sections? Is that something USWDS allows? Doesn't seem to be a clear way back, since I expect "cancel" to literally cancel the entire submission process.
- Email address: "can't be null" error needs copy update. "Please enter a valid email address" maybe? To check with Erin.

**Comment by melchoyce** [comment]
> Can we add links to the progress bar to navigate forward/back between sections? Is that something USWDS allows? Doesn't seem to be a clear way back, since I expect "cancel" to literally cancel the entire submission process.

Checked the component, and it looks like there is **not** an example linking the numbers in the demo at least: https://designsystem.digital.gov/components/step-indicator/

I do think it would be good to allow people to move backwards if needed. @austinhernandez what do you think about this one?

**Comment by melchoyce** [comment]
> In the latest mockups, the UEI lookup error message is displayed to the right of the field, outside of the form markup. Should that still be the case, and can it appear outside of the form?

Checked with @sreuber about this, and I think I was actually looking at the wrong mockup. What's on staging is good to go!

Scott had one copy note for when @erinzstrenio is back:

> I wonder if the "you will have to confirm your UEI before [your] (spelling) submission can be certified" and the "you will be able to update the UEI later" could be switched? With the latter being after the comma and the former in the next sentence.
