### ISSUE TITLE
NR dashboard to support periodic log audits

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3953]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** periodically review logs
**as a** member of the FAC team
**I want** a dashboard that encodes all of our log review facets.

# Acceptance Criteria

We want to have dashboard automation/reporting for *at least* the following.

```[tasklist]
### Tasks
- [x] The existence (and, in the case of `production`, minimum row count) of known tables is checked daily.
- [x] Verify that no new tables have come into existence when compared to the set of known/existing tables.
- [x] Upon audit submission completion, we should log enough information to contact everyone who submitted in a given time window (if needed, in case of data loss) (This means certifiers and, ideally, all editors on a submission.)
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

No security considerations.

**Comment by asteel-gsa** [comment]
Note:
- Part of this tool should, before a backup, check to see if the table exists, and notify via slack its output.
- Following that, we can set this tool to run every hour, in the event of middle hour deployments (`X:01 - X:59`) to see at the top of the hour, did a table disappear, and at the top of every 2 hours, did a table disappear before it backed up the RDS
