### ISSUE TITLE
Public facing office hours

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3959]
As part of our work over the next two quarters, we discussed having monthly, public-facing office hours to support recipients and auditors as they work on their SF-SAC/SA submissions.

This placeholder ticket is for further discussion and revision in order to launch those office hours in a timely manner.

```[tasklist]
### Tasks
- [ ] Discuss timeline, schedule, ops
- [ ] Develop planned activities for each office hours on FAC.gov
- [ ] Review planned activities with representative users
- [ ] Identify messaging partners
- [ ] Develop messaging
```

**Comment by danswick** [comment]
Combining with https://github.com/GSA-TTS/FAC/issues/4208
