### ISSUE TITLE
As a user, I want buttons to be in consistent positions across all pages so I don't click the wrong action.

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#396]
This issue covers the design of all pages that use buttons: 

### Background

| Primary + Link  | Secondary + Primary |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/2846578/181075255-0f7d2fb4-9e9d-4a67-8837-271f2e91348f.png) | ![image](https://user-images.githubusercontent.com/2846578/181076121-26f3d733-685c-4f89-8415-412576cbc13f.png) |

In some cases, we use a primary button for the primary action on the left, with a link for the secondary action to the right of that. In other places, though, we have a secondary button on the left, with a primary button on the right. We should pick one of these patterns and move forward with it.

I personally think the primary button + link pattern is a little more intuitive.

### Acceptance criteria (We'll know we're done when...)

- [ ] We identify all screens that use the pattern we want to replace
- [ ] We update the mockups for all of those screens to use the same consistent pattern
  
### Tasks

- [ ] Update mockups with final button pattern
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by petermarks-gsa** [comment]
@austinhernandez @melchoyce Sounds like this might be covered in another ticket? Maybe link as a breakout for clarity?

**Comment by melchoyce** [comment]
Related to https://github.com/GSA-TTS/FAC/issues/375, but extends outside of just Audit Start.

**Comment by melchoyce** [comment]
All of these instances have been updated in the "All Screens" Figma page: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A22829

**Comment by pkigongo** [comment]
Not relevant until whole front end functioning in unified Django app. Also depends on how much we're bringing over from Milestone 1. If we're re-implementing with the most recent designs, this shouldn't be an issue.
