### ISSUE TITLE
User and Documentation Research for FAC API

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3963]
# What question are we trying to answer?

The API documentation was not written with any particular user in mind. We want to better understand:

1. How they got started?
2. What they were trying to achieve?
3. What they found useful?
4. What they found confusing?

Our goal is to develop a profile (or profiles) for one or more "kinds" of developer who is looking to use our API.

##  What can we do next?

We can talk to some of our existing API users and learn about their experience working with the FAC API. We'll want to prepare some starter questions in advance, and use those to guide the conversation around the API.

```[tasklist]
### Tasks
- [x] Develop a set of potential questions (4-5) informed by the existing content review
- [x] Draft research plan according to template(ish)
- [x] Determined user types with Leigh
- [x] Determine participants needed
- [x] Meet with James Mason to draft email/slack message and send finalized questions to participants
- [x] Review questions with **Leigh**, Dan, or Matt.
- [x] Ask on the developers list if anyone would be willing to talk to us about their experience using the API.
- [x] Finilized questions with Matt, Leigh, James, or Dan
- [x] Meet with participants for feedback
- [x] Organize feedback for Design and Content Review
```
