### ISSUE TITLE
Improve submission support/documentation

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3968]
# What problem are we trying to solve?

We have work to do in response to GAO recommendation 8:

> The Administrator of GSA should, upon consulting with professional audit organizations, provide additional training to auditors and recipients to help ensure that they complete FAC data collection forms accurately, completely, and consistent with the audit report.

In short, we want to improve our user's experience, and in doing so, continue to drive improvements to the collection of data.

## What we can do today

We have work underway that makes sure that all of our instructions include references back to the UG (https://github.com/GSA-TTS/FAC/issues/2454). This is a first step.

We have committed to running monthly, public-facing office hours for at least 6 months, at the end of which time we will evaluate their effectiveness.

We can do some light content usability research on our existing submission support materials. 

```[tasklist]
### Tasks
- [ ] Develop a plan (staffing, comms) for monthly office hours.
- [ ] Communicate office hours schedule
- [ ] Develop research plan for evaluating the effectiveness of our existing submission support materials.
- [ ] Develop a research plan for evaluating the effectiveness of our materials supporting search.
```

# What we might aim towards

Our initial steps will inform next steps.  It may be that we need to develop more detailed instructions to support auditors and auditees (especially first-time or infrequent submitters to the FAC) in their Single Audit submissions. Those instructions may want to be informed by our Zendesk macros, which represent knowledge that needs to leveraged often; in that case, perhaps it should also be woven into our support mateirals.

We have little-to-no evaluation of our search support materials.

In all cases, these investigations are likely to drive improvements across the FAC, from content through to engineering.

**Comment by jadudm** [comment]
fac.gov does little to nothing to educate what the Single Audit is or for, interestingly.

Perhaps out of scope for this particular work (which is about the submission), we may want to think a bit more broadly about the broader audience. This could become a separate ticket.

AICPA has [a nice overview](https://us.aicpa.org/content/dam/aicpa/interestareas/governmentalauditquality/resources/singleaudit/uniformguidanceforfederalrewards/downloadabledocuments/keyplayerssingleauditprocess.pdf) of SAs, and we should keep things like this in mind as we consider the Clearinghouse's role in terms of education re: SAs, writ large.

**Comment by danswick** [comment]
I think this is covered in some of the other docs / content related tickets that have come in over time.
