### ISSUE TITLE
Quarterly web content review

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3984]
Per [the TTS web content governance policy](https://docs.google.com/document/d/1idb6Y15EnEHWcMq9U7msLQjbECuCNxKBipcmvzwuX54/edit#heading=h.2bcmg0ub5ako), the following tasks need to take place for fac.gov by July 12:

### Tasks

```[tasklist]
- [x] review fac.gov content against web content policy standards
- [x] update any necessary content
- [x] submit quarterly confirmation form to TTS leadership
```

**Comment by danswick** [comment]
Laura to add links to the review guidelines and get final decision re: OMB notices.

@ChrisB-16 to follow up to capture this work in our SSPP.

**Comment by lauraherring** [comment]
@danswick and @ChrisB-16 I've added the link to the policy to the ticket description.

**Comment by lauraherring** [comment]
I completed the review and submitted the form on 6/27. Moving this ticket to done.
