### ISSUE TITLE
Code cleanup / dead code removal

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3993]
# What what?

Let's remove some code that is no longer in use. 

## Candidates

```[tasklist]
### Tasks
- [x] api
- [x] data_distro: https://github.com/GSA-TTS/FAC/pull/3995
- [ ] report_submission + audit
- [x] data fixtures *everywhere*
- [x] Removed dead code : https://github.com/GSA-TTS/FAC/pull/4109
```

# Notes

* report_submission + audit: Might involve moving URLs up to top-level.
* api: some parts need to be kept
* data_distro: possibly nothing needs to be kept
* cms: probably not needed at all (was for possible web content)
* data fixtures: what? why? where? for whom? Should we send some of them a card?

**Comment by timoballard** [comment]
The pre-SAC form has 3 steps:

#### eligibility - basic questions that determine whether or not you should be submitting
- [Frontend template](https://github.com/GSA-TTS/FAC/blob/main/backend/report_submission/templates/report_submission/step-1.html)
- When a user clicks Continue, [a Javascript handler submits the form](https://github.com/GSA-TTS/FAC/blob/dda11bdfd31a000601e427379a3fac6ee9e7f1f8/backend/static/js/check-eligibility.js#L54). The form data is received by a [Django view](https://github.com/GSA-TTS/FAC/blob/dda11bdfd31a000601e427379a3fac6ee9e7f1f8/backend/report_submission/views.py#L45) in the report_submission app, which forwards the form data to the eligibility-check [function](https://github.com/GSA-TTS/FAC/blob/dda11bdfd31a000601e427379a3fac6ee9e7f1f8/backend/api/views.py#L43) in the api app. This function uses the [EligibilitySerializer](https://github.com/GSA-TTS/FAC/blob/dda11bdfd31a000601e427379a3fac6ee9e7f1f8/backend/api/serializers.py#L46) to deserialize and validate the form data. If valid, the data is saved to the user’s [UserProfile](https://github.com/GSA-TTS/FAC/blob/dda11bdfd31a000601e427379a3fac6ee9e7f1f8/backend/users/models.py#L33). The user is then redirected to step 2.

#### auditee info - UEI, audit period start/end dates
- [Frontend template](https://github.com/GSA-TTS/FAC/blob/main/backend/report_submission/templates/report_submission/step-2.html)
- When a user enters a UEI and clicks Validate UEI, a Javascript handler passes the UEI to the backend with an ajax call to /api/sac/ueivalidation. [The view](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/views.py#L215C7-L215C15) for this endpoint is a Django REST Framework (DRF) API view. 
- [The use of DRF in the FAC application](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0004-use-drf-for-the-api.md) dates back to the original architecture, which intended to pair a [static frontend](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0009-use-11ty-for-the-frontend.md) with an API-driven submission process. This approach [was eventually scrapped](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0021-switch-to-unified-django-web-app.md) in favor of a more traditional Django application.
The UEI validation endpoint should be the only DRF endpoint still in usage.
- When a user enters the fiscal period dates and clicks Continue, [a Javascript handler submits the form](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/static/js/check-ueid.js#L251). The form data is received by a [Django view](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/report_submission/views.py#L71) in the report_submission app, which forwards the form data to the auditee_info_check [function](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/views.py#L57) in the api app. This function uses the [AuditeeInfoSerializer](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/serializers.py#L163) to deserialize and validate the form data. If valid, the data is saved to the user’s [UserProfile](https://github.com/GSA-TTS/FAC/blob/dda11bdfd31a000601e427379a3fac6ee9e7f1f8/backend/users/models.py#L33). The user is then redirected to step 3.

#### access - names and emails for submission editors and certifiers
- [Frontend template](https://github.com/GSA-TTS/FAC/blob/main/backend/report_submission/templates/report_submission/step-3.html)
- When a user clicks Save and create audit, a Javascript handler submits the form. The form data is received by a Django view in the report_submission app, which forwards the form data to the access_and_submission_check [function](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/views.py#L87C5-L87C15) in the api app. This function uses the [AccessAndSubmissionSerializer](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/serializers.py#L198) to deserialize and validate the form data. If valid, the SingleAuditChecklist object is created and persisted to the database, along with the necessary Access objects, and the [UserProfile](https://github.com/GSA-TTS/FAC/blob/dda11bdfd31a000601e427379a3fac6ee9e7f1f8/backend/users/models.py#L33) data is cleared.

**Comment by timoballard** [comment]
Going forward...

The `api` app is used in a couple of ways:
- there is a [DRF view](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/views.py#L215) that performs UEI validations against SAM.gov. This view is called from step 2 of the pre-SAC form.
- there are [DRF serializers](https://github.com/GSA-TTS/FAC/blob/main/backend/api/serializers.py) that are the mechanism for validating the form data from each of the 3 pre-SAC steps.
- there are functions ([1](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/views.py#L43), [2](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/views.py#L57), [3](https://github.com/GSA-TTS/FAC/blob/506e25806bf40f564745f9396c6015a821fdd168/backend/api/views.py#L87)) that perform the business logic of validating the pre-SAC form data (using the above-mentioned serializers) and persisting the submitted data to the database. These functions are called from the corresponding views in the `report_submission` app. 
  - Things were setup this was because when we switched from an API-driven submission process to a traditional Django application, we briefly attempted to continue support for API submissions, and so the business logic behind the pre-SAC form was implemented behind pure python functions in the `api` app so that they could, in theory, be called from both API and Django views.
  - That said, the DRF API has not been maintained and should be removed. If we wish to enable an API-driven submission workflow in the future, we would be better served starting from scratch, as the DRF API has drifted dramatically from the current state of the application.

Removing the `api` app will have to be done gradually and with care, as it still houses much of the pre-SAC business logic.

**Comment by danswick** [comment]
We're going to punt on combining the audit and report_submission applications for now.
