### ISSUE TITLE
Write project README

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#4]
**Background**

**We'll know we're done when...**
- [X] We have a project README that orients people to the project
- [X] The README is in a findable place

**Tasks**
- [X] Draft initial content
- [X] @jadudm reviews
- [X] @Jkrzy reviews
- [x] @MelissaBraxton reviews
