### ISSUE TITLE
Update API versions, tables

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#4039]
The API is out-of-date. Multiple actions are required.

* The default version of the API is still `v1.0.3`. This version suppresses all `is_public=False` data. We should move to `v1.1.0`.
* A new version (`v1.1.1`) should be introduced that includes the `MATERIALIZED VIEW` as an API endpoint.
* The administrative API should have the remaining internal tables added for data analysis, problem solving.

```[tasklist]
### Tasks
- [ ] Discuss timeline to `v1.1.0` default switch with community
- [ ] Post timeline to updates page.
- [x] Add `MV` to public API
```

**Comment by jperson1** [comment]
The above changes have done something strange to the staging environment - see the most recent deploys [here](https://github.com/GSA-TTS/FAC/actions/workflows/deploy-staging.yml). The deploy times out on an unknown error. The development and preview environments seem fine. We're looking at different approaches to applying v1.1.1 to resolve this.

**Comment by danswick** [comment]
I think this can pretty safely be replaced by [#4285](https://github.com/GSA-TTS/FAC/issues/4285).
