### ISSUE TITLE
Documenting CX metrics within zendesk in the helpdesk SOP

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4049]
This ticket is a continuation of work conducted in https://github.com/GSA-TTS/fac-team/issues/2

**As a team member of the fac working on CX process and reporting, I want to know what resources are available within out helpdesk software, so that I can use them to inform stakeholders and make product decisions.** 

We launched our helpdesk pretty quickly, and are still learning all of the valuable metrics we have access to. We want to document this for ourselves and future teammates in the helpdesk SOP. Examples of this would include identifying valuable metrics and providing instruction for how to access and share them; Things like our one-touch rate, response time, customer satisfaction, etc.. we can provide a step by step guide to pulling these metrics with screen grabs to illustrate workflow. 

### Tasks

```[tasklist]
- [ ] Work with team to determine 5-7 valuable metrics for product decisions and stakeholder education
- [ ] Document within the SOP a step by step guide for pulling each metric, including file formatting
- [ ] Share work with teammate for review 

```
