### ISSUE TITLE
Document CX resources in helpdesk SOP

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4050]
Continuation of https://github.com/GSA-TTS/fac-team/issues/2

**As a teammate at the FAC, I want to know how to access different resources within our helpdesk software, so that I can use them to maintain and improve the helpdesk and our reporting metrics.** 

We recently conducted an audit of the available resources within our helpdesk software. See list [here. ](https://github.com/GSA-TTS/fac-team/issues/2) We want to document each of these resources, how to access them, and any associated workflows and timelines. For example, our helpdesk macro dashboard can be accessed [here](https://fac-gov.zendesk.com/admin/workspaces/agent-workspace/macros?access=shared&active=true&page=1&per_page=100&sort_by=alphabetical&sort_order=asc&tab=macros), and content reviews the macros with at least one additional teammate once a month for accuracy and to make sure content is current. 

### Tasks

```[tasklist]
- [ ] Create new section in the [helpdesk SOP](https://docs.google.com/document/d/1mxDe9AhklmL1DdPdm_4wuY5WC_BdXfBUBD1h4cVVLUg/edit#heading=h.1haaswr9c8i) for User Rsources
- [ ] Document each resource identified in audit. Include all valuable information: What it is, how we use it, when we maintain it, etc
- [ ] Have teammate review work
```
