### ISSUE TITLE
Create 'how to" for reading the basic search results table 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4058]
As a searcher of records on fac.gov [basic search](https://app.fac.gov/dissemination/search/), I need a guide to understand what each column on the search results table means so that I can select the appropriate submission(s). 

We currently do not have a how-to guide for interpreting our search results table. We want something similar to our current [basic search filters](https://www.fac.gov/search-resources/filters/) guide. 

### Tasks

```[tasklist]
- [x] Audit columns
- [x] Write guide with explanation for each column
- [x] Build page
- [x] Add card to[ Search Resource](https://www.fac.gov/search-resources/) hub page
- [ ] (Optional) review guide with 2-4 users for feedback before pushing to site
- [ ] Have teammate review work
```

**Comment by lauraherring** [comment]
@James-Paul-Mason and @analynd I've got [a first draft of this page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/search-results-guide/search-resources/results-guide/#PDF) built and I'd love any feedback you both have.

**Comment by James-Paul-Mason** [comment]
@lauraherring Just sent my notes via Google doc/email.

**Comment by analynd** [comment]
@lauraherring Looking good! I created this mural with my notes: https://app.mural.co/t/gsa6/m/gsa6/1722968168645/b4ff364531879fccde89a3e9182c554d11758d5e?sender=u657059c7ef2d757db0e10088

Lmk if you have any questions. Thanks!

**Comment by lauraherring** [comment]
@James-Paul-Mason and @analynd I've made some updates to [the page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/search-results-guide/search-resources/results-guide/) based on your feedback and realizing we were missing some info. @jperson1 adding you as well for a quick look at how I've described the pagination and sorting features.

**Comment by jperson1** [comment]
The pagination and sort portions look good to me! I like @analynd's comment on numbering the features.

**Comment by lauraherring** [comment]
Wow, somehow I completely missed @analynd's suggested mock-up. My bad! I'd like to talk through the potential ADA implications of numbering the columns in an image though.

**Comment by lauraherring** [comment]
Thanks to help from @Leighdiddy and based on @analynd's feedback, I updated the page with a shorter screenshot that should be ADA friendly.

![Image](https://github.com/user-attachments/assets/6576a62f-80c8-416e-8d72-e2ca3f4dc57a)

**Comment by analynd** [comment]
@lauraherring Noiceee! Looks great to me! 🥳 🙌

**Comment by James-Paul-Mason** [comment]
@lauraherring LGTM as well!

**Comment by lauraherring** [comment]
Thank you all! I just created [PR #141](https://github.com/GSA-TTS/FAC-transition-site/pull/141) for this update.
