### ISSUE TITLE
Public office hours planning

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#4059]
# What problem are we trying to solve?

We said we'd trial some public office hours.

```[tasklist]
### Tasks
- [ ] Frequency (monthly?)
- [ ] When?
- [ ] How will we communicate it? (e.g. grantsfed list, AICPA, etc.)
- [ ] Who will take part?
- [ ] What do we say at the front (mini-presentation on updates, ground rules)
- [ ] Do we need any additional support for the call?
```

**Comment by danswick** [comment]
Combining with https://github.com/GSA-TTS/FAC/issues/4208
