### ISSUE TITLE
Login flow: keep original destination for logged-out user

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#407]
### Background
Users may wish to be redirected upon login based on where they were trying to go before being required to log in.

Enhancement of #388.

If the destination is not the root path, this should override redirection based on how many submissions a user has; otherwise, it should fall back to that flow, if it has been implemented.

The proposed flow is:

1.  User attempts to visit location `x` but isn't logged in.
1.  Since they're not logged in, they're redirected to login flow.
1.  This redirection includes their original destination as a parameter.
1.  Backend login flow retains that original destination and passes it to frontend when user finishes login flow.
1.  Frontend redirects user to that original destination.

### Acceptance Criteria (We'll know we're done when...)

- [ ] When a logged-out user attempts to go to destination `x` and passes through the login flow, they end up at destination `x`.

### Tasks

- [ ]   Alter frontend login flow to include the original destination.
- [ ]   Alter backend login flow to accept the original destination as a parameter and, after login, to pass it to the frontend.
- [ ]   Alter frontend login flow to accommodate URL redirection.

**Comment by jadudm** [comment]
I'm going to close this as not planned. Given the changes since the ticket was written, we can come back post-MVP and evaluate user experience through testing.
