### ISSUE TITLE
Research spike for data monitoring

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#4073]
1. Research various tools to monitor / analyze FAC data and create visualizations.  Create an example visualization if tool can be installed.
2. Pull out data requirements from GAO doc.
3. Identify data quality metrics.
4. How many audits have prior year finding reference numbers that do not exist in the prior year ?

### Tasks

```[tasklist]
- [ ] https://github.com/GSA-TTS/FAC/issues/4074
- [ ] https://github.com/GSA-TTS/FAC/issues/4091
- [ ] https://github.com/GSA-TTS/FAC/issues/4097
- [ ] https://github.com/GSA-TTS/FAC/issues/4075
- [ ] https://github.com/GSA-TTS/FAC/issues/4089
- [ ] https://github.com/GSA-TTS/FAC/issues/4090
- [ ] https://github.com/GSA-TTS/FAC/issues/4108
- [ ] https://github.com/GSA-TTS/FAC/issues/4098
- [ ] https://github.com/GSA-TTS/FAC/issues/4135
- [ ] https://github.com/GSA-TTS/FAC/issues/4148
```

**Comment by gsa-suk** [comment]
https://docs.google.com/spreadsheets/d/1S-sKVouBy0sCaFNVUTI8td99A_7BhB_dEtc8gYd4esI/edit?gid=0#gid=0

**Comment by gsa-suk** [comment]
Closing issue based on discussion with @danswick
