### ISSUE TITLE
Login flow: user should end up somewhere depending on their number of submissions.

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#408]
### Background
Users may wish to be redirected upon login based on the number of submissions they have.

Enhancement for #388.

The proposed flow is:

1.  User logs in.
1.  Backend looks up how many audits the user is associated with.
1.  Backend determines, based on that number, where the user should go:
    *   0 submissions: step 1 of pre-SAC flow.
    *   1 submission: audit start page for that submission.
    *   2+ submissions: “My submissions” page.
1.  Backend returns that information; frontend redirects user to that location.

### Acceptance Criteria (We'll know we're done when...)

- [ ] When a user logs in and has no submissions, they are redirected to step 1 of the pre-SAC flow
- [ ] When a user logs in and has exactly 1 submission, they are redirected to the audit start page
- [ ] When a user logs in and has two or more submissions, they are redirected to the "My submissions" page

### Tasks

- [ ]   Write backend function for checking user/audit associations.
- [ ]   Write backend function for determining URL based on above rules for how many submissions are associated with the user.
- [ ]   Alter backend login flow to include the URL redirection.
- [ ]   Alter frontend login flow to accommodate URL redirection.

**Comment by jadudm** [comment]
We always go to the same place on login. I do not think we'll pick this up again. Or, if we do, we'll revisit/ticket in light of the architecture we have now, vs. the vision we had in September 2022. Closing as not planned.
