### ISSUE TITLE
Fix policies content and rate content in historical migrationinspectionrecord

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#4114]
While implementing code for tickets related to note content, a bug was uncovered related to recording of Census policies_content and rate_content in the dissemination_migrationinspectionrecord table.  
https://github.com/GSA-TTS/FAC/commit/a05559c2f04a66e6abd1a21b86f1c58d3463c5d3#:~:text=policies_content%20%3D%20settings.GSA_MIGRATION

This bug was fixed before the final migrations.  https://github.com/GSA-TTS/FAC/commit/916ff2f53e584492e29a8dbb2ce15fa733fd3098#diff-be5b92da3f2b339f0776164c5269819c1dfc9a11c53e2fea791d45246a4cd612:~:text=def%20xform_rate_content(rate_content)%3A

However, to not have any data inaccuracies in inspection records, the Census policies_content and rate_content for the initial migration records in dissemination_migrationinspectionrecord table in Prod need to be checked and updated with the corresponding Census data as appropriate.

### Tasks

```[tasklist]
- [x] Create management command
- [x] Test command in local
- [x] Test command in Preview
- [x] Update table in Dev
- [x] Update table in Staging
- [x] Update table in Preview
- [x] Update table in Prod
- [ ] Remove command
```

**Comment by gsa-suk** [comment]
https://github.com/GSA-TTS/FAC/issues/4702
