### ISSUE TITLE
As a user, I need to know where to go for help when setting up my audit

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#413]
This issue covers the design of help and support during the Audit Start process.

### Background

When starting a new audit, users need to know what to do if they run into trouble or can't fill something out. We should provide a clear way for them to find support.

(Chat bots are out of scope for this round.)

### Acceptance criteria (We'll know we're done when...)

- [ ] Users know where to get support when starting their audit submissions.
  
### Tasks

- [ ] Research the best way to integrate support into the Audit Start flow (documentation links? modals?)
- [ ] Design the support elements.
- [ ] Adapt or write support copy as necessary.
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by pkigongo** [comment]
To be discussed w/Shelley + other Census team members who are due to arrive at OROS.

**Comment by jadudm** [comment]
#1289 replaces this/advances this.
