### ISSUE TITLE
Configure Github to post action runs to slack

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#4133]
# At a glance
At the FAC, there are occasions where it would be beneficial to have a bot output workflow status logs to dedicated channels. This would allow the team easier access to view newly open PRs that require review, as well as when a deployment fails or completes. Having this functionality would greatly increase our visibility into the CI/CD.

**In order to**  Have more insight into the CI/CD 
**as a** Member of the FAC Team
**I want** To be able to check slack for active github operations.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

### Scenario: 

**Given**  A PR is in in need of review
**when**  A PR is opened
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] A notification should be sent to slack when it is created
- [ ] A notification should be sent to slack when it is approved
- [ ] A notification should be sent to slack when it is merged
```

**Given**  we are running a workflow
**when**  A workflow is being run
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] A notification should alert that the workflow has started
- [ ] A notification should alert if a workflow has failed
- [ ] A notification should alert if a workflow has completed successfully
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: @asteel-gsa  

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

# Sketch

We're thinking we'll try implementing A and then changing B.

```[tasklist]
# Tasks
- [ ] [something we'll definitely have to do]
```

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] A slack webhook is created
- [ ] A slack webhook has been added to github secrets

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by asteel-gsa** [comment]
Currently we have slack configured to receive github notifications. Currently testing and fine tuning usage.

**Comment by asteel-gsa** [comment]
Heavy tunes were done to the bot, and will be monitoring how it operates for a few hours

**Comment by asteel-gsa** [comment]
Testing comments to specific channel, rather than threads for visibility

**Comment by asteel-gsa** [comment]
This has been implemented successfully. Any further modifications will be done outside of a ticket. Core slack notifications are working as expected.
