### ISSUE TITLE
Identify potential data quality metrics

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#4135]
List potential data quality metrics for FAC data.

```[tasklist]
### Tasks
- [x] Draft proposal for 5 data quality metrics: list the measure and how often it should be checked. Describe what it tells us about our data and the health of the FAC as a system.
- [ ] Circulate for review and feedback.
- [ ] Revise if needed.
```

Once we've settled on these five indicators, we can put an MVP togehter.

**Comment by gsa-suk** [comment]
https://docs.google.com/document/d/1q4mFP4BfLi_ulg5dUu_3gYT723c-SrpAC_K2r3-P0jk/edit

**Comment by gsa-suk** [comment]
Draft proposal - https://docs.google.com/document/d/1BAzN8CoZ2HcY5p8Sqjb2ZfY4jWlbvunN9GQCPP2LEoU/edit

**Comment by gsa-suk** [comment]
Closing issue based on discussions with @danswick
