### ISSUE TITLE
Surface "Tribal Audits" in top navigation for static site + app

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4194]
_As a federal user of fac.gov who needs access to suppressed tribal audits, I want to easily locate instructions on fac.gov for how to access suppressed tribal audits, so that I can follow the instructions and gain access to perform my jobs duties._ 

Currently, all information regarding access to [tribal audits](https://www.fac.gov/search-resources/tribal/) is located under **Audit search> Search resources> Tribal audits** We want to move information about Tribal audits one level up to be visible within the **Audit Search** top navigation drop down.  

### Tasks

```[tasklist]
- [x] Create new "Tribal Audits" category to be listed under **Audit search** in top navigation drop down
- [x] Redirect [existing Tribal audits page](https://www.fac.gov/search-resources/tribal/) to open from new "Tribal Audits" category under **Audit search** in top navigation
- [x] Remove **Tribal audits** card/UI from [Audit search resources](https://www.fac.gov/search-resources/) page
```

**Comment by Leighdiddy** [comment]
@jperson1 I imagine you might tackle this one, let me know if you have any questions! Basically we just want to scoot this up higher in the nav so folks can find it faster :)
