### ISSUE TITLE
Revise "Searching Tribal audit submissions" page content + images 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4195]
_As a Federal user of fac.gov who needs access to suppressed Tribal audits, I want to find all current instructions and resources re: Tribal on fac.gov, so that I can understand how to gain access to suppressed Tribal audits._ 

Currently our Tribal audit resource page shares how to access tribal audits after signing in by walking you through a step by step visual guide using outdated site images. We want to revise these instructions and images to reflect the current site workflows and UI. 

Additionally, based on user feedback we believe that further context on who can access tribal audits and how they should go about gaining that access would be helpful on this page. We also want to clarify that these instructions are only for accessing suppressed tribal audits through web results, and include a link to the [Tribal API](https://www.fac.gov/api/tribal/) page for questions re: Tribal via the API.

### Tasks

```[tasklist]
- [x] Review and test the [current instructions](https://www.fac.gov/search-resources/tribal/) for searching Tribal audits for accuracy, note what copy or images need to be updated to match the current site UI.
- [x] Tag @Leighdiddy in ticket comments to provide updated images files as needed
- [x] Revise step-by-step instructions copy if deemed necessary
- [x] Review copy at top of page that outlines access to suppressed Tribal audits. Determine where we could include additional clarification, for example: What is the user supposed to do or say when contacting the helpdesk? What is the difference between a public and suppressed Tribal audit in our search results? How can a user tell if they have the correct access set up?
- [x] Include a link and reference to the [Tribal API](https://www.fac.gov/api/tribal/) page in updated top of page copy with brief explanation of the difference between accessing suppressed audits via web vs. API.
- [ ] Link to updated images and copy in ticket comments.
- [x] @Analynd review page structure in GitHub and determine if template is needed.
```

**Comment by James-Paul-Mason** [comment]
@Leighdiddy, we will need updated image files for the following: 

 

![Image](https://github.com/user-attachments/assets/2caa95ed-faef-4ea4-80e8-255a0e8e1e5f)



![Image](https://github.com/user-attachments/assets/ae7c431a-a347-435f-ad75-5df6cc6f8d30)

**Comment by James-Paul-Mason** [comment]
@Leighdiddy When convenient, could you please perform a content review? https://docs.google.com/document/d/11kc9e1Dv6FTEEHd9_TqFuqrkVZfRy58LP72ZgFSLn_s/edit

**Comment by Leighdiddy** [comment]
@James-Paul-Mason content reviewed, I left you some notes!

**Comment by Leighdiddy** [comment]
I'll have the images over by end of this week.

**Comment by James-Paul-Mason** [comment]
@Leighdiddy Just catching up after my PTO. Wanted to check on the status of the required images.

**Comment by Leighdiddy** [comment]
@James-Paul-Mason I"m having @analynd pull these for you. She needs to update some frames in Figma first but should have them over soon! @analynd [here](url) are instructions for pulling the images (ignore the second half about uploading to github) and [here](https://drive.google.com/drive/folders/1EHYqkIwG8jSP0OYyjR8NmhgzMSYuX3Vh) is where you can save the updated files.

**Comment by analynd** [comment]
@Leighdiddy @James-Paul-Mason [Here are the updated screenshots for the page](https://drive.google.com/drive/folders/12MRI883nMs2IObQnUANRbPvBHe4-qJ8B?usp=drive_link)! Lmk if I saved correctly or if I could just override the current file. Also, idk if it's needed but I included 1a, the shot of the login modal. 

@Leighdiddy Side note: The link to the instructions for pulling the images isn't working for me--I got the error "This view no longer exists Select another view to use this project." I also didn't use the Figma screens for this bc updating the UI components to match the site is gonna take a bit more work. But since the outcome for my task here is just web images, I just took screenshots of prod at 1200px wide and added green arrows to them in Figma.

Also, if I could add a UX suggestion for the website:
As a FAC.gov user, I want to be able to click on the image of a screenshot so that I can read the circled text more clearly when seeking help.

Lmk if you have any questions or concerns, thanks!
