### ISSUE TITLE
How important to users are their roles on audits?

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#421]
### Background

The current version of the “My audit submissions” table has these columns:

|               |             |                  |                   |                           |
| ------------- | ----------- | ---------------- | ----------------- | ------------------------- |
| **Report Id** |  **Status** |  **Auditee UEI** |  **Auditee name** |  **Fiscal year end date** |

This does not include a column for the user's role (creator, certifying auditor, etc.). We need to know whether or not role is important to users—for example, are there users who have different roles on different audits, and is it useful for them to distinguish between the audits on which they have different roles?

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We've done user research to cover this topic.
- [ ]   We've synthesized the research findings and made a decision about whether or not the table needs a column for role.

### Tasks

- [ ]   Plan how to ask users this question.
- [ ]   Conduct research.
- [ ]   Make decision and, if necessary, create follow-up story.

**Comment by petermarks-gsa** [comment]
Next steps are covered by https://github.com/GSA-TTS/FAC/issues/340. Closing.
