### ISSUE TITLE
Remove duplicate rows in dissemination tables

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#4214]
In the public prod dissemination backup from 03/26/24, duplicate rows are present in dissemination_federalaward and dissemination_passthrough.  Verify Prod tables and remove duplicate rows as appropriate.

### Tasks

```[tasklist]
- [ ] https://github.com/GSA-TTS/FAC/issues/4215
- [ ] https://github.com/GSA-TTS/FAC/issues/4216
- [x] Test removal of duplicates in dissemination_federalaward in Staging with Prod data
- [x] Remove duplicates in dissemination_federalaward in Prod
```

**Comment by gsa-suk** [comment]
The duplicate awards are in the GSAFAC.  These are associated with race condition / user hitting Submit button multiple times.

**Comment by gsa-suk** [comment]
https://github.com/GSA-TTS/FAC/issues/4630

**Comment by gsa-suk** [comment]
All entities listed for direct or indirect awards are present in the dissemination_passthrough table.  Some entities are listed multiple times and hence recorded multiple times in the table.
