### ISSUE TITLE
Validate awards in passthrough table with respect to federal award table.

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#4227]
For every audit, dissemination_passthrough table holds details of awards that are marked as passthrough awards in the dissemination_federalaward table.

However, in the public prod dissemination backup from 03/26/24, there are many awards in the dissemination_passthrough table that are not indicated as passthrough awards in the corresponding dissemination_federalaward table.

Reference - https://docs.google.com/document/d/1KEqXVVliaCkxFC9kKseGlQ9xpEcMxepK91GGxdeQaQk/edit

### Tasks

```[tasklist]
- [ ] Verify data in Prod.
- [ ] Implement validation to only accept an award in passthrough table if the award is identified as passthrough in federal award table. 
- [ ] Curate existing Prod data to remove unidentified passthrough awards.
```

**Comment by gsa-suk** [comment]
Closing this ticket.  Resolution in https://github.com/GSA-TTS/FAC/issues/4214
