### ISSUE TITLE
Post contact lists for NSACs, KSMALs to static site

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#4231]
# Nov 2024 Update 

- As an auditor/grantee, I need to see a contact list of:
  * cognizant and oversight agency contacts, so that I know who to contact for technical audit advice and liaison assistance to auditees and auditors, extensions, and questions about indirect costs.
  * National Single Audit Coordinators (NSACs) for technical audit questions.
  * Key Management Single Audit Liaisons (KSMALs) for questions about administrative requirements applicable to agency programs.
  * Program contacts for program-specific questions.

## Links
- [Figma Design](https://www.figma.com/design/obmvJhUT5rwHfTWkCeYx0o/%234231-Post-contact-lists-for-NSACs%2C-KSMALs-to-static-site?node-id=12-550&t=5ukFK166Ch5diEYt-4)

 

```[tasklist]
### Tasks
- [x] Create new Contact page with a [list of NSACs and KSAMLs](https://drive.google.com/file/d/1zkn8R4whj3EzWDrsdWd_EP2UbOMHnSSE/view?usp=drive_link) and a [list of cognizant agency contacts](https://docs.google.com/spreadsheets/d/1Q-uOu5bgbx_-iP-jc9bhzsgCptBF6Lry/edit?usp=drive_link&ouid=116911111828729053885&rtpof=true&sd=true)
- [x] Review designs with Leigh, Dan, James M for copy, and James P for dev
- [ ] https://github.com/GSA-TTS/FAC/issues/4442
- [x] Remove [Federal agency program contacts](https://www.fac.gov/audit-resources/program-contacts/) page from website
```

## Archive
<details>
<summary>Aug 28, 2024</summary>

## At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** get answers to questions about my audit
**as a** submitter or member of the FAC 
**I want** an easy reference to NSACs, KSMALs, and program contacts.

## Acceptance criteria

In keeping with M-22-23 ([Delivering a Digital-First Digital Experience](https://www.whitehouse.gov/wp-content/uploads/2023/09/M-23-22-Delivering-a-Digital-First-Public-Experience.pdf), PDF), we want to provide critical information to our users in an accessible, HTML form wherever possible. More specifically...

[comment]: # "Each task should be a verifiable outcome"

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: @Leighdiddy 

## Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

A branch that makes a start on this exists in our static site repository.

https://github.com/GSA-TTS/FAC-transition-site/tree/jadudm/contacts-helpdesk/src

In the `omb` directory...

* `nsacs.md` provides the NSAC list
* `ksamls` (WHICH IS NAMED INCORRECTLY---OOPS) provides the KSMALs list
* `program-contacts` provides the program contact information.

All of these are data files in the repository.

https://github.com/GSA-TTS/FAC-transition-site/tree/jadudm/contacts-helpdesk/src/_data/omb

* [nsacs.yaml](https://github.com/GSA-TTS/FAC-transition-site/blob/jadudm/contacts-helpdesk/src/_data/omb/nsacs.yaml) -- YAML was used because the information was variable enough, as provided by OMB in the supplement,  that variable fields (and variable rendering) were required to capture all of the information. It might be able to be normalized into CSV. :shrug: I chose to represent the information faithfully as-is.
* [ksamls.csv](https://github.com/GSA-TTS/FAC-transition-site/blob/jadudm/contacts-helpdesk/src/_data/omb/ksamls.csv) was clean enough to represent as a CSV.
* [program-contacts.yaml](https://github.com/GSA-TTS/FAC-transition-site/blob/jadudm/contacts-helpdesk/src/_data/omb/program-contacts.yaml) is a complex mess. That data is not well organized. I created a repeatable YAML structure to encode the data, and used `&` references where appropriate to avoid repeating data entry. 
* We have no starting point (yet) for the extensions list; it must be provided by OMB.

Styling/design work is needed for the rendered pages, but much of the data we need is present. 100% of the NSAC and KSMAL data is present; it would represent a good "first step." The programmatic data is needed, but requires more data entry work (the hard way---manually).

## Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

No known security concerns; this is static content for the static website.

</details>

**Comment by Leighdiddy** [comment]
@analynd as we discussed today: Let's define what we are sharing in the short term (PDF pg. 2048-2074 from the[ UG](https://www.fac.gov/uniform-guidance/)), where it lives (helpdesk, by request for feds only), and how + where are we sharing instructions for users. Next steps: Draft instructions for how to request the contact PDF, include explanation that it's for feds only. Determine where we share this on the site, mock it up in figma!

**Comment by Leighdiddy** [comment]
Work is currently blocked pending clarification from OMB, call scheduled this friday. 

**There are now two contact lists**, a new cog contact list from OMB (@danswick has it) and the existing NSAC/KSAML from UG (see attached). They can both be distributed following the same method. Waiting on: Explanation of when to contact your cog vs. nsac/ksaml, explicit permission to share contact lists publicly 
[Agency_contacts.pdf](https://github.com/user-attachments/files/17120796/Agency_contacts.pdf)

**Comment by analynd** [comment]
Synced with Leigh to update task list: 

Notes from convo (reframing user stories so I can better understand context):
- Create new Contact page under "Policy & Compliance" tab with the two lists
- As a user, I need to see a contact list of cognizant agency contacts, so that I know who to contact in regards to my question about extensions.
- As a user, I need to see a contact list of NSACs & KSAMLs, so that I know who to go to for questions about my audit.
  ("NSACs can answer technical audit questions, KSMALs, can answer questions related to the administrative requirements applicable to an agency program(s), and program contacts can answer program specific questions.")

**Comment by analynd** [comment]
### [Design of new Contact page is ready for review! ](https://www.figma.com/design/obmvJhUT5rwHfTWkCeYx0o/%234231-Post-contact-lists-for-NSACs%2C-KSMALs-to-static-site?node-id=12-550&t=5ukFK166Ch5diEYt-4)

Routing to several people for review, please mark complete here and unassign this ticket to yourself when done: 

- [ ] - @Leighdiddy @danswick I know the ask was to just post the 2 contact lists, but what do yall think about creating a new Contact page to replace the “Helpdesk” link in the Nav? More info in Figma design, but gist is consolidating ALL of the contact resources for our users in one place on the site instead of digging around and guessing where to go for various info.
- [ ] - @James-Paul-Mason Can you please help me by finessing the copy in the designs? Thank you! 
- [ ] - @jperson1 Can you please review the overall design from a dev POV? I had a comment in there about tables, too. Thanks!

**Comment by James-Paul-Mason** [comment]
@analynd I should be able to get this done tomorrow! Quick question: would you like comments directly in the Figma file? I assume yes, but just wanted to double check.

**Comment by analynd** [comment]
> @analynd I should be able to get this done tomorrow! Quick question: would you like comments directly in the Figma file? I assume yes, but just wanted to double check.

@James-Paul-Mason Yes, commenting in Figma and tagging my email would be perfect. Thank you so much!

**Comment by danswick** [comment]
Done!
