### ISSUE TITLE
Update Figma Source of Truth 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4270]
As a designer at the FAC, I want to be able to reference [a design document](https://www.figma.com/design/lnkXJTfKzD3YBhiJZ2QFEv/FAC-Source-of-Truth?node-id=0-1&node-type=canvas&t=Crzi7Ai8oAEWBWsS-0) outside of the live website that represents all current frames, so that I am able to confirm we are showing the correct UI and content on our live site and reference our existing frames when designing new ones.

### Tasks

```[tasklist]
- [x] Update existing local header component to reflect most current version as shown on "Resource hubs" frames
- [ ] Review all existing frames to confirm they use the updated header component
- [ ] Review all existing frames against current content audit to confirm we have documented all frames shown on the live site
- [ ] Create figma mocks for any missing frames
- [ ] Tag a teammate to review for accuracy and completion
```

**Comment by analynd** [comment]
We have access to USWDS's new alpha Figma UI kit that uses variables and other new Figma features. Use this when updating source of truth doc. Caveat: provide feedback to Anne Peterson and USWDS team.

**Comment by analynd** [comment]
Discussed with @jperson1 after 11/21/24 Monthly USWDS meeting:

Since it was clarified that the updated USDWS won't be fully released until "a year" from now, I should:
- deprioritize retrofitting/designing with alpha/beta UI kit right now 
- instead focus efforts on rebuilding source of truth with current state UI kit

**Comment by Leighdiddy** [comment]
Note: Low priority

**Comment by jadudm** [comment]
Per Dec 11 note, closing as not planned. We can bring this ticket back out of archive if we decide we have the capacity/it is roadmapped as a priority.
