### ISSUE TITLE
SF-SAC loading

### ISSUE THREAD

**Issue by rocheller123** [GSA-TTS/FAC#4281]
```[tasklist]
### Tasks
- [x] Draft approaches for loading SF-SAC data.
- [x] Test approaches and document them.
- [x] Test procedure with Prod data in Staging environment.
- [x] Copy 275K+316 sac table to Prod S3
- [x] Load 275K+316 sac to Prod
- [x] Prepare 275K+316 reportfile and access for Prod
- [x] Copy 275K+316 reportfile and access to Prod S3
- [x] Load 275K+316 reportfile and access to Prod
- [x] Test in Prod
```

**Comment by gsa-suk** [comment]
https://docs.google.com/document/d/1CsCICVy0FZO4YxvO7RobQUcEltEBOkO0RkieN--GFcs/edit
