### ISSUE TITLE
Create initial design section of wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#43]
**Background**
To onboard new design team mates, we want a handy design reference section of the wiki to help folks get up to speed and begin contributing quickly. also

**We'll know we're done when...**
- [x] A designer external to the project confirms that the wiki provides enough info for them to feel confident getting started. 
- [ ] 

**Tasks**
- [x] Distill phase 3 research into concise user role descriptions [role, goals, needs, pain points]
- [x] Link to available journey maps
- [x] Link to design system
- [x] Link to design prototyping environment
