### ISSUE TITLE
🅢 M1: Cancel button doesn't work yet

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#430]
Breakout issue of #395

In the M1 pre-sac flow steps (1-3), the "cancel" button doesn't do anything yet. 

"Cancel" should display an "are you sure?" confirmation, and if you click yes, should bring you back to the "my audit submissions page" (list of all audits)

### Tasks

- [ ] ~~(Potentially back end) delete entries in JSON packet for steps 1-3.~~
- [ ] Code up the "cancel" button so it cancels the current WIP audit and brings you to your audit dashboard.
- [ ] Add a yes/no confirmation

**Comment by pkigongo** [comment]
Q: I'm working on copy for the audit submission checklist and for the confirmation notification for Confirming Submission, I've got in there that once you submit, you cannot edit or rescind your submission. Here's my question: If a user decides they don't want to submit and want to do one last check, if they select "Cancel" at that point instead, will their recent changes be saved?

**Comment by jadudm** [comment]
@danswick, if you're looking for a place to dive in, this may be a good one to pair with @heymatthenry on.

**Comment by jadudm** [comment]
We have a replacement ticket for this (#919). Archiving this ticket in lieu of the newer, better-specified ticket that was discussed/clarified with the team.

**Comment by jadudm** [comment]
I said I archived this, but didn't. Closing as not planned, but the work was picked up elsewhere.
