### ISSUE TITLE
Cleanup Tribal access table

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#4360]
The tribal access table can have addresses like

Darth.Vader@gsa.gov

and

darth.vader@gsa.gov

Unfortunately, this can cause problems.

We should clean this table up.

1. Anything uppercased should be lowercased.
2. Anything that has duplication, we should look and see if one record has a user id, and the other does not. If so... delete the record without the user id.

There may be other considerations. Our goal is to eliminate the upper/lowercase confusion that earlier versions of the admin API allowed for.

Most of this work can likely be done via the Admin API, but it wants to be investigated/documented/discussed before action is taken.

### Tasks

```[tasklist]
- [x] Get Admin API key.
- [x] Determine scope of problem.
- [x] Formulate likely solution
- [x] Demonstrate locally/in a lower environment
- [x] Backup existing table (via API)
- [x] Cleanup table
```
