### ISSUE TITLE
Swimlane diagram for as-is workflow

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#44]
**Background**

**We'll know we're done when...**
- [x] We have a high level diagram of how information flows through the existing system.
- [x] We've identified knowledge gaps and aspects to validate

**Tasks**
- [x] Sketch out as-is WF
- [x] Link to from wiki
