### ISSUE TITLE
📍 Rebase cog/over

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#4402]
This is a placeholder for tracking work related to rebasing our cognizant / oversight assignments.

### Tasks

```[tasklist]
- [x] Confirm how we should be determining assignment outside of base years: https://github.com/GSA-TTS/FAC/issues/3903
- [x] Create public documentation describing how cog/over assignments are done
- [ ] https://github.com/GSA-TTS/FAC/issues/4439
- [ ] https://github.com/GSA-TTS/FAC/issues/4510
- [ ] https://github.com/GSA-TTS/FAC/issues/4459
- [x] All assignment pathways have unit tests and are testable in a lower env
- [x] Clean up old cog/over assignment logic and tables
```

Tagging in @gsa-jrothacker and @LynnMHouston

**Comment by gsa-suk** [comment]
Questions related to rebasing:
1.  Current base year is 2019.  When does the base year change to 2024?
2. How far can re-submissions go?  Do multiple base years have to be supported by FAC?

**Comment by danswick** [comment]
Capturing some notes from discussion with @gsa-suk and @gsa-jrothacker:
1. Let's explore capturing all the business logic in code rather than in tables. If we can jettison both the assignment tables, let's do it and rely on the submission record itself.
2. If the above looks good, we should be able to write more complete unit tests for COG / OVER assignment.
3. The rest of the assignment logic should still be valid (the flowchart).
4. I think there was one more thing, but it's escaping me.

**Comment by gsa-suk** [comment]
The audit_year, baseline year mapping is as follows:
<google-sheets-html-origin><style type="text/css"></style>
audit_year | base_year
-- | --
2019 | 2019
2020 | 2019
2021 | 2019
2022 | 2019
2023 | 2019
2024 | 2024
2025 | 2024
2026 | 2024
2027 | 2024
2028 | 2024
2029 | 2029
2030 | 2029
2031 | 2029
2032 | 2029
2033 | 2029
2034 | 2034
2035 | 2034
2036 | 2034
2037 | 2034
2038 | 2034
2039 | 2039
2040 | 2039
2041 | 2039
2042 | 2039
2043 | 2039
