### ISSUE TITLE
Update "managing user access" documentation page to support removal of contacts

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#4404]
As a FAC user, I need updated documentation copy and screenshots on the [Managing User Access](https://www.fac.gov/audit-resources/user-access/) documentation page, so that I know how to remove an Audit Editor from an audit and can refer to a guide if I need help.

```[tasklist]
### Tasks
- [x] Screenshot [new "Remove Auditor" feature](https://app.fac.gov/audit/manage-submission/2023-08-GSAFAC-0000062274)
- [x] Gather updated screenshots of "Manage user roles" page on the documentation page with new header for consistency
- [x] Develop documentation copy
- [x] Update [copy and screenshots](https://docs.google.com/document/d/12MrfRqyAlW_vWJ4u49Hu7ymRPKly7u48lBRRfySgpPk/edit?usp=sharing) on [Managing User Access](https://www.fac.gov/audit-resources/user-access/) documentation page
```

🏁 **[Final Copy Doc](https://docs.google.com/document/d/12MrfRqyAlW_vWJ4u49Hu7ymRPKly7u48lBRRfySgpPk/edit?usp=sharing)**

**Comment by analynd** [comment]
Since we're adding a new feature, I thought it'd be best to update all the screenshots on the documentation page for consistency so we are not confusing the user (some screenshots have the header and some have the old user roles table with just the Edit function).

@James-Paul-Mason From a CX and Content POV, could you please **review the [updated screenshots and minor copy edits in Figma](https://www.figma.com/design/mpCUqTMkxeO4ibvTVwVb4N/Static-Site-Screenshots?node-id=6-82&t=FTRGqaTiBqLe4oth-4)**? 

Lmk if you have any questions, thanks!

**Comment by James-Paul-Mason** [comment]
@analynd Looks awesome! I think all of your copy edits were fine. However, I noticed a number of areas on the original copy that needed revision for clarity. Please see my comments and let me know if you want to chat!

**Comment by analynd** [comment]
Thanks @James-Paul-Mason! Just documenting next steps here:

- I'll save out the screenshots and a copy doc for the website upload
- These changes need to be made on the static site--would you like to do the honors of implementing those updates? 😄

**Comment by analynd** [comment]
Link to updated copy and screenshots are located here: https://docs.google.com/document/d/12MrfRqyAlW_vWJ4u49Hu7ymRPKly7u48lBRRfySgpPk/edit?usp=sharing

@James-Paul-Mason How about we set up a time to work on updating the site together? I'm actually a bit familiar with front-end code so I'm definitely down to help! Thanks!

**Comment by James-Paul-Mason** [comment]
@analynd That sounds great!

**Comment by James-Paul-Mason** [comment]
@analynd How about tomorrow (10/29) any time after Stand that is convenient for you?
