### ISSUE TITLE
Excel Generation functionality

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#443]
### Overview
Implement basic Excel template generation to be used first with the federal awards screen. Should be componentized to be used on other screens. 

### Acceptance criteria: 
Test case: blank form
* [ ] Go to screen with upload step (i.e. Federal Awards)
* [ ] Click "download worksheet" button
* [ ] The heading and button copy updates from “download” to “re-download,” and the step counter is changed from a number to a checkmark.
* [ ] An excel template should be downloaded containing EIN identifier for the submission
  * [this worksheet](https://docs.google.com/spreadsheets/d/1GEhEUPlsMFn7yFV4N2KAeCnKNom-crtI/edit#gid=459082746) for federal awards
 
Test case: already uploaded form
* [ ] Go to screen with upload step (i.e. Federal Awards)
* [ ] Click "download worksheet" button
* [ ] An excel template should be downloaded containing all the info previously entered that was recorded

### Tasks
- Design/UX
   - Either ensure the old Excel template can work or design a new template
   - Design how validation should alert users to issues (i.e. color changes, text wording, etc.)
- Front end
   - Generate Excel file using library determined in #442 to do it
   - #478 
   - #479 
   - #482 
   - #483 
- Back end
   - Define database model for federal awards (if not already done in #450) 
   - #478 
   - #480
   - #481

### Not in scope
- https://github.com/GSA-TTS/FAC/issues/449
- https://github.com/GSA-TTS/FAC/issues/450
- Saving the uploaded Excel file (not actually necessary)

**Comment by petermarks-gsa** [comment]
cc @tadhg-ohiggins @geekygirlsarah @jasnakai

**Comment by geekygirlsarah** [comment]
I feel like this is, at minimum, at least 4 stories:
* As a submitter, I should be able to download an Excel template... (front end)
* (same but backend)
* As a submitter, I should be able to upload my filled out template with fields...
* (same but backend)

I think this isn't one step but is in fact several steps and at different points (even if they're close) that one ticket doesn't really describe what needs to be done, but also is going to balloon larger than initially thought because we don't have the front or back ends of this set up for how the flow works. With how things are designed, we can probably break down into stories better. I think once we've started actual development on the flow of the user submitting the full audit, we'll know how large each of those are. But I feel like this is a massive multi-story that's not adequately defined or scoped.

**Comment by petermarks-gsa** [comment]
@geekygirlsarah Agreed needs to be refined and broken up into multiple tasks, if not multiple stories. My intention of taking a rough stab at documenting high-level end to end functionality here is to make sure we've answered the technical unknowns in #328 to be able to refine / break up this work without additional research.

**Comment by petermarks-gsa** [comment]
@geekygirlsarah FYI, I broke out uploading into its own story (#449)
