### ISSUE TITLE
Onboarding SOP + Tracker

### ISSUE THREAD

**Issue by imanaali** [GSA-TTS/FAC#4431]
Create a clear SOP that covers all aspects of the FAC onboarding process to ensure consistency and efficiency, and to facilitate easy updates to materials as processes evolve.
```[tasklist]
### Tasks
- [x] Research existing onboarding processes: Gather any current documentation or notes on our current onboarding approach.
- [x] Identify key steps and stages: Outline the stages of onboarding (first day, first week, first month)
- [ ] Draft onboarding steps and responsibilities: List all tasks to be completed during onboarding, assigning responsible roles for each step.
- [ ] Create maintenance guidelines: Develop a system for reviewing, updating, and archiving onboarding materials periodically (e.g., quarterly reviews, as-needed updates).
- [ ] Gather feedback: Review draft SOP with Leigh
- [ ] Finalize SOP
```

**Comment by imanaali** [comment]
[Draft Onboarding SOP](https://docs.google.com/document/d/1R88uqa42cuTtb-qVGHX6PvyCKFYS1-UBh1XyY2FqV2Y/edit?usp=sharing)

**Comment by imanaali** [comment]
[Draft Onboarding New Member Tracker](https://docs.google.com/spreadsheets/d/1nfJSjsr7AWv9zIDyMQIEYpyLxGgbydCyJTfylQrS5BE/edit?usp=sharing)

**Comment by Leighdiddy** [comment]
Closing due to low priority, will re-scope and define clearer outcome in future. See previous comments for links to past work.
