### ISSUE TITLE
Code Scan Finding #1761

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#4438]
### Tasks

Determine if highlighted sections are necessary, validate if not. 

See [here](https://github.com/GSA-TTS/FAC/pull/4420) for an implementation that resolves a similar issue. 

```[tasklist]
- [x] https://github.com/GSA-TTS/FAC/security/code-scanning/1761
- [x] https://github.com/GSA-TTS/FAC/security/code-scanning/1559
- [x] https://github.com/GSA-TTS/FAC/security/code-scanning/1558
```
