### ISSUE TITLE
SF-FAC audit meta section

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#445]
### Background
Throughout the screens in the SF-SAC flow, there is a shared heading (circled in red) that contains: 
![Screen Shot 2022-08-24 at 1 10 28 PM](https://user-images.githubusercontent.com/100610443/186514000-b0cb068a-d9ee-453d-a5f1-b85cd2cc0794.png)

### Acceptance criteria
Shared UI that includes
- [ ] Title of the entity in the header
- [ ] Report ID
- [ ] Type of Entity with edit link that takes you to ____
- [ ] UEI with Invalid UEI state that that takes you to ____
- [ ] Form Type
- [ ] Version

**Comment by petermarks-gsa** [comment]
@melchoyce Can you please confirm the destination of the edit links described here and also provide a link to the most recent designs showing various states (valid/invalid UEI)

**Comment by petermarks-gsa** [comment]
@heymatthenry @tadhg-ohiggins cc'ing you on this. From what I can tell on our federalist builds, we don't currently have this. I'm seeing a section with a different layout and non-dynamic data (attached). Please let me know if you think this is covered by another issue. 
![Screen Shot 2022-08-24 at 1 16 21 PM](https://user-images.githubusercontent.com/100610443/186515148-0baad55a-e354-4224-8882-cc0035735fd3.png)

**Comment by austinhernandez** [comment]
TBDDDDDDDD. 

- the first mockup is redundant and i feel like it doesnt need to be the header on every page. the H1 text SHOULD be the page name, not the report title.
-  2nd mockup is an old because the secondary navigation on the left should be at the top of the page. weve removed version number as it was confusing to users and wont have the same iteration pattern as it did before. 

we are experimenting with a new layout to contain all report information but have not finalized anything yet. if you are going to build it out please use the screenshot below. please bear in mind that the navigation is something we are testing as well. 

![image](https://user-images.githubusercontent.com/23194720/186962243-0e92ebcf-8173-4b25-a2c6-1946690bff33.png)

**Comment by petermarks-gsa** [comment]
@austinhernandez Thanks for taking a look! In response:

> the first mockup is redundant and i feel like it doesnt need to be the header on every page. the H1 text SHOULD be the page name, not the report title.

Gotcha, so sounds like that design is not final. Is there a related design task to finalize this? 

> 2nd mockup is an old because the secondary navigation on the left should be at the top of the page. weve removed version number as it was confusing to users and wont have the same iteration pattern as it did before.

[The second image I posted](https://github.com/GSA-TTS/FAC/issues/445#issuecomment-1226246783) is actually a screen shot from the current application. This task is about updating it.

**Comment by melchoyce** [comment]
We talked about this during our Design Sync today. I'll be exploring the different states and interactions within the audit meta section.

**Comment by melchoyce** [comment]
When you click "edit" in the meta section:

![image](https://user-images.githubusercontent.com/2846578/198351422-3e07e6dc-724d-42bb-ac20-c7bf400e2b8c.png)

It should open a modal:

![image](https://user-images.githubusercontent.com/2846578/198351454-39640be8-9d72-40be-9096-b057fe49bbbe.png)

[Figma mockups](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A24318) | [Prototype view](https://www.figma.com/proto/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?page-id=4954%3A22829&node-id=4954%3A24318&viewport=2888%2C-1499%2C0.33&scaling=min-zoom&starting-point-node-id=4954%3A24052&show-proto-sidebar=1)
