### ISSUE TITLE
As a user, I want to be able to enter my form data via web (in addition to Excel)

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#447]
Breakout issue of https://github.com/GSA-TTS/FAC/issues/274, https://github.com/GSA-TTS/FAC/issues/313.

This issue covers the design of:
- Federal Awards
- Award Findings
- Findings Text
- CAP Text
- Additional EINs
- Additional UEIs

And eventually:
- Notes to SEFA
- Secondary Auditors

### Background

- The existing Census FAC lets you upload an excel worksheet for each of these pages, and then it syncs the information into a webform that you can edit directly on the FAC website.
- We originally designed this functionality into the GSA FAC design: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=2464%3A10742
- But, due to time constraints, [we opted to remove the web forms from the MVP](https://docs.google.com/document/d/14C5neV7rClnoGX2ds7ZBEOXYB6qwzrW-QrOeBxewGp8/edit?usp=sharing).
- [In our 8/25/22 coworking session](https://docs.google.com/document/d/1ItVZgH6nC3EcAXe15GezHR0w-TP7nA7HfwK7HG-PPUM/edit?usp=sharing), we determined that, given our deadline extension, we should rethink this decision.
- We don't have data around how web forms benefit auditors' workflows, so we need to generate that data by talking to them.
- To that end, our new plan is for design to explore reintegrating web forms into these pages, and then talk to auditors to determine whether or not web form support in the MVP would benefit their workflows. Research study TBD.
- We've had some overall site architecture changes since initially designing these SF-SAC pages, so we'll want to update the mockups to use the latest patterns.

### Acceptance criteria (We'll know we're done when...)

- [ ] Each of the above listed pages has both excel uploading and a web form designed
- [ ] The pages and various form states are present in a clickable prototype. 
  
### Tasks

- [ ] Design web form for Federal Awards
- [ ] Design web form for Award Findings
- [ ] Design web form for Findings Text
- [ ] Design web form for CAP Text
- [ ] Design web form for Additional EINs
- [ ] Design web form for Additional UEIs
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by pkigongo** [comment]
Design to discuss in further detail

**Comment by Leighdiddy** [comment]
Reviewed w/ Mel, there are mockups hiding in Figma from spring '22 but they are built with outdated patterns. Will need to continue pause until we move past excell submission workflow with dev.

**Comment by jadudm** [comment]
This is still in the "it needs research/validation" phase. We moved forward a long time ago with XLSX upload as the primary data entry mechanism. Closing this as "not planned" for now.
