### ISSUE TITLE
Add alt text to images on the static site

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#4488]
Many images don't have alternative text. To meet accessibility standards, we should include written descriptions of images where they appear. Where appropriate, we should include this text on screen, such as in image modals or caption areas. 

### Tasks

```[tasklist]
- [x] Add alt text to collections frontmatter (ex [here](https://github.com/GSA-TTS/FAC-transition-site/blob/1d0945dc06efc5d9fb291439cf8553906ef4c677/src/_collections/access/01-landing.md?plain=1#L4))
- [x] Include alt text on the displayed images (ex [here](https://github.com/GSA-TTS/FAC-transition-site/blob/1d0945dc06efc5d9fb291439cf8553906ef4c677/src/audit-resources/user-access.md?plain=1#L44))
- [x] Include alt text in image modals as descriptor text
```
