### ISSUE TITLE
Determine styles  

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#45]
**Background**
We will be using the USWDS, but we want to explore the extent to which it should align with the reimagined usa.gov styling.

**We'll know we're done when...**
- [ ] We document whether the new FAC should align with future usa.gov styling
- [ ] We have identified a style guide 

**Tasks**
- [ ] Talk with usa.gov product design folks
- [ ] Review style guide(s)
