### ISSUE TITLE
Enhance footer content for fac.gov

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4506]
_As a user of fac.gov, I want to view the navigation menu in the footer as well as the header, so that I can quickly find the pages I'm looking for within the site navigation._ 

We currently only show the GSA footer on fac.gov, and want to add a section showing fac.gov navigation links for users reference. This new footer should show on all pages of the site, both app and static. 

### Tasks

```[tasklist]
- [x] Design fac.gov navigation menu footer in figma
- [x] Have teammate review design before handoff to dev
- [x] Handoff to dev for frontend implementation
```

**Comment by analynd** [comment]
@Leighdiddy Do you want to review the redesigned footer and provide feedback before I handoff to dev? Thanks! 

https://www.figma.com/design/yoK0RCOtVDiaeOBqx8sK92/%234506-Enhance-footer-content-for-fac.gov?node-id=3-5157&t=oT08xZ8V4EH8CDD2-4

**Comment by Leighdiddy** [comment]
@analynd This looks good! A few thoughts: Instead of having a "Contact" button, could we add a "Contacts" column and list links to:
1. [Helpdesk](https://support.fac.gov/hc/en-us/requests/new)
2. [FAQ](https://support.fac.gov/hc/en-us) (I know this is part of the helpdesk, but it's hidden and I want to help users find it
3. [Cognizant Agencies](https://www.fac.gov/contact-resources/cognizant-agency-contacts/) 
4. NSACs and KMSALs (Clicking will automatically download PDF

And second, after removing the "Contact" button from the left side we can tweak the logo/layout. I mocked up what I was thinking for you in Figma, let me know what you think!

**Comment by analynd** [comment]
I really like the updates, I feel like users will find those links really helpful. Thank you! 🥳  I updated the component and finalized the file for dev! 

![image](https://github.com/user-attachments/assets/aa330571-afdc-4245-af23-c5da864ffbc2)


@jperson1 or any dev with bandwidth, this ticket is ready for dev. Let us know if you have any questions, thanks!
https://www.figma.com/design/yoK0RCOtVDiaeOBqx8sK92/%234506-Enhance-footer-content-for-fac.gov?node-id=26-3901&t=LbkSI2JJkMrzdw6S-4

**Comment by rnovak338** [comment]
@analynd on the mobile version, how does it look when clicking into one of the five categories? Is there a similar existing component in the app that I could find and reference?
