### ISSUE TITLE
Revise design of Contact page on fac.gov

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4507]
_As a user of fac.gov, I want to view one page that shares all available methods to contact both the FAC and Federal awarding agencies, so that I know who to contact with questions regarding use of fac.gov or specific to my oversight agency._ 

We created a [contacts page](https://www.fac.gov/contact-resources/), but the current layout uses cards inconsistently with the rest of the site. We want to redesign this page to better describe and differentiate between the available contact options: Our helpdesk, cognizant agencies, and NSACs and KSAMLs. 

### Tasks

```[tasklist]
- [x] Design new contact page in figma
- [x] Have teammate(s) review design for feedback, both design and dev
- [ ] Have dev implement new page design
```

**Comment by analynd** [comment]
@Leighdiddy Can you please review the design of this? I thought about adding sections for our various guides to boost visibility on those, plus the email sign up component from the Updates page. Thanks! 

https://www.figma.com/design/5sbwOykviCVAHnKirkaVzd/%234507-Revised-Contact-page?node-id=34-780&t=3KvG79Y8WSr43Ht8-4

![Image](https://github.com/user-attachments/assets/5da489bc-8086-4cc5-bd6f-fabfd291fde1)

**Comment by Leighdiddy** [comment]
@analynd I left a few small feedback items as comments in the file, looks great!

**Comment by analynd** [comment]
Hi devs, the revised contact page design is ready for dev review/build/handoff in Figma! https://www.figma.com/design/5sbwOykviCVAHnKirkaVzd/%234507-Revised-Contact-page?node-id=68-1589&t=OqmeH2xeI3W9tLAb-4 

Please let me know if folks have any questions, thank you! 

![Image](https://github.com/user-attachments/assets/e56a862a-6560-4b2f-b0ec-7d8a994738bc)

**Comment by phildominguez-gsa** [comment]
@analynd Should "helpdesk" be capitalized here?

<img width="537" alt="Image" src="https://github.com/user-attachments/assets/6050045e-74e3-403d-86e5-a0b57a3fc9e6" />

**Comment by analynd** [comment]
> [@analynd](https://github.com/analynd) Should "helpdesk" be capitalized here?
> 
> <img alt="Image" width="537" src="https://private-user-images.githubusercontent.com/142051477/408668087-6050045e-74e3-403d-86e5-a0b57a3fc9e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgzNDY4MTAsIm5iZiI6MTczODM0NjUxMCwicGF0aCI6Ii8xNDIwNTE0NzcvNDA4NjY4MDg3LTYwNTAwNDVlLTc0ZTMtNDAzZC04NmU1LWEwYjU3YTNmYzllNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEzMVQxODAxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDhlN2I3NzNmZTkyY2M4MTc5ZTlkYzFhMzIzYTMxZWMyMDlkM2NhNTA1YmE3NzIzMTIxZmY3NjFlYzQ5NjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1b5SUJziEqt1Wxhd-AJJRvcm_GJI-kPaATLPpmAYLCc">

@phildominguez-gsa Good catch, yes I just updated it in Figma. Thank you!

**Comment by analynd** [comment]
You're amazing @phildominguez-gsa!!! Thanks for getting this up so quickly! 😍🙌🎉
