### ISSUE TITLE
Attach a DNS entry on fac.gov before 9/25/2022

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#452]
** DUE BEFORE SEPTEMBER 25, 2022! **

### Background

@jadudm says:
>The [fac.gov](http://fac.gov/) domain will expire on 9/25/22 if we do not attach a DNS to it. I assume this means we need to get a placeholder up on Federalist. Whether that’s the app (FAC-frontend) or the skeleton I threw together ([FAC-transition-site](https://github.com/GSA-TTS/FAC-transition-site)), I don’t know.

(See 🔒 https://gsa-tts.slack.com/archives/C1L58R804/p1661862909026119 )

### Acceptance Criteria (We'll know we're done when...)

- [x] A determination was made for what should be on the fac.gov site until a production-ready site is up 
  - Per Matt J, a simple "coming soon, go to https://facweb.census.gov/" should suffice
- ~~fac.gov resolves to that site~~
- [x] This is done before 9/25
    - We received word the domain is locked in now!

### Tasks

(These may evolve the deeper down the rabbit hole I go...)

- [x] Determine what should go on fac.gov before we have production-ready site to go there
- [X] Make PR against `18f/dns` to add DNS entries for fac.gov (see [18f/dns#602](https://github.com/18F/dns/pull/602)/[18f/dns#603](https://github.com/18F/dns/pull/603))
- [X] DNS records are live

(Tasks associated with placeholder site have been moved to #469)

**Comment by geekygirlsarah** [comment]
This is done. As the PRs for `18f/dns` were reviewed/merged by @JJediny, I'm calling this done.
