### ISSUE TITLE
Upgrade Terraform Modules to use v2.0.0

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#4522]
There has been some tremendous progress in upgrading from `cloudfoundry-community` to `cloudfoundry` provider over on the DevTools [repo](https://github.com/GSA-TTS/terraform-cloudgov/pull/57). We should probably get everything up to date and keep up with that development, as the longer we go without this, the harder it will be to maintain our terraform.

### Tasks
```[tasklist]
- [ ] Read through the changes on the PR and analyze what modules need updates
- [ ] Perform the provider & module updates in sandbox
- [ ] Regression test functionality across the site and check for breakage in sandbox
- [ ] Perform the provider & module updates in preview as the baseline after sandbox
- [ ] Regression test functionality across the site and check for breakage in preview
- [ ] Promote to the higher environments
```

*Note*: Due to the scale of this, I probably will not start working on this until the new year.

**Comment by asteel-gsa** [comment]
This has been completed with the latest [Release](https://github.com/GSA-TTS/FAC/releases/tag/v1.20250314).
