### ISSUE TITLE
Revise layout + copy for Basic and Advanced search screens

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4531]
We are currently showing too much copy in the info alert on our Search and Advanced Search page layouts, which was raised as an issue in our recent EOP review. We need to revise the [Search](https://app.fac.gov/dissemination/search/) and [Advanced Search ](https://app.fac.gov/dissemination/search/advanced/) screens to remove the "Summary reports" and "Search" or "Advanced Search" sections of copy from the blue info alert. The info alert should only contain "Searching the FAC database" copy. 

The "Search" and "Advanced Search" sections of copy should be combined and revised to say: "Basic search is updated in real time and can be used to confirm that an audit submission has been accepted. Advanced Search is updated once daily at 12am EST and includes additional filters to support Federal audit resolution and oversight." 

The headlines on Basic and Advanced search screens should be updated to reflect which type of search you are currently viewing: "Audit submissions - Advanced search" or "Audit submissions - Basic search"  The info alert and additional search copy should be identical on both pages, containing links to their respective pages (basic vs. advanced.) 

<img width="1336" alt="Screenshot 2024-12-11 at 12 29 46 PM" src="https://github.com/user-attachments/assets/e7a36ca6-712e-47e4-b6bc-e568b890e377" />

### Tasks

```[tasklist]
- [x] Revise search screen layout for **Basic** search with updated headline and revised "Basic vs. Advanced" copy shown outside of the info alert.
- [x] Revise search screen layout for **Advanced** search with updated headline and revised "Basic vs. Advanced" copy shown outside of the info alert.
- [ ] Review with design teammate (can share screen grabs in ticket for async review)
- [ ] Implement change on frontend
```

**Comment by Leighdiddy** [comment]
In progress: https://www.figma.com/design/D5LZmSTi50vnAoyVxCZSMM/Revise-layout-%2B-copy-for%234531--%234531-Basic-and-Advanced-search-screens%C2%A0?node-id=1-5520&node-type=frame&t=9iqjecCRgamWyuEM-0

**Comment by anagradova** [comment]
@Leighdiddy Please see the adjusted screens for approval. 

<img width="873" alt="Image" src="https://github.com/user-attachments/assets/6b00e646-357e-4a1c-a2a5-97e28da4eee9" />

<img width="851" alt="Image" src="https://github.com/user-attachments/assets/09397d74-cda1-461c-a47e-8f190b31bb66" />

**Comment by Leighdiddy** [comment]
Hi @anagradova ! This looks good with one change: Please update the basic headline to read "Audit Submissions Basic Search" and the advanced headline to read "Audit Submissions Advanced Search" using that exact wording. Thanks!
