### ISSUE TITLE
FAQs page content audit

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#457]
### Background

The FAQs page on the Census FAC site ([link](https://facweb.census.gov/FAQs.aspx)) contains information that will be outdated once we launch the fac.gov. The old FAQs refer back to FAC Census links/workflow on the Census FAC site.

Every question on the FAQs page will need to be reviewed and potentially updated for users. We will review each question and decide: 

- is this question/answer still useful? 
- should it remain as a FAQ? added as helper text in the form instead? 
- Are there new questions we should add for first-time FAC users?

[Here's a spreadsheet](https://docs.google.com/spreadsheets/d/171VkiF0iPEo2xAVAfJDxdt1_B8VM_olhPvn-v5jrwsE/edit#gid=0) we started for the content audit: it lists out all of the original FAQs and how we might handle each of them.

The new fac.gov FAQs can be revisited in the future based on the most common requests/questions that help desk receives. 
  
### Tasks

- [x] [Content audit](https://docs.google.com/spreadsheets/d/171VkiF0iPEo2xAVAfJDxdt1_B8VM_olhPvn-v5jrwsE/edit#gid=0) of all questions on FAQs page on Census site 
- [x] Review audit with design & dev team @melchoyce @tadhg-ohiggins 
- [ ] Crew new FAQs page based on audit
- [ ] Review new FAQs page with design team 
- [ ] Review new FAQs page with other FAC stakeholders

**Comment by erinzstrenio** [comment]
Status of the FAQs audit: [this spreadsheet](https://docs.google.com/spreadsheets/d/171VkiF0iPEo2xAVAfJDxdt1_B8VM_olhPvn-v5jrwsE/edit#gid=0) is color-labeled with the status of each FAQ. 

- Green = This info will still either live on as an FAQ or be included as helper text in the form. Most of these have updated text for the FAQ or helper text but some may still need to be drafted or reviewed. 
- Yellow = We're not sure. Need to come back to these. Many of these have turned into backlog tickets to determine later.
- Pink = We're not sure. Planning to get clarity from Mark Dixon. 

Someone will need to pick up this work where we left off, which includes drafting a new FAQs page with the FAQ questions we decided to preserve and update.

**Comment by pkigongo** [comment]
Do we have a SME /reviewer at the FAC to review our assessments of content?

**Comment by lauraherring** [comment]
Spoke with Erin, the SME she worked with was Mark Dixon with Census. 

Mark Dixon
Branch Chief
Federal Programs Branch
Economic Reimbursable Surveys Division
U.S. Census Bureau
Office [301.763.7264]
[Mark.A.Dixon@census.gov](

**Comment by jadudm** [comment]
Part of static site work, ongoing, has been/will be covered in other epics/tickets.
