### ISSUE TITLE
Rethink new FAC Resources page

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#458]
### Background

We're designing a new FAC Resources page for the GSA FAC site. This will be an updated version of the [Census FAC Resources page](https://facweb.census.gov/Resources.aspx), which hasn't been updated in 20+ years and contains outdated info. 

We're talking to Census, AICPA, auditees, and auditors about how to best rethink this page so it provides the most valuable resources to auditors and auditees using the FAC. 

**User need statement from auditee research that this work should also address:** _As a user, I need clear paths to specific kinds of resources (including troubleshooting, help for first-time users, and OMB guidance) from the homepage, so that I can get the info I need to proceed with my audit submission work._ 

[Here's a draft](https://docs.google.com/document/d/1WKIO45rufy81cgVKiCoR4g0KMBATd4rwCr3XgVgvr1s/edit#heading=h.t1j4uzbl1bn7) of the updated copy for this page.
  
### Tasks

- [x] Reach out to AICPA about auditor resources
- [x] Update Resources page based on AICPA feedback
- [x] Research with auditees during interviews
- [x] #470
- [ ] Update Resources page based on auditees' feedback
- [ ] Update Resources page based on auditors' feedback
- [ ] Peer review with design team
- [ ]  #466 
- [ ] Hand off to dev

**Comment by melchoyce** [comment]
Just finished a round of auditee testing. For the most part, it felt like auditees were most concerned about:

- OMB guidance
- Help getting started with their first audit submissions
- Technical help (FAQs)

**Comment by melchoyce** [comment]
Auditor survey is now complete.

**Comment by melchoyce** [comment]
Most recent mockup:

![image](https://user-images.githubusercontent.com/2846578/218805609-bb6381d4-b87a-44b1-b45b-cbd3273eda7b.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5725%3A33243&t=tJV9hgr08q9yihCD-4)

**Comment by melchoyce** [comment]
Survey responses: https://docs.google.com/forms/d/1P5T1ExyXfKZWvHedSVcedm0wpJhjAW6u8XYMhlNXBHE/edit#responses

**Comment by jadudm** [comment]
These designs have all been pulled in to the most recent work/design/content work, and will be ticketed as part of new epics.
