### ISSUE TITLE
Onboard Scott

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#46]
**Background**

**We'll know we're done when...**
- [x] Scott has access to all tools and context he needs to start picking up some initial work 

**Tasks**
- [x] Add Scott to GH team
- [x] Make sure Scott can access Figma
- [x] Add Scott to 10x-federal-audit-clearinghouse
- [x] Add Scott to our Gdrive phase 3 and 4 folders
- [x] Add Scott to all relevant meetings
