### ISSUE TITLE
Mock up new FAC Resources page

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#466]
Breakout issue of #377

### Background

We're designing a new FAC Resources page (#458) based on research with auditors and auditees.  Once we complete the research and content design work in #458, we can mock up the new FAC Resources page in Figma.

### Tasks

- [x] Mock up new page
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] All text has a contrast ratio of 4.5:1 with the background
- [x] Interaction are documented if they deviate from USWDS components
- [x] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [x] There is an option for multilingual support
- [x] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
Related: https://github.com/GSA-TTS/FAC/issues/377

**Comment by pkigongo** [comment]
Partially blocked due to lack of content staff. Erin did complete some things that can be used in for copy in Mockups.

**Comment by melchoyce** [comment]
Still waiting on final copy, but I had a chance to cowork with @Leighdiddy and @lauraherring and we came up with a draft for the page:

![image](https://user-images.githubusercontent.com/2846578/216400068-ecec4323-be70-480e-bb06-78e9f47354b4.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5725%3A33243&t=Wuq6OT3Qgwxucjds-4)

Pinging the above folks + @austinhernandez @thebestsophist for peer review.

**Comment by melchoyce** [comment]
Chatted about this during our design backlog chat today. Putting it in our backlog to revisit and update once we have a chance to review the copy for these pages.

**Comment by jadudm** [comment]
Done. Or, integrated into the new static site work.
