### ISSUE TITLE
Attach placeholder site on fac.gov

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#469]
Split off of #452

### Background

@jadudm says:
>The [fac.gov](http://fac.gov/) domain will expire on 9/25/22 if we do not attach a DNS to it. I assume this means we need to get a placeholder up on Federalist. Whether that’s the app (FAC-frontend) or the skeleton I threw together ([FAC-transition-site](https://github.com/GSA-TTS/FAC-transition-site)), I don’t know.

(See 🔒 https://gsa-tts.slack.com/archives/C1L58R804/p1661862909026119 )

### Acceptance Criteria (We'll know we're done when...)

- [x] A determination was made for what should be on the fac.gov site until a production-ready site is up 
  - Per Matt J, a simple "coming soon, go to https://facweb.census.gov/" should suffice
- [x] fac.gov resolves to that site

### Tasks

(These may evolve the deeper down the rabbit hole I go...)

- [x] Determine what should go on fac.gov before we have production-ready site to go there
- [X] Deploy site to Federalist staging server
- [X] Contact Federalist regarding production site
- [x] Fill out Federalist questionaire
- [X] Site scanned by GSA IT
- [x] Attach custom domain to Federalist instance
- [x] Federalist production site is live
- [X] Add DNS entries to fac.gov
   - See #452
- [X] Start process of adding record for site to [GSA Touchpoints](https://touchpoints.app.cloud.gov/admin/websites)
- [x] Site added to GSA Touchpoints

**Comment by petermarks-gsa** [comment]
Per sprint planning discussion, we're blocked on response from Federalist.
