### ISSUE TITLE
User survey to auditors for FAC Resources page

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#470]
Breakout issue of #458 

### Background

We're sending out a user survey to ~150 auditors to find out which resources are most helpful to them when submitting audits to the FAC. We'll need to go through PRA approval before sending out the survey.

The survey asks auditors: "How would you rate this resource...?" on a scale of "not at all helpful" to "very helpful." The survey asks them about each resource that AICPA and Census recommend we include on the FAC resources page. Once we get survey results back, we can decide which resource links we want to include on the page based on which ones are rated as most helpful. 

### Acceptance criteria (We'll know we're done when...)

- [x] We hear back from ideally 30 auditors and can synthesize the results to decide which resources should be on the updated FAC resources page and which are not helpful for users
  
### Tasks

- [x] Create [Google Form survey](https://docs.google.com/forms/d/1P5T1ExyXfKZWvHedSVcedm0wpJhjAW6u8XYMhlNXBHE/edit) for auditors to complete
- [x] Peer review of survey 
- [x] Complete ICR form for PRA approval 
- [x] Send documents to OMB contact to begin PRA process
- [x] Get PRA approval
- [x] Send survey to auditors ([email list](https://docs.google.com/spreadsheets/d/1sOtfOD0KHHJgNDu2zOQYKRY3LQf9TQFR-NxyX8TQBfo/edit#gid=0))

**Comment by erinzstrenio** [comment]
Here's a link to the survey: https://docs.google.com/forms/d/1P5T1ExyXfKZWvHedSVcedm0wpJhjAW6u8XYMhlNXBHE/edit

And attached is the completed ICR form for PRA approval.
[FAC user testing - ICR for GSA A11 Section 280 Clearance.docx.pdf](https://github.com/GSA-TTS/FAC/files/9569494/FAC.user.testing.-.ICR.for.GSA.A11.Section.280.Clearance.docx.pdf)

**Comment by melchoyce** [comment]
Hey @erinzstrenio, do you happen to remember if we have any email copy drafted already? I'm finally circling back to this.

**Comment by melchoyce** [comment]
Surveys sent!

**Comment by melchoyce** [comment]
I closed the survey this morning. We ended up with 16 total respondents.

Here are the results, ranked in order of score average:

## 1. [Assistance Listings from SAM.gov](https://sam.gov/content/assistance-listings)

![assistance listings](https://user-images.githubusercontent.com/2846578/199314070-7bc13029-61a5-4e9f-896a-c3cf28c1f223.png)
Ave. score: 4.75

## 2. [Compliance supplements from OMB](https://www.whitehouse.gov/omb/office-federal-financial-management/)

![compliance supplements](https://user-images.githubusercontent.com/2846578/199314341-5d5a82be-85b9-4371-b16f-e3d11de5ed98.png)
Ave. score: 4.5

## 3. [Government Auditing Standards (GAO) Yellow Book](https://www.gao.gov/assets/720/713761.pdf)

![gao yellow book](https://user-images.githubusercontent.com/2846578/199314621-b608e491-5ae7-47b6-9829-dcc307caf095.png)
Ave. score: 4.5

## 4. [FAQs on Uniform Guidance/Code of Federal Regulations (CFR)](https://www.cfo.gov/assets/files/2CFR-FrequentlyAskedQuestions_2021050321.pdf)

![faqs on uniform guidance](https://user-images.githubusercontent.com/2846578/199314729-4e7042bf-f6b6-4136-a37d-9d37295ebd9c.png)
Ave. score: 4.125

## 5. [GAO Green Book, Standards for Internal Control in the Federal Government](https://www.gao.gov/assets/720/713761.pdf)

![gao green book](https://user-images.githubusercontent.com/2846578/199314861-f43b4e0a-fb27-40db-a1b5-89c2568c83bb.png)
Ave. score: 3.9375

## 6. [Compliance Audits](https://us.aicpa.org/content/dam/aicpa/research/standards/auditattest/downloadabledocuments/au-c-00935.pdf)

![compliance audits](https://user-images.githubusercontent.com/2846578/199315134-d32308dd-6db0-4aaf-91bb-2f01eeb56787.png)
Ave. score: 3.875

## 7. [Consideration of Laws and Regulations in an Audit of Financial Statements](https://us.aicpa.org/content/dam/aicpa/research/standards/auditattest/downloadabledocuments/au-c-00250.pdf)

![consideration of laws](https://user-images.githubusercontent.com/2846578/199315236-0042373e-5468-4a3f-a26e-d63829f3f694.png)
Ave. score: 3.6875

## 8. [Communicating Internal Control Related Matters Identified in an Audit](https://us.aicpa.org/content/dam/aicpa/research/standards/auditattest/downloadabledocuments/au-c-00265.pdf)

![communicating internal contrl related matters](https://user-images.githubusercontent.com/2846578/199315376-4eba864c-6642-4fdc-b898-0bef66d04c3c.png)
Ave. score: 3.625

## 9. [Audit report validator](https://facweb.census.gov/uploadpdf.aspx)

![audit report validator](https://user-images.githubusercontent.com/2846578/199315555-eca2209b-7a31-4b6f-8c76-232a73c9978e.png)
Ave. score: 3.5625

## 10. [UEI registration on SAM.gov](https://sam.gov/content/home)

![uei reg](https://user-images.githubusercontent.com/2846578/199315658-aca62e54-355b-4ff6-bba7-7926b57725dd.png)
Ave. score: 3.4375

## 11. [Federal program contacts](https://facdissem.census.gov/Main.aspx)

![federal programcontacts](https://user-images.githubusercontent.com/2846578/199315755-afffc580-7840-4d3d-a452-016a22efff3c.png)
Ave. score: 3.375

## 12. [Single Audit Act (SAA)](https://uscode.house.gov/view.xhtml?path=/prelim@title31/subtitle5/chapter75&edition=prelim)

![saa](https://user-images.githubusercontent.com/2846578/199315831-ce533c68-5417-4d02-ae96-967896786ebd.png)
Ave. score: 3.3125

## 13. [US Code codified by year and subject](https://www.govinfo.gov/app/collection/uscode)

![us code](https://user-images.githubusercontent.com/2846578/199315921-a3e50671-d261-4f48-84e3-d72802143305.png)
Ave. score: 3.1875

**Comment by melchoyce** [comment]
We also had some freeform answers:

## Do you refer to any other resources on a regular basis to help you more easily complete your audits on the FAC? List any resources here.

- Uniform Guidance - 2 CFR Part 200, OMB Compliance Supplement as parted out by the American Institute of Certified Public Accountants
- Suggest adding links to the Code of Federal Regulations search (both the annual edition and the ecfr) and a specific link for the Uniform Guidance.
- CCH Knowledge Coach audit methodology
- i always use the single audit search database, and the audit report validator. now that UIN numbers are required for submission, I assume that search database will be used frequently as well.
- https://www.usaspending.gov/; https://www.grants.gov; https://www.whitehouse.gov/omb/information-for-agencies/memoranda/
- AICPA audit guide for Government Auditing Standards and Uniform Guidance; 2 CFR 200 (uniform guidance)
