### ISSUE TITLE
Synthesize and write up Auditee research

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#474]
Breakout issue of #150 

### Background
We've completed usability testing with Auditee user groups and now need to review, synthesize, and document our findings.

### Acceptance Criteria (We'll know we're done when...)

- [x] We have documented research results in the wiki
- [x] We have documented any new user stories
- [x] We have documented auditee user roles, goals, pain points, and needs in the design wiki

### Tasks

- [x] Completed 8-9 usability tests with a mix of tribal and non-tribal Auditees
- [x] Pull quotes
- [x] Tag quotes
- [x] Synthesize research
- [x] Write up summary 
- [x] Write up new user needs statements
- [x] Write up user roles, goals, pain points, and add to the design wiki
