### ISSUE TITLE
As an (auditee or auditor) certifying official, I need to be able to revoke access from the account creator.

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#476]
### Background

Per Mark Dixon's feedback in our Census call on 9/10 (see [meeting notes](https://docs.google.com/document/d/1DxuyVOusBIIRrXCaOmmzQp-Q54bthuSirmwR4j4jTbc/edit#heading=h.ie9w2176jkvz)), both auditee certifying official and auditor certifying official should be able to revoke access from the account creator. 

> "I think you should be able to remove their access, because I could see that happening… wouldn’t be unusual that you have a staff account that starts a submission,but then moves to a different CPA firm and the original firm wants to revoke access. Or, the account creator gets fired. Should be a mechanism in place to revoke their access."

It covers the following stories:

1. As an auditee certifying official or auditor certifying official, I need to be able to revoke access from the account creator.

### Acceptance criteria (We'll know we're done when...)

- [ ] When a certifying official user can revoke access from the account creator. The account creator role doesn't need to be re-assigned to a new user. The original account creator's name can still be listed on the "Manage user access" page but this user should no longer be able to edit the audit report. 
  
### Tasks

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

### Definition of Done

- [ ] Meets acceptance criteria
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

**Comment by melchoyce** [comment]
Done in #540
