### ISSUE TITLE
Backend endpoint for data to generate Excel (placeholder)

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#478]
Breakout issue of #443 

### Background

The FAC has to generate an Excel file for the user to download to fill in with their federal awards. This task is specifically for an API endpoint that the frontend will gather data for the Excel spreadsheet. (For now, this API endpoint won't return anything.)

Endpoint should be `/sac/edit/[report_id]/federal_awards`

### Acceptance Criteria (We'll know we're done when...)

- [ ] New endpoint is created
- [ ] Test to ensure it's able to be contacted and return an empty `{}`

### Tasks

- [ ] New endpoint is created
- [ ] Test to ensure it's able to be contacted and return an empty `{}`
