### ISSUE TITLE
Get the download button to work so that it generates a blank Excel sheet from an empty JSON object that it gets from an endpoint

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#479]
Breakout issue of #443 
Blocked on #478

### Background

The FAC has to generate an Excel file for the user to download to fill in with their federal awards. This task is specifically for the download button that the user will click to get a blank Excel spreadsheet.

### Acceptance Criteria (We'll know we're done when...)

- [ ] Click download button, you should receive a .xlsx file
- [ ] The file should not have any data inside of it
- [ ] There should be some unit test to check a file was gathered

### Tasks

- [ ] Import ExcelJS
- [ ] Make sure there is a design there is a design for this
- [ ] Add download button
- [ ] The frontend will access an API which will be an empty object (for now)
- [ ] Then it will generate a blank spreadsheet .xlsx file and sent to the user

**Comment by geekygirlsarah** [comment]
#478 is closed so this is unblocked.

**Comment by heymatthenry** [comment]
There isn't currently a button to get working, so this issue arguably depends on #462.

**Comment by tadhg-ohiggins** [comment]
We decided to focus on making sure we could accept Excel and pull data from it, and are deprioritizing the generation of Excel for the moment, so I moved this to Backlog.

**Comment by tadhg-ohiggins** [comment]
I edited the ticket to reflect our no longer generating Excel files dynamically; now this issue is about downloading a static Excel file.

**Comment by jadudm** [comment]
In the spirit of helping get this off the board...

@Leighdiddy or @lauraherring , where could we link the static files in? Is there somewhere in the site design that we can link these assets? Even if it isn't perfect/part of a *final* information architecture, could/should we get them linked in *somewhere*?

If we put that in here, we can link the templates and be done with this ticket.

**Comment by thebestsophist** [comment]
noting here that some of the figma mockups include excel templates for files that are being inputted in the web interface on the Census FAC so either we need to create new templates or include a web interface

Data in question: 
- Additional EINs
- Secondary auditors

**Comment by jadudm** [comment]
Will this be in the app, or the static site? Going to remove @danswick for the moment, and move this to available... it's not urgent-urgent, just important-to-do-soon...

**Comment by jadudm** [comment]
We do need to be able to download the templates. Moving to the SF-SAC documentation milestone, as linking in the templates feels like part of documentation.
