### ISSUE TITLE
Backend endpoint for JSON schema file

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#481]
Breakout issue of #443 

### Background

The FAC has to generate an Excel file for the user to download to fill in with their federal awards. This task is specifically for an API endpoint that will provide a JSON schema file that the frontend and backend can use for validating data and generating Excel files.

The endpoint should be something like `/schemas/2023/federal_awards`.

### Acceptance Criteria (We'll know we're done when...)

- [ ] API endpoint exists
- [ ] Endpoint returns JSON schema file
- [ ] Test(s) to ensure file is sent

### Tasks

- [ ] Create API endpoint
- [ ] Send JSON schema as return item
- [ ] Add test(s) to ensure this works as expected
