### ISSUE TITLE
Frontend generates the unfilled Excel file from that JSON Schema

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#482]
Breakout issue of #443
~Blocked on #478~
Blocked on #481 

### Background

The FAC has to generate an Excel file for the user to download to fill in with their federal awards. This task is to generate the unfilled Excel file with validation that matches the JSON schema. 

### Acceptance Criteria (We'll know we're done when...)

- [ ] Generates an Excel file with validation via call to external API (using PowerQuery or similar means).
- [ ] Sends file to user
- [ ] Test to ensure file is downloaded
   - Don't test stuff in the file yet, this will take a while until the Excel uploading features are done

### Tasks

- [ ] Generate an Excel file that reads JSON schema and generates Excel file based on that
- [ ] Send the file to the user
- [ ] Manually test it (check validations work)
- [ ] Write tests (if they don't exist) to check the file is downloaded

**Comment by jadudm** [comment]
We have more work to do with users before we make decisions on this front; also, it will be post-MVP. What we believe is that this is not the path we will be going in the first instance.
