### ISSUE TITLE
Accept only UEI in pre-SAC flow, add backend SAM.gov 

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#486]
### Background

In implementing #399, we realized the following about the information coming from SAM.gov:

*   We’re not storing all the fields we need.
*   We’re getting info from SAM.gov and then passing it to the form, which technically means the user could alter that somehow; we want that information to be coming from SAM.gov directly.

We should store only the UEI as part of that interaction and then, during the SAC creation step, make another request to SAM.gov for that information.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   The SAC creation step pulls the data from SAM.gov.
- [ ]   The `/sac/edit` endpoint returns the data in question as part of its response (currently it returns the correct JSON shape and the fields, but they’re empty because we don’t have that information).

### Tasks

- [ ]   Add a UEI-lookup step to the SAC creation flow and add the returned information to the new SAC.
- [ ]   Change the backend to no longer submit the non-UEI information from the user in the pre-SAC steps.
- [ ]   Change the frontend to longer submit that information to the backend.

**Comment by jadudm** [comment]
I'm adding this to the SF-SAC milestone, not because this is something we need to address as-is, *per se*. However, we do need to move to our "you must have a UEI" posture. This ticket serves as a reminder. We are expecting users to have a valid UEI at time of Pre-SAC, and if they don't, they cannot proceed. Further, we will cache SAM.gov data, which is not ticketed/storied, and may not be part of the MVP.

**Comment by tadhg-ohiggins** [comment]
We finished this quite some time ago; closing.
