### ISSUE TITLE
Remove deprecated fields from SingleAuditChecklist model

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#489]
### Background
As part of #455, several fields/columns need to be removed from the `SingleAuditChecklist` model, as they are [migrating to the newly-created `sac_json` field](https://github.com/GSA-TTS/FAC/issues/488).

The fields to be removed from `SingleAuditChecklist` are:
- `auditee_fiscal_period_start`
- `auditee_fiscal_period_end`
- `audit_period_covered`
- `ein`
- `ein_not_an_ssn_attestation`
- `multiple_eins_convered`
- `auditee_uei`
- `multiple_ueis_covered`
- `auditee_name`
- `auditee_address_line_1`
- `auditee_city`
- `auditee_state`
- `auditee_zip`
- `auditee_contact_name`
- `auditee_contact_title`
- `auditee_phone`
- `auditee_email`
- `auditor_firm_name`
- `auditor_ein`
- `auditor_ein_not_an_ssn_attestation`
- `auditor_country`
- `auditor_address_line_1`
- `auditor_city`
- `auditor_state`
- `auditor_zip`
- `auditor_contact_name`
- `auditor_contact_title`
- `auditor_phone`
- `auditor_email`
- `submitted_by` (not migrating to `sac_json`, but being removed because it is made redundant by the `creator` `Access` role.

### Acceptance Criteria (We'll know we're done when...)

- [x] The `SingleAuditChecklist` model contains none of the above fields
- [x] All existing tests are passing

### Tasks

- [x] Remove the above fields from the `SingleAuditChecklist` model and generate a migration
- [x] Update all tests that depend on the above fields to reference the appropriate data in `general_information` instead
- [x] Wherever necessary, implement [model properties](https://docs.djangoproject.com/en/4.1/topics/db/models/#model-methods) on `SingleAuditChecklist` for accessing data contained in the `general_information` field.

**Comment by pkigongo** [comment]
Related to #488

**Comment by timoballard** [comment]
This was completed in #671
