### ISSUE TITLE
Support Alternative Compliance Examination Engagement (ACEE) audits

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#497]
### Background

A new type of audit is being introduced, called "alternative compliance examinations." This is for grants such as temporary COVID relief funds. Census is working to integrate this into their system for this upcoming year's audits, and we should start thinking about supporting it as well. This will likely need to be in our MVP.

See additional details in [our Census Call notes](https://docs.google.com/document/d/1DxuyVOusBIIRrXCaOmmzQp-Q54bthuSirmwR4j4jTbc/edit?usp=sharing).

### Acceptance criteria (We'll know we're done when...)

- [ ] Folks submitting ACE audit reports will be able to successfully submit their forms.
  
### Tasks

- [x] Figure out everywhere ACE should be mentioned/supported in the audit submission process
  - [x] Create New Audit page (new question)
  - [x] SF-Sac: General Information page ("type of audit" question)
- [ ] Write copy for the new questions (ask Census what they're saying?)
- [ ] Add ACE to the mockups
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
We're going to check in with Census in our next call about their implementation to use as an example.

**Comment by melchoyce** [comment]
Sorry, forgot to update this with meeting notes:

- Only available for 2022 submission. Form isn’t different, however audit that gets uploaded is different so they can’t answer all the questions.
- There are certain parts of the form that aren’t visible so they don’t have answers
- Have separate set of edits that get run.
- Watered down from normal
- Different certification statement—audtior isn’t willing to certify things that are from the 
- Should be able to find them on the image management system
- Text of correction plan, findings, new search filter for type of audit
  - Three options: single, program specific, ACEE
  - You can bring up the ACE submissions in the (search?)
- Will forward updated copy of the 2023 grant form for SF-SAC
  - Someone to post in slack for visibility
  - Will also check to make sure the description on the tool is correct
- Mel will log into site to take screenshots to see what’s changed

@pkigongo Do you remember who was going to forward that 2023 grant form?

**Comment by melchoyce** [comment]
<img width="1203" alt="Screen Shot 2023-03-02 at 1 05 57 PM" src="https://user-images.githubusercontent.com/2846578/222514627-f4c1b46e-98ff-42d5-afe5-e616976e3fe4.png">
<img width="1260" alt="Screen Shot 2023-03-02 at 1 08 23 PM" src="https://user-images.githubusercontent.com/2846578/222514648-601d362c-b13c-467b-9cd6-1ee0891b834a.png">

**Comment by pkigongo** [comment]
Blocked. Leigh to sync w/Mel to review

**Comment by Leighdiddy** [comment]
screen shot 1 submission criteria check: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A23015&t=MKoQbRjmJpV67qqN-0

-needs new Q for ACEE (have @lauraherring review copy)

ss 2 submission form: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A24912&t=GoncNbOaUcofzhpd-0

-note for engineering, selecting ACEE will introduce different tabs, ACEE has less tabs.

**Comment by jadudm** [comment]
Will pick up in post-launch work with OMB and other conversations.
