### ISSUE TITLE
Allow certifying officials to reject audits

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#498]
### Background

During a recent Census call, Mark suggested allowing certifying officials to reject and send back audits for revision. They could potentially choose a reject option, then select who to notify about the rejection, and include a message about why they are not certifying the audit. 

This would be a post-MVP feature.

### Acceptance criteria (We'll know we're done when...)

- [ ] Certifying officials have a way of rejecting audits during the certification step.
  
### Tasks

- [ ] Design a way for auditor and auditee certifying officials to reject audits from the Certification page
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)
