### ISSUE TITLE
Manage user access screen

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#499]
### Background

Covers the following stories:

1. As a user, I need to be able to change who has/modify users' access to a draft audit submission. 

The following designs were produced in https://github.com/GSA-TTS/FAC/issues/340: 

https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4034%3A19388

### Acceptance criteria (We'll know we're done when...)

- [ ] A user can add/change the auditee/auditor certifying official, including email validation
- [ ] A user can change the role of the auditee/auditor certifying official through the dropdown
- [ ] A user can add auditee/auditor contacts through a modal screen, including email validation
- [ ] A user can change the role of auditee/auditor contacts through the dropdown 
- [ ] A user can remove auditee/auditor with modal confirmation
- [ ] A user can view but not edit the audit submission creator

### Interaction notes from #340 

- Since you can have only one "certifying official" and they are a required field, the CTA is “Change user," and you have to add a valid email address (error message below)
- We also added the account creator as it's own role. 
  - The current FAC, does not show the audit submission creator user on the list of roles/users and [according to census](https://docs.google.com/document/d/1DxuyVOusBIIRrXCaOmmzQp-Q54bthuSirmwR4j4jTbc/edit#bookmark=id.8owbjdpuo8jv), the system does not allow you to change yourself and they do not have a special role they have because they start the form.
- Clicking on the role dropdown and changing the role moves the row to another section, but moving a certifying official [generates an inline error](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4755%3A22617) (more on errors below)
- I also made a new page for what will happen if the certifying officials are added during the submission creation process but the auditee/auditor contacts are blank
- Email address fields are not editable on the submission access page, you must click the add or change button below each row to open the "Add / change..." modal
- Each role (Auditee certifying official, Auditor certifying official, Auditee, or Auditor) has its own add/change button is unique to the section, so no role selection is needed.
- Since you can have multiple auditee contacts and auditor contacts, the button is "Add another contact"
- Add another contact and change contact links open a modal which will ask for email address and confirm/re-enter email field
- You can shift the roles around on the page without adding a new user
- Clicking on the role dropdown and changing the role moves the row to another section
- In the Auditee and Auditor sections, `remove user` button in the first row deletes the email address field, in the subsequent rows (in the case of multiple auditees/ors) remove user button deletes the entire row and add another contact link moves under the row above

### Error messages:
- On the [Manage user access - moved certifying auditee page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4755%3A22617) "You must enter an email address..." error message only occurs when you move someone from a certifying role (either auditee or auditor) into another role.
- On [Modal - duplicate error](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4706%3A21287) Error message only occurs when you try duplicating contacts
- On [Modal - invalid email address](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4762%3A21741) Error message only occurs when you try putting in an incorrect email address format (no @ or .domain, etc.)
- On [Modal - email address required](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4764%3A21782) Error message only occurs when you try submitting a blank form

### Tasks

NEEDS SCOPING

### Definition of Done

- [ ] Meets acceptance criteria
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

**Comment by melchoyce** [comment]
Latest mockups: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5281%3A32558&t=e5RAy7v8wlfoUX9m-4

More recent information in #540
