### ISSUE TITLE
Mock up SF-SAC data submission for testing

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#50]
### **Background**
In order to test our [initial hypotheses](https://docs.google.com/document/d/1ZQ3Q8iJrdjRdsg9gEDmrzhLyCQSOoF2EzMiu9vPANLI/edit#) about building the current audit submission process using USWDS, we want to mock up how the SF-SAC form data entry process might look and feel and test it with auditors and auditees. 

**Assumptions that impact what screens we mock**
- We will begin by mocking only the happy path
- Users will be creating a new submission, not picking up/editing a saved submission
- Users will be existing users 
- Users will be asked to enter UEI instead of DUNS
- Auditor participants are submitting an audit that has no findings
- Audit has no No CAP Text
- Audit has no secondary auditors
- Audit has no additional DUNS

**We'll know we're done when...**
- [x] We have mocked minimum screens that allow us to test our hypotheses
- [x] Users can interact with mocks (e.g., via InVision or Figma prototyping capability)

**Tasks**
- [x] Set up Figma environment with USWDS components and page templates
- [x] Review [current screen flow](https://www.figma.com/file/ty7iZnrnpBO5OlhRoDQd4m/FAC-Playground?node-id=1801%3A9179)
- [x] Mock screens using USWDS
- [x] Pair on reviewing designs / making refinements
- [x] Review w/ SME (Gil, Mark D?)
