### ISSUE TITLE
Audit submission

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#503]
### Background
Implementation task for https://github.com/GSA-TTS/FAC/issues/339 that covers the following stories:

1. As a someone who has access to a draft audit submission, I need a way to submit my certified audit package to the FAC. 

### Design
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3736%3A17737

### Acceptance criteria (We'll know we're done when...)

- [ ] Given both auditee and auditors have certified an audit, per work in https://github.com/GSA-TTS/FAC/issues/319
- [ ] I should see "Submit to FAC for Processing" button
- [ ] When I press the button, I should see a "confirm your submission" modal
- [ ] When I click confirm, I should be on the my audit submissions page. 
- [ ] On that page I should see "Submission complete" and see the status of the submission change in the table
  
### Tasks

NEEDS SCOPING

### Definition of Done

- [ ] Meets acceptance criteria
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.
