### ISSUE TITLE
Mock new audit creation process

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#51]
**Background**

**We'll know we're done when...**
- [x] Users can enter min. information required to create a new audit record in the DB
- [x] Users are prompted to check whether they meet audit requirements before investing any effort in entering audit data
- [x] Users can specify the name and contac info for folks who need to have access to the submission
- [x] Users can associate their new audit with their UEI

**Tasks**

- [x] Review [current screen flow](https://www.figma.com/file/ty7iZnrnpBO5OlhRoDQd4m/FAC-Playground?node-id=1801%3A9179)
- [x]  Mock screens:
 - - [X] New/existing record
 - - [X] Check submission criteria
 - - [x] Auditee info
 - - [x] Submission access / contact info
- [x]  Pair on reviewing designs / making refinements
- [x]  Review w/ SME (Gil, Mark D?)
