### ISSUE TITLE
Analyze auditee research data

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#512]
**Background**

**Acceptance Criteria (We'll know we're done when...)**
- [x] We've done some affinity mapping across relevant data and have identified themes from auditee research

**Tasks**
- [x] Create analysis template in Mural or Excel
- [x] Review interview notes and (if needed) videos
- [x] Pull relevant excerpts into analysis template
- [x] Look across excerpts and name themes.
