### ISSUE TITLE
Report out on auditee research / make auditee research insights actionable

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#513]
**Background**

**Acceptance Criteria (We'll know we're done when...)**
- [x] We have an easily scannable artifact that communicates the most salient research insights and recommendations
- [x] New user needs statements are documented either in the story map or as new GH issues

**Tasks**
- [x] Dependent on #512 
- [x] Write up summary of research insights (either a doc or a deck)
- [x] Present research summary to the team during a co-work session
- [x] Write up new user needs statements and add to story map or GH
- [x] Update auditee role, goals, and needs statements in wiki as needed

**Comment by MelissaBraxton** [comment]
@melchoyce  - here's my draft wiki update to the auditee description [this page](https://github.com/GSA-TTS/FAC/wiki/User-roles-and-key-epics) if you want to take a look before I post!
https://docs.google.com/document/d/1d4MSX61WaRXxZTw2nW6KEzD09ff689JZO8wPDahjO1w/edit
