### ISSUE TITLE
Conduct cognitive walkthrough workshop to evaluate current prototype 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#514]
### Background
Given the highly specialized nature of single audits and the FAC workflow, we'd like to enlist the help of SMEs to do an [cognitive walkthrough workshop](https://www.nngroup.com/articles/cognitive-walkthrough-workshop/) of the current prototype to help us catch usability and content issues that are very difficult for people without deep experience and domain specific subject matter expertise to see.  

### Acceptance Criteria (We'll know we're done when...)
- [ ] We've completed the cognitive walkthrough
- [ ] Notes on insights and task success/fail from the cognitive walkthrough are documented in a place the relevant folks can access

### Tasks
- [ ] Schedule 90 minute cog walkthrough workshop w/ SMEs
- [ ] Stitch together end to end prototype
- [ ] Write walkthrough facilitation script and action sequences
- [ ] Conduct workshop
- [ ] Document insights

**Comment by MelissaBraxton** [comment]
@melchoyce and @austinhernandez  - This is issue I put together based on our chat this afternoon. LMK what you think and feel free to edit/add to it as you see fit!
