### ISSUE TITLE
Census: Start directing people to the landing page

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#517]
### Background
Census is eager to start directing people to the new FAC.gov page so that they can begin bookmarking it for future use. We want to invest a little bit of effort in making people's first visit a valuable experience by refining the content and offering them an opportunity to participate in user research.  

### Acceptance Criteria (We'll know we're done when...)

- [x] The landing page has clear, concise copy that explains what the page is for and where to to submit /search for audits
- [x] FAC.gov provides users a way to volunteer for user research/provide their contact info to the FAC research team in a few clicks. 

### Tasks

- [x] Reply to Census and ask them to hold off comms for a few more days
- [x] Review copy write up any refinements
- [x] Set up touchpoints intercept
- [x] Submit intercept for touchpoints to implement
- [x] Test touchpoints intercept
- [x] Email Census to let them know that they can start sharing the URL

**Comment by MelissaBraxton** [comment]
@austinhernandez and/or @melchoyce  - here's a draft touchpoints research recruitment intercept. Would be great to have another pair of eyes on it! 

https://touchpoints.app.cloud.gov/touchpoints/9412c559/submit

I'm thinking of going with the tab & modal option for implementing it but would welcome other thoughts if you have them.

**Comment by MelissaBraxton** [comment]
Update: Our Census contact is on board with waiting until 10/17 or 10/18 until after touchpoints is up to share the url more broadly.

**Comment by melchoyce** [comment]
> I'm thinking of going with the tab & modal option for implementing it but would welcome other thoughts if you have them.

Is that [this option](https://touchpoints.app.cloud.gov/admin/forms/76fb6507/example)?

**Comment by MelissaBraxton** [comment]
Yep! But I was thinking the button text would be "Help us design the FAC!"

**Comment by melchoyce** [comment]
I find the "tab that opens a modal instead of opening up a panel" pattern kind of weird from an interaction standpoint, but it's probably the pattern that works best of the options provided.

**Comment by MelissaBraxton** [comment]
@melchoyce - Any copyedits, or do you 👍 for touchpoints to implement and test? 

Based on our Slack exchange, it sounds like we're leaning away from other copy edits on the fac.gov page itself right now?

**Comment by melchoyce** [comment]
What do you think about something like this: 

> The Federal Audit Clearinghouse is in the process of being revamped, and the team is looking for people to participate in user research interviews. Interviews will be conducted over Zoom, and will take about 45 minutes. If you’re interested in chatting about your experience using the FAC, please enter your details so we can follow up with you!

**Comment by MelissaBraxton** [comment]
Touchpoints is live. 

We talked about holding off on additionally detailed copy for now. 

There's one outstanding Q on whether we want to add the footer in the near term, but either way, Census has scheduled an announcement that will include the new URL for 10/20.
