### ISSUE TITLE
Begin leveraging Census and GSA FAC web analytics

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#526]
### Background

Analytics data can help us understand how resources on the current site are being used. This issue 

### Acceptance criteria (We'll know we're done when...)

- [ ] Members of the GSA and Census teams can access Census FAC site analytics. 
- [ ] We have written guidance on meaningful metrics that will help us triangulate other data on how folks are using the site(s) and implications for our work. 
  
### Tasks

- [x] Check and see whether analytics are wired up on Census FAC sites
- [x] Check and see whether analytics are wired up at fac.gov
- [ ] Get DAP analytics code for FAC.gov
- [ ] Determine who at Census will own the DAP dashboard for Census
- [ ] Get someone at Census to generate the DAP analytics code for Census submission site
- [ ] Get someone at Census to generate the DAP analytics code for Census dissemination site
- [ ] Ensure that relevant team members can log in to DAP and view analytics
- [ ] Identify key metrics and document a plan for establishing a baseline and how progress over time will inform our work
- [ ] Post plan to wiki (or other other place where everyone on the team can easily access?)
- [ ] Update [design onboarding documentation](https://docs.google.com/document/d/1EILl0nZr59T4PFJJMtFbmnQDJPksgzIFPuoFDN0bk0g/edit) w/ instructions on how to get access to analytics dashboard
- [ ] TBD...

**Comment by MelissaBraxton** [comment]
As of 11/10/22, neither fac.gov or the Census FAC sites have the GA script in place.

**Comment by geekygirlsarah** [comment]
If you know what the script to add GA is, I can add it to fac.gov.

**Comment by melchoyce** [comment]
Who is able to get us a DAP analytics code for fac.gov? Should that be owned by engineering? @JeanMarie-TTS @tadhg-ohiggins

**Comment by mogul** [comment]
Here's [the entry point for all things DAP](https://digital.gov/guides/dap/).

**Comment by JeanMarie-TTS** [comment]
Dropped a note to the DAP to find a point of contact.

**Comment by JeanMarie-TTS** [comment]
@melchoyce , have we confirmed that the Census FAC has no analytics?

**Comment by melchoyce** [comment]
We have confirmed they don't have any analytics set up 👍

**Comment by JeanMarie-TTS** [comment]
Some links shared by the DAP team:

**Comment by JeanMarie-TTS** [comment]
1.[ Github repo with implementation instructions & code](https://github.com/digital-analytics-program/gov-wide-code)
2. [DigitalGov implementation page](https://digital.gov/guides/dap/add-your-site-dap/)
3. [DAP FAQs](https://digital.gov/guides/dap/common-questions-about-dap/)

**Comment by thebestsophist** [comment]
Noting that the Census team may have previously shared tableau analytics, but updates to legacy FAC would probably take a while.

**Comment by pkigongo** [comment]
Blocked on Census side. Have some Tableau data from Census; unsure if we'll be getting more. On our side we can put DAP on FAC.gov
