### ISSUE TITLE
Generated Excel documents should be reviewed by Design Team

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#528]
Breakout issue of...

This issue covers the design of Excel generated files.

### Background

This issue covers the design of what the Excel documents would look like as they're generated. This could be a review of Census's existing templates or it could be designing a new one from scratch. Either way, this should be done so that we can write the code to generate these in the best ways.
  
### Tasks

- [x] Design
- [x] Peer review
- [x] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [x] Interaction are documented if they deviate from USWDS components
- [x] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [x] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
@geekygirlsarah When would y'all like this done by?

**Comment by geekygirlsarah** [comment]
No rush, but don't wait forever?

I can work around not having a design for now, but I know ultimately we probably can't call the excel generation tickets "done" until this is done as well.

**Comment by melchoyce** [comment]
Looking at some of these templates, I honestly don't have a huge opinion on their styling. Overall, I think it would be nice to update the colors to match the website, and bump up the font size just a little. For example:

## Before

![Screen Shot 2022-10-25 at 11 13 56 AM](https://user-images.githubusercontent.com/2846578/197813371-e44afe87-06fd-4937-b48e-b092f78affff.png)
![Screen Shot 2022-10-25 at 11 26 09 AM](https://user-images.githubusercontent.com/2846578/197815805-4007c657-e675-441a-a719-7a67da216291.png)

## After

![Screen Shot 2022-10-25 at 11 13 39 AM](https://user-images.githubusercontent.com/2846578/197813429-b38f35e6-b3a9-474a-a7d7-4d5b08cefdeb.png)
![Screen Shot 2022-10-25 at 11 25 52 AM](https://user-images.githubusercontent.com/2846578/197815850-f7a2c47c-0993-4f9e-84af-eeab52f07d60.png)

Font: Arial 12px `#1B1B1B`
Background: `#97D4EA`
Border-bottom on just the bottom header rows: `#3D4551`

Looking at the instructions pages, I'd just update the fonts:

## Before

![Screen Shot 2022-10-25 at 11 19 02 AM](https://user-images.githubusercontent.com/2846578/197814120-0f86a5cc-8e08-4b52-aad4-bfce2fd3fd02.png)

## After

![Screen Shot 2022-10-25 at 11 18 13 AM](https://user-images.githubusercontent.com/2846578/197814329-8816b815-dbcb-45b1-b6d6-1f5bfd852269.png)

Font: 14px Arial `#1B1B1B`

Tagging @MelissaBraxton for peer review.

**Comment by geekygirlsarah** [comment]
I feel like lighter bg with darker fg is easier on the eyes, but all I have to do is change a hex code in my code and it's changed. I'd rather do whatever you all think is best.

**Comment by melchoyce** [comment]
Alright, let's go for dark text on the lighter blue background then 👍

**Comment by geekygirlsarah** [comment]
@mogul @MelissaBraxton @tadhg-ohiggins Should we close this or is this better being "officially" documented via some form of ADR-kind of thing?

**Comment by mogul** [comment]
I think this work can/should continue! The only thing we're easing up on is generating the validation inline, rather than by including some kind of macro that will submitting the Excel file (or some representation of its content) to an API for validation.

**Comment by pkigongo** [comment]
Done, from a design standpoint. To be moved to Engineering backlog
