### ISSUE TITLE
Recruit sprint 1 test participants (auditors) 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#53]
**Background**
The initial hypotheses we want to test are around Audit report and SF-SAC submission. To that end, we want to recruit auditees and auditors. We want to have completed all test sessions by 4/8.

**We'll know we're done when...**
- [x] We have scheduled research sessions with 6-7 auditors

**Tasks**
- [x] Ask Gil for list of contacts
- [x] Set up recruitment tracking spreadsheet
- [X] ensure sheet w/ PII is only available to team mates w/ a need to know
- [x] Meet with auditee/auditor contacts to refine recruitment criteria
- [x] Draft recruitment email
- [x] Email folks
- [x] Book sessions
