### ISSUE TITLE
Determining how to handle Federal Award prefix/extension edge cases

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#530]
Breakout issue of https://github.com/GSA-TTS/FAC/issues/519

### Background

Based on discussion with Census we moved forward with consolidating `agency prefix` and `CFDA extension`  into a single value, `program number`, and wrote validation in JSON Schema that requires the entry for `program number` to be in an enumeration that we sourced from [SAM.gov](https://sam.gov/data-services/Assistance%20Listings?privacy=Public). This covers the majority of cases, but the instructions for the [2019 template](https://docs.google.com/spreadsheets/d/1jswh-bw-QvsUfR9p-gYEMe4TbobnzB1N/edit#gid=385338852) refer to a number of edge cases that having only `program number` as a single value does not accommodate:

*   If the user’s intended prefix isn’t in the list, they’re supposed to choose `99` as their agency prefix, but there are no valid entries starting with `99` in the SAM.gov list.
*   CFDA three digit extension can apparently be `RD`, which is neither three characters long nor composed of digits. There are no valid entries with that extension in our list, so users would not be able to enter this.
*   CFDA three digit extension can apparently be `U` followed by two digits if the user doesn’t know their actual extension. Obviously there are no valid entries with those extensions in our list, so users could not enter those either.
*   The instructions for Additional Award Identification state that it’s required if either of the previous two cases are true, which isn’t possible with our current validation.
*   Federal Program Name can (must) be manually entered if the extension is `RD` or `U` plus some random numbers, which also doesn’t apply for us.

Overall, this is an issue for users who do not have their extensions or agency prefixes—or users whose valid extensions or prefixes are for some reason not present in our enumerated list.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We have decided either to require users to have all of this information about each federal award in order to proceed or have come up with some other approach.
- [ ]   If we come up with another approach, we’ve created the appropriate issues for it.

### Tasks

- [ ]   Consult with Census again to see how important these edge cases are for MVP.

**Comment by MelissaBraxton** [comment]
Two things stand out from a Slack thread w/ Mark that make me think we may not be able to bar folks from proceeding without an ALS:

 - some agencies may actually award some grants without an assistance listing number
 - Congress may direct funding directly to a recipient without it going through an agency or obtaining an assistance listing number.

 I think we need to come up w/ a different approach:

**Comment by tadhg-ohiggins** [comment]
2022-11-15: We intend to talk about the potential different approach for this at today's design/dev meeting.

**Comment by MelissaBraxton** [comment]
@tadhg-ohiggins and @melchoyce (cc @pkigongo) 

Based on our discussion, these are the user needs I think we need to keep top of mind here: 

- As a user, when my audit submission includes a funding source that does not have an assistance listing number (ALN), I need to be able to proceed with my audit submission without entering an ALN so that I can complete my submission on time.   (This story is not yet on the story map)

- As an agency audit resolution official, I need the search for single audits page to allow me to search by Auditee Name and CFDA so I can search for their reports more quickly. (this story IS on the story map, but below the MVP cut lin--it's on the data dissemination side)

**Comment by MelissaBraxton** [comment]
One other thing to note re: the second story ALN is formerly known as CFDA.

**Comment by melchoyce** [comment]
@tadhg-ohiggins Does this feel complete to you based on our conversation with Census on 11/17?

**Comment by tadhg-ohiggins** [comment]
I/we haven't written up the issues arising from the decision we made[^1], so probably not quite complete yet.

[^1]: Basically to do regular expression validation rather than requiring strict compliance with a list of known program numbers, while also providing user affordances in Excel to populate other fields if what the user enters is found on our list.

**Comment by tadhg-ohiggins** [comment]
Closed since we decided to follow the approach outlined in https://github.com/GSA-TTS/FAC/issues/633 instead.
