### ISSUE TITLE
Additional validation for `federal_award_passed_to_subrecipients_amount`

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#532]
Breakout issue of https://github.com/GSA-TTS/FAC/issues/531

### Background

For each federal award entry, if `federal_award_passed_to_subrecipients` is Y, then `federal_award_passed_to_subrecipients_amount` must be an integer and must not exceed the number entered for `amount_expended`.

This requirement cannot be expressed in JSON Schema and so must be captured and performed elsewhere.

For MVP, we will do this at the backend level only.

This issue includes some of the initial functionality required to handle these issues; later issues for other additional rules should be able to use the framework we create here.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We have expressed this requirement in the supplemental schema format we come up with.
- [ ]   We have written and stored the copy for the error messages in this same format.
- [ ]   We have a validation process that runs after JSON Schema validation that applies this rule.
- [ ]   We have tests for this additional validation process.

### Tasks

- [ ]   Create an additional schema format similar to JSON Schema that is suitable for use in the backend context.
- [ ]   Create the functionality to read and apply this additional schema.
- [ ]   Write functionality and tests for this particular rule.

**Comment by tadhg-ohiggins** [comment]
Closed since we decided to follow the approach outlined in https://github.com/GSA-TTS/FAC/issues/633 instead.
