### ISSUE TITLE
As a site visitor, I need consistent messaging to let me know I'm logging in to the correct place.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#533]
This issue addresses an insight from our recent research with auditees. 

On the FAC homepage, the labels on the sign in buttons should be consistent. People found two sign in buttons named different things confusing.

### Acceptance criteria (We'll know we're done when...)

- [x] When the labels on the two sign in buttons on the FAC homepage say the same thing. 
  
### Tasks

- [x] Design
- [x] Peer review
- [x] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [x] Interaction are documented if they deviate from USWDS components
- [x] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [x] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
I went with the body button label, since people seemed to click on that one more:

![image](https://user-images.githubusercontent.com/2846578/197828912-7d421f76-447a-426d-b673-2b43478cd86e.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A24052)

Pinging @MelissaBraxton for peer review.
