### ISSUE TITLE
As an auditor or auditee, I need to know whether the types of awards my entity got are subject to audit before I sign in to create a submission so that I don't start a submission when I don't need to. 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#534]
This issue covers the design of content on the FAC homepage that helps folks better understand which types of awards are/are not subject to the single audit. The $750K threshold does not actually apply to all types of awards, and some folks wondered about this.

![image](https://user-images.githubusercontent.com/2846578/217334126-639b1fa1-92cd-4cc5-8391-66b1ab22af4f.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A24052&t=pNpDk5p8r2YLFeSL-4)

### Acceptance criteria (We'll know we're done when...)

- [ ] When visitors to the homepage can quickly find information on which types of awards are/are not subject to the single audit requirement. 
  
### Tasks

- [ ] Design
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
Suggestion from Shelley Goss at Census:

> The Federal Audit Clearinghouse (FAC) is the place to submit and review federal ​single audits. When ​a non-federal entity spends $750,000 or more in federal grant funds in a given year, they are required to submit a ​single audit.

**Comment by melchoyce** [comment]
From Mark D:
> There are so many types of funding that are considered to be a federal award subject to single audit. I'm not sure there is a plain language guide that would outline the types that aren't subject to single audit.  I'm not actually aware of any federal awards that aren't subject to a single audit (based upon the actual award).  Not being subject to a single audit would be more based upon characteristics of the auditee (i.e. didn't reach threshold, for-profit, foreign based...). Here is the URL to a section of Uniform Guidance that outlines the different types of federal expenditures: https://www.ecfr.gov/current/title-2/subtitle-A/chapter-II/part-200 
> 
> I think if an auditee is unsure if they meet the threshold to need a single audit, then they should contact their grantor as the best source of information for any uncertainty or questions they have about grant compliance.  Even if they don't meet the single audit threshold, they almost certainly have alternative compliance requirements they will need to fill.
> 
> For the auditees questioning the $750K threshold, I wonder if they could be mixing that up with the threshold to distinguish Type A and Type B programs (which can be more than $750K for large recipients of federal awards).  https://www.ecfr.gov/current/title-2/subtitle-A/chapter-II/part-200/subpart-F/subject-group-ECFRea73e47c9a286e6/section-200.518#p-200.518(a)

**Comment by melchoyce** [comment]
@lauraherring Updated with screenshot

**Comment by lauraherring** [comment]
Also need to revisit helper language around "sign in" to avoid using "your audits" 

Another note: historically, some users have found having two "sign in" CTAs (page center and upper right) to be confusing but this is inconsistent across testing groups.

**Comment by danswick** [comment]
I don't think we're planning to pursue this. Please feel free to reopen if I'm mistaken!
