### ISSUE TITLE
As an auditee or auditor, I need the login process to be free of references to Census systems that are not longer relevant to my current task, so that I can proceed to logging in without confusion.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#535]
This issue covers the removal of reference to the Census Bureau at the login step. This confused some people. Even folks familiar with the FAC may not have been that aware that it’s been housed at Census. 

### Acceptance criteria (We'll know we're done when...)

- [x] The login screen does not refer to the Census Bureau
  
### Tasks

- [x] Design
- [x] Peer review
- [x] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [x] Interaction are documented if they deviate from USWDS components
- [x] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [x] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment]
Looking good! Peer review box checked!

**Comment by pkigongo** [comment]
Login.gov integration has been rebuilt.

**Comment by timoballard** [comment]
@melchoyce - Login.gov sandbox configuration updated to match the above screens:

![image](https://user-images.githubusercontent.com/1425377/210887555-08d237ea-1bf9-42ef-975c-2a8e02901846.png)

**Comment by melchoyce** [comment]
Thanks @timoballard! Can we resize the logo so it's more in proportion with the Login.gov logo? It's 115x26 in the mockup.

**Comment by timoballard** [comment]
![Image](https://user-images.githubusercontent.com/1425377/213575853-a7449e2f-b3c5-4d2f-8b22-717bb0e3a070.png)



Thanks for the help @melchoyce!
