### ISSUE TITLE
Design refinements to the report home/audit start page

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#536]
This issue covers the refinement of the report home page. We need to be careful not to overly rely on button labels and states to communicate the submission process. Button states (primary, disabled, and locked) are trying to communicate too much about what submission entails. Auditees struggled to see what they could and couldn’t do next. 

**User needs the refinements should address:**

- As an auditor or auditee, I'd like the action I need to take on the report home page to be explicit so that I don't become overwhelmed by too many options / buttons

### Acceptance criteria (We'll know we're done when...)

- [x] We'll know we're done when the report homepage clearly communicates where users are in the process and what action they need to take. 
  
### Tasks

- [x] Design
- [x] Peer review
- [x] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by austinhernandez** [comment]
**overview**
the goal was to improve the "report home" page after observations from the last round of usability testing.  Users were confused by where they were in the process, what action they need to take next, and terms, and what is required of them. this will need to go through a round of usability testing.

**figma notes**
addressed designer feedback and closed all of the comments from @melchoyce [on figma in the #536 page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5031%3A26947) to create a re-imagined report home page.

Added and linked the pages on the [ALL SCREENS](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A22829&t=FGKO9RfrVtRPRBjS-1) section of figma so people can see the interactions. 


**implementation notes.** 
- there's a progress bar on the top. i gave my best guess on %completed. this will def need another look at
- very much needs a content designer, content is only outlining important information users needed (eg definitions of terms, the purpose of specific forms, and what is expected of them)
- the link on people's names will take you to the manage report access section.

**Comment by melchoyce** [comment]
Looks great! Removing the design label and adding the engineering label for an engineering review.

**Comment by mogul** [comment]
@lauraherring what was the label we were going to use for tagging issues for review in the next design-eng sync...? This one looks like it needs it!

**Comment by lauraherring** [comment]
@mogul I thought we decided we were going to try for using the design/eng sync agenda first and reminding folks to add to that before we went with the extra label?

**Comment by jadudm** [comment]
This is essentially done. We're working on this in other tickets, and we will likely have more tickets in this space as we decide whether there is strict ordering or not. Closing as not planned.
