### ISSUE TITLE
As an auditor, I need to know which audit submissions are most urgent to work on.

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#537]
This issue covers the design of the default sort order for the table of records on the "my submissions" page. Currently it's ordered chronologically by report ID, but users think of the work more in terms of due dates / which report is coming due. 

### Acceptance criteria (We'll know we're done when...)

- [x] Example
  
### Tasks

- [x] Design
- [x] Peer review
- [x] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [ ] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
@tadhg-ohiggins Do you know if we get the audit due date attached to the UEI?

**Comment by tadhg-ohiggins** [comment]
We're certainly not getting it now. But if we have the organization's fiscal year end date, can we calculate their deadline from there? Am I right in thinking that the due date is connected to the organization's fiscal year dates?

**Comment by melchoyce** [comment]
Yup:
> The entity’s due date for an audit submission is the earlier of 1) 30 calendar days after receipt of the audit report, or 2) nine months after the end of the audit period (plus extension).

**Comment by tadhg-ohiggins** [comment]
So I think that we don't have access to when they receive the audit report, which would preclude us from figuring out when their deadline is, but maybe I'm forgetting somewhere that information is accessible.

**Comment by melchoyce** [comment]
Thanks, good to know. In that case, do you think fiscal year end date would be an okay proxy for displaying entries by urgency?

**Comment by tadhg-ohiggins** [comment]
My opinion is that it's not a good proxy, because it's potentially highly misleading depending on what information is available to the user. If their fiscal year end date is 31 October, and they get their audit report 01 March, we'd be suggesting a deadline that's six months later than their actual deadline. Those are hypothetical examples, but they don't seem wildly implausible, so I'm not sure we should use fiscal year end date in this way.

**Comment by melchoyce** [comment]
We chatted about this during our design sync today. Even though fiscal year isn't a good proxy for due date, since we don't have access to due date information, it might still be a good default to sort by.

We'll need a secondary column to organize by (since auditors can have multiple audits within the same fiscal year). Do we have access to report creation date? If not, we could potentially sort by report number instead? Would love to hear y'all's thoughts on this.

**Comment by MelissaBraxton** [comment]
My hunch is that secondarily sorting by status will be more useful to users in helping them determine which audit they should work on first.

**Comment by austinhernandez** [comment]
Ready for design review (@melchoyce @MelissaBraxton) and looking for opionions/thoughts.

**Rationale:**
I totally hear the need for multiple ways to filter, but in terms of first column, second column, third, etc. In reading from left to right I was thinking:  
-  **status / progress** [what needs my attention first]
    - I added a "percentage done" to the status column bc its a design pattern we are trying to incorporate on the report home page. Ostensibly, if that information is be collected there it can be displayed here.
- **entity name** [what is the thing that needs to be done]
- **Auditee UEI** [if there are a few entities with the same name, more clarification on the specific thing] 
- **report ID** [if there is already an auditee UEI giving more specificity to the entity name, do we need report ID, tambien?]
  - it didnt seem to resonate with any auditee, but I know it will be more useful for an auditor that may have many more open audit submissions, but does it even need to be on here if the UEI is providing clarifying entity info
  - i know there was a use case where an auditee created several of the same report as a draft, then would delete them, but we dont have delete functionality here anyway...
  - if we keep it, idk if report ID needs to be so long if its alphanumeric. if we keep it, can we take out some characters to shrink this column?
- **Fiscal period end date** [doesn't seem to be a good proxy for due date, but we don't have due date info. it also seems like they end around the same time? so this is really more of a question for auditors]
  - I added it at the end because even though it might be a valid way to sort things, it's not more important than status and would break up the distance between status and entity name which seemed a little confusing.
  - I also figured it could be like reading the P.S. or footer effect, first and last is read more than in-between
    
![image](https://user-images.githubusercontent.com/23194720/206561434-deaaf1ef-f997-4701-9e77-978dbd2d5177.png)

On figma: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5312%3A32084

**Comment by melchoyce** [comment]
I wonder if Mark would be the right person to ask about getting rid of the report ID? We could add that as a question to the next Census meeting?

Otherwise, LGTM 👍

**Comment by melchoyce** [comment]
@austinhernandez What needs to happen to wrap this up? Are we good to move it over to engineering review?

**Comment by mogul** [comment]
@austinhernandez based on what Mel said above, I'm thinking we should move this issue into the `Design Done` column for presentation in this week's sprint review meeting. Then following that meeting the issue would move into the `Engineering Backlog` column for that side of the team to take on/break down as they take ownership. What do you think?
