### ISSUE TITLE
As a user, I'd like to know what kinds of notifications will be triggered by my actions so that I can avoid sending duplicative emails. 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#538]
This issue covers the attention to how were contextualizing buttons that trigger an email notification. This came up in our research with auditees around the "certify" button on the certification page, but we should think about a consistent pattern that could be applied across all buttons that trigger notifications to provide a consistent experience for users and also save design/dev time. 

### Acceptance criteria (We'll know we're done when...)

- [ ] When users are made aware of when their action will trigger an automated email notification. 
  
### Tasks

- [ ] Design
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
Working on getting a list of email notifications the current Census system sends out.

**Comment by melchoyce** [comment]
Users receive emails when:
- A submission has been created
- A submission has both the form and pdf uploaded (STEPS 1 & 2 Complete) and ready for certification
- Submission has been certified by both auditee and auditor
- Submission complete - has been sent off for processing

**Comment by melchoyce** [comment]
On the Create New Audit > Access screen, we show a message before the submit button:

![Screen Shot 2022-11-15 at 10 32 06 AM](https://user-images.githubusercontent.com/2846578/201959721-c8a91bb6-942f-4ec7-9d73-5540b0039882.png)

I think we could carry this across the different pages that prompt a notification:

| Upload single audit report package | Finalize | Auditor Certification | Auditee Certification |
| ------------- | ------------- | ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/2846578/201960458-018ceecb-a5c3-48ed-b21f-7747ec5afa87.png) | ![image](https://user-images.githubusercontent.com/2846578/201967712-355519b3-1628-4bb7-bab1-fe16a8b499e5.png) | ![image](https://user-images.githubusercontent.com/2846578/201967812-9073d354-c7fa-41a4-937e-5bc4c8b7657e.png) | ![image](https://user-images.githubusercontent.com/2846578/201967844-8da9a99d-d60d-40a2-8329-5037d7bed1d8.png) |

We'd also want to add a message to the final step before submitting your audit, pending #536, but I think that should fit well into Austin's updated designs.

@MelissaBraxton @austinhernandez What do y'all think about this direction? Too subtle, or just clear enough?

**Comment by austinhernandez** [comment]
I think it seems clear to me! def. something to write up as something to test.

**Comment by melchoyce** [comment]
Great 👍 

Do you think we should put the notification for submitting a report on Report Home:

![image](https://user-images.githubusercontent.com/2846578/205384595-077ffb3c-1606-4ac6-80ff-5d32620efcd4.png)

Or in the submission modal?:

![image](https://user-images.githubusercontent.com/2846578/205384646-66644afb-8a0a-4a87-bf98-cd6d37004e34.png)

**Comment by austinhernandez** [comment]
good question... im wondering if these are all making sense as 2 different tickets as i just wrote something up on #550 thats similar. I think it both is fine. if you wanna just do 1, i would chose the modal.
