### ISSUE TITLE
As an auditor certifying official, I need a way to certify my audit

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#539]
This issue covers the design of the certification page for auditors. We've designed an auditee cert page, but auditors need one too!

### Acceptance criteria (We'll know we're done when...)

- [x] When we've designed a way for an auditor certifying official to certify their audit. 

![image](https://user-images.githubusercontent.com/2846578/198084275-9d392464-27f0-4efc-814f-a623cfddcb45.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5031%3A28048)
  
### Tasks

- [x] Design
- [x] Peer review
- [ ] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [x] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
Looks like the auditor certification step is just one screen of checkboxes:

![image](https://user-images.githubusercontent.com/2846578/197878727-75817ab2-e7e7-420e-9306-df3199d723bd.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5031%3A26952)

Pinging @MelissaBraxton for peer review.

**Comment by MelissaBraxton** [comment]
@melchoyce A few quick Qs: 

- Do we know if there's another page after this where they enter their name and role (a la the auditee flow)? If there is an additional "type your name to sign step" we might want to include the progress bar. What do you think? 
- Do we want to make this consistent w/ the auditee version wrt to the ability to download and view their SF-SAC and audit report one last time from this page?  
<img width="587" alt="Screen Shot 2022-10-25 at 3 10 08 PM" src="https://user-images.githubusercontent.com/20651166/197891824-e05f6c8c-f18e-4faf-a6de-f85432794baa.png">

**Comment by melchoyce** [comment]
> * Do we know if there's another page after this where they enter their name and role (a la the auditee flow)? If there is an additional "type your name to sign step" we might want to include the progress bar. What do you think?

There isn't, the Auditor flow only seems to have this one step.

> * Do we want to make this consistent w/ the auditee version wrt to the ability to download and view their SF-SAC and audit report one last time from this page?

Sure, I can add those back.

**Comment by melchoyce** [comment]
Updated: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5031%3A28048

**Comment by melchoyce** [comment]
Agreed. Do we have an issue for that yet?

**Comment by MelissaBraxton** [comment]
We do not!

**Comment by melchoyce** [comment]
Thanks, I'll go ahead and make one then 👍

**Comment by melchoyce** [comment]
Issue created: #550

**Comment by jadudm** [comment]
Closing and archiving as this work is being picked up in https://github.com/GSA-TTS/FAC/issues/970.
