### ISSUE TITLE
As a user on the manage access page, I need to understand what changing a user will do before I do it so that I don't accidentally change someone's access to the submission in a way I didn't intend. 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#540]
This issue covers  refinements to manage access page based on auditee user research. 

### Acceptance criteria (We'll know we're done when...)

- [ ] Example
  
### Tasks

- [ ] Design
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment]
Observations / what tripped people up: 
 - User questioned whether the report creator could also be the certifier. 
 - User expected to be able to go in and add a new certifying official
 - User didn't understand what the change user button would do

**Comment by austinhernandez** [comment]
I have 2 different versions that i've been working on that address the observations above. i'd love design feedback and review - @MelissaBraxton @melchoyce 



![Image](https://user-images.githubusercontent.com/23194720/199743708-2d3f4cb0-c47d-45f6-b6a6-1f904c59236f.png)

**Comment by melchoyce** [comment]
I like how the second version emphasizes the certifying officials, and also clarifies what to do about the report creator. It feels a little more clear to me than the left. I'd personally move forward with that version.

**Comment by austinhernandez** [comment]
I agree. I was worried the report creator message was a little heavy handed but I think it makes clear that they are unassigned and still have access(which could be a potential problem since there are no restrictions in who can do what). It just won't show this alert if they _are_ assigned!

![Image](https://user-images.githubusercontent.com/23194720/199761507-ae67235d-37e2-4bf4-a497-31bffa1b7fab.png)

I did add the pending invite pattern from the first mockup to the second mockup because there will be a delay between invite and acceptance and that wasnt captured anywhere. I need to do a few add/remove of interaction flows but this helps! thanks

**Comment by austinhernandez** [comment]
prototype / interactions linked here: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5086%3A28828

Implementation notes

- Warning banner: displays only when the person who created the audit submission did not assign themselves to a role. Clicking "revoke this user’s access" will take you to the remove user modal to confirm.
- “Designate a new ... certifying official” button opens the corresponding modal. You can only change the email address and will get errors if:
  - invalid email address (Error message only occurs when you try putting in an incorrect email address format (no @ or .domain, etc.))
  - email address required (Error message only occurs when you try submitting a blank form)
  - duplicate user (Error message only occurs when you try putting someone who is already associated with the submission) 


Auditee and auditor contacts section
- edit button opens corresponding modal where you can update email address or change the role from auditor to auditee contact
- remove button opens the remove user modal to confirm. 
- add new user opens corresponding modal where you enter someones email, confirm it, and then select a role.
- error states same as above (duplicate email, invalid email, no email) and additionally when no role selected.
- Invitation pending users show up in this section when someone is invited but has not yet accepted.  You can resend the invitation if it hasn't been uploaded OR you can cancel the invite

**Comment by austinhernandez** [comment]
**overview**
Addressed the needs of users brought up in last round of usability tests. this still needs testing, but i changed some of the text on the CTAs, and tried to make it more obvious what was required. i changed the interactions from the previous design, only allowing change of roles when editing a user. i also made a warning label if the submission creator is not listed as someone on the audit submission.

figma notes
addressed designer feedback and closed all of the comments from @melchoyce [on figma in the #540 page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4034%3A19388)

Added and linked the pages on the [ALL SCREENS](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5281%3A32558&t=FGKO9RfrVtRPRBjS-1) section of figma so people can see the interactions.

**Implementation notes**

- Warning banner: displays only when the person who created the audit submission did not assign themselves to a role. Clicking "revoke this user’s access" will take you to the remove user modal to confirm.
- “Designate a new ... certifying official” button opens the corresponding modal. You can only change the email address and will get errors if:
  - invalid email address (Error message only occurs when you try putting in an incorrect email address format (no @ or .domain, etc.))
  - email address required (Error message only occurs when you try submitting a blank form)
  - duplicate user (Error message only occurs when you try putting someone who is already associated with the submission) 


Auditee and auditor contacts section
- edit button opens corresponding modal where you can update email address or change the role from auditor to auditee contact
- remove button opens the remove user modal to confirm. 
- add new user opens corresponding modal where you enter someones email, confirm it, and then select a role.
- error states same as above (duplicate email, invalid email, no email) and additionally when no role selected.
- Invitation pending users show up in this section when someone is invited but has not yet accepted.  You can resend the invitation if it hasn't been uploaded OR you can cancel the invite

**Comment by pkigongo** [comment]
Note: we haven't done accessibility testing...yet

**Comment by jadudm** [comment]
Noting that we are likely collapsing the roles to "Editor" from "Auditee contact" and "Auditor contact." However, the word "Editor" is up for grabs as a role name.
