### ISSUE TITLE
Draft 18F > vendor onboarding plan + success scenarios

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#541]
### Background
Given that we will be welcoming a vendor to begin working alongside the 18F team soon, we want to make sure that we are ready to provide a smooth and easy onboarding experience for vendor designers and engineers and that the hybrid team is well prepared to work together! 

### Acceptance Criteria (We'll know we're done when...)
- [ ] We have a prioritized list of tasks that we want to accomplish before and after the vendor comes on board to ensure a smooth transition of the work from the 18F team to the vendor

### Tasks
- [x] Review the approach with the team
- [x] Review past example transition plans
- [x] Draft success scenarios, success metrics, and tasks
- [x] Prioritize success scenarios with the team
- [ ] Create new issues in GH for tasks that ladder up to success scenarios 
- [x] Create a new "transition" view in GH projects? 
- [x] Add the "transition" label to transition focused tasks

**Comment by MelissaBraxton** [comment]
- [Transition plan overview deck](https://docs.google.com/presentation/d/1SRwuggyA_MMnDouSiOVaZKVNz6H81pLXRpgCVV6VqsU/edit#slide=id.g5ecdbbee9e_0_0)
- [Open Forest example](https://docs.google.com/document/d/1JsGH_7OkDMZhi6xOW0xVeCkNO8aLgUTIUpRLlnsERxk/edit#heading=h.r6832jge8q7b)
- [Firewood permitting example](https://docs.google.com/document/d/1K2eHmXZM1BhIPF48yMn6e-oDuJ2gcOs2v9eRmLHzryo/edit#heading=h.r6832jge8q7b)
- [Grants and agreements example](https://docs.google.com/document/d/1YOlrpQXbbWwYcE-LYeqoavvMDolHjIgBmfQorp8Ft3c/edit#heading=h.r6832jge8q7b)

**Comment by MelissaBraxton** [comment]
This issue will likely lead to a few more issues that could be pulled in during the current sprint, if there's capacity.

**Comment by MelissaBraxton** [comment]
Draft success scenarios are [here.](https://app.mural.co/invitation/mural/gsa6/1667315905206?sender=melissabraxton2796&key=769de9b0-cabc-4d33-8462-5e0d7ed657de). We'll check w/ the team for the best way to get their input on the scenarios before moving on to success criteria and tasks.

**Comment by MelissaBraxton** [comment]
Team voted to provide feedback async and then we'll discuss at an upcoming co-work. Added to the agenda on 11/10.

**Comment by MelissaBraxton** [comment]
Hoping to wrap this up at our next co-working mtg scheduled for 12/1/22.

**Comment by MelissaBraxton** [comment]
Draft doc is [here](https://docs.google.com/document/d/1koQjxHSkIC76NHrtHA2WSFzGrcekIHeEjtwcAVm3s3k/edit#heading=h.r6832jge8q7b)

**Comment by pkigongo** [comment]
Previous blocked by the lack of a timeline for Vendor arrival/onboarding

**Comment by jadudm** [comment]
We're good.
