### ISSUE TITLE
Update design documentation in prep for vendor onboarding

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#542]
Breakout issue of <story>

### Acceptance Criteria (We'll know we're done when...)

- [x] When our design documentation is up to date
- [x] When a designer unfamiliar with the project can use our documentation to quickly get up to speed and start being productive

### Tasks

- [x] Update design onboarding doc
- [x] Update as-is WF model (melissa)
- [x] ~Update to-be WF model (melissa)~ Covered by #555 
- [x] Update user flow diagram?
- [x] ~Add wiki content re: how we integrate design research into agile sprints~ (this will be covered by our config mgmt plan)
- [x] ~Document how to get access to analytics dashboard~ (now covered under #526) 
- [x] Update story map (melissa)
- [x] A designer unfamiliar with the project completes a peer review
- [x] Refine documentation based on peer review feedback

**Comment by pkigongo** [comment]
NOTE: Leigh Cox, designer due to come onboard on 11/21/2022

**Comment by MelissaBraxton** [comment]
Based on our transition planning discussion today in which we chatted about how our configuration management plan should cover how we integrate design research into agile sprints, should we get rid of adding that documentation to the wiki as a task (currently task 5 above)? I don't want us to have to maintain the info in more than one place...  

@pkigongo and @mogul what do you think?

**Comment by MelissaBraxton** [comment]
I removed the task to document how to get access to an analytics dashboard and moved it to #526, since there'll be nothing to document until after #526 is completed.

**Comment by mogul** [comment]
> Based on our transition planning discussion today in which we chatted about how our configuration management plan should cover how we integrate design research into agile sprints, should we get rid of adding that documentation to the wiki as a task (currently task 5 above)? I don't want us to have to maintain the info in more than one place...
> 
> @pkigongo and @mogul what do you think?

I agree, that should be part of our CM plan doc. Typically such a doc covers what the columns on our boards represent and how cards move among them. It should definitely cover how we're now having design cards "loop back" for an implmentation pass. It can also extend "pre-board" to describe that design issues land on the board in the first place based on user research.

**Comment by MelissaBraxton** [comment]
One more Q - I had listed updating [this user flow diagram](https://app.mural.co/t/gsa6/m/gsa6/1656512586292/552d9adbc706e08386778f56d2ecbf2e55200175?sender=melissabraxton2796), which I don't believe has been updated since May. Given that the team hasn't seemed to miss it, I'm wondering whether we think updating it is a good use of time or if we're fine letting it fall by the wayside?

**Comment by melchoyce** [comment]
I don't think I'd ever seen the user flow diagram!

**Comment by austinhernandez** [comment]
ive def used it and it was helpful to build a mental modal of the entire application. i dont think it needs to be continuously updated, but maybe just here as a blueprint. i think we can sunset it, but def not continue adding to it.

**Comment by MelissaBraxton** [comment]
Moving to blocked as we await peer review, which may not happen until the week of 11/21.

**Comment by MelissaBraxton** [comment]
I think we can call this done!
