### ISSUE TITLE
Onboarding checklist for @pkigongo

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#544]
### Welcome to the team @pkigongo!

Here's a few pointers to get you started as well as a checklist to make sure you've got access to :all-the-things:!

**For you**
- [x] Review the [project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/) in drive
- [x] Join the Slack channels in the project README
- [x] Review our [process documentation](https://github.com/GSA-TTS/FAC#fac-documentation)
- [x] Get access to our GitHub repositories
  - [x] If you are NOT already a member of the [GSA](https://github.com/orgs/GSA/people) or [GSA-TTS](https://github.com/orgs/GSA-TTS/people) GitHub organizations, [follow the process outlined here](https://github.com/GSA/GitHub-Administration#joining-the-gsa-enterprise-organization), requesting access to the appropriate org(s). Include the Product Lead (see [the staffing list](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/edit#heading=h.us8xylqg455c)) on cc: for your email, and mention that you’re being added to the Federal Audit Clearinghouse project. (This may reduce back-and-forth as you’re being added to the GitHub orgs.) Note this step potentially takes a few days; there’s a person who does things in order for this to happen.
  - [x] Once you are added to the GSA-TTS org, ask the person(s) with the "Maintainer" role to add you to [the FAC-team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members). This will give you read/write access to our repositories.
- [ ] (designers) Review the [design onboarding document](https://docs.google.com/document/d/1EILl0nZr59T4PFJJMtFbmnQDJPksgzIFPuoFDN0bk0g/edit#heading=h.bhu3dgydlbvr)
- [ ] (engineers) Familiarize yourself with Python, Django, and Cloud.gov—all tools used in this project.
  - [ ] If you need to catch up on the latest in Python development, check out the [Python developer's guide](https://devguide.python.org/).
  - [ ] Work through the [Django Tutorial](https://docs.djangoproject.com/en/4.0/intro/tutorial01/) and writing your first Django app.
  - [ ] If you're not already, get [setup with Cloud.gov](https://cloud.gov/docs/getting-started/setup/)
  - [ ] Practice deploying a [python application](https://github.com/cloud-gov/cf-hello-worlds/tree/main/python-flask) to Cloud.gov using the Cloud.gov command line interface (CLI): https://cloud.gov/docs/getting-started/your-first-deploy/.
  - [ ] Survey existing TTS projects which use Django+Cloud.gov like: [Tock](https://github.com/18F/tock) and the [DOJ CRT Portal](https://github.com/usdoj-crt/crt-portal).
- [ ] (engineers) Get set up for [local development](https://github.com/GSA-TTS/FAC/blob/main/docs/development.md#local-development) so you can start contributing

@MelissaBraxton will be your onboarding buddy and will tackle the list below!

**For your onboarding buddy**
- [x] Add to [FAC-team@GSA.gov](https://groups.google.com/a/gsa.gov/g/fac-team) Google Group
- [x] Add to standing meeting invites (should happen automatically via addition to the Google Group membership)
- [ ] (engineers) Add to `gsa-10x-prototyping` Organization in cloud.gov
