### ISSUE TITLE
As a user, I need clear paths to specific kinds of resources from the homepage, so that I can get the info I need to proceed with my audit submission work.

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#549]
As a user, I need clear paths to specific kinds of resources (including troubleshooting, help for first-time users, and OMB guidance) from the homepage, so that I can get the info I need to proceed with my audit submission work.

Related to #458.

### Background

Arose during usability testing with auditees.

### Acceptance criteria (We'll know we're done when...)

- [ ] The homepage includes more explicit call-outs for resources to help users get started
  
### Tasks

- [x] Design
- [ ] Content review
- [ ] Design review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
Started thinking about this. Here's a first draft:

![image](https://user-images.githubusercontent.com/2846578/198091771-0461ade1-bac1-471b-9b1e-1c21674369fa.png)
[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5034%3A28311)

The resources linked are...

**New to FAC.gov?**
- [Get a UEI on Sam.gov](https://sam.gov/content/home)
- [Single audit checklist and instructions](https://facides.census.gov/Files/2022%20Checklist%20Instructions%20and%20Form.pdf) (Will need to be rewritten and hosted on FAC.gov)
- Read our FAQs (To be created on the FAC.gov website)
- [OMB 2022 Compliance Supplement ](https://www.whitehouse.gov/wp-content/uploads/2021/08/OMB-2021-Compliance-Supplement_Final_V2.pdf)

**Auditing resources**
- Validate my audit PDF (To be moved over to the new site as a page)
- Federal Cognizant Agency list (XLS) (File to be hosted on FAC.gov, found on FAC IDES > Specialized Reports)
- [Federal program contacts](https://facdissem.census.gov/Documents/AgencyContact.pdf)
- [Audit component examples](https://us.aicpa.org/interestareas/governmentalauditquality/resources/illustrativeauditorsreports#A4)
- [Accounting](https://www.aicpa.org/)

**Additional FAC.gov resources**
- Communities of practice (the [current FAC resources page](https://facweb.census.gov/Resources.aspx) links to several, but we've cut those from our draft—do we still need this and if so, what should it link to?)
- [Federal awards](https://sam.gov/content/assistance-listings)
- Data and research (the [current FAC resources page](https://facweb.census.gov/Resources.aspx) links to several, but we've cut those from our draft—do we still need this and if so, what should it link to?)
- [Policy](https://www.whitehouse.gov/omb/office-federal-financial-management/)
- Contact us (new FAC.gov contact page)

--- 

A few follow-up questions:
1. Are these the right resources to provide from the homepage?
2. If not, what resources should we link to?
3. Which resources should be removed?
4. Should any of these resources be summarized on the homepage as their own section?
5. Should we write any new resources to help users?

**Comment by melchoyce** [comment]
Punting to post-MVP.

**Comment by jadudm** [comment]
Closing as this is work in-flight elsewhere; the work is tracked (currently) in a GSheet, and needs to be brought into its own epic.
