### ISSUE TITLE
Conduct sprint 1 tests sessions

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#55]
**Background**

**We'll know we're done when...**
- [ ] We've conducted test sessions w/ 6-8 auditors.
- [ ] We've documented our sessions via notes in shared drive
- [ ] recordings are stored in PII folder

**Tasks**
- [ ] 
- [ ]
