### ISSUE TITLE
As a user, I'd like to be able to control what notifications I receive from the FAC

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#552]
Breakout issue of #538

### Background

Came up in [Slack](https://gsa-tts.slack.com/archives/C1L58R804/p1666882628623139?thread_ts=1666798568.717959&cid=C1L58R804):

> I do believe our users would like some flexibility to control which notifications they receive and which notifications they can opt out of receiving.

### Acceptance criteria (We'll know we're done when...)

- [ ] Users have a way to control what notifications they receive
  
### Tasks

- [ ] Design
- [ ] Write UI copy
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by jadudm** [comment]
If there is a way to opt out of some notifications, it will be post-MVP.

**Comment by danswick** [comment]
👉 https://github.com/GSA-TTS/FAC/issues/1401
