### ISSUE TITLE
Model workflows in BPMN

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#555]
### Background

In order to document the expected process explicitly and potentially enable a back-end service to handle state for individual submissions, we want to document the to-be workflow in BPMN.

### Acceptance Criteria (We'll know we're done when...)

- [ ] There's a BPMN description of the to-be workflow in the `GSA-TTS/FAC` repository.
- [ ] The BPMN description should load up in bpmn.io (and Camunda Modeler) without errors.
- [ ] The BPMN deploys without issues from Camunda Modeler to Camunda Operate

### Tasks

- [x] Get to know the Camunda Modeler
- [x] Try to model a piece of our to-be workflow
- [x] Verify that we can export and import the model as a BPMN file
- [x] Verify that we can deploy the model to Camunda Operate without problems
- [ ] Commit the BPMN file to version control
- [ ] Repeat the steps above for each of the other sections of our workflow

**Comment by MelissaBraxton** [comment]
@mogul I've gotten started on a model of the new submission process in Camunda. I think you'll be able to access it via [this link!](https://modeler.cloud.camunda.io/share/7e4e739b-89e0-46cc-b497-26fbcf96a60a) I've put some time on the calendar next week to check in before I invest more time here.

**Comment by MelissaBraxton** [comment]
Schema links: 
[SAC model](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/models.py#L46)
[Backend JSON](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/sections/FederalAwards.schema.json)

As we build out the model(s) and data flow, we'll want variable names in the model to be consistent w/ our schema.

**Comment by mogul** [comment]
Melissa has [modeled a small piece of our workflow in Camunda](https://modeler.cloud.camunda.io/share/22d7b26b-13a1-4459-ae30-f3dc73dc3632) but we're having a problem getting it to deploy. We've [posted the Camunda forum](https://forum.camunda.io/t/unable-to-deploy-model-from-modeler-saxexception-while-parsing-input-stream/41307) to try to get some help. I'm moving this issue to `Blocked` with a plan to resume our debugging efforts Monday if no one has replied by then.

**Comment by MelissaBraxton** [comment]
This is no longer blocked. I plan to devote Monday to modeling the data entry, certification, and submission flows.

**Comment by MelissaBraxton** [comment]
@mogul and @JeanMarie-TTS  - How would you like me to save the models for reference? I can download the xml files and put them in GH somewhere if you like?

**Comment by JeanMarie-TTS** [comment]
We should save the xml version in GitHub. I believe there are different tools to view and edit BPMN files.
