### ISSUE TITLE
[research:5d] Investigate XRBL/GRIP as viable submission/reporting model/schema/validation option

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#561]
### Background

The GREAT Act puts a requirement on the FAC to use a consensus-developed standard for submission and reporting. 

We want to know if the GRIP taxonomy put forward by XBRL.us fits our needs technically/operationally.

We don't want to spend more than five days on this.

### Acceptance criteria (We'll know we're done when...)

- [ ] We can definitively say whether use of XBRL/GRIP and related tooling is worth pursuing in the near or far term.
  
### Tasks

- [ ] Research materials provided by XBRL.us
- [ ] Research tooling provided by XBRL.us
  - [ ] Can we generate XRBL/GRIP SA content from Excel?
  - [ ] Can we validate XRBL/GRIP SA content in Excel, in our front-end, in our API, and in our backend?
  - [ ] Can we use XBRL/GRIP to validate on the backend instead of JSON Schema?

**Comment by jadudm** [comment]
This is being discussed, but is a substantial change management challenge.

We know we can intake workbooks and transform them to other formats. We know we can generate workbooks from textual representations. 

We will drive spike explorations in partnership with auditors, Federal partners, and others. This is not on the short-term roadmap, and is something we might come back to in calendar 2024.
