### ISSUE TITLE
Move templates/CSS/content from FAC-Frontend to Django

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#564]
Breakout issue of #556

### Background

We need to move the CSS over from the frontend and figure out how to structure templates with reusable components. Ideally we can port or convert from nunjuks to the Django templating language.

This includes moving content currently stored in YAML in the frontend over and determining how to store it in the Django application.

### Acceptance Criteria (We'll know we're done when...)

- [x]   We’ve moved the static CSS over (there will be a separate issue to develop the SASS pipeline we need to generate CSS later).
- [x]   We have working basic templates and components.
- [x]   We have some approach to storing/retrieving content (the content that’s currently in YAML in FAC-Frontend).
- [x]   No new CSS or JavaScript has been written, as that needs to be covered by the new SASS build pipeline.

### Tasks

- [x]   Stand up new Django app for content management.
- [x]   Setting up the templates and components.
- [x]   Moving the CSS over as-is (SASS pipeline is a separate issue).

**Comment by heymatthenry** [comment]
@tadhg-ohiggins @LindsayYoung Do y'all think that implementing the CMS piece, which Lindsay has done, counts as "some approach to storing/retrieving content?" for AC purposes? I feel like it does.

**Comment by LindsayYoung** [comment]
Just seeing this now, I think what we have makes sense for a first pass!

**Comment by heymatthenry** [comment]
Barebones approach to getting content into the database is covered in #709, so I'm checking that last box and closing this one.
