### ISSUE TITLE
Create SASS pipeline for unified Django application

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#565]
Breakout issue of #556

### Background

The static frontend used Node to generate the CSS; we need to have an equivalent build pipeline for the unified Django application.

### Acceptance Criteria (We'll know we're done when...)

- [x]   We have a SASS build pipeline that supports USWDS and our CSS/JS generation needs.

### Tasks

- [x]   Create the build pipeline.
- [x]   Integrate the build pipeline into our CI/CD process.

**Comment by heymatthenry** [comment]
Implemented in #620
