### ISSUE TITLE
SonarLint appeasement

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#567]
### Background

Via @JeanMarie-TTS, SonarLint picked up some issues in `backend/audit/models.py` that should be relatively easy to clean up.

Raw dump here:

```json
[{
	"resource": "/Users/jeanmariepmariadasso/FAC/backend/audit/models.py",
	"owner": "sonarlint",
	"code": "python:S1845",
	"severity": 4,
	"message": "Rename field \"audit_type\" to prevent any misunderstanding/clash with field \"AUDIT_TYPE\" defined on line 60 [+1 location]",
	"source": "sonarlint",
	"startLineNumber": 93,
	"startColumn": 5,
	"endLineNumber": 93,
	"endColumn": 15
},{
	"resource": "/Users/jeanmariepmariadasso/FAC/backend/audit/models.py",
	"owner": "sonarlint",
	"code": "python:S1845",
	"severity": 4,
	"message": "Rename field \"user_provided_organization_type\" to prevent any misunderstanding/clash with field \"USER_PROVIDED_ORGANIZATION_TYPE\" defined on line 50 [+1 location]",
	"source": "sonarlint",
	"startLineNumber": 146,
	"startColumn": 5,
	"endLineNumber": 146,
	"endColumn": 36
},{
	"resource": "/Users/jeanmariepmariadasso/FAC/backend/audit/models.py",
	"owner": "sonarlint",
	"code": "python:S1481",
	"severity": 2,
	"message": "Remove the unused local variable \"i\".",
	"source": "sonarlint",
	"startLineNumber": 38,
	"startColumn": 45,
	"endLineNumber": 38,
	"endColumn": 46
}]
```

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We’ve made the above tweaks.

### Tasks

- [ ]   `USER_PROVIDED_ORGANIZATION_TYPE` -> `USER_PROVIDED_ORGANIZATION_TYPES`.
- [ ]   `AUDIT_TYPE` -> `AUDIT_TYPES`
- [ ]   `i` -> `_`
