### ISSUE TITLE
Update Login.gov integration for unified Django application

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#568]
Breakout issue of #556

### Background
The current LoginGov integration follows the PKCE flow and is driven primarily by the static FAC-Frontend site. Moving to a more traditional server-rendered Django application will require us to use a different [OpenID Connect flow](https://developers.login.gov/oidc/#choosing-an-authentication-method) (specifically `private_key_jwt`). With this flow, the server is involved in the initial authentication exchange with LoginGov and session creation. This should obviate the need for the [current token-based API authentication](https://github.com/GSA-TTS/FAC/blob/main/backend/users/auth.py) in favor of [session authentication](https://www.django-rest-framework.org/api-guide/authentication/#sessionauthentication).

### Acceptance Criteria (We'll know we're done when...)

- [x] Our Login.gov configuration has been updated to use the `private_key_jwt` flow
- [x] Login/Logout functionality works as before (nothing about the authentication experience should appear different to end-users) 

### Tasks

- [x] Update LoginGov configuration to  use `private_key_jwt` flow
- [x] Remove `ExpiringTokenAuthentication` backend + references
- [x] Remove `JwtUpsertAuthentication` backend + references
- [x] Remove `djangorestframework-simplejwt` dependency + references
- [x] Select and incorporate an OIDC authentication backend to manage the authentication flow with LoginGov (`mozilla-django-oidc` is one option)
- [ ] Revisit #320 and document any outstanding edge cases related to LoginGov users and Access
