### ISSUE TITLE
Update Notes to SEFA page to support data entry

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#570]
This issue covers the design of the Notes to SEFA page within the SF-SAC form.

When our deadline was originally October, we looked for ways to simplify the MVP. One of the suggestions was to remove the Notes to SEFA page. With our deadline now stretching an extra year, we have time to implement this page in its entirety, and Census suggests we do so.

See #326 and #406 for more history.

### Acceptance criteria (We'll know we're done when...)

- [x] The Notes to SEFA page allows data entry
  
### Tasks

- [x] Design
- [x] Peer review
- [ ] Copy review
- [x] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [x] Interaction are documented if they deviate from USWDS components
- [x] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
## Design

I've taken a pass on including a web form on the Notes to SEFA page. I tried to keep it as simple and streamlined as possible.

![image](https://user-images.githubusercontent.com/2846578/206294932-5bece853-d2c5-40c2-a679-99e7434fec9c.png)
### [WIP Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5311%3A33156&t=cUukfvlHay8NGXsw-4)

I've also explored how the page would work when your first additional note is automatically generated by the FAC:

https://user-images.githubusercontent.com/2846578/206291903-107b7245-b14a-4e56-978e-e9c828b5b084.mp4

## Implementation notes

- The text fields are wider than average on this page, taking up the entirety of the page content grid. Since these notes get fairly lengthy, and are largely copied and pasted from the PDF report, I wasn't as concerned about line-length. I'd rather take up some extra horizontal space than vertical space, because the page can get quite lengthy.
- If you have an additional note auto-generated by the FAC, a link that opens a modal with an explanation is shown. This link isn't shown if you don't have any auto-generated notes.
- "Add another note" creates a new note title and content field below the first note. If someone adds a bunch of notes and leaves them blank, we should discard those on save.
- One thing I _haven't_ accounted for is deleting additional notes, because I'm thinking we can just automatically delete empty notes. So to get rid of a note, someone would just remove the content from the note. **I'd love a gut check on this.**
- I've excluded the "Note 1" "Note 2" etc. labels because they seemed superfluous, and also don't end up matching the audit report in the long run; for example, a note could be 4 in the FAC website, but 7 in the audit report (and each audit report is formatted differently). 
- I've kept the character count ([see this conversation for details](https://gsa-tts.slack.com/archives/C1L58R804/p1670284136760849)), but totally open to discussing this more.

Tagging @austinhernandez and @leighdiddy for peer review.

**Comment by austinhernandez** [comment]
looks good to me! great documentation!

**Comment by melchoyce** [comment]
Thanks! Moving this over into engineering review.

**Comment by jadudm** [comment]
This is picked up in #1279 via conversion to XLSX workbook. Closing as not planned.
