### ISSUE TITLE
Update Secondary Auditors page to support data entry

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#571]
This issue covers the design of the Secondary Auditors page within the SF-SAC form.

When our deadline was originally October, we looked for ways to simplify the MVP. One of the suggestions was to remove the Secondary Auditors page. With our deadline now stretching an extra year, we have time to implement this page in its entirety, and Census suggests we do so.

See #326 for more history.

### Acceptance criteria (We'll know we're done when...)

- [x] The Secondary Auditors page allows data entry
  
### Tasks

- [x] Design
- [x] Peer review
- [x] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [x] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment]
I'm good with that!

**Comment by melchoyce** [comment]
Great! Added this to our All Screens page: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5200%3A30488&t=ZtSXqJAaDEZOlmbU-4

No additional implementation notes, since it matches all of the other worksheet pages.

**Comment by jadudm** [comment]
Closing this, as #940 is picking up this kind of work via Jsonnet definitions. Provided a link back to this ticket from there.
