### ISSUE TITLE
Style email notifications

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#572]
Related to #538 and #550.

This issue covers the design of FAC notification emails.

### Background

The current FAC emails are unstyled:

![image](https://user-images.githubusercontent.com/2846578/199544485-0d186823-edaa-4581-b58a-f0bdff64e9d4.png)

It would be nice to create a branded email template to go along with the new site.

### Acceptance criteria (We'll know we're done when...)

- [x] We have a template that works for all the various notification emails from the FAC
  
### Tasks

- [x] Design
- [x] Peer review
- [ ] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [x] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by austinhernandez** [comment]
What do you think about something along the lines of "unsubscribe." Maybe some kind of option to request to be removed in case they left the project or get a million of these alerts during a busy season?

**Comment by melchoyce** [comment]
I think that makes sense—would tie into #552.

**Comment by austinhernandez** [comment]
I know the content needs work, but just a few questions:

- I also think the report ID was something auditees weren't familiar with. Maybe UEI instead? 
- UX-wise, the instructions are clear, but would direct links solve this problem? So instead of 1 go to FAC, 2 log in,  etc... its [header]"**It's time the certifying auditee to certify DC kitchen**... [sign in to view this report](#)" and have it take you directly to the report page. maybe add text below like "not the certifying auditee? manage user permissions here"
  - Maybe thats and engineering nightmare and the instructions are better. 
- Visually idk if GSA needs to be so big as users of the FAC didnt seem to notice/care about census vs GSA. Maybe thats smaller footer information with the contact, privacy info, and unsubscribe stuff.

**Comment by melchoyce** [comment]
With existing content (which will still need to get edited):

![image](https://user-images.githubusercontent.com/2846578/204911353-7de7e164-4402-445c-a86d-30e3b2f40075.png)

With simplified content: 

![image](https://user-images.githubusercontent.com/2846578/204911386-6795517d-2a9c-4f6c-9c63-5dea07f314e2.png)

@austinhernandez Let me know if you have any additional feedback based on these concepts!

**Comment by melchoyce** [comment]
## Figma Mocks

https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5188%3A30155

## Implementation Notes

We have two mockups: one using (mostly) the existing text, just updated for the new FAC website, and a second one that's simplified and more direct. If possible, we'd like to go with the second email option. If it's not possible to link directly to submissions, we can go for the first option.

**Comment by mogul** [comment]
@Leighdiddy @thebestsophist I noticed this is languishing in the `Engineering Review Needed` column... Is that the right place for this, given Mel's no longer assigned and it doesn't look like it's awaiting any particular review from outside the design sub-team? Does more design work need to be done (meaning moving it back to `Design in progress`)? Or should it be moving forward into the `Engineering Backlog`?

**Comment by mogul** [comment]
> Or should it be moving forward into the Engineering Backlog?

Or really, following our current process: I suggest we move this to `Design Done` for presentation in this week's sprint review. Following that meeting, it would move to the `Engineering Backlog` for that side of the team to take ownership and break-down going forward.

**Comment by mogul** [comment]
(I moved it, because it was bugging me where it was! 🤓)

**Comment by danswick** [comment]
consolidating to https://github.com/GSA-TTS/FAC/issues/1401
