### ISSUE TITLE
Review Shelley's community change spreadsheet

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#578]
This is related to #548.

### Background

[This Google Doc](https://docs.google.com/spreadsheets/d/1E02vTfTWR3icY-v57-CaD_Jfr0deP2T9/edit#gid=892644454) is a list of suggestions for changes to the SF-SAC. These were collected from the user community by Shelley; this task is for review of the proposed changes.

### Acceptance Criteria (We'll know we're done when...)

- [x] The reviewers have gone through the changes.
- [x] We have consensus on a decision for each (won’t do for MVP/won’t consider/consider at some future date).

### Tasks

- [x]   Add `18F Review` column to spreadsheet.
- [x]    Each reviewer reviews each of the changes.

**Comment by tadhg-ohiggins** [comment]
I went through the rows and left a comment on each.
