### ISSUE TITLE
Move accounts to OROS cloud.gov org

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#579]
### Background
We need to move to spaces under the OROS organization in cloud.gov.

### Acceptance Criteria (We'll know we're done when...)

- [x] We have a documented process for granting and revoking access to the OROS cloud.gov spaces as part of on-boarding/off-boarding (and we’ve updated our on-boarding and off-boarding docs to reflect this).
- [x] We have org managers assigned to the org as described in the new documentation.
- [x] We’ve used that process to grant appropriate access to all team members.

### Tasks

- [x] #582
- [x] #583 
- [x] #584
