### ISSUE TITLE
Data dissemination discovery sprint: Agency users 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#58]
**Background**
We want to better understand the experience of agency audit resolution officials (how they use single audit data, how they resolve single audits, what their needs are, etc) so that we can ensure that the new FAC meets their needs.  

**We'll know we're done when...**
- [ ] We have the data we need in order to accurately represent agency users' single audit service experience (service blueprint).

**Tasks**
- [ ] Draft research plan
- [ ] Recruit users (dependent on #64) 
- [ ] Develop interview protocol
- [ ] Develop notes and debrief template
- [ ] Conduct interviews and observations
