### ISSUE TITLE
Move to GitFlow documentation

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#580]
### Background
We will need a change control process for our ATO and a way for more formalized review as the project matures.

GitFlow is a common approach to keep up the speed of the development branch. That is helps keep PRs small and manageable. Staging releases allow for a stable branch to preview so that stakeholders and people who are providing the relevant quality checks can review the release. Then, the main branch can be deployed to Prod. 

This ticket will result in documentation that will guide the implementation steps:

### Acceptance Criteria (We'll know we're done when...)

- [ ] Add a `branching.md` document to the documentation that outlines:
    - Naming conventions
    - The mechanics of when a branch is deployed
    - What the responsibility of different roles is to merge
    - The permissions of who can merge
    - Proposed timeline and how that fits into the sprint
    - Hotfix procedure with bug triage guidance

### Tasks

- [ ] Create `branching.md` document 
- [ ] Update any other part of the documentation that needs an update

**Comment by mogul** [comment]
I'm curious why there's a `dev` branch rather than that just being `main`. All the tests are supposed to pass prior to a PR merging...

**Comment by mogul** [comment]
Also you might want to highlight that the release is triggered by actually applying a release tag to `main`.

**Comment by tadhg-ohiggins** [comment]
I'm not attached to having a `staging` branch; that diagram reflects a first draft based on what I understood from our dev huddle discussion.

**Comment by tadhg-ohiggins** [comment]
Similarly I'm not attached to having a `dev` branch either, if we're in practice going to be pushing releases via release tags.

**Comment by JeanMarie-TTS** [comment]
Here is a good tutorial that explains the use of two main branches, `dev` and `main`, to manafe feature development, hot fixes, release tagging, etc. https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by mogul** [comment]
As it says in that article (emphasis mine):
> Gitflow is a **legacy Git workflow** that was originally a disruptive and novel strategy for managing Git branches. Gitflow has fallen in popularity in favor of [trunk-based workflows](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development), which are now considered best practices for modern continuous software development and [DevOps](https://www.atlassian.com/devops/what-is-devops) practices. Gitflow also can be challenging to use with [CI/CD](https://www.atlassian.com/continuous-delivery). This post details Gitflow for historical purposes.**

I really recommend reading this series of articles about GitFlow vs trunk-based development:
https://www.endoflineblog.com/gitflow-considered-harmful

The fourth article in particular (written in 2021) describes exactly the practice I've seen used in other TTS teams:
https://www.endoflineblog.com/implementing-oneflow-on-github-bitbucket-and-gitlab

...though it leaves out that GitHub now even has a drop-down in the Pull Request UI to choose which merge strategy you want to use, which makes this even easier, since you won't be using the command-line to do the merge itself.

I figured if our intent is "make sure merged stuff is always demoable, release to stg in a controlled fashion at specific points, promote to prod when people say OK", then we can achieve that pretty easily without incorporating the cumbersome side-effects using GitFlow.

**Comment by JeanMarie-TTS** [comment]
The OneFlow article talks about a **variant**, which addresses the need I expressed regarding short-lived hotfix branches. This variant has two eternal branches, and we can call them whatever we want  - `develop` and `main`, or `main` and `release`. `develop` has the entire history and the article talks about best practices to record this history.

**Comment by LindsayYoung** [comment]
graph TD
    A[branch 1] --> PA
    B[branch 2] --> PA
    C[branch 3] --> PA
    PA( code review & automated tests) --> BA[main]
    BA --> EA{fac-dev}
    BA --> PB(release review & automated tests)
    PB --> BB[branch prod]
    BB --> EB{fac-staging}
    BB --> PC(stakeholder review & automated tests)
    PC --> BC[version tag on prod branch]
    BC --> EC{fac-prod}
```
