### ISSUE TITLE
Develop processes for adding and removing access (we need those for ATO)

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#583]
Breakout issue of [#579](https://github.com/GSA-TTS/FAC/issues/579)

### Background
We need to have well-defined, well-documented processes for controlling access to the OROS FAC cloud.gov spaces.

### Acceptance Criteria (We'll know we're done when...)

- [x]   We know who’s responsible for maintaining access administration for these spaces.
- [x]   We know who to go to if there’s some issue with the current administrator(s) or their access.
- [x]   We have documentation on who should have access, how to get access, how to remove access, and how often those things are reviewed (and/or what events might also trigger review).
- [x]   We’ve updated our on-boarding and off-boarding documentation to reflect the above.

### Tasks

- [x]   Identify whoever has current administrative rights.
- [x]   Identify who should have administrative rights.
- [x]   Address “who administrates the administrators?” question?
- [x]   Identify backup personnel for administration.
- [x]   Determine cadence for periodically reviewing who has administrative rights and who is listed as backup(s).
- [x]   Determine what events trigger access review and who’s responsible for doing that review.
- [x]   Document all of the above for ATO purposes.
- [x]   Update on-boarding and off-boarding documentation accordingly.

**Comment by tadhg-ohiggins** [comment]
2022-12-14 currently blocked on deployment/terraform PRs.

**Comment by mogul** [comment]
@tadhg-ohiggins are you okay with closing this one without breaking the last checkbox out? (I though about adding a GitHub action that creates an issue, and assigns it to the fac-admins, but really I can just put a reminder in the calendar too...)

**Comment by mogul** [comment]
_ping_ @tadhg-ohiggins ...

**Comment by tadhg-ohiggins** [comment]
@mogul If there's a calendar reminder then I think that qualifies as closing the item for **Determine cadence for periodically reviewing who has administrative rights and who is listed as backup(s).**

**Comment by mogul** [comment]
Done. 
![image](https://user-images.githubusercontent.com/47762/222645658-beb7968a-2c8f-4af6-978b-58a20007b2af.png)
