### ISSUE TITLE
Grant team access to OROS cloud.gov spaces

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#584]
Breakout issue of [#579](https://github.com/GSA-TTS/FAC/issues/579)

### Background
After [#583](https://github.com/GSA-TTS/FAC/issues/583) is done, we need to use the processes it defines to actually grant the required access to team members

This should be done by someone with the administrative rights to do it…

### Acceptance Criteria (We'll know we're done when...)

- [x]   All team members who need admin access have it.
- [x]   All team members who need developer access have it.

### Tasks

- [x]   Grant appropriate access to all team members.
