### ISSUE TITLE
Move dev team to git-workflow process

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#585]
Breakout issue of [#579](https://github.com/GSA-TTS/FAC/issues/579)

### Background

The team agreed to move to git-flow at the [2022-11-02 dev huddle](https://docs.google.com/document/d/1LoHhx0dxS3wCvSSKE_d033b5RcN_PLKVFjkkrLzUnMg/edit#heading=h.3ztycbhxzjki); now we need to actually switch over. We’re doing that as part of the move to the OROS cloud.gov spaces.

The rationale for this is that Gitflow provides some additional guardrails that it will be useful to have while we’re on-boarding a vendor team.

The current plan for this is:

#### Use `fac-dev` for ongoing work

Whichever branch we’re using for development work will involve CI/CD processes that push to `fac-dev` on any commit/merge.

#### Release to `fac-staging` about once per sprint

Work in the development branch would get gathered into releases that would go into the primary branch and be pushed to `fac-staging`.

#### Release to `fac-prod` on some to-be-determined cadence

Stakeholders would review on `fac-staging` and after that review we would push to a production branch that would be pushed to `fac-prod`.

#### Overview diagram
The process would look something like this:

```mermaid
graph TD
    A[feature branch 1] --> PA
    B[feature branch 2] --> PA
    C[feature branch 3] --> PA
    PA(automated checks & code review) --> BA[develop]
    BA --> EA{fac-dev}
    BA --> PB(release review)
    PB --> BB[main]
    BB --> EB{fac-staging}
    BB --> PC(stakeholder review)
    PC --> BC[release]
    BC --> EC{fac-prod}
```

### Acceptance Criteria (We'll know we're done when...)

- [ ]   This issue has been vetted/edited/rewritten to reflect consensus on this approach
- [ ]   Our CI/CD processes are set up for each branch/space.
- [ ]   We’ve documented the review processes for releasing to `fac-staging` and `fac-prod`

### Tasks

- [ ]   Refine this issue to reflect consensus.
- [ ]   Implement CI/CD processes for `fac-dev`.
- [ ]   Implement CI/CD processes for `fac-stage`.
- [ ]   Implement CI/CD processes for `fac-prod`.
- [ ]   Document the above processes.
