### ISSUE TITLE
[spike:5d] Validate Excel content by calling an API

### ISSUE THREAD

**Issue by pkigongo** [GSA-TTS/FAC#589]
### Background

We need to see how difficult/awkward it is to use external API calls from within Excel to do either/both of:

*   Validation of fields.
*   Validation of cross-field relationships.
*   Population of drop-down lists.

We want to spend no more than five days of developer time on this task

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We know how hard it is to do field validation.
- [ ]   We know how hard it is to do cross-field validation.
- [ ]   We know how hard it is to do drop-down list population.

### Tasks

- [ ]   Investigate various paths for doing the external calls.
- [ ]   Get an external call working as a demo. See [this Arelle snippet](https://arelle.org/arelle/documentation/api-web-services/#:~:text=EntityIdentifier%2C%E2%80%8BPeriod%2CDimensions-,Excel%20interface,-GUI%20operation%3A) for starters.
- [ ]   Estimate time/difficulty for each of the acceptance criteria.

**Comment by timoballard** [comment]
FYSA @tadhg-ohiggins @mogul @JeanMarie-TTS 

API-based validation of submission data in Excel can be accomplished with the Office Scripts offering. This feature allows custom scripts to be written in Javascript. An example script is shown in the screenshot below which demonstrates a proof-of-concept validation call to a local instance of the FAC API.

Office Scripts appear to only be available as part of the Office 365 offering, so this validation feature would likely be unavailable to at least some of the FAC user base.

Excel also has VBA scripting capabilities, which have more backward compatibility than Office Scripts. However, according to the [official documentation](https://learn.microsoft.com/en-us/office/dev/scripts/resources/vba-differences#platform-and-ecosystem), they “have no convenient way to call out to the internet”, which all but eliminates this as an option for API validation.

There is no indication that ExcelJS (or OpenPyXL) offer any support for interacting with Office Scripts. Therefore, if we pursue this approach to validation, we are not likely to be able to fully generate the Excel template.

I would put the level of effort at medium/large to implement an Office Script which calls out to an API to validate the entered data and report any errors inline.


![Image](https://user-images.githubusercontent.com/1425377/213792044-385db1c3-8975-42ae-9836-f58f4da5d882.png)

**Comment by mogul** [comment]
> Excel also has VBA scripting capabilities, which have more backward compatibility than Office Scripts. However, according to the [official documentation](https://learn.microsoft.com/en-us/office/dev/scripts/resources/vba-differences#platform-and-ecosystem), they “have no convenient way to call out to the internet”, which all but eliminates this as an option for API validation.

I think this undersells what VBA can do. I'm not terribly familiar with VBA myself, but the [Arelle REST API documentation](https://arelle.org/arelle/documentation/api-web-services/#:~:text=Import%20Data%20dialog.-,VBA%20macro,-%3A) drops some breadcrumbs:

- This example relies on the use of [QueryTables](https://learn.microsoft.com/en-us/office/vba/api/excel.querytable), which as I understand it is a long-standing Excel feature though it may be fairly static, in terms of when it is invoked. 
- However at a simpler level, it makes use of [Connection](https://learn.microsoft.com/en-us/office/vba/api/excel.workbookconnection), which seems more generally to do what we want, and has a [Refresh()](https://learn.microsoft.com/en-us/office/vba/api/excel.workbookconnection.refresh) method.

**Comment by timoballard** [comment]
Yeah I'm possibly selling it a bit short, although everything I managed to find was about essentially importing "table-like" data from the web (which is what that arelle example appears to be doing). I couldn't find any documentation or examples of what (I think) we'd need to do, which is to POST data from the spreadsheet to our API for validation

**Comment by mogul** [comment]
Right, submitting data from the current sheet for validation would be difficult!
