### ISSUE TITLE
Create risk tracker

### ISSUE THREAD

**Issue by pkigongo** [GSA-TTS/FAC#593]
Breakout issue of <story>

### Background
During a co-working discussion on 11/17/22, the team realized that we need to formalize our risk tracking going forward. We'll need to create a new risk tracker, document how it's to be maintained, assign someone to regularly maintain it.

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] Select a template for risk tracking
- [ ] Document a practice for maintenance of that risk tracker
- [ ] Determine who will maintain it

- [ ] 
- [ ]

**Comment by jadudm** [comment]
We... do not have a formal risk tracker. We also discuss risk as an ongoing part of our agile process, and document it in our story templates. So, this is covered for all intents and purposes as we approach MVP.
