### ISSUE TITLE
Onboard Abby

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#60]
**Background**

**We'll know we're done when...**
- [x] Abby has access to all tools and context they need to start picking up some initial work 

**Tasks**
- [x] Add Abby to GH team
- [x] Add Abby to 10x-federal-audit-clearinghouse
- [x] Add Abby  to our Gdrive
- [x] Add Abby to all relevant meetings
