### ISSUE TITLE
Compile human centered design training for incoming FAC/Census staff

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#603]
### Background

Based on discussion during our coworking session on 11/17, PO (and other relevant FAC/Census staff) should attend 18F product human centered design training.

### Acceptance Criteria (We'll know we're done when...)

- [ ] We have a slide deck explaining the basics of HCD we can use to train incoming staff
- [ ] Our deck includes how we incorporate HCD into our agile sprints

### Tasks

- [ ] Find an existing 18F HCD deck we can start working from
- [ ] Update content to fit the FAC
- [ ] Peer review

**Comment by melchoyce** [comment]
Some past decks we've used at 18F:
- https://docs.google.com/presentation/d/1BdI1qSSOuv3V7BK8psSMVwrib2XXj3dw1spvA_IHb1k/edit?usp=sharing
- https://docs.google.com/presentation/d/1ec8aICKcHpJVKTnEts3XAAE4S03IId8VOncUC_PuUWE/edit#slide=id.g14785ec7c0e_1_0
- https://docs.google.com/presentation/d/1Ho0iFJUzxaE8M6__6eTGoDBfAANDAkQH-bQChraAk_Q/edit#slide=id.g5ecdbbee9e_0_0

**Comment by jadudm** [comment]
We have colleagues on the team with this expertise. Closing as not planned.
