### ISSUE TITLE
Re-use CISA login.gov OIDC for FAC

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#607]
Breakout issue of [#568](https://github.com/GSA-TTS/FAC/issues/568) 

### Background

As part of integrating the login.gov auth flow with Django we’re reusing work that has been done on [CISA](https://github.com/cisagov/getgov). In order to make that work generally we have to implement some slight tweaks that it makes sense to put in a standalone Django application with its own repository.

This should not take a lot of time, but we’re timeboxing it at one day of developer time; if we don’t get through it by then we’ll put the app inside our own Django project and work through any issues there

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We’re importing the login.gov OIDC app from [django_logingov_oidc](https://github.com/18F/django_logingov_oidc).
- [ ]   OR we’ve copied the relevant code into our own Django project

### Tasks

- [ ]   Stand up [django_logingov_oidc](https://github.com/18F/django_logingov_oidc).
- [ ]   Import [django_logingov_oidc](https://github.com/18F/django_logingov_oidc) as a requirement.
- [ ]   OR stand up sub-app for this functionality within our Django project.
