### ISSUE TITLE
Onboarding checklist for Andrea Chappelear

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#610]
**Instructions for the issue creator:** 
1. Fill in the GitHub username of the new person (if known) and the name of the onboarding buddy. 
1. Remove irrelevant checklists (eg designers should never see the engineer checklist.]
1. Remove the horizontal line below and everything above it (these instructions).

---

# Welcome to the team {Leigh Cox}!

@MelissaBraxton will be your onboarding buddy and can help you if you get stuck on any of the steps in the checklist below. There's also a separate checklist that your onboarding buddy will tackle!

## For you

Here's a checklist to get you started and to make sure you've got access to :all-the-things:!

- [ ] Review [the project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/) in Google Drive
- [ ] Join the Slack channels in [the project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/)
- [ ] Review our [process documentation](https://github.com/GSA-TTS/FAC#fac-documentation)
- [ ] Get access to our GitHub repositories
  - [ ] If you are NOT already a member of the [GSA](https://github.com/orgs/GSA/people) or [GSA-TTS](https://github.com/orgs/GSA-TTS/people) GitHub organizations, [follow the process outlined here](https://github.com/GSA/GitHub-Administration#joining-the-gsa-enterprise-organization), requesting access to the appropriate org(s). Include the Product Lead (see [the staffing list](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/edit#heading=h.us8xylqg455c)) on cc: for your email, and mention that you’re being added to the Federal Audit Clearinghouse project. (This may reduce back-and-forth as you’re being added to the GitHub orgs.) Note this step potentially takes a few days; there’s a person who does things in order for this to happen.
  - [ ] Once you are added to the GSA-TTS org, ask the person(s) with the "Maintainer" role to add you to [the FAC-team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members). This will give you read/write access to our repositories.

**For designers, also...**
- [ ] Review the [design onboarding document](https://docs.google.com/document/d/1EILl0nZr59T4PFJJMtFbmnQDJPksgzIFPuoFDN0bk0g/edit#heading=h.bhu3dgydlbvr)

## For your onboarding buddy

Note: If you're not able to do any of these yourself, you're still responsible for making sure that the right person makes them happen!

- [ ] Add to the [FAC-team@GSA.gov](https://groups.google.com/a/gsa.gov/g/fac-team) Google Group
- [ ] Add to standing meeting invites (should happen automatically via addition to the Google Group membership)

**For designers, also...**
- [ ] Add as an editor on active Figma projects

**Comment by MelissaBraxton** [comment]
Moving to blocked until Leigh has access to our GH org.

**Comment by Leighdiddy** [comment]
We are all caught up here!
