### ISSUE TITLE
As a user, I need to know when I've hit a server-level or authentication error

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#621]
Breakout issue of #568.

This issue covers the design of status and permission error pages:
- 400, 401, 403, 404, 422, 500, 501, 502, 503
- csrf failure
- wrong permissions

### Acceptance criteria (We'll know we're done when...)

- [x] We've designed a custom error page template we can use for all errors
- [ ] We've written copy for each of these errors, including instructions on how to move forward
  
### Tasks

- [x] Design the error template
- [x] Write content for each error page (or pull content from an existing project)
- [x] Peer review of design
- [ ] Peer review of copy
- [ ] Write implementation notes

### Definition of Done

- [x] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [x] Interaction are documented if they deviate from USWDS components
- [x] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
- 400: Bad Request
- 403: Forbidden
- 404: Not Found
- 422: Unprocessable Entity
- 500: Internal Server Error
- 501: Not Implemented
- 502: Bad Gateway
- 503: Service Unavailable
- csrf failure: Page Expired

For reference: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

@LindsayYoung Is the permissions error Django's providing a 403 error, or a separate, bespoke error? Also, can you help me brainstorm how a user would move forward after receiving one of these errors? (ex: when someone lands on a 404, we direct them to search static pages on the site)

**Comment by melchoyce** [comment]
Thanks @LindsayYoung for linking us to https://github.com/usdoj-crt/crt-portal/blob/01b3d4da653adcf5af89e20d5d95a8961fc9379b/crt_portal/cts_forms/views.py! I've filled in everything but 422.

**Comment by melchoyce** [comment]
| Text error (short)  | Text error (long) | Error with sign in | Error with search |
| ------------- | ------------- | ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/2846578/206511115-10606c77-21de-491f-827c-b4cf3bb7c10e.png) | ![image](https://user-images.githubusercontent.com/2846578/206511181-3c0bd130-dfeb-496b-a77b-c17a357c733f.png) | ![image](https://user-images.githubusercontent.com/2846578/206511218-38220ad1-2898-49e7-a10d-8434a65d95ea.png) | ![image](https://user-images.githubusercontent.com/2846578/206511254-1f74497d-bb45-45c7-9600-8097691cd5b6.png) |

### [WIP Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5320%3A33337)

Tried to keep it simple. If possible, it would be great to load the global header and footer. (Are there any errors where this won't be possible?)

Of the errors, it seems we have three types: just text, text and button, and text and search. I've mocked up all three, and all of the errors should slot into one of these templates.

Tagging @austinhernandez and @leighdiddy for peer feedback.

**Comment by austinhernandez** [comment]
I think these work and they all have clear error recovery

**Comment by melchoyce** [comment]
Thanks! Moving this into the copy backlog.

**Comment by lauraherring** [comment]
This is a review & refine of error message copy.

**Comment by jadudm** [comment]
Moving to engineering to pick up the first pass at error pages in the Django framework. May ticket new stories in the future to pick up anything we're missing.
