### ISSUE TITLE
Implement notices on "All Screens" page of Figma

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#634]
Breakout issue of #550, see https://github.com/GSA-TTS/FAC/issues/550#issuecomment-1335840052 for latest mockups.

@austinhernandez has mocked up how the notices will work, and now we need to create each notice and wire it up on the "All Screens" page of Figma.

### Acceptance criteria (We'll know we're done when...)

- [x] All notices have been wired up and are ready for permanent copy (see #635)
  
### Tasks

Mock and wire up these notices:
- [x] A submission has been created
- [x] The SF-SAC has been completed
- [x] The audit report has been uploaded
- [x] The auditee has certified
- [x] The auditor has certified

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by melchoyce** [comment]
@austinhernandez I think this one's done now, correct?
