### ISSUE TITLE
Write notice content for audit submission checklist

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#635]
Breakout issue of #550 and #634.

This issue covers the content of notices people receive after taking actions, such as uploading their report pdf and certifying their audits.

![image](https://user-images.githubusercontent.com/2846578/217332407-7d199b57-fd33-4ade-b2a6-b6fd049e8e4b.png)

![image](https://user-images.githubusercontent.com/2846578/217332662-5e1c68bf-2183-4ffb-97d5-f2821db6b775.png)

![image](https://user-images.githubusercontent.com/2846578/217332842-e7b1c554-edbd-4c40-8a49-86ed4aea6769.png)

![image](https://user-images.githubusercontent.com/2846578/217333118-84e5179a-d317-46bf-a245-8950553986c7.png)

![image](https://user-images.githubusercontent.com/2846578/217333184-87d40c66-a7b3-4d46-b8dc-78eb7e0b6418.png)

![image](https://user-images.githubusercontent.com/2846578/217333297-3892f26a-09b4-4fc7-b7d9-433d85a3cf46.png)

![image](https://user-images.githubusercontent.com/2846578/217333485-8283c184-5ffe-46c9-9a01-c2c62e98c0d5.png)

![image](https://user-images.githubusercontent.com/2846578/217333385-9430568a-5578-49d5-b67c-c28b77ddf9b4.png)

![image](https://user-images.githubusercontent.com/2846578/217333415-d7fa7b0d-865c-47f7-a1b4-6529c0710262.png)

![image](https://user-images.githubusercontent.com/2846578/217333520-d966bef1-cdc1-4ba3-a1ec-0b75a9a1a1de.png)

![image](https://user-images.githubusercontent.com/2846578/217333588-f1747e6d-e6bc-4c17-81f0-f4d23123e08d.png)

![image](https://user-images.githubusercontent.com/2846578/217333696-bd488ec3-b942-4d49-a4cd-e570c83bee12.png)

[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A22829)

### Acceptance criteria (We'll know we're done when...)

- [ ] All notices have content written
  
### Tasks

- [ ] Write content for each notice identified in #634
- [ ] Peer review
- [ ] Pass to @Leighdiddy for implementation

**Comment by melchoyce** [comment]
@lauraherring Updated with screenshots. @austinhernandez can you confirm I got everything?

**Comment by lauraherring** [comment]
Screenshots cover all the notices from the report home/report checklist page. Does not cover more administrative tasks, like assigning a new auditor, etc.

**Comment by lauraherring** [comment]
"Open audit list" takes users to the "My Audit Submissions" (internal name) page (see ticket #763) at this time. This is page is different from the the report checklist.

**Comment by lauraherring** [comment]
@austinhernandez @melchoyce Working on these this morning I realized that for "Confirm your submission", the body copy there refers to being able to revise the audit after submitting. Is that the case? I thought that was still an open question/leaning toward the direction of no for MVP?

CC @Leighdiddy

**Comment by lauraherring** [comment]
Confirmed with Tadgh that editing after final submission will not be part of MVP so I'm going to remove that from this confirmation screen.

**Comment by lauraherring** [comment]
@Leighdiddy Here's the new copy for these notifications. Note that two of them (marked with asterisks) I have questions about the functionality of those tasks that I'll bring up with engineering on our next sync. CC @melchoyce  and @austinhernandez 



Auditee certification complete
The audit submission has been successfully signed by the auditee and users with report access have been notified. Before the audit submission can be completed, it must be certified by the auditor and submitted to the FAC for processing. 

[Return to audit submission checklist]	[Go to list of open audit submissions]	[Sign out]


Auditor certification complete
The audit submission has been successfully signed by the auditor and users with report access have been notified. To be completed, the auditee must submit it to the FAC for processing.

[Return to audit submission checklist]	[Go to list of open audit submissions]	[Sign out]


Single audit report package uploaded
The single audit report package has been successfully uploaded and users with report access have been notified. To finish this audit submission, complete the tasks on the report checklist.

[Return to audit submission checklist]	[Go to list of open audit submissions]	[Sign out]


SF-SAC completion
The SF-SAC for this audit submission has been successfully completed and users with report access have been notified. To finish this audit submission, complete the tasks on the report checklist.

[Return to audit submission checklist]	[Go to list of open audit submissions]	[Sign out]


****Confirm your submission
You are about to submit your audit submission to the Federal Audit Clearinghouse (FAC) for processing. You will not be able to edit or rescind this submission after this point.

If you cancel at this time, your recent changes will be saved.

[Submit to the FAC for processing] [Cancel]


Audit submission created
The audit submission for [Auditee Entity] has been successfully created. It may be access at any time by users with report access. To complete this audit submission package, complete the tasks below. **(Do we want to put explainer text here that not all the steps have to be done in order but those with dependencies will be locked until the dependent task is complete?)


Auditee certification completed
The audit submission has been successfully signed by the auditee and the certifying auditor assigned has been notified. Before the audit package may be completed, it must be reviewed and approved by the auditor. 


*****The audit report PDF has been uploaded
The audit report PDF has been successfully uploaded and is attached to this single audit submission. If there is an issue with this PDF, you can re-upload the file. (Where does this link go?)


The SF-SAC has been finalized
The SF-SAC for this audit submission has been finalized and is attached to this report. To complete this single audit submission, please complete the task list below and finalize the certification steps.


Submission complete
You have successfully submitted your audit. It now appears on your list of completed audits connected to your email address below.
