### ISSUE TITLE
Recruit audit resolution officials for discovery research

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#64]
**Background**

**We'll know we're done when...**
- [x] We have interviews with 6-8 agency audit resolution officials on the books
- [x] Participants represent a relevant range of experience (this will determine the number of folks we want to recruit)

**Tasks**
- [x] Talk to QSMO to better understand range of experience among audit resolution officials
- [x] Refine recruitment criteria
- [x] Set up interview time slots
- [x] Draft recruitment email
- [x] Email and schedule participants
