### ISSUE TITLE
Create research plan for tribal auditee testing

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#642]
Breakout issue of #641

### Background

We've started planning a usability testing research spike with tribal auditees, and need to start defining our research plan.

We can likely repurpose much of our [previous auditee research plan](https://docs.google.com/document/d/1CSOj4lJIz2F7sGZ4riAwJYwnJjYwBqWRnlB4055XA94/edit#).

### Acceptance Criteria (We'll know we're done when...)

- [x] We have a research plan outlining our goals for this research spike

### Tasks

- [x] Write a research plan
- [x] Peer review 
- [ ] Copy review (optional but recommended, can ask for help in Slack)

**Comment by melchoyce** [comment]
Draft: https://docs.google.com/document/d/1TrsiqUq-Zi0K1531KoIZ2FDDuVJv54P3RVoG29v9DqQ/edit?usp=sharing

**Comment by austinhernandez** [comment]
@melchoyce @thebestsophist hey! forgot to tag yall on this for a peer review. 

i wrote things for tribal auditees, then rewrote for  auditees and auitors working with tribal orgs. i added more considerations/biases from my work with equitable research with AI/AN 10x. There's some language consistency i was wondering about.`Auditees and auditors working with Indian tribes and/or tribal organizations` is quite long as a user group and my seem to broad, but the needs are the same— this group can opt out of publication, but must make copies of the reporting package available for public inspection. It won't block research or how we address participants, but it's for our internal documentation. Do y'all have thoughts on the matter?
