### ISSUE TITLE
Create interview guide for tribal auditee testing

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#643]
Breakout issue of https://github.com/GSA-TTS/FAC/issues/641

### Background

We've started planning a usability testing research spike with tribal auditees, and need an interview guide.

We might be able to pull out some parts of our [previous auditee testing interview guide](https://docs.google.com/document/d/1BEt0p0aTPBZTjcE1KIybSn4-wKOYw5Peqx7STlrN6I4/edit#heading=h.r9nbj795zr0k).

### Acceptance Criteria (We'll know we're done when...)

- [x]  We have an interview guide outlining the questions we have for tribal auditees 

### Tasks

- [x] Write interview guide
- [x] Peer review
- [ ] Copy review (optional but recommended, can ask for help in Slack)

**Comment by melchoyce** [comment]
Draft: https://docs.google.com/document/d/1slJ1R3ZpeZ58EEOItJXn-Q36yO5uPh1Ynzxhw1_6lOw/edit?usp=sharing

**Comment by austinhernandez** [comment]
this is also complete. i just needed to link the prototype for this group. i decided to just link the all screens prototype so we can go through additional sections if needed. if we need to change from people looking at multiple audits vs. one or someone who is creating a new audit submission vs an auditor that just needs to certify—it's a quick(ish) fix.

[figma link](https://www.figma.com/proto/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?page-id=4954%3A22829&node-id=4954%3A24052&viewport=2151%2C17%2C0.13&scaling=min-zoom&starting-point-node-id=4954%3A24052&show-proto-sidebar=1)

**Comment by austinhernandez** [comment]
@melchoyce already looked and commented, but @Leighdiddy @thebestsophist tagging yall in for a peer review. going through the figma prototype and/or interview guide for last pieces of feedback would be helpful. 💃

**Comment by Leighdiddy** [comment]
@austinhernandez @melchoyce I'm leaving a few edits in suggestion mode on the interview guide itself, nothing major! Only thing that caught my eye on the actual mockup is included here in a screen grab, I didn't change it myself because I wasn't sure if it's intentional but the "  for 2022 only." reads like a typo to me 🤓
<img width="1194" alt="Screen Shot 2023-01-18 at 4 40 43 PM" src="https://user-images.githubusercontent.com/119363060/213300982-66ec1d68-3d72-4133-959c-a5ef239930bc.png">
