### ISSUE TITLE
Recruit participants for tribal auditee testing

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#646]
Breakout issue of #641

### Background

We were unable to speak with any tribal auditees in our last round of research, but now have a few leads. We'd like to learn more about their experiences using the FAC. 

### Acceptance Criteria (We'll know we're done when...)

- [ ] We recruited a few participants (number TBD) to conduct interviews with

### Tasks

- [ ] Follow up with IHS about getting connected to tribal auditees
- [ ] Touch base with @jasnakai about [getting in touch with his connections](https://gsa-tts.slack.com/archives/C1L58R804/p1670264805132829)
