### ISSUE TITLE
Synthesize and write up results of tribal auditee interviews

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#648]
Breakout issue of #641

### Acceptance Criteria (We'll know we're done when...)

- [x] We've synthesize out interview data
- [x] We've summarized the results of our interview data
- [x] The OROS designers are caught up with the previous rounds of research

### Tasks

- [x] Synthesize interviews
- [x] Demonstrate TTS research best practices to new designers
- [x] Work with OROS designers to answer questions and give additional context to meetings
- [x] Write up results
- [x] Peer review

**Comment by austinhernandez** [comment]
[Working on the synthesis here in Mural](https://app.mural.co/t/gsa6/m/gsa6/1674586892132/1bee4b6733934c0985e76f8dbc180095d21b8659?sender=austinhernandez5199)

**Comment by austinhernandez** [comment]
[presentation ready to share](https://docs.google.com/presentation/d/1ZGho8x30pNJXGv4LiMytYmE7vWD_tNpCNxd1TcLI9js/edit#slide=id.g1fdb613d97c_0_457)
