### ISSUE TITLE
Present results of tribal auditee research to the FAC team

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#649]
Breakout issue of #641 

### Background

After synthesizing and writing up our research (#648), we'll want to report out to the team.

### Acceptance Criteria (We'll know we're done when...)

- [ ] We've presented our results at a coworking session

### Tasks

- [ ] Finalize report in a presentable format (like Google Slides)
- [ ] Present to the team

**Comment by austinhernandez** [comment]
[Working on the presentation here in Slides](https://docs.google.com/presentation/d/1ZGho8x30pNJXGv4LiMytYmE7vWD_tNpCNxd1TcLI9js/edit?usp=sharing)
