### ISSUE TITLE
Finalize research protocols / green light testing!

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#69]
**Background**

**We'll know we're done when...**
- [x] We have everything we need to run user research sessions

**Tasks**
- [x] Finalize research protocol
- [x] Create note taking template
- [x] Check that mocks are wired for testing
