### ISSUE TITLE
Create clickable prototype for testing

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#70]
**Background**

**We'll know we're done when...**
- [x] We have a clickable prototype that we can use to address our sprint 1 research Qs
- [x] We've confirmed that participants will be able to access it. 

**Tasks**
- [x] Review final research protocol
- [x] Decide on prototyping tool (e.g., Figma or InVision?)
- [x] Move mocks from FAC playground to clean prototyping space
- [x] Wire up / make clickable in a way that lines up with test scenario
- [x] Ask a team mate to click through and look for anything broken!
