### ISSUE TITLE
Populate database with content

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#709]
## Background

Content in the old FAC Frontend application was contained in static files as markdown/YAML. The rationale for this was to enable team members who don't primarily write code to add/edit/update content. In moving to a monolithic Django application, we still want to be able to do this. The simplest way to go about this is to use Django's CMS functionality to give users access to content via the admin panel. In support of this as part of #564, @LindsayYoung implemented some basic CMS functionality as a way of getting content into our templates.

## Subtasks

- [ ] Add slots in existing templates for database content
- [ ] Create a [migration to seed initial content](https://docs.djangoproject.com/en/4.1/howto/initial-data/)
- [ ] Ensure content is then editable from within Django admin

**Comment by tadhg-ohiggins** [comment]
#493 and #621 should become sub-issues of this; there are probably other content issues that might end up being part of this story.

**Comment by tadhg-ohiggins** [comment]
@lauraherring and @heymatthenry and I discussed this 2023-02-21 and these are our preliminary conclusions:

Initial plan for handling error messages in the database is to use these three tables:

*   A table based on Year/Section/Question/Subquestion/Subquestion that will, for a given row, point at one of the following two tables.
*   A table based on type of error message, such as “can’t be null”.
*   A table for messages specific to individual questions, such as “since you answered X to Y, Z must be A, B, or C.”.

1.  Set up the above.
2.  Migrate existing error copy that currently in the markup to the database tables above and then to point from Django templates to those tables.
3.  Figure out what the editing process for these copy changes would be, and whether or not we really want to move copy out of source control and into the database completely.
4.  Laura to review/edit the copy.

**Comment by JeanMarie-TTS** [comment]
@tadhg-ohiggins , is this one a Must Do, Should Do, Could Do, or Won't Do for the MVP?

**Comment by jadudm** [comment]
There are questions around how to manage content in both the static site and the application. However, we are not tackling questions of CMSes at this time. It is unlikely we will invest engineering effort into CMS functionality pre-MVP. If we get all of our MUST work done, we might be able to revisit this question (which really is in a SHOULD/COULD space right now). 

Closing as "not planned."
