### ISSUE TITLE
OWASP ZAP scan

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#712]
Breakout issue of deployment pipeline

### Background
This should be one of the last tasks for the pipeline

### Acceptance Criteria (We'll know we're done when...)
The OWASP ZAP scan runs via GitHub actions: 
- [x] on the dev site before merging to the main branch
- [x] on the dev site before merging to the prod branch
- [x] on the staging site before deploy using a tag
- [x] on the prod site after deploy

Update docs:
- [x] instructions on how to run locally
- [x] update existing branching and testing docs

### Tasks
- [x] add OWASP config
- [x] add to GitHub workflows
- [x] update docs

**Comment by LindsayYoung** [comment]
Just found [owasp-zap](https://github.com/marketplace/actions/owasp-zap-baseline-scan) in the github actions marketplace, so that should make it easier.

**Comment by LindsayYoung** [comment]
I didn't use the marketplace app. It was nice because it could auto create issues, but I could not get it to load our config file.

**Comment by LindsayYoung** [comment]
done [ly/owasp#712](https://github.com/GSA-TTS/FAC/tree/ly/owasp%23712)
