### ISSUE TITLE
Mock more filter options in new audit creation

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#72]
**Background**
We heard from our Census colleagues that auditors will likely want to filter their lists of audits in multiple ways. To test this hypothesis, we want to mock up more complex filters that we can put in front of sprint 1 test participants. 

**We'll know we're done when...**
- [x] We have mocks to facilitate conversation with auditors on more complex filtering options. 
- [ ] 

**Tasks**
- [x] Look at inspo linked to in the issue
- [x] mock up
- [x] Review with/get feedback from a peer
- [x] refine as needed
