### ISSUE TITLE
Epic: Obtain an ATO for FAC

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#725]
```[tasklist]
### Must/required for assessment
- [x] Initiate ATO meeting with Ryan Palmer
- [x] Have an ISSO assigned
- [x] Have a folder created
- [x] Complete FIPS 199 template
- [x] Complete DIA Template
- [x] Get PTA approved
- [x] Create architecture doc
- [ ] https://github.com/GSA-TTS/FAC/issues/1006
- [ ] #828
- [ ] #834
- [ ] https://github.com/GSA-TTS/FAC/issues/1031
- [ ] https://github.com/GSA-TTS/FAC/issues/1014
- [ ] https://github.com/GSA-TTS/FAC/issues/1015
- [ ] https://github.com/GSA-TTS/FAC/issues/1064
- [ ] https://github.com/GSA-TTS/FAC/issues/1071
- [ ] https://github.com/GSA-TTS/FAC/issues/1161
- [ ] https://github.com/GSA-TTS/FAC/issues/1027
- [ ] https://github.com/GSA-TTS/FAC/issues/1394
- [ ] https://github.com/GSA-TTS/FAC/issues/1022
- [x] Remove public_networks_egress ASG from spaces
- [x] Fill in data transfer agreement for Census/GSA transfer
- [ ] Provision OracleDB for ETL
- [x] Update boundary diagrams to include ETL/Oracle DB
- [x] Update boundary diagrams to include ETL/S3 bucket
- [ ] https://github.com/GSA-TTS/FAC/issues/1070
- [ ] https://github.com/GSA-TTS/FAC/issues/1522
- [ ] https://github.com/GSA-TTS/FAC/issues/1397
- [ ] https://github.com/GSA-TTS/FAC/issues/1677
- [ ] https://github.com/GSA-TTS/FAC/issues/1020
- [ ] https://github.com/GSA-TTS/FAC/issues/1019
- [ ] https://github.com/GSA-TTS/FAC/issues/1521
- [ ] https://github.com/GSA-TTS/FAC/issues/1679
- [ ] https://github.com/GSA-TTS/FAC/issues/1634
- [ ] https://github.com/GSA-TTS/FAC/issues/1648
- [ ] https://github.com/GSA-TTS/FAC/issues/1649
- [ ] https://github.com/GSA-TTS/FAC/issues/1676
```

**Comment by JeanMarie-TTS** [comment]
Folder created: https://drive.google.com/drive/folders/1tvH6w0FzGGpoMcEHfBVnLqaadgN_r7n5?usp=sharing_eil_se_dm&ts=63a46476

**Comment by JeanMarie-TTS** [comment]
Need the following doc to be reviewed. In particular, are there other information types that we need to include in Table 3.2? https://docs.google.com/document/d/1k5VxDeKqGS3svqZGgeNlX6HswWIXJ9Jhf67dhvZmze4/edit?usp=sharing
@mogul , can you take a look please, or let me know who can do this?

**Comment by mogul** [comment]
That looks accurate AFAIK.

**Comment by JeanMarie-TTS** [comment]
Status on 02/15/23:

- DIA , FIPS-199 and PTA awaiting approval by Ryan Palmer.
- System architecture diagram has been updated and needs to be discussed with Ryan.

**Comment by JeanMarie-TTS** [comment]
JM started working on PIA in archer. Waiting for Chris to get access to archer.

**Comment by mogul** [comment]
@jadudm can you please confirm that we are definitely going to be adding an Oracle DB to work with during ETL? If so I will roll all three of these into a separate issue.


![Image](https://github.com/GSA-TTS/FAC/assets/47762/c366adbd-75ae-4b70-9e4d-8097ecb79f61)

**Comment by jadudm** [comment]
LATO obtained. Future work will be tracked through the board and future epics.
