### ISSUE TITLE
Manual testing infrastructure

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#726]
### Background

We want to make manual testing of submissions in various stages easy for staff to perform.

We will, for starters, only use submissions that have already had UEI entered; this task does not include the UEI entry/verification steps. Testing that will be an enhancement and a future separate issue.

We will start with very simple/early submission states and will add more of them to this set over time.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We have a basic list of stages of completion for submissions that we want to test (starting small and growing—this does not need to be exhaustive).
- [ ]   We have a list of `dev` and `staging` user accounts to associate with these submissions.
- [ ]   We have files representing these submission in the repo.
- [ ]   We have a script that loads these into the `dev` and `staging` databases as part of CI/CD.

### Tasks

- [ ]   Get list of user login.gov accounts for the above.
- [ ]   Create at least two submissions in different incomplete states.
- [ ]   Add those to the repo as JSON files.
- [ ]   Add the script to our CI/CD processes.

**Comment by pkigongo** [comment]
Should remain in triage upon the arrival of a QA.
