### ISSUE TITLE
Show finalized reports in My Audit Submissions table

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#727]
Breakout issue of #414.

### Background

We need to list submitted/finalized reports in the submissions table even if we can’t yet support viewing those reports

### Acceptance Criteria (We'll know we're done when...)

- [ ]   Submitted/finalized reports are listed in the my audit submissions table.

### Tasks

- [ ]   Add test data for finalized reports.
- [ ]   Ensure that finalized reports show in the table.

**Comment by jadudm** [comment]
Tracking elsewhere. Closing as not planned.
