### ISSUE TITLE
As-is workflow model 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#73]
**Background**

**We'll know we're done when...**
- [x] We have a visual representation of users tasks and how information flows through the current system
- [x] We've validated that our representation is accurate

**Tasks**
- [X] Sketch out WF based on knowledge and current knowledge
- [x] Augment/update, based on what we learn in talking with users. 
- [ ] Cognitive walkthrough w/ SMEs

**Comment by MelissaBraxton** [comment]
Updated the model. Aim to walk through w/ Mark D. on Monday 5/2. Then we can close this out.

**Comment by MelissaBraxton** [comment]
Rescheduling the walkthrough with Mark D.

**Comment by MelissaBraxton** [comment]
Yep!
