### ISSUE TITLE
Implement DAP on FAC.gov landing page

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#741]
Breakout issue of #526

### Tasks

- [x] Generate DAP code
- [x] Add to fac.gov
- [x] Request access for relevant team members to access analytics
- [x] Ensure that relevant team members can log in to DAP and view analytics

### Resources

1. [Github repo with implementation instructions & code](https://github.com/digital-analytics-program/gov-wide-code)
2. [DigitalGov implementation page](https://digital.gov/guides/dap/add-your-site-dap/)
3. [DAP FAQs](https://digital.gov/guides/dap/common-questions-about-dap/)

**Comment by geekygirlsarah** [comment]
https://github.com/GSA-TTS/FAC-transition-site/pull/3 put the code on fac.gov and it's live now.

**Comment by geekygirlsarah** [comment]
Access for @austinhernandez, @thebestsophist, @lauraherring, @Leighdiddy, and @melchoyce requested and they have been sent emails to start the access process.

**Comment by geekygirlsarah** [comment]
I heard they got in and can access the site, so I'm calling this done. (There's nothing to review.)
