### ISSUE TITLE
Initial data structure

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#742]
Breakout issue of Data Migration Epic #723

### Task
Create simple data models with readable names and documentation based on the structure of the downloads and the download data key

### Acceptance Criteria (We'll know we're done when...)
- [x] There are models and fields for all the public data elements
- [x] The names are readable
- [x] The fields are documented so that  we can optimize the data structure without loosing track of the data source

**Comment by LindsayYoung** [comment]
This was an intermeiatestep in the data migration epic, you can see the moels here:
LY/data exploration [WIP] #754

We discused this at eng huddle an considered this closed.
