### ISSUE TITLE
Test some basic queries and add indexes

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#748]
Breakout issue of Data Migration Epic #723
(Begin after completion of  #913 )

### Background

Depends on #746, #747.  It would be nice to load the non-public data first, but that shouldn't be a blocker.

### Acceptance Criteria (We'll know we're done when...)

- [ ]  Test queries can be run in a reasonable table

### Tasks

- [ ]  Check on database size
- [ ]  Add indexes
- [ ]  Get some performance baseline records

**Comment by pkigongo** [comment]
Can't start until data is loaded.
