### ISSUE TITLE
[revisit 6/12] Modify or create script to load all data

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#750]
Breakout issue of Data Migration Epic #723

### Background

To get all the data, we will need a data dump form Census.

Some adits are not public:
- In the Elecaudit table data, if `IT` is populated in `suppression_code`
- In the year 2015, only audit reports with uniform guidance ( A133 - filed) - are available 
- All audits before 2015 are not public

The PDF mapping for reports are not available in bulk downloads. We would want to just add that data from a data dump rather than build a scraper for it. 

The PDFs themselves we will get from a data dump form Census.

We will have to get records that come in after this dump but before we go live. That shouldn't be a problem because we will have a data load script. 

### Acceptance Criteria (We'll know we're done when...)
- [ ]  GSA has data dump from Census Dissemination
- [ ]  GSA has all necessary PDFs

### Tasks
- [ ]  See [Data Migration Notes](https://docs.google.com/document/d/1j4HlhaeSB-27e_d8gxsYSDB7WFy7Cc8h_HG_RmbuPfo/edit#bookmark=id.vq5gxv9xsc85) for how we are going to transfer the data.

**Comment by LindsayYoung** [comment]
Sent a follow up email to Census about data transfer 2/13/23

**Comment by LindsayYoung** [comment]
Sent a follow up email to Census about data transfer 2/21/23

**Comment by LindsayYoung** [comment]
Sent a follot up 2/28 and 3/8

**Comment by LindsayYoung** [comment]
Necessary tooling is installed on relevant servers 👍

**Comment by LindsayYoung** [comment]
We have PDFs more data to come

**Comment by mogul** [comment]
@danswick will chase this when he's back from vacation. cc @jadudm
