### ISSUE TITLE
Link existing data to PDFs via URL

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#751]
Breakout issue of Data Migration Epic #723 

### Background

Get PDFs and add them to buckets. 

We can use the filename to generate a url point to the bucket, we would want to incase the bucket name changes. We also don't want the url in the data because it will be different in prod, stage, and dev. We may want to revisit this when we look at #748 (We may want to pregenerate production uls for speeder downloads.)

Linking the PDF file names to  reports can be done by looking at the name of the file - {DBKEY}{AUDITYEAR}.pdf

### Acceptance Criteria (We'll know we're done when...)

- [ ]  We have public PDFs in predictable urls in our public bucket
- [ ]  We have private PDFs in predictable urls in our private bucket

### Tasks

- [ ] Sort PDFs into public and private buckets
- [x] Create private bucket for private PDFs
- [ ] Add public PDFs to the public bucket the structure could be something like `/collections/year/month/<file name>.pdf` (Buckets don't like a lot of sequentially numbered file names one bucket, so trying to break them up into chunks that will be performant.)
- [ ]  Add private PDFs to the private bucket in a file structure that mimics the public PDFs

Reach goal:
- [ ]  Add some test PDFs for local development

**Comment by jadudm** [comment]
We have, at this point, a single private S3 bucket. We are going to route everything through the app.

E.g. 

`https://app.fac.gov/pdf/...`

will link to a file, and we'll determine in the app/do a redirect if appropriate.
