### ISSUE TITLE
Update error pages to use USWDS 404 page template

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#756]
This issue covers the design of error pages, such as 404. 

Related: #381 

### Background

Current 404 pages:

![image](https://user-images.githubusercontent.com/2846578/214388337-1c903752-37f1-41a2-a571-69bcf4b4705d.png)

USWDS template: https://designsystem.digital.gov/templates/404-page/

![image](https://user-images.githubusercontent.com/2846578/214388393-f66a8095-3523-4a3a-953d-bdedb0c0a290.png)

### Acceptance criteria (We'll know we're done when...)

- [ ] We can use the USWDS 404 page template for all of these error pages
  
### Tasks

- [ ] Redesign error pages to work within the USWDS 40 page template
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by jadudm** [comment]
We added error pages.
