### ISSUE TITLE
Bug: Pre-SAC UEI search can be bypassed, breaking form functionality

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#757]
### Background

In the Pre-SAC flow, step 2 asks you to enter a UEI to search for it. If it can find it, it uses it. If it can't, it lets you continue manually but will have to validate later.

You can bypass the process by leaving the UEI field empty, hitting search, it will fail, then do it manually. This seems to break the Continue button on the page.

This should probably not be allowed and either force the search, or just let the user not enter it immediately.

### Acceptance Criteria (We'll know we're done when...)

- [ ] You can complete step 2 of the Pre-SAC flow and are required to search for the UEI
   or 
- [ ] You can complete step 2 of the Pre-SAC flow by specifying you'd rather do it manually

### Tasks

- [ ] TBD (for developer/designers to figure out)

**Comment by pkigongo** [comment]
Iceboxing thanks to #835

**Comment by jadudm** [comment]
This should close out when we finish requiring UEI. Putting it into the SF-SAC submission milestone for completeness.
