### ISSUE TITLE
As an auditor or auditee, I'd like a quick way to navigate to my previous audit submissions

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#770]
As an auditor or auditee, I'd like a quick way to navigate to my entity's past few years audit submissions while I'm working on this year's submission so that I can learn from past examples. 

### Background

During our [October round of auditee research](https://github.com/GSA-TTS/FAC/blob/main/docs/design-research-documentation/auditee-research-report--2022-10.pdf), we discovered that some auditees would likely to more easily reference previous years' audit submissions to compare to their current year's submissions. We should provide a way for people to quickly access previous submissions.

### Acceptance criteria (We'll know we're done when...)

- [ ] Users can quickly and easily find past submissions
  
### Tasks

- [ ] Design
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by Leighdiddy** [comment]
Reviewed w Mel: fuction is to be able to compare prior years reporrts to current, for auditors or auditees.

**Comment by melchoyce** [comment]
We discussed the idea of a section under "Search audit reports"



![Image](https://user-images.githubusercontent.com/2846578/221653130-b6473289-7a35-4fee-982b-10a89f000fea.png)
