### ISSUE TITLE
As an auditee, I'd like a way to quickly check key figures, names, and dates

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#771]
As an auditee, I'd like a way to quickly check key figures, names, and dates without having to download anything before I certify my audit submission. 

### Background

During our [October round of auditee research](https://github.com/GSA-TTS/FAC/blob/main/docs/design-research-documentation/auditee-research-report--2022-10.pdf), we discovered that some auditees would prefer to have key points of their audit submissions shown before certification, instead of needing to individually review the SF-SAC and Audit Report manually.

### Acceptance criteria (We'll know we're done when...)

- [ ] Auditees can get an overview of their audit submission before certification, without needing to download anything
  
### Tasks

- [ ] Design
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [x] ~All text has a contrast ratio of 4.5:1 with the background~ (Built into USWDS)
- [ ] Interaction are documented if they deviate from USWDS components
- [ ] The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [x] ~There is an option for multilingual support~ (We've established multilingual support in the header)
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by Leighdiddy** [comment]
Reviewed w/ Mel: Post MVP, ideal feature not sure how it would pan out after excel workflow is established.
