### ISSUE TITLE
Audit UI colors for consistency

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#788]
### Background

@sreuber asked a color question in Slack earlier which made me take a look at all of our UI colors. I've brought them all inline with [available USWDS color tokens](https://designsystem.digital.gov/design-tokens/color/system-tokens/), but we'll want to do a full audit. For example, we use a mix of cool, warm, and vivid colors—we might want to standardize around one, where appropriate.

### Acceptance criteria (We'll know we're done when...)

- [ ] Very nebulous, but: we've reduced the number of colors in our palette and standardized them as much as possible
  
### Tasks

- [ ] Audit all of our UI colors
- [ ] Double-check current colors against stock USWDS components
- [ ] Make changes where possible
- [ ] Peer review
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] All text has a contrast ratio of 4.5:1 with the background

**Comment by Leighdiddy** [comment]
Double check HEX codes on similar objects, create consistent color library!
