### ISSUE TITLE
Audit User Management content

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#795]
![image](https://user-images.githubusercontent.com/2846578/218801099-05144bdb-13a9-401b-9674-9c536b51b7f3.png)

![image](https://user-images.githubusercontent.com/2846578/218801214-1e0a2ebc-a7e2-4b5b-aff5-7270d7b536e0.png)

![image](https://user-images.githubusercontent.com/2846578/218801279-b6db8a4a-b779-4583-b17a-54d19f49704f.png)

![image](https://user-images.githubusercontent.com/2846578/218801320-9ae010c5-3848-480c-8505-c30e540deaa8.png)

[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5281%3A32558&t=tJV9hgr08q9yihCD-4)

### Acceptance criteria (We'll know we're done when...)

- [ ] We've audited all of the content on the page, including modals and error states
- [ ] The Figma mockups have been updated with content changes
  
### Tasks

- [ ] Audit page content
- [ ] Peer review
- [ ] Update Figma designs
- [ ] Write implementation notes

### Definition of Done

- [ ] Screens in Figma are ready to be handed off to front end
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, tab order, focus order, and what assistive technologies should announce (if applicable)

**Comment by lauraherring** [comment]
This is another review & refine copy as necessary.
