### ISSUE TITLE
Offboarding checklist for @melchoyce

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#825]
I (@melchoyce) will be offboarding on 3/6/2023. 

# For everyone

- [ ] Remove from [the FAC-team Google Group](https://groups.google.com/a/gsa.gov/g/fac-team/members)
- [ ] Remove from [the FAC team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members)
- [ ] Remove from the private channel #oros-fac-private in Slack (“/remove @[person]”)

**For designers, also...**

- [ ] Remove from active Figma projects (Do we want to retain my Figma access another few weeks to answer questions?)

**For product leads/owners, also...**

- [ ] Make someone else the owner of [the various Google Groups in the project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/edit#heading=h.81zynabayrrg) (and remove them)
- [ ] Make someone else the Maintainer and remove the departing team member from [the FAC-admins team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-admins/members)

**Comment by mogul** [comment]
@thebestsophist can you check for any Figma access that needs to be removed, and then move this to `Done`?

**Comment by mogul** [comment]
(@thebestsophist _gentle ping_, we could close this out pretty easily...)

**Comment by thebestsophist** [comment]
done!
