### ISSUE TITLE
Offboarding checklist for @mhiner-fearsol

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#830]
# For everyone

- [x] Remove from [the FAC-team Google Group](https://groups.google.com/a/gsa.gov/g/fac-team/members)
- [x] Remove from [the FAC team in GitHub](https://github.com/orgs/GSA-TTS/teams/fac-team/members)
- [x] Remove from the private channel #oros-fac-private in Slack (“/remove @[person]”)

**For engineers, also...**

- [x] Make a PR to [remove the departing team member from the list of developers and managers](https://github.com/GSA-TTS/FAC/tree/main/terraform/management/config.tf) with access to our spaces.
