### ISSUE TITLE
Remove SAM.gov UEI lookup from Django views

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#835]
Breakout issue of #185

### Background

We previously tried to pull UEI data from SAM.gov, and as of 2023-03-02 have decided to proceed without it to simplify process flow. 

We will ask for UEI and validate against UEI structure as part of the Pre-SAC flow. We will not check the UEI against the SAM.gov API. Users will enter their own organization information, including name and address; none of that information will come from SAM.gov.

We need to remove some of the existing code in the application that currently tries to accommodate both SAM.gov and non-SAM.gov flows.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   Users enter their UEI, name, and address directly without a SAM.gov lookup.
- [ ]   We’re removed the code from the views that dealt with SAM.gov integration.

### Tasks

- [ ]   Remove SAM.gov UEI flow integration from the Django views.
- [ ]   Verify that the flow for entering UEI/name/address directly still work.

**Comment by JeanMarie-TTS** [comment]
@tadhg-ohiggins , should this one be closed?

**Comment by tadhg-ohiggins** [comment]
Closing since we're not taking this path, instead going with what's outline in https://github.com/GSA-TTS/FAC/pull/848.
