### ISSUE TITLE
Setup initial Django project

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#84]
**Background**

Let's establish a file structure and Django project to begin development. We value idiomatic Django and will use the `startproject` [django-admin command](https://docs.djangoproject.com/en/4.0/ref/django-admin/#django-admin-startproject) to create our project. 

As part of this, we'll propose a directory structure for the repo and names for our Django project and first Django application. 

**We'll know we're done when...**
- [x] We've added a Django project, created with `startproject`, to the repository
- [x] We've added a Django application within our new project using `createapp`
- [ ] Everyone who needs to have Docker or local set up has done this and confirmed it works

**Tasks**
- [x] Propose a project name and initial application name
- [x] Propose a directory structure in which the Django application will live.
