### ISSUE TITLE
Deploy to cloud.gov

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#85]
**Background**

Once we've got a Django project [#84], it needs to run on Cloud.gov. Implement and document our initial cloud.gov setup by deploying our skeleton Django project to cloud.gov.

**We'll know we're done when we have...**
- [ ] Our Django project is running on cloud.gov and we've documented the process surrounding it.

**Tasks**
- [ ] Document the cloud.gov organizations we'll use including onboarding/offboarding
- [ ] Document and creating if needed a `development` space within the org
- [ ] Provision S3 and Postgres services in the above dev space
- [ ] Create a manifest file which can be used with `cf push` successfully run our Django
