### ISSUE TITLE
Starter views for the dissemination API

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#859]
### Background
We want to create views for people to grab data in a user friendly way.

### Acceptance Criteria (We'll know we're done when...)
- [x]  You can access all the data through the API
- [x]  You can search the data by fields that make sense of the type of data (Agency, Auditee)

### Next steps

- This should serve as a first offering of data dissemination, but his can be improved and reorganized after input from users.
- After this is built, there should be some speed tests and indexes should be added.
- Once the format of the data is reviewed with users, we would want to make a bulk data download that we could refresh nightly.

### Tasks
- [x]  Create views
- [x]  Incorporate migrations into data_distro

**Comment by jadudm** [comment]
I think there are questions we're going to have to answer about how we expose the API, and your documentation comment/question is... just one of probably many. However, we're not going to answer all of our questions in the first instance. Better to push, explore, and iterate than wait. 

In part, I wonder about exposing the `vw` as part of the API, because the notion that these are views is irrelevant to the user of the API. However, again... this is not "version 1," but "version 0." So, better to push and explore than not.

Swagger doesn't know how to interactively talk to the PostgREST backend, because it looks to 0.0.0.0 by default. I *think* that is an env-variable-type fix, but better for a ticket than to dwell no it today. 

Looks good to me.

**Comment by jadudm** [comment]
Moving to "done" given that we have views in place, and users starting to test them.
