### ISSUE TITLE
Set up deployment pipeline for Postgrest API

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#860]
### Background
We are formalizing the API exploration that @jadudm did here: https://github.com/GSA-TTS/fac-dissemination-api-exploration We need to add it as part of our pipeline so we can deploy in envirnonments.

The backend app will create the views and the postgrest api should just be a consumer of the existing database.

### Acceptance Criteria (We'll know we're done when...)
- [ ]  When there is an update to the code it deploys from GitHub
- [x]  It follows our branching strategy
- [ ]  Document API decisions as an ADR
- [ ]  Update architecture diagram

### Tasks
- [ ]  Set up pipeline dev
- [ ]  Set up pipeline staging
- [ ]  Set up pipeline  production

This is going to be a first iteration, we can set up a buildpack if it is easy, otherwise that should be a follow up.
This is just adding an app so I don't think we need TF, but we can add it later if desired.

**Comment by LindsayYoung** [comment]
https://github.com/GSA-TTS/fac-dissemination-api-exploration/pull/1

**Comment by jadudm** [comment]
@LindsayYoung , what ADR decisions can I draft up for consideration to help this ticket move towards completion? What would you like to see documented? (If it is essentially "we're using PostgREST for dissemination," I can write something up to this effect.)

@JeanMarie-TTS , do we have architecture diagrams up to date, such that that part of this ticket is complete?
