### ISSUE TITLE
API demo repository - home and process

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#863]
### Background

To demo the historical data intake and public dissemination API, we created a small repository with example code and minimal docs.

https://github.com/GSA-TTS/fac-dissemination-api-exploration

We shared this in a brown bag as part of the API demo.  

We know this is "down the board" in terms of stories, but it now serves as a surface for agencies to engage with us around the data and APIs (generally speaking).

We need to discuss and decide where this should live and, depending, what process it needs around it.

### Tasks

- [ ] Consider how/where community dialogue around this kind of code will live (e.g. in GH, a mailing list).
- [ ] Consider how community will engage/contribute, and implications for where it lives (e.g. product vs. separate repo). May have compliance implications? 
- [ ] Consider how we manage the code in this repo (process).

### Acceptance criteria (We'll know we're done when...)

- [ ] When we know where we want the API example code and documentation to live.
- [ ] When we decide what process (ticketing, review, etc.) this repo will follow. (E.g. a reasonable answer might be "it is ticketed and managed via the team's normal process.)
- [ ] When we know how/where we want to have conversation with the community regarding this kind of "outward facing" code. Examples might be "a new mailing list," or "in GH." 
 - [ ] Write up an initial ADR regarding these decisions, so we can share it back out to the community for feedback (which may lead to change).
 
*Initial decisions are not implementation; this may spawn additional tickets.*
