### ISSUE TITLE
Modify the script to deal with records amended since the last load

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#890]
Data Load Epic #723

### Background
Since the current dissemination site only displays the current record, we need to make sure we update the data that has changed since the last load.

(We could run the data from scratch later but I don't recommend that because it is time and labor intensive.)

### Acceptance Criteria (We'll know we're done when...)

- [ ] We update data that has changed since the last load of the data

### Tasks

- [ ] Move the revision loading to be the first action of the load script
- [ ] Check if a revision record exist in the current data 
- [ ] If the revision doesn't exist, find all the existing records that link to that general form and remove them
- [ ] Make sure many to many fields are taken care of appropriately, (Removal if this is the only record they reference, leave them if other records reference them)

**Comment by jadudm** [comment]
I'm going to close this ticket as "not planned."

At this point, we are moving to an operational posture where we assume we will, at some point, get "the final dump of data." This will be what we load. Along the way, we're going to make sure we can ETL the historic data, but we're not going to assume that there are multiple loads in-flight.

Hence, this can close out.
