### ISSUE TITLE
Research spike: bulk data upload patterns

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#91]
**Background**
Users need to be able to upload bulk data as part of filling out the SF-SAC form. Currently this is handled by users downloading and uploading specific excel templates from/to the FAC, but this comes with a lot of potential problems / complications both technically and from a UX perspective. We want to research alternative options for meeting this need, including how to represent and/or direct users on the front to access the API.

**We'll know we're done when...**
- [x] We have a clear write up of possible approaches and the trade-offs. 
~~- [ ] We've made a decision on which approach we want to take~~

**Tasks**
- [x] Comparative analysis of different approaches to bulk data upload 
- [x] Write up brief description and pros/cons

**Comment by petermarks-gsa** [comment]
Per backlog grooming, I've adjusted the acceptance criteria and am closing this.
