### ISSUE TITLE
GitHub deployment issues issue

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#917]
### Background
We’ve run into various issues trying to get our GitHub deployment workflow to function all the way through to production. 

This is an ad-hoc ticket for tracking this until we’ve got it working.

### Acceptance Criteria (We'll know we're done when...)

- [x]   Deploying to `dev` works.
- [x]   Deploying to `staging` works.
- [x]   Deploying to `production` works.

### Tasks

- [x]   Rework triggers to use `startsWith` in conditional.
- [x]   Rename `fac-public-s3` service in `production` cloud.gov environemnt.
- [x]   Rewrite `triggers.yml` to generate terraform plan on all PRs, not a specific subset.

**Comment by tadhg-ohiggins** [comment]
I believe the order of operations for what we’re currently trying is:

- [ ]   Rename or remove `fac-public-s3` from the services running in the cloud.gov `production` space.
- [ ]   Rename or remove `fac-private-s3` from the services running in the cloud.gov `production` space.
- [ ]   Change `triggers.yml` to generate a terraform plan for more or less everything.
- [ ]   Create a PR for the above `triggers.yml` change, targeting `main`.
- [ ]   After tests, merge that PR into `main`.
- [ ]   After tests, create a PR from `main` targeting `prod`.
- [ ]   After tests, create a new release.
- [ ]   Probably follow a terraform step if the deployment of the new release fails in the way we expect.
