### ISSUE TITLE
Finalize and share FAC design principles

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#918]
Breakout issue of...

#837 

### Background (from ticket #837)

All preliminary work is done on the FAC design principles. Next, OROS designers will make it their own to guide the product and design of the FAC going forward. Here are some of the artifacts I created from the preliminary work:

- [Research mural](https://app.mural.co/t/gsa6/m/gsa6/1677783369867/0d97718fea0c70cca6d5337b32a4d6cb0eae3cbf): Here are quotes pulled from _all_ of our interview notes from 2022-2023. This was the work that guided the first draft of the design principles

- [DRAFT user research based design principles](https://docs.google.com/document/d/1BLaL6BpItMqeOYq41tD7joOhpcYAQX_i_GIF0l6oSz0/edit#):  A draft of design principles / themes from [the above research mural](https://app.mural.co/t/gsa6/m/gsa6/1677783369867/0d97718fea0c70cca6d5337b32a4d6cb0eae3cbf?sender=austinhernandez5199). This is an in-progress document requiring the results of the  [Design Workshop Mural activity](https://app.mural.co/t/gsa6/m/gsa6/1678917820778/26aa32d2c0af104dcf4e5ab9c573f12e87a556ab?invited=true&sender=austinhernandez5199) and input of the team.

- [Design Workshop Mural activity 3/30](https://app.mural.co/t/gsa6/m/gsa6/1678917820778/26aa32d2c0af104dcf4e5ab9c573f12e87a556ab?invited=true&sender=austinhernandez5199): Design principles workshop we completed as a team.

- [FAC Workshop Summary from 3/30](https://docs.google.com/document/d/12pQB44EqPOieO9MZds-NChdN4fPE5wQVAIrHB1R6mZ0/edit): Summary of the [above Design Workshop Mural activity](https://app.mural.co/t/gsa6/m/gsa6/1678917820778/26aa32d2c0af104dcf4e5ab9c573f12e87a556ab?invited=true&sender=austinhernandez5199) with voting results and additional context.

- [Design principles on Google Drive](https://drive.google.com/drive/folders/1j2abzmSXfHtPKkUQ7lkFir6pHgP8KVYx): Link to the Drive where Design Principle artifacts live/will live

### Acceptance criteria (We'll know we're done when...)
- [ ] The FAC has design principles!
- [ ] The design + product team have agreed and signed off
- [ ] The whole team knows about 'em
- [ ] They are documented publicly 
  
### Tasks

- [x] Compete
- [x] Peer review
- [x] Implement
- [x] Share with team
- [ ] Document
