### ISSUE TITLE
Design - Data disem research spike with Audit Resolution Officials

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#931]
This issue covers the design research interview spike with Audit Resolution Officials.

### Background

We are interviewing AARO (agency audit resolution officials) to learn more about how they use the data dissemination side of the FAC. 

### Acceptance criteria (We'll know we're done when...)

- [ ] Interviews have been completed producing feedback for synthesis 
  
### Tasks

- [x] Compose interview solicitation email
- [x] Identify and email potential recruits 
- [x] Write and revise interview script
- [x] Create zoom sessions for all scheduled sessions, update gcal invites 
- [x] Confirm scheduled interviews via email, include participation consent form, questions and zoom link
- [x] Coordinate note takers and observers
- [x] Conduct interviews 

### Definition of Done

- [x] All interviews have been completed and feedback is compiled for synthesis

**Comment by jadudm** [comment]
Adding this to search (post-MVP).

**Comment by Leighdiddy** [comment]
Final synthesis/summary: https://docs.google.com/presentation/d/1e1iEZ3w_-nSliJaRB1ErVEKqCK7AUhGWs1fmZtnPDqo/edit?usp=sharing
