### ISSUE TITLE
FAC System Diagram design

### ISSUE THREAD

**Issue by ChrisB-16** [GSA-TTS/FAC#944]
### Tasks

`Design draft FAC diagram to outline ATO boundary & cloud services from external systems
- [x] Gain access to Lucid charts-convert current diagram
- [x] insert technical details from Development huddle notes- JeanMarie
- [x] Track requirements from Security Architecture Review Checklist (ISSM/ISSO )
- [ ] perform review session with System Owner on draft before team release for review cycle
```

**Comment by ChrisB-16** [comment]
Actions are in progress

**Comment by ChrisB-16** [comment]
New FAC ATO Boundary diagram draft ready for review: _FAC Cloud ATO high-level systems overview v1_

 https://github.com/GSA-TTS/FAC/tree/jm/Context_with_AV_and_PostgREST/docs/architecture/diagrams

Please feel free to provide comments for updates needed.

Regards,

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 , I update the puml file to include the proxy services.

**Comment by JeanMarie-TTS** [comment]
@mogul , I copied the pull file into an md file with a mermaid tag. But cannot get the diagram to render.

**Comment by mogul** [comment]
I made a couple commits showing the problems. See these lines in particular:
https://github.com/GSA-TTS/FAC/commit/5556cf51d689541deae6cc5573a7d95114675034#diff-d6179519cc87ef13a90c45e9f71d3210ed203cb8ecde76b1734cc49dff87e0fcR56-R60

We should check if relationships with boundaries are supposed to be possible in C4-PlantUML... If not, then we should fix that in our diagram. Otherwise, given the state of Mermaid's support for C4, it may be a good example to [point out a bug to them in the issue where this support is being discussed](https://github.com/mermaid-js/mermaid/issues/1276).
