### ISSUE TITLE
Allow user to edit `user_provided_organization_type`

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#949]
### Background

The pre-SAC steps allow the user to select from some options to enter what type of organization they’re submitting an audit for. This gets stored as `user_provided_organization_type`. However, we don’t have any way for them to change it later in the process, and it’s not possible to go back to the pre-SAC form for a submission that’s already in progress. Since it’s entirely possible for users to be wrong about the answer, we may need some way to edit this; the simplest way to do it is probably to add the field to General Information and populate it.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We’ve decided that adding the field to General Information is the correct way to handle this.
- [ ]   The General Information section has this field.

### Tasks

- [ ]   Decide whether to do this at all.
- [ ]   Decide whether General Information is the right place for it.
- [ ]   Add it to General Information or close this issue.

**Comment by JeanMarie-TTS** [comment]
@jadudm  - a couple of product functionality questions related to the one on this ticket...

1. What is the reason that a user cannot go back to the pre-SAC pages to modify what was previously entered?.
2. Besides org type, there are other fields in the pre-SAC that are persisted - like email addresses. Is there a way for users to modify them?

**Comment by jadudm** [comment]
We most likely need to provide a way for users to delete/cancel an audit in progress and start over. Or, break the UEI out from the rest of the pre-screener. Either way, closing as not planned until we decide how we will handle this in general.
