### ISSUE TITLE
Onboarding checklist for @brentryanjohnson

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#95]
### Welcome to the team  @brentryanjohnson!

Here's a few pointers to get you started as well as a checklist to make sure you've got access to :all-the-things:!

**For you**
- [x] [Join](https://github.com/GSA/GitHub-Administration#joining-the-gsa-enterprise-organization) GSA’s Enterprise Github org
- [x] Review the [project README](https://docs.google.com/document/d/1g8nYqYS_ifFlZB-DBgfeSoJRMB__EqWsmLnacyk-bDI/) in drive
- [x] Join Slack channels in the project README

@jadudm will be your onboarding buddy and will tackle the list below!

**For your onboarding buddy**
- [x] Add to the FAC team folder in drive
- [x] Add to [FAC@GSA.gov](https://groups.google.com/a/gsa.gov/g/fac) google group
- [x] <Engineering> Added to `gsa-10x-prototyping` Organization in cloud.gov
- [x] Add to the [FAC team](https://github.com/orgs/GSA-TTS/teams/fac-team) in github
- [x] Add to standing meeting invites
