### ISSUE TITLE
Epic: Certification workflow

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#970]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

A **certifying team** is the group of people working on a submission. At the least, it involves an auditee and a certifying official on the audit side. There may be more; they would likely be other members of the grant team and/or the auditing house working on the audit. We are primarily concerned with the auditee and certifying official.

**In order to** certify the FAC
**as a** certifying team
**I want** to have a defined, step-wise process to add each certification and complete the SF-SAC workflow.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: The dev team is eager to implement the certification workflow.

**Given**  a reworked set of certification mocks
**when**  the engineering team is ready to build
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] design has reworked the certification workflow as a lockstep process
- [ ] content has reviewed text for the certification workflow
- [ ] the revised designs have been shared with SMEs, with tentative approval until more extensive user testing is possible
```

### Scenario: A team has completed uploads, and is ready to certify/complete their audit submission process.

**Given**  a completed set of uploads for the SF-SAC
**when**  the certifying team is ready to certify
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [ ] https://github.com/GSA-TTS/FAC/issues/1449
- [ ] https://github.com/GSA-TTS/FAC/issues/1450
- [ ] https://github.com/GSA-TTS/FAC/issues/1451
- [ ] https://github.com/GSA-TTS/FAC/issues/985
- [x] State changes, where applicable, are only permitted for users with the appropriate user roles.
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: @Leighdiddy 
* Engineering shepherd: @tadhg-ohiggins 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

Issue https://github.com/GSA-TTS/FAC/issues/539 is relevant in terms of design and prior art.

We've decided that the workflow for certification will proceed lockstep. Working doc for that discussion/decision (to become a PDR) is linked/screen-capped below.

[https://docs.google.com/document/d/1j9uCcbxiaHiqVOQObw5fq8mk91WCeJQ07SsOpnkpvDI/edit](https://docs.google.com/document/d/1j9uCcbxiaHiqVOQObw5fq8mk91WCeJQ07SsOpnkpvDI/edit)

![image](https://user-images.githubusercontent.com/38290/230920627-ccc8881f-5e20-413d-9f57-a8f4c8a5ae4b.png)
 
# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no security concerns to the change in certification process. By locking the SF-SAC at the start of this workflow, we eliminate a number of complex logic operations in the backend, and by simplifying our software and user process, arguably make it safer.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design is discussed with stakeholders by PO
- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
Note to self: add 

https://github.com/GSA-TTS/FAC/issues/536

to this ticket as either "tracked by" or as part of the background. Noting here so I can come back to it. Answers questions about "My Audits" and workflow.

**Comment by jadudm** [comment]
I believe we've already discussed these things, but I'm adding a comment here for completeness/transparency.

Assuming we get to a point where all the pieces are uploaded, we'll find ourselves here as an auditor or auditee:

![image](https://user-images.githubusercontent.com/38290/236247802-19beb3e3-2b55-4ddb-8a2a-d44b56de6d57.png)

If I am logged in as Annie Auditor, I will see this:

![image](https://user-images.githubusercontent.com/38290/236247898-aff0f50b-8fd9-4675-b8e2-e2401db38822.png)

Once I do the certification workflow, I will be brought back to this page, and see that I am done, but can do nothing else:

![image](https://user-images.githubusercontent.com/38290/236248001-0f08bbe8-0393-4bc1-b6f2-6a1b8f493f67.png)

If I am Gabby Grantee, however, I can log in and get the landing page for the workflow:

![image](https://user-images.githubusercontent.com/38290/236248164-c281267f-eb46-4083-826d-5546418bb737.png)

I will see the auditor step done, and can now start my cert. After I'm done with the cert step, I come back here:

![image](https://user-images.githubusercontent.com/38290/236248431-787a27b9-48bb-42fc-bf5c-9d8f26e6b0ef.png)

and, that should be it. That is, I can choose to go to do my final submission step.

**Comment by jadudm** [comment]
Note, some of the details of the text are not correct in the _detail_ of those screen grabs, but the workflow is. The Figma should be more up-to-date/corrected.

**Comment by jadudm** [comment]
Closing as done. This has been moved into `main` and demoed.

**Comment by mogul** [comment]
Reopening as the front-end work is still in progress and not yet merged.

**Comment by jadudm** [comment]
Re-ticketing the frontend and revised pieces in #1495.
