### ISSUE TITLE
The backend uses a finite state machine to track states for the workflow.

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#985]
Breakout issue of https://github.com/GSA-TTS/FAC/issues/970.

### Background

We need a way on the backend to track status changes for submissions. We will try [`django-fsm`](https://github.com/viewflow/django-fsm/) but will abandon it and write custom code ourselves if it turns out to be trickier than it appears. Research so far suggests that it should suffice for the use cases we have.

This ticket covers adding a `state` (or `status`) field to the `SingleAuditChecklist` model, using `django-fsm` to manage that field, and using `django-fsm` to handle transitions between states.

This issue covers basic state machine support only; any more advanced tweaks or requirements (such as automatically reverting the state back to “in progress” from “certified” if any submission data fields are altered) will be covered in separate issues.

### Acceptance Criteria (We'll know we're done when...)

- [x]   `SingleAuditChecklist` has a `submission_status` field managed by `django-fsm`.
- [x]   We have a basic list of states.
- [x]   We’re managing the basic state transitions.

### Tasks

- [x]   Add `django-fsm` to the project requirements.
- [x]   Add basic state transition handling using `django-fsm`.
- [x]   Write tests for those transitions.
